import type { FlavorLabel } from './types'

export const agilityLabels: FlavorLabel[] = [
  // F- (score: 2)
  { label: 'Trips on Flat Surfaces', weight: 1, tier: 'F-', score: 2, color: 'var(--tier-f-minus)' },
  { label: 'Lost a Dance-Off to a Filing Cabinet', weight: 1, tier: 'F-', score: 2, color: 'var(--tier-f-minus)' },
  { label: 'Falls Getting Out of Chairs', weight: 1, tier: 'F-', score: 2, color: 'var(--tier-f-minus)' },
  { label: 'Dodges Nothing Successfully', weight: 1, tier: 'F-', score: 2, color: 'var(--tier-f-minus)' },
  { label: 'Stumbles on Memories', weight: 1, tier: 'F-', score: 2, color: 'var(--tier-f-minus)' },
  { label: 'Can\'t Dodge a Slow Blink', weight: 1, tier: 'F-', score: 2, color: 'var(--tier-f-minus)' },
  { label: 'Coordination: Missing', weight: 1, tier: 'F-', score: 2, color: 'var(--tier-f-minus)' },
  { label: 'Fell Attempting to Stand Still', weight: 1, tier: 'F-', score: 2, color: 'var(--tier-f-minus)' },
  { label: 'Can\'t Touch Their Own Face Reliably', weight: 1, tier: 'F-', score: 2, color: 'var(--tier-f-minus)' },
  { label: 'Balance: Optional', weight: 1, tier: 'F-', score: 2, color: 'var(--tier-f-minus)' },
  { label: 'Gets Tangled Walking', weight: 1, tier: 'F-', score: 2, color: 'var(--tier-f-minus)' },
  { label: 'Arms Go One Way, Legs the Other', weight: 1, tier: 'F-', score: 2, color: 'var(--tier-f-minus)' },
  { label: 'Rolled Ankle Standing Still', weight: 1, tier: 'F-', score: 2, color: 'var(--tier-f-minus)' },
  { label: 'Graceful as Wet Cardboard', weight: 1, tier: 'F-', score: 2, color: 'var(--tier-f-minus)' },
  { label: 'Navigates Furniture as Obstacles', weight: 1, tier: 'F-', score: 2, color: 'var(--tier-f-minus)' },
  { label: 'Dodging: Theoretical', weight: 1, tier: 'F-', score: 2, color: 'var(--tier-f-minus)' },
  { label: 'Corners Are Nemeses', weight: 1, tier: 'F-', score: 2, color: 'var(--tier-f-minus)' },
  { label: 'Trips Over Painted Lines', weight: 1, tier: 'F-', score: 2, color: 'var(--tier-f-minus)' },
  { label: 'Body Disagrees on Direction', weight: 1, tier: 'F-', score: 2, color: 'var(--tier-f-minus)' },
  { label: 'Limbs File Separate Itineraries', weight: 1, tier: 'F-', score: 2, color: 'var(--tier-f-minus)' },

  // F (score: 5)
  { label: 'Stumbles Occasionally', weight: 1, tier: 'F', score: 5, color: 'var(--tier-f)' },
  { label: 'Basic Balance Only', weight: 1, tier: 'F', score: 5, color: 'var(--tier-f)' },
  { label: 'Cannot Dodge a Door Swinging Open', weight: 1, tier: 'F', score: 5, color: 'var(--tier-f)' },
  { label: 'Walks Into Clear Glass Doors', weight: 1, tier: 'F', score: 5, color: 'var(--tier-f)' },
  { label: 'Limbs Arrive in Sequence, Not Unison', weight: 1, tier: 'F', score: 5, color: 'var(--tier-f)' },
  { label: 'Coordination: Below Par', weight: 1, tier: 'F', score: 5, color: 'var(--tier-f)' },
  { label: 'Graceful Occasionally (By Accident)', weight: 1, tier: 'F', score: 5, color: 'var(--tier-f)' },
  { label: 'Takes Wide Turns', weight: 1, tier: 'F', score: 5, color: 'var(--tier-f)' },
  { label: 'Knocks Things Over While Trying to Catch Them', weight: 1, tier: 'F', score: 5, color: 'var(--tier-f)' },
  { label: 'Movement Path: Unpredictable', weight: 1, tier: 'F', score: 5, color: 'var(--tier-f)' },
  { label: 'Trips Up Stairs and Down', weight: 1, tier: 'F', score: 5, color: 'var(--tier-f)' },
  { label: 'Dodges Into Things', weight: 1, tier: 'F', score: 5, color: 'var(--tier-f)' },
  { label: 'Reactions Arrive Late', weight: 1, tier: 'F', score: 5, color: 'var(--tier-f)' },
  { label: 'Wobbles on Smooth Floors', weight: 1, tier: 'F', score: 5, color: 'var(--tier-f)' },
  { label: 'Caught Themselves Last Minute Once', weight: 1, tier: 'F', score: 5, color: 'var(--tier-f)' },
  { label: 'Balance: Renting Month-to-Month', weight: 1, tier: 'F', score: 5, color: 'var(--tier-f)' },
  { label: 'Reflexes Are More Suggestions', weight: 1, tier: 'F', score: 5, color: 'var(--tier-f)' },
  { label: 'Sidesteps Are Actually Just Steps', weight: 1, tier: 'F', score: 5, color: 'var(--tier-f)' },
  { label: 'Ducks Too Late', weight: 1, tier: 'F', score: 5, color: 'var(--tier-f)' },
  { label: 'Has a Reliable Bruise Collection', weight: 1, tier: 'F', score: 5, color: 'var(--tier-f)' },

  // F+ (score: 8)
  { label: 'Clumsy but Upright', weight: 1, tier: 'F+', score: 8, color: 'var(--tier-f-plus)' },
  { label: 'Stays on Their Feet Mostly', weight: 1, tier: 'F+', score: 8, color: 'var(--tier-f-plus)' },
  { label: 'Dodges Slow Objects', weight: 1, tier: 'F+', score: 8, color: 'var(--tier-f-plus)' },
  { label: 'Navigates Stairs Without Incident', weight: 1, tier: 'F+', score: 8, color: 'var(--tier-f-plus)' },
  { label: 'Arms and Legs Occasionally Agree', weight: 1, tier: 'F+', score: 8, color: 'var(--tier-f-plus)' },
  { label: 'Turns Corners Without Hitting Them', weight: 1, tier: 'F+', score: 8, color: 'var(--tier-f-plus)' },
  { label: 'Below Average Dexterity', weight: 1, tier: 'F+', score: 8, color: 'var(--tier-f-plus)' },
  { label: 'Balance: Maintained Under Protest', weight: 1, tier: 'F+', score: 8, color: 'var(--tier-f-plus)' },
  { label: 'Reflexes: Occasionally on Time', weight: 1, tier: 'F+', score: 8, color: 'var(--tier-f-plus)' },
  { label: 'Catches Things (Dropped First)', weight: 1, tier: 'F+', score: 8, color: 'var(--tier-f-plus)' },
  { label: 'Modest But Present Coordination', weight: 1, tier: 'F+', score: 8, color: 'var(--tier-f-plus)' },
  { label: 'Can Thread a Doorway Adequately', weight: 1, tier: 'F+', score: 8, color: 'var(--tier-f-plus)' },
  { label: 'Navigates Furniture with Minor Bruising', weight: 1, tier: 'F+', score: 8, color: 'var(--tier-f-plus)' },
  { label: 'Sidesteps Work Occasionally', weight: 1, tier: 'F+', score: 8, color: 'var(--tier-f-plus)' },
  { label: 'Falls Down Rarely', weight: 1, tier: 'F+', score: 8, color: 'var(--tier-f-plus)' },
  { label: 'Dexterity: Functional', weight: 1, tier: 'F+', score: 8, color: 'var(--tier-f-plus)' },
  { label: 'Catches Slow Throws', weight: 1, tier: 'F+', score: 8, color: 'var(--tier-f-plus)' },
  { label: 'Ducking Works When Anticipated', weight: 1, tier: 'F+', score: 8, color: 'var(--tier-f-plus)' },
  { label: 'Moderate Limb Discipline', weight: 1, tier: 'F+', score: 8, color: 'var(--tier-f-plus)' },
  { label: 'Gets Out of the Way Eventually', weight: 1, tier: 'F+', score: 8, color: 'var(--tier-f-plus)' },

  // E- (score: 11)
  { label: 'Functional Coordination', weight: 1, tier: 'E-', score: 11, color: 'var(--tier-e-minus)' },
  { label: 'Decent Reflexes', weight: 1, tier: 'E-', score: 11, color: 'var(--tier-e-minus)' },
  { label: 'Catches Most Throws', weight: 1, tier: 'E-', score: 11, color: 'var(--tier-e-minus)' },
  { label: 'Navigates Crowds with Skill', weight: 1, tier: 'E-', score: 11, color: 'var(--tier-e-minus)' },
  { label: 'Dodges Things Casually', weight: 1, tier: 'E-', score: 11, color: 'var(--tier-e-minus)' },
  { label: 'Stays on Their Feet on Uneven Ground', weight: 1, tier: 'E-', score: 11, color: 'var(--tier-e-minus)' },
  { label: 'Good Spatial Awareness', weight: 1, tier: 'E-', score: 11, color: 'var(--tier-e-minus)' },
  { label: 'Light Footwork', weight: 1, tier: 'E-', score: 11, color: 'var(--tier-e-minus)' },
  { label: 'Ducks Under Things Cleanly', weight: 1, tier: 'E-', score: 11, color: 'var(--tier-e-minus)' },
  { label: 'Reactions: Reasonably Timed', weight: 1, tier: 'E-', score: 11, color: 'var(--tier-e-minus)' },
  { label: 'Moves Through Small Spaces', weight: 1, tier: 'E-', score: 11, color: 'var(--tier-e-minus)' },
  { label: 'Can Sidestep Without Planning', weight: 1, tier: 'E-', score: 11, color: 'var(--tier-e-minus)' },
  { label: 'Comfortable at Height', weight: 1, tier: 'E-', score: 11, color: 'var(--tier-e-minus)' },
  { label: 'Balance: Reliable', weight: 1, tier: 'E-', score: 11, color: 'var(--tier-e-minus)' },
  { label: 'Quick Recovery from Stumbles', weight: 1, tier: 'E-', score: 11, color: 'var(--tier-e-minus)' },
  { label: 'Moves Precisely Under Pressure', weight: 1, tier: 'E-', score: 11, color: 'var(--tier-e-minus)' },
  { label: 'Dexterous Hands', weight: 1, tier: 'E-', score: 11, color: 'var(--tier-e-minus)' },
  { label: 'Limbs Go Where Intended', weight: 1, tier: 'E-', score: 11, color: 'var(--tier-e-minus)' },
  { label: 'Agile Enough to Not be the Problem', weight: 1, tier: 'E-', score: 11, color: 'var(--tier-e-minus)' },
  { label: 'Capable Mover', weight: 1, tier: 'E-', score: 11, color: 'var(--tier-e-minus)' },

  // E (score: 14)
  { label: 'Average Human Agility', weight: 1, tier: 'E', score: 14, color: 'var(--tier-e)' },
  { label: 'Solid Reflexes', weight: 1, tier: 'E', score: 14, color: 'var(--tier-e)' },
  { label: 'Dodges Most Things', weight: 1, tier: 'E', score: 14, color: 'var(--tier-e)' },
  { label: 'Good Balance', weight: 1, tier: 'E', score: 14, color: 'var(--tier-e)' },
  { label: 'Moves with Natural Ease', weight: 1, tier: 'E', score: 14, color: 'var(--tier-e)' },
  { label: 'Quick to Adjust', weight: 1, tier: 'E', score: 14, color: 'var(--tier-e)' },
  { label: 'Can Dance Adequately', weight: 1, tier: 'E', score: 14, color: 'var(--tier-e)' },
  { label: 'Handles Unstable Surfaces', weight: 1, tier: 'E', score: 14, color: 'var(--tier-e)' },
  { label: 'Reactions Match Stimulus', weight: 1, tier: 'E', score: 14, color: 'var(--tier-e)' },
  { label: 'Limb Control: Present', weight: 1, tier: 'E', score: 14, color: 'var(--tier-e)' },
  { label: 'Catches Fast Throws', weight: 1, tier: 'E', score: 14, color: 'var(--tier-e)' },
  { label: 'Runs Without Incident', weight: 1, tier: 'E', score: 14, color: 'var(--tier-e)' },
  { label: 'Navigates Narrow Passages', weight: 1, tier: 'E', score: 14, color: 'var(--tier-e)' },
  { label: 'Foot Placement Intentional', weight: 1, tier: 'E', score: 14, color: 'var(--tier-e)' },
  { label: 'Rolls Out of Falls', weight: 1, tier: 'E', score: 14, color: 'var(--tier-e)' },
  { label: 'Normal Dexterity', weight: 1, tier: 'E', score: 14, color: 'var(--tier-e)' },
  { label: 'Keeps Rhythm', weight: 1, tier: 'E', score: 14, color: 'var(--tier-e)' },
  { label: 'Changes Direction Cleanly', weight: 1, tier: 'E', score: 14, color: 'var(--tier-e)' },
  { label: 'Functional Movement at Speed', weight: 1, tier: 'E', score: 14, color: 'var(--tier-e)' },
  { label: 'Body Goes Where Told', weight: 1, tier: 'E', score: 14, color: 'var(--tier-e)' },

  // E+ (score: 17)
  { label: 'Athletic Agility', weight: 1, tier: 'E+', score: 17, color: 'var(--tier-e-plus)' },
  { label: 'Quick Direction Changes', weight: 1, tier: 'E+', score: 17, color: 'var(--tier-e-plus)' },
  { label: 'Fluid Movement', weight: 1, tier: 'E+', score: 17, color: 'var(--tier-e-plus)' },
  { label: 'Can Dodge Moving Objects', weight: 1, tier: 'E+', score: 17, color: 'var(--tier-e-plus)' },
  { label: 'Graceful Under Pressure', weight: 1, tier: 'E+', score: 17, color: 'var(--tier-e-plus)' },
  { label: 'Instinctive Evasion', weight: 1, tier: 'E+', score: 17, color: 'var(--tier-e-plus)' },
  { label: 'Light on Their Feet', weight: 1, tier: 'E+', score: 17, color: 'var(--tier-e-plus)' },
  { label: 'Precision Footwork', weight: 1, tier: 'E+', score: 17, color: 'var(--tier-e-plus)' },
  { label: 'Above Average Reflexes', weight: 1, tier: 'E+', score: 17, color: 'var(--tier-e-plus)' },
  { label: 'Parkour Curious', weight: 1, tier: 'E+', score: 17, color: 'var(--tier-e-plus)' },
  { label: 'Can Roll Into Any Fall', weight: 1, tier: 'E+', score: 17, color: 'var(--tier-e-plus)' },
  { label: 'Nimble Hands and Feet', weight: 1, tier: 'E+', score: 17, color: 'var(--tier-e-plus)' },
  { label: 'Reads Environment Quickly', weight: 1, tier: 'E+', score: 17, color: 'var(--tier-e-plus)' },
  { label: 'Dodge Success Rate: High', weight: 1, tier: 'E+', score: 17, color: 'var(--tier-e-plus)' },
  { label: 'Moves Through Chaos Smoothly', weight: 1, tier: 'E+', score: 17, color: 'var(--tier-e-plus)' },
  { label: 'Dances Around Obstacles', weight: 1, tier: 'E+', score: 17, color: 'var(--tier-e-plus)' },
  { label: 'Controlled Balance at Speed', weight: 1, tier: 'E+', score: 17, color: 'var(--tier-e-plus)' },
  { label: 'Three-Point Landing: Standard', weight: 1, tier: 'E+', score: 17, color: 'var(--tier-e-plus)' },
  { label: 'Movement Economy: Efficient', weight: 1, tier: 'E+', score: 17, color: 'var(--tier-e-plus)' },
  { label: 'Appears to Float', weight: 1, tier: 'E+', score: 17, color: 'var(--tier-e-plus)' },

  // D- (score: 20)
  { label: 'Acrobatic Baseline', weight: 1, tier: 'D-', score: 20, color: 'var(--tier-d-minus)' },
  { label: 'Parkour Capable', weight: 1, tier: 'D-', score: 20, color: 'var(--tier-d-minus)' },
  { label: 'Gym Gymnast Level', weight: 1, tier: 'D-', score: 20, color: 'var(--tier-d-minus)' },
  { label: 'Combat Roll as Default', weight: 1, tier: 'D-', score: 20, color: 'var(--tier-d-minus)' },
  { label: 'Walls Are Surfaces to Run On', weight: 1, tier: 'D-', score: 20, color: 'var(--tier-d-minus)' },
  { label: 'Can Dodge Multiple Attackers', weight: 1, tier: 'D-', score: 20, color: 'var(--tier-d-minus)' },
  { label: 'Backflips Are Casual', weight: 1, tier: 'D-', score: 20, color: 'var(--tier-d-minus)' },
  { label: 'Cat-Like Landing', weight: 1, tier: 'D-', score: 20, color: 'var(--tier-d-minus)' },
  { label: 'Reaction Time: Below 200ms', weight: 1, tier: 'D-', score: 20, color: 'var(--tier-d-minus)' },
  { label: 'Flows Through Environments', weight: 1, tier: 'D-', score: 20, color: 'var(--tier-d-minus)' },
  { label: 'Impossible Angles on Turns', weight: 1, tier: 'D-', score: 20, color: 'var(--tier-d-minus)' },
  { label: 'Can Spin in the Air', weight: 1, tier: 'D-', score: 20, color: 'var(--tier-d-minus)' },
  { label: 'Never Breaks Stride', weight: 1, tier: 'D-', score: 20, color: 'var(--tier-d-minus)' },
  { label: 'Zero Wasted Movement', weight: 1, tier: 'D-', score: 20, color: 'var(--tier-d-minus)' },
  { label: 'Gravity Is a Mild Suggestion', weight: 1, tier: 'D-', score: 20, color: 'var(--tier-d-minus)' },
  { label: 'Precision Acrobatics', weight: 1, tier: 'D-', score: 20, color: 'var(--tier-d-minus)' },
  { label: 'Handstands: Casual Resting Pose', weight: 1, tier: 'D-', score: 20, color: 'var(--tier-d-minus)' },
  { label: 'Dodges Faster Than Eyes Can Track', weight: 1, tier: 'D-', score: 20, color: 'var(--tier-d-minus)' },
  { label: 'Runs at Impossible Angles', weight: 1, tier: 'D-', score: 20, color: 'var(--tier-d-minus)' },
  { label: 'Moves Like Water', weight: 1, tier: 'D-', score: 20, color: 'var(--tier-d-minus)' },

  // D (score: 23)
  { label: 'Superhuman Agility', weight: 1, tier: 'D', score: 23, color: 'var(--tier-d)' },
  { label: 'Defies Basic Physics', weight: 1, tier: 'D', score: 23, color: 'var(--tier-d)' },
  { label: 'Can Dodge Projectiles', weight: 1, tier: 'D', score: 23, color: 'var(--tier-d)' },
  { label: 'Runs Vertically', weight: 1, tier: 'D', score: 23, color: 'var(--tier-d)' },
  { label: 'Friction Optional', weight: 1, tier: 'D', score: 23, color: 'var(--tier-d)' },
  { label: 'Bends Mid-Sprint', weight: 1, tier: 'D', score: 23, color: 'var(--tier-d)' },
  { label: 'Triple-Axis Spinning', weight: 1, tier: 'D', score: 23, color: 'var(--tier-d)' },
  { label: 'Changes Direction Mid-Air', weight: 1, tier: 'D', score: 23, color: 'var(--tier-d)' },
  { label: 'Moves Between Raindrops', weight: 1, tier: 'D', score: 23, color: 'var(--tier-d)' },
  { label: 'Reaction Time: Instantaneous', weight: 1, tier: 'D', score: 23, color: 'var(--tier-d)' },
  { label: 'Impossible Trajectories as Default', weight: 1, tier: 'D', score: 23, color: 'var(--tier-d)' },
  { label: 'Air Is a Surface', weight: 1, tier: 'D', score: 23, color: 'var(--tier-d)' },
  { label: 'Dodges Arrows Casually', weight: 1, tier: 'D', score: 23, color: 'var(--tier-d)' },
  { label: 'Runs on Water Accidentally', weight: 1, tier: 'D', score: 23, color: 'var(--tier-d)' },
  { label: 'Cartwheels Are Combat Maneuvers', weight: 1, tier: 'D', score: 23, color: 'var(--tier-d)' },
  { label: 'Can Dodge Without Looking', weight: 1, tier: 'D', score: 23, color: 'var(--tier-d)' },
  { label: 'Performs Zero-G Feats at Sea Level', weight: 1, tier: 'D', score: 23, color: 'var(--tier-d)' },
  { label: 'Moves Like a Living Exception', weight: 1, tier: 'D', score: 23, color: 'var(--tier-d)' },
  { label: 'Physics Is Advisory', weight: 1, tier: 'D', score: 23, color: 'var(--tier-d)' },
  { label: 'Impossible Pivot Speed', weight: 1, tier: 'D', score: 23, color: 'var(--tier-d)' },

  // D+ (score: 26)
  { label: 'Gravitational Independence', weight: 1, tier: 'D+', score: 26, color: 'var(--tier-d-plus)' },
  { label: 'Moves Like Smoke', weight: 1, tier: 'D+', score: 26, color: 'var(--tier-d-plus)' },
  { label: 'Bullets Part Around Them', weight: 1, tier: 'D+', score: 26, color: 'var(--tier-d-plus)' },
  { label: 'Can Occupy Two Positions Sequentially', weight: 1, tier: 'D+', score: 26, color: 'var(--tier-d-plus)' },
  { label: 'Bends Around Attacks', weight: 1, tier: 'D+', score: 26, color: 'var(--tier-d-plus)' },
  { label: 'Moves in Impossible Curves', weight: 1, tier: 'D+', score: 26, color: 'var(--tier-d-plus)' },
  { label: 'Perceives Threats Before They Form', weight: 1, tier: 'D+', score: 26, color: 'var(--tier-d-plus)' },
  { label: 'Runs on Clouds (Probably)', weight: 1, tier: 'D+', score: 26, color: 'var(--tier-d-plus)' },
  { label: 'Martial Arts Defies Logic', weight: 1, tier: 'D+', score: 26, color: 'var(--tier-d-plus)' },
  { label: 'Dodges Faster Than Possible', weight: 1, tier: 'D+', score: 26, color: 'var(--tier-d-plus)' },
  { label: 'Position Unclear on Any Axis', weight: 1, tier: 'D+', score: 26, color: 'var(--tier-d-plus)' },
  { label: 'Momentum Is Optional', weight: 1, tier: 'D+', score: 26, color: 'var(--tier-d-plus)' },
  { label: 'Flows Through Solid Objects (Barely)', weight: 1, tier: 'D+', score: 26, color: 'var(--tier-d-plus)' },
  { label: 'Every Movement Is Impossible', weight: 1, tier: 'D+', score: 26, color: 'var(--tier-d-plus)' },
  { label: 'Changes Vector Without Deceleration', weight: 1, tier: 'D+', score: 26, color: 'var(--tier-d-plus)' },
  { label: 'Moves in Negative Space', weight: 1, tier: 'D+', score: 26, color: 'var(--tier-d-plus)' },
  { label: 'Reflexes Predate Stimulus', weight: 1, tier: 'D+', score: 26, color: 'var(--tier-d-plus)' },
  { label: 'Can Dodge Before Attack Begins', weight: 1, tier: 'D+', score: 26, color: 'var(--tier-d-plus)' },
  { label: 'Spatial Awareness: Omnidirectional', weight: 1, tier: 'D+', score: 26, color: 'var(--tier-d-plus)' },
  { label: 'Exists in Multiple Positions Briefly', weight: 1, tier: 'D+', score: 26, color: 'var(--tier-d-plus)' },

  // C- (score: 30)
  { label: 'Quantum Dodge', weight: 1, tier: 'C-', score: 30, color: 'var(--tier-c-minus)' },
  { label: 'Moves Between Dimensions', weight: 1, tier: 'C-', score: 30, color: 'var(--tier-c-minus)' },
  { label: 'Exists in Superposition', weight: 1, tier: 'C-', score: 30, color: 'var(--tier-c-minus)' },
  { label: 'Physics Gave Up Tracking', weight: 1, tier: 'C-', score: 30, color: 'var(--tier-c-minus)' },
  { label: 'Can Dodge Thoughts', weight: 1, tier: 'C-', score: 30, color: 'var(--tier-c-minus)' },
  { label: 'Position: All of Them', weight: 1, tier: 'C-', score: 30, color: 'var(--tier-c-minus)' },
  { label: 'Dodges Laser Beams', weight: 1, tier: 'C-', score: 30, color: 'var(--tier-c-minus)' },
  { label: 'Steps Through Solid Objects', weight: 1, tier: 'C-', score: 30, color: 'var(--tier-c-minus)' },
  { label: 'Gravity: An Old Friend, Not a Constraint', weight: 1, tier: 'C-', score: 30, color: 'var(--tier-c-minus)' },
  { label: 'Three-Dimensional Movement on Two', weight: 1, tier: 'C-', score: 30, color: 'var(--tier-c-minus)' },
  { label: 'Occupies All Positions at Once', weight: 1, tier: 'C-', score: 30, color: 'var(--tier-c-minus)' },
  { label: 'Can Dodge What Doesn\'t Exist Yet', weight: 1, tier: 'C-', score: 30, color: 'var(--tier-c-minus)' },
  { label: 'Movement Has Become Abstract', weight: 1, tier: 'C-', score: 30, color: 'var(--tier-c-minus)' },
  { label: 'Bends Existence to Avoid Attack', weight: 1, tier: 'C-', score: 30, color: 'var(--tier-c-minus)' },
  { label: 'Can Sidestep Probability', weight: 1, tier: 'C-', score: 30, color: 'var(--tier-c-minus)' },
  { label: 'Nimbler Than Thought', weight: 1, tier: 'C-', score: 30, color: 'var(--tier-c-minus)' },
  { label: 'Spatial Laws Don\'t Quite Apply', weight: 1, tier: 'C-', score: 30, color: 'var(--tier-c-minus)' },
  { label: 'Evasion That Rewrites Trajectory', weight: 1, tier: 'C-', score: 30, color: 'var(--tier-c-minus)' },
  { label: 'Moves Like Intention Made Solid', weight: 1, tier: 'C-', score: 30, color: 'var(--tier-c-minus)' },
  { label: 'Every Step Defies Geometry', weight: 1, tier: 'C-', score: 30, color: 'var(--tier-c-minus)' },

  // C (score: 34)
  { label: 'Dimensional Maneuvering', weight: 1, tier: 'C', score: 34, color: 'var(--tier-c)' },
  { label: 'Dodges Photons', weight: 1, tier: 'C', score: 34, color: 'var(--tier-c)' },
  { label: 'Exists in All Positions Simultaneously', weight: 1, tier: 'C', score: 34, color: 'var(--tier-c)' },
  { label: 'Movement Predates Causality', weight: 1, tier: 'C', score: 34, color: 'var(--tier-c)' },
  { label: 'Bends Spacetime to Avoid Hits', weight: 1, tier: 'C', score: 34, color: 'var(--tier-c)' },
  { label: 'Every Move Is Geometrically Impossible', weight: 1, tier: 'C', score: 34, color: 'var(--tier-c)' },
  { label: 'Can Sidestep Time', weight: 1, tier: 'C', score: 34, color: 'var(--tier-c)' },
  { label: 'Occupies Non-Euclidean Space Comfortably', weight: 1, tier: 'C', score: 34, color: 'var(--tier-c)' },
  { label: 'Reflexes Faster Than Reality Updates', weight: 1, tier: 'C', score: 34, color: 'var(--tier-c)' },
  { label: 'Avoids Being Hit by Not Existing Where Hits Land', weight: 1, tier: 'C', score: 34, color: 'var(--tier-c)' },
  { label: 'Can Duck Under Concept Attacks', weight: 1, tier: 'C', score: 34, color: 'var(--tier-c)' },
  { label: 'Movement Loops Through Dimensions', weight: 1, tier: 'C', score: 34, color: 'var(--tier-c)' },
  { label: 'Impossible is Just a Slower Route', weight: 1, tier: 'C', score: 34, color: 'var(--tier-c)' },
  { label: 'Runs Through Non-Space', weight: 1, tier: 'C', score: 34, color: 'var(--tier-c)' },
  { label: 'Existence Cannot Contain Their Movement', weight: 1, tier: 'C', score: 34, color: 'var(--tier-c)' },
  { label: 'Spatial Reality Politely Steps Aside', weight: 1, tier: 'C', score: 34, color: 'var(--tier-c)' },
  { label: 'Reaction: Pre-Conscious', weight: 1, tier: 'C', score: 34, color: 'var(--tier-c)' },
  { label: 'Occupies Theoretical Space', weight: 1, tier: 'C', score: 34, color: 'var(--tier-c)' },
  { label: 'Moves Faster Than Motion', weight: 1, tier: 'C', score: 34, color: 'var(--tier-c)' },
  { label: 'Sidesteps the Concept of Being Hit', weight: 1, tier: 'C', score: 34, color: 'var(--tier-c)' },

  // C+ (score: 38)
  { label: 'Trans-Dimensional Evasion', weight: 1, tier: 'C+', score: 38, color: 'var(--tier-c-plus)' },
  { label: 'Movement That Bypasses Causality', weight: 1, tier: 'C+', score: 38, color: 'var(--tier-c-plus)' },
  { label: 'Exists in Non-Euclidean Space Primarily', weight: 1, tier: 'C+', score: 38, color: 'var(--tier-c-plus)' },
  { label: 'Moves Through What Hasn\'t Happened', weight: 1, tier: 'C+', score: 38, color: 'var(--tier-c-plus)' },
  { label: 'Can Dodge Universal Forces', weight: 1, tier: 'C+', score: 38, color: 'var(--tier-c-plus)' },
  { label: 'Spatial Logic: Customized', weight: 1, tier: 'C+', score: 38, color: 'var(--tier-c-plus)' },
  { label: 'Avoids Attacks Across All Timelines', weight: 1, tier: 'C+', score: 38, color: 'var(--tier-c-plus)' },
  { label: 'Movement Through Unwritten Dimensions', weight: 1, tier: 'C+', score: 38, color: 'var(--tier-c-plus)' },
  { label: 'Can Sidestep The Future', weight: 1, tier: 'C+', score: 38, color: 'var(--tier-c-plus)' },
  { label: 'Reflexes Older Than Their Body', weight: 1, tier: 'C+', score: 38, color: 'var(--tier-c-plus)' },
  { label: 'Every Dodge Rewrites Possibility', weight: 1, tier: 'C+', score: 38, color: 'var(--tier-c-plus)' },
  { label: 'Moves Through Layers of Reality', weight: 1, tier: 'C+', score: 38, color: 'var(--tier-c-plus)' },
  { label: 'Position: Negotiable', weight: 1, tier: 'C+', score: 38, color: 'var(--tier-c-plus)' },
  { label: 'Can Avoid Logical Outcomes', weight: 1, tier: 'C+', score: 38, color: 'var(--tier-c-plus)' },
  { label: 'Direction Has No Meaning', weight: 1, tier: 'C+', score: 38, color: 'var(--tier-c-plus)' },
  { label: 'Sidesteps Gravity\'s Opinion', weight: 1, tier: 'C+', score: 38, color: 'var(--tier-c-plus)' },
  { label: 'Evasion at the Level of Pure Abstraction', weight: 1, tier: 'C+', score: 38, color: 'var(--tier-c-plus)' },
  { label: 'Can Be Anywhere Except Where Attacked', weight: 1, tier: 'C+', score: 38, color: 'var(--tier-c-plus)' },
  { label: 'Motion That Transcends Physical Law', weight: 1, tier: 'C+', score: 38, color: 'var(--tier-c-plus)' },
  { label: 'Moves Between Frames of Reality', weight: 1, tier: 'C+', score: 38, color: 'var(--tier-c-plus)' },

  // B- (score: 42)
  { label: 'Omnidirectional Evasion', weight: 1, tier: 'B-', score: 42, color: 'var(--tier-b-minus)' },
  { label: 'Dodges Timelines', weight: 1, tier: 'B-', score: 42, color: 'var(--tier-b-minus)' },
  { label: 'Moves Outside of Space', weight: 1, tier: 'B-', score: 42, color: 'var(--tier-b-minus)' },
  { label: 'Can Avoid Any Attack by Rewriting Position', weight: 1, tier: 'B-', score: 42, color: 'var(--tier-b-minus)' },
  { label: 'Position Doesn\'t Apply', weight: 1, tier: 'B-', score: 42, color: 'var(--tier-b-minus)' },
  { label: 'Multiversal Dodge', weight: 1, tier: 'B-', score: 42, color: 'var(--tier-b-minus)' },
  { label: 'Slips Between Moments', weight: 1, tier: 'B-', score: 42, color: 'var(--tier-b-minus)' },
  { label: 'Exists Where Attacks Aren\'t', weight: 1, tier: 'B-', score: 42, color: 'var(--tier-b-minus)' },
  { label: 'Reflexes Predate Attack Intention', weight: 1, tier: 'B-', score: 42, color: 'var(--tier-b-minus)' },
  { label: 'Movement Has Become Metaphysics', weight: 1, tier: 'B-', score: 42, color: 'var(--tier-b-minus)' },
  { label: 'Can Dodge What Hasn\'t Been Conceived', weight: 1, tier: 'B-', score: 42, color: 'var(--tier-b-minus)' },
  { label: 'Never Been in the Wrong Place', weight: 1, tier: 'B-', score: 42, color: 'var(--tier-b-minus)' },
  { label: 'Spatial Intuition: Omniversal', weight: 1, tier: 'B-', score: 42, color: 'var(--tier-b-minus)' },
  { label: 'Evasion That Erases Attack Potential', weight: 1, tier: 'B-', score: 42, color: 'var(--tier-b-minus)' },
  { label: 'Moves Between Existence Layers', weight: 1, tier: 'B-', score: 42, color: 'var(--tier-b-minus)' },
  { label: 'Avoids What Will Happen Across All Futures', weight: 1, tier: 'B-', score: 42, color: 'var(--tier-b-minus)' },
  { label: 'Steps Into Adjacent Realities to Dodge', weight: 1, tier: 'B-', score: 42, color: 'var(--tier-b-minus)' },
  { label: 'Impossible Position: Their Default', weight: 1, tier: 'B-', score: 42, color: 'var(--tier-b-minus)' },
  { label: 'Geometry Is Polite Fiction', weight: 1, tier: 'B-', score: 42, color: 'var(--tier-b-minus)' },
  { label: 'Occupies Anti-Space', weight: 1, tier: 'B-', score: 42, color: 'var(--tier-b-minus)' },

  // B (score: 47)
  { label: 'Absolute Evasion', weight: 1, tier: 'B', score: 47, color: 'var(--tier-b)' },
  { label: 'Cannot Be Hit from Any Direction', weight: 1, tier: 'B', score: 47, color: 'var(--tier-b)' },
  { label: 'Moves Across All Dimensions', weight: 1, tier: 'B', score: 47, color: 'var(--tier-b)' },
  { label: 'Exists Where Attacks Cannot', weight: 1, tier: 'B', score: 47, color: 'var(--tier-b)' },
  { label: 'Agility That Transcends Physical Location', weight: 1, tier: 'B', score: 47, color: 'var(--tier-b)' },
  { label: 'Movement Predates Thought', weight: 1, tier: 'B', score: 47, color: 'var(--tier-b)' },
  { label: 'Dodges the Concept of Being Targeted', weight: 1, tier: 'B', score: 47, color: 'var(--tier-b)' },
  { label: 'Can Avoid Universal Constants', weight: 1, tier: 'B', score: 47, color: 'var(--tier-b)' },
  { label: 'No Force Can Track Them', weight: 1, tier: 'B', score: 47, color: 'var(--tier-b)' },
  { label: 'Sidesteps the Framework of Reality', weight: 1, tier: 'B', score: 47, color: 'var(--tier-b)' },
  { label: 'Movement Becomes Conceptual', weight: 1, tier: 'B', score: 47, color: 'var(--tier-b)' },
  { label: 'All Attacks Reach Empty Positions', weight: 1, tier: 'B', score: 47, color: 'var(--tier-b)' },
  { label: 'Can Move Through Non-Dimensions', weight: 1, tier: 'B', score: 47, color: 'var(--tier-b)' },
  { label: 'Dodge Reflex: Pre-Causal', weight: 1, tier: 'B', score: 47, color: 'var(--tier-b)' },
  { label: 'Avoids Being at Any Fixed Location', weight: 1, tier: 'B', score: 47, color: 'var(--tier-b)' },
  { label: 'Slips Through Fate Itself', weight: 1, tier: 'B', score: 47, color: 'var(--tier-b)' },
  { label: 'Position: Philosophical', weight: 1, tier: 'B', score: 47, color: 'var(--tier-b)' },
  { label: 'Evasion Has Become a Natural Law', weight: 1, tier: 'B', score: 47, color: 'var(--tier-b)' },
  { label: 'Can Dodge What Hasn\'t Existed Yet', weight: 1, tier: 'B', score: 47, color: 'var(--tier-b)' },
  { label: 'Omnidirectional at the Metaphysical Level', weight: 1, tier: 'B', score: 47, color: 'var(--tier-b)' },

  // B+ (score: 52)
  { label: 'Impossible Positioning', weight: 1, tier: 'B+', score: 52, color: 'var(--tier-b-plus)' },
  { label: 'Dodges All Possible Attacks Simultaneously', weight: 1, tier: 'B+', score: 52, color: 'var(--tier-b-plus)' },
  { label: 'Exists Outside Attack Domains', weight: 1, tier: 'B+', score: 52, color: 'var(--tier-b-plus)' },
  { label: 'Moves Through Infinite Dimensions', weight: 1, tier: 'B+', score: 52, color: 'var(--tier-b-plus)' },
  { label: 'Agility That Wrote the Laws of Motion', weight: 1, tier: 'B+', score: 52, color: 'var(--tier-b-plus)' },
  { label: 'Position: Omniversal', weight: 1, tier: 'B+', score: 52, color: 'var(--tier-b-plus)' },
  { label: 'Can Step Around Abstract Concepts', weight: 1, tier: 'B+', score: 52, color: 'var(--tier-b-plus)' },
  { label: 'Evasion That Preceded Creation', weight: 1, tier: 'B+', score: 52, color: 'var(--tier-b-plus)' },
  { label: 'Reflexes Outside of Sequential Time', weight: 1, tier: 'B+', score: 52, color: 'var(--tier-b-plus)' },
  { label: 'Sidesteps the End of Everything', weight: 1, tier: 'B+', score: 52, color: 'var(--tier-b-plus)' },
  { label: 'Cannot Be Located in Space or Time', weight: 1, tier: 'B+', score: 52, color: 'var(--tier-b-plus)' },
  { label: 'Avoids All Timelines\' Attacks', weight: 1, tier: 'B+', score: 52, color: 'var(--tier-b-plus)' },
  { label: 'Moves Through What Cannot Be Moved Through', weight: 1, tier: 'B+', score: 52, color: 'var(--tier-b-plus)' },
  { label: 'Dodge That Unmakes the Attack\'s Premise', weight: 1, tier: 'B+', score: 52, color: 'var(--tier-b-plus)' },
  { label: 'Every Dimension Is a Valid Path', weight: 1, tier: 'B+', score: 52, color: 'var(--tier-b-plus)' },
  { label: 'Agility: Pre-Universal', weight: 1, tier: 'B+', score: 52, color: 'var(--tier-b-plus)' },
  { label: 'Evasion as a Form of Ontology', weight: 1, tier: 'B+', score: 52, color: 'var(--tier-b-plus)' },
  { label: 'Reflexes: Before Physics Needed Them', weight: 1, tier: 'B+', score: 52, color: 'var(--tier-b-plus)' },
  { label: 'Can Dodge Logical Consequences', weight: 1, tier: 'B+', score: 52, color: 'var(--tier-b-plus)' },
  { label: 'Movement That Defies All Frameworks', weight: 1, tier: 'B+', score: 52, color: 'var(--tier-b-plus)' },

  // A- (score: 57)
  { label: 'Absolute Motion Mastery', weight: 1, tier: 'A-', score: 57, color: 'var(--tier-a-minus)' },
  { label: 'Sidesteps Causal Reality', weight: 1, tier: 'A-', score: 57, color: 'var(--tier-a-minus)' },
  { label: 'Movement Through Absolute Nothing', weight: 1, tier: 'A-', score: 57, color: 'var(--tier-a-minus)' },
  { label: 'Cannot Be Located', weight: 1, tier: 'A-', score: 57, color: 'var(--tier-a-minus)' },
  { label: 'Evasion: An Ontological State', weight: 1, tier: 'A-', score: 57, color: 'var(--tier-a-minus)' },
  { label: 'Occupies All and No Positions', weight: 1, tier: 'A-', score: 57, color: 'var(--tier-a-minus)' },
  { label: 'Dodges What Cannot Be Attacked', weight: 1, tier: 'A-', score: 57, color: 'var(--tier-a-minus)' },
  { label: 'Reflexes Pre-Date Possibility', weight: 1, tier: 'A-', score: 57, color: 'var(--tier-a-minus)' },
  { label: 'Movement That Bypasses Everything', weight: 1, tier: 'A-', score: 57, color: 'var(--tier-a-minus)' },
  { label: 'Position Is a Personal Choice', weight: 1, tier: 'A-', score: 57, color: 'var(--tier-a-minus)' },
  { label: 'Can Sidestep the Big Bang', weight: 1, tier: 'A-', score: 57, color: 'var(--tier-a-minus)' },
  { label: 'Agility Written Into Universal Law', weight: 1, tier: 'A-', score: 57, color: 'var(--tier-a-minus)' },
  { label: 'Avoids the Concept of Harm', weight: 1, tier: 'A-', score: 57, color: 'var(--tier-a-minus)' },
  { label: 'Every Dodge Destroys the Attacker\'s Timeline', weight: 1, tier: 'A-', score: 57, color: 'var(--tier-a-minus)' },
  { label: 'Movement: Pre-Physical', weight: 1, tier: 'A-', score: 57, color: 'var(--tier-a-minus)' },
  { label: 'Spatial Reality Submits', weight: 1, tier: 'A-', score: 57, color: 'var(--tier-a-minus)' },
  { label: 'Can Slip Through the Uncreated', weight: 1, tier: 'A-', score: 57, color: 'var(--tier-a-minus)' },
  { label: 'Evasion Transcends Consequence', weight: 1, tier: 'A-', score: 57, color: 'var(--tier-a-minus)' },
  { label: 'Exists Only Where Safe', weight: 1, tier: 'A-', score: 57, color: 'var(--tier-a-minus)' },
  { label: 'Dodge: A Universal Force Now', weight: 1, tier: 'A-', score: 57, color: 'var(--tier-a-minus)' },

  // A (score: 62)
  { label: 'Exists in All Positions Simultaneously', weight: 1, tier: 'A', score: 62, color: 'var(--tier-a)' },
  { label: 'Dodges Photons', weight: 1, tier: 'A', score: 62, color: 'var(--tier-a)' },
  { label: 'Omnipositional', weight: 1, tier: 'A', score: 62, color: 'var(--tier-a)' },
  { label: 'Sidesteps the Concept of Impact', weight: 1, tier: 'A', score: 62, color: 'var(--tier-a)' },
  { label: 'Untouchable', weight: 1, tier: 'A', score: 62, color: 'var(--tier-a)' },
  { label: 'Movement Beyond All Physical Laws', weight: 1, tier: 'A', score: 62, color: 'var(--tier-a)' },
  { label: 'Can Avoid Being Hit by Ceasing to Have a Location', weight: 1, tier: 'A', score: 62, color: 'var(--tier-a)' },
  { label: 'Evasion Is Cosmic Function Now', weight: 1, tier: 'A', score: 62, color: 'var(--tier-a)' },
  { label: 'Reflexes: Pre-Universal', weight: 1, tier: 'A', score: 62, color: 'var(--tier-a)' },
  { label: 'Every Attack Misses Across All Timelines', weight: 1, tier: 'A', score: 62, color: 'var(--tier-a)' },
  { label: 'Moves Through the Framework of Reality', weight: 1, tier: 'A', score: 62, color: 'var(--tier-a)' },
  { label: 'No Position Is Final', weight: 1, tier: 'A', score: 62, color: 'var(--tier-a)' },
  { label: 'Spatial Topology: Irrelevant', weight: 1, tier: 'A', score: 62, color: 'var(--tier-a)' },
  { label: 'Movement Without Dimension', weight: 1, tier: 'A', score: 62, color: 'var(--tier-a)' },
  { label: 'Dodge Written Into the First Physical Law', weight: 1, tier: 'A', score: 62, color: 'var(--tier-a)' },
  { label: 'Exists Only Between Threats', weight: 1, tier: 'A', score: 62, color: 'var(--tier-a)' },
  { label: 'Can Sidestep Omnipotent Attacks', weight: 1, tier: 'A', score: 62, color: 'var(--tier-a)' },
  { label: 'Agility: A Fundamental Property of Reality', weight: 1, tier: 'A', score: 62, color: 'var(--tier-a)' },
  { label: 'Movement Pre-Dates the First Movement', weight: 1, tier: 'A', score: 62, color: 'var(--tier-a)' },
  { label: 'Can Occupy Non-Space', weight: 1, tier: 'A', score: 62, color: 'var(--tier-a)' },

  // A+ (score: 67)
  { label: 'Untouchable Across All Existence', weight: 1, tier: 'A+', score: 67, color: 'var(--tier-a-plus)' },
  { label: 'Evasion That Transcends Physicality', weight: 1, tier: 'A+', score: 67, color: 'var(--tier-a-plus)' },
  { label: 'Moves Through Pre-Creation', weight: 1, tier: 'A+', score: 67, color: 'var(--tier-a-plus)' },
  { label: 'No Framework Constrains Movement', weight: 1, tier: 'A+', score: 67, color: 'var(--tier-a-plus)' },
  { label: 'Dodges What Cannot Be Conceived', weight: 1, tier: 'A+', score: 67, color: 'var(--tier-a-plus)' },
  { label: 'Position Is Their Decision', weight: 1, tier: 'A+', score: 67, color: 'var(--tier-a-plus)' },
  { label: 'Reflexes That Pre-Exist Their Existence', weight: 1, tier: 'A+', score: 67, color: 'var(--tier-a-plus)' },
  { label: 'Can Sidestep the Birth of the Universe', weight: 1, tier: 'A+', score: 67, color: 'var(--tier-a-plus)' },
  { label: 'Every Attack Has Already Missed', weight: 1, tier: 'A+', score: 67, color: 'var(--tier-a-plus)' },
  { label: 'Agility That Authored Spatial Law', weight: 1, tier: 'A+', score: 67, color: 'var(--tier-a-plus)' },
  { label: 'Moves Between the Uncreated and Existent', weight: 1, tier: 'A+', score: 67, color: 'var(--tier-a-plus)' },
  { label: 'Movement: A Platonic Form', weight: 1, tier: 'A+', score: 67, color: 'var(--tier-a-plus)' },
  { label: 'Can Dodge Absolute Authority', weight: 1, tier: 'A+', score: 67, color: 'var(--tier-a-plus)' },
  { label: 'All Possible Attack Vectors: Void', weight: 1, tier: 'A+', score: 67, color: 'var(--tier-a-plus)' },
  { label: 'Evasion is a Natural Constant', weight: 1, tier: 'A+', score: 67, color: 'var(--tier-a-plus)' },
  { label: 'Position: Pre-Cosmic', weight: 1, tier: 'A+', score: 67, color: 'var(--tier-a-plus)' },
  { label: 'Occupies Space That Doesn\'t Exist', weight: 1, tier: 'A+', score: 67, color: 'var(--tier-a-plus)' },
  { label: 'Movement That Writes Reality\'s Constitution', weight: 1, tier: 'A+', score: 67, color: 'var(--tier-a-plus)' },
  { label: 'Dodges Omnipotent Inevitability', weight: 1, tier: 'A+', score: 67, color: 'var(--tier-a-plus)' },
  { label: 'Even Fate Cannot Catch Them', weight: 1, tier: 'A+', score: 67, color: 'var(--tier-a-plus)' },

  // S- (score: 72)
  { label: 'Fate-Level Evasion', weight: 1, tier: 'S-', score: 72, color: 'var(--tier-s-minus)' },
  { label: 'Dodges the Uncaused', weight: 1, tier: 'S-', score: 72, color: 'var(--tier-s-minus)' },
  { label: 'Movement That Precedes All Categories', weight: 1, tier: 'S-', score: 72, color: 'var(--tier-s-minus)' },
  { label: 'Can Sidestep Timelessness', weight: 1, tier: 'S-', score: 72, color: 'var(--tier-s-minus)' },
  { label: 'Spatial Rules Were Overruled', weight: 1, tier: 'S-', score: 72, color: 'var(--tier-s-minus)' },
  { label: 'Exists at the Intersection of All Dimensions', weight: 1, tier: 'S-', score: 72, color: 'var(--tier-s-minus)' },
  { label: 'Every Conceivable Attack: Already Missed', weight: 1, tier: 'S-', score: 72, color: 'var(--tier-s-minus)' },
  { label: 'Can Dodge What Will Never Exist', weight: 1, tier: 'S-', score: 72, color: 'var(--tier-s-minus)' },
  { label: 'Evasion Defines the Concept of Safe', weight: 1, tier: 'S-', score: 72, color: 'var(--tier-s-minus)' },
  { label: 'Position: Permanent Evasion', weight: 1, tier: 'S-', score: 72, color: 'var(--tier-s-minus)' },
  { label: 'Movement That Is Indistinguishable from Not Being Hit', weight: 1, tier: 'S-', score: 72, color: 'var(--tier-s-minus)' },
  { label: 'Agility: Pre-Logical', weight: 1, tier: 'S-', score: 72, color: 'var(--tier-s-minus)' },
  { label: 'Avoids Omniversal Harm Vectors', weight: 1, tier: 'S-', score: 72, color: 'var(--tier-s-minus)' },
  { label: 'Reflexes: Precede the Framework', weight: 1, tier: 'S-', score: 72, color: 'var(--tier-s-minus)' },
  { label: 'Sidesteps the Architecture of Reality', weight: 1, tier: 'S-', score: 72, color: 'var(--tier-s-minus)' },
  { label: 'Every Attack Has Always Already Failed', weight: 1, tier: 'S-', score: 72, color: 'var(--tier-s-minus)' },
  { label: 'Exists in the Negative Space of All Attacks', weight: 1, tier: 'S-', score: 72, color: 'var(--tier-s-minus)' },
  { label: 'Movement: Predates the Option to Not Move', weight: 1, tier: 'S-', score: 72, color: 'var(--tier-s-minus)' },
  { label: 'Dodges Before Aggression Exists', weight: 1, tier: 'S-', score: 72, color: 'var(--tier-s-minus)' },
  { label: 'Position: Undefined, and That\'s Intentional', weight: 1, tier: 'S-', score: 72, color: 'var(--tier-s-minus)' },

  // S (score: 77)
  { label: 'Existence-Level Evasion', weight: 1, tier: 'S', score: 77, color: 'var(--tier-s)' },
  { label: 'Can Dodge Omnipotent Inevitability', weight: 1, tier: 'S', score: 77, color: 'var(--tier-s)' },
  { label: 'Movement That Precedes Being', weight: 1, tier: 'S', score: 77, color: 'var(--tier-s)' },
  { label: 'Cannot Be Attacked in Any Conceivable Universe', weight: 1, tier: 'S', score: 77, color: 'var(--tier-s)' },
  { label: 'Position Has Become a Philosophical Stance', weight: 1, tier: 'S', score: 77, color: 'var(--tier-s)' },
  { label: 'Reflexes: Pre-Reality', weight: 1, tier: 'S', score: 77, color: 'var(--tier-s)' },
  { label: 'Movement That Defines What Moved', weight: 1, tier: 'S', score: 77, color: 'var(--tier-s)' },
  { label: 'Sidesteps the Concept of Being a Target', weight: 1, tier: 'S', score: 77, color: 'var(--tier-s)' },
  { label: 'All Harm: Retroactively Avoided', weight: 1, tier: 'S', score: 77, color: 'var(--tier-s)' },
  { label: 'Agility: An Eternal Constant', weight: 1, tier: 'S', score: 77, color: 'var(--tier-s)' },
  { label: 'Moves Through Being Itself', weight: 1, tier: 'S', score: 77, color: 'var(--tier-s)' },
  { label: 'Evasion That Erases the Attack\'s Past', weight: 1, tier: 'S', score: 77, color: 'var(--tier-s)' },
  { label: 'Every Position Possible: Occupied Briefly', weight: 1, tier: 'S', score: 77, color: 'var(--tier-s)' },
  { label: 'Can Be Anywhere in the Omniverse', weight: 1, tier: 'S', score: 77, color: 'var(--tier-s)' },
  { label: 'Physics Cannot Constrain Their Evasion', weight: 1, tier: 'S', score: 77, color: 'var(--tier-s)' },
  { label: 'Movement: The Foundational Force', weight: 1, tier: 'S', score: 77, color: 'var(--tier-s)' },
  { label: 'Dodge That Predates Space-Time', weight: 1, tier: 'S', score: 77, color: 'var(--tier-s)' },
  { label: 'Every Attack Has No Record of Existing', weight: 1, tier: 'S', score: 77, color: 'var(--tier-s)' },
  { label: 'Position: Negated', weight: 1, tier: 'S', score: 77, color: 'var(--tier-s)' },
  { label: 'Evasion Has Been Deified', weight: 1, tier: 'S', score: 77, color: 'var(--tier-s)' },

  // S+ (score: 81)
  { label: 'Infinite Dimensional Movement', weight: 1, tier: 'S+', score: 81, color: 'var(--tier-s-plus)' },
  { label: 'Can Dodge in All Existences At Once', weight: 1, tier: 'S+', score: 81, color: 'var(--tier-s-plus)' },
  { label: 'Evasion Predates Existence', weight: 1, tier: 'S+', score: 81, color: 'var(--tier-s-plus)' },
  { label: 'Has Never Not Already Dodged', weight: 1, tier: 'S+', score: 81, color: 'var(--tier-s-plus)' },
  { label: 'Reflexes: Pre-Causal', weight: 1, tier: 'S+', score: 81, color: 'var(--tier-s-plus)' },
  { label: 'Evasion That Authored Safety', weight: 1, tier: 'S+', score: 81, color: 'var(--tier-s-plus)' },
  { label: 'Can Sidestep Non-Existence', weight: 1, tier: 'S+', score: 81, color: 'var(--tier-s-plus)' },
  { label: 'Movement That Bypasses All Categories', weight: 1, tier: 'S+', score: 81, color: 'var(--tier-s-plus)' },
  { label: 'Position: A Choice, Not a Constraint', weight: 1, tier: 'S+', score: 81, color: 'var(--tier-s-plus)' },
  { label: 'Occupies the Theoretical at Will', weight: 1, tier: 'S+', score: 81, color: 'var(--tier-s-plus)' },
  { label: 'Agility That Transcends Metaphysics', weight: 1, tier: 'S+', score: 81, color: 'var(--tier-s-plus)' },
  { label: 'All Attacks Simply Cannot Land', weight: 1, tier: 'S+', score: 81, color: 'var(--tier-s-plus)' },
  { label: 'Moves Through Pre-Logic', weight: 1, tier: 'S+', score: 81, color: 'var(--tier-s-plus)' },
  { label: 'Location: Metaphysically Uncertain', weight: 1, tier: 'S+', score: 81, color: 'var(--tier-s-plus)' },
  { label: 'Evasion as a Property of Reality', weight: 1, tier: 'S+', score: 81, color: 'var(--tier-s-plus)' },
  { label: 'Every Dodge Is a New Theorem', weight: 1, tier: 'S+', score: 81, color: 'var(--tier-s-plus)' },
  { label: 'Sidesteps What Never Was', weight: 1, tier: 'S+', score: 81, color: 'var(--tier-s-plus)' },
  { label: 'Can Slip Between Omnipotent Certainties', weight: 1, tier: 'S+', score: 81, color: 'var(--tier-s-plus)' },
  { label: 'No Attack Has a Path to Their Position', weight: 1, tier: 'S+', score: 81, color: 'var(--tier-s-plus)' },
  { label: 'Movement That Pre-Dates What Movement Is', weight: 1, tier: 'S+', score: 81, color: 'var(--tier-s-plus)' },

  // SS- (score: 85)
  { label: 'Reality-Defying Agility', weight: 1, tier: 'SS-', score: 85, color: 'var(--tier-ss-minus)' },
  { label: 'Can Dodge Omnipotence', weight: 1, tier: 'SS-', score: 85, color: 'var(--tier-ss-minus)' },
  { label: 'Evasion at the Level of Pure Will', weight: 1, tier: 'SS-', score: 85, color: 'var(--tier-ss-minus)' },
  { label: 'Movement Beyond Being', weight: 1, tier: 'SS-', score: 85, color: 'var(--tier-ss-minus)' },
  { label: 'Never Defined by Position', weight: 1, tier: 'SS-', score: 85, color: 'var(--tier-ss-minus)' },
  { label: 'Agility That Wrote Universal Law', weight: 1, tier: 'SS-', score: 85, color: 'var(--tier-ss-minus)' },
  { label: 'Occupies Pre-Existent Space', weight: 1, tier: 'SS-', score: 85, color: 'var(--tier-ss-minus)' },
  { label: 'All Vectors: Negative', weight: 1, tier: 'SS-', score: 85, color: 'var(--tier-ss-minus)' },
  { label: 'Evasion Pre-Dates What It Evades', weight: 1, tier: 'SS-', score: 85, color: 'var(--tier-ss-minus)' },
  { label: 'Can Be Where Only Nothing Is', weight: 1, tier: 'SS-', score: 85, color: 'var(--tier-ss-minus)' },
  { label: 'Movement: A Property of the First Cause', weight: 1, tier: 'SS-', score: 85, color: 'var(--tier-ss-minus)' },
  { label: 'Reflexes: Eternal and Retroactive', weight: 1, tier: 'SS-', score: 85, color: 'var(--tier-ss-minus)' },
  { label: 'Sidesteps Existence if Needed', weight: 1, tier: 'SS-', score: 85, color: 'var(--tier-ss-minus)' },
  { label: 'Position Has No Hold on Them', weight: 1, tier: 'SS-', score: 85, color: 'var(--tier-ss-minus)' },
  { label: 'Every Move Is Outside Known Physics', weight: 1, tier: 'SS-', score: 85, color: 'var(--tier-ss-minus)' },
  { label: 'Can Avoid Even the Concept of Harm', weight: 1, tier: 'SS-', score: 85, color: 'var(--tier-ss-minus)' },
  { label: 'Agility That Authored the Idea of Movement', weight: 1, tier: 'SS-', score: 85, color: 'var(--tier-ss-minus)' },
  { label: 'Evasion: Permanent and Eternal', weight: 1, tier: 'SS-', score: 85, color: 'var(--tier-ss-minus)' },
  { label: 'Unconstrained by Any Physical Truth', weight: 1, tier: 'SS-', score: 85, color: 'var(--tier-ss-minus)' },
  { label: 'Can Step Through the Uncaused Cause', weight: 1, tier: 'SS-', score: 85, color: 'var(--tier-ss-minus)' },

  // SS (score: 88)
  { label: 'Divine Agility', weight: 1, tier: 'SS', score: 88, color: 'var(--tier-ss)' },
  { label: 'Untouchable by Any Possible Force', weight: 1, tier: 'SS', score: 88, color: 'var(--tier-ss)' },
  { label: 'Movement That Preceded the Option to Stay Still', weight: 1, tier: 'SS', score: 88, color: 'var(--tier-ss)' },
  { label: 'Evasion Is Cosmological Constant', weight: 1, tier: 'SS', score: 88, color: 'var(--tier-ss)' },
  { label: 'Position: Chosen, Not Imposed', weight: 1, tier: 'SS', score: 88, color: 'var(--tier-ss)' },
  { label: 'Exists in All Spaces Where There Are None', weight: 1, tier: 'SS', score: 88, color: 'var(--tier-ss)' },
  { label: 'Dodges What Comes Before Attacks', weight: 1, tier: 'SS', score: 88, color: 'var(--tier-ss)' },
  { label: 'Every Moment Is a Perfect Position', weight: 1, tier: 'SS', score: 88, color: 'var(--tier-ss)' },
  { label: 'Spatial Reality Has No Say', weight: 1, tier: 'SS', score: 88, color: 'var(--tier-ss)' },
  { label: 'Agility Beyond All Description', weight: 1, tier: 'SS', score: 88, color: 'var(--tier-ss)' },
  { label: 'Movement: The First and Last Law', weight: 1, tier: 'SS', score: 88, color: 'var(--tier-ss)' },
  { label: 'Cannot Be Located by Any Possible Means', weight: 1, tier: 'SS', score: 88, color: 'var(--tier-ss)' },
  { label: 'Evasion Wrote Itself Into First Principles', weight: 1, tier: 'SS', score: 88, color: 'var(--tier-ss)' },
  { label: 'Reflexes That Define Causality Itself', weight: 1, tier: 'SS', score: 88, color: 'var(--tier-ss)' },
  { label: 'Movement Equivalent to Non-Location', weight: 1, tier: 'SS', score: 88, color: 'var(--tier-ss)' },
  { label: 'Exists Optimally in All Moments', weight: 1, tier: 'SS', score: 88, color: 'var(--tier-ss)' },
  { label: 'Can Sidestep the Death of the Universe', weight: 1, tier: 'SS', score: 88, color: 'var(--tier-ss)' },
  { label: 'Agility: Synonymous with Untouchable', weight: 1, tier: 'SS', score: 88, color: 'var(--tier-ss)' },
  { label: 'All Attacks Retroactively Miss', weight: 1, tier: 'SS', score: 88, color: 'var(--tier-ss)' },
  { label: 'Position: A Polite Suggestion They Ignored', weight: 1, tier: 'SS', score: 88, color: 'var(--tier-ss)' },

  // SS+ (score: 91)
  { label: 'Movement That Authors Possibility', weight: 1, tier: 'SS+', score: 91, color: 'var(--tier-ss-plus)' },
  { label: 'Can Dodge the Void', weight: 1, tier: 'SS+', score: 91, color: 'var(--tier-ss-plus)' },
  { label: 'Every Attack: Eternally Missed', weight: 1, tier: 'SS+', score: 91, color: 'var(--tier-ss-plus)' },
  { label: 'Evasion Transcends All Known Frameworks', weight: 1, tier: 'SS+', score: 91, color: 'var(--tier-ss-plus)' },
  { label: 'Moves Through the Primordial Absence', weight: 1, tier: 'SS+', score: 91, color: 'var(--tier-ss-plus)' },
  { label: 'Position: Never Determined', weight: 1, tier: 'SS+', score: 91, color: 'var(--tier-ss-plus)' },
  { label: 'Agility That Is Its Own Cosmology', weight: 1, tier: 'SS+', score: 91, color: 'var(--tier-ss-plus)' },
  { label: 'Can Sidestep the Uncaused First Cause', weight: 1, tier: 'SS+', score: 91, color: 'var(--tier-ss-plus)' },
  { label: 'Movement: Not Bound by Any Logic', weight: 1, tier: 'SS+', score: 91, color: 'var(--tier-ss-plus)' },
  { label: 'Spatial Existence Is Optional', weight: 1, tier: 'SS+', score: 91, color: 'var(--tier-ss-plus)' },
  { label: 'Reflexes: Outside Sequential Time', weight: 1, tier: 'SS+', score: 91, color: 'var(--tier-ss-plus)' },
  { label: 'Dodge That Erased the Attack From History', weight: 1, tier: 'SS+', score: 91, color: 'var(--tier-ss-plus)' },
  { label: 'Can Occupy All and No Space', weight: 1, tier: 'SS+', score: 91, color: 'var(--tier-ss-plus)' },
  { label: 'Evasion Pre-Dates Harm\'s Invention', weight: 1, tier: 'SS+', score: 91, color: 'var(--tier-ss-plus)' },
  { label: 'Agility That Defined the Possible', weight: 1, tier: 'SS+', score: 91, color: 'var(--tier-ss-plus)' },
  { label: 'Spatial Law: On Appeal', weight: 1, tier: 'SS+', score: 91, color: 'var(--tier-ss-plus)' },
  { label: 'Movement Through the Pre-Spatial', weight: 1, tier: 'SS+', score: 91, color: 'var(--tier-ss-plus)' },
  { label: 'Can Avoid Anything Including Non-Existence', weight: 1, tier: 'SS+', score: 91, color: 'var(--tier-ss-plus)' },
  { label: 'Every Conceivable Position: Occupied Safely', weight: 1, tier: 'SS+', score: 91, color: 'var(--tier-ss-plus)' },
  { label: 'Evasion Has Become a Principle of Reality', weight: 1, tier: 'SS+', score: 91, color: 'var(--tier-ss-plus)' },

  // SSS- (score: 94)
  { label: 'Absolute Agility', weight: 1, tier: 'SSS-', score: 94, color: 'var(--tier-sss-minus)' },
  { label: 'Untouchable: A Cosmic Constant', weight: 1, tier: 'SSS-', score: 94, color: 'var(--tier-sss-minus)' },
  { label: 'Evasion That Precedes the Universe', weight: 1, tier: 'SSS-', score: 94, color: 'var(--tier-sss-minus)' },
  { label: 'Movement: Primordial Force', weight: 1, tier: 'SSS-', score: 94, color: 'var(--tier-sss-minus)' },
  { label: 'Position: Entirely Personal', weight: 1, tier: 'SSS-', score: 94, color: 'var(--tier-sss-minus)' },
  { label: 'Can Dodge the Concept of Being', weight: 1, tier: 'SSS-', score: 94, color: 'var(--tier-sss-minus)' },
  { label: 'Every Attack Path: Nonexistent', weight: 1, tier: 'SSS-', score: 94, color: 'var(--tier-sss-minus)' },
  { label: 'Reflexes Outside of All Physical Law', weight: 1, tier: 'SSS-', score: 94, color: 'var(--tier-sss-minus)' },
  { label: 'Agility That Wrote Physical Law', weight: 1, tier: 'SSS-', score: 94, color: 'var(--tier-sss-minus)' },
  { label: 'Can Sidestep Omnipotent Will', weight: 1, tier: 'SSS-', score: 94, color: 'var(--tier-sss-minus)' },
  { label: 'Movement That Is a Creative Force', weight: 1, tier: 'SSS-', score: 94, color: 'var(--tier-sss-minus)' },
  { label: 'Evasion: Eternal and Absolute', weight: 1, tier: 'SSS-', score: 94, color: 'var(--tier-sss-minus)' },
  { label: 'Can Occupy What Cannot Be Occupied', weight: 1, tier: 'SSS-', score: 94, color: 'var(--tier-sss-minus)' },
  { label: 'Position: Omniversal and Undefined', weight: 1, tier: 'SSS-', score: 94, color: 'var(--tier-sss-minus)' },
  { label: 'Agility That Pre-Dates Agency', weight: 1, tier: 'SSS-', score: 94, color: 'var(--tier-sss-minus)' },
  { label: 'Every Attack Has Forever Missed', weight: 1, tier: 'SSS-', score: 94, color: 'var(--tier-sss-minus)' },
  { label: 'Movement That Cannot Be Named', weight: 1, tier: 'SSS-', score: 94, color: 'var(--tier-sss-minus)' },
  { label: 'Evasion Authored by Reality Itself', weight: 1, tier: 'SSS-', score: 94, color: 'var(--tier-sss-minus)' },
  { label: 'Can Sidestep Death Itself', weight: 1, tier: 'SSS-', score: 94, color: 'var(--tier-sss-minus)' },
  { label: 'Reflexes That Pre-Date the Concept of Reflexes', weight: 1, tier: 'SSS-', score: 94, color: 'var(--tier-sss-minus)' },

  // SSS (score: 97)
  { label: 'Transcendent Evasion', weight: 1, tier: 'SSS', score: 97, color: 'var(--tier-sss)' },
  { label: 'Position Is an Author\'s Choice', weight: 1, tier: 'SSS', score: 97, color: 'var(--tier-sss)' },
  { label: 'Dodges What Has Always Already Happened', weight: 1, tier: 'SSS', score: 97, color: 'var(--tier-sss)' },
  { label: 'Movement: Universal Constant', weight: 1, tier: 'SSS', score: 97, color: 'var(--tier-sss)' },
  { label: 'Evasion Predates the Laws That Allow It', weight: 1, tier: 'SSS', score: 97, color: 'var(--tier-sss)' },
  { label: 'Can Occupy All Non-Positions', weight: 1, tier: 'SSS', score: 97, color: 'var(--tier-sss)' },
  { label: 'No Attack Has Ever Defined Them', weight: 1, tier: 'SSS', score: 97, color: 'var(--tier-sss)' },
  { label: 'Agility That Wrote Infinity', weight: 1, tier: 'SSS', score: 97, color: 'var(--tier-sss)' },
  { label: 'Movement Through the Absolute Void', weight: 1, tier: 'SSS', score: 97, color: 'var(--tier-sss)' },
  { label: 'Reflexes: The First Law of Nature', weight: 1, tier: 'SSS', score: 97, color: 'var(--tier-sss)' },
  { label: 'Can Dodge Omniversal Certainty', weight: 1, tier: 'SSS', score: 97, color: 'var(--tier-sss)' },
  { label: 'Evasion That Authored All Spatial Law', weight: 1, tier: 'SSS', score: 97, color: 'var(--tier-sss)' },
  { label: 'Position: Infinite and Personal', weight: 1, tier: 'SSS', score: 97, color: 'var(--tier-sss)' },
  { label: 'All Known Attack Vectors: Obsolete', weight: 1, tier: 'SSS', score: 97, color: 'var(--tier-sss)' },
  { label: 'Agility: The Cosmological Constant', weight: 1, tier: 'SSS', score: 97, color: 'var(--tier-sss)' },
  { label: 'Occupies Where Nothing Has Been', weight: 1, tier: 'SSS', score: 97, color: 'var(--tier-sss)' },
  { label: 'Movement Synonymous with Safety', weight: 1, tier: 'SSS', score: 97, color: 'var(--tier-sss)' },
  { label: 'Evasion Before the Notion of Harm', weight: 1, tier: 'SSS', score: 97, color: 'var(--tier-sss)' },
  { label: 'Can Sidestep Absolute Truth', weight: 1, tier: 'SSS', score: 97, color: 'var(--tier-sss)' },
  { label: 'Every Dodge: An Act of Creation', weight: 1, tier: 'SSS', score: 97, color: 'var(--tier-sss)' },

  // SSS+ (score: 99)
  { label: 'Eternal Evasion', weight: 1, tier: 'SSS+', score: 99, color: 'var(--tier-sss-plus)' },
  { label: 'Untouchable by Anything That Could Exist', weight: 1, tier: 'SSS+', score: 99, color: 'var(--tier-sss-plus)' },
  { label: 'Movement That Is a Natural Law', weight: 1, tier: 'SSS+', score: 99, color: 'var(--tier-sss-plus)' },
  { label: 'Evasion: The Original Force', weight: 1, tier: 'SSS+', score: 99, color: 'var(--tier-sss-plus)' },
  { label: 'Can Be Where Everything Isn\'t', weight: 1, tier: 'SSS+', score: 99, color: 'var(--tier-sss-plus)' },
  { label: 'Position: Pre-Chosen From Before the Big Bang', weight: 1, tier: 'SSS+', score: 99, color: 'var(--tier-sss-plus)' },
  { label: 'Agility That Preceded All Other Properties', weight: 1, tier: 'SSS+', score: 99, color: 'var(--tier-sss-plus)' },
  { label: 'Movement Through Non-Being', weight: 1, tier: 'SSS+', score: 99, color: 'var(--tier-sss-plus)' },
  { label: 'All Threats Have Been Retroactively Avoided', weight: 1, tier: 'SSS+', score: 99, color: 'var(--tier-sss-plus)' },
  { label: 'Reflexes: Pre-Spatial', weight: 1, tier: 'SSS+', score: 99, color: 'var(--tier-sss-plus)' },
  { label: 'Can Dodge What Pre-Dates Existence', weight: 1, tier: 'SSS+', score: 99, color: 'var(--tier-sss-plus)' },
  { label: 'Every Conceivable Hit: Historically Impossible', weight: 1, tier: 'SSS+', score: 99, color: 'var(--tier-sss-plus)' },
  { label: 'Position: Authored by Them', weight: 1, tier: 'SSS+', score: 99, color: 'var(--tier-sss-plus)' },
  { label: 'Evasion That Authored Spatial Reality', weight: 1, tier: 'SSS+', score: 99, color: 'var(--tier-sss-plus)' },
  { label: 'Agility: A Theorem They Proved', weight: 1, tier: 'SSS+', score: 99, color: 'var(--tier-sss-plus)' },
  { label: 'Moves Through What Cannot Be Said', weight: 1, tier: 'SSS+', score: 99, color: 'var(--tier-sss-plus)' },
  { label: 'Movement That Negates Being Targeted', weight: 1, tier: 'SSS+', score: 99, color: 'var(--tier-sss-plus)' },
  { label: 'Can Dodge the Uncaused', weight: 1, tier: 'SSS+', score: 99, color: 'var(--tier-sss-plus)' },
  { label: 'Every Attack: Erased from Possibility', weight: 1, tier: 'SSS+', score: 99, color: 'var(--tier-sss-plus)' },
  { label: 'Evasion That Predates Harm\'s First Concept', weight: 1, tier: 'SSS+', score: 99, color: 'var(--tier-sss-plus)' },

  // God (score: 100)
  { label: 'Exists in All Positions Simultaneously', weight: 1, tier: 'God', score: 100, color: 'var(--tier-god)' },
  { label: 'Dodges Photons', weight: 1, tier: 'God', score: 100, color: 'var(--tier-god)' },
  { label: 'Untouchable by Anything Conceivable', weight: 1, tier: 'God', score: 100, color: 'var(--tier-god)' },
  { label: 'Position: Omniversal Sovereignty', weight: 1, tier: 'God', score: 100, color: 'var(--tier-god)' },
  { label: 'Evasion Is a Fundamental Force', weight: 1, tier: 'God', score: 100, color: 'var(--tier-god)' },
  { label: 'Movement Predates Physical Law', weight: 1, tier: 'God', score: 100, color: 'var(--tier-god)' },
  { label: 'Has Never Been Hit and Never Will Be', weight: 1, tier: 'God', score: 100, color: 'var(--tier-god)' },
  { label: 'Reflexes: Pre-Universal Constant', weight: 1, tier: 'God', score: 100, color: 'var(--tier-god)' },
  { label: 'All Attacks Have No Possible Path', weight: 1, tier: 'God', score: 100, color: 'var(--tier-god)' },
  { label: 'Agility: The Foundation of Motion', weight: 1, tier: 'God', score: 100, color: 'var(--tier-god)' },
  { label: 'Can Be Anywhere Across All Realities at Once', weight: 1, tier: 'God', score: 100, color: 'var(--tier-god)' },
  { label: 'Evasion Authored by the First Principle', weight: 1, tier: 'God', score: 100, color: 'var(--tier-god)' },
  { label: 'Moves Through Creation\'s Absence', weight: 1, tier: 'God', score: 100, color: 'var(--tier-god)' },
  { label: 'Every Attack: Cosmologically Impossible', weight: 1, tier: 'God', score: 100, color: 'var(--tier-god)' },
  { label: 'Position: Written Into Genesis', weight: 1, tier: 'God', score: 100, color: 'var(--tier-god)' },
  { label: 'Spatial Law Defers to Their Preference', weight: 1, tier: 'God', score: 100, color: 'var(--tier-god)' },
  { label: 'Agility That Created the Word "Graceful"', weight: 1, tier: 'God', score: 100, color: 'var(--tier-god)' },
  { label: 'Movement: The Original Creative Act', weight: 1, tier: 'God', score: 100, color: 'var(--tier-god)' },
  { label: 'Can Dodge the God of Harm', weight: 1, tier: 'God', score: 100, color: 'var(--tier-god)' },
  { label: 'Evasion Is How Reality Was Made', weight: 1, tier: 'God', score: 100, color: 'var(--tier-god)' },
]
