import type { FlavorLabel } from './types'

export const agilityLabels: FlavorLabel[] = [
  { label: 'Trips on Flat Surfaces',          weight: 4, tier: 'F-',   score: 2,   color: '#555'    },
  { label: 'Falls Up Stairs Regularly',       weight: 4, tier: 'F',    score: 5,   color: '#666'    },
  { label: 'Slightly Uncoordinated',          weight: 4, tier: 'F+',   score: 8,   color: '#777'    },
  { label: 'Awkward but Functional',          weight: 6, tier: 'E-',   score: 11,  color: '#6b7280' },
  { label: 'Average Balance',                 weight: 6, tier: 'E',    score: 14,  color: '#9ca3af' },
  { label: 'Good Reflexes',                   weight: 6, tier: 'E+',   score: 17,  color: '#d1d5db' },
  { label: 'Cat-Like Footing',                weight: 8, tier: 'D-',   score: 20,  color: '#92400e' },
  { label: 'Gymnast in Training',             weight: 8, tier: 'D',    score: 23,  color: '#b45309' },
  { label: 'Parkour Capable',                 weight: 8, tier: 'D+',   score: 26,  color: '#d97706' },
  { label: 'Elite Acrobat',                   weight: 8, tier: 'C-',   score: 30,  color: '#1d4ed8' },
  { label: 'Never Misses a Step',             weight: 8, tier: 'C',    score: 34,  color: '#2563eb' },
  { label: 'Defies Reasonable Gravity',       weight: 8, tier: 'C+',   score: 38,  color: '#3b82f6' },
  { label: 'Dodges Bullets on Instinct',      weight: 7, tier: 'B-',   score: 42,  color: '#065f46' },
  { label: 'Combat Acrobatics Master',        weight: 7, tier: 'B',    score: 47,  color: '#059669' },
  { label: 'Phantom Evasion',                 weight: 7, tier: 'B+',   score: 52,  color: '#34d399' },
  { label: 'Shadow Step-Level Reflexes',      weight: 5, tier: 'A-',   score: 57,  color: '#7c3aed' },
  { label: 'Untouchable in Combat',           weight: 5, tier: 'A',    score: 62,  color: '#8b5cf6' },
  { label: 'Afterimage Fighter',              weight: 5, tier: 'A+',   score: 67,  color: '#a78bfa' },
  { label: 'Moves Before Attacks Register',   weight: 4, tier: 'S-',   score: 72,  color: '#b91c1c' },
  { label: 'Beyond Reaction Limit',           weight: 4, tier: 'S',    score: 77,  color: '#dc2626' },
  { label: 'Time-Defying Reflexes',           weight: 4, tier: 'S+',   score: 81,  color: '#ef4444' },
  { label: 'Splits Probability to Dodge',     weight: 3, tier: 'SS-',  score: 85,  color: '#ea580c' },
  { label: 'Probabilistic Combat Evasion',    weight: 3, tier: 'SS',   score: 88,  color: '#f97316' },
  { label: 'Moves Between Moments',           weight: 3, tier: 'SS+',  score: 91,  color: '#fb923c' },
  { label: 'Causality-Immune Dodge',                        weight: 2, tier: 'SSS-',      score: 94,  color: '#ca8a04' },
  { label: 'Untouchable by Physical Law',                   weight: 2, tier: 'SSS',       score: 97,  color: '#eab308' },
  { label: 'The Concept of Missing Them',                   weight: 2, tier: 'SSS+',      score: 99,  color: '#fde047' },
  { label: 'Dodges Attacks From Adjacent Timelines',        weight: 2, tier: 'Z-',        score: 101, color: '#0e7490' },
  { label: 'Exists Between Coordinates',                    weight: 2, tier: 'Z',         score: 103, color: '#0891b2' },
  { label: 'Untouchable Across Multiple Dimensions',        weight: 2, tier: 'Z+',        score: 105, color: '#06b6d4' },
  { label: 'Moves Through the Gaps Between Realities',      weight: 1, tier: 'ZZ-',       score: 107, color: '#3730a3' },
  { label: 'Avoids Concepts as Well as Attacks',            weight: 1, tier: 'ZZ',        score: 109, color: '#4f46e5' },
  { label: 'Evasion That Makes Fate Reroute',               weight: 1, tier: 'ZZ+',       score: 111, color: '#818cf8' },
  { label: 'Transcends Spatial Limitation Entirely',        weight: 1, tier: 'ZZZ-',      score: 113, color: '#9d174d' },
  { label: 'Attacks Pass Through Memory of Their Location', weight: 1, tier: 'ZZZ',       score: 115, color: '#be185d' },
  { label: 'Physically Immune to Being Where an Attack Is', weight: 1, tier: 'ZZZ+',      score: 117, color: '#ec4899' },
  { label: 'Evades Divine Retribution Without Noticing',    weight: 1, tier: 'Celestial-',score: 119, color: '#075985' },
  { label: 'Dances Between Planes of Existence',            weight: 1, tier: 'Celestial', score: 121, color: '#0284c7' },
  { label: 'Even Omniscient Beings Lose Track of Them',     weight: 1, tier: 'Celestial+',score: 123, color: '#38bdf8' },
  { label: 'Evasion That Humiliates Omniscience',           weight: 1, tier: 'Godly-',    score: 125, color: '#c026d3' },
  { label: 'Dodged the Big Bang',                           weight: 1, tier: 'Godly',     score: 127, color: '#e879f9' },
  { label: 'Movement Predates the Laws of Physics',         weight: 1, tier: 'Primordial',score: 130, color: '#ffffff' },
]
