import type { FlavorLabel } from './types'

// Agility scale: F- = trips over flat ground, mortal mid = athletic gymnast,
// A range = elite acrobat / parkour pro, S = superhuman dodging,
// SS+ = reads bullet trajectories, Cosmic+ = post-mortal coordination,
// Infinite+ = beyond infinite agility.
export const agilityLabels: FlavorLabel[] = [
  { label: 'Trips Over Flat Ground',                         weight: 4, tier: 'F-',            score: 2,   color: '#4a4a4a' },
  { label: 'Walks Into Doorframes',                          weight: 4, tier: 'F',             score: 5,   color: '#5c5c5c' },
  { label: 'Drops Whatever They Pick Up',                    weight: 4, tier: 'F+',            score: 8,   color: '#6e6e6e' },
  { label: 'Awkward Coordination',                           weight: 6, tier: 'E-',            score: 11,  color: '#6b7280' },
  { label: 'Normal Hand-Eye',                                weight: 6, tier: 'E',             score: 14,  color: '#9ca3af' },
  { label: 'Decent Reflexes',                                weight: 6, tier: 'E+',            score: 17,  color: '#d1d5db' },
  { label: 'Recreational-League Quick',                      weight: 8, tier: 'D-',            score: 20,  color: '#92400e' },
  { label: 'Solid Footwork',                                 weight: 8, tier: 'D',             score: 23,  color: '#b45309' },
  { label: 'Quick Reaction Time',                            weight: 8, tier: 'D+',            score: 26,  color: '#d97706' },
  { label: 'Trained Gymnast',                                weight: 8, tier: 'C-',            score: 30,  color: '#1d4ed8' },
  { label: 'Parkour Practitioner',                           weight: 9, tier: 'C',             score: 34,  color: '#2563eb' },
  { label: 'Pro Acrobat',                                    weight: 8, tier: 'C+',            score: 38,  color: '#3b82f6' },
  { label: 'Elite Gymnast',                                  weight: 7, tier: 'B-',            score: 42,  color: '#065f46' },
  { label: 'Champion-Level Footwork',                        weight: 7, tier: 'B',             score: 47,  color: '#059669' },
  { label: 'Peak Human Coordination',                        weight: 7, tier: 'B+',            score: 52,  color: '#34d399' },
  { label: 'Olympic-Caliber Movement',                       weight: 5, tier: 'A-',            score: 57,  color: '#7c3aed' },
  { label: 'Moves Like Water',                               weight: 5, tier: 'A',             score: 62,  color: '#8b5cf6' },
  { label: 'Reads Movement Three Steps Ahead',               weight: 5, tier: 'A+',            score: 67,  color: '#a78bfa' },
  { label: 'Superhuman Reflexes',                            weight: 4, tier: 'S-',            score: 72,  color: '#b91c1c' },
  { label: 'Dodges Bullets at Close Range',                  weight: 4, tier: 'S',             score: 77,  color: '#dc2626' },
  { label: 'Reads Trajectories Mid-Flight',                  weight: 4, tier: 'S+',            score: 81,  color: '#ef4444' },
  { label: 'Untouchable in Close Quarters',                  weight: 3, tier: 'SS-',           score: 85,  color: '#ea580c' },
  { label: 'Slips Through Crossfire',                        weight: 3, tier: 'SS',            score: 88,  color: '#f97316' },
  { label: 'Moves Faster Than Reflex',                       weight: 3, tier: 'SS+',           score: 91,  color: '#fb923c' },
  { label: 'Sidesteps Outcomes',                             weight: 2, tier: 'SSS-',          score: 94,  color: '#ca8a04' },
  { label: 'Already Avoided Whatever Comes Next',            weight: 2, tier: 'SSS',           score: 97,  color: '#eab308' },
  { label: 'Never Where Strikes Land',                       weight: 2, tier: 'SSS+',          score: 99,  color: '#fde047' },
  { label: 'Reflexes Outpace Causation',                     weight: 2, tier: 'Z-',            score: 101, color: '#be185d' },
  { label: 'Dodges Through Multiple Realities',              weight: 2, tier: 'Z',             score: 103, color: '#db2777' },
  { label: 'Reflex Predates the Trigger',                    weight: 2, tier: 'Z+',            score: 105, color: '#ec4899' },
  { label: 'Steps Between Possibilities',                    weight: 1, tier: 'ZZ-',           score: 107, color: '#6d28d9' },
  { label: 'Avoids Outcomes That Have Not Happened',         weight: 1, tier: 'ZZ',            score: 109, color: '#7c3aed' },
  { label: 'Moves Without Movement',                         weight: 1, tier: 'ZZ+',           score: 111, color: '#8b5cf6' },
  { label: 'Coordination Defies Physics',                    weight: 1, tier: 'ZZZ-',          score: 113, color: '#0e7490' },
  { label: 'Reflex That Reality Cannot Catch',               weight: 1, tier: 'ZZZ',           score: 115, color: '#06b6d4' },
  { label: 'Every Motion Already Accounted For',             weight: 1, tier: 'ZZZ+',          score: 117, color: '#22d3ee' },
  { label: 'Cosmic-Scale Coordination',                      weight: 1, tier: 'Cosmic-',       score: 119, color: '#0e6b8a' },
  { label: 'Dances Through Galactic Storms',                 weight: 1, tier: 'Cosmic',        score: 121, color: '#0891b2' },
  { label: 'Galaxies Realign to Their Footwork',             weight: 1, tier: 'Cosmic+',       score: 123, color: '#06b6d4' },
  { label: 'Reflex That Outlives Time',                      weight: 1, tier: 'Immortal-',     score: 125, color: '#d946ef' },
  { label: 'Immortal-Class Footwork',                        weight: 1, tier: 'Immortal',      score: 127, color: '#ec4899' },
  { label: 'Has Always Been Just Out of Reach',              weight: 1, tier: 'Immortal+',     score: 129, color: '#f472b6' },
  { label: 'Eludes the Divine Themselves',                   weight: 1, tier: 'Celestial-',    score: 131, color: '#831843' },
  { label: 'Untouched by Any Celestial Sweep',               weight: 1, tier: 'Celestial',     score: 133, color: '#9d174d' },
  { label: 'Even Pantheons Cannot Lay a Hand on Them',       weight: 1, tier: 'Celestial+',    score: 135, color: '#be185d' },
  { label: 'Slips Past Divine Causation',                    weight: 1, tier: 'Godly-',        score: 137, color: '#f9a8d4' },
  { label: 'Cannot Be Trapped by Any God',                   weight: 1, tier: 'Godly',         score: 139, color: '#f472b6' },
  { label: 'Outmaneuvers the Divine Order Itself',           weight: 1, tier: 'Godly+',        score: 141, color: '#ec4899' },
  { label: 'Predates the Idea of "Catching" Things',         weight: 1, tier: 'Primordial-',   score: 143, color: '#d4d4d8' },
  { label: 'Authored the First Dodge',                       weight: 1, tier: 'Primordial',    score: 145, color: '#e4e4e7' },
  { label: 'Reality Has Never Touched Them',                 weight: 1, tier: 'Primordial+',   score: 147, color: '#fafafa' },
  { label: 'Absolutely Untouchable',                         weight: 1, tier: 'Absolute-',     score: 149, color: '#7dd3fc' },
  { label: 'Existence Cannot Tag Them',                      weight: 1, tier: 'Absolute',      score: 151, color: '#38bdf8' },
  { label: 'Out of Range of Anything That Reaches',          weight: 1, tier: 'Absolute+',     score: 153, color: '#0ea5e9' },
  { label: 'Beyond Motion as a Concept',                     weight: 1, tier: 'Transcendent-', score: 155, color: '#84cc16' },
  { label: 'Movement Transcends Itself Around Them',         weight: 1, tier: 'Transcendent',  score: 157, color: '#65a30d' },
  { label: 'They Are Never Found by Anything',               weight: 1, tier: 'Transcendent+', score: 159, color: '#4d7c0f' },
  { label: 'Infinite Agility',                               weight: 1, tier: 'Infinite-',     score: 161, color: '#525252' },
  { label: 'Truly Infinite Coordination',                    weight: 1, tier: 'Infinite',      score: 163, color: '#262626' },
  { label: 'Beyond Infinite Reflex',                         weight: 1, tier: 'Infinite+',     score: 165, color: '#000000' },
]
