// archetypes.ts — Archetype content data for Wheel of Fate.
// 35 archetypes across classic fantasy, fiction-inspired, comedic, and special-mechanic types.
// Special mechanic fields:
//   statModifiers         — probability multipliers per stat (>1 boosts toward high tiers, <1 pushes low)
//   customAbilityPool     — overrides ability pool (Stand names, breathing styles, titan forms, etc.)
//   abilitySpinDisplayName — renames the ability spin slots (e.g. "Stand", "Breathing Style")
//   statBonusGrants       — stat bonus/penalty spins spliced immediately after archetype lands
//   extraPowerSpins       — additional power spins
//   bonusWeaponSpins      — additional weapon spins (dual wielders, gadgeteers)
//   bonusSpins            — arbitrary extra spins (e.g. Possession: possessionRace + possessionStrength)
//   grantedPowers         — auto-injected powers (no spin required)

import type { Archetype } from './types'

export const archetypes: Archetype[] = [
  {
    label: 'Warrior',
    weight: 6,
    archetypeType: 'Fighter',
    abilitySpinCount: 2,
    description: 'Solves most problems with direct application of force.',
    statBonusGrants: { strength: 'statBonus', fightingSkill: 'statBonus' },
    statModifiers: { strength: 1.4, durability: 1.3, fightingSkill: 1.3, iq: 0.8, charisma: 0.85 },
    weaponTypeBias: { Melee: 2.5, Ancient: 1.3, Ranged: 0.6, Magical: 0.4, None: 0.3 },
    armorTypeBias: { 'Full-Suit': 2.2, 'Half-Suit': 1.5, Ancient: 1.8, None: 0.2, 'Helmet Only': 0.7 },
    abilities: [
      { label: 'Battle Hardened', weight: 3, element: 'Earth', grade: 'C' },
      { label: 'Shield Wall', weight: 3, element: 'Neutral', grade: 'C' },
      { label: 'Weapon Mastery', weight: 2, element: 'Neutral', grade: 'C' },
      { label: "Soldier's Endurance", weight: 3 },
      { label: 'War Cry', weight: 2, element: 'Neutral', grade: 'C' },
      { label: 'Second Wind', weight: 2, element: 'Wind', grade: 'C' },
      { label: 'Blade Storm', weight: 1, element: 'Lightning', grade: 'B' },
      { label: 'Unbreakable Will', weight: 1, element: 'Neutral', grade: 'B' },
    ],
  },

  {
    label: 'Mage',
    weight: 5,
    archetypeType: 'Spellcaster',
    abilitySpinCount: 3,
    description: 'Bends reality via intensive study and questionable decisions.',
    extraPowerSpins: 1,
    statBonusGrants: { iq: 'statBonus' },
    statModifiers: { iq: 1.6, energyLevel: 1.3, powerMastery: 1.4, strength: 0.65, durability: 0.75, fightingSkill: 0.8 },
    weaponTypeBias: { Magical: 3.5, Cursed: 1.2, None: 1.5, Melee: 0.5, Ranged: 0.5, Exotic: 1.2 },
    armorTypeBias: { None: 1.8, 'Helmet Only': 1.2, Exotic: 1.5, 'Half-Suit': 0.7, 'Full-Suit': 0.3 },
    abilities: [
      { label: 'Arcane Surge', weight: 3, element: 'Arcane', grade: 'C' },
      { label: 'Counterspell', weight: 2, element: 'Arcane', grade: 'C' },
      { label: 'Mana Shield', weight: 3, element: 'Arcane', grade: 'C' },
      { label: 'Ritual Magic', weight: 2, element: 'Arcane', grade: 'C' },
      { label: 'Ley Line Tap', weight: 2, element: 'Arcane', grade: 'C' },
      { label: 'Spell Amplification', weight: 2, element: 'Arcane', grade: 'C' },
      { label: 'Forbidden Tome', weight: 1, element: 'Arcane', grade: 'B' },
      { label: 'Reality Fracture', weight: 1, element: 'Arcane', grade: 'B' },
    ],
  },

  {
    label: 'Rogue',
    weight: 5,
    archetypeType: 'Shadow',
    abilitySpinCount: 2,
    description: 'Prefers to work in the shadows, usually for unclear reasons.',
    statBonusGrants: { agility: 'statBonus', speed: 'statBonus' },
    statModifiers: { agility: 1.5, speed: 1.4, fightingSkill: 1.2, charisma: 1.1, strength: 0.85, durability: 0.8 },
    weaponTypeBias: { Melee: 1.5, Ranged: 1.5, Exotic: 2.0, Cursed: 1.5, None: 1.0, Magical: 0.5 },
    armorTypeBias: { Exotic: 2.0, 'Half-Suit': 1.5, 'Helmet Only': 1.3, None: 1.0, 'Full-Suit': 0.3 },
    abilities: [
      { label: 'Backstab', weight: 3, element: 'Shadow', grade: 'C' },
      { label: 'Shadow Step', weight: 2, element: 'Shadow', grade: 'C' },
      { label: 'Pick Pocket', weight: 3, element: 'Shadow', grade: 'C' },
      { label: 'Poison Coating', weight: 2, element: 'Poison', grade: 'C' },
      { label: 'Evasion', weight: 2, element: 'Shadow', grade: 'C' },
      { label: 'Death Mark', weight: 1, element: 'Shadow', grade: 'B' },
      { label: 'Master Disguise', weight: 2, element: 'Shadow', grade: 'C' },
      { label: 'Unseen Strike', weight: 1, element: 'Shadow', grade: 'B' },
    ],
  },

  {
    label: 'Superhero',
    weight: 5,
    archetypeType: 'Powered',
    abilitySpinCount: 2,
    description: 'Has a code, a costume, and a complicated relationship with authority.',
    statBonusGrants: { strength: 'statBonus', durability: 'statBonus' },
    statModifiers: { strength: 1.5, speed: 1.3, durability: 1.4, charisma: 1.3, potential: 1.2 },
    weaponTypeBias: { Exotic: 1.8, Melee: 1.2, Ranged: 1.2, None: 1.0, Magical: 0.8, Cursed: 0.5 },
    armorTypeBias: { Exotic: 2.5, 'Half-Suit': 1.5, 'Full-Suit': 1.2, 'Helmet Only': 0.8, None: 0.5 },
    abilities: [
      { label: 'Heroic Resolve', weight: 3, element: 'Neutral', grade: 'B' },
      { label: 'Never-Give-Up Punch', weight: 3, element: 'Neutral', grade: 'B' },
      { label: 'Civilian Protection Protocol', weight: 2, element: 'Neutral', grade: 'B' },
      { label: 'Power Restraint', weight: 2, element: 'Water', grade: 'B' },
      { label: 'Inspirational Speech', weight: 2, element: 'Neutral', grade: 'B' },
      { label: 'Iconic Finishing Move', weight: 1, element: 'Neutral', grade: 'B' },
      { label: 'One For All', weight: 1, element: 'Neutral', grade: 'S' },
      { label: 'Detroit Smash', weight: 1, element: 'Neutral', grade: 'S' },
    ],
  },

  {
    label: 'Paladin',
    weight: 4,
    archetypeType: 'Holy Knight',
    abilitySpinCount: 2,
    description: 'Divine warrior who will remind you of their oaths unbidden.',
    statBonusGrants: { durability: 'statBonus', charisma: 'statBonus' },
    statModifiers: { durability: 1.5, charisma: 1.4, strength: 1.2, speed: 0.85, agility: 0.85 },
    grantedWeapons: ['Holy Warhammer'],
    weaponTypeBias: { Melee: 3.0, Ancient: 1.8, None: 0.2, Ranged: 0.5, Magical: 0.8, Cursed: 0.1 },
    armorTypeBias: { 'Full-Suit': 3.0, Ancient: 2.5, 'Half-Suit': 1.5, 'Helmet Only': 0.5, None: 0.1 },
    abilities: [
      { label: 'Divine Smite', weight: 3, element: 'Light', grade: 'B' },
      { label: 'Lay on Hands', weight: 3, element: 'Light', grade: 'B' },
      { label: 'Holy Aura', weight: 2, element: 'Light', grade: 'C' },
      { label: 'Turn Undead', weight: 2, element: 'Soul', grade: 'B' },
      { label: 'Sacred Vow', weight: 2, element: 'Light', grade: 'B' },
      { label: 'Radiant Shield', weight: 2, element: 'Light', grade: 'C' },
      { label: 'Celestial Weapon', weight: 1, element: 'Light', grade: 'B' },
      { label: 'Angelic Intervention', weight: 1, element: 'Light', grade: 'B' },
    ],
  },

  {
    label: 'Ranger',
    weight: 4,
    archetypeType: 'Hunter',
    abilitySpinCount: 2,
    description: 'At home in the wilderness. Suspicious of architecture.',
    statBonusGrants: { speed: 'statBonus', agility: 'statBonus' },
    statModifiers: { speed: 1.4, agility: 1.3, fightingSkill: 1.2, iq: 1.2, strength: 0.9 },
    weaponTypeBias: { Ranged: 4.0, Melee: 0.8, Exotic: 1.2, Magical: 0.5, None: 0.5 },
    armorTypeBias: { 'Half-Suit': 1.8, 'Helmet Only': 1.2, None: 1.0, Exotic: 1.5, 'Full-Suit': 0.4 },
    abilities: [
      { label: "Tracker's Eye", weight: 3 },
      { label: 'Favored Terrain', weight: 3, element: 'Water', grade: 'C' },
      { label: 'Arrow Rain', weight: 2, element: 'Water', grade: 'C' },
      { label: 'Beast Bond', weight: 2, element: 'Nature', grade: 'C' },
      { label: "Hunter's Mark", weight: 2 },
      { label: 'Camouflage', weight: 2, element: 'Shadow', grade: 'C' },
      { label: "Predator's Instinct", weight: 1 },
      { label: 'Wilderness Communion', weight: 1, element: 'Nature', grade: 'C' },
    ],
  },

  {
    label: 'Bard',
    weight: 4,
    archetypeType: 'Performer',
    abilitySpinCount: 2,
    description: 'Weaponises music, poetry, and audacity.',
    statBonusGrants: { charisma: 'statBonus' },
    statModifiers: { charisma: 1.8, iq: 1.3, strength: 0.65, durability: 0.75, fightingSkill: 0.7 },
    weaponTypeBias: { Exotic: 2.5, Magical: 1.5, None: 1.5, Ranged: 0.8, Melee: 0.7, Cursed: 0.8 },
    armorTypeBias: { None: 2.0, Exotic: 1.5, 'Helmet Only': 0.8, 'Half-Suit': 0.8, 'Full-Suit': 0.2 },
    abilities: [
      { label: 'Inspire Courage', weight: 3, element: 'Time', grade: 'C' },
      { label: 'Cutting Words', weight: 2, element: 'Sound', grade: 'C' },
      { label: 'Song of Rest', weight: 3, element: 'Sound', grade: 'C' },
      { label: 'Hypnotic Melody', weight: 2, element: 'Sound', grade: 'C' },
      { label: 'Lore Master', weight: 2, element: 'Sound', grade: 'C' },
      { label: 'Silver Tongue', weight: 2, element: 'Sound', grade: 'C' },
      { label: 'Epic Ballad', weight: 1, element: 'Sound', grade: 'C' },
      { label: 'World-Ending Encore', weight: 1, element: 'Sound', grade: 'C' },
    ],
  },

  {
    label: 'Cleric',
    weight: 4,
    archetypeType: 'Divine',
    abilitySpinCount: 2,
    description: "Divine conduit. God's chosen errand-runner.",
    statBonusGrants: { durability: 'statBonus' },
    statModifiers: { durability: 1.4, charisma: 1.3, energyLevel: 1.2, strength: 0.8 },
    weaponTypeBias: { Melee: 2.0, Ancient: 1.5, Magical: 1.5, None: 0.8, Ranged: 0.5, Cursed: 0.3 },
    armorTypeBias: { 'Full-Suit': 2.0, 'Half-Suit': 1.8, Ancient: 1.5, 'Helmet Only': 0.8, Exotic: 0.6, None: 0.3 },
    abilities: [
      { label: 'Channel Divinity', weight: 3, element: 'Light', grade: 'C' },
      { label: 'Divine Word', weight: 2, element: 'Light', grade: 'C' },
      { label: 'Sacred Flame', weight: 3, element: 'Fire', grade: 'C' },
      { label: 'Blessed Healer', weight: 2, element: 'Light', grade: 'C' },
      { label: 'Spiritual Weapon', weight: 2, element: 'Arcane', grade: 'C' },
      { label: 'Divine Intervention', weight: 1, element: 'Light', grade: 'C' },
      { label: 'Holy Ground', weight: 2, element: 'Light', grade: 'C' },
      { label: 'Avatar of the Divine', weight: 1, element: 'Light', grade: 'C' },
    ],
  },

  {
    label: 'Anti-Hero',
    weight: 4,
    archetypeType: 'Morally Grey',
    abilitySpinCount: 2,
    description: 'Does the right thing, badly, with maximum collateral damage.',
    statBonusGrants: { fightingSkill: 'statBonus' },
    statModifiers: { fightingSkill: 1.4, agility: 1.3, durability: 1.2, charisma: 0.75 },
    weaponTypeBias: { Cursed: 2.0, Melee: 1.5, Ranged: 1.5, Exotic: 1.2, Ancient: 0.8, Magical: 0.8, None: 0.8 },
    armorTypeBias: { 'Half-Suit': 1.8, Exotic: 1.5, 'Helmet Only': 1.2, None: 0.8, Ancient: 0.8, 'Full-Suit': 0.5 },
    abilities: [
      { label: 'Moral Ambiguity', weight: 3, element: 'Shadow', grade: 'B' },
      { label: 'Lethal Force Authorized', weight: 2, element: 'Shadow', grade: 'B' },
      { label: 'Trauma Response Combat', weight: 2, element: 'Shadow', grade: 'C' },
      { label: 'Reluctant Ally', weight: 3, element: 'Shadow', grade: 'B' },
      { label: 'Not Actually Sorry', weight: 2, element: 'Shadow', grade: 'B' },
      { label: 'Regeneration (Inconvenient)', weight: 2, element: 'Nature', grade: 'B' },
      { label: 'Maximum Effort', weight: 1, element: 'Shadow', grade: 'B' },
      { label: 'Fourth Wall Advisory', weight: 1, element: 'Shadow', grade: 'B' },
    ],
  },

  {
    label: 'Demon Slayer',
    weight: 4,
    archetypeType: 'Breathing Style',
    abilitySpinCount: 2,
    description: 'Trained in Breathing Techniques. The demons are in real trouble.',
    abilitySpinDisplayName: 'Breathing Style',
    statBonusGrants: { fightingSkill: 'statBonus', speed: 'statBonus' },
    statModifiers: { fightingSkill: 1.5, speed: 1.5, agility: 1.3, energyLevel: 1.3, durability: 1.1, iq: 0.9 },
    grantedWeapons: ['Nichirin Blade (Katana)'],
    weaponTypeBias: { Melee: 4.0, Ancient: 1.5, Exotic: 1.0, Cursed: 0.5, Ranged: 0.3, Magical: 0.3, None: 0.3 },
    armorTypeBias: { 'Half-Suit': 2.0, 'Helmet Only': 1.5, None: 1.2, Exotic: 1.0, Ancient: 0.6, 'Full-Suit': 0.4 },
    abilities: [],
    customAbilityPool: [
      { label: 'Flame Breathing',          weight: 3 },
      { label: 'Water Breathing',          weight: 3 },
      { label: 'Thunder Breathing',        weight: 2 },
      { label: 'Stone Breathing',          weight: 2 },
      { label: 'Wind Breathing',           weight: 2 },
      { label: 'Serpent Breathing',        weight: 2 },
      { label: 'Insect Breathing',         weight: 2 },
      { label: 'Love Breathing',           weight: 2 },
      { label: 'Sound Breathing',          weight: 2 },
      { label: 'Mist Breathing',           weight: 2 },
      { label: 'Beast Breathing',          weight: 2 },
      { label: 'Flower Breathing',         weight: 2 },
      { label: 'Moon Breathing',           weight: 1 },
      { label: 'Hinokami Kagura (Sun Breathing)', weight: 1 },
    ],
  },

  {
    label: 'Shinobi',
    weight: 4,
    archetypeType: 'Ninja',
    abilitySpinCount: 3,
    description: 'Mastery of chakra, deception, and dying dramatically.',
    statBonusGrants: { agility: 'statBonus', speed: 'statBonus' },
    statModifiers: { agility: 1.6, speed: 1.5, fightingSkill: 1.3, iq: 1.2, strength: 0.85, durability: 0.85 },
    weaponTypeBias: { Melee: 2.5, Exotic: 2.5, Ranged: 1.5, None: 0.8, Cursed: 0.8, Ancient: 0.5, Magical: 0.4 },
    armorTypeBias: { Exotic: 2.0, None: 1.5, 'Half-Suit': 1.5, 'Helmet Only': 1.2, Ancient: 0.5, 'Full-Suit': 0.2 },
    abilities: [
      { label: 'Ninjutsu — Shadow Clone', weight: 3, element: 'Shadow', grade: 'B' },
      { label: 'Genjutsu — Illusion Bind', weight: 2, element: 'Psychic', grade: 'B' },
      { label: 'Taijutsu — Eight Gates', weight: 1, element: 'Wind', grade: 'A' },
      { label: 'Rasengan', weight: 2, element: 'Wind', grade: 'B' },
      { label: 'Sharingan Insight', weight: 2, element: 'Wind', grade: 'B' },
      { label: 'Sage Mode', weight: 1, element: 'Time', grade: 'A' },
      { label: 'Summoning Jutsu', weight: 2, element: 'Wind', grade: 'B' },
      { label: 'Six Paths Chakra', weight: 1, element: 'Wind', grade: 'SS' },
    ],
  },

  {
    label: 'Berserker',
    weight: 3,
    archetypeType: 'Rage',
    abilitySpinCount: 1,
    description: 'Combat strategy: rage. Follow-up strategy: also rage.',
    statBonusGrants: { strength: 'statBonus', durability: 'statBonus', iq: 'statPenalty' },
    statModifiers: { strength: 1.7, durability: 1.5, fightingSkill: 1.2, iq: 0.55, charisma: 0.65, agility: 0.85 },
    weaponTypeBias: { Melee: 3.5, Ancient: 2.0, Cursed: 1.5, None: 0.6, Ranged: 0.4, Exotic: 0.5, Magical: 0.3 },
    armorTypeBias: { None: 1.5, Ancient: 1.5, 'Half-Suit': 1.2, 'Helmet Only': 1.0, 'Full-Suit': 0.8, Exotic: 0.5 },
    abilities: [
      { label: 'Frenzied Rage', weight: 3, element: 'Time', grade: 'B' },
      { label: 'Pain Resistance', weight: 3, element: 'Fire', grade: 'B' },
      { label: 'Reckless Attack', weight: 2, element: 'Fire', grade: 'B' },
      { label: 'Intimidating Presence', weight: 2, element: 'Psychic', grade: 'B' },
      { label: 'Feral Instinct', weight: 2, element: 'Nature', grade: 'C' },
      { label: 'Mindless Fury', weight: 2, element: 'Fire', grade: 'B' },
      { label: "Death's Door Surge", weight: 1 },
    ],
  },

  {
    label: 'Monk',
    weight: 3,
    archetypeType: 'Martial Arts',
    abilitySpinCount: 2,
    description: 'Inner peace achieved through punching things.',
    statBonusGrants: { agility: 'statBonus', fightingSkill: 'statBonus' },
    statModifiers: { fightingSkill: 1.7, agility: 1.5, speed: 1.3, energyLevel: 1.3, strength: 0.9, durability: 1.1 },
    weaponTypeBias: { None: 3.5, Exotic: 1.5, Melee: 0.8, Ancient: 0.5, Magical: 0.5, Ranged: 0.3, Cursed: 0.3 },
    armorTypeBias: { None: 2.5, Exotic: 1.5, 'Helmet Only': 0.8, 'Half-Suit': 0.8, Ancient: 0.5, 'Full-Suit': 0.2 },
    abilities: [
      { label: 'Flurry of Blows', weight: 3, element: 'Neutral', grade: 'B' },
      { label: 'Ki Blast', weight: 2, element: 'Neutral', grade: 'C' },
      { label: 'Deflect Missiles', weight: 2, element: 'Neutral', grade: 'B' },
      { label: 'Stillness of Mind', weight: 3, element: 'Psychic', grade: 'B' },
      { label: 'Step of the Wind', weight: 2, element: 'Wind', grade: 'B' },
      { label: 'Iron Body', weight: 2, element: 'Metal', grade: 'B' },
      { label: 'Empty Palm', weight: 1, element: 'Neutral', grade: 'B' },
      { label: 'One With Everything', weight: 1, element: 'Neutral', grade: 'B' },
    ],
  },

  {
    label: 'Dual Wielder',
    weight: 3,
    archetypeType: 'Fighter',
    abilitySpinCount: 1,
    description: 'Twice the blades, twice the chaos, zero spatial awareness.',
    bonusWeaponSpins: 1,
    statBonusGrants: { speed: 'statBonus', agility: 'statBonus' },
    statModifiers: { speed: 1.4, agility: 1.4, fightingSkill: 1.3, durability: 0.85 },
    weaponTypeBias: { Melee: 3.5, Exotic: 1.5, Cursed: 1.2, Ancient: 1.0, Ranged: 0.5, Magical: 0.5, None: 0.2 },
    armorTypeBias: { 'Half-Suit': 2.0, Exotic: 1.5, 'Helmet Only': 1.0, 'Full-Suit': 0.8, Ancient: 0.8, None: 0.5 },
    abilities: [
      { label: 'Ambidextrous Strike', weight: 3, element: 'Metal', grade: 'C' },
      { label: 'Twin Flourish', weight: 3, element: 'Metal', grade: 'C' },
      { label: 'Parry and Riposte', weight: 2, element: 'Metal', grade: 'C' },
      { label: 'Blade Dance', weight: 2, element: 'Metal', grade: 'C' },
      { label: 'Cross Counter', weight: 2, element: 'Metal', grade: 'C' },
      { label: 'Death By a Thousand Cuts', weight: 1, element: 'Soul', grade: 'C' },
    ],
  },

  {
    label: 'Supervillain',
    weight: 3,
    archetypeType: 'Villain',
    abilitySpinCount: 2,
    description: 'Grand ambitions. Elaborate lair. Refuses to just shoot the hero.',
    statBonusGrants: { iq: 'statBonus' },
    statModifiers: { iq: 1.4, charisma: 1.3, fightingSkill: 1.1, strength: 0.9 },
    weaponTypeBias: { Exotic: 2.5, Magical: 2.0, Cursed: 1.5, Ranged: 1.5, None: 1.0, Melee: 0.7, Ancient: 0.5 },
    armorTypeBias: { Exotic: 2.5, 'Full-Suit': 1.8, None: 1.0, 'Half-Suit': 0.8, Ancient: 0.8, 'Helmet Only': 0.8 },
    abilities: [
      { label: 'World Domination Plan', weight: 3, element: 'Shadow', grade: 'B' },
      { label: 'Minion Army', weight: 3, element: 'Shadow', grade: 'B' },
      { label: 'Monologue Mastery', weight: 2, element: 'Shadow', grade: 'C' },
      { label: 'Evil Lair Fortress', weight: 2, element: 'Earth', grade: 'B' },
      { label: 'Doomsday Device Mk. II', weight: 2, element: 'Ice', grade: 'B' },
      { label: 'Tragic Backstory Buff', weight: 2, element: 'Shadow', grade: 'B' },
      { label: 'Redemption Arc Resistance', weight: 1, element: 'Shadow', grade: 'B' },
      { label: 'I Am The Hero Speech', weight: 1, element: 'Shadow', grade: 'B' },
    ],
  },

  {
    label: 'Bounty Hunter',
    weight: 3,
    archetypeType: 'Mercenary',
    abilitySpinCount: 2,
    description: 'This is the way. Payment up front. No disintegrations.',
    bonusWeaponSpins: 1,
    statBonusGrants: { fightingSkill: 'statBonus' },
    statModifiers: { agility: 1.3, speed: 1.3, iq: 1.2, fightingSkill: 1.3, durability: 1.1 },
    weaponTypeBias: { Ranged: 3.0, Exotic: 2.5, Melee: 1.0, Cursed: 0.8, Ancient: 0.5, Magical: 0.5, None: 0.5 },
    armorTypeBias: { Exotic: 2.5, 'Half-Suit': 2.0, 'Helmet Only': 1.8, 'Full-Suit': 1.5, None: 0.3, Ancient: 0.5 },
    abilities: [
      { label: 'Target Acquired', weight: 3, element: 'Neutral', grade: 'C' },
      { label: 'Whistling Bird Missiles', weight: 2, element: 'Neutral', grade: 'C' },
      { label: 'Jetpack Assault', weight: 2, element: 'Neutral', grade: 'C' },
      { label: 'Beskar Armor', weight: 2, element: 'Neutral', grade: 'C' },
      { label: 'Grappling Hook Takedown', weight: 2, element: 'Neutral', grade: 'C' },
      { label: 'I Have Spoken', weight: 2, element: 'Neutral', grade: 'C' },
      { label: 'Whistling Bird Salvo', weight: 1, element: 'Neutral', grade: 'C' },
    ],
  },

  {
    label: 'Stand User',
    weight: 3,
    archetypeType: 'Stand',
    abilitySpinCount: 1,
    description: 'Manifests a spiritual entity of immeasurable power. Ora ora ora.',
    abilitySpinDisplayName: 'Stand',
    statBonusGrants: { potential: 'statBonus', energyLevel: 'statBonus' },
    statModifiers: { potential: 1.5, energyLevel: 1.4, iq: 1.2, fightingSkill: 1.2 },
    weaponTypeBias: { None: 4.0, Melee: 1.0, Exotic: 1.0, Cursed: 0.8, Ranged: 0.5, Magical: 0.5, Ancient: 0.5 },
    armorTypeBias: { None: 3.0, Exotic: 1.5, 'Helmet Only': 0.8, 'Half-Suit': 0.5, 'Full-Suit': 0.2, Ancient: 0.3 },
    abilities: [],
    customAbilityPool: [
      { label: 'Star Platinum',             weight: 2 },
      { label: 'The World',                 weight: 2 },
      { label: 'Crazy Diamond',             weight: 3 },
      { label: 'Gold Experience',           weight: 2 },
      { label: 'King Crimson',              weight: 2 },
      { label: 'Sticky Fingers',            weight: 3 },
      { label: 'Moody Blues',              weight: 3 },
      { label: 'Sex Pistols',              weight: 3 },
      { label: 'Purple Haze',              weight: 2 },
      { label: 'White Album',              weight: 2 },
      { label: 'Stone Free',               weight: 2 },
      { label: 'Weather Report',           weight: 2 },
      { label: 'Diver Down',               weight: 2 },
      { label: 'D4C — Love Train',          weight: 1 },
      { label: 'Tusk Act 4',               weight: 1 },
      { label: 'Soft & Wet',               weight: 2 },
      { label: 'The Hand',                 weight: 2 },
      { label: 'Echoes Act 3',             weight: 2 },
      { label: "Heaven's Door",            weight: 2 },
      { label: 'Hermit Purple',            weight: 3 },
      { label: "Magician's Red",           weight: 3 },
      { label: 'Hierophant Green',         weight: 3 },
      { label: 'Silver Chariot',           weight: 3 },
      { label: 'Beach Boy',                weight: 2 },
      { label: 'Notorious B.I.G.',         weight: 1 },
      { label: 'Grateful Dead',            weight: 2 },
      { label: 'Metallica',                weight: 2 },
      { label: 'Spice Girl',               weight: 2 },
      { label: 'Scary Monsters',           weight: 1 },
      { label: 'Bohemian Rhapsody',        weight: 1 },
      { label: 'Gold Experience Requiem',  weight: 1 },
      { label: 'Made in Heaven',           weight: 1 },
    ],
  },

  {
    label: 'Nen Hunter',
    weight: 3,
    archetypeType: 'Nen',
    abilitySpinCount: 1,
    description: 'Licensed Hunter. Nen-trained. Dangerous and chronically underpaid.',
    abilitySpinDisplayName: 'Nen Type',
    extraPowerSpins: 1,
    statBonusGrants: { energyLevel: 'statBonus', potential: 'statBonus' },
    statModifiers: { energyLevel: 1.6, potential: 1.5, fightingSkill: 1.3, iq: 1.1 },
    weaponTypeBias: { Exotic: 2.5, Melee: 2.0, None: 1.5, Ranged: 1.0, Cursed: 0.5, Magical: 0.5, Ancient: 0.5 },
    armorTypeBias: { None: 2.0, 'Half-Suit': 1.5, Exotic: 1.5, 'Helmet Only': 1.0, Ancient: 0.5, 'Full-Suit': 0.3 },
    abilities: [],
    customAbilityPool: [
      { label: 'Enhancer — Amplify Physical Ability', weight: 4 },
      { label: 'Transmuter — Alter Aura Properties',  weight: 4 },
      { label: 'Emitter — Project Aura at Range',     weight: 4 },
      { label: 'Conjurer — Materialize Objects',      weight: 3 },
      { label: 'Manipulator — Control Living Things', weight: 3 },
      { label: 'Specialist — Unknown Nen Category',   weight: 1 },
    ],
  },

  {
    label: 'Esper',
    weight: 3,
    archetypeType: 'Psychic',
    abilitySpinCount: 3,
    description: 'Psychic to a dangerous degree. Tries very hard not to explode.',
    extraPowerSpins: 1,
    statBonusGrants: { iq: 'statBonus', potential: 'statBonus' },
    statModifiers: { iq: 1.7, potential: 1.6, energyLevel: 1.3, strength: 0.65, durability: 0.7, fightingSkill: 0.8 },
    weaponTypeBias: { None: 4.0, Magical: 1.5, Exotic: 1.0, Ranged: 0.5, Melee: 0.4, Cursed: 0.5, Ancient: 0.3 },
    armorTypeBias: { None: 3.0, Exotic: 1.5, 'Helmet Only': 0.5, 'Half-Suit': 0.3, Ancient: 0.3, 'Full-Suit': 0.1 },
    abilities: [
      { label: 'Telekinesis', weight: 3, element: 'Psychic', grade: 'B' },
      { label: 'Telepathy', weight: 2, element: 'Psychic', grade: 'B' },
      { label: 'Psychic Barrier', weight: 2, element: 'Psychic', grade: 'B' },
      { label: '???% Release', weight: 1, element: 'Psychic', grade: 'B' },
      { label: 'Astral Projection', weight: 2, element: 'Cosmic', grade: 'B' },
      { label: 'Emotion Amplification', weight: 2, element: 'Psychic', grade: 'B' },
      { label: 'Mind Crush', weight: 1, element: 'Psychic', grade: 'B' },
      { label: 'World Destruction Sneeze', weight: 1, element: 'Psychic', grade: 'B' },
    ],
  },

  {
    label: 'Cursed Sorcerer',
    weight: 3,
    archetypeType: 'Cursed Technique',
    abilitySpinCount: 1,
    description: 'Channels cursed energy through a personal technique. Smells like regret.',
    abilitySpinDisplayName: 'Cursed Technique',
    statBonusGrants: { strength: 'statBonus', energyLevel: 'statBonus' },
    statModifiers: { fightingSkill: 1.5, energyLevel: 1.4, strength: 1.2, durability: 1.1, iq: 1.1 },
    weaponTypeBias: { Cursed: 3.0, Melee: 2.5, Exotic: 1.5, None: 1.0, Magical: 0.8, Ancient: 0.6, Ranged: 0.4 },
    armorTypeBias: { None: 1.5, Exotic: 2.0, 'Half-Suit': 1.5, 'Helmet Only': 1.0, Ancient: 0.5, 'Full-Suit': 0.3 },
    abilities: [],
    customAbilityPool: [
      { label: 'Limitless — Infinite Space',          weight: 2 },
      { label: 'Ten Shadows Technique',               weight: 2 },
      { label: 'Idle Transfiguration',                weight: 2 },
      { label: 'Cursed Speech',                       weight: 3 },
      { label: 'Boogie Woogie',                       weight: 3 },
      { label: 'Blood Manipulation',                  weight: 3 },
      { label: 'Projection Sorcery',                  weight: 2 },
      { label: 'Collapse',                            weight: 3 },
      { label: 'Ratio Technique',                     weight: 2 },
      { label: 'Divergent Fist',                      weight: 3 },
      { label: 'Contract King — Binding Vow',         weight: 2 },
      { label: 'Reverse Cursed Technique',            weight: 1 },
      { label: 'Hollow — Purple (Six Eyes)',           weight: 1 },
    ],
  },

  {
    label: 'Necromancer',
    weight: 2,
    archetypeType: 'Death Magic',
    abilitySpinCount: 3,
    description: 'Death is just a resource management problem.',
    grantedPowers: ['Undead Minion'],
    statBonusGrants: { iq: 'statBonus', strength: 'statPenalty' },
    statModifiers: { iq: 1.5, energyLevel: 1.3, powerMastery: 1.3, strength: 0.65, durability: 0.65, agility: 0.8 },
    weaponTypeBias: { Magical: 2.5, Cursed: 2.5, None: 1.5, Ancient: 0.8, Exotic: 0.8, Melee: 0.6, Ranged: 0.4 },
    armorTypeBias: { None: 1.8, Exotic: 1.2, 'Helmet Only': 1.0, Ancient: 0.8, 'Half-Suit': 0.6, 'Full-Suit': 0.2 },
    abilities: [
      { label: 'Raise Dead', weight: 3, element: 'Soul', grade: 'B' },
      { label: 'Soul Drain', weight: 2, element: 'Water', grade: 'B' },
      { label: 'Bone Armor', weight: 3, element: 'Soul', grade: 'B' },
      { label: 'Death Coil', weight: 2, element: 'Soul', grade: 'B' },
      { label: "Lich's Focus", weight: 2 },
      { label: 'Plague Burst', weight: 2, element: 'Poison', grade: 'B' },
      { label: 'Soul Bind', weight: 1, element: 'Soul', grade: 'B' },
      { label: 'Army of the Dead', weight: 1, element: 'Soul', grade: 'B' },
    ],
  },

  {
    label: 'Druid',
    weight: 2,
    archetypeType: 'Nature',
    abilitySpinCount: 3,
    description: "Nature's spokesperson. Takes the role very seriously.",
    extraPowerSpins: 1,
    statBonusGrants: { durability: 'statBonus' },
    statModifiers: { iq: 1.3, energyLevel: 1.3, durability: 1.2, charisma: 1.2, strength: 0.9 },
    weaponTypeBias: { Ancient: 2.0, None: 2.0, Melee: 1.5, Exotic: 1.5, Magical: 1.0, Ranged: 0.8, Cursed: 0.3 },
    armorTypeBias: { Exotic: 2.0, Ancient: 1.8, None: 1.5, 'Helmet Only': 1.0, 'Half-Suit': 0.8, 'Full-Suit': 0.4 },
    abilities: [
      { label: 'Wild Shape', weight: 3, element: 'Nature', grade: 'C' },
      { label: 'Entangle', weight: 2, element: 'Nature', grade: 'C' },
      { label: 'Barkskin', weight: 3, element: 'Nature', grade: 'C' },
      { label: 'Call Lightning', weight: 2, element: 'Lightning', grade: 'C' },
      { label: 'Speak with Animals', weight: 2, element: 'Nature', grade: 'C' },
      { label: 'Regrowth', weight: 2, element: 'Nature', grade: 'C' },
      { label: "Nature's Wrath", weight: 1 },
      { label: 'Verdant Avatar', weight: 1, element: 'Nature', grade: 'C' },
    ],
  },

  {
    label: 'Artificer',
    weight: 2,
    archetypeType: 'Tech-Mage',
    abilitySpinCount: 2,
    description: 'Builds magical gadgets. Safety is a suggestion.',
    bonusWeaponSpins: 1,
    statBonusGrants: { iq: 'statBonus', strength: 'statPenalty' },
    statModifiers: { iq: 1.6, strength: 0.75, agility: 0.85, fightingSkill: 0.8 },
    weaponTypeBias: { Exotic: 3.5, Ranged: 2.0, Magical: 1.5, None: 0.8, Ancient: 0.5, Melee: 0.5, Cursed: 0.3 },
    armorTypeBias: { Exotic: 3.5, 'Half-Suit': 1.5, 'Full-Suit': 1.0, 'Helmet Only': 1.0, None: 0.5, Ancient: 0.5 },
    abilities: [
      { label: "Tinker's Tools", weight: 3 },
      { label: 'Infuse Item', weight: 2, element: 'Metal', grade: 'C' },
      { label: 'Flash Bomb', weight: 2, element: 'Metal', grade: 'C' },
      { label: 'Automaton Companion', weight: 2, element: 'Metal', grade: 'C' },
      { label: 'Arcane Cannon', weight: 2, element: 'Arcane', grade: 'C' },
      { label: 'Emergency Protocol', weight: 2, element: 'Metal', grade: 'C' },
      { label: 'Experimental Serum', weight: 1, element: 'Metal', grade: 'C' },
      { label: 'Doomsday Device', weight: 1, element: 'Ice', grade: 'C' },
    ],
  },

  {
    label: 'Warlock',
    weight: 2,
    archetypeType: 'Pact Magic',
    abilitySpinCount: 3,
    description: "Made a deal with something ancient. Didn't read the fine print.",
    extraPowerSpins: 1,
    statBonusGrants: { energyLevel: 'statBonus', potential: 'statBonus' },
    statModifiers: { energyLevel: 1.5, potential: 1.4, iq: 1.2, strength: 0.8, durability: 0.85 },
    weaponTypeBias: { Cursed: 3.0, Magical: 2.5, Exotic: 1.0, None: 1.0, Ancient: 0.8, Melee: 0.8, Ranged: 0.5 },
    armorTypeBias: { Exotic: 2.0, None: 1.5, 'Helmet Only': 1.2, Ancient: 1.0, 'Half-Suit': 0.8, 'Full-Suit': 0.3 },
    abilities: [
      { label: 'Eldritch Blast', weight: 3, element: 'Void', grade: 'B' },
      { label: "Patron's Gift", weight: 2 },
      { label: 'Hex', weight: 2, element: 'Void', grade: 'B' },
      { label: 'Dark Invocation', weight: 2, element: 'Shadow', grade: 'B' },
      { label: 'Soul Siphon', weight: 2, element: 'Soul', grade: 'B' },
      { label: 'Shadow Cloak', weight: 2, element: 'Shadow', grade: 'B' },
      { label: 'Pact Weapon', weight: 2, element: 'Void', grade: 'B' },
      { label: 'Void Summon', weight: 1, element: 'Void', grade: 'B' },
    ],
  },

  {
    label: 'Exorcist',
    weight: 2,
    archetypeType: 'Holy Arts',
    abilitySpinCount: 3,
    description: 'Banishes demons for a living. Surprisingly good job market.',
    statBonusGrants: { fightingSkill: 'statBonus', durability: 'statBonus' },
    statModifiers: { fightingSkill: 1.4, durability: 1.3, charisma: 1.2, energyLevel: 1.2, iq: 1.1 },
    grantedWeapons: ['Sacred Flame Blade'],
    weaponTypeBias: { Melee: 2.5, Ancient: 2.0, Magical: 1.8, Exotic: 0.8, Ranged: 0.5, None: 0.5, Cursed: 0.3 },
    armorTypeBias: { 'Full-Suit': 2.0, 'Half-Suit': 2.0, Ancient: 1.5, 'Helmet Only': 0.8, Exotic: 0.8, None: 0.3 },
    abilities: [
      { label: 'Holy Flame Slash', weight: 3, element: 'Fire', grade: 'B' },
      { label: 'Anti-Demon Barrier', weight: 2, element: 'Light', grade: 'B' },
      { label: 'Scripture Ward', weight: 2, element: 'Arcane', grade: 'C' },
      { label: 'Demon Eye Sight', weight: 2, element: 'Light', grade: 'B' },
      { label: 'Gehenna Gate Seal', weight: 1, element: 'Water', grade: 'B' },
      { label: "Satan's Spawn Wrath", weight: 1 },
      { label: 'Purification Wave', weight: 2, element: 'Light', grade: 'B' },
      { label: 'True Cross Order Blessing', weight: 2, element: 'Light', grade: 'B' },
    ],
  },

  {
    label: 'Alchemist',
    weight: 2,
    archetypeType: 'Alchemy',
    abilitySpinCount: 3,
    description: 'Transmutes matter via equivalent exchange. Arm is optional.',
    statBonusGrants: { iq: 'statBonus', strength: 'statPenalty' },
    statModifiers: { iq: 1.7, powerMastery: 1.2, strength: 0.65, fightingSkill: 0.75, charisma: 0.9 },
    weaponTypeBias: { Exotic: 3.0, Magical: 2.0, None: 1.0, Ranged: 1.0, Melee: 0.8, Cursed: 0.5, Ancient: 0.5 },
    armorTypeBias: { Exotic: 2.0, None: 1.5, 'Half-Suit': 1.2, 'Helmet Only': 1.0, 'Full-Suit': 0.5, Ancient: 0.6 },
    abilities: [
      { label: 'Transmutation Circle', weight: 3, element: 'Arcane', grade: 'C' },
      { label: "Flamel's Insight", weight: 2 },
      { label: 'Auto-Mail Augmentation', weight: 2, element: 'Arcane', grade: 'C' },
      { label: 'Stone Alchemy', weight: 2, element: 'Earth', grade: 'C' },
      { label: 'Human Transmutation (Forbidden)', weight: 1, element: 'Arcane', grade: 'B' },
      { label: "Philosopher's Stone Fragment", weight: 1 },
      { label: 'Destruction Alchemy', weight: 2, element: 'Arcane', grade: 'C' },
      { label: "Truth's Gate Power", weight: 1 },
    ],
  },

  {
    label: 'Devil Fruit User',
    weight: 2,
    archetypeType: 'Devil Fruit',
    abilitySpinCount: 1,
    description: 'Ate a Devil Fruit. Swims like a rock. No regrets.',
    abilitySpinDisplayName: 'Devil Fruit',
    extraPowerSpins: 1,
    statBonusGrants: { potential: 'statBonus', energyLevel: 'statBonus' },
    statModifiers: { potential: 1.5, energyLevel: 1.4, powerMastery: 1.3, durability: 1.1 },
    weaponTypeBias: { None: 2.0, Exotic: 1.5, Melee: 1.2, Ranged: 1.0, Magical: 0.8, Cursed: 0.8, Ancient: 0.8 },
    armorTypeBias: { None: 2.5, Exotic: 1.2, 'Half-Suit': 1.0, 'Helmet Only': 0.8, 'Full-Suit': 0.5, Ancient: 0.5 },
    abilities: [],
    customAbilityPool: [
      { label: 'Gomu Gomu no Mi — Rubber Body',          weight: 4 },
      { label: 'Mera Mera no Mi — Fire Logia',           weight: 3 },
      { label: 'Hie Hie no Mi — Ice Logia',              weight: 3 },
      { label: 'Suna Suna no Mi — Sand Logia',           weight: 3 },
      { label: 'Pika Pika no Mi — Light Logia',          weight: 2 },
      { label: 'Magu Magu no Mi — Magma Logia',          weight: 2 },
      { label: 'Goro Goro no Mi — Lightning Logia',      weight: 2 },
      { label: 'Yuki Yuki no Mi — Snow Logia',           weight: 2 },
      { label: 'Ope Ope no Mi — Op-Op Paramecia',        weight: 2 },
      { label: 'Gura Gura no Mi — Quake Paramecia',      weight: 2 },
      { label: 'Bari Bari no Mi — Barrier Paramecia',    weight: 3 },
      { label: 'Baku Baku no Mi — Munch-Munch Paramecia',weight: 2 },
      { label: 'Yami Yami no Mi — Darkness Logia',       weight: 1 },
      { label: 'Tori Tori no Mi — Phoenix Mythical Zoan',weight: 1 },
      { label: 'Uo Uo no Mi — Dragon Mythical Zoan',     weight: 1 },
      { label: 'Hito Hito no Mi — Nika Mythical Zoan',   weight: 1 },
    ],
  },

  {
    label: 'Possessed',
    weight: 2,
    archetypeType: 'Cursed',
    abilitySpinCount: 0,
    description: 'Something else is riding shotgun in your body. It has opinions.',
    abilities: [],
    bonusSpins: [
      { category: 'possessionRace',     displayName: 'Possessing Race'      },
      { category: 'possessionStrength', displayName: 'Possession Strength'  },
    ],
    weaponTypeBias: { Cursed: 1.5, None: 1.5, Magical: 1.0, Melee: 1.0, Exotic: 1.0, Ranged: 0.8, Ancient: 0.8 },
    armorTypeBias: { None: 1.5, Exotic: 1.2, 'Half-Suit': 1.0, 'Helmet Only': 1.0, 'Full-Suit': 0.8, Ancient: 0.8 },
  },

  {
    label: 'Sorcerer',
    weight: 1,
    archetypeType: 'Wild Magic',
    abilitySpinCount: 2,
    description: 'Magic runs in the blood. Mostly uncontrolled. Usually fine.',
    extraPowerSpins: 2,
    statBonusGrants: { potential: 'statBonus', energyLevel: 'statBonus' },
    statModifiers: { potential: 1.7, energyLevel: 1.5, iq: 1.3, durability: 0.8, strength: 0.75 },
    weaponTypeBias: { Magical: 3.0, None: 2.0, Cursed: 1.2, Exotic: 1.0, Ancient: 0.8, Melee: 0.5, Ranged: 0.5 },
    armorTypeBias: { None: 2.0, Exotic: 1.5, 'Helmet Only': 1.0, Ancient: 0.6, 'Half-Suit': 0.7, 'Full-Suit': 0.2 },
    abilities: [
      { label: 'Wild Surge', weight: 3, element: 'Nature', grade: 'B' },
      { label: 'Metamagic', weight: 2, element: 'Arcane', grade: 'B' },
      { label: 'Font of Magic', weight: 2, element: 'Arcane', grade: 'B' },
      { label: 'Bloodline Empowerment', weight: 2, element: 'Blood', grade: 'B' },
      { label: 'Twinned Spell', weight: 2, element: 'Arcane', grade: 'B' },
      { label: 'Quickened Spell', weight: 2, element: 'Arcane', grade: 'B' },
      { label: 'Chaos Bolt', weight: 2, element: 'Chaos', grade: 'B' },
      { label: 'Cosmic Overload', weight: 1, element: 'Cosmic', grade: 'SS' },
    ],
  },

  {
    label: 'Middle Manager',
    weight: 1,
    archetypeType: 'Corporate',
    abilitySpinCount: 1,
    description: 'Wields passive-aggression and passive-aggressive meeting invites.',
    statBonusGrants: { strength: 'statPenalty', fightingSkill: 'statPenalty', speed: 'statPenalty' },
    statModifiers: { iq: 1.1, charisma: 0.7, strength: 0.55, speed: 0.5, fightingSkill: 0.4, agility: 0.6, durability: 0.65 },
    weaponTypeBias: { None: 4.0, Exotic: 1.5, Melee: 0.5, Ranged: 0.5, Cursed: 0.5, Magical: 0.3, Ancient: 0.3 },
    armorTypeBias: { None: 4.0, Exotic: 1.0, 'Helmet Only': 0.5, 'Half-Suit': 0.3, 'Full-Suit': 0.1, Ancient: 0.1 },
    abilities: [
      { label: 'Meeting Invites (Mandatory)', weight: 3, element: 'Neutral', grade: 'D' },
      { label: 'Passive-Aggressive Email', weight: 3, element: 'Neutral', grade: 'D' },
      { label: 'Delegate Everything', weight: 2, element: 'Neutral', grade: 'D' },
      { label: 'Synergy Buzzword Blast', weight: 2, element: 'Neutral', grade: 'D' },
      { label: "CC'd on Every Thread", weight: 2 },
      { label: 'Quiet Budget Veto', weight: 2, element: 'Neutral', grade: 'D' },
      { label: 'KPI Reality Distortion', weight: 1, element: 'Cosmic', grade: 'D' },
    ],
  },

  {
    label: 'Professional Sneezer',
    weight: 1,
    archetypeType: 'Absurd',
    abilitySpinCount: 1,
    description: 'Specialised beyond all reason. Somehow rated highly on Yelp.',
    statBonusGrants: { strength: 'statPenalty', fightingSkill: 'statPenalty' },
    statModifiers: { strength: 0.5, speed: 0.45, fightingSkill: 0.35, agility: 0.5, durability: 0.6, iq: 0.65 },
    weaponTypeBias: { None: 5.0, Exotic: 1.0, Melee: 0.3, Ranged: 0.3, Magical: 0.3, Cursed: 0.2, Ancient: 0.2 },
    armorTypeBias: { None: 5.0, Exotic: 0.5, 'Helmet Only': 0.3, 'Half-Suit': 0.1, 'Full-Suit': 0.05, Ancient: 0.1 },
    abilities: [
      { label: 'Achoo (Gale Force)', weight: 3, element: 'Wind', grade: 'D' },
      { label: 'Pre-Sneeze Tension', weight: 3, element: 'Neutral', grade: 'D' },
      { label: 'Sneeze Chain Combo', weight: 2, element: 'Neutral', grade: 'D' },
      { label: 'Strategic Tissue Deploy', weight: 2, element: 'Neutral', grade: 'D' },
      { label: 'Blessed By Allergies', weight: 2, element: 'Light', grade: 'D' },
      { label: 'Sonic Boom Exhale', weight: 1, element: 'Sound', grade: 'D' },
    ],
  },

  {
    label: 'Chaos Gremlin',
    weight: 1,
    archetypeType: 'Chaotic',
    abilitySpinCount: 2,
    description: 'No plan. No fear. Somehow winning.',
    // No statModifiers — true chaos, every stat is equally likely
    weaponTypeBias: { Exotic: 1.5, Cursed: 1.5, None: 1.5, Melee: 1.0, Ranged: 1.0, Magical: 1.0, Ancient: 1.0 },
    armorTypeBias: { None: 1.5, Exotic: 1.5, 'Half-Suit': 1.0, 'Helmet Only': 1.0, Ancient: 1.0, 'Full-Suit': 0.8 },
    abilities: [
      { label: 'Random Button Pressing', weight: 3, element: 'Chaos', grade: 'D' },
      { label: 'It Just Works', weight: 2, element: 'Chaos', grade: 'D' },
      { label: 'Chaos Theory Applied', weight: 2, element: 'Chaos', grade: 'D' },
      { label: 'Glitch Exploit', weight: 2, element: 'Chaos', grade: 'D' },
      { label: 'Unhinged Confidence', weight: 2, element: 'Chaos', grade: 'D' },
      { label: 'Inexplicable Survival', weight: 2, element: 'Chaos', grade: 'D' },
      { label: 'Delete System32', weight: 1, element: 'Chaos', grade: 'D' },
    ],
  },

  {
    label: 'Time Traveler',
    weight: 1,
    archetypeType: 'Temporal',
    abilitySpinCount: 4,
    description: 'Sees the timeline as a rough suggestion. Chronic anachronist.',
    statBonusGrants: { iq: 'statBonus', potential: 'statBonus' },
    statModifiers: { iq: 1.6, potential: 1.5, speed: 0.75, strength: 0.8, agility: 0.9 },
    weaponTypeBias: { Exotic: 3.0, Ancient: 2.0, Magical: 1.5, Ranged: 1.0, None: 1.0, Melee: 0.7, Cursed: 0.5 },
    armorTypeBias: { Exotic: 3.0, Ancient: 1.5, None: 1.5, 'Half-Suit': 0.8, 'Helmet Only': 0.8, 'Full-Suit': 0.5 },
    abilities: [
      { label: 'Temporal Displacement', weight: 3, element: 'Time', grade: 'A' },
      { label: 'Paradox Immunity', weight: 2, element: 'Time', grade: 'A' },
      { label: 'Foreknowledge', weight: 2, element: 'Time', grade: 'A' },
      { label: 'Fixed Point Awareness', weight: 2, element: 'Time', grade: 'A' },
      { label: 'Timeline Rewrite', weight: 1, element: 'Time', grade: 'A' },
      { label: 'Wibbly-Wobbly Manipulation', weight: 2, element: 'Time', grade: 'A' },
      { label: 'Pre-Cognition Loop', weight: 2, element: 'Time', grade: 'A' },
      { label: 'Snap Back (Forced Return)', weight: 1, element: 'Time', grade: 'A' },
    ],
  },

  {
    label: 'Titan Shifter',
    weight: 1,
    archetypeType: 'Titan Power',
    abilitySpinCount: 1,
    description: 'Transforms into a Titan at will. Smells worse than it sounds.',
    abilitySpinDisplayName: 'Titan Form',
    statBonusGrants: { strength: 'statBonus', durability: 'statBonus' },
    statModifiers: { strength: 1.9, durability: 1.8, speed: 0.65, agility: 0.6, fightingSkill: 1.2, iq: 0.9 },
    weaponTypeBias: { None: 5.0, Melee: 0.8, Ranged: 0.5, Exotic: 0.5, Cursed: 0.5, Ancient: 0.5, Magical: 0.3 },
    armorTypeBias: { None: 3.0, 'Half-Suit': 1.0, 'Helmet Only': 1.0, Exotic: 0.5, 'Full-Suit': 0.5, Ancient: 0.5 },
    abilities: [],
    customAbilityPool: [
      { label: 'Attack Titan',       weight: 3 },
      { label: 'Armored Titan',      weight: 2 },
      { label: 'Colossal Titan',     weight: 2 },
      { label: 'Female Titan',       weight: 2 },
      { label: 'Beast Titan',        weight: 2 },
      { label: 'Jaw Titan',          weight: 3 },
      { label: 'Cart Titan',         weight: 3 },
      { label: 'War Hammer Titan',   weight: 2 },
      { label: 'Founding Titan',     weight: 1 },
    ],
  },

  {
    label: 'Awakened',
    weight: 1,
    archetypeType: 'Transcendent',
    abilitySpinCount: 2,
    description: 'Touched something vast. Changed forever. Refuses to explain.',
    extraPowerSpins: 1,
    statBonusGrants: { potential: 'statBonus', energyLevel: 'statBonus', powerMastery: 'statBonus' },
    statModifiers: { potential: 2.0, energyLevel: 1.6, powerMastery: 1.4, iq: 1.3, strength: 1.2, speed: 1.2, agility: 1.2, durability: 1.2 },
    weaponTypeBias: { Ancient: 1.5, Magical: 1.5, Exotic: 1.3, None: 1.5, Melee: 1.0, Cursed: 1.0, Ranged: 0.8 },
    armorTypeBias: { Ancient: 1.5, Exotic: 1.5, 'Full-Suit': 1.2, None: 1.0, 'Half-Suit': 1.0, 'Helmet Only': 0.8 },
    abilities: [
      { label: 'Latent Power Surge',     weight: 3, element: 'Arcane', grade: 'S' },
      { label: 'Danger Sense Overdrive', weight: 2, element: 'Arcane', grade: 'S' },
      { label: 'Limit Break',            weight: 2, element: 'Arcane', grade: 'S' },
      { label: 'Resonance Field',        weight: 2, element: 'Sound', grade: 'B' },
      { label: 'Cascading Awakening',    weight: 1, element: 'Arcane', grade: 'S' },
      { label: 'Beyond Peak Form',       weight: 1, element: 'Arcane', grade: 'S' },
    ],
  },

]
