// archetypes.ts — Archetype content data for Wheel of Fate.
// 29 Archetype entries with rarity weights, abilitySpinCount, and unique abilities pool.
// Weight determines rarity: higher weight = more common slice on wheel.
// No default export. No functions. Static const array only.

import type { Archetype } from './types'

export const archetypes: Archetype[] = [
  {
    label: 'Warrior',
    weight: 6,
    abilitySpinCount: 2,
    description: 'Solves most problems with direct application of force.',
    abilities: [
      { label: 'Battle Hardened', weight: 3 },
      { label: 'Shield Wall', weight: 3 },
      { label: 'Weapon Mastery', weight: 2 },
      { label: 'Soldier\'s Endurance', weight: 3 },
      { label: 'War Cry', weight: 2 },
      { label: 'Second Wind', weight: 2 },
      { label: 'Blade Storm', weight: 1 },
      { label: 'Unbreakable Will', weight: 1 },
    ],
  },
  {
    label: 'Mage',
    weight: 5,
    abilitySpinCount: 3,
    description: 'Bends reality via intensive study and questionable decisions.',
    abilities: [
      { label: 'Arcane Surge', weight: 3 },
      { label: 'Counterspell', weight: 2 },
      { label: 'Mana Shield', weight: 3 },
      { label: 'Ritual Magic', weight: 2 },
      { label: 'Ley Line Tap', weight: 2 },
      { label: 'Spell Amplification', weight: 2 },
      { label: 'Forbidden Tome', weight: 1 },
      { label: 'Reality Fracture', weight: 1 },
    ],
  },
  {
    label: 'Rogue',
    weight: 5,
    abilitySpinCount: 2,
    description: 'Prefers to work in the shadows, usually for unclear reasons.',
    abilities: [
      { label: 'Backstab', weight: 3 },
      { label: 'Shadow Step', weight: 2 },
      { label: 'Pick Pocket', weight: 3 },
      { label: 'Poison Coating', weight: 2 },
      { label: 'Evasion', weight: 2 },
      { label: 'Death Mark', weight: 1 },
      { label: 'Master Disguise', weight: 2 },
      { label: 'Unseen Strike', weight: 1 },
    ],
  },
  {
    label: 'Paladin',
    weight: 4,
    abilitySpinCount: 2,
    description: 'Divine warrior who will remind you of their oaths unbidden.',
    abilities: [
      { label: 'Divine Smite', weight: 3 },
      { label: 'Lay on Hands', weight: 3 },
      { label: 'Holy Aura', weight: 2 },
      { label: 'Turn Undead', weight: 2 },
      { label: 'Sacred Vow', weight: 2 },
      { label: 'Radiant Shield', weight: 2 },
      { label: 'Celestial Weapon', weight: 1 },
      { label: 'Angelic Intervention', weight: 1 },
    ],
  },
  {
    label: 'Ranger',
    weight: 4,
    abilitySpinCount: 2,
    description: 'At home in the wilderness. Suspicious of architecture.',
    abilities: [
      { label: 'Tracker\'s Eye', weight: 3 },
      { label: 'Favored Terrain', weight: 3 },
      { label: 'Arrow Rain', weight: 2 },
      { label: 'Beast Bond', weight: 2 },
      { label: 'Hunter\'s Mark', weight: 2 },
      { label: 'Camouflage', weight: 2 },
      { label: 'Predator\'s Instinct', weight: 1 },
      { label: 'Wilderness Communion', weight: 1 },
    ],
  },
  {
    label: 'Berserker',
    weight: 3,
    abilitySpinCount: 1,
    description: 'Combat strategy: rage. Follow-up strategy: also rage.',
    abilities: [
      { label: 'Frenzied Rage', weight: 3 },
      { label: 'Pain Resistance', weight: 3 },
      { label: 'Reckless Attack', weight: 2 },
      { label: 'Intimidating Presence', weight: 2 },
      { label: 'Feral Instinct', weight: 2 },
      { label: 'Mindless Fury', weight: 2 },
      { label: 'Death\'s Door Surge', weight: 1 },
    ],
  },
  {
    label: 'Necromancer',
    weight: 2,
    abilitySpinCount: 3,
    description: 'Death is just a resource management problem.',
    abilities: [
      { label: 'Raise Dead', weight: 3 },
      { label: 'Soul Drain', weight: 2 },
      { label: 'Bone Armor', weight: 3 },
      { label: 'Death Coil', weight: 2 },
      { label: 'Lich\'s Focus', weight: 2 },
      { label: 'Plague Burst', weight: 2 },
      { label: 'Soul Bind', weight: 1 },
      { label: 'Army of the Dead', weight: 1 },
    ],
  },
  {
    label: 'Bard',
    weight: 4,
    abilitySpinCount: 2,
    description: 'Weaponises music, poetry, and audacity.',
    abilities: [
      { label: 'Inspire Courage', weight: 3 },
      { label: 'Cutting Words', weight: 2 },
      { label: 'Song of Rest', weight: 3 },
      { label: 'Hypnotic Melody', weight: 2 },
      { label: 'Lore Master', weight: 2 },
      { label: 'Silver Tongue', weight: 2 },
      { label: 'Epic Ballad', weight: 1 },
      { label: 'World-Ending Encore', weight: 1 },
    ],
  },
  {
    label: 'Monk',
    weight: 3,
    abilitySpinCount: 2,
    description: 'Inner peace achieved through punching things.',
    abilities: [
      { label: 'Flurry of Blows', weight: 3 },
      { label: 'Ki Blast', weight: 2 },
      { label: 'Deflect Missiles', weight: 2 },
      { label: 'Stillness of Mind', weight: 3 },
      { label: 'Step of the Wind', weight: 2 },
      { label: 'Iron Body', weight: 2 },
      { label: 'Empty Palm', weight: 1 },
      { label: 'One With Everything', weight: 1 },
    ],
  },
  {
    label: 'Druid',
    weight: 2,
    abilitySpinCount: 3,
    description: 'Nature\'s spokesperson. Takes the role very seriously.',
    abilities: [
      { label: 'Wild Shape', weight: 3 },
      { label: 'Entangle', weight: 2 },
      { label: 'Barkskin', weight: 3 },
      { label: 'Call Lightning', weight: 2 },
      { label: 'Speak with Animals', weight: 2 },
      { label: 'Regrowth', weight: 2 },
      { label: 'Nature\'s Wrath', weight: 1 },
      { label: 'Verdant Avatar', weight: 1 },
    ],
  },
  {
    label: 'Artificer',
    weight: 2,
    abilitySpinCount: 2,
    description: 'Builds magical gadgets. Safety is a suggestion.',
    abilities: [
      { label: 'Tinker\'s Tools', weight: 3 },
      { label: 'Infuse Item', weight: 2 },
      { label: 'Flash Bomb', weight: 2 },
      { label: 'Automaton Companion', weight: 2 },
      { label: 'Arcane Cannon', weight: 2 },
      { label: 'Emergency Protocol', weight: 2 },
      { label: 'Experimental Serum', weight: 1 },
      { label: 'Doomsday Device', weight: 1 },
    ],
  },
  {
    label: 'Warlock',
    weight: 2,
    abilitySpinCount: 3,
    description: 'Made a deal with something ancient. Didn\'t read the fine print.',
    abilities: [
      { label: 'Eldritch Blast', weight: 3 },
      { label: 'Patron\'s Gift', weight: 2 },
      { label: 'Hex', weight: 2 },
      { label: 'Dark Invocation', weight: 2 },
      { label: 'Soul Siphon', weight: 2 },
      { label: 'Shadow Cloak', weight: 2 },
      { label: 'Pact Weapon', weight: 2 },
      { label: 'Void Summon', weight: 1 },
    ],
  },
  {
    label: 'Sorcerer',
    weight: 1,
    abilitySpinCount: 4,
    description: 'Magic runs in the blood. Mostly uncontrolled. Usually fine.',
    abilities: [
      { label: 'Wild Surge', weight: 3 },
      { label: 'Metamagic', weight: 2 },
      { label: 'Font of Magic', weight: 2 },
      { label: 'Bloodline Empowerment', weight: 2 },
      { label: 'Twinned Spell', weight: 2 },
      { label: 'Quickened Spell', weight: 2 },
      { label: 'Chaos Bolt', weight: 2 },
      { label: 'Cosmic Overload', weight: 1 },
    ],
  },
  {
    label: 'Cleric',
    weight: 4,
    abilitySpinCount: 2,
    description: 'Divine conduit. God\'s chosen errand-runner.',
    abilities: [
      { label: 'Channel Divinity', weight: 3 },
      { label: 'Divine Word', weight: 2 },
      { label: 'Sacred Flame', weight: 3 },
      { label: 'Blessed Healer', weight: 2 },
      { label: 'Spiritual Weapon', weight: 2 },
      { label: 'Divine Intervention', weight: 1 },
      { label: 'Holy Ground', weight: 2 },
      { label: 'Avatar of the Divine', weight: 1 },
    ],
  },
  {
    label: 'Middle Manager',
    weight: 1,
    abilitySpinCount: 1,
    description: 'Wields passive-aggression and passive-aggressive meeting invites.',
    abilities: [
      { label: 'Meeting Invites (Mandatory)', weight: 3 },
      { label: 'Passive-Aggressive Email', weight: 3 },
      { label: 'Delegate Everything', weight: 2 },
      { label: 'Synergy Buzzword Blast', weight: 2 },
      { label: 'CC\'d on Every Thread', weight: 2 },
      { label: 'Quiet Budget Veto', weight: 2 },
      { label: 'KPI Reality Distortion', weight: 1 },
    ],
  },
  {
    label: 'Professional Sneezer',
    weight: 1,
    abilitySpinCount: 1,
    description: 'Specialised beyond all reason. Somehow rated highly on Yelp.',
    abilities: [
      { label: 'Achoo (Gale Force)', weight: 3 },
      { label: 'Pre-Sneeze Tension', weight: 3 },
      { label: 'Sneeze Chain Combo', weight: 2 },
      { label: 'Strategic Tissue Deploy', weight: 2 },
      { label: 'Blessed By Allergies', weight: 2 },
      { label: 'Sonic Boom Exhale', weight: 1 },
    ],
  },
  {
    label: 'Chaos Gremlin',
    weight: 1,
    abilitySpinCount: 2,
    description: 'No plan. No fear. Somehow winning.',
    abilities: [
      { label: 'Random Button Pressing', weight: 3 },
      { label: 'It Just Works', weight: 2 },
      { label: 'Chaos Theory Applied', weight: 2 },
      { label: 'Glitch Exploit', weight: 2 },
      { label: 'Unhinged Confidence', weight: 2 },
      { label: 'Inexplicable Survival', weight: 2 },
      { label: 'Delete System32', weight: 1 },
    ],
  },

  // — Fiction-inspired archetypes —

  {
    label: 'Demon Slayer',
    weight: 4,
    abilitySpinCount: 3,
    description: 'Trained in Breathing Techniques. The demons are in real trouble.',
    abilities: [
      { label: 'Total Concentration Breathing', weight: 3 },
      { label: 'Flame Breathing', weight: 2 },
      { label: 'Water Breathing', weight: 2 },
      { label: 'Thunder Breathing', weight: 2 },
      { label: 'Stone Breathing', weight: 2 },
      { label: 'Hinokami Kagura', weight: 1 },
      { label: 'Selfless State', weight: 1 },
      { label: 'Transparent World', weight: 1 },
    ],
  },
  {
    label: 'Stand User',
    weight: 3,
    abilitySpinCount: 2,
    description: 'Manifests a spiritual entity of immeasurable power. Ora ora ora.',
    abilities: [
      { label: 'Stand Summon', weight: 3 },
      { label: 'Barrage Assault', weight: 2 },
      { label: 'Stand Barrier', weight: 2 },
      { label: 'Requiem Evolution', weight: 1 },
      { label: 'Time Stop (Brief)', weight: 1 },
      { label: 'Infinite Rotation', weight: 1 },
      { label: 'Gold Experience Reversal', weight: 1 },
      { label: 'Epitaph Precognition', weight: 2 },
    ],
  },
  {
    label: 'Nen Hunter',
    weight: 3,
    abilitySpinCount: 3,
    description: 'Licensed Hunter. Nen-trained. Dangerous and chronically underpaid.',
    abilities: [
      { label: 'Ten — Aura Retention', weight: 3 },
      { label: 'Zetsu — Concealment', weight: 2 },
      { label: 'Ren — Aura Amplification', weight: 2 },
      { label: 'Hatsu — Personal Nen Ability', weight: 1 },
      { label: 'Gyo — Focused Sight', weight: 2 },
      { label: 'In — Invisible Aura', weight: 1 },
      { label: 'Ko — Concentrated Strike', weight: 2 },
      { label: 'Vow and Limitation', weight: 1 },
    ],
  },
  {
    label: 'Superhero',
    weight: 5,
    abilitySpinCount: 2,
    description: 'Has a code, a costume, and a complicated relationship with authority.',
    abilities: [
      { label: 'Heroic Resolve', weight: 3 },
      { label: 'Never-Give-Up Punch', weight: 3 },
      { label: 'Civilian Protection Protocol', weight: 2 },
      { label: 'Power Restraint', weight: 2 },
      { label: 'Inspirational Speech', weight: 2 },
      { label: 'Iconic Finishing Move', weight: 1 },
      { label: 'One For All', weight: 1 },
      { label: 'Detroit Smash', weight: 1 },
    ],
  },
  {
    label: 'Supervillain',
    weight: 3,
    abilitySpinCount: 2,
    description: 'Grand ambitions. Elaborate lair. Refuses to just shoot the hero.',
    abilities: [
      { label: 'World Domination Plan', weight: 3 },
      { label: 'Minion Army', weight: 3 },
      { label: 'Monologue Mastery', weight: 2 },
      { label: 'Evil Lair Fortress', weight: 2 },
      { label: 'Doomsday Device Mk. II', weight: 2 },
      { label: 'Tragic Backstory Buff', weight: 2 },
      { label: 'Redemption Arc Resistance', weight: 1 },
      { label: 'I Am The Hero Speech', weight: 1 },
    ],
  },
  {
    label: 'Anti-Hero',
    weight: 4,
    abilitySpinCount: 2,
    description: 'Does the right thing, badly, with maximum collateral damage.',
    abilities: [
      { label: 'Moral Ambiguity', weight: 3 },
      { label: 'Lethal Force Authorized', weight: 2 },
      { label: 'Trauma Response Combat', weight: 2 },
      { label: 'Reluctant Ally', weight: 3 },
      { label: 'Not Actually Sorry', weight: 2 },
      { label: 'Regeneration (Inconvenient)', weight: 2 },
      { label: 'Maximum Effort', weight: 1 },
      { label: 'Fourth Wall Advisory', weight: 1 },
    ],
  },
  {
    label: 'Shinobi',
    weight: 4,
    abilitySpinCount: 3,
    description: 'Mastery of chakra, deception, and dying dramatically.',
    abilities: [
      { label: 'Ninjutsu — Shadow Clone', weight: 3 },
      { label: 'Genjutsu — Illusion Bind', weight: 2 },
      { label: 'Taijutsu — Eight Gates', weight: 1 },
      { label: 'Rasengan', weight: 2 },
      { label: 'Sharingan Insight', weight: 2 },
      { label: 'Sage Mode', weight: 1 },
      { label: 'Summoning Jutsu', weight: 2 },
      { label: 'Six Paths Chakra', weight: 1 },
    ],
  },
  {
    label: 'Esper',
    weight: 3,
    abilitySpinCount: 3,
    description: 'Psychic to a dangerous degree. Tries very hard not to explode.',
    abilities: [
      { label: 'Telekinesis', weight: 3 },
      { label: 'Telepathy', weight: 2 },
      { label: 'Psychic Barrier', weight: 2 },
      { label: '???% Release', weight: 1 },
      { label: 'Astral Projection', weight: 2 },
      { label: 'Emotion Amplification', weight: 2 },
      { label: 'Mind Crush', weight: 1 },
      { label: 'World Destruction Sneeze', weight: 1 },
    ],
  },
  {
    label: 'Bounty Hunter',
    weight: 3,
    abilitySpinCount: 2,
    description: 'This is the way. Payment up front. No disintegrations.',
    abilities: [
      { label: 'Target Acquired', weight: 3 },
      { label: 'Whistling Bird Missiles', weight: 2 },
      { label: 'Jetpack Assault', weight: 2 },
      { label: 'Beskar Armor', weight: 2 },
      { label: 'Whistling Whistling Whistling', weight: 2 },
      { label: 'Grappling Hook Takedown', weight: 2 },
      { label: 'Whistling Bird Salvo', weight: 1 },
      { label: 'I Have Spoken', weight: 1 },
    ],
  },
  {
    label: 'Alchemist',
    weight: 2,
    abilitySpinCount: 3,
    description: 'Transmutes matter via equivalent exchange. Arm is optional.',
    abilities: [
      { label: 'Transmutation Circle', weight: 3 },
      { label: 'Flamel\'s Insight', weight: 2 },
      { label: 'Auto-Mail Augmentation', weight: 2 },
      { label: 'Stone Alchemy', weight: 2 },
      { label: 'Human Transmutation (Forbidden)', weight: 1 },
      { label: 'Philosopher\'s Stone Fragment', weight: 1 },
      { label: 'Destruction Alchemy', weight: 2 },
      { label: 'Truth\'s Gate Power', weight: 1 },
    ],
  },
  {
    label: 'Exorcist',
    weight: 2,
    abilitySpinCount: 3,
    description: 'Banishes demons for a living. Surprisingly good job market.',
    abilities: [
      { label: 'Holy Flame Slash', weight: 3 },
      { label: 'Anti-Demon Barrier', weight: 2 },
      { label: 'Scripture Ward', weight: 2 },
      { label: 'Demon Eye Sight', weight: 2 },
      { label: 'Gehenna Gate Seal', weight: 1 },
      { label: 'Satan\'s Spawn Wrath', weight: 1 },
      { label: 'Purification Wave', weight: 2 },
      { label: 'True Cross Order Blessing', weight: 2 },
    ],
  },
  {
    label: 'Time Traveler',
    weight: 1,
    abilitySpinCount: 4,
    description: 'Sees the timeline as a rough suggestion. Chronic anachronist.',
    abilities: [
      { label: 'Temporal Displacement', weight: 3 },
      { label: 'Paradox Immunity', weight: 2 },
      { label: 'Foreknowledge', weight: 2 },
      { label: 'Fixed Point Awareness', weight: 2 },
      { label: 'Timeline Rewrite', weight: 1 },
      { label: 'Wibbly-Wobbly Manipulation', weight: 2 },
      { label: 'Pre-Cognition Loop', weight: 2 },
      { label: 'Snap Back (Forced Return)', weight: 1 },
    ],
  },
]
