// armors.ts — Armor content pools for Wheel of Fate, organized by armorType category.
// 300+ SimpleItem entries spanning comic to legendary. No default export.

import type { SimpleItem } from './types'

const helmetOnly: SimpleItem[] = [
  { label: 'Iron Cap',                                    weight: 4, element: 'Metal',   grade: 'D' },
  { label: 'Leather Helm',                                weight: 4, element: 'Neutral', grade: 'D' },
  { label: 'Bronze Barbute',                              weight: 3, element: 'Metal',   grade: 'D' },
  { label: 'Chainmail Coif',                              weight: 3, element: 'Metal',   grade: 'D' },
  { label: 'Open-Faced Steel Visor',                      weight: 3, element: 'Metal',   grade: 'D' },
  { label: 'Blacksmith\'s Work Cap',                      weight: 3, element: 'Metal',   grade: 'D' },
  { label: 'Padded Skull Cap',                            weight: 3, element: 'Neutral', grade: 'D' },
  { label: 'Archer\'s Hood (Reinforced)',                  weight: 3, element: 'Neutral', grade: 'D' },
  { label: 'Scout\'s Ranger Hat (Hardened)',               weight: 3, element: 'Neutral', grade: 'D' },
  { label: 'Legionnaire\'s Galea',                        weight: 2, element: 'Metal',   grade: 'D' },
  { label: 'Viking Half-Helm',                            weight: 2, element: 'Metal',   grade: 'D' },
  { label: 'Spartan Corinthian Helm',                     weight: 2, element: 'Metal',   grade: 'D' },
  { label: 'Plumed Knight\'s Helm',                       weight: 2, element: 'Metal',   grade: 'D' },
  { label: 'Jousting Greathelm',                         weight: 2, element: 'Metal',   grade: 'D' },
  { label: 'Samurai Kabuto',                              weight: 2, element: 'Metal',   grade: 'D' },
  { label: 'Executioner\'s Coif',                         weight: 2, element: 'Shadow',  grade: 'D' },
  { label: 'Assassin\'s Cowl (Reinforced)',                weight: 2, element: 'Shadow',  grade: 'D' },
  { label: 'Mage\'s Iron-Banded Skullcap',                weight: 2, element: 'Arcane',  grade: 'D' },
  { label: 'Battle Pope\'s Fortified Mitre',              weight: 1, element: 'Light',   grade: 'C' },
  { label: 'Dragon Scale Hood',                           weight: 2, element: 'Nature',  grade: 'C' },
  { label: 'Obsidian War Mask',                           weight: 2, element: 'Earth',   grade: 'C' },
  { label: 'Oni Mask (Combat Grade)',                     weight: 2, element: 'Shadow',  grade: 'C' },
  { label: 'Kitsune War Mask',                            weight: 2, element: 'Shadow',  grade: 'C' },
  { label: 'Demon\'s Visage Helm',                        weight: 2, element: 'Fire',    grade: 'C' },
  { label: 'Skull Knight\'s Faceplate',                   weight: 2, element: 'Soul',    grade: 'C' },
  { label: 'Crystal Seer\'s Helmet',                      weight: 2, element: 'Arcane',  grade: 'C' },
  { label: 'Glowing Tactical Visor',                      weight: 2, element: 'Metal',   grade: 'C' },
  { label: 'Holographic HUD Helm',                        weight: 2, element: 'Metal',   grade: 'C' },
  { label: 'Combat Drone Headpiece',                      weight: 2, element: 'Metal',   grade: 'C' },
  { label: 'Tactical Ballistic Helmet',                   weight: 2, element: 'Metal',   grade: 'D' },
  { label: 'Stealth Ops Mask',                            weight: 2, element: 'Shadow',  grade: 'D' },
  { label: 'Cardboard Box (Eye Holes Included)',           weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Traffic Cone (Repurposed)',                    weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Birthday Crown (Surprisingly Sturdy)',         weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Paper Bag (Very Intimidating)',                weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Upside-Down Bucket Helm',                     weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Colander (Classic)',                          weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Pasta Pot Helm (Slightly Moist)',             weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Party Hat (Stapled On)',                       weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Fishbowl (Air Included)',                      weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Bike Helmet (Wrong Sport)',                    weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Soup Ladle and Bandana Combo',                weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Sieve Helm (Well-Ventilated)',                 weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Cereal Bowl Lid (Defense: 0.4)',              weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Graduation Cap (Bulletproof Edition)',         weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Praetorian Imperial Helmet',                  weight: 1, element: 'Metal',   grade: 'C' },
  { label: 'Phrygian Cap (Battle Grade)',                  weight: 1, element: 'Neutral', grade: 'D' },
  { label: 'Hoplite Corinthian Panoply Helm',             weight: 1, element: 'Metal',   grade: 'C' },
  { label: 'Samurai Menpo (Full Face)',                    weight: 1, element: 'Metal',   grade: 'C' },
  { label: 'Cyber-Eye Implant Helm',                      weight: 2, element: 'Metal',   grade: 'C' },
]

const halfSuit: SimpleItem[] = [
  { label: 'Leather Vest',                                weight: 4, element: 'Neutral', grade: 'D' },
  { label: 'Quilted Gambeson',                            weight: 4, element: 'Neutral', grade: 'D' },
  { label: 'Chain Shirt',                                 weight: 3, element: 'Metal',   grade: 'D' },
  { label: 'Riveted Brigandine',                          weight: 3, element: 'Metal',   grade: 'D' },
  { label: 'Scale Shirt',                                 weight: 3, element: 'Metal',   grade: 'D' },
  { label: 'Splint Mail Vest',                            weight: 3, element: 'Metal',   grade: 'D' },
  { label: 'Plate Cuirass (Partial)',                      weight: 3, element: 'Metal',   grade: 'D' },
  { label: 'Lamellar Breastplate',                        weight: 3, element: 'Metal',   grade: 'D' },
  { label: 'Roman Lorica Hamata (Chain)',                  weight: 2, element: 'Metal',   grade: 'D' },
  { label: 'Byzantine Klibanion',                         weight: 2, element: 'Metal',   grade: 'D' },
  { label: 'Japanese Haramaki',                           weight: 2, element: 'Metal',   grade: 'D' },
  { label: 'Mongol Lamellar Vest',                        weight: 2, element: 'Metal',   grade: 'D' },
  { label: 'Ranger\'s Studded Leather',                   weight: 3, element: 'Nature',  grade: 'D' },
  { label: 'Scout\'s Lightweight Chestguard',              weight: 3, element: 'Neutral', grade: 'D' },
  { label: 'Spy\'s Concealable Vest',                      weight: 3, element: 'Shadow',  grade: 'D' },
  { label: 'Duelist\'s Padded Jack',                      weight: 3, element: 'Neutral', grade: 'D' },
  { label: 'Marksman\'s Silenced Vest',                   weight: 3, element: 'Neutral', grade: 'D' },
  { label: 'Rogue\'s Shadow-Weave Jerkin',                 weight: 3, element: 'Shadow',  grade: 'D' },
  { label: 'Bard\'s Stage-Ready Chestpiece',              weight: 2, element: 'Sound',   grade: 'D' },
  { label: 'Adventurer\'s All-Purpose Vest',               weight: 3, element: 'Neutral', grade: 'D' },
  { label: 'Mercenary\'s Battered Cuirass',                weight: 3, element: 'Metal',   grade: 'D' },
  { label: 'Dragon Scale Chest Guard',                    weight: 2, element: 'Nature',  grade: 'C' },
  { label: 'Phoenix Feather Breastplate',                 weight: 2, element: 'Fire',    grade: 'C' },
  { label: 'Kraken Leather Vest',                         weight: 2, element: 'Water',   grade: 'C' },
  { label: 'Wolf Pelt Harness',                           weight: 2, element: 'Nature',  grade: 'C' },
  { label: 'Bear Muscle Suit (Upper)',                     weight: 2, element: 'Nature',  grade: 'C' },
  { label: 'Troll Hide Vest (Itchy)',                      weight: 2, element: 'Nature',  grade: 'C' },
  { label: 'Bubble Wrap Tactical Vest (Single-Use)',       weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Cardboard Breastplate (Dampened)',             weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Apron of Marginal Protection',                weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Football Shoulder Pads (Repurposed)',          weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'High-Visibility Safety Vest (Enchanted)',      weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Lab Coat (Kevlar-Lined)',                      weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Chef\'s Coat (Flame Resistant, Unfortunately)', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Winter Coat (Thick)',                          weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Life Jacket (Combat Rating: 0.2)',             weight: 3, element: 'Water',   grade: 'F' },
  { label: 'Duct Tape and Hope',                          weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Stack of Books (Strapped to Chest)',           weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Pool Noodle Chest Harness',                   weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Mattress Cover Chest Piece',                   weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Pizza Box Breastplate',                        weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Sumo Suit Upper Half',                        weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Pillow Strapped with Belts',                  weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Hydra-Scale Breastplate (Regenerates)',        weight: 1, element: 'Nature',  grade: 'A' },
  { label: 'Basilisk Hide Chest (Gaze-Proof)',             weight: 1, element: 'Earth',   grade: 'C' },
  { label: 'Indian Char Aina (Four Mirrors)',              weight: 2, element: 'Metal',   grade: 'D' },
  { label: 'Ottoman Mail Shirt (Zirh)',                    weight: 2, element: 'Metal',   grade: 'D' },
  { label: 'Sellsword\'s Mix-and-Match Set',               weight: 2, element: 'Metal',   grade: 'D' },
  { label: 'Acrobat\'s Spring-Flex Upper Suit',            weight: 2, element: 'Neutral', grade: 'D' },
  { label: 'Viking Chainmail Hauberk',                    weight: 2, element: 'Metal',   grade: 'D' },
  { label: 'Scottish Gambeson (Reinforced)',               weight: 2, element: 'Neutral', grade: 'D' },
]

const fullSuit: SimpleItem[] = [
  { label: 'Standard Plate Armor',                        weight: 4, element: 'Metal',   grade: 'D' },
  { label: 'Gothic Full Plate',                           weight: 3, element: 'Metal',   grade: 'C' },
  { label: 'Maximilian Plate Armor',                      weight: 3, element: 'Metal',   grade: 'C' },
  { label: 'Milanese Full Plate',                         weight: 3, element: 'Metal',   grade: 'C' },
  { label: 'Tournament Plate Armor',                      weight: 3, element: 'Metal',   grade: 'C' },
  { label: 'Knight\'s Full Harness',                      weight: 3, element: 'Metal',   grade: 'C' },
  { label: 'Man-at-Arms Harness',                         weight: 3, element: 'Metal',   grade: 'C' },
  { label: 'Samurai O-Yoroi',                             weight: 3, element: 'Metal',   grade: 'C' },
  { label: 'Samurai Tosei-Gusoku',                        weight: 3, element: 'Metal',   grade: 'C' },
  { label: 'Roman Legionnaire Full Kit',                  weight: 2, element: 'Metal',   grade: 'C' },
  { label: 'Greek Hoplite Panoply',                       weight: 2, element: 'Metal',   grade: 'C' },
  { label: 'Byzantine Cataphract Armor',                  weight: 2, element: 'Metal',   grade: 'C' },
  { label: 'Viking Mail Hauberk (Extended)',               weight: 2, element: 'Metal',   grade: 'C' },
  { label: 'Dark Knight\'s Midnight Plate',               weight: 2, element: 'Shadow',  grade: 'B' },
  { label: 'Blood Knight\'s Sanguine Armor',              weight: 2, element: 'Blood',   grade: 'B' },
  { label: 'Shadow Stalker\'s Void Plate',                weight: 2, element: 'Shadow',  grade: 'B' },
  { label: 'Battle Mage\'s Force Plate',                  weight: 2, element: 'Arcane',  grade: 'B' },
  { label: 'Artificer\'s Mechanical Plate Suit',          weight: 2, element: 'Metal',   grade: 'B' },
  { label: 'Iron Man Suit (Home-Built Version)',           weight: 2, element: 'Metal',   grade: 'B' },
  { label: 'Power Armor (Needs Charging)',                 weight: 2, element: 'Metal',   grade: 'A' },
  { label: 'Powered Exosuit (Economy Class)',             weight: 2, element: 'Metal',   grade: 'B' },
  { label: 'Hardlight Barrier Suit',                      weight: 2, element: 'Light',   grade: 'B' },
  { label: 'Nanofiber Full Combat Suit',                  weight: 2, element: 'Metal',   grade: 'B' },
  { label: 'Space Marine Powered Armor',                  weight: 2, element: 'Metal',   grade: 'A' },
  { label: 'Elven Mithril Full Plate',                    weight: 2, element: 'Arcane',  grade: 'A' },
  { label: 'Dwarven Masterwork Adamantine',               weight: 2, element: 'Metal',   grade: 'A' },
  { label: 'Orc-Forged Brutal Plate (Heavy)',             weight: 2, element: 'Metal',   grade: 'B' },
  { label: 'Dragon Slayer\'s Scale Plate',                weight: 1, element: 'Nature',  grade: 'A' },
  { label: 'Dragonheart Full Plate',                      weight: 1, element: 'Nature',  grade: 'A' },
  { label: 'Wyvern Plate Suit',                           weight: 2, element: 'Nature',  grade: 'B' },
  { label: 'Cardboard Box Suit (Artisanal)',               weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Mattress Fort Armor (Deconstructed)',         weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Bubble Suit (Full Coverage)',                 weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Pillowfort Plate (Four-Star Comfort)',        weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Inflatable Sumo Suit (Combat Grade)',         weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'LEGO Full Suit (Structural Integrity: TBD)',  weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Stuffed Animal Armor Set',                    weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Moving Blanket Suit (Reinforced)',            weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Snail Shell (Rented)',                        weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Pool Float Plate (Floaty But Functional)',    weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Suit of Armor Full of Bees (Offensive)',      weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Refrigerator Box Full Plate',                 weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Mughal War Armor (Full)',                     weight: 2, element: 'Metal',   grade: 'B' },
  { label: 'Korean Brigandine Full Suit',                 weight: 2, element: 'Metal',   grade: 'B' },
  { label: 'Lich\'s Bone Plate Full Suit',               weight: 1, element: 'Soul',    grade: 'A' },
  { label: 'Celestial Plate (Gifted)',                    weight: 1, element: 'Light',   grade: 'S' },
  { label: 'Infernal Plate (Cursed Origin)',              weight: 1, element: 'Fire',    grade: 'A' },
  { label: 'Phoenix Plate (Reforms on Death)',            weight: 1, element: 'Fire',    grade: 'A' },
  { label: 'Drop Trooper Ceramic Full Suit',              weight: 2, element: 'Metal',   grade: 'C' },
  { label: 'Energy Field Full Plate',                     weight: 2, element: 'Arcane',  grade: 'C' },
  { label: 'Particle Shield Suit',                        weight: 2, element: 'Arcane',  grade: 'C' },
]

const exotic: SimpleItem[] = [
  { label: 'Symbiote Suit (Willing)',                      weight: 2, element: 'Void',    grade: 'B' },
  { label: 'Living Carapace (Slightly Disagreeable)',      weight: 2, element: 'Nature',  grade: 'B' },
  { label: 'Coral Reef Armor (Breathing)',                 weight: 2, element: 'Nature',  grade: 'C' },
  { label: 'Crystal Golem Plate',                         weight: 2, element: 'Earth',   grade: 'B' },
  { label: 'Obsidian Shell',                              weight: 2, element: 'Earth',   grade: 'C' },
  { label: 'Shadow-Woven Armor',                          weight: 2, element: 'Shadow',  grade: 'B' },
  { label: 'Temporal Displacement Suit',                  weight: 2, element: 'Time',    grade: 'B' },
  { label: 'Phase-Shift Plating',                         weight: 2, element: 'Void',    grade: 'B' },
  { label: 'Gravity Weave Armor',                         weight: 2, element: 'Gravity', grade: 'B' },
  { label: 'Sound-Dampening Plate',                       weight: 2, element: 'Sound',   grade: 'B' },
  { label: 'Light-Bending Cloak (Armor Rating Included)', weight: 2, element: 'Shadow',  grade: 'C' },
  { label: 'Anti-Magic Plate (Annoying to Everyone)',      weight: 2, element: 'Arcane',  grade: 'B' },
  { label: 'Soul-Bound Exoskeleton (Wants Things)',        weight: 2, element: 'Soul',    grade: 'B' },
  { label: 'Bone Plate (Self-Assembled)',                  weight: 2, element: 'Soul',    grade: 'C' },
  { label: 'Chitinous Exoskeleton (Organic)',              weight: 2, element: 'Nature',  grade: 'C' },
  { label: 'Bark Armor (Treant Heritage)',                 weight: 2, element: 'Nature',  grade: 'C' },
  { label: 'Crystal Lattice Suit',                        weight: 2, element: 'Earth',   grade: 'C' },
  { label: 'Iron-Wood Full Plate',                        weight: 2, element: 'Earth',   grade: 'C' },
  { label: 'Seastone Chainmail (Anti-Power)',              weight: 2, element: 'Water',   grade: 'C' },
  { label: 'Haki-Hardened Plate',                         weight: 2, element: 'Neutral', grade: 'C' },
  { label: 'Chakra Channeling Suit',                      weight: 2, element: 'Arcane',  grade: 'C' },
  { label: 'Automail Full Plate',                         weight: 2, element: 'Metal',   grade: 'B' },
  { label: 'Breathing Armor (Self-Sustaining)',            weight: 2, element: 'Nature',  grade: 'C' },
  { label: 'Titan Hardening Armor (Crystalline)',         weight: 2, element: 'Earth',   grade: 'B' },
  { label: 'Nen Coating (Full Body)',                      weight: 2, element: 'Arcane',  grade: 'C' },
  { label: 'Phantom Armor (Passes Through People)',        weight: 2, element: 'Psychic', grade: 'B' },
  { label: 'Astral Plate (Multiple Planes Simultaneous)', weight: 1, element: 'Cosmic',  grade: 'S' },
  { label: 'Dream-Forged Armor',                          weight: 2, element: 'Psychic', grade: 'C' },
  { label: 'Paradox Plate (Exists Before You Put It On)', weight: 2, element: 'Time',    grade: 'A' },
  { label: 'Probability Shell (Sometimes There)',          weight: 2, element: 'Chaos',   grade: 'B' },
  { label: 'Void-Forged Carapace',                        weight: 2, element: 'Void',    grade: 'S' },
  { label: 'Quantum Superposition Plate (On and Off)',    weight: 2, element: 'Void',    grade: 'A' },
  { label: 'Time-Locked Suit (Permanent 2PM)',            weight: 2, element: 'Time',    grade: 'B' },
  { label: 'Living Metal Exoskeleton (Hungry)',            weight: 2, element: 'Metal',   grade: 'C' },
  { label: 'Starweave Armor (Dead Star Forged)',          weight: 1, element: 'Cosmic',  grade: 'S' },
  { label: 'Nebula Plate',                                weight: 1, element: 'Cosmic',  grade: 'S' },
  { label: 'Singularity Shell (Very Dense)',               weight: 1, element: 'Cosmic',  grade: 'S' },
  { label: 'Micro-Rune Exosuit',                          weight: 2, element: 'Arcane',  grade: 'B' },
  { label: 'Hive Mind Shell (Connected)',                 weight: 2, element: 'Psychic', grade: 'B' },
  { label: 'Slime Armor (Regenerates)',                   weight: 2, element: 'Nature',  grade: 'C' },
  { label: 'Sand Armor (Constantly Rebuilding)',          weight: 2, element: 'Earth',   grade: 'C' },
  { label: 'Lava Stone Shell (Warm)',                     weight: 2, element: 'Fire',    grade: 'C' },
  { label: 'Ice Lattice Plate (Cold)',                    weight: 2, element: 'Ice',     grade: 'C' },
  { label: 'Amber Fossil Armor',                          weight: 2, element: 'Earth',   grade: 'C' },
  { label: 'Volcanic Rock Carapace',                      weight: 2, element: 'Fire',   grade: 'C' },
  { label: 'Natural Claws and Thick Hide (No Armor Needed)', weight: 3, element: 'Nature', grade: 'C' },
  { label: 'Spiritual Chain Mail',                        weight: 2, element: 'Soul',    grade: 'C' },
  { label: 'Null-Space Armor',                            weight: 2, element: 'Void',    grade: 'B' },
  { label: 'Automail Exoskeleton (Full Combat Config)',   weight: 2, element: 'Metal',   grade: 'B' },
  { label: 'Ancestral Plate (Haunted Positively)',         weight: 2, element: 'Soul',    grade: 'B' },
  { label: 'Rune-Animated Plate (Self-Moving)',            weight: 2, element: 'Arcane',  grade: 'B' },
  { label: 'Elemental Integration Armor',                 weight: 2, element: 'Arcane',  grade: 'C' },
  { label: 'Galaxy-Woven Suit',                           weight: 1, element: 'Cosmic',  grade: 'S' },
  { label: 'Titan\'s Crystallized Hardening',             weight: 1, element: 'Cosmic',  grade: 'S' },
  { label: 'Comet Tail Cape-Armor',                       weight: 1, element: 'Cosmic',  grade: 'S' },
]

const cursed: SimpleItem[] = [
  { label: 'Bloodpact Plate (Binds to Your Blood)',        weight: 3, element: 'Blood',   grade: 'C' },
  { label: 'Soul-Tethered Chainmail',                     weight: 3, element: 'Soul',    grade: 'C' },
  { label: 'Damnation Plate (One-Way Agreement)',          weight: 3, element: 'Soul',    grade: 'C' },
  { label: 'The Armor That Won\'t Come Off',              weight: 3, element: 'Chaos',   grade: 'C' },
  { label: 'Haunted Breastplate (Previous Owner Inside)', weight: 3, element: 'Soul',    grade: 'C' },
  { label: 'Cursed Plate (Laughs at Bad Jokes)',          weight: 3, element: 'Chaos',   grade: 'F' },
  { label: 'Wailing Chainmail (Very Loud)',                weight: 3, element: 'Sound',   grade: 'C' },
  { label: 'Betrayal Suit (Fights For Both Sides)',        weight: 3, element: 'Chaos',   grade: 'F' },
  { label: 'Misfortune Mail (Breaks at Key Moments)',      weight: 3, element: 'Chaos',   grade: 'F' },
  { label: 'Jinxed Full Plate (Everything Is Fine)',       weight: 3, element: 'Chaos',   grade: 'F' },
  { label: 'Hex-Forged Plate (Mild Hex Only)',             weight: 3, element: 'Arcane',  grade: 'C' },
  { label: 'Vengeful Carapace (Holds Grudges)',            weight: 3, element: 'Soul',    grade: 'C' },
  { label: 'Irony Plate (Hurts You with Irony)',           weight: 3, element: 'Chaos',   grade: 'C' },
  { label: 'Regret Chainmail (Haunts You)',                weight: 3, element: 'Soul',    grade: 'C' },
  { label: 'Wraith Shroud (Partially Incorporeal)',        weight: 2, element: 'Shadow',  grade: 'C' },
  { label: 'Gorgon\'s Stone Mantle (Petrification Risk)', weight: 2, element: 'Earth',   grade: 'C' },
  { label: 'Medusa\'s Gaze Armor (Mirror Finish)',         weight: 2, element: 'Poison',  grade: 'C' },
  { label: 'Cursed Skeleton Suit (You Are the Skeleton)', weight: 2, element: 'Soul',    grade: 'C' },
  { label: 'Lich\'s Phylactery Plate (Keeps You Alive)',  weight: 2, element: 'Soul',    grade: 'C' },
  { label: 'Vampire Shroud Armor',                        weight: 2, element: 'Shadow',  grade: 'C' },
  { label: 'Demon-Branded Plate',                         weight: 2, element: 'Fire',    grade: 'C' },
  { label: 'Devil\'s Bargain Armor',                      weight: 2, element: 'Fire',    grade: 'C' },
  { label: 'Fae-Cursed Mail (Unpredictable)',              weight: 2, element: 'Chaos',   grade: 'C' },
  { label: 'Chaos Armor (Random Stats Each Day)',         weight: 2, element: 'Chaos',   grade: 'C' },
  { label: 'Poltergeist Plate (Moves on Its Own)',         weight: 2, element: 'Chaos',   grade: 'B' },
  { label: 'Bad Luck Suit',                               weight: 3, element: 'Chaos',   grade: 'F' },
  { label: 'Hex Loop Mail (Curses Loop Back)',             weight: 3, element: 'Arcane',  grade: 'C' },
  { label: 'Ancient Witch\'s Plate',                      weight: 2, element: 'Arcane',  grade: 'C' },
  { label: 'Broken Mirror Plate (Seven Reasons)',          weight: 3, element: 'Chaos',   grade: 'F' },
  { label: 'Jinx Suit (It Knows)',                        weight: 3, element: 'Chaos',   grade: 'C' },
  { label: 'Karma Chestplate (You Feel It)',              weight: 3, element: 'Soul',    grade: 'C' },
  { label: 'Demonic Pact Plate',                          weight: 2, element: 'Fire',    grade: 'C' },
  { label: 'Eldritch Horror Suit (Witnessing It Hurts)',  weight: 2, element: 'Void',    grade: 'B' },
  { label: 'Void-Touched Mail',                           weight: 2, element: 'Void',    grade: 'B' },
  { label: 'Abyss-Stained Plate',                         weight: 2, element: 'Void',    grade: 'B' },
  { label: 'Corruption Carapace (Slowly Winning)',        weight: 2, element: 'Shadow',  grade: 'C' },
  { label: 'Suffering Amplifier Suit',                    weight: 2, element: 'Soul',    grade: 'C' },
  { label: 'Stolen Valor Armor (Fake)',                   weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Werewolf-Skin Suit (Uncomfortable)',          weight: 2, element: 'Blood',   grade: 'C' },
  { label: 'Black Cat\'s Pelt Armor (Seven More Years)',  weight: 3, element: 'Chaos',   grade: 'C' },
]

const ancient: SimpleItem[] = [
  { label: 'Primordial Stone Plate (Pre-History)',         weight: 2, element: 'Earth',   grade: 'B' },
  { label: 'First-Forged Iron (Origin Point)',             weight: 2, element: 'Metal',   grade: 'B' },
  { label: 'Adamantine Full Plate (Absolute Hardness)',   weight: 2, element: 'Metal',   grade: 'A' },
  { label: 'Orichalcum Plate (Lost Formula)',             weight: 2, element: 'Metal',   grade: 'A' },
  { label: 'Starmetal Plate (Meteorite Forged)',          weight: 2, element: 'Cosmic',  grade: 'A' },
  { label: 'Celestial Bronze Plate (God-Forged)',         weight: 2, element: 'Light',   grade: 'A' },
  { label: 'Moonsilver Mail (Lunar Forged)',              weight: 2, element: 'Ice',     grade: 'A' },
  { label: 'Sunfire Plate (Sol-Forged)',                  weight: 2, element: 'Fire',    grade: 'A' },
  { label: 'Voidsteel Carapace (Pre-Universe)',           weight: 1, element: 'Void',    grade: 'S' },
  { label: 'Titan\'s Raiment (God-Scale)',                weight: 1, element: 'Cosmic',  grade: 'SS' },
  { label: 'Godskin Plate (Do Not Ask)',                  weight: 1, element: 'Soul',    grade: 'SSS' },
  { label: 'Dragonheart Aegis (Dragon God Origin)',       weight: 1, element: 'Nature',  grade: 'SS' },
  { label: 'Phoenix Father Plate (First Phoenix)',        weight: 1, element: 'Fire',    grade: 'SS' },
  { label: 'World-Serpent Scale Plate (Ouroboros)',       weight: 1, element: 'Nature',  grade: 'SS' },
  { label: 'Behemoth Plate (Living World Fragment)',      weight: 1, element: 'Earth',   grade: 'SS' },
  { label: 'First Warrior\'s Battered Plate',             weight: 2, element: 'Metal',   grade: 'C' },
  { label: 'Dawn-Era Battlesuit',                         weight: 2, element: 'Light',   grade: 'C' },
  { label: 'Creation-Age Full Plate',                     weight: 2, element: 'Arcane',  grade: 'C' },
  { label: 'Myth-Time Armor',                             weight: 2, element: 'Arcane',  grade: 'C' },
  { label: 'Atlantean Full Plate (Sunken)',                weight: 2, element: 'Water',   grade: 'B' },
  { label: 'Olympian Plate (Gifted by Zeus)',             weight: 2, element: 'Light',   grade: 'S' },
  { label: 'Asgardian Ring Mail',                         weight: 2, element: 'Light',   grade: 'A' },
  { label: 'Egyptian Pharaoh\'s War Plate',               weight: 2, element: 'Light',   grade: 'B' },
  { label: 'Greek Hero\'s Panoply (Achilles Grade)',      weight: 2, element: 'Light',   grade: 'A' },
  { label: 'Precursor Battlesuit',                        weight: 1, element: 'Metal',   grade: 'SS' },
  { label: 'Antediluvian Plate (Pre-Flood)',              weight: 1, element: 'Water',   grade: 'SS' },
  { label: 'Dwarf-Lord\'s First Masterwork',              weight: 2, element: 'Metal',   grade: 'B' },
  { label: 'Dragon King\'s Ancient Shell',                weight: 1, element: 'Nature',  grade: 'S' },
  { label: 'Ancient Lich\'s Pre-Death Armor',             weight: 1, element: 'Soul',    grade: 'S' },
  { label: 'Former God\'s Discarded Shell',               weight: 1, element: 'Light',   grade: 'SSS' },
  { label: 'Fallen Angel\'s Wing-Plate',                  weight: 1, element: 'Light',   grade: 'S' },
  { label: 'Celestial Shard Plate',                       weight: 1, element: 'Light',   grade: 'S' },
  { label: 'Void Ancestor\'s Remnant Shell',              weight: 1, element: 'Void',    grade: 'SSS' },
  { label: 'The Last Plate From the Previous Universe',   weight: 1, element: 'Cosmic',  grade: 'SSS' },
  { label: 'Plate of the First Champion',                 weight: 1, element: 'Metal',   grade: 'SSS' },
  { label: 'Star Knight\'s Celestial Shell',              weight: 2, element: 'Cosmic',  grade: 'C' },
  { label: 'Spartan War God\'s Armor',                    weight: 2, element: 'Light',   grade: 'A' },
  { label: 'Elven Age-of-Stars Plate',                    weight: 2, element: 'Arcane',  grade: 'S' },
  { label: 'Mesopotamian Hero\'s Mail',                   weight: 2, element: 'Metal',   grade: 'A' },
  { label: 'Roman God-Plate (Jupiter\'s Own)',             weight: 1, element: 'Light',   grade: 'S' },
]

export const armorsByCategory: Record<string, SimpleItem[]> = {
  'Helmet Only': helmetOnly,
  'Half-Suit':   halfSuit,
  'Full-Suit':   fullSuit,
  'Exotic':      exotic,
  'Cursed':      cursed,
  'Ancient':     ancient,
}

export const armors: SimpleItem[] = [
  ...helmetOnly, ...halfSuit, ...fullSuit, ...exotic, ...cursed, ...ancient,
]
