// Armor Strength scale: F- = bathrobe / nothing, mortal mid = trauma plate carrier,
// A range = world-class composite armor, S+ = mythical plate,
// SS-SSS = legendary alloys, Cosmic+ = post-mortal protection,
// Infinite+ = armor beyond armor.
import type { FlavorLabel } from './types'

export const armorStrengthLabels: FlavorLabel[] = [
  { label: 'Bathrobe',                                       weight: 4, tier: 'F-',            score: 2,   color: '#4a4a4a' },
  { label: 'Threadbare Cloth',                               weight: 4, tier: 'F',             score: 5,   color: '#5c5c5c' },
  { label: 'Patched Leather',                                weight: 4, tier: 'F+',            score: 8,   color: '#6e6e6e' },
  { label: 'Studded Leather',                                weight: 6, tier: 'E-',            score: 11,  color: '#6b7280' },
  { label: 'Basic Padded Armor',                             weight: 6, tier: 'E',             score: 14,  color: '#9ca3af' },
  { label: 'Boiled Leather',                                 weight: 6, tier: 'E+',            score: 17,  color: '#d1d5db' },
  { label: 'Chain Shirt',                                    weight: 8, tier: 'D-',            score: 20,  color: '#92400e' },
  { label: 'Soft Body Armor',                                weight: 8, tier: 'D',             score: 23,  color: '#b45309' },
  { label: 'Tactical Vest',                                  weight: 8, tier: 'D+',            score: 26,  color: '#d97706' },
  { label: 'Riot Suit',                                      weight: 8, tier: 'C-',            score: 30,  color: '#1d4ed8' },
  { label: 'Standard Trauma Plate Carrier',                  weight: 9, tier: 'C',             score: 34,  color: '#2563eb' },
  { label: 'Heavy Ceramic Plate',                            weight: 8, tier: 'C+',            score: 38,  color: '#3b82f6' },
  { label: 'Steel Half-Plate',                               weight: 7, tier: 'B-',            score: 42,  color: '#065f46' },
  { label: 'Full Knight Harness',                            weight: 7, tier: 'B',             score: 47,  color: '#059669' },
  { label: 'Peak Composite Plate',                           weight: 7, tier: 'B+',            score: 52,  color: '#34d399' },
  { label: 'World-Class Composite Armor',                    weight: 5, tier: 'A-',            score: 57,  color: '#7c3aed' },
  { label: 'Adamantine Half-Suit',                           weight: 5, tier: 'A',             score: 62,  color: '#8b5cf6' },
  { label: 'Master-Forged Plate',                            weight: 5, tier: 'A+',            score: 67,  color: '#a78bfa' },
  { label: 'Mythril Mail',                                   weight: 4, tier: 'S-',            score: 72,  color: '#b91c1c' },
  { label: 'Dragonscale Plate',                              weight: 4, tier: 'S',             score: 77,  color: '#dc2626' },
  { label: 'Rune-Inscribed Full Plate',                      weight: 4, tier: 'S+',            score: 81,  color: '#ef4444' },
  { label: 'Adamant Plate of the Old Kingdoms',              weight: 3, tier: 'SS-',           score: 85,  color: '#ea580c' },
  { label: 'Star-Forged Armor',                              weight: 3, tier: 'SS',            score: 88,  color: '#f97316' },
  { label: 'Black-Iron Aegis',                               weight: 3, tier: 'SS+',           score: 91,  color: '#fb923c' },
  { label: 'Plate of the Eternal King',                      weight: 2, tier: 'SSS-',          score: 94,  color: '#ca8a04' },
  { label: 'Plate That No Blade Has Ever Pierced',           weight: 2, tier: 'SSS',           score: 97,  color: '#eab308' },
  { label: 'World-Tree Armor',                               weight: 2, tier: 'SSS+',          score: 99,  color: '#fde047' },
  { label: 'Plate Forged From a Dead Star',                  weight: 2, tier: 'Z-',            score: 101, color: '#be185d' },
  { label: 'Armor Mined From a Collapsed Universe',          weight: 2, tier: 'Z',             score: 103, color: '#db2777' },
  { label: 'Voidsteel Bulwark',                              weight: 2, tier: 'Z+',            score: 105, color: '#ec4899' },
  { label: 'Multiversal Aegis',                              weight: 1, tier: 'ZZ-',           score: 107, color: '#6d28d9' },
  { label: 'Armor That Re-Forges Itself',                    weight: 1, tier: 'ZZ',            score: 109, color: '#7c3aed' },
  { label: 'Plate That Filters Reality Out',                 weight: 1, tier: 'ZZ+',           score: 111, color: '#8b5cf6' },
  { label: 'Indestructible Shell',                           weight: 1, tier: 'ZZZ-',          score: 113, color: '#0e7490' },
  { label: 'Mantle of Outlived Realities',                   weight: 1, tier: 'ZZZ',           score: 115, color: '#06b6d4' },
  { label: 'Plate That Has No Surface to Strike',            weight: 1, tier: 'ZZZ+',          score: 117, color: '#22d3ee' },
  { label: 'Cosmic Aegis',                                   weight: 1, tier: 'Cosmic-',       score: 119, color: '#0e6b8a' },
  { label: 'Plate Cut From the Cosmic Crown',                weight: 1, tier: 'Cosmic',        score: 121, color: '#0891b2' },
  { label: 'Armor Lined With Constellations',                weight: 1, tier: 'Cosmic+',       score: 123, color: '#06b6d4' },
  { label: 'Plate That Outlives Eras',                       weight: 1, tier: 'Immortal-',     score: 125, color: '#d946ef' },
  { label: 'Immortal-Class Harness',                         weight: 1, tier: 'Immortal',      score: 127, color: '#ec4899' },
  { label: 'Mantle That Refuses to End',                     weight: 1, tier: 'Immortal+',     score: 129, color: '#f472b6' },
  { label: 'Plate of the Divine Vanguard',                   weight: 1, tier: 'Celestial-',    score: 131, color: '#831843' },
  { label: 'Celestial-Forged Aegis',                         weight: 1, tier: 'Celestial',     score: 133, color: '#9d174d' },
  { label: 'Halo-Forged Bulwark',                            weight: 1, tier: 'Celestial+',    score: 135, color: '#be185d' },
  { label: 'Armor Worn by a Living God',                     weight: 1, tier: 'Godly-',        score: 137, color: '#f9a8d4' },
  { label: 'Plate of the Pantheon',                          weight: 1, tier: 'Godly',         score: 139, color: '#f472b6' },
  { label: 'Mantle of the First Throne',                     weight: 1, tier: 'Godly+',        score: 141, color: '#ec4899' },
  { label: 'First Armor Ever Forged',                        weight: 1, tier: 'Primordial-',   score: 143, color: '#d4d4d8' },
  { label: 'Plate Older Than Damage Itself',                 weight: 1, tier: 'Primordial',    score: 145, color: '#e4e4e7' },
  { label: 'Aegis That Defined "Protection"',                weight: 1, tier: 'Primordial+',   score: 147, color: '#fafafa' },
  { label: 'Absolute Plate',                                 weight: 1, tier: 'Absolute-',     score: 149, color: '#7dd3fc' },
  { label: 'Armor That Decides What Can Strike It',          weight: 1, tier: 'Absolute',      score: 151, color: '#38bdf8' },
  { label: 'Bulwark of the First Law',                       weight: 1, tier: 'Absolute+',     score: 153, color: '#0ea5e9' },
  { label: 'Beyond the Concept of Armor',                    weight: 1, tier: 'Transcendent-', score: 155, color: '#84cc16' },
  { label: 'Protection That Transcends Itself',              weight: 1, tier: 'Transcendent',  score: 157, color: '#65a30d' },
  { label: 'Plate Made of "Cannot Be Harmed"',               weight: 1, tier: 'Transcendent+', score: 159, color: '#4d7c0f' },
  { label: 'Infinite Plate',                                 weight: 1, tier: 'Infinite-',     score: 161, color: '#525252' },
  { label: 'Truly Infinite Armor',                           weight: 1, tier: 'Infinite',      score: 163, color: '#262626' },
  { label: 'Beyond Infinite Aegis',                          weight: 1, tier: 'Infinite+',     score: 165, color: '#000000' },
]
