// Armor strength flavor labels — one per tier grade, F- through God
import type { FlavorLabel } from './types'

export const armorStrengthLabels: FlavorLabel[] = [
  { label: 'Made of Wet Paper',                        weight: 4, tier: 'F-',   score: 2,   color: '#555'    },
  { label: 'Technically Present',                      weight: 4, tier: 'F',    score: 5,   color: '#666'    },
  { label: 'Stops Very Slow Projectiles',              weight: 4, tier: 'F+',   score: 8,   color: '#777'    },
  { label: 'Basic Leather Caliber',                    weight: 6, tier: 'E-',   score: 11,  color: '#6b7280' },
  { label: 'Standard Non-Combatant Grade',             weight: 6, tier: 'E',    score: 14,  color: '#9ca3af' },
  { label: 'Reduces Bruising (Sometimes)',             weight: 6, tier: 'E+',   score: 17,  color: '#d1d5db' },
  { label: 'Reliable Against Glancing Blows',          weight: 8, tier: 'D-',   score: 20,  color: '#92400e' },
  { label: 'Combat Rated, Loosely',                    weight: 8, tier: 'D',    score: 23,  color: '#b45309' },
  { label: 'Holds Together in a Fight',                weight: 8, tier: 'D+',   score: 26,  color: '#d97706' },
  { label: 'Properly Tempered Steel',                  weight: 8, tier: 'C-',   score: 30,  color: '#1d4ed8' },
  { label: 'Battle-Tested and Approved',               weight: 8, tier: 'C',    score: 34,  color: '#2563eb' },
  { label: 'Deflects Serious Blows',                   weight: 8, tier: 'C+',   score: 38,  color: '#3b82f6' },
  { label: 'Military Specification',                   weight: 7, tier: 'B-',   score: 42,  color: '#065f46' },
  { label: "Knight's Standard Issue",                  weight: 7, tier: 'B',    score: 47,  color: '#059669' },
  { label: 'Legendary Smithwork Grade',                weight: 7, tier: 'B+',   score: 52,  color: '#34d399' },
  { label: 'Absorbs Catastrophic Impacts',             weight: 5, tier: 'A-',   score: 57,  color: '#7c3aed' },
  { label: 'Siege Weapon Tested',                      weight: 5, tier: 'A',    score: 62,  color: '#8b5cf6' },
  { label: 'Functionally Inviolable',                  weight: 5, tier: 'A+',   score: 67,  color: '#a78bfa' },
  { label: 'Proof Against Conventional Reality',       weight: 4, tier: 'S-',   score: 72,  color: '#b91c1c' },
  { label: 'Has Never Been Dented',                    weight: 4, tier: 'S',    score: 77,  color: '#dc2626' },
  { label: 'Inspires Existential Dread in Attackers',  weight: 4, tier: 'S+',   score: 81,  color: '#ef4444' },
  { label: 'Absorbs Attacks That Defy Physics',        weight: 3, tier: 'SS-',  score: 85,  color: '#ea580c' },
  { label: 'The Armor Has Opinions Now',               weight: 3, tier: 'SS',   score: 88,  color: '#f97316' },
  { label: 'Weapons Reconsider Their Life Choices',    weight: 3, tier: 'SS+',  score: 91,  color: '#fb923c' },
  { label: 'Worn by Things That Predate Damage',            weight: 2, tier: 'SSS-',      score: 94,  color: '#ca8a04' },
  { label: 'Cannot Be Harmed Within This Universe',         weight: 2, tier: 'SSS',       score: 97,  color: '#eab308' },
  { label: 'The Attack Legally Did Not Happen',             weight: 2, tier: 'SSS+',      score: 99,  color: '#fde047' },
  { label: 'Protected by the Laws of a Neighboring Universe', weight: 2, tier: 'Z-',      score: 101, color: '#0e7490' },
  { label: 'Armor Exists Across All Timelines Simultaneously', weight: 2, tier: 'Z',      score: 103, color: '#0891b2' },
  { label: 'The Damage Occurred in a Different Dimension',  weight: 2, tier: 'Z+',        score: 105, color: '#06b6d4' },
  { label: 'Impact Is Redirected to a Fictional Scenario',  weight: 1, tier: 'ZZ-',       score: 107, color: '#3730a3' },
  { label: 'Armor Absorbs Attacks Before They Are Thrown',  weight: 1, tier: 'ZZ',        score: 109, color: '#4f46e5' },
  { label: 'Defense That Exceeds Any Known Force',          weight: 1, tier: 'ZZ+',       score: 111, color: '#818cf8' },
  { label: 'Armor Has Transcended Being Hit',               weight: 1, tier: 'ZZZ-',      score: 113, color: '#9d174d' },
  { label: 'The Attack Has Been Informed It Will Not Proceed', weight: 1, tier: 'ZZZ',    score: 115, color: '#be185d' },
  { label: 'Reality Agrees Not to Harm the Wearer',         weight: 1, tier: 'ZZZ+',      score: 117, color: '#ec4899' },
  { label: 'Armor Forged in the Divine Realm',              weight: 1, tier: 'Celestial-',score: 119, color: '#075985' },
  { label: 'Blessed by Every Pantheon Simultaneously',      weight: 1, tier: 'Celestial', score: 121, color: '#0284c7' },
  { label: 'Even Divine Weapons Bounce Off',                weight: 1, tier: 'Celestial+',score: 123, color: '#38bdf8' },
  { label: 'Armor That Redefines Invulnerable',             weight: 1, tier: 'Godly-',    score: 125, color: '#c026d3' },
  { label: 'Armor Is Now a Fundamental Law of Physics',     weight: 1, tier: 'Godly',     score: 127, color: '#e879f9' },
  { label: 'Worn Before Damage Was Conceptualized',         weight: 1, tier: 'Primordial',score: 130, color: '#ffffff' },
]
