// backstories.ts — Backstory content pool for Wheel of Fate.
// 17+ SimpleItem entries. No default export. No functions. Static const array only.

import type { SimpleItem } from './types'

export const backstories: SimpleItem[] = [
  { label: 'Raised by wolves (they have complicated feelings about it)', weight: 1 },
  { label: 'Former accountant — the darkness chose them', weight: 1 },
  { label: 'Bit by a radioactive middle manager', weight: 1 },
  { label: 'Survived by being too stubborn to die', weight: 1 },
  { label: 'Woke up in a field with no memory and excellent posture', weight: 1 },
  { label: 'Prophecy child (the prophecy was vague and possibly about someone else)', weight: 1 },
  { label: 'Built different — literally, in a lab', weight: 1 },
  { label: 'Lost everything to a villain who monologued for too long', weight: 1 },
  { label: 'Just passing through and got involved somehow', weight: 1 },
  { label: 'Studied abroad; dimension was unspecified', weight: 1 },
  { label: 'Grew up on the wrong side of a pocket dimension', weight: 1 },
  { label: 'Professional adventurer (tax purposes)', weight: 1 },
  { label: 'Failed hero of a different story', weight: 1 },
  { label: 'Reluctant chosen one', weight: 1 },
  { label: 'Lived in a tower; asked zero questions', weight: 1 },
  { label: 'Escaped a fate worse than death (the estate planning)', weight: 1 },
  { label: 'Technically dead, but working on it', weight: 1 },
  { label: 'Revenge quest that somehow became a career', weight: 1 },
  { label: 'Touched by a god who immediately regretted it', weight: 1 },
  { label: 'Made a deal at a crossroads; still unclear on the terms', weight: 1 },
  { label: 'Found in a meteor crater wrapped in mystery (and a weird blanket)', weight: 1 },
  { label: 'Heir to a kingdom nobody told them about until adulthood', weight: 1 },
  { label: 'Last survivor of a tragedy they caused accidentally', weight: 1 },
  { label: 'Retired assassin (three more jobs, then retired assassin)', weight: 1 },
  { label: 'Former child prodigy, now average adult, extremely bitter', weight: 1 },
  { label: 'Chose power over love; now has both and neither is satisfying', weight: 1 },
  { label: 'The villain in someone else\'s story', weight: 1 },
  { label: 'Saved the world; nobody knows; they have feelings about that', weight: 1 },
  { label: 'Clone of someone legendary with absolutely none of their skills', weight: 1 },
  { label: 'Time traveller who messed up and is now stuck in the present', weight: 1 },
  { label: 'Survived the apocalypse because they were in the bathroom', weight: 1 },
  { label: 'Accidentally absorbed a god\'s power at an open-buffet divine feast', weight: 1 },
  { label: 'Born at the exact moment of a prophecy, the wrong prophecy', weight: 1 },
  { label: 'The one who got away (from multiple factions, simultaneously)', weight: 1 },
  { label: 'Left home seeking fortune; found chaos; considering the fortune', weight: 1 },
  { label: 'Wrongly imprisoned; correctly escaped; technically a fugitive', weight: 1 },
  { label: 'Raised by a library (the books were very formative)', weight: 1 },
  { label: 'Was a potato farmer until the potato farmer chosen by prophecy was unavailable', weight: 1 },
  { label: 'Literally fell into this from a portal while trying to get to work', weight: 1 },
  { label: 'Wrote a strongly-worded letter that changed the course of history', weight: 1 },
]
