import type { FlavorLabel } from './types'

// Charisma scale: F- = repellent presence, mortal mid = popular professional,
// A range = world-class charismatic leader / influencer, S+ = mass-movement leader,
// SS-SSS = inspires civilizations, Cosmic+ = post-mortal charm,
// Infinite+ = charisma beyond infinity.
export const charismaLabels: FlavorLabel[] = [
  { label: 'Aggressively Off-Putting',                       weight: 4, tier: 'F-',            score: 2,   color: '#4a4a4a' },
  { label: 'People Cross the Street',                        weight: 4, tier: 'F',             score: 5,   color: '#5c5c5c' },
  { label: 'Conversation-Ender',                             weight: 4, tier: 'F+',            score: 8,   color: '#6e6e6e' },
  { label: 'Forgettable',                                    weight: 6, tier: 'E-',            score: 11,  color: '#6b7280' },
  { label: 'Pleasant Enough',                                weight: 6, tier: 'E',             score: 14,  color: '#9ca3af' },
  { label: 'Easy to Talk To',                                weight: 6, tier: 'E+',            score: 17,  color: '#d1d5db' },
  { label: 'Reliably Likable',                               weight: 8, tier: 'D-',            score: 20,  color: '#92400e' },
  { label: 'Office Favorite',                                weight: 8, tier: 'D',             score: 23,  color: '#b45309' },
  { label: 'Naturally Magnetic',                             weight: 8, tier: 'D+',            score: 26,  color: '#d97706' },
  { label: 'Popular Co-Worker',                              weight: 8, tier: 'C-',            score: 30,  color: '#1d4ed8' },
  { label: 'Local Celebrity Energy',                         weight: 9, tier: 'C',             score: 34,  color: '#2563eb' },
  { label: 'Crowd-Working Presenter',                        weight: 8, tier: 'C+',            score: 38,  color: '#3b82f6' },
  { label: 'Skilled Negotiator',                             weight: 7, tier: 'B-',            score: 42,  color: '#065f46' },
  { label: 'National Figure',                                weight: 7, tier: 'B',             score: 47,  color: '#059669' },
  { label: 'Peak Human Charm',                               weight: 7, tier: 'B+',            score: 52,  color: '#34d399' },
  { label: 'World-Class Orator',                             weight: 5, tier: 'A-',            score: 57,  color: '#7c3aed' },
  { label: 'Generation-Defining Influence',                  weight: 5, tier: 'A',             score: 62,  color: '#8b5cf6' },
  { label: 'Movement Leader',                                weight: 5, tier: 'A+',            score: 67,  color: '#a78bfa' },
  { label: 'Superhumanly Convincing',                        weight: 4, tier: 'S-',            score: 72,  color: '#b91c1c' },
  { label: 'Crowds Follow Without Question',                 weight: 4, tier: 'S',             score: 77,  color: '#dc2626' },
  { label: 'Persuades Anyone of Anything',                   weight: 4, tier: 'S+',            score: 81,  color: '#ef4444' },
  { label: 'Inspires Whole Nations',                         weight: 3, tier: 'SS-',           score: 85,  color: '#ea580c' },
  { label: 'Civilizations Form Around Their Word',           weight: 3, tier: 'SS',            score: 88,  color: '#f97316' },
  { label: 'Mass-Movement Architect',                        weight: 3, tier: 'SS+',           score: 91,  color: '#fb923c' },
  { label: 'Reality Bends Toward Their Confidence',          weight: 2, tier: 'SSS-',          score: 94,  color: '#ca8a04' },
  { label: 'Diplomacy Personified',                          weight: 2, tier: 'SSS',           score: 97,  color: '#eab308' },
  { label: 'Speaks and Outcomes Comply',                     weight: 2, tier: 'SSS+',          score: 99,  color: '#fde047' },
  { label: 'Galaxies Listen When They Speak',                weight: 2, tier: 'Z-',            score: 101, color: '#be185d' },
  { label: 'Multiversal Influence',                          weight: 2, tier: 'Z',             score: 103, color: '#db2777' },
  { label: 'Persuades Realities to Cooperate',               weight: 2, tier: 'Z+',            score: 105, color: '#ec4899' },
  { label: 'Even Concepts Want to Be Their Friend',          weight: 1, tier: 'ZZ-',           score: 107, color: '#6d28d9' },
  { label: 'The Multiverse Has a Crush',                     weight: 1, tier: 'ZZ',            score: 109, color: '#7c3aed' },
  { label: 'Reality Negotiates on Their Behalf',             weight: 1, tier: 'ZZ+',           score: 111, color: '#8b5cf6' },
  { label: 'Every Existing Thing Quietly Roots for Them',    weight: 1, tier: 'ZZZ-',          score: 113, color: '#0e7490' },
  { label: 'Causality Wants Them to Win',                    weight: 1, tier: 'ZZZ',           score: 115, color: '#06b6d4' },
  { label: 'Existence Sends Birthday Cards',                 weight: 1, tier: 'ZZZ+',          score: 117, color: '#22d3ee' },
  { label: 'Cosmic-Scale Magnetism',                         weight: 1, tier: 'Cosmic-',       score: 119, color: '#0e6b8a' },
  { label: 'Stars Lean In to Hear Them',                     weight: 1, tier: 'Cosmic',        score: 121, color: '#0891b2' },
  { label: 'Galaxies Send Delegations',                      weight: 1, tier: 'Cosmic+',       score: 123, color: '#06b6d4' },
  { label: 'Charm That Outlives Empires',                    weight: 1, tier: 'Immortal-',     score: 125, color: '#d946ef' },
  { label: 'Immortal-Class Presence',                        weight: 1, tier: 'Immortal',      score: 127, color: '#ec4899' },
  { label: 'Has Charmed Beings That No Longer Exist',        weight: 1, tier: 'Immortal+',     score: 129, color: '#f472b6' },
  { label: 'Even the Divine Are Starstruck',                 weight: 1, tier: 'Celestial-',    score: 131, color: '#831843' },
  { label: 'Celestial Courts Quote Them',                    weight: 1, tier: 'Celestial',     score: 133, color: '#9d174d' },
  { label: 'Pantheons Defer to Their Judgement',             weight: 1, tier: 'Celestial+',    score: 135, color: '#be185d' },
  { label: 'Persuasion That Bends the Divine Will',          weight: 1, tier: 'Godly-',        score: 137, color: '#f9a8d4' },
  { label: 'Gods Argue Over Their Approval',                 weight: 1, tier: 'Godly',         score: 139, color: '#f472b6' },
  { label: 'Even the Old Powers Bow Politely',               weight: 1, tier: 'Godly+',        score: 141, color: '#ec4899' },
  { label: 'Charmed Reality Into Existing',                  weight: 1, tier: 'Primordial-',   score: 143, color: '#d4d4d8' },
  { label: 'Authored the Idea of "Likable"',                 weight: 1, tier: 'Primordial',    score: 145, color: '#e4e4e7' },
  { label: 'Shapes Narrative Arcs by Existing in Them',      weight: 1, tier: 'Primordial+',   score: 147, color: '#fafafa' },
  { label: 'Absolute Charm',                                 weight: 1, tier: 'Absolute-',     score: 149, color: '#7dd3fc' },
  { label: 'Everyone Always Agrees With Them',               weight: 1, tier: 'Absolute',      score: 151, color: '#38bdf8' },
  { label: 'Persuasion Itself Is Their Native Tongue',       weight: 1, tier: 'Absolute+',     score: 153, color: '#0ea5e9' },
  { label: 'Beyond the Idea of Charm',                       weight: 1, tier: 'Transcendent-', score: 155, color: '#84cc16' },
  { label: 'Influence Transcends Will Itself',               weight: 1, tier: 'Transcendent',  score: 157, color: '#65a30d' },
  { label: 'Nothing Has Ever Said No to Them',               weight: 1, tier: 'Transcendent+', score: 159, color: '#4d7c0f' },
  { label: 'Infinite Charisma',                              weight: 1, tier: 'Infinite-',     score: 161, color: '#525252' },
  { label: 'Truly Infinite Presence',                        weight: 1, tier: 'Infinite',      score: 163, color: '#262626' },
  { label: 'Beyond Infinite Charm',                          weight: 1, tier: 'Infinite+',     score: 165, color: '#000000' },
]
