import type { FlavorLabel } from './types'

export const charismaLabels: FlavorLabel[] = [
  // F- (score: 2)
  { label: 'Cleared a Room by Walking In', weight: 1, tier: 'F-', score: 2, color: 'var(--tier-f-minus)' },
  { label: 'Repels Eye Contact on Sight', weight: 1, tier: 'F-', score: 2, color: 'var(--tier-f-minus)' },
  { label: 'Awkward Silence Generator', weight: 1, tier: 'F-', score: 2, color: 'var(--tier-f-minus)' },
  { label: 'Handshakes Go Wrong Somehow', weight: 1, tier: 'F-', score: 2, color: 'var(--tier-f-minus)' },
  { label: 'People Suddenly Remember Appointments', weight: 1, tier: 'F-', score: 2, color: 'var(--tier-f-minus)' },
  { label: 'Social Antimatter', weight: 1, tier: 'F-', score: 2, color: 'var(--tier-f-minus)' },
  { label: 'Introduced Twice at Same Party', weight: 1, tier: 'F-', score: 2, color: 'var(--tier-f-minus)' },
  { label: 'Makes Plants Wilt', weight: 1, tier: 'F-', score: 2, color: 'var(--tier-f-minus)' },
  { label: 'Conversation Graveyard', weight: 1, tier: 'F-', score: 2, color: 'var(--tier-f-minus)' },
  { label: 'Actively Avoided at Networking Events', weight: 1, tier: 'F-', score: 2, color: 'var(--tier-f-minus)' },
  { label: 'Parties End When They Arrive', weight: 1, tier: 'F-', score: 2, color: 'var(--tier-f-minus)' },
  { label: 'Forgot Mid-Sentence by Listeners', weight: 1, tier: 'F-', score: 2, color: 'var(--tier-f-minus)' },
  { label: 'Exudes Beige Energy', weight: 1, tier: 'F-', score: 2, color: 'var(--tier-f-minus)' },
  { label: 'Humor Always Lands Flat', weight: 1, tier: 'F-', score: 2, color: 'var(--tier-f-minus)' },
  { label: 'Charisma Score: -7', weight: 1, tier: 'F-', score: 2, color: 'var(--tier-f-minus)' },
  { label: 'Pets Run Away Too', weight: 1, tier: 'F-', score: 2, color: 'var(--tier-f-minus)' },
  { label: 'Invited Out of Pity Only', weight: 1, tier: 'F-', score: 2, color: 'var(--tier-f-minus)' },
  { label: 'Generates Social Debt', weight: 1, tier: 'F-', score: 2, color: 'var(--tier-f-minus)' },
  { label: 'The Wet Blanket Personified', weight: 1, tier: 'F-', score: 2, color: 'var(--tier-f-minus)' },
  { label: 'NPC Energy (Background)', weight: 1, tier: 'F-', score: 2, color: 'var(--tier-f-minus)' },

  // F (score: 5)
  { label: 'Forgettable at Best', weight: 1, tier: 'F', score: 5, color: 'var(--tier-f)' },
  { label: 'People Vaguely Recall Someone Was There', weight: 1, tier: 'F', score: 5, color: 'var(--tier-f)' },
  { label: 'Interrupts Themselves Talking', weight: 1, tier: 'F', score: 5, color: 'var(--tier-f)' },
  { label: 'Speaks in Filler Words Only', weight: 1, tier: 'F', score: 5, color: 'var(--tier-f)' },
  { label: 'Laughs at Own Jokes Alone', weight: 1, tier: 'F', score: 5, color: 'var(--tier-f)' },
  { label: 'Holds Door; Nobody Thanks Them', weight: 1, tier: 'F', score: 5, color: 'var(--tier-f)' },
  { label: 'Stories Have No Point', weight: 1, tier: 'F', score: 5, color: 'var(--tier-f)' },
  { label: 'Mispronounces Own Name Under Pressure', weight: 1, tier: 'F', score: 5, color: 'var(--tier-f)' },
  { label: 'Waved Back at Someone Waving at Someone Else', weight: 1, tier: 'F', score: 5, color: 'var(--tier-f)' },
  { label: 'Background Character Energy', weight: 1, tier: 'F', score: 5, color: 'var(--tier-f)' },
  { label: 'Invisible in Groups Under 3', weight: 1, tier: 'F', score: 5, color: 'var(--tier-f)' },
  { label: 'Overshares Immediately', weight: 1, tier: 'F', score: 5, color: 'var(--tier-f)' },
  { label: 'Accidentally Insulting', weight: 1, tier: 'F', score: 5, color: 'var(--tier-f)' },
  { label: 'Cannot Make Small Talk', weight: 1, tier: 'F', score: 5, color: 'var(--tier-f)' },
  { label: 'Speaks in Monotone', weight: 1, tier: 'F', score: 5, color: 'var(--tier-f)' },
  { label: 'Kills Vibes Softly', weight: 1, tier: 'F', score: 5, color: 'var(--tier-f)' },
  { label: 'Eye Contact Too Much or None', weight: 1, tier: 'F', score: 5, color: 'var(--tier-f)' },
  { label: 'Laugh Always Timed Wrong', weight: 1, tier: 'F', score: 5, color: 'var(--tier-f)' },
  { label: 'Memorable Only for Bad Reasons', weight: 1, tier: 'F', score: 5, color: 'var(--tier-f)' },
  { label: 'Forgot the Plot Mid-Story', weight: 1, tier: 'F', score: 5, color: 'var(--tier-f)' },

  // F+ (score: 8)
  { label: 'Slightly Less Forgettable', weight: 1, tier: 'F+', score: 8, color: 'var(--tier-f-plus)' },
  { label: 'Occasionally Makes People Smile', weight: 1, tier: 'F+', score: 8, color: 'var(--tier-f-plus)' },
  { label: 'Technically Likeable', weight: 1, tier: 'F+', score: 8, color: 'var(--tier-f-plus)' },
  { label: 'Decent Handshake, Bad Eye Contact', weight: 1, tier: 'F+', score: 8, color: 'var(--tier-f-plus)' },
  { label: 'Gets Invited to Some Things', weight: 1, tier: 'F+', score: 8, color: 'var(--tier-f-plus)' },
  { label: 'Recognized by First Name, Rarely', weight: 1, tier: 'F+', score: 8, color: 'var(--tier-f-plus)' },
  { label: 'Told One Good Joke Ever', weight: 1, tier: 'F+', score: 8, color: 'var(--tier-f-plus)' },
  { label: 'Tolerated in Most Settings', weight: 1, tier: 'F+', score: 8, color: 'var(--tier-f-plus)' },
  { label: 'Not the Last Choice', weight: 1, tier: 'F+', score: 8, color: 'var(--tier-f-plus)' },
  { label: 'Presence Noted but Not Celebrated', weight: 1, tier: 'F+', score: 8, color: 'var(--tier-f-plus)' },
  { label: 'Mildly Amusing on Good Days', weight: 1, tier: 'F+', score: 8, color: 'var(--tier-f-plus)' },
  { label: 'Occasionally Makes Others Comfortable', weight: 1, tier: 'F+', score: 8, color: 'var(--tier-f-plus)' },
  { label: 'People Vaguely Remember Their Name', weight: 1, tier: 'F+', score: 8, color: 'var(--tier-f-plus)' },
  { label: 'Once Made a Crowd Chuckle', weight: 1, tier: 'F+', score: 8, color: 'var(--tier-f-plus)' },
  { label: 'Warming Up to Likeable', weight: 1, tier: 'F+', score: 8, color: 'var(--tier-f-plus)' },
  { label: 'Acceptable Small Talk', weight: 1, tier: 'F+', score: 8, color: 'var(--tier-f-plus)' },
  { label: 'Manages to Seem Interested', weight: 1, tier: 'F+', score: 8, color: 'var(--tier-f-plus)' },
  { label: 'Nods at the Right Times', weight: 1, tier: 'F+', score: 8, color: 'var(--tier-f-plus)' },
  { label: 'Gets a Seat at the Table (Corner)', weight: 1, tier: 'F+', score: 8, color: 'var(--tier-f-plus)' },
  { label: 'Presence Mildly Appreciated', weight: 1, tier: 'F+', score: 8, color: 'var(--tier-f-plus)' },

  // E- (score: 11)
  { label: 'Actually Remembers Names', weight: 1, tier: 'E-', score: 11, color: 'var(--tier-e-minus)' },
  { label: 'Decent at Introductions', weight: 1, tier: 'E-', score: 11, color: 'var(--tier-e-minus)' },
  { label: 'Sometimes Makes Friends', weight: 1, tier: 'E-', score: 11, color: 'var(--tier-e-minus)' },
  { label: 'Tells Passable Stories', weight: 1, tier: 'E-', score: 11, color: 'var(--tier-e-minus)' },
  { label: 'Compliments Land 50% of the Time', weight: 1, tier: 'E-', score: 11, color: 'var(--tier-e-minus)' },
  { label: 'Knows When to Shut Up', weight: 1, tier: 'E-', score: 11, color: 'var(--tier-e-minus)' },
  { label: 'Reliably Remembered the Next Day', weight: 1, tier: 'E-', score: 11, color: 'var(--tier-e-minus)' },
  { label: 'Gets Invited Back Most Times', weight: 1, tier: 'E-', score: 11, color: 'var(--tier-e-minus)' },
  { label: 'Reads the Room Occasionally', weight: 1, tier: 'E-', score: 11, color: 'var(--tier-e-minus)' },
  { label: 'Leaves Good-ish Impressions', weight: 1, tier: 'E-', score: 11, color: 'var(--tier-e-minus)' },
  { label: 'Humor Lands on Second Try', weight: 1, tier: 'E-', score: 11, color: 'var(--tier-e-minus)' },
  { label: 'Earns Polite Applause', weight: 1, tier: 'E-', score: 11, color: 'var(--tier-e-minus)' },
  { label: 'People Enjoy Their Company Somewhat', weight: 1, tier: 'E-', score: 11, color: 'var(--tier-e-minus)' },
  { label: 'Convinces Others of Basic Things', weight: 1, tier: 'E-', score: 11, color: 'var(--tier-e-minus)' },
  { label: 'Negotiates Small Disagreements', weight: 1, tier: 'E-', score: 11, color: 'var(--tier-e-minus)' },
  { label: 'Warm Smile, Remembered', weight: 1, tier: 'E-', score: 11, color: 'var(--tier-e-minus)' },
  { label: 'Decent Presence in a Room', weight: 1, tier: 'E-', score: 11, color: 'var(--tier-e-minus)' },
  { label: 'Makes Others Feel Heard', weight: 1, tier: 'E-', score: 11, color: 'var(--tier-e-minus)' },
  { label: 'Groups Glad They Joined', weight: 1, tier: 'E-', score: 11, color: 'var(--tier-e-minus)' },
  { label: 'People Seek Them Out at Gatherings', weight: 1, tier: 'E-', score: 11, color: 'var(--tier-e-minus)' },

  // E (score: 14)
  { label: 'Genuinely Likeable', weight: 1, tier: 'E', score: 14, color: 'var(--tier-e)' },
  { label: 'Makes a Good First Impression', weight: 1, tier: 'E', score: 14, color: 'var(--tier-e)' },
  { label: 'Easy to Talk To', weight: 1, tier: 'E', score: 14, color: 'var(--tier-e)' },
  { label: 'Remembered Fondly', weight: 1, tier: 'E', score: 14, color: 'var(--tier-e)' },
  { label: 'Wins Arguments Politely', weight: 1, tier: 'E', score: 14, color: 'var(--tier-e)' },
  { label: 'Natural at Small Groups', weight: 1, tier: 'E', score: 14, color: 'var(--tier-e)' },
  { label: 'Gets the Crowd Going', weight: 1, tier: 'E', score: 14, color: 'var(--tier-e)' },
  { label: 'Frequently Asked for Opinions', weight: 1, tier: 'E', score: 14, color: 'var(--tier-e)' },
  { label: 'Jokes Actually Land', weight: 1, tier: 'E', score: 14, color: 'var(--tier-e)' },
  { label: 'Reads the Room Well', weight: 1, tier: 'E', score: 14, color: 'var(--tier-e)' },
  { label: 'Commands Mild Attention', weight: 1, tier: 'E', score: 14, color: 'var(--tier-e)' },
  { label: 'Warm Handshake, Solid Presence', weight: 1, tier: 'E', score: 14, color: 'var(--tier-e)' },
  { label: 'Remembered at Follow-Up', weight: 1, tier: 'E', score: 14, color: 'var(--tier-e)' },
  { label: 'Makes Strangers Comfortable', weight: 1, tier: 'E', score: 14, color: 'var(--tier-e)' },
  { label: 'Persuasion Has Consistent Effect', weight: 1, tier: 'E', score: 14, color: 'var(--tier-e)' },
  { label: 'People Tell Them Secrets', weight: 1, tier: 'E', score: 14, color: 'var(--tier-e)' },
  { label: 'Often Asked to Lead Small Tasks', weight: 1, tier: 'E', score: 14, color: 'var(--tier-e)' },
  { label: 'Instinctively Diplomatic', weight: 1, tier: 'E', score: 14, color: 'var(--tier-e)' },
  { label: 'Elevated Vibes on Entry', weight: 1, tier: 'E', score: 14, color: 'var(--tier-e)' },
  { label: 'Groups Orbit Them Naturally', weight: 1, tier: 'E', score: 14, color: 'var(--tier-e)' },

  // E+ (score: 17)
  { label: 'Charismatic in Most Situations', weight: 1, tier: 'E+', score: 17, color: 'var(--tier-e-plus)' },
  { label: 'Smooths Over Tense Moments', weight: 1, tier: 'E+', score: 17, color: 'var(--tier-e-plus)' },
  { label: 'Likeable to Strangers Instantly', weight: 1, tier: 'E+', score: 17, color: 'var(--tier-e-plus)' },
  { label: 'Wins With a Smile', weight: 1, tier: 'E+', score: 17, color: 'var(--tier-e-plus)' },
  { label: 'People Feel Better Near Them', weight: 1, tier: 'E+', score: 17, color: 'var(--tier-e-plus)' },
  { label: 'Magnetic in Small Doses', weight: 1, tier: 'E+', score: 17, color: 'var(--tier-e-plus)' },
  { label: 'Rarely Loses a Debate', weight: 1, tier: 'E+', score: 17, color: 'var(--tier-e-plus)' },
  { label: 'Elevated Energy on Entry', weight: 1, tier: 'E+', score: 17, color: 'var(--tier-e-plus)' },
  { label: 'Gets Free Upgrades Occasionally', weight: 1, tier: 'E+', score: 17, color: 'var(--tier-e-plus)' },
  { label: 'Persuades Without Pressure', weight: 1, tier: 'E+', score: 17, color: 'var(--tier-e-plus)' },
  { label: 'Commands Moderate Attention', weight: 1, tier: 'E+', score: 17, color: 'var(--tier-e-plus)' },
  { label: 'Knows What Everyone Wants to Hear', weight: 1, tier: 'E+', score: 17, color: 'var(--tier-e-plus)' },
  { label: 'Held in High Regard Among Peers', weight: 1, tier: 'E+', score: 17, color: 'var(--tier-e-plus)' },
  { label: 'Makes Long-Term Fans', weight: 1, tier: 'E+', score: 17, color: 'var(--tier-e-plus)' },
  { label: 'Stories Always Hit', weight: 1, tier: 'E+', score: 17, color: 'var(--tier-e-plus)' },
  { label: 'Disarms Hostility Instinctively', weight: 1, tier: 'E+', score: 17, color: 'var(--tier-e-plus)' },
  { label: 'Fills Silence Effortlessly', weight: 1, tier: 'E+', score: 17, color: 'var(--tier-e-plus)' },
  { label: 'Mentioned in Conversations Later', weight: 1, tier: 'E+', score: 17, color: 'var(--tier-e-plus)' },
  { label: 'Recruits People Without Asking', weight: 1, tier: 'E+', score: 17, color: 'var(--tier-e-plus)' },
  { label: 'Reputation Precedes Them', weight: 1, tier: 'E+', score: 17, color: 'var(--tier-e-plus)' },

  // D- (score: 20)
  { label: 'Noticeably Charming', weight: 1, tier: 'D-', score: 20, color: 'var(--tier-d-minus)' },
  { label: 'Commands a Room on a Good Day', weight: 1, tier: 'D-', score: 20, color: 'var(--tier-d-minus)' },
  { label: 'People Root for Them', weight: 1, tier: 'D-', score: 20, color: 'var(--tier-d-minus)' },
  { label: 'Has a Fanbase, Small but Loyal', weight: 1, tier: 'D-', score: 20, color: 'var(--tier-d-minus)' },
  { label: 'Convinces People Quickly', weight: 1, tier: 'D-', score: 20, color: 'var(--tier-d-minus)' },
  { label: 'Gets Things Done Through Others', weight: 1, tier: 'D-', score: 20, color: 'var(--tier-d-minus)' },
  { label: 'Smiles That Stick in Memory', weight: 1, tier: 'D-', score: 20, color: 'var(--tier-d-minus)' },
  { label: 'Referred to as "That Person"', weight: 1, tier: 'D-', score: 20, color: 'var(--tier-d-minus)' },
  { label: 'Draws Eyes When They Enter', weight: 1, tier: 'D-', score: 20, color: 'var(--tier-d-minus)' },
  { label: 'Deals Close on First Meeting', weight: 1, tier: 'D-', score: 20, color: 'var(--tier-d-minus)' },
  { label: 'Remembered by Everyone in the Room', weight: 1, tier: 'D-', score: 20, color: 'var(--tier-d-minus)' },
  { label: 'Handles Crowds Comfortably', weight: 1, tier: 'D-', score: 20, color: 'var(--tier-d-minus)' },
  { label: 'Generates Positive Word of Mouth', weight: 1, tier: 'D-', score: 20, color: 'var(--tier-d-minus)' },
  { label: 'Charisma Noticed by Rivals', weight: 1, tier: 'D-', score: 20, color: 'var(--tier-d-minus)' },
  { label: 'Earns Trust Ahead of Schedule', weight: 1, tier: 'D-', score: 20, color: 'var(--tier-d-minus)' },
  { label: 'Turns Skeptics Into Allies', weight: 1, tier: 'D-', score: 20, color: 'var(--tier-d-minus)' },
  { label: 'People Describe as "Magnetic"', weight: 1, tier: 'D-', score: 20, color: 'var(--tier-d-minus)' },
  { label: 'Regularly Sought for Advice', weight: 1, tier: 'D-', score: 20, color: 'var(--tier-d-minus)' },
  { label: 'Small-Scale Influencer Energy', weight: 1, tier: 'D-', score: 20, color: 'var(--tier-d-minus)' },
  { label: 'Always Has a Seat Saved', weight: 1, tier: 'D-', score: 20, color: 'var(--tier-d-minus)' },

  // D (score: 23)
  { label: 'Commanding Presence', weight: 1, tier: 'D', score: 23, color: 'var(--tier-d)' },
  { label: 'Wins Crowds Over in Minutes', weight: 1, tier: 'D', score: 23, color: 'var(--tier-d)' },
  { label: 'People Change Minds for Them', weight: 1, tier: 'D', score: 23, color: 'var(--tier-d)' },
  { label: 'Causes Line-Cutting Through Aura Alone', weight: 1, tier: 'D', score: 23, color: 'var(--tier-d)' },
  { label: 'Generates Loyal Allies Rapidly', weight: 1, tier: 'D', score: 23, color: 'var(--tier-d)' },
  { label: 'Gets Standing Ovations at Low Bars', weight: 1, tier: 'D', score: 23, color: 'var(--tier-d)' },
  { label: 'Negotiates Down Impossible Terms', weight: 1, tier: 'D', score: 23, color: 'var(--tier-d)' },
  { label: 'Inspires Others Just by Existing', weight: 1, tier: 'D', score: 23, color: 'var(--tier-d)' },
  { label: 'Has Informal Authority', weight: 1, tier: 'D', score: 23, color: 'var(--tier-d)' },
  { label: 'Starts Social Movements Accidentally', weight: 1, tier: 'D', score: 23, color: 'var(--tier-d)' },
  { label: 'People Quit Their Plans to Talk', weight: 1, tier: 'D', score: 23, color: 'var(--tier-d)' },
  { label: 'Makes the Room Feel Warmer', weight: 1, tier: 'D', score: 23, color: 'var(--tier-d)' },
  { label: 'Aura That Precedes Arrival', weight: 1, tier: 'D', score: 23, color: 'var(--tier-d)' },
  { label: 'Enemies Become Friends Often', weight: 1, tier: 'D', score: 23, color: 'var(--tier-d)' },
  { label: 'Spoken of With Reverence', weight: 1, tier: 'D', score: 23, color: 'var(--tier-d)' },
  { label: 'Strangers Trust Them Immediately', weight: 1, tier: 'D', score: 23, color: 'var(--tier-d)' },
  { label: 'Group Decisions Favor Them by Default', weight: 1, tier: 'D', score: 23, color: 'var(--tier-d)' },
  { label: 'Opinion-Shifting Just by Tone', weight: 1, tier: 'D', score: 23, color: 'var(--tier-d)' },
  { label: 'Creates Mild Cults of Personality', weight: 1, tier: 'D', score: 23, color: 'var(--tier-d)' },
  { label: 'Has a Fanclub They Never Asked For', weight: 1, tier: 'D', score: 23, color: 'var(--tier-d)' },

  // D+ (score: 26)
  { label: 'Extremely Well-Liked', weight: 1, tier: 'D+', score: 26, color: 'var(--tier-d-plus)' },
  { label: 'Wins Debates Before They Start', weight: 1, tier: 'D+', score: 26, color: 'var(--tier-d-plus)' },
  { label: 'Turns Crowds Into Supporters', weight: 1, tier: 'D+', score: 26, color: 'var(--tier-d-plus)' },
  { label: 'Rooms Reorganize Around Them', weight: 1, tier: 'D+', score: 26, color: 'var(--tier-d-plus)' },
  { label: 'Described as Unforgettable', weight: 1, tier: 'D+', score: 26, color: 'var(--tier-d-plus)' },
  { label: 'Starts Trends Without Trying', weight: 1, tier: 'D+', score: 26, color: 'var(--tier-d+)', },
  { label: 'Gets Out of Anything With Words', weight: 1, tier: 'D+', score: 26, color: 'var(--tier-d-plus)' },
  { label: 'Enemies Silently Respect Them', weight: 1, tier: 'D+', score: 26, color: 'var(--tier-d-plus)' },
  { label: 'Words Carry Weight in Any Room', weight: 1, tier: 'D+', score: 26, color: 'var(--tier-d-plus)' },
  { label: 'People Volunteer for Their Causes', weight: 1, tier: 'D+', score: 26, color: 'var(--tier-d-plus)' },
  { label: 'Generates Goodwill at Scale', weight: 1, tier: 'D+', score: 26, color: 'var(--tier-d-plus)' },
  { label: 'Makes Crowds Feel Chosen', weight: 1, tier: 'D+', score: 26, color: 'var(--tier-d-plus)' },
  { label: 'Speeches That Change Directions', weight: 1, tier: 'D+', score: 26, color: 'var(--tier-d-plus)' },
  { label: 'Asked to Lead Before Being Ready', weight: 1, tier: 'D+', score: 26, color: 'var(--tier-d-plus)' },
  { label: 'Spontaneous Standing Ovation Territory', weight: 1, tier: 'D+', score: 26, color: 'var(--tier-d-plus)' },
  { label: 'Entire Groups Shift Priorities for Them', weight: 1, tier: 'D+', score: 26, color: 'var(--tier-d-plus)' },
  { label: 'Causes Bidding Wars at Auction', weight: 1, tier: 'D+', score: 26, color: 'var(--tier-d-plus)' },
  { label: 'Unites Rivals Over Common Admiration', weight: 1, tier: 'D+', score: 26, color: 'var(--tier-d-plus)' },
  { label: 'Inspires Loyalty in Strangers', weight: 1, tier: 'D+', score: 26, color: 'var(--tier-d-plus)' },
  { label: 'Born Diplomat', weight: 1, tier: 'D+', score: 26, color: 'var(--tier-d-plus)' },

  // C- (score: 30)
  { label: 'Natural Leader Aura', weight: 1, tier: 'C-', score: 30, color: 'var(--tier-c-minus)' },
  { label: 'Crowds Quiet When They Speak', weight: 1, tier: 'C-', score: 30, color: 'var(--tier-c-minus)' },
  { label: 'Gets Standing Ovations Regularly', weight: 1, tier: 'C-', score: 30, color: 'var(--tier-c-minus)' },
  { label: 'Rival Factions Pause for Them', weight: 1, tier: 'C-', score: 30, color: 'var(--tier-c-minus)' },
  { label: 'Has Unofficial Followers', weight: 1, tier: 'C-', score: 30, color: 'var(--tier-c-minus)' },
  { label: 'Negotiates Impossible Peace Deals', weight: 1, tier: 'C-', score: 30, color: 'var(--tier-c-minus)' },
  { label: 'Can Defuse Any Situation', weight: 1, tier: 'C-', score: 30, color: 'var(--tier-c-minus)' },
  { label: 'Remembered in Story Form', weight: 1, tier: 'C-', score: 30, color: 'var(--tier-c-minus)' },
  { label: 'People Quote Them Daily', weight: 1, tier: 'C-', score: 30, color: 'var(--tier-c-minus)' },
  { label: 'Presence Alters the Atmosphere', weight: 1, tier: 'C-', score: 30, color: 'var(--tier-c-minus)' },
  { label: 'Politicians Seek Their Endorsement', weight: 1, tier: 'C-', score: 30, color: 'var(--tier-c-minus)' },
  { label: 'Causes Spontaneous Applause', weight: 1, tier: 'C-', score: 30, color: 'var(--tier-c-minus)' },
  { label: 'Reframes Arguments Until Everyone Wins', weight: 1, tier: 'C-', score: 30, color: 'var(--tier-c-minus)' },
  { label: 'Remembered Across Generations', weight: 1, tier: 'C-', score: 30, color: 'var(--tier-c-minus)' },
  { label: 'Media Wants to Cover Them', weight: 1, tier: 'C-', score: 30, color: 'var(--tier-c-minus)' },
  { label: 'Turns Haters Into Advocates', weight: 1, tier: 'C-', score: 30, color: 'var(--tier-c-minus)' },
  { label: 'Generates Loyalty Without Promise', weight: 1, tier: 'C-', score: 30, color: 'var(--tier-c-minus)' },
  { label: 'Gets Nations Talking', weight: 1, tier: 'C-', score: 30, color: 'var(--tier-c-minus)' },
  { label: 'Inspires Chills With a Look', weight: 1, tier: 'C-', score: 30, color: 'var(--tier-c-minus)' },
  { label: 'Gives Great Speeches Accidentally', weight: 1, tier: 'C-', score: 30, color: 'var(--tier-c-minus)' },

  // C (score: 34)
  { label: 'Small Celebrity Energy', weight: 1, tier: 'C', score: 34, color: 'var(--tier-c)' },
  { label: 'People Move Aside Automatically', weight: 1, tier: 'C', score: 34, color: 'var(--tier-c)' },
  { label: 'Changes Group Dynamic by Arriving', weight: 1, tier: 'C', score: 34, color: 'var(--tier-c)' },
  { label: 'Recognized Across Industries', weight: 1, tier: 'C', score: 34, color: 'var(--tier-c)' },
  { label: 'Makes News Without Trying', weight: 1, tier: 'C', score: 34, color: 'var(--tier-c)' },
  { label: 'Inspirational Speaker Material', weight: 1, tier: 'C', score: 34, color: 'var(--tier-c)' },
  { label: 'Earns Unconditional Trust', weight: 1, tier: 'C', score: 34, color: 'var(--tier-c)' },
  { label: 'Words Echo After Leaving', weight: 1, tier: 'C', score: 34, color: 'var(--tier-c)' },
  { label: 'Casual Fan to Zealot Pipeline', weight: 1, tier: 'C', score: 34, color: 'var(--tier-c)' },
  { label: 'Starts Movements by Accident', weight: 1, tier: 'C', score: 34, color: 'var(--tier-c)' },
  { label: 'Enemies Become Devoted Advocates', weight: 1, tier: 'C', score: 34, color: 'var(--tier-c)' },
  { label: 'Voice Calms Riots', weight: 1, tier: 'C', score: 34, color: 'var(--tier-c)' },
  { label: 'People Want to Name Children After Them', weight: 1, tier: 'C', score: 34, color: 'var(--tier-c)' },
  { label: 'Causes Crowds to Weep From Words Alone', weight: 1, tier: 'C', score: 34, color: 'var(--tier-c)' },
  { label: 'Has the Gravity of a Sun', weight: 1, tier: 'C', score: 34, color: 'var(--tier-c)' },
  { label: 'Unites Nations With a Speech', weight: 1, tier: 'C', score: 34, color: 'var(--tier-c)' },
  { label: 'Cult Following — Multiple Countries', weight: 1, tier: 'C', score: 34, color: 'var(--tier-c)' },
  { label: 'Presence Causes Weather Changes', weight: 1, tier: 'C', score: 34, color: 'var(--tier-c)' },
  { label: 'Conviction So Strong It\'s Contagious', weight: 1, tier: 'C', score: 34, color: 'var(--tier-c)' },
  { label: 'Even Skeptics Follow Them', weight: 1, tier: 'C', score: 34, color: 'var(--tier-c)' },

  // C+ (score: 38)
  { label: 'Regional Legend', weight: 1, tier: 'C+', score: 38, color: 'var(--tier-c-plus)' },
  { label: 'Spontaneous Parades in Their Honor', weight: 1, tier: 'C+', score: 38, color: 'var(--tier-c-plus)' },
  { label: 'Governments Consult Them', weight: 1, tier: 'C+', score: 38, color: 'var(--tier-c-plus)' },
  { label: 'Animals Are Strangely Loyal', weight: 1, tier: 'C+', score: 38, color: 'var(--tier-c-plus)' },
  { label: 'Entire Ideologies Align to Their Words', weight: 1, tier: 'C+', score: 38, color: 'var(--tier-c-plus)' },
  { label: 'Causes Mass Conversions With a Look', weight: 1, tier: 'C+', score: 38, color: 'var(--tier-c-plus)' },
  { label: 'People Travel to Meet Them', weight: 1, tier: 'C+', score: 38, color: 'var(--tier-c-plus)' },
  { label: 'Starts Philosophies by Accident', weight: 1, tier: 'C+', score: 38, color: 'var(--tier-c-plus)' },
  { label: 'Has Unwanted Disciples', weight: 1, tier: 'C+', score: 38, color: 'var(--tier-c-plus)' },
  { label: 'Speeches Change Laws', weight: 1, tier: 'C+', score: 38, color: 'var(--tier-c-plus)' },
  { label: 'Causes Rivers to Divert Via Presence', weight: 1, tier: 'C+', score: 38, color: 'var(--tier-c-plus)' },
  { label: 'Charisma Visible From a Distance', weight: 1, tier: 'C+', score: 38, color: 'var(--tier-c-plus)' },
  { label: 'People Tattoo Their Face on Themselves', weight: 1, tier: 'C+', score: 38, color: 'var(--tier-c-plus)' },
  { label: 'Inspires Songs From Enemies', weight: 1, tier: 'C+', score: 38, color: 'var(--tier-c-plus)' },
  { label: 'Strangers Weep When They Leave', weight: 1, tier: 'C+', score: 38, color: 'var(--tier-c-plus)' },
  { label: 'Has Statues Pre-Made in Their Honor', weight: 1, tier: 'C+', score: 38, color: 'var(--tier-c-plus)' },
  { label: 'Borders Shift at Their Request', weight: 1, tier: 'C+', score: 38, color: 'var(--tier-c-plus)' },
  { label: 'Changes Belief Systems Casually', weight: 1, tier: 'C+', score: 38, color: 'var(--tier-c-plus)' },
  { label: 'Enemies Dedicate Art to Them', weight: 1, tier: 'C+', score: 38, color: 'var(--tier-c-plus)' },
  { label: 'Their Name Is Already a Legend', weight: 1, tier: 'C+', score: 38, color: 'var(--tier-c-plus)' },

  // B- (score: 42)
  { label: 'Global Celebrity', weight: 1, tier: 'B-', score: 42, color: 'var(--tier-b-minus)' },
  { label: 'Historically Famous by Accident', weight: 1, tier: 'B-', score: 42, color: 'var(--tier-b-minus)' },
  { label: 'Words Alter Timelines', weight: 1, tier: 'B-', score: 42, color: 'var(--tier-b-minus)' },
  { label: 'Nations Align to Their Preference', weight: 1, tier: 'B-', score: 42, color: 'var(--tier-b-minus)' },
  { label: 'Empires Built on Their Approval', weight: 1, tier: 'B-', score: 42, color: 'var(--tier-b-minus)' },
  { label: 'People Name Children AND Countries After Them', weight: 1, tier: 'B-', score: 42, color: 'var(--tier-b-minus)' },
  { label: 'Wars Paused to Hear Them Speak', weight: 1, tier: 'B-', score: 42, color: 'var(--tier-b-minus)' },
  { label: 'Causes Mass Epiphanies', weight: 1, tier: 'B-', score: 42, color: 'var(--tier-b-minus)' },
  { label: 'Presence Rearranges Crowds Instinctively', weight: 1, tier: 'B-', score: 42, color: 'var(--tier-b-minus)' },
  { label: 'Every Word Becomes Canonical', weight: 1, tier: 'B-', score: 42, color: 'var(--tier-b-minus)' },
  { label: 'Armies Lay Down Arms at Their Request', weight: 1, tier: 'B-', score: 42, color: 'var(--tier-b-minus)' },
  { label: 'Makes Kings Kneel Without Asking', weight: 1, tier: 'B-', score: 42, color: 'var(--tier-b-minus)' },
  { label: 'Has Religions Founded in Their Name (Uninvited)', weight: 1, tier: 'B-', score: 42, color: 'var(--tier-b-minus)' },
  { label: 'The Word "Charismatic" Insufficient Here', weight: 1, tier: 'B-', score: 42, color: 'var(--tier-b-minus)' },
  { label: 'Changes Civilizations on a Whim', weight: 1, tier: 'B-', score: 42, color: 'var(--tier-b-minus)' },
  { label: 'Presence Visible on Satellite Imagery', weight: 1, tier: 'B-', score: 42, color: 'var(--tier-b-minus)' },
  { label: 'Universe Leans Toward Their Opinion', weight: 1, tier: 'B-', score: 42, color: 'var(--tier-b-minus)' },
  { label: 'Convinces Planets to Relocate', weight: 1, tier: 'B-', score: 42, color: 'var(--tier-b-minus)' },
  { label: 'Galactic Influencer Status', weight: 1, tier: 'B-', score: 42, color: 'var(--tier-b-minus)' },
  { label: 'History Rewrites to Feature Them More', weight: 1, tier: 'B-', score: 42, color: 'var(--tier-b-minus)' },

  // B (score: 47)
  { label: 'Spoke Once and Ended a War', weight: 1, tier: 'B', score: 47, color: 'var(--tier-b)' },
  { label: 'Founded Civilizations With a Wave', weight: 1, tier: 'B', score: 47, color: 'var(--tier-b)' },
  { label: 'Entire Faiths Pivot on Their Whims', weight: 1, tier: 'B', score: 47, color: 'var(--tier-b)' },
  { label: 'Universes Reorganize to Please Them', weight: 1, tier: 'B', score: 47, color: 'var(--tier-b)' },
  { label: 'Causes Stars to Shine Brighter', weight: 1, tier: 'B', score: 47, color: 'var(--tier-b)' },
  { label: 'Omnipresent Social Gravitational Field', weight: 1, tier: 'B', score: 47, color: 'var(--tier-b)' },
  { label: 'Even the Dead Recall Them Fondly', weight: 1, tier: 'B', score: 47, color: 'var(--tier-b)' },
  { label: 'Animals Organize Themselves on Their Behalf', weight: 1, tier: 'B', score: 47, color: 'var(--tier-b)' },
  { label: 'Deities Rethink Their Stances', weight: 1, tier: 'B', score: 47, color: 'var(--tier-b)' },
  { label: 'Persuades Reality Itself', weight: 1, tier: 'B', score: 47, color: 'var(--tier-b)' },
  { label: 'Turns Atheists Into Fervent Believers (in Them)', weight: 1, tier: 'B', score: 47, color: 'var(--tier-b)' },
  { label: 'Creates Culture by Breathing', weight: 1, tier: 'B', score: 47, color: 'var(--tier-b)' },
  { label: 'The Concept of Charisma Was Named After Them', weight: 1, tier: 'B', score: 47, color: 'var(--tier-b)' },
  { label: 'Their Absence Is Itself Inspiring', weight: 1, tier: 'B', score: 47, color: 'var(--tier-b)' },
  { label: 'Aura Audible in Nearby Dimensions', weight: 1, tier: 'B', score: 47, color: 'var(--tier-b)' },
  { label: 'Wrote No Texts; Inspired All of Them', weight: 1, tier: 'B', score: 47, color: 'var(--tier-b)' },
  { label: 'Unasked-For Monuments on Every Continent', weight: 1, tier: 'B', score: 47, color: 'var(--tier-b)' },
  { label: 'Makes Mathematicians Feel Emotional', weight: 1, tier: 'B', score: 47, color: 'var(--tier-b)' },
  { label: 'The Universe Finds Them Relatable', weight: 1, tier: 'B', score: 47, color: 'var(--tier-b)' },
  { label: 'Presence Bends Probability Toward Applause', weight: 1, tier: 'B', score: 47, color: 'var(--tier-b)' },

  // B+ (score: 52)
  { label: 'Mythological Status Achieved Alive', weight: 1, tier: 'B+', score: 52, color: 'var(--tier-b-plus)' },
  { label: 'Inspired Every Major Cultural Shift', weight: 1, tier: 'B+', score: 52, color: 'var(--tier-b-plus)' },
  { label: 'People Write Books About Meeting Them', weight: 1, tier: 'B+', score: 52, color: 'var(--tier-b-plus)' },
  { label: 'Religions Form, Reform, and Dissolve on Their Mood', weight: 1, tier: 'B+', score: 52, color: 'var(--tier-b-plus)' },
  { label: 'Galaxies Have Opinions About Them', weight: 1, tier: 'B+', score: 52, color: 'var(--tier-b-plus)' },
  { label: 'Even Black Holes Change Course', weight: 1, tier: 'B+', score: 52, color: 'var(--tier-b-plus)' },
  { label: 'Social Gravity — Planets Orbit Them', weight: 1, tier: 'B+', score: 52, color: 'var(--tier-b-plus)' },
  { label: 'The Universe Applauds Their Entrance', weight: 1, tier: 'B+', score: 52, color: 'var(--tier-b-plus)' },
  { label: 'Words Become Naturally Binding', weight: 1, tier: 'B+', score: 52, color: 'var(--tier-b-plus)' },
  { label: 'Time Stops to Let Them Finish', weight: 1, tier: 'B+', score: 52, color: 'var(--tier-b-plus)' },
  { label: 'Spoken Name Causes Reverence', weight: 1, tier: 'B+', score: 52, color: 'var(--tier-b-plus)' },
  { label: 'All Arguments Resolved in Their Favor', weight: 1, tier: 'B+', score: 52, color: 'var(--tier-b-plus)' },
  { label: 'Metaphysical Fanbase', weight: 1, tier: 'B+', score: 52, color: 'var(--tier-b-plus)' },
  { label: 'The Very Concept of Persuasion Bows', weight: 1, tier: 'B+', score: 52, color: 'var(--tier-b-plus)' },
  { label: 'Nature Itself Cheers Them On', weight: 1, tier: 'B+', score: 52, color: 'var(--tier-b-plus)' },
  { label: 'Future Generations Remember Without Being Told', weight: 1, tier: 'B+', score: 52, color: 'var(--tier-b-plus)' },
  { label: 'Alternate Dimensions Follow Them on Socials', weight: 1, tier: 'B+', score: 52, color: 'var(--tier-b-plus)' },
  { label: 'Simulated Universes Built Around Them', weight: 1, tier: 'B+', score: 52, color: 'var(--tier-b-plus)' },
  { label: 'Reality Pitches Them Ideas', weight: 1, tier: 'B+', score: 52, color: 'var(--tier-b-plus)' },
  { label: 'Voted "Most Likely to Be Worshipped" by Physics', weight: 1, tier: 'B+', score: 52, color: 'var(--tier-b-plus)' },

  // A- (score: 57)
  { label: 'Post-Human Charm Level', weight: 1, tier: 'A-', score: 57, color: 'var(--tier-a-minus)' },
  { label: 'Gods Argue About Who Gets to Meet Them First', weight: 1, tier: 'A-', score: 57, color: 'var(--tier-a-minus)' },
  { label: 'Invented the Concept of Being Liked', weight: 1, tier: 'A-', score: 57, color: 'var(--tier-a-minus)' },
  { label: 'Numbers Rearrange to Make Them Look Better', weight: 1, tier: 'A-', score: 57, color: 'var(--tier-a-minus)' },
  { label: 'Reality Checks for Their Approval', weight: 1, tier: 'A-', score: 57, color: 'var(--tier-a-minus)' },
  { label: 'Every Entity That Meets Them Is Changed', weight: 1, tier: 'A-', score: 57, color: 'var(--tier-a-minus)' },
  { label: 'Their Jokes Alter Local Physics', weight: 1, tier: 'A-', score: 57, color: 'var(--tier-a-minus)' },
  { label: 'Entire Cosmologies Were Written as Fan Fiction', weight: 1, tier: 'A-', score: 57, color: 'var(--tier-a-minus)' },
  { label: 'Causes Joy in Beings That Lack Emotions', weight: 1, tier: 'A-', score: 57, color: 'var(--tier-a-minus)' },
  { label: 'Gravity Pulls Things Toward Their Smile', weight: 1, tier: 'A-', score: 57, color: 'var(--tier-a-minus)' },
  { label: 'Has More Followers Than Atoms in the Sun', weight: 1, tier: 'A-', score: 57, color: 'var(--tier-a-minus)' },
  { label: 'Persuaded the Laws of Thermodynamics Once', weight: 1, tier: 'A-', score: 57, color: 'var(--tier-a-minus)' },
  { label: 'The Social Fabric Weaves Around Them', weight: 1, tier: 'A-', score: 57, color: 'var(--tier-a-minus)' },
  { label: 'Causes Epiphanies in Non-Conscious Matter', weight: 1, tier: 'A-', score: 57, color: 'var(--tier-a-minus)' },
  { label: 'Every Parallel Version of Them Is Also Adored', weight: 1, tier: 'A-', score: 57, color: 'var(--tier-a-minus)' },
  { label: 'Infinite Loyalty From Finite Beings', weight: 1, tier: 'A-', score: 57, color: 'var(--tier-a-minus)' },
  { label: 'Entire Omniverse Is a Fan', weight: 1, tier: 'A-', score: 57, color: 'var(--tier-a-minus)' },
  { label: 'Smiles Have Mass', weight: 1, tier: 'A-', score: 57, color: 'var(--tier-a-minus)' },
  { label: 'Casual Words Become Sacred Texts', weight: 1, tier: 'A-', score: 57, color: 'var(--tier-a-minus)' },
  { label: 'The Concept of "Fan" Was Invented for Them', weight: 1, tier: 'A-', score: 57, color: 'var(--tier-a-minus)' },

  // A (score: 62)
  { label: 'Transcendent Social Force', weight: 1, tier: 'A', score: 62, color: 'var(--tier-a)' },
  { label: 'Deities Update Themselves to Mirror Them', weight: 1, tier: 'A', score: 62, color: 'var(--tier-a)' },
  { label: 'Words Carry the Weight of Universal Law', weight: 1, tier: 'A', score: 62, color: 'var(--tier-a)' },
  { label: 'Causes Multiverse-Wide Moments of Peace', weight: 1, tier: 'A', score: 62, color: 'var(--tier-a)' },
  { label: 'Even Concepts Get Starstruck', weight: 1, tier: 'A', score: 62, color: 'var(--tier-a)' },
  { label: 'The Universe Considers Them a Close Personal Friend', weight: 1, tier: 'A', score: 62, color: 'var(--tier-a)' },
  { label: 'Causes Spontaneous Harmony in Warring Dimensions', weight: 1, tier: 'A', score: 62, color: 'var(--tier-a)' },
  { label: 'Persuaded Entropy to Take a Day Off', weight: 1, tier: 'A', score: 62, color: 'var(--tier-a)' },
  { label: 'All Possible Civilizations Align to Their Culture', weight: 1, tier: 'A', score: 62, color: 'var(--tier-a)' },
  { label: 'Existence Itself Is More Likeable for Knowing Them', weight: 1, tier: 'A', score: 62, color: 'var(--tier-a)' },
  { label: 'Omniverse-Level Reputation', weight: 1, tier: 'A', score: 62, color: 'var(--tier-a)' },
  { label: 'The Multiverse Takes Their Side', weight: 1, tier: 'A', score: 62, color: 'var(--tier-a)' },
  { label: 'Even Mathematical Constants Like Them', weight: 1, tier: 'A', score: 62, color: 'var(--tier-a)' },
  { label: 'Charisma Defies Thermodynamics', weight: 1, tier: 'A', score: 62, color: 'var(--tier-a)' },
  { label: 'Time Asks Permission Before Passing', weight: 1, tier: 'A', score: 62, color: 'var(--tier-a)' },
  { label: 'The Big Bang Was Just Them Arriving', weight: 1, tier: 'A', score: 62, color: 'var(--tier-a)' },
  { label: 'Reality Treats Their Opinion as Fact', weight: 1, tier: 'A', score: 62, color: 'var(--tier-a)' },
  { label: 'Has Been Worshipped Before Time Existed', weight: 1, tier: 'A', score: 62, color: 'var(--tier-a)' },
  { label: 'Void Has a Warm Spot for Them', weight: 1, tier: 'A', score: 62, color: 'var(--tier-a)' },
  { label: 'Every Universe Votes for Them', weight: 1, tier: 'A', score: 62, color: 'var(--tier-a)' },

  // A+ (score: 67)
  { label: 'Starts Religions by Accident', weight: 1, tier: 'A+', score: 67, color: 'var(--tier-a-plus)' },
  { label: 'Converted All Opposition Into Devotees', weight: 1, tier: 'A+', score: 67, color: 'var(--tier-a-plus)' },
  { label: 'Has Organized Fan Clubs in Pre-Time', weight: 1, tier: 'A+', score: 67, color: 'var(--tier-a-plus)' },
  { label: 'Even Nihilism Finds Them Appealing', weight: 1, tier: 'A+', score: 67, color: 'var(--tier-a-plus)' },
  { label: 'All Beings Across All Time Admire Them', weight: 1, tier: 'A+', score: 67, color: 'var(--tier-a-plus)' },
  { label: 'Existence Itself Clamors for Their Attention', weight: 1, tier: 'A+', score: 67, color: 'var(--tier-a-plus)' },
  { label: 'The Fabric of Space Fangirls for Them', weight: 1, tier: 'A+', score: 67, color: 'var(--tier-a-plus)' },
  { label: 'Prime Mover of Social Reality', weight: 1, tier: 'A+', score: 67, color: 'var(--tier-a-plus)' },
  { label: 'Casual Glance Founds New Pantheons', weight: 1, tier: 'A+', score: 67, color: 'var(--tier-a-plus)' },
  { label: 'The Laws of Physics Asked to Be Their Assistant', weight: 1, tier: 'A+', score: 67, color: 'var(--tier-a-plus)' },
  { label: 'Their Name Is Whispered By Stars', weight: 1, tier: 'A+', score: 67, color: 'var(--tier-a-plus)' },
  { label: 'Convinced Nothing to Become Something', weight: 1, tier: 'A+', score: 67, color: 'var(--tier-a-plus)' },
  { label: 'Wrote No Gospel; All Gospels Are About Them', weight: 1, tier: 'A+', score: 67, color: 'var(--tier-a-plus)' },
  { label: 'Omniversal Cultural Foundation', weight: 1, tier: 'A+', score: 67, color: 'var(--tier-a-plus)' },
  { label: 'Causes the Void to Have Opinions', weight: 1, tier: 'A+', score: 67, color: 'var(--tier-a-plus)' },
  { label: 'All Histories Pivot on Their Presence', weight: 1, tier: 'A+', score: 67, color: 'var(--tier-a-plus)' },
  { label: 'Turned Emptiness Into a Devoted Disciple', weight: 1, tier: 'A+', score: 67, color: 'var(--tier-a-plus)' },
  { label: 'Convinced Math That It Agrees With Them', weight: 1, tier: 'A+', score: 67, color: 'var(--tier-a-plus)' },
  { label: 'The Abstract Concepts Gossip About Meeting Them', weight: 1, tier: 'A+', score: 67, color: 'var(--tier-a-plus)' },
  { label: 'Every Universe\'s "Most Beloved Being"', weight: 1, tier: 'A+', score: 67, color: 'var(--tier-a-plus)' },

  // S- (score: 72)
  { label: 'Omniversal Charisma Class', weight: 1, tier: 'S-', score: 72, color: 'var(--tier-s-minus)' },
  { label: 'Social Magnetism With Cosmic Range', weight: 1, tier: 'S-', score: 72, color: 'var(--tier-s-minus)' },
  { label: 'Presence Measurable in Parsecs', weight: 1, tier: 'S-', score: 72, color: 'var(--tier-s-minus)' },
  { label: 'Zero Opponents; All Were Converted', weight: 1, tier: 'S-', score: 72, color: 'var(--tier-s-minus)' },
  { label: 'Deities Commissioned Them, Not Vice Versa', weight: 1, tier: 'S-', score: 72, color: 'var(--tier-s-minus)' },
  { label: 'Social Gravity Replaces Physics in Their Vicinity', weight: 1, tier: 'S-', score: 72, color: 'var(--tier-s-minus)' },
  { label: 'Even Paradoxes Find Them Logical', weight: 1, tier: 'S-', score: 72, color: 'var(--tier-s-minus)' },
  { label: 'Being Near Them Counts as Enlightenment', weight: 1, tier: 'S-', score: 72, color: 'var(--tier-s-minus)' },
  { label: 'Caused the First Sunrise to Happen on Time', weight: 1, tier: 'S-', score: 72, color: 'var(--tier-s-minus)' },
  { label: 'The Concept of "Meeting" Yearns for Them', weight: 1, tier: 'S-', score: 72, color: 'var(--tier-s-minus)' },
  { label: 'Makes Omnipotent Beings Feel Seen', weight: 1, tier: 'S-', score: 72, color: 'var(--tier-s-minus)' },
  { label: 'Has Groupies In All Eleven Dimensions', weight: 1, tier: 'S-', score: 72, color: 'var(--tier-s-minus)' },
  { label: 'Convinced Oblivion to Show Up for Them', weight: 1, tier: 'S-', score: 72, color: 'var(--tier-s-minus)' },
  { label: 'Social Warmth Has Its Own Spectral Signature', weight: 1, tier: 'S-', score: 72, color: 'var(--tier-s-minus)' },
  { label: 'Even Voids Attend Their Events', weight: 1, tier: 'S-', score: 72, color: 'var(--tier-s-minus)' },
  { label: 'Reality Re-Ran Itself Just to Meet Them Earlier', weight: 1, tier: 'S-', score: 72, color: 'var(--tier-s-minus)' },
  { label: 'All Possible Selves Are Popular', weight: 1, tier: 'S-', score: 72, color: 'var(--tier-s-minus)' },
  { label: 'Omniversal Hall of Fame — All Categories', weight: 1, tier: 'S-', score: 72, color: 'var(--tier-s-minus)' },
  { label: 'Has More Titles Than the Cosmos Has Stars', weight: 1, tier: 'S-', score: 72, color: 'var(--tier-s-minus)' },
  { label: 'Defined "Beloved" by Existing', weight: 1, tier: 'S-', score: 72, color: 'var(--tier-s-minus)' },

  // S (score: 77)
  { label: 'Pure Distilled Magnetism', weight: 1, tier: 'S', score: 77, color: 'var(--tier-s)' },
  { label: 'Worshipped by Things That Predate Worship', weight: 1, tier: 'S', score: 77, color: 'var(--tier-s)' },
  { label: 'Causes New Stars to Form From Joy', weight: 1, tier: 'S', score: 77, color: 'var(--tier-s)' },
  { label: 'Existence Considers Them a Co-Creator', weight: 1, tier: 'S', score: 77, color: 'var(--tier-s)' },
  { label: 'Has Fan Mail From Before Time Began', weight: 1, tier: 'S', score: 77, color: 'var(--tier-s)' },
  { label: 'Makes God Feel Like a Fan', weight: 1, tier: 'S', score: 77, color: 'var(--tier-s)' },
  { label: 'Galaxies Rename Themselves in Their Honor', weight: 1, tier: 'S', score: 77, color: 'var(--tier-s)' },
  { label: 'Omniversal Keynote Speaker', weight: 1, tier: 'S', score: 77, color: 'var(--tier-s)' },
  { label: 'Zero-Point Charm Field', weight: 1, tier: 'S', score: 77, color: 'var(--tier-s)' },
  { label: 'The Concept of "Love" Named After Them', weight: 1, tier: 'S', score: 77, color: 'var(--tier-s)' },
  { label: 'Even Absolute Zero Warms Up Nearby', weight: 1, tier: 'S', score: 77, color: 'var(--tier-s)' },
  { label: 'Every Being That Ever Was Considers Them Family', weight: 1, tier: 'S', score: 77, color: 'var(--tier-s)' },
  { label: 'Caused the Big Bang With a Smile', weight: 1, tier: 'S', score: 77, color: 'var(--tier-s)' },
  { label: 'An Audience With Them Changes All Futures', weight: 1, tier: 'S', score: 77, color: 'var(--tier-s)' },
  { label: 'The Void Called Them "Surprisingly Warm"', weight: 1, tier: 'S', score: 77, color: 'var(--tier-s)' },
  { label: 'All Possible Universes Elect Them Leader', weight: 1, tier: 'S', score: 77, color: 'var(--tier-s)' },
  { label: 'Persuaded Pre-Existence to Be Excited', weight: 1, tier: 'S', score: 77, color: 'var(--tier-s)' },
  { label: 'Omniversal Mayor by Unanimous Vote', weight: 1, tier: 'S', score: 77, color: 'var(--tier-s)' },
  { label: 'Entropy Postpones Itself to Spend Time With Them', weight: 1, tier: 'S', score: 77, color: 'var(--tier-s)' },
  { label: 'The Final Boss of Social Dynamics', weight: 1, tier: 'S', score: 77, color: 'var(--tier-s)' },

  // S+ (score: 81)
  { label: 'Omniversal Icon', weight: 1, tier: 'S+', score: 81, color: 'var(--tier-s-plus)' },
  { label: 'The Universe Asks Their Permission to Expand', weight: 1, tier: 'S+', score: 81, color: 'var(--tier-s-plus)' },
  { label: 'Began Worshipped; Never Stopped', weight: 1, tier: 'S+', score: 81, color: 'var(--tier-s-plus)' },
  { label: 'Every Deity Is Just a Rumor About Them', weight: 1, tier: 'S+', score: 81, color: 'var(--tier-s-plus)' },
  { label: 'Charm Field Measurable Across Dimensions', weight: 1, tier: 'S+', score: 81, color: 'var(--tier-s-plus)' },
  { label: 'Love Letters From the Fundamental Forces', weight: 1, tier: 'S+', score: 81, color: 'var(--tier-s-plus)' },
  { label: 'Every Atom in Existence Is a Fan', weight: 1, tier: 'S+', score: 81, color: 'var(--tier-s-plus)' },
  { label: 'Multiverse Unanimously Calls Them a Legend', weight: 1, tier: 'S+', score: 81, color: 'var(--tier-s-plus)' },
  { label: 'Starts Religions by Making Eye Contact', weight: 1, tier: 'S+', score: 81, color: 'var(--tier-s-plus)' },
  { label: 'Defined "Popular" Before Popularity Existed', weight: 1, tier: 'S+', score: 81, color: 'var(--tier-s-plus)' },
  { label: 'Existence Reorganized Around Their Preferences', weight: 1, tier: 'S+', score: 81, color: 'var(--tier-s-plus)' },
  { label: 'Even Formless Void Has Good Things to Say', weight: 1, tier: 'S+', score: 81, color: 'var(--tier-s-plus)' },
  { label: 'Omniversal Peace Brokered With a Handshake', weight: 1, tier: 'S+', score: 81, color: 'var(--tier-s-plus)' },
  { label: 'The Concept of "Admiration" Was Named After Them', weight: 1, tier: 'S+', score: 81, color: 'var(--tier-s-plus)' },
  { label: 'Convinced Absolute Nothingness to Show Up', weight: 1, tier: 'S+', score: 81, color: 'var(--tier-s-plus)' },
  { label: 'All Conscious and Unconscious Beings Approve', weight: 1, tier: 'S+', score: 81, color: 'var(--tier-s-plus)' },
  { label: 'Has Groupies That Are Concepts, Not People', weight: 1, tier: 'S+', score: 81, color: 'var(--tier-s-plus)' },
  { label: 'Omniversal "Person of the Eon" Every Eon', weight: 1, tier: 'S+', score: 81, color: 'var(--tier-s-plus)' },
  { label: 'Even Paradoxes Root for Them', weight: 1, tier: 'S+', score: 81, color: 'var(--tier-s-plus)' },
  { label: 'Is the Reason "Charisma" Is a Word', weight: 1, tier: 'S+', score: 81, color: 'var(--tier-s-plus)' },

  // SS- (score: 85)
  { label: 'Absolute Social Singularity', weight: 1, tier: 'SS-', score: 85, color: 'var(--tier-ss-minus)' },
  { label: 'Love Gravity: Inescapable', weight: 1, tier: 'SS-', score: 85, color: 'var(--tier-ss-minus)' },
  { label: 'Born Worshipped by Everything', weight: 1, tier: 'SS-', score: 85, color: 'var(--tier-ss-minus)' },
  { label: 'Founded All Mythologies Accidentally', weight: 1, tier: 'SS-', score: 85, color: 'var(--tier-ss-minus)' },
  { label: 'Even Silence Applauds Them', weight: 1, tier: 'SS-', score: 85, color: 'var(--tier-ss-minus)' },
  { label: 'Charm Field Visible on Cosmic Maps', weight: 1, tier: 'SS-', score: 85, color: 'var(--tier-ss-minus)' },
  { label: 'All Laws of Nature Defer to Their Opinion', weight: 1, tier: 'SS-', score: 85, color: 'var(--tier-ss-minus)' },
  { label: 'All Possible Realities Want to Impress Them', weight: 1, tier: 'SS-', score: 85, color: 'var(--tier-ss-minus)' },
  { label: 'The Pre-Universe Was a Practice Run for Them', weight: 1, tier: 'SS-', score: 85, color: 'var(--tier-ss-minus)' },
  { label: 'Every Story Ever Told Is About Meeting Them', weight: 1, tier: 'SS-', score: 85, color: 'var(--tier-ss-minus)' },
  { label: 'Omniversal Beloved', weight: 1, tier: 'SS-', score: 85, color: 'var(--tier-ss-minus)' },
  { label: 'Charisma Is Just Them Existing Nearby', weight: 1, tier: 'SS-', score: 85, color: 'var(--tier-ss-minus)' },
  { label: 'Created All Affection by Being Affectionate', weight: 1, tier: 'SS-', score: 85, color: 'var(--tier-ss-minus)' },
  { label: 'The Concept of Fame Is a Pale Imitation of Them', weight: 1, tier: 'SS-', score: 85, color: 'var(--tier-ss-minus)' },
  { label: 'Universal Beloved; No Exceptions', weight: 1, tier: 'SS-', score: 85, color: 'var(--tier-ss-minus)' },
  { label: 'Time Itself Grew Up Admiring Them', weight: 1, tier: 'SS-', score: 85, color: 'var(--tier-ss-minus)' },
  { label: 'The Fundamental Forces Are Fan Art', weight: 1, tier: 'SS-', score: 85, color: 'var(--tier-ss-minus)' },
  { label: 'Every Universe Was Created to Appreciate Them', weight: 1, tier: 'SS-', score: 85, color: 'var(--tier-ss-minus)' },
  { label: 'Deity Tier — But Better at Parties', weight: 1, tier: 'SS-', score: 85, color: 'var(--tier-ss-minus)' },
  { label: 'Even the Heat Death of the Universe Hesitates', weight: 1, tier: 'SS-', score: 85, color: 'var(--tier-ss-minus)' },

  // SS (score: 88)
  { label: 'Transcendent Social God', weight: 1, tier: 'SS', score: 88, color: 'var(--tier-ss)' },
  { label: 'Every Atom Is a Devoted Fan', weight: 1, tier: 'SS', score: 88, color: 'var(--tier-ss)' },
  { label: 'All Realities Compete to Host Them', weight: 1, tier: 'SS', score: 88, color: 'var(--tier-ss)' },
  { label: 'Omnipresent Social Warmth', weight: 1, tier: 'SS', score: 88, color: 'var(--tier-ss)' },
  { label: 'The Big Bang Was an Applause Line', weight: 1, tier: 'SS', score: 88, color: 'var(--tier-ss)' },
  { label: 'Became the Definition of "Beloved"', weight: 1, tier: 'SS', score: 88, color: 'var(--tier-ss)' },
  { label: 'Causes Spontaneous Enlightenment in Observers', weight: 1, tier: 'SS', score: 88, color: 'var(--tier-ss)' },
  { label: 'Existence Has a Crush on Them', weight: 1, tier: 'SS', score: 88, color: 'var(--tier-ss)' },
  { label: 'The Void Decorates for Them', weight: 1, tier: 'SS', score: 88, color: 'var(--tier-ss)' },
  { label: 'Every Narrative Ever Written Has Them as Protagonist', weight: 1, tier: 'SS', score: 88, color: 'var(--tier-ss)' },
  { label: 'Social Pull Exceeds Gravitational Constants', weight: 1, tier: 'SS', score: 88, color: 'var(--tier-ss)' },
  { label: 'Omniversal Consensus: Them', weight: 1, tier: 'SS', score: 88, color: 'var(--tier-ss)' },
  { label: 'Invented the Word "Admire" By Being Admirable', weight: 1, tier: 'SS', score: 88, color: 'var(--tier-ss)' },
  { label: 'All of Time Lined Up Just to Say Hello', weight: 1, tier: 'SS', score: 88, color: 'var(--tier-ss)' },
  { label: 'Even Pre-Existence Is a Fan', weight: 1, tier: 'SS', score: 88, color: 'var(--tier-ss)' },
  { label: 'Forged Devotion From the Raw Fabric of Reality', weight: 1, tier: 'SS', score: 88, color: 'var(--tier-ss)' },
  { label: 'The Heat Death Paused to Wave Goodbye', weight: 1, tier: 'SS', score: 88, color: 'var(--tier-ss)' },
  { label: 'Words Anchor New Universes', weight: 1, tier: 'SS', score: 88, color: 'var(--tier-ss)' },
  { label: 'The Source of All Social Energy', weight: 1, tier: 'SS', score: 88, color: 'var(--tier-ss)' },
  { label: 'Deities Were Inspired by Them, Not the Other Way', weight: 1, tier: 'SS', score: 88, color: 'var(--tier-ss)' },

  // SS+ (score: 91)
  { label: 'Absolute Charisma — Final Form', weight: 1, tier: 'SS+', score: 91, color: 'var(--tier-ss-plus)' },
  { label: 'Even "Legendary" Feels Understated', weight: 1, tier: 'SS+', score: 91, color: 'var(--tier-ss-plus)' },
  { label: 'Every Conceivable Being Is a Lifelong Fan', weight: 1, tier: 'SS+', score: 91, color: 'var(--tier-ss-plus)' },
  { label: 'Omniversal Prime Minister by Unanimous Acclaim', weight: 1, tier: 'SS+', score: 91, color: 'var(--tier-ss-plus)' },
  { label: 'The Concept of Opinion Was Made to Support Them', weight: 1, tier: 'SS+', score: 91, color: 'var(--tier-ss-plus)' },
  { label: 'Every Story Ever Was a Prequel to Meeting Them', weight: 1, tier: 'SS+', score: 91, color: 'var(--tier-ss-plus)' },
  { label: 'Social Mass Exceeds Dark Matter', weight: 1, tier: 'SS+', score: 91, color: 'var(--tier-ss-plus)' },
  { label: 'The Abstract Is Loyal to Them', weight: 1, tier: 'SS+', score: 91, color: 'var(--tier-ss-plus)' },
  { label: 'No Enemies — They Were All Converted', weight: 1, tier: 'SS+', score: 91, color: 'var(--tier-ss-plus)' },
  { label: 'Wrote No Doctrine; All Doctrines Reference Them', weight: 1, tier: 'SS+', score: 91, color: 'var(--tier-ss-plus)' },
  { label: 'The Multiverse Sets Its Clocks by Their Mood', weight: 1, tier: 'SS+', score: 91, color: 'var(--tier-ss-plus)' },
  { label: 'Even "God" Is Just a Fan Account for Them', weight: 1, tier: 'SS+', score: 91, color: 'var(--tier-ss-plus)' },
  { label: 'All Possible Worlds Voted: It\'s Them', weight: 1, tier: 'SS+', score: 91, color: 'var(--tier-ss-plus)' },
  { label: 'Omniversal Source of Joy', weight: 1, tier: 'SS+', score: 91, color: 'var(--tier-ss-plus)' },
  { label: 'All Futures Were Written to Eventually Meet Them', weight: 1, tier: 'SS+', score: 91, color: 'var(--tier-ss-plus)' },
  { label: 'The Very Fabric of Meaning Admires Them', weight: 1, tier: 'SS+', score: 91, color: 'var(--tier-ss-plus)' },
  { label: 'Every Universe Considers Them Native', weight: 1, tier: 'SS+', score: 91, color: 'var(--tier-ss-plus)' },
  { label: 'Existence Itself Has a Devoted Fanbase for Them', weight: 1, tier: 'SS+', score: 91, color: 'var(--tier-ss-plus)' },
  { label: 'The Heat Death Wrote a Tribute Album', weight: 1, tier: 'SS+', score: 91, color: 'var(--tier-ss-plus)' },
  { label: 'Invented Charisma, Then Perfected It', weight: 1, tier: 'SS+', score: 91, color: 'var(--tier-ss-plus)' },

  // SSS- (score: 94)
  { label: 'Beyond God-Tier Social Energy', weight: 1, tier: 'SSS-', score: 94, color: 'var(--tier-sss-minus)' },
  { label: 'Every Parallel Self Is Also a Legend', weight: 1, tier: 'SSS-', score: 94, color: 'var(--tier-sss-minus)' },
  { label: 'Pre-Existence Already Had a Crush', weight: 1, tier: 'SSS-', score: 94, color: 'var(--tier-sss-minus)' },
  { label: 'Omniversal Best Friend to All That Exists', weight: 1, tier: 'SSS-', score: 94, color: 'var(--tier-sss-minus)' },
  { label: 'Charisma Is a Measurement Named in Their Honor', weight: 1, tier: 'SSS-', score: 94, color: 'var(--tier-sss-minus)' },
  { label: 'Makes Even the Void Feel Included', weight: 1, tier: 'SSS-', score: 94, color: 'var(--tier-sss-minus)' },
  { label: 'Inspired All Stories Before Being Born', weight: 1, tier: 'SSS-', score: 94, color: 'var(--tier-sss-minus)' },
  { label: 'Unalloyed Social Light', weight: 1, tier: 'SSS-', score: 94, color: 'var(--tier-sss-minus)' },
  { label: 'All Creation Is a Standing Ovation', weight: 1, tier: 'SSS-', score: 94, color: 'var(--tier-sss-minus)' },
  { label: 'Pre-Reality Knew Their Name', weight: 1, tier: 'SSS-', score: 94, color: 'var(--tier-sss-minus)' },
  { label: 'Invented Admiration by Being Admirable', weight: 1, tier: 'SSS-', score: 94, color: 'var(--tier-sss-minus)' },
  { label: 'All Future Beings Pre-Approved of Them', weight: 1, tier: 'SSS-', score: 94, color: 'var(--tier-sss-minus)' },
  { label: 'The Universe Never Had a Chance', weight: 1, tier: 'SSS-', score: 94, color: 'var(--tier-sss-minus)' },
  { label: 'Persuaded Non-Existence to Exist for Them', weight: 1, tier: 'SSS-', score: 94, color: 'var(--tier-sss-minus)' },
  { label: 'Omniversal Everything Agrees: Yes', weight: 1, tier: 'SSS-', score: 94, color: 'var(--tier-sss-minus)' },
  { label: 'Legendary in Timelines That Never Happened', weight: 1, tier: 'SSS-', score: 94, color: 'var(--tier-sss-minus)' },
  { label: 'History Considers Meeting Them Its Best Moment', weight: 1, tier: 'SSS-', score: 94, color: 'var(--tier-sss-minus)' },
  { label: 'Their Absence Created More Followers Than Their Presence', weight: 1, tier: 'SSS-', score: 94, color: 'var(--tier-sss-minus)' },
  { label: 'The Infinite Admires Them Infinitely', weight: 1, tier: 'SSS-', score: 94, color: 'var(--tier-sss-minus)' },
  { label: 'Omniversal Ambassador for Warmth', weight: 1, tier: 'SSS-', score: 94, color: 'var(--tier-sss-minus)' },

  // SSS (score: 97)
  { label: 'Omniversal Social Singularity', weight: 1, tier: 'SSS', score: 97, color: 'var(--tier-sss)' },
  { label: 'All Beings, All Times, All Realities: Loyal', weight: 1, tier: 'SSS', score: 97, color: 'var(--tier-sss)' },
  { label: 'The Word "Charisma" Is About Them', weight: 1, tier: 'SSS', score: 97, color: 'var(--tier-sss)' },
  { label: 'No Force Can Resist Their Social Pull', weight: 1, tier: 'SSS', score: 97, color: 'var(--tier-sss)' },
  { label: 'Reality Itself Is Just a Stage for Them', weight: 1, tier: 'SSS', score: 97, color: 'var(--tier-sss)' },
  { label: 'Pre-Existence Already Had a Fan Club Ready', weight: 1, tier: 'SSS', score: 97, color: 'var(--tier-sss)' },
  { label: 'Wrote All Cultural History by Showing Up', weight: 1, tier: 'SSS', score: 97, color: 'var(--tier-sss)' },
  { label: 'All Gods Are Secondary Characters to Them', weight: 1, tier: 'SSS', score: 97, color: 'var(--tier-sss)' },
  { label: 'Even Time Has a Warm Memory of Them', weight: 1, tier: 'SSS', score: 97, color: 'var(--tier-sss)' },
  { label: 'Persuaded Nothingness to Bring Snacks', weight: 1, tier: 'SSS', score: 97, color: 'var(--tier-sss)' },
  { label: 'All Possible Versions: Universally Beloved', weight: 1, tier: 'SSS', score: 97, color: 'var(--tier-sss)' },
  { label: 'Their Presence Made Reality Worth Having', weight: 1, tier: 'SSS', score: 97, color: 'var(--tier-sss)' },
  { label: 'Founded the Concept of "Joy" Accidentally', weight: 1, tier: 'SSS', score: 97, color: 'var(--tier-sss)' },
  { label: 'Created Devotion by Being Devotable', weight: 1, tier: 'SSS', score: 97, color: 'var(--tier-sss)' },
  { label: 'The Universe Claps When They Wake Up', weight: 1, tier: 'SSS', score: 97, color: 'var(--tier-sss)' },
  { label: 'The Void Went Out and Made Friends for Them', weight: 1, tier: 'SSS', score: 97, color: 'var(--tier-sss)' },
  { label: 'Defined Existence by Existing Within It', weight: 1, tier: 'SSS', score: 97, color: 'var(--tier-sss)' },
  { label: 'The Infinite Bows Wherever They Look', weight: 1, tier: 'SSS', score: 97, color: 'var(--tier-sss)' },
  { label: 'The Concept of Loyalty Was Coined for Them', weight: 1, tier: 'SSS', score: 97, color: 'var(--tier-sss)' },
  { label: 'Omniversal Prime Force of Connection', weight: 1, tier: 'SSS', score: 97, color: 'var(--tier-sss)' },

  // SSS+ (score: 99)
  { label: 'Perfect Social Force', weight: 1, tier: 'SSS+', score: 99, color: 'var(--tier-sss-plus)' },
  { label: 'Defined Charisma Before There Was Language', weight: 1, tier: 'SSS+', score: 99, color: 'var(--tier-sss-plus)' },
  { label: 'Every Possible Devotion Points Back to Them', weight: 1, tier: 'SSS+', score: 99, color: 'var(--tier-sss-plus)' },
  { label: 'The Word "Beloved" Is Just Their Name in Old Tongue', weight: 1, tier: 'SSS+', score: 99, color: 'var(--tier-sss-plus)' },
  { label: 'The Universe Exists Partially to Appreciate Them', weight: 1, tier: 'SSS+', score: 99, color: 'var(--tier-sss-plus)' },
  { label: 'No Reality Exists Where They Are Not Loved', weight: 1, tier: 'SSS+', score: 99, color: 'var(--tier-sss-plus)' },
  { label: 'Omniversal Beloved — No Exceptions, All of Time', weight: 1, tier: 'SSS+', score: 99, color: 'var(--tier-sss-plus)' },
  { label: 'Even the Concept of Loneliness Gave Up Near Them', weight: 1, tier: 'SSS+', score: 99, color: 'var(--tier-sss-plus)' },
  { label: 'Founded the Social Fabric With Their First Breath', weight: 1, tier: 'SSS+', score: 99, color: 'var(--tier-sss-plus)' },
  { label: 'Made All Things Feel Less Alone', weight: 1, tier: 'SSS+', score: 99, color: 'var(--tier-sss-plus)' },
  { label: 'All of History Is a Love Letter to Them', weight: 1, tier: 'SSS+', score: 99, color: 'var(--tier-sss-plus)' },
  { label: 'Complete Social Completion — No Room for More', weight: 1, tier: 'SSS+', score: 99, color: 'var(--tier-sss-plus)' },
  { label: 'Summoned Devotion From the Pre-Cosmic Silence', weight: 1, tier: 'SSS+', score: 99, color: 'var(--tier-sss-plus)' },
  { label: 'Turned Infinite Emptiness Into Community', weight: 1, tier: 'SSS+', score: 99, color: 'var(--tier-sss-plus)' },
  { label: 'The Final Form of Social Energy', weight: 1, tier: 'SSS+', score: 99, color: 'var(--tier-sss-plus)' },
  { label: 'The Universe\'s Favorite Being, Officially', weight: 1, tier: 'SSS+', score: 99, color: 'var(--tier-sss-plus)' },
  { label: 'Transcends the Concept of Being Liked', weight: 1, tier: 'SSS+', score: 99, color: 'var(--tier-sss-plus)' },
  { label: 'All Faiths Are Just Their Fan Clubs', weight: 1, tier: 'SSS+', score: 99, color: 'var(--tier-sss-plus)' },
  { label: 'The Primordial Beloved', weight: 1, tier: 'SSS+', score: 99, color: 'var(--tier-sss-plus)' },
  { label: 'Made the Concept of Connection Possible', weight: 1, tier: 'SSS+', score: 99, color: 'var(--tier-sss-plus)' },

  // God (score: 100)
  { label: 'Starts Religions by Making Eye Contact', weight: 1, tier: 'God', score: 100, color: 'var(--tier-god)' },
  { label: 'The Very Word "Charisma" Bows to Them', weight: 1, tier: 'God', score: 100, color: 'var(--tier-god)' },
  { label: 'Every Being That Will Ever Exist Already Loves Them', weight: 1, tier: 'God', score: 100, color: 'var(--tier-god)' },
  { label: 'Omniversal Social Absolute', weight: 1, tier: 'God', score: 100, color: 'var(--tier-god)' },
  { label: 'The Concept of "Other" Was Created Just to Miss Them', weight: 1, tier: 'God', score: 100, color: 'var(--tier-god)' },
  { label: 'All Existence Is Their Social Circle', weight: 1, tier: 'God', score: 100, color: 'var(--tier-god)' },
  { label: 'The Universe Has No Word for "Indifferent" Regarding Them', weight: 1, tier: 'God', score: 100, color: 'var(--tier-god)' },
  { label: 'Founded the Feeling of Being Loved', weight: 1, tier: 'God', score: 100, color: 'var(--tier-god)' },
  { label: 'Every Atom in Every Universe: Devoted', weight: 1, tier: 'God', score: 100, color: 'var(--tier-god)' },
  { label: 'The Void Was Inspired by Wanting to Hold a Party for Them', weight: 1, tier: 'God', score: 100, color: 'var(--tier-god)' },
  { label: 'Defined "Together" Before the Universe Split Into Parts', weight: 1, tier: 'God', score: 100, color: 'var(--tier-god)' },
  { label: 'The Social Force That Holds Reality Together', weight: 1, tier: 'God', score: 100, color: 'var(--tier-god)' },
  { label: 'Caused the Big Bang by Walking In', weight: 1, tier: 'God', score: 100, color: 'var(--tier-god)' },
  { label: 'Created Love, Joy, and Admiration in That Order', weight: 1, tier: 'God', score: 100, color: 'var(--tier-god)' },
  { label: 'Everything That Is, Was, and Will Be: A Fan', weight: 1, tier: 'God', score: 100, color: 'var(--tier-god)' },
  { label: 'The Fundamental Force Nobody Talks About', weight: 1, tier: 'God', score: 100, color: 'var(--tier-god)' },
  { label: 'All Creation Is Just the Universe Trying to Impress Them', weight: 1, tier: 'God', score: 100, color: 'var(--tier-god)' },
  { label: 'Omniversal Singularity of Warmth', weight: 1, tier: 'God', score: 100, color: 'var(--tier-god)' },
  { label: 'Makes Nothingness Wish It Was Something', weight: 1, tier: 'God', score: 100, color: 'var(--tier-god)' },
  { label: 'The Final Answer to Why Anything Exists at All', weight: 1, tier: 'God', score: 100, color: 'var(--tier-god)' },
]
