// devil-fruits.ts — Devil fruit name pools keyed by the exact classPool label of the
// Devil Fruit User race. Spliced as a 'devilFruitName' spin after 'raceClass' resolves.
// No default export. Single named export.

export const DEVIL_FRUIT_POOLS: Record<string, { label: string; weight: number }[]> = {
  'Paramecia (Body / Environment)': [
    { label: 'Gomu Gomu no Mi — Rubber Body',            weight: 4 },
    { label: 'Ito Ito no Mi — Thousand Strings',         weight: 3 },
    { label: 'Hana Hana no Mi — Thousand Limbs',         weight: 3 },
    { label: 'Mero Mero no Mi — Love Beam',              weight: 3 },
    { label: 'Bari Bari no Mi — Barrier Wall',           weight: 3 },
    { label: 'Sube Sube no Mi — Frictionless Skin',      weight: 3 },
    { label: 'Mane Mane no Mi — Face Clone',             weight: 2 },
    { label: 'Supa Supa no Mi — Blade Body',             weight: 2 },
    { label: 'Toge Toge no Mi — Spike Body',             weight: 2 },
    { label: 'Ori Ori no Mi — Binding Cage',             weight: 2 },
    { label: 'Noro Noro no Mi — Slow Beam',              weight: 2 },
    { label: 'Doa Doa no Mi — Door Anywhere',            weight: 2 },
    { label: 'Baku Baku no Mi — Eat Anything',           weight: 2 },
    { label: 'Doru Doru no Mi — Wax Construct',          weight: 2 },
    { label: 'Ope Ope no Mi — Op-Op Surgeon',            weight: 1 },
    { label: 'Gura Gura no Mi — Earthquake Fist',        weight: 1 },
    { label: 'Hobi Hobi no Mi — Toy Curse',              weight: 1 },
    { label: 'Memo Memo no Mi — Memory Edit',            weight: 2 },
    { label: 'Netsu Netsu no Mi — Heat Aura',            weight: 2 },
    { label: 'Shibo Shibo no Mi — Drain Touch',          weight: 2 },
    { label: 'Kobu Kobu no Mi — Cheer Amp',              weight: 2 },
    { label: 'Nuki Nuki no Mi — Pass-Through Body',      weight: 2 },
  ],

  'Zoan (Animal Transformation)': [
    { label: 'Inu Inu no Mi: Model Wolf',                weight: 4 },
    { label: 'Neko Neko no Mi: Model Leopard',           weight: 4 },
    { label: 'Tori Tori no Mi: Model Falcon',            weight: 4 },
    { label: 'Uma Uma no Mi: Model Horse',               weight: 3 },
    { label: 'Kame Kame no Mi: Model Tortoise',          weight: 3 },
    { label: 'Hebi Hebi no Mi: Model King Cobra',        weight: 3 },
    { label: 'Kumo Kumo no Mi: Model Tarantula',         weight: 3 },
    { label: 'Mushi Mushi no Mi: Model Rhinoceros Beetle', weight: 2 },
    { label: 'Mogu Mogu no Mi: Model Mole',              weight: 2 },
    { label: 'Zou Zou no Mi: Model Elephant',            weight: 2 },
    { label: 'Ushi Ushi no Mi: Model Giraffe',           weight: 2 },
    { label: 'Batta Batta no Mi: Model Grasshopper',     weight: 2 },
    { label: 'Sara Sara no Mi: Model Axolotl',           weight: 2 },
    { label: 'Tori Tori no Mi: Model Albatross',         weight: 2 },
    { label: 'Batto Batto no Mi: Model Vampire',         weight: 1 },
  ],

  'Ancient Zoan': [
    { label: 'Ryu Ryu no Mi: Model Pteranodon',          weight: 4 },
    { label: 'Ryu Ryu no Mi: Model Brachiosaurus',       weight: 4 },
    { label: 'Ryu Ryu no Mi: Model Allosaurus',          weight: 3 },
    { label: 'Ryu Ryu no Mi: Model Spinosaurus',         weight: 3 },
    { label: 'Ryu Ryu no Mi: Model Pachycephalosaurus',  weight: 3 },
    { label: 'Ryu Ryu no Mi: Model Triceratops',         weight: 3 },
    { label: 'Zou Zou no Mi: Model Mammoth',             weight: 2 },
    { label: 'Neko Neko no Mi: Model Saber-Tooth Tiger', weight: 2 },
    { label: 'Kumo Kumo no Mi: Model Rosamygale',        weight: 1 },
  ],

  'Mythical Zoan': [
    { label: 'Tori Tori no Mi: Model Phoenix',           weight: 4 },
    { label: 'Uo Uo no Mi: Model Seiryu (Azure Dragon)', weight: 3 },
    { label: 'Inu Inu no Mi: Model Kyubi no Kitsune',    weight: 3 },
    { label: 'Uma Uma no Mi: Model Pegasus',             weight: 3 },
    { label: 'Hito Hito no Mi: Model Daibutsu',          weight: 2 },
    { label: 'Hebi Hebi no Mi: Model Yamata no Orochi',  weight: 2 },
    { label: 'Inu Inu no Mi: Model Cerberus',            weight: 2 },
    { label: 'Hito Hito no Mi: Model Nika',              weight: 1 },
  ],

  'Logia (Element Control)': [
    { label: 'Mera Mera no Mi — Fire',                   weight: 4 },
    { label: 'Hie Hie no Mi — Ice',                      weight: 4 },
    { label: 'Goro Goro no Mi — Lightning',              weight: 3 },
    { label: 'Suna Suna no Mi — Sand',                   weight: 3 },
    { label: 'Moku Moku no Mi — Smoke',                  weight: 3 },
    { label: 'Yuki Yuki no Mi — Snow',                   weight: 3 },
    { label: 'Gasu Gasu no Mi — Poison Gas',             weight: 2 },
    { label: 'Numa Numa no Mi — Swamp',                  weight: 2 },
    { label: 'Magu Magu no Mi — Magma',                  weight: 2 },
    { label: 'Pika Pika no Mi — Light',                  weight: 2 },
    { label: 'Yami Yami no Mi — Darkness',               weight: 1 },
    { label: 'Ame Ame no Mi — Rain',                     weight: 2 },
    { label: 'Kaze Kaze no Mi — Wind',                   weight: 2 },
    { label: 'Tsuchi Tsuchi no Mi — Earth',              weight: 2 },
  ],

  'Awakened Devil Fruit': [
    { label: 'Gomu Gomu no Mi: Gear 5 Awakening',                 weight: 3 },
    { label: 'Ito Ito no Mi: Awakened Thread Dominion',            weight: 2 },
    { label: 'Gura Gura no Mi: Seismic World-Break',               weight: 2 },
    { label: 'Hie Hie no Mi: Absolute Zero Awakening',             weight: 2 },
    { label: 'Ope Ope no Mi: Awakened Immortality Surgery',        weight: 1 },
    { label: 'Yami Yami no Mi: Void Awakening',                    weight: 1 },
    { label: 'Mera Mera no Mi: Awakened Conflagration',            weight: 2 },
    { label: 'Unknown Ancient Fruit — Awakened Form',              weight: 3 },
  ],
}
