import type { FlavorLabel } from './types'

export const durabilityLabels: FlavorLabel[] = [
  { label: 'Tissue Paper Constitution',           weight: 1, tier: 'F-',   score: 2,   color: '#555'    },
  { label: 'Bruises Thinking Too Hard',           weight: 1, tier: 'F',    score: 5,   color: '#666'    },
  { label: 'Gets Winded on Stairs',               weight: 1, tier: 'F+',   score: 8,   color: '#777'    },
  { label: 'Normal Human Resilience',             weight: 1, tier: 'E-',   score: 11,  color: '#6b7280' },
  { label: 'Takes a Hit, Complains About It',     weight: 1, tier: 'E',    score: 14,  color: '#9ca3af' },
  { label: 'Takes Hits Without Flinching',        weight: 1, tier: 'E+',   score: 17,  color: '#d1d5db' },
  { label: 'Shrugs Off Minor Injuries',           weight: 1, tier: 'D-',   score: 20,  color: '#92400e' },
  { label: 'Tough to Slow Down',                  weight: 1, tier: 'D',    score: 23,  color: '#b45309' },
  { label: 'Breaks Weapons on Their Skin',        weight: 1, tier: 'D+',   score: 26,  color: '#d97706' },
  { label: 'Bulletproof Moments',                 weight: 1, tier: 'C-',   score: 30,  color: '#1d4ed8' },
  { label: 'Small Arms Do Not Register',          weight: 1, tier: 'C',    score: 34,  color: '#2563eb' },
  { label: 'Survives Explosions',                 weight: 1, tier: 'C+',   score: 38,  color: '#3b82f6' },
  { label: 'Walking Tank',                        weight: 1, tier: 'B-',   score: 42,  color: '#065f46' },
  { label: 'Walks Out of Warzones',               weight: 1, tier: 'B',    score: 47,  color: '#059669' },
  { label: 'Shrugs Off Artillery',                weight: 1, tier: 'B+',   score: 52,  color: '#34d399' },
  { label: 'Nuclear-Resistant',                   weight: 1, tier: 'A-',   score: 57,  color: '#7c3aed' },
  { label: 'Continental Blast Immune',            weight: 1, tier: 'A',    score: 62,  color: '#8b5cf6' },
  { label: 'Planet-Core Survivor',                weight: 1, tier: 'A+',   score: 67,  color: '#a78bfa' },
  { label: 'Stellar Flares Tickle',               weight: 1, tier: 'S-',   score: 72,  color: '#b91c1c' },
  { label: 'Supernova Adjacent',                  weight: 1, tier: 'S',    score: 77,  color: '#dc2626' },
  { label: 'Universe Won\'t Kill Them',           weight: 1, tier: 'S+',   score: 81,  color: '#ef4444' },
  { label: 'Endures Reality Fractures',           weight: 1, tier: 'SS-',  score: 85,  color: '#ea580c' },
  { label: 'Death Itself Gives Up',               weight: 1, tier: 'SS',   score: 88,  color: '#f97316' },
  { label: 'Exists Through Annihilation',         weight: 1, tier: 'SS+',  score: 91,  color: '#fb923c' },
  { label: 'The Damage Happened to the Attack',   weight: 1, tier: 'SSS-', score: 94,  color: '#ca8a04' },
  { label: 'Concept of Harm Does Not Apply',      weight: 1, tier: 'SSS',  score: 97,  color: '#eab308' },
  { label: 'Invincible in Every Sense',           weight: 1, tier: 'SSS+', score: 99,  color: '#fde047' },
  { label: 'The Universe Tried, It Did Not',      weight: 1, tier: 'God',  score: 100, color: '#e879f9' },
]
