import type { FlavorLabel } from './types'

// Durability scale: F- = tissue paper, B = elite veteran (still mortal — small-arms,
// not tank shells), A range = bulletproof/explosion-resistant, S = tank-grade,
// SS-SSS = world-ending durability, Cosmic+ = post-mortal endurance,
// Infinite+ = cannot be unmade by any concept.
export const durabilityLabels: FlavorLabel[] = [
  { label: 'Tissue-Paper Constitution',                      weight: 4, tier: 'F-',            score: 2,   color: '#2c2c2c' },
  { label: 'Bruises From Sitting Down Too Hard',             weight: 4, tier: 'F',             score: 5,   color: '#404040' },
  { label: 'Fragile but Functional',                         weight: 4, tier: 'F+',            score: 8,   color: '#525252' },
  { label: 'Below-Average Resilience',                       weight: 6, tier: 'E-',            score: 11,  color: '#4b5563' },
  { label: 'Average Pain Tolerance',                         weight: 6, tier: 'E',             score: 14,  color: '#64748b' },
  { label: 'Takes a Hit, Walks It Off',                      weight: 6, tier: 'E+',            score: 17,  color: '#94a3b8' },
  { label: 'Tough for Their Build',                          weight: 8, tier: 'D-',            score: 20,  color: '#14532d' },
  { label: 'Pro Athlete Durability',                         weight: 8, tier: 'D',             score: 23,  color: '#166534' },
  { label: 'Survives a Bad Crash',                           weight: 8, tier: 'D+',            score: 26,  color: '#22c55e' },
  { label: 'Hardened Combatant',                             weight: 8, tier: 'C-',            score: 30,  color: '#047857' },
  { label: 'Shrugs Off Stab Wounds',                         weight: 9, tier: 'C',             score: 34,  color: '#059669' },
  { label: 'Walks Off Bad Falls',                            weight: 8, tier: 'C+',            score: 38,  color: '#10b981' },
  { label: 'Veteran Soldier Toughness',                      weight: 7, tier: 'B-',            score: 42,  color: '#115e59' },
  { label: 'Special-Ops Conditioning',                       weight: 7, tier: 'B',             score: 47,  color: '#0d9488' },
  { label: 'Peak Human Durability',                          weight: 7, tier: 'B+',            score: 52,  color: '#14b8a6' },
  { label: 'Bulletproof Moments',                            weight: 5, tier: 'A-',            score: 57,  color: '#155e75' },
  { label: 'Small Arms Do Not Register',                     weight: 5, tier: 'A',             score: 62,  color: '#0e7490' },
  { label: 'Walks Out of Explosions',                        weight: 5, tier: 'A+',            score: 67,  color: '#06b6d4' },
  { label: 'Tank Shells Are an Inconvenience',               weight: 4, tier: 'S-',            score: 72,  color: '#0c4a6e' },
  { label: 'Walking Tank',                                   weight: 4, tier: 'S',             score: 77,  color: '#0369a1' },
  { label: 'Shrugs Off Artillery Strikes',                   weight: 4, tier: 'S+',            score: 81,  color: '#0ea5e9' },
  { label: 'Nuclear-Adjacent Resistance',                    weight: 3, tier: 'SS-',           score: 85,  color: '#1e3a8a' },
  { label: 'Continental Blast Immune',                       weight: 3, tier: 'SS',            score: 88,  color: '#2563eb' },
  { label: 'Planet-Core Survivor',                           weight: 3, tier: 'SS+',           score: 91,  color: '#3b82f6' },
  { label: 'Supernova Adjacent',                             weight: 1, tier: 'SSS-',          score: 94,  color: '#4338ca' },
  { label: 'Universe Will Not Kill Them',                    weight: 1, tier: 'SSS',           score: 97,  color: '#4f46e5' },
  { label: 'Endures Reality Fractures',                      weight: 1, tier: 'SSS+',          score: 99,  color: '#6366f1' },
  { label: 'Survives Galactic Annihilation Events',          weight: 1, tier: 'Z-',            score: 101, color: '#5b21b6' },
  { label: 'Withstands Universal Collapse Casually',         weight: 1, tier: 'Z',             score: 103, color: '#7c3aed' },
  { label: 'Absorbs the Heat Death of a Universe',           weight: 1, tier: 'Z+',            score: 105, color: '#8b5cf6' },
  { label: 'Endures Across Collapsing Realities',            weight: 0.7, tier: 'ZZ-',           score: 107, color: '#86198f' },
  { label: 'Persists Through Multiversal Extinction',        weight: 0.7, tier: 'ZZ',            score: 109, color: '#a21caf' },
  { label: 'Outlasts the Concept of Destruction',            weight: 0.7, tier: 'ZZ+',           score: 111, color: '#c026d3' },
  { label: 'Immune to Annihilation as a Category',           weight: 0.5, tier: 'ZZZ-',          score: 113, color: '#be185d' },
  { label: 'Cannot Be Destroyed — Verified',                 weight: 0.5, tier: 'ZZZ',           score: 115, color: '#db2777' },
  { label: 'Destruction Refuses to Process the Request',     weight: 0.5, tier: 'ZZZ+',          score: 117, color: '#ec4899' },
  { label: 'Cosmic-Scale Endurance',                         weight: 0.35, tier: 'Cosmic-',       score: 119, color: '#0e6b8a' },
  { label: 'Survives the Birth of New Cosmoses',             weight: 0.35, tier: 'Cosmic',        score: 121, color: '#0891b2' },
  { label: 'Cosmic Forces Recoil From Them',                 weight: 0.35, tier: 'Cosmic+',       score: 123, color: '#06b6d4' },
  { label: 'Death Itself Gave Up Trying',                    weight: 0.25, tier: 'Immortal-',     score: 125, color: '#d946ef' },
  { label: 'Cannot Be Killed by Any Known Means',            weight: 0.25, tier: 'Immortal',      score: 127, color: '#ec4899' },
  { label: 'Has Outlived Every Method of Killing',           weight: 0.25, tier: 'Immortal+',     score: 129, color: '#f472b6' },
  { label: 'Endures Directly in the Divine Realm',           weight: 0.2, tier: 'Celestial-',    score: 131, color: '#831843' },
  { label: 'Celestial Forces Cannot Touch Them',             weight: 0.2, tier: 'Celestial',     score: 133, color: '#9d174d' },
  { label: 'Beyond the Reach of Any Ruin',                   weight: 0.2, tier: 'Celestial+',    score: 135, color: '#be185d' },
  { label: 'Nothing in Any Plane Can Kill Them',             weight: 0.15, tier: 'Godly-',        score: 137, color: '#f9a8d4' },
  { label: 'The Universe Tried — It Did Not',                weight: 0.15, tier: 'Godly',         score: 139, color: '#f472b6' },
  { label: 'Outlasts Gods Themselves',                       weight: 0.15, tier: 'Godly+',        score: 141, color: '#ec4899' },
  { label: 'Pre-Dates the Concept of Harm',                  weight: 0.1, tier: 'Primordial-',   score: 143, color: '#d4d4d8' },
  { label: 'Authored the First Body That Could Not Break',   weight: 0.1, tier: 'Primordial',    score: 145, color: '#e4e4e7' },
  { label: 'Destruction Has No Jurisdiction Here',           weight: 0.1, tier: 'Primordial+',   score: 147, color: '#fafafa' },
  { label: 'Every Plane Agreed: Not Today',                  weight: 0.07, tier: 'Absolute-',     score: 149, color: '#7dd3fc' },
  { label: 'The Void Filed for Exemption and Was Denied',    weight: 0.07, tier: 'Absolute',      score: 151, color: '#38bdf8' },
  { label: 'Absolutely Indestructible',                      weight: 0.07, tier: 'Absolute+',     score: 153, color: '#0ea5e9' },
  { label: 'Beyond Destruction as a Concept',                weight: 0.05, tier: 'Transcendent-', score: 155, color: '#84cc16' },
  { label: 'Damage Transcends Itself Trying',                weight: 0.05, tier: 'Transcendent',  score: 157, color: '#65a30d' },
  { label: 'Harm Is Meaningless to Them',                    weight: 0.05, tier: 'Transcendent+', score: 159, color: '#4d7c0f' },
  { label: 'Infinite Durability',                            weight: 0.03, tier: 'Infinite-',     score: 161, color: '#525252' },
  { label: 'Truly Infinite Endurance',                       weight: 0.03, tier: 'Infinite',      score: 163, color: '#262626' },
  { label: 'Beyond Infinite Durability',                     weight: 0.03, tier: 'Infinite+',     score: 165, color: '#000000' },
]
