import type { FlavorLabel } from './types'

export const durabilityLabels: FlavorLabel[] = [
  { label: 'Tissue Paper Constitution',           weight: 4, tier: 'F-',   score: 2,   color: '#555'    },
  { label: 'Bruises Thinking Too Hard',           weight: 4, tier: 'F',    score: 5,   color: '#666'    },
  { label: 'Gets Winded on Stairs',               weight: 4, tier: 'F+',   score: 8,   color: '#777'    },
  { label: 'Normal Human Resilience',             weight: 6, tier: 'E-',   score: 11,  color: '#6b7280' },
  { label: 'Takes a Hit, Complains About It',     weight: 6, tier: 'E',    score: 14,  color: '#9ca3af' },
  { label: 'Takes Hits Without Flinching',        weight: 6, tier: 'E+',   score: 17,  color: '#d1d5db' },
  { label: 'Shrugs Off Minor Injuries',           weight: 8, tier: 'D-',   score: 20,  color: '#92400e' },
  { label: 'Tough to Slow Down',                  weight: 8, tier: 'D',    score: 23,  color: '#b45309' },
  { label: 'Breaks Weapons on Their Skin',        weight: 8, tier: 'D+',   score: 26,  color: '#d97706' },
  { label: 'Bulletproof Moments',                 weight: 8, tier: 'C-',   score: 30,  color: '#1d4ed8' },
  { label: 'Small Arms Do Not Register',          weight: 8, tier: 'C',    score: 34,  color: '#2563eb' },
  { label: 'Survives Explosions',                 weight: 8, tier: 'C+',   score: 38,  color: '#3b82f6' },
  { label: 'Walking Tank',                        weight: 7, tier: 'B-',   score: 42,  color: '#065f46' },
  { label: 'Walks Out of Warzones',               weight: 7, tier: 'B',    score: 47,  color: '#059669' },
  { label: 'Shrugs Off Artillery',                weight: 7, tier: 'B+',   score: 52,  color: '#34d399' },
  { label: 'Nuclear-Resistant',                   weight: 5, tier: 'A-',   score: 57,  color: '#7c3aed' },
  { label: 'Continental Blast Immune',            weight: 5, tier: 'A',    score: 62,  color: '#8b5cf6' },
  { label: 'Planet-Core Survivor',                weight: 5, tier: 'A+',   score: 67,  color: '#a78bfa' },
  { label: 'Stellar Flares Tickle',               weight: 4, tier: 'S-',   score: 72,  color: '#b91c1c' },
  { label: 'Supernova Adjacent',                  weight: 4, tier: 'S',    score: 77,  color: '#dc2626' },
  { label: 'Universe Won\'t Kill Them',           weight: 4, tier: 'S+',   score: 81,  color: '#ef4444' },
  { label: 'Endures Reality Fractures',           weight: 3, tier: 'SS-',  score: 85,  color: '#ea580c' },
  { label: 'Death Itself Gives Up',               weight: 3, tier: 'SS',   score: 88,  color: '#f97316' },
  { label: 'Exists Through Annihilation',         weight: 3, tier: 'SS+',  score: 91,  color: '#fb923c' },
  { label: 'The Damage Happened to the Attack',        weight: 2, tier: 'SSS-',      score: 94,  color: '#ca8a04' },
  { label: 'Concept of Harm Does Not Apply',           weight: 2, tier: 'SSS',       score: 97,  color: '#eab308' },
  { label: 'Invincible in Every Sense',                weight: 2, tier: 'SSS+',      score: 99,  color: '#fde047' },
  { label: 'Survives Galactic Annihilation Events',    weight: 2, tier: 'Z-',        score: 101, color: '#0e7490' },
  { label: 'Withstands Universal Collapse Casually',   weight: 2, tier: 'Z',         score: 103, color: '#0891b2' },
  { label: 'Absorbs the Heat Death of a Universe',     weight: 2, tier: 'Z+',        score: 105, color: '#06b6d4' },
  { label: 'Endures Across Multiple Collapsing Realities', weight: 1, tier: 'ZZ-',  score: 107, color: '#3730a3' },
  { label: 'Persists Through Multiversal Extinction',  weight: 1, tier: 'ZZ',        score: 109, color: '#4f46e5' },
  { label: 'Outlasts the Concept of Destruction',      weight: 1, tier: 'ZZ+',       score: 111, color: '#818cf8' },
  { label: 'Immune to Annihilation as a Category',     weight: 1, tier: 'ZZZ-',      score: 113, color: '#9d174d' },
  { label: 'Cannot Be Destroyed — Verified',           weight: 1, tier: 'ZZZ',       score: 115, color: '#be185d' },
  { label: 'Destruction Refuses to Process the Request', weight: 1, tier: 'ZZZ+',   score: 117, color: '#ec4899' },
  { label: 'Endures Directly in the Divine Realm',     weight: 1, tier: 'Celestial-',score: 119, color: '#075985' },
  { label: 'Celestial Forces Cannot Touch Them',       weight: 1, tier: 'Celestial', score: 121, color: '#0284c7' },
  { label: 'Exists Beyond the Reach of Any Ruin',      weight: 1, tier: 'Celestial+',score: 123, color: '#38bdf8' },
  { label: 'Nothing in Any Plane Can Kill Them',        weight: 1, tier: 'Godly-',   score: 125, color: '#c026d3' },
  { label: 'The Universe Tried, It Did Not',           weight: 1, tier: 'Godly',     score: 127, color: '#e879f9' },
  { label: 'Pre-Dates the Concept of Harm',            weight: 1, tier: 'Primordial',score: 130, color: '#ffffff' },
]
