// enchantments.ts — Enchantment content pool for Wheel of Fate.
// 80+ SimpleItem entries spanning legendary to absurd. No default export. No functions.

import type { SimpleItem } from './types'

export const enchantments: SimpleItem[] = [
  // ── Practical / tactical (common) ────────────────────────────────────────
  { label: 'Returning',                                                    weight: 3, element: 'Arcane',  grade: 'C' },
  { label: 'Extending Rune',                                               weight: 3, element: 'Arcane',  grade: 'C' },
  { label: 'Seeking Inscription',                                          weight: 3, element: 'Arcane',  grade: 'C' },
  { label: 'Parrying Groove',                                              weight: 3, element: 'Metal',   grade: 'C' },
  { label: 'Lightweight Alloy',                                            weight: 3, element: 'Metal',   grade: 'C' },
  { label: 'Bloodhunter Mark',                                             weight: 3, element: 'Blood',   grade: 'C' },
  { label: 'Silencing Strike',                                             weight: 3, element: 'Shadow',  grade: 'C' },
  { label: 'Phase Shift',                                                  weight: 3, element: 'Arcane',  grade: 'C' },
  { label: 'Warding Sigil',                                                weight: 3, element: 'Arcane',  grade: 'C' },
  { label: 'Binding Hex',                                                  weight: 3, element: 'Shadow',  grade: 'C' },
  // ── Absurd (common) ───────────────────────────────────────────────────────
  { label: 'Slightly Faster',                                              weight: 3, element: 'Wind',    grade: 'D' },
  { label: 'Warm to the Touch (No One Knows Why)',                         weight: 3, element: 'Fire',    grade: 'D' },
  { label: 'Mildly Ominous Glow',                                          weight: 3, element: 'Shadow',  grade: 'D' },
  { label: 'Hums Off-Key',                                                 weight: 3, element: 'Sound',   grade: 'D' },
  { label: 'Definitely Not Haunted',                                       weight: 3, element: 'Soul',    grade: 'D' },
  { label: 'Resonates with Nostalgia',                                     weight: 3, element: 'Neutral', grade: 'D' },
  { label: 'Attractive to Small Birds',                                    weight: 3, element: 'Nature',  grade: 'D' },
  { label: 'Makes a Satisfying "Thunk"',                                   weight: 3, element: 'Earth',   grade: 'D' },
  { label: 'Previous Owner Unspecified (It\'s Fine)',                      weight: 3, element: 'Shadow',  grade: 'D' },
  { label: 'Blessed by a Passing Deity Who Didn\'t Stop',                  weight: 3, element: 'Light',   grade: 'D' },
  { label: 'Slightly Smug',                                                weight: 3, element: 'Neutral', grade: 'D' },
  { label: 'Named (Refuses to Answer)',                                    weight: 3, element: 'Psychic', grade: 'D' },
  { label: 'Self-Aware (Embarrassed About It)',                            weight: 3, element: 'Psychic', grade: 'D' },
  { label: 'Enhanced by Exposure to Tuesdays',                             weight: 3, element: 'Chaos',   grade: 'D' },
  { label: 'Anointed with Something That Smells Like Victory',             weight: 3, element: 'Neutral', grade: 'D' },
  // ── Elemental / classical (uncommon) ─────────────────────────────────────
  { label: 'Acid Bite',                                                    weight: 2, element: 'Poison',  grade: 'B' },
  { label: 'Poison Seep',                                                  weight: 2, element: 'Poison',  grade: 'B' },
  { label: 'Chain Lightning Etching',                                      weight: 2, element: 'Lightning',grade: 'B' },
  { label: 'Blizzard Binding',                                             weight: 2, element: 'Ice',      grade: 'B' },
  { label: 'Earthquake Rune',                                              weight: 2, element: 'Earth',   grade: 'B' },
  { label: 'Galeforce Carving',                                            weight: 2, element: 'Wind',    grade: 'B' },
  { label: 'Magma Heart',                                                  weight: 2, element: 'Fire',    grade: 'B' },
  { label: 'Tidal Rune',                                                   weight: 2, element: 'Water',   grade: 'B' },
  { label: 'Thornwall Inscription',                                        weight: 2, element: 'Nature',  grade: 'B' },
  { label: 'Crystal Resonance',                                            weight: 2, element: 'Arcane',  grade: 'B' },
  { label: 'Arcane Sharpening',                                            weight: 2, element: 'Arcane',  grade: 'B' },
  { label: 'Necrotic Leach',                                               weight: 2, element: 'Soul',    grade: 'B' },
  { label: 'Radiant Smite',                                                weight: 2, element: 'Light',   grade: 'B' },
  { label: 'Psychic Resonance',                                            weight: 2, element: 'Psychic', grade: 'B' },
  { label: 'Entropic Decay',                                               weight: 2, element: 'Void',    grade: 'B' },
  // ── Legendary / powerful (rare) ──────────────────────────────────────────
  { label: 'Flamebrand',                                                   weight: 1, element: 'Fire',    grade: 'A' },
  { label: 'Vorpal Edge',                                                  weight: 1, element: 'Metal',   grade: 'A' },
  { label: 'Frostbite',                                                    weight: 1, element: 'Ice',     grade: 'A' },
  { label: 'Thunderstrike',                                                weight: 1, element: 'Lightning',grade: 'A' },
  { label: 'Soulstealer',                                                  weight: 1, element: 'Soul',    grade: 'A' },
  { label: 'Shadowmeld',                                                   weight: 1, element: 'Shadow',  grade: 'A' },
  { label: 'Holy Consecration',                                            weight: 1, element: 'Light',   grade: 'A' },
  { label: 'Vampiric Drain',                                               weight: 1, element: 'Blood',   grade: 'A' },
  { label: 'Ethereal Phasing',                                             weight: 1, element: 'Void',    grade: 'A' },
  { label: 'Unstoppable Force',                                            weight: 1, element: 'Earth',   grade: 'A' },
  { label: 'Immovable Object',                                             weight: 1, element: 'Earth',   grade: 'A' },
  // ── Absurd (rare) ─────────────────────────────────────────────────────────
  { label: 'Cursed (But It Somehow Works Out)',                            weight: 1, element: 'Chaos',   grade: 'C' },
  { label: '+1 Against Tuesdays',                                          weight: 1, element: 'Neutral', grade: 'D' },
  { label: 'Slightly Magnetic',                                            weight: 1, element: 'Metal',   grade: 'D' },
  { label: 'Probably Cursed But Who Can Tell',                             weight: 1, element: 'Chaos',   grade: 'D' },
  { label: 'Glows When Goblins Are Nearby (Goblins Are Everywhere)',       weight: 1, element: 'Nature',  grade: 'D' },
  { label: 'Smells Like Victory (Investigators Dispute This)',              weight: 1, element: 'Neutral', grade: 'D' },
  { label: 'Extremely Loud Swish',                                         weight: 1, element: 'Sound',   grade: 'D' },
  { label: 'Anti-Social Properties',                                       weight: 1, element: 'Shadow',  grade: 'D' },
  { label: 'Blessed by a Deity Who Was Having a Bad Day',                  weight: 1, element: 'Light',   grade: 'D' },
  { label: 'Keen Edge (Self-Assessed)',                                    weight: 1, element: 'Metal',   grade: 'D' },
  { label: 'Radiant (in the Humble Opinion of Its Wielder)',               weight: 1, element: 'Light',   grade: 'D' },
  { label: 'Bound to a Soul (They Don\'t Know)',                           weight: 1, element: 'Soul',    grade: 'C' },
  { label: 'Moderately Enchanted',                                         weight: 1, element: 'Neutral', grade: 'D' },
  { label: 'Strongly Worded Inscription',                                  weight: 1, element: 'Neutral', grade: 'D' },
  { label: 'Runes of Unclear Purpose',                                     weight: 1, element: 'Arcane',  grade: 'D' },
  { label: 'Ancient Text (Nobody Can Read)',                               weight: 1, element: 'Arcane',  grade: 'D' },
  { label: 'Smite (Requires Paperwork)',                                   weight: 1, element: 'Light',   grade: 'D' },
  { label: 'Infused with the Essence of a Very Tired Wizard',              weight: 1, element: 'Arcane',  grade: 'D' },
  { label: 'Enchanted Specifically to Annoy One Person',                   weight: 1, element: 'Psychic', grade: 'D' },
  { label: 'Twice Enchanted (The Second Cancelled the First)',              weight: 1, element: 'Arcane',  grade: 'D' },
  { label: 'Forged in a Volcano on Purpose',                               weight: 1, element: 'Fire',    grade: 'D' },
  { label: 'Blessed by the God of Mild Inconvenience',                     weight: 1, element: 'Light',   grade: 'D' },
  // ── Godtier (rare) ────────────────────────────────────────────────────────
  { label: 'World-Breaker Runes',                                          weight: 1, element: 'Earth',   grade: 'SS' },
  { label: 'Sundering Edge',                                               weight: 1, element: 'Metal',   grade: 'S'  },
  { label: 'Voidheart Binding',                                            weight: 1, element: 'Void',    grade: 'S'  },
  { label: 'Eternal Sharpness',                                            weight: 1, element: 'Metal',   grade: 'S'  },
  { label: 'Soul Reaper',                                                  weight: 1, element: 'Soul',    grade: 'S'  },
  { label: 'Celestial Temper',                                             weight: 1, element: 'Light',   grade: 'SS' },
  { label: 'Abyssal Infusion',                                             weight: 1, element: 'Void',    grade: 'S'  },
  { label: 'Time-Locked Strike',                                           weight: 1, element: 'Time',    grade: 'S'  },
  { label: 'Reality Sever',                                                weight: 1, element: 'Arcane',  grade: 'SS' },
  { label: 'Fate Cutter',                                                  weight: 1, element: 'Arcane',  grade: 'SS' },
  { label: 'Godslayer Edge',                                               weight: 1, element: 'Light',   grade: 'SSS'},
  { label: 'Dragon\'s Fury Inscription',                                   weight: 1, element: 'Fire',    grade: 'S'  },
  { label: 'Primordial Consecration',                                      weight: 1, element: 'Light',   grade: 'SSS'},
  { label: 'Starblight Temper',                                            weight: 1, element: 'Cosmic',  grade: 'S'  },
  { label: 'Death\'s Own Edge',                                            weight: 1, element: 'Soul',    grade: 'SS' },
]
