// enchantments.ts — Enchantment content pool for Wheel of Fate.
// 80+ SimpleItem entries spanning legendary to absurd. No default export. No functions.

import type { SimpleItem } from './types'

export const enchantments: SimpleItem[] = [
  { label: 'Returning', weight: 3 },
  { label: 'Extending Rune', weight: 3 },
  { label: 'Seeking Inscription', weight: 3 },
  { label: 'Parrying Groove', weight: 3 },
  { label: 'Lightweight Alloy', weight: 3 },
  { label: 'Bloodhunter Mark', weight: 3 },
  { label: 'Silencing Strike', weight: 3 },
  { label: 'Phase Shift', weight: 3 },
  { label: 'Warding Sigil', weight: 3 },
  { label: 'Binding Hex', weight: 3 },
  { label: 'Slightly Faster', weight: 3 },
  { label: 'Warm to the Touch (No One Knows Why)', weight: 3 },
  { label: 'Mildly Ominous Glow', weight: 3 },
  { label: 'Hums Off-Key', weight: 3 },
  { label: 'Definitely Not Haunted', weight: 3 },
  { label: 'Resonates with Nostalgia', weight: 3 },
  { label: 'Attractive to Small Birds', weight: 3 },
  { label: 'Makes a Satisfying "Thunk"', weight: 3 },
  { label: 'Previous Owner Unspecified (It\'s Fine)', weight: 3 },
  { label: 'Blessed by a Passing Deity Who Didn\'t Stop', weight: 3 },
  { label: 'Slightly Smug', weight: 3 },
  { label: 'Named (Refuses to Answer)', weight: 3 },
  { label: 'Self-Aware (Embarrassed About It)', weight: 3 },
  { label: 'Enhanced by Exposure to Tuesdays', weight: 3 },
  { label: 'Anointed with Something That Smells Like Victory', weight: 3 },
  { label: 'Acid Bite', weight: 2 },
  { label: 'Poison Seep', weight: 2 },
  { label: 'Chain Lightning Etching', weight: 2 },
  { label: 'Blizzard Binding', weight: 2 },
  { label: 'Earthquake Rune', weight: 2 },
  { label: 'Galeforce Carving', weight: 2 },
  { label: 'Magma Heart', weight: 2 },
  { label: 'Tidal Rune', weight: 2 },
  { label: 'Thornwall Inscription', weight: 2 },
  { label: 'Crystal Resonance', weight: 2 },
  { label: 'Arcane Sharpening', weight: 2 },
  { label: 'Necrotic Leach', weight: 2 },
  { label: 'Radiant Smite', weight: 2 },
  { label: 'Psychic Resonance', weight: 2 },
  { label: 'Entropic Decay', weight: 2 },
  { label: 'Flamebrand', weight: 1 },
  { label: 'Vorpal Edge', weight: 1 },
  { label: 'Frostbite', weight: 1 },
  { label: 'Thunderstrike', weight: 1 },
  { label: 'Soulstealer', weight: 1 },
  { label: 'Shadowmeld', weight: 1 },
  { label: 'Holy Consecration', weight: 1 },
  { label: 'Vampiric Drain', weight: 1 },
  { label: 'Ethereal Phasing', weight: 1 },
  { label: 'Unstoppable Force', weight: 1 },
  { label: 'Immovable Object', weight: 1 },
  { label: 'Cursed (But It Somehow Works Out)', weight: 1 },
  { label: '+1 Against Tuesdays', weight: 1 },
  { label: 'Slightly Magnetic', weight: 1 },
  { label: 'Probably Cursed But Who Can Tell', weight: 1 },
  { label: 'Glows When Goblins Are Nearby (Goblins Are Everywhere)', weight: 1 },
  { label: 'Smells Like Victory (Investigators Dispute This)', weight: 1 },
  { label: 'Extremely Loud Swish', weight: 1 },
  { label: 'Anti-Social Properties', weight: 1 },
  { label: 'Blessed by a Deity Who Was Having a Bad Day', weight: 1 },
  { label: 'Keen Edge (Self-Assessed)', weight: 1 },
  { label: 'Radiant (in the Humble Opinion of Its Wielder)', weight: 1 },
  { label: 'Bound to a Soul (They Don\'t Know)', weight: 1 },
  { label: 'Moderately Enchanted', weight: 1 },
  { label: 'Strongly Worded Inscription', weight: 1 },
  { label: 'Runes of Unclear Purpose', weight: 1 },
  { label: 'Ancient Text (Nobody Can Read)', weight: 1 },
  { label: 'Smite (Requires Paperwork)', weight: 1 },
  { label: 'Infused with the Essence of a Very Tired Wizard', weight: 1 },
  { label: 'Enchanted Specifically to Annoy One Person', weight: 1 },
  { label: 'Twice Enchanted (The Second Cancelled the First)', weight: 1 },
  { label: 'Forged in a Volcano on Purpose', weight: 1 },
  { label: 'Blessed by the God of Mild Inconvenience', weight: 1 },
  { label: 'World-Breaker Runes', weight: 1 },
  { label: 'Sundering Edge', weight: 1 },
  { label: 'Voidheart Binding', weight: 1 },
  { label: 'Eternal Sharpness', weight: 1 },
  { label: 'Soul Reaper', weight: 1 },
  { label: 'Celestial Temper', weight: 1 },
  { label: 'Abyssal Infusion', weight: 1 },
  { label: 'Time-Locked Strike', weight: 1 },
  { label: 'Reality Sever', weight: 1 },
  { label: 'Fate Cutter', weight: 1 },
  { label: 'Godslayer Edge', weight: 1 },
  { label: 'Dragon\'s Fury Inscription', weight: 1 },
  { label: 'Primordial Consecration', weight: 1 },
  { label: 'Starblight Temper', weight: 1 },
  { label: 'Death\'s Own Edge', weight: 1 },
  // Legendary / powerful (rare)
  // Elemental / classical (uncommon)
  // Tactical / practical (common)
  // Absurd (common)
]
