import type { FlavorLabel } from './types'

export const energyLevelLabels: FlavorLabel[] = [
  { label: 'Naps More Than Acts',                    weight: 1, tier: 'F-',   score: 2,   color: '#555'    },
  { label: 'Visibly Drained at Rest',                weight: 1, tier: 'F',    score: 5,   color: '#666'    },
  { label: 'Makes It to Lunch',                      weight: 1, tier: 'F+',   score: 8,   color: '#777'    },
  { label: 'Normal Human Stamina',                   weight: 1, tier: 'E-',   score: 11,  color: '#6b7280' },
  { label: 'Active Day Without Exhaustion',          weight: 1, tier: 'E',    score: 14,  color: '#9ca3af' },
  { label: 'Rarely Tires',                           weight: 1, tier: 'E+',   score: 17,  color: '#d1d5db' },
  { label: 'Athlete-Level Stamina',                  weight: 1, tier: 'D-',   score: 20,  color: '#92400e' },
  { label: 'Extended Combat Capable',                weight: 1, tier: 'D',    score: 23,  color: '#b45309' },
  { label: 'Days Without Rest',                      weight: 1, tier: 'D+',   score: 26,  color: '#d97706' },
  { label: 'Tireless in Extended Combat',            weight: 1, tier: 'C-',   score: 30,  color: '#1d4ed8' },
  { label: 'Aura Visibly Radiates',                  weight: 1, tier: 'C',    score: 34,  color: '#2563eb' },
  { label: 'Energy Disrupts Electronics Nearby',     weight: 1, tier: 'C+',   score: 38,  color: '#3b82f6' },
  { label: 'Ki Presence Felt in the Room',           weight: 1, tier: 'B-',   score: 42,  color: '#065f46' },
  { label: 'Aura Combat Enhancement',                weight: 1, tier: 'B',    score: 47,  color: '#059669' },
  { label: 'Overflows with Restrained Power',        weight: 1, tier: 'B+',   score: 52,  color: '#34d399' },
  { label: 'Energy Warps the Environment',           weight: 1, tier: 'A-',   score: 57,  color: '#7c3aed' },
  { label: 'Power Level Detectable at Distance',     weight: 1, tier: 'A',    score: 62,  color: '#8b5cf6' },
  { label: 'Atmospheric Disturbance on Release',     weight: 1, tier: 'A+',   score: 67,  color: '#a78bfa' },
  { label: 'Continent-Scale Energy Presence',        weight: 1, tier: 'S-',   score: 72,  color: '#b91c1c' },
  { label: 'Planet Feels It When They Power Up',     weight: 1, tier: 'S',    score: 77,  color: '#dc2626' },
  { label: 'Solar System-Level Output',              weight: 1, tier: 'S+',   score: 81,  color: '#ef4444' },
  { label: 'Galactic Energy Signature',              weight: 1, tier: 'SS-',  score: 85,  color: '#ea580c' },
  { label: 'Universe Registers Their Presence',      weight: 1, tier: 'SS',   score: 88,  color: '#f97316' },
  { label: 'Energy Output Has Its Own Gravity',      weight: 1, tier: 'SS+',  score: 91,  color: '#fb923c' },
  { label: 'Powering Up Rearranges Stars',           weight: 1, tier: 'SSS-', score: 94,  color: '#ca8a04' },
  { label: 'Energy Level Is a Natural Phenomenon',   weight: 1, tier: 'SSS',  score: 97,  color: '#eab308' },
  { label: 'The Big Bang Was Practice',              weight: 1, tier: 'SSS+', score: 99,  color: '#fde047' },
  { label: 'Existence Itself Is Their Energy Source', weight: 1, tier: 'God', score: 100, color: '#e879f9' },
]
