import type { FlavorLabel } from './types'

export const energyLevelLabels: FlavorLabel[] = [
  // F- (score: 2)
  { label: 'Tired After Thinking About Standing Up', weight: 1, tier: 'F-', score: 2, color: 'var(--tier-f-minus)' },
  { label: 'Naps to Recover From Naps', weight: 1, tier: 'F-', score: 2, color: 'var(--tier-f-minus)' },
  { label: 'Walking Is a Sprint to Them', weight: 1, tier: 'F-', score: 2, color: 'var(--tier-f-minus)' },
  { label: 'Exhausted by Breakfast', weight: 1, tier: 'F-', score: 2, color: 'var(--tier-f-minus)' },
  { label: 'Peak Hours: 11am-11:15am', weight: 1, tier: 'F-', score: 2, color: 'var(--tier-f-minus)' },
  { label: 'Slept Through Their Own Motivation Speech', weight: 1, tier: 'F-', score: 2, color: 'var(--tier-f-minus)' },
  { label: 'Rest Required After Breathing Hard', weight: 1, tier: 'F-', score: 2, color: 'var(--tier-f-minus)' },
  { label: 'Energy Level: Dial Tone', weight: 1, tier: 'F-', score: 2, color: 'var(--tier-f-minus)' },
  { label: 'Gets Winded Opening Doors', weight: 1, tier: 'F-', score: 2, color: 'var(--tier-f-minus)' },
  { label: 'Powered Off by Mild Breezes', weight: 1, tier: 'F-', score: 2, color: 'var(--tier-f-minus)' },
  { label: 'Exists in a Permanent Pre-Nap State', weight: 1, tier: 'F-', score: 2, color: 'var(--tier-f-minus)' },
  { label: 'Has Never Once Felt "Rested"', weight: 1, tier: 'F-', score: 2, color: 'var(--tier-f-minus)' },
  { label: 'Falls Asleep Mid-Complaint', weight: 1, tier: 'F-', score: 2, color: 'var(--tier-f-minus)' },
  { label: 'Snores During High-Intensity Situations', weight: 1, tier: 'F-', score: 2, color: 'var(--tier-f-minus)' },
  { label: 'Stamina: Decorative', weight: 1, tier: 'F-', score: 2, color: 'var(--tier-f-minus)' },
  { label: 'Running on Fumes — The Tank Was Empty', weight: 1, tier: 'F-', score: 2, color: 'var(--tier-f-minus)' },
  { label: 'Cannot Climb Stairs and Arrive Functional', weight: 1, tier: 'F-', score: 2, color: 'var(--tier-f-minus)' },
  { label: 'Considered "Inactive" by Medical Devices', weight: 1, tier: 'F-', score: 2, color: 'var(--tier-f-minus)' },
  { label: 'Woke Up Tired — Every Day, Forever', weight: 1, tier: 'F-', score: 2, color: 'var(--tier-f-minus)' },
  { label: 'Energy Signature: Flatline', weight: 1, tier: 'F-', score: 2, color: 'var(--tier-f-minus)' },

  // F (score: 5)
  { label: 'Low Energy but Present', weight: 1, tier: 'F', score: 5, color: 'var(--tier-f)' },
  { label: 'Warms Up After 4 Hours', weight: 1, tier: 'F', score: 5, color: 'var(--tier-f)' },
  { label: 'Can Make It Through the Morning', weight: 1, tier: 'F', score: 5, color: 'var(--tier-f)' },
  { label: 'Good Day: Made It to Lunch', weight: 1, tier: 'F', score: 5, color: 'var(--tier-f)' },
  { label: 'Functioning on Low Power Mode', weight: 1, tier: 'F', score: 5, color: 'var(--tier-f)' },
  { label: 'Coffee-Dependent Existence', weight: 1, tier: 'F', score: 5, color: 'var(--tier-f)' },
  { label: 'Occasional Bursts of Mild Enthusiasm', weight: 1, tier: 'F', score: 5, color: 'var(--tier-f)' },
  { label: 'Regularly Hits 2pm Crash', weight: 1, tier: 'F', score: 5, color: 'var(--tier-f)' },
  { label: 'Can Walk and Not Complain (Mostly)', weight: 1, tier: 'F', score: 5, color: 'var(--tier-f)' },
  { label: 'Technically Awake', weight: 1, tier: 'F', score: 5, color: 'var(--tier-f)' },
  { label: 'Energy: "Present — Barely"', weight: 1, tier: 'F', score: 5, color: 'var(--tier-f)' },
  { label: 'Works in Short Bursts, Crashes Afterward', weight: 1, tier: 'F', score: 5, color: 'var(--tier-f)' },
  { label: 'Yawning: Chronic', weight: 1, tier: 'F', score: 5, color: 'var(--tier-f)' },
  { label: 'Peak Performance Window: 20 Minutes', weight: 1, tier: 'F', score: 5, color: 'var(--tier-f)' },
  { label: 'Avoids Stairs When Possible', weight: 1, tier: 'F', score: 5, color: 'var(--tier-f)' },
  { label: 'Naps Scheduled Into the Day', weight: 1, tier: 'F', score: 5, color: 'var(--tier-f)' },
  { label: 'Gets By on Passive Participation', weight: 1, tier: 'F', score: 5, color: 'var(--tier-f)' },
  { label: 'Vitality: Technically Detectable', weight: 1, tier: 'F', score: 5, color: 'var(--tier-f)' },
  { label: 'Needs Two Breaks on Short Walks', weight: 1, tier: 'F', score: 5, color: 'var(--tier-f)' },
  { label: 'Runs on Snacks and Spite', weight: 1, tier: 'F', score: 5, color: 'var(--tier-f)' },

  // F+ (score: 8)
  { label: 'Decent Energy Most Days', weight: 1, tier: 'F+', score: 8, color: 'var(--tier-f-plus)' },
  { label: 'Makes It Through Full Workdays', weight: 1, tier: 'F+', score: 8, color: 'var(--tier-f-plus)' },
  { label: 'Active When Motivated', weight: 1, tier: 'F+', score: 8, color: 'var(--tier-f-plus)' },
  { label: 'Occasional Impressive Output', weight: 1, tier: 'F+', score: 8, color: 'var(--tier-f-plus)' },
  { label: 'Can Exercise Without Drama', weight: 1, tier: 'F+', score: 8, color: 'var(--tier-f-plus)' },
  { label: 'Holds a Steady Pace', weight: 1, tier: 'F+', score: 8, color: 'var(--tier-f-plus)' },
  { label: 'Not Winded by Normal Activity', weight: 1, tier: 'F+', score: 8, color: 'var(--tier-f-plus)' },
  { label: 'Vitality: Functional and Consistent', weight: 1, tier: 'F+', score: 8, color: 'var(--tier-f-plus)' },
  { label: 'Good Energy After Rest', weight: 1, tier: 'F+', score: 8, color: 'var(--tier-f-plus)' },
  { label: 'Keeps Pace With Most People', weight: 1, tier: 'F+', score: 8, color: 'var(--tier-f-plus)' },
  { label: 'Reliably Awake and Functional by 9am', weight: 1, tier: 'F+', score: 8, color: 'var(--tier-f-plus)' },
  { label: 'Active in the Evenings Without Regret', weight: 1, tier: 'F+', score: 8, color: 'var(--tier-f-plus)' },
  { label: 'Stamina That Gets the Job Done', weight: 1, tier: 'F+', score: 8, color: 'var(--tier-f-plus)' },
  { label: 'Doesn\'t Need a Nap Every Afternoon', weight: 1, tier: 'F+', score: 8, color: 'var(--tier-f-plus)' },
  { label: 'Recovers From Exercise By Next Day', weight: 1, tier: 'F+', score: 8, color: 'var(--tier-f-plus)' },
  { label: 'Pulls Through Demanding Days', weight: 1, tier: 'F+', score: 8, color: 'var(--tier-f-plus)' },
  { label: 'Sustained Effort Possible', weight: 1, tier: 'F+', score: 8, color: 'var(--tier-f-plus)' },
  { label: 'Average Energy — Not a Complaint', weight: 1, tier: 'F+', score: 8, color: 'var(--tier-f-plus)' },
  { label: 'Wakes With Purpose Most Days', weight: 1, tier: 'F+', score: 8, color: 'var(--tier-f-plus)' },
  { label: 'Doesn\'t Drag — Keeps Moving', weight: 1, tier: 'F+', score: 8, color: 'var(--tier-f-plus)' },

  // E- (score: 11)
  { label: 'High-Energy Baseline', weight: 1, tier: 'E-', score: 11, color: 'var(--tier-e-minus)' },
  { label: 'Rested Before Others Wake', weight: 1, tier: 'E-', score: 11, color: 'var(--tier-e-minus)' },
  { label: 'Noticeably More Energetic Than Peers', weight: 1, tier: 'E-', score: 11, color: 'var(--tier-e-minus)' },
  { label: 'Never Drags on Long Tasks', weight: 1, tier: 'E-', score: 11, color: 'var(--tier-e-minus)' },
  { label: 'Maintains Intensity Without Flagging', weight: 1, tier: 'E-', score: 11, color: 'var(--tier-e-minus)' },
  { label: 'Energy Outlasts Events', weight: 1, tier: 'E-', score: 11, color: 'var(--tier-e-minus)' },
  { label: 'Late Nights Don\'t Break Them', weight: 1, tier: 'E-', score: 11, color: 'var(--tier-e-minus)' },
  { label: 'Recovered by Morning — Always', weight: 1, tier: 'E-', score: 11, color: 'var(--tier-e-minus)' },
  { label: 'Stamina Others Find Slightly Annoying', weight: 1, tier: 'E-', score: 11, color: 'var(--tier-e-minus)' },
  { label: 'Operates at 90% While Others Are at 50%', weight: 1, tier: 'E-', score: 11, color: 'var(--tier-e-minus)' },
  { label: 'No Mid-Afternoon Crash Ever', weight: 1, tier: 'E-', score: 11, color: 'var(--tier-e-minus)' },
  { label: 'Exercises Daily Without Dreading It', weight: 1, tier: 'E-', score: 11, color: 'var(--tier-e-minus)' },
  { label: 'High Endurance Across All Tasks', weight: 1, tier: 'E-', score: 11, color: 'var(--tier-e-minus)' },
  { label: 'Wakes Up Ready', weight: 1, tier: 'E-', score: 11, color: 'var(--tier-e-minus)' },
  { label: 'Energy: Consistent and High', weight: 1, tier: 'E-', score: 11, color: 'var(--tier-e-minus)' },
  { label: 'Holds Peak Hours Across Full Days', weight: 1, tier: 'E-', score: 11, color: 'var(--tier-e-minus)' },
  { label: 'Rarely Slows, Never Stops', weight: 1, tier: 'E-', score: 11, color: 'var(--tier-e-minus)' },
  { label: 'Multi-Day Events Are No Problem', weight: 1, tier: 'E-', score: 11, color: 'var(--tier-e-minus)' },
  { label: 'Outlasts Most Training Programs', weight: 1, tier: 'E-', score: 11, color: 'var(--tier-e-minus)' },
  { label: 'Energized by Challenges Others Find Draining', weight: 1, tier: 'E-', score: 11, color: 'var(--tier-e-minus)' },

  // E (score: 14)
  { label: 'Boundless Vitality', weight: 1, tier: 'E', score: 14, color: 'var(--tier-e)' },
  { label: 'Goes From Dawn to Midnight With Ease', weight: 1, tier: 'E', score: 14, color: 'var(--tier-e)' },
  { label: 'Others Are Tired Just Watching', weight: 1, tier: 'E', score: 14, color: 'var(--tier-e)' },
  { label: 'Sleep Optional (Not Really — But Almost)', weight: 1, tier: 'E', score: 14, color: 'var(--tier-e)' },
  { label: 'Never Flagged in a Recorded Session', weight: 1, tier: 'E', score: 14, color: 'var(--tier-e)' },
  { label: 'Carries High Output All Day Without Fuel', weight: 1, tier: 'E', score: 14, color: 'var(--tier-e)' },
  { label: 'Recovers From Full Days in Hours', weight: 1, tier: 'E', score: 14, color: 'var(--tier-e)' },
  { label: 'High Energy Is Just Their Resting State', weight: 1, tier: 'E', score: 14, color: 'var(--tier-e)' },
  { label: 'Consistently Peak-Performing', weight: 1, tier: 'E', score: 14, color: 'var(--tier-e)' },
  { label: 'Energy That Lifts the Room', weight: 1, tier: 'E', score: 14, color: 'var(--tier-e)' },
  { label: 'Seems Energized by Things That Exhaust Others', weight: 1, tier: 'E', score: 14, color: 'var(--tier-e)' },
  { label: 'Has a Reserve Tank Nobody Else Has', weight: 1, tier: 'E', score: 14, color: 'var(--tier-e)' },
  { label: 'Body Doesn\'t Know the Word "Fatigue" Yet', weight: 1, tier: 'E', score: 14, color: 'var(--tier-e)' },
  { label: 'Clocks Impressive Hours Without Breakdown', weight: 1, tier: 'E', score: 14, color: 'var(--tier-e)' },
  { label: 'Vitality: Legendary for Their Age Group', weight: 1, tier: 'E', score: 14, color: 'var(--tier-e)' },
  { label: 'Energized After Others Have Collapsed', weight: 1, tier: 'E', score: 14, color: 'var(--tier-e)' },
  { label: 'Runs Multi-Day Operations on Three Hours Sleep', weight: 1, tier: 'E', score: 14, color: 'var(--tier-e)' },
  { label: 'Energy Level Commented on Frequently by Observers', weight: 1, tier: 'E', score: 14, color: 'var(--tier-e)' },
  { label: 'Sustains Peak Output When Others Are at 10%', weight: 1, tier: 'E', score: 14, color: 'var(--tier-e)' },
  { label: 'Fatigue: Eventually, Hours Later, Mildly', weight: 1, tier: 'E', score: 14, color: 'var(--tier-e)' },

  // E+ (score: 17)
  { label: 'Superhuman Endurance', weight: 1, tier: 'E+', score: 17, color: 'var(--tier-e-plus)' },
  { label: 'Runs All Day, Runs All Night', weight: 1, tier: 'E+', score: 17, color: 'var(--tier-e-plus)' },
  { label: 'Certified Tireless', weight: 1, tier: 'E+', score: 17, color: 'var(--tier-e-plus)' },
  { label: 'Slept 4 Hours — Outpaced Everyone', weight: 1, tier: 'E+', score: 17, color: 'var(--tier-e-plus)' },
  { label: 'Energy Is Their Most Noted Feature', weight: 1, tier: 'E+', score: 17, color: 'var(--tier-e-plus)' },
  { label: 'Others Go Home; They Go Again', weight: 1, tier: 'E+', score: 17, color: 'var(--tier-e-plus)' },
  { label: 'Fatigued Opponents Are Confused', weight: 1, tier: 'E+', score: 17, color: 'var(--tier-e-plus)' },
  { label: 'Recovery Is Faster Than Most Warmups', weight: 1, tier: 'E+', score: 17, color: 'var(--tier-e-plus)' },
  { label: 'Can Go 48+ Hours Without Performance Drop', weight: 1, tier: 'E+', score: 17, color: 'var(--tier-e-plus)' },
  { label: 'Energizes Those Around Them Passively', weight: 1, tier: 'E+', score: 17, color: 'var(--tier-e-plus)' },
  { label: 'Stamina Not Found in Current Medical Literature', weight: 1, tier: 'E+', score: 17, color: 'var(--tier-e-plus)' },
  { label: 'Outlasts Everything Without Trying', weight: 1, tier: 'E+', score: 17, color: 'var(--tier-e-plus)' },
  { label: 'Doctors Called It "Unusual but Not Concerning"', weight: 1, tier: 'E+', score: 17, color: 'var(--tier-e-plus)' },
  { label: 'No Ceiling on Output Duration', weight: 1, tier: 'E+', score: 17, color: 'var(--tier-e-plus)' },
  { label: 'Every Activity Leaves Them Wanting More', weight: 1, tier: 'E+', score: 17, color: 'var(--tier-e-plus)' },
  { label: 'Woke Up Before Sleep Ended — Was Fine', weight: 1, tier: 'E+', score: 17, color: 'var(--tier-e-plus)' },
  { label: 'Fatigue: Rumored but Never Confirmed', weight: 1, tier: 'E+', score: 17, color: 'var(--tier-e-plus)' },
  { label: 'Body Converts Any Food Into Fuel Instantly', weight: 1, tier: 'E+', score: 17, color: 'var(--tier-e-plus)' },
  { label: 'Vitality: Classified as "Unfair" by Peers', weight: 1, tier: 'E+', score: 17, color: 'var(--tier-e-plus)' },
  { label: 'Energy Level Alarming to Observers', weight: 1, tier: 'E+', score: 17, color: 'var(--tier-e-plus)' },

  // D- (score: 20)
  { label: 'Inexhaustible Energy', weight: 1, tier: 'D-', score: 20, color: 'var(--tier-d-minus)' },
  { label: 'Goes Longer Than Any Training Program Allows', weight: 1, tier: 'D-', score: 20, color: 'var(--tier-d-minus)' },
  { label: 'Tired: A Concept They Know Only Theoretically', weight: 1, tier: 'D-', score: 20, color: 'var(--tier-d-minus)' },
  { label: 'Energy That Outlasts the Event Itself', weight: 1, tier: 'D-', score: 20, color: 'var(--tier-d-minus)' },
  { label: 'Recovery Rate: Immediate', weight: 1, tier: 'D-', score: 20, color: 'var(--tier-d-minus)' },
  { label: 'Runs at 100% Without Depletion', weight: 1, tier: 'D-', score: 20, color: 'var(--tier-d-minus)' },
  { label: 'Sleep Optional — Body Doesn\'t Enforce It', weight: 1, tier: 'D-', score: 20, color: 'var(--tier-d-minus)' },
  { label: 'Measured in Weeks Without Rest', weight: 1, tier: 'D-', score: 20, color: 'var(--tier-d-minus)' },
  { label: 'Vitality: Unprecedented in Clinical Records', weight: 1, tier: 'D-', score: 20, color: 'var(--tier-d-minus)' },
  { label: 'Challenges Others\' Will to Continue Simply by Persisting', weight: 1, tier: 'D-', score: 20, color: 'var(--tier-d-minus)' },
  { label: 'Outlasts All Opposition', weight: 1, tier: 'D-', score: 20, color: 'var(--tier-d-minus)' },
  { label: 'Energy Is a Threat in Endurance Events', weight: 1, tier: 'D-', score: 20, color: 'var(--tier-d-minus)' },
  { label: 'Converts Setbacks Into Fuel', weight: 1, tier: 'D-', score: 20, color: 'var(--tier-d-minus)' },
  { label: 'Stamina Now Considered a Superpower Locally', weight: 1, tier: 'D-', score: 20, color: 'var(--tier-d-minus)' },
  { label: 'Fatigue Files Have No Entry', weight: 1, tier: 'D-', score: 20, color: 'var(--tier-d-minus)' },
  { label: 'Energy Output Consistent at All Hours', weight: 1, tier: 'D-', score: 20, color: 'var(--tier-d-minus)' },
  { label: 'Still Going When Machines Have Stopped', weight: 1, tier: 'D-', score: 20, color: 'var(--tier-d-minus)' },
  { label: 'Can Field Multiple Events Back-to-Back', weight: 1, tier: 'D-', score: 20, color: 'var(--tier-d-minus)' },
  { label: 'Rest Happens By Choice, Not Necessity', weight: 1, tier: 'D-', score: 20, color: 'var(--tier-d-minus)' },
  { label: 'Treats 72-Hour Sessions as "Short Runs"', weight: 1, tier: 'D-', score: 20, color: 'var(--tier-d-minus)' },

  // D (score: 23)
  { label: 'Energy Without Limit', weight: 1, tier: 'D', score: 23, color: 'var(--tier-d)' },
  { label: 'Biological Fatigue Appears Suspended', weight: 1, tier: 'D', score: 23, color: 'var(--tier-d)' },
  { label: 'Has Outlasted Nations in Endurance Events', weight: 1, tier: 'D', score: 23, color: 'var(--tier-d)' },
  { label: 'Operates Without Sleep for Weeks Measurably', weight: 1, tier: 'D', score: 23, color: 'var(--tier-d)' },
  { label: 'Energy Level: Beyond Clinical Scale', weight: 1, tier: 'D', score: 23, color: 'var(--tier-d)' },
  { label: 'Opponents Tired Watching Them Warm Up', weight: 1, tier: 'D', score: 23, color: 'var(--tier-d)' },
  { label: 'Vitality That Unsettles Biologists', weight: 1, tier: 'D', score: 23, color: 'var(--tier-d)' },
  { label: 'Never Runs Out — Even Theoretically', weight: 1, tier: 'D', score: 23, color: 'var(--tier-d)' },
  { label: 'Output Doesn\'t Drop — It Accelerates', weight: 1, tier: 'D', score: 23, color: 'var(--tier-d)' },
  { label: 'Wins by Outlasting Everything Else', weight: 1, tier: 'D', score: 23, color: 'var(--tier-d)' },
  { label: 'Causes Machines to Give Out Before Them', weight: 1, tier: 'D', score: 23, color: 'var(--tier-d)' },
  { label: 'Stamina: Registered Impossible', weight: 1, tier: 'D', score: 23, color: 'var(--tier-d)' },
  { label: 'Doesn\'t Slow Down — Speeds Up Under Duress', weight: 1, tier: 'D', score: 23, color: 'var(--tier-d)' },
  { label: 'Energy Field Palpable to Observers', weight: 1, tier: 'D', score: 23, color: 'var(--tier-d)' },
  { label: 'Considered a Battery by the Scientific Community', weight: 1, tier: 'D', score: 23, color: 'var(--tier-d)' },
  { label: 'Fatigue Timeline: "Not Applicable"', weight: 1, tier: 'D', score: 23, color: 'var(--tier-d)' },
  { label: 'Rest Is a Hobby, Not a Requirement', weight: 1, tier: 'D', score: 23, color: 'var(--tier-d)' },
  { label: 'Energy At Max Even After Extraordinary Output', weight: 1, tier: 'D', score: 23, color: 'var(--tier-d)' },
  { label: 'Has Outpaced Every Endurance Record Available', weight: 1, tier: 'D', score: 23, color: 'var(--tier-d)' },
  { label: 'Runs on Something Other Than Food or Rest', weight: 1, tier: 'D', score: 23, color: 'var(--tier-d)' },

  // D+ (score: 26)
  { label: 'Perpetual Energy Source', weight: 1, tier: 'D+', score: 26, color: 'var(--tier-d-plus)' },
  { label: 'Has Kept Going for Days Without Biological Consequences', weight: 1, tier: 'D+', score: 26, color: 'var(--tier-d-plus)' },
  { label: 'Energy That Defies Nutritional Logic', weight: 1, tier: 'D+', score: 26, color: 'var(--tier-d-plus)' },
  { label: 'Energizes Areas by Being Present', weight: 1, tier: 'D+', score: 26, color: 'var(--tier-d-plus)' },
  { label: 'Sleep Does Not Appear to Be Required', weight: 1, tier: 'D+', score: 26, color: 'var(--tier-d-plus)' },
  { label: 'Vitality Registers as Cosmic Class', weight: 1, tier: 'D+', score: 26, color: 'var(--tier-d-plus)' },
  { label: 'Challenges the Concept of Burnout by Not Experiencing It', weight: 1, tier: 'D+', score: 26, color: 'var(--tier-d-plus)' },
  { label: 'Still at 100% After Others Are at 5%', weight: 1, tier: 'D+', score: 26, color: 'var(--tier-d-plus)' },
  { label: 'Sustained Energy Causes Awe Among Witnesses', weight: 1, tier: 'D+', score: 26, color: 'var(--tier-d-plus)' },
  { label: 'Output Rate Defies Thermodynamics', weight: 1, tier: 'D+', score: 26, color: 'var(--tier-d-plus)' },
  { label: 'Running on Something Not Yet Named by Science', weight: 1, tier: 'D+', score: 26, color: 'var(--tier-d-plus)' },
  { label: 'Energy: Self-Replenishing Without Inputs', weight: 1, tier: 'D+', score: 26, color: 'var(--tier-d-plus)' },
  { label: 'Has Not Experienced Depletion in Living Memory', weight: 1, tier: 'D+', score: 26, color: 'var(--tier-d-plus)' },
  { label: 'Vitality That Makes Researchers Curious and Nervous', weight: 1, tier: 'D+', score: 26, color: 'var(--tier-d-plus)' },
  { label: 'Could Run Power Grids if Harnessed', weight: 1, tier: 'D+', score: 26, color: 'var(--tier-d-plus)' },
  { label: 'Never Slows; Never Stops; Never Falters', weight: 1, tier: 'D+', score: 26, color: 'var(--tier-d-plus)' },
  { label: 'Endurance Beyond All Known Athletic Standards', weight: 1, tier: 'D+', score: 26, color: 'var(--tier-d-plus)' },
  { label: 'The Battery That Will Not Die', weight: 1, tier: 'D+', score: 26, color: 'var(--tier-d-plus)' },
  { label: 'Energy Sustains Even After Sustaining Is Impossible', weight: 1, tier: 'D+', score: 26, color: 'var(--tier-d-plus)' },
  { label: 'Has Outlasted Every Challenge Given', weight: 1, tier: 'D+', score: 26, color: 'var(--tier-d-plus)' },

  // C- (score: 30)
  { label: 'Self-Sustaining Vitality', weight: 1, tier: 'C-', score: 30, color: 'var(--tier-c-minus)' },
  { label: 'Energy That Creates More Energy', weight: 1, tier: 'C-', score: 30, color: 'var(--tier-c-minus)' },
  { label: 'Operates at Maximum Without External Support', weight: 1, tier: 'C-', score: 30, color: 'var(--tier-c-minus)' },
  { label: 'Has Outlasted Time-Based Records', weight: 1, tier: 'C-', score: 30, color: 'var(--tier-c-minus)' },
  { label: 'Metabolic System Works Like a Fusion Reactor', weight: 1, tier: 'C-', score: 30, color: 'var(--tier-c-minus)' },
  { label: 'Not Fatigued — Not Even During Record-Breaking Runs', weight: 1, tier: 'C-', score: 30, color: 'var(--tier-c-minus)' },
  { label: 'Energy That Warps Surrounding Energy Fields', weight: 1, tier: 'C-', score: 30, color: 'var(--tier-c-minus)' },
  { label: 'Operates Without Sleep, Food, or Rest — Functionally', weight: 1, tier: 'C-', score: 30, color: 'var(--tier-c-minus)' },
  { label: 'Vitality Visible to Observers at Distance', weight: 1, tier: 'C-', score: 30, color: 'var(--tier-c-minus)' },
  { label: 'Energy Output Has Never Declined in Recorded Sessions', weight: 1, tier: 'C-', score: 30, color: 'var(--tier-c-minus)' },
  { label: 'Powers Both Themselves and Nearby Equipment', weight: 1, tier: 'C-', score: 30, color: 'var(--tier-c-minus)' },
  { label: 'Has Not Slept in Days — Medical Staff Mystified', weight: 1, tier: 'C-', score: 30, color: 'var(--tier-c-minus)' },
  { label: 'Measured in Weeks of Sustained Output', weight: 1, tier: 'C-', score: 30, color: 'var(--tier-c-minus)' },
  { label: 'Fatigue Laws Do Not Apply Here', weight: 1, tier: 'C-', score: 30, color: 'var(--tier-c-minus)' },
  { label: 'Vitality: Bright Enough to Read By', weight: 1, tier: 'C-', score: 30, color: 'var(--tier-c-minus)' },
  { label: 'Every Session Ends Before They Do', weight: 1, tier: 'C-', score: 30, color: 'var(--tier-c-minus)' },
  { label: 'Energy Is Now a Local Environmental Feature', weight: 1, tier: 'C-', score: 30, color: 'var(--tier-c-minus)' },
  { label: 'Sleep Was Once Tried — No Longer Necessary', weight: 1, tier: 'C-', score: 30, color: 'var(--tier-c-minus)' },
  { label: 'Outlasted All Events Available to Enter', weight: 1, tier: 'C-', score: 30, color: 'var(--tier-c-minus)' },
  { label: 'Runs Hotter the Longer They Go', weight: 1, tier: 'C-', score: 30, color: 'var(--tier-c-minus)' },

  // C (score: 34)
  { label: 'Radiant Vitality', weight: 1, tier: 'C', score: 34, color: 'var(--tier-c)' },
  { label: 'Powers Others in Proximity', weight: 1, tier: 'C', score: 34, color: 'var(--tier-c)' },
  { label: 'Runs for Weeks Without Measurable Fatigue', weight: 1, tier: 'C', score: 34, color: 'var(--tier-c)' },
  { label: 'Has Outlasted Military Endurance Tests', weight: 1, tier: 'C', score: 34, color: 'var(--tier-c)' },
  { label: 'Stamina: Registered as Phenomenon', weight: 1, tier: 'C', score: 34, color: 'var(--tier-c)' },
  { label: 'Energy Signature Detectable at Range', weight: 1, tier: 'C', score: 34, color: 'var(--tier-c)' },
  { label: 'Vitality Output Recharges the Surrounding Area', weight: 1, tier: 'C', score: 34, color: 'var(--tier-c)' },
  { label: 'Has Redefined What "Full Energy" Means', weight: 1, tier: 'C', score: 34, color: 'var(--tier-c)' },
  { label: 'Never Below 95% — Not Measurably', weight: 1, tier: 'C', score: 34, color: 'var(--tier-c)' },
  { label: 'Warmth and Light Generated Passively', weight: 1, tier: 'C', score: 34, color: 'var(--tier-c)' },
  { label: 'Functions at Full Capacity Without Needs Being Met', weight: 1, tier: 'C', score: 34, color: 'var(--tier-c)' },
  { label: 'Outlasted Automated Systems', weight: 1, tier: 'C', score: 34, color: 'var(--tier-c)' },
  { label: 'Output Creates Local Power Fluctuations', weight: 1, tier: 'C', score: 34, color: 'var(--tier-c)' },
  { label: 'Energetic to the Point of Being Hazardous', weight: 1, tier: 'C', score: 34, color: 'var(--tier-c)' },
  { label: 'Has Never Slept — Doctors Called It "A Situation"', weight: 1, tier: 'C', score: 34, color: 'var(--tier-c)' },
  { label: 'Body Generates Power Without Input', weight: 1, tier: 'C', score: 34, color: 'var(--tier-c)' },
  { label: 'Energy Visually Apparent to the Naked Eye', weight: 1, tier: 'C', score: 34, color: 'var(--tier-c)' },
  { label: 'Fatigue: Only Appears in Biographies', weight: 1, tier: 'C', score: 34, color: 'var(--tier-c)' },
  { label: 'The Room Gets Brighter When They Arrive', weight: 1, tier: 'C', score: 34, color: 'var(--tier-c)' },
  { label: 'Sustained Peak Output: Months', weight: 1, tier: 'C', score: 34, color: 'var(--tier-c)' },

  // C+ (score: 38)
  { label: 'Infinite Stamina (Basically)', weight: 1, tier: 'C+', score: 38, color: 'var(--tier-c-plus)' },
  { label: 'Energy: Eternal and Brightening', weight: 1, tier: 'C+', score: 38, color: 'var(--tier-c-plus)' },
  { label: 'Lives in a State of Perpetual Readiness', weight: 1, tier: 'C+', score: 38, color: 'var(--tier-c-plus)' },
  { label: 'Has Never Approached Depletion', weight: 1, tier: 'C+', score: 38, color: 'var(--tier-c-plus)' },
  { label: 'Vitality Is Measurable From Space', weight: 1, tier: 'C+', score: 38, color: 'var(--tier-c-plus)' },
  { label: 'Generates Energy Passively While Idle', weight: 1, tier: 'C+', score: 38, color: 'var(--tier-c-plus)' },
  { label: 'Energy Output Disrupts Local Electronics', weight: 1, tier: 'C+', score: 38, color: 'var(--tier-c-plus)' },
  { label: 'Runs on a Power Source Not Yet Identified', weight: 1, tier: 'C+', score: 38, color: 'var(--tier-c-plus)' },
  { label: 'Body Doesn\'t Convert Energy — It Creates It', weight: 1, tier: 'C+', score: 38, color: 'var(--tier-c-plus)' },
  { label: 'Maximum Output: Always. No Exceptions.', weight: 1, tier: 'C+', score: 38, color: 'var(--tier-c-plus)' },
  { label: 'Vitality Field Extends Beyond Their Body', weight: 1, tier: 'C+', score: 38, color: 'var(--tier-c-plus)' },
  { label: 'Sleep No Longer a Variable in Their Function', weight: 1, tier: 'C+', score: 38, color: 'var(--tier-c-plus)' },
  { label: 'Has Outlasted Simulated Environments Designed to Exhaust Them', weight: 1, tier: 'C+', score: 38, color: 'var(--tier-c-plus)' },
  { label: 'Physically Exhausts Observers by Proxy', weight: 1, tier: 'C+', score: 38, color: 'var(--tier-c-plus)' },
  { label: 'Power Generation Exceeds Metabolic Explanation', weight: 1, tier: 'C+', score: 38, color: 'var(--tier-c-plus)' },
  { label: 'Outlasted Multiple Biomes Testing Them', weight: 1, tier: 'C+', score: 38, color: 'var(--tier-c-plus)' },
  { label: 'Energetic at Year 1 and Year 100 Equally', weight: 1, tier: 'C+', score: 38, color: 'var(--tier-c-plus)' },
  { label: 'Stamina: Something Else Entirely Now', weight: 1, tier: 'C+', score: 38, color: 'var(--tier-c-plus)' },
  { label: 'Vitality Visible as an Aura', weight: 1, tier: 'C+', score: 38, color: 'var(--tier-c-plus)' },
  { label: 'Could Power a Small Settlement Indefinitely', weight: 1, tier: 'C+', score: 38, color: 'var(--tier-c-plus)' },

  // B- (score: 42)
  { label: 'Energy Beyond Human Physiology', weight: 1, tier: 'B-', score: 42, color: 'var(--tier-b-minus)' },
  { label: 'Fatigue: A Concept Filed Under "Other People"', weight: 1, tier: 'B-', score: 42, color: 'var(--tier-b-minus)' },
  { label: 'Hasn\'t Needed Sleep Since the Last Decade', weight: 1, tier: 'B-', score: 42, color: 'var(--tier-b-minus)' },
  { label: 'Energy Signature Causes Instruments to Recalibrate', weight: 1, tier: 'B-', score: 42, color: 'var(--tier-b-minus)' },
  { label: 'Outputs More Than Their Input — Always', weight: 1, tier: 'B-', score: 42, color: 'var(--tier-b-minus)' },
  { label: 'Vitality That Defies Conservation Laws', weight: 1, tier: 'B-', score: 42, color: 'var(--tier-b-minus)' },
  { label: 'Operates Without Physical Needs — Fully', weight: 1, tier: 'B-', score: 42, color: 'var(--tier-b-minus)' },
  { label: 'Stamina Confirmed Impossible by Three Labs', weight: 1, tier: 'B-', score: 42, color: 'var(--tier-b-minus)' },
  { label: 'Energy Has Become a Measurable Atmospheric Effect', weight: 1, tier: 'B-', score: 42, color: 'var(--tier-b-minus)' },
  { label: 'Could Run a City Indefinitely', weight: 1, tier: 'B-', score: 42, color: 'var(--tier-b-minus)' },
  { label: 'No Depletion in Any Simulation', weight: 1, tier: 'B-', score: 42, color: 'var(--tier-b-minus)' },
  { label: 'Operates Beyond Thermal Limits of Normal Bodies', weight: 1, tier: 'B-', score: 42, color: 'var(--tier-b-minus)' },
  { label: 'Still at Full Output After Months on Record', weight: 1, tier: 'B-', score: 42, color: 'var(--tier-b-minus)' },
  { label: 'Their Idle State Powers Things Nearby', weight: 1, tier: 'B-', score: 42, color: 'var(--tier-b-minus)' },
  { label: 'Energy Output Registered as Celestial', weight: 1, tier: 'B-', score: 42, color: 'var(--tier-b-minus)' },
  { label: 'Faster and Stronger at Hour 1000 Than Hour 1', weight: 1, tier: 'B-', score: 42, color: 'var(--tier-b-minus)' },
  { label: 'Doesn\'t Run on Energy — They Are Energy', weight: 1, tier: 'B-', score: 42, color: 'var(--tier-b-minus)' },
  { label: 'Warmth Radiates at a Distance', weight: 1, tier: 'B-', score: 42, color: 'var(--tier-b-minus)' },
  { label: 'Outlasted All Stars They\'ve Been Near', weight: 1, tier: 'B-', score: 42, color: 'var(--tier-b-minus)' },
  { label: 'Vitality That Rearranges the Local Physics', weight: 1, tier: 'B-', score: 42, color: 'var(--tier-b-minus)' },

  // B (score: 47)
  { label: 'Cosmic-Tier Vitality', weight: 1, tier: 'B', score: 47, color: 'var(--tier-b)' },
  { label: 'Energy That Powers Entire Systems', weight: 1, tier: 'B', score: 47, color: 'var(--tier-b)' },
  { label: 'Has Been Running for Years Without Drop', weight: 1, tier: 'B', score: 47, color: 'var(--tier-b)' },
  { label: 'Could Power a Planet Casually', weight: 1, tier: 'B', score: 47, color: 'var(--tier-b)' },
  { label: 'Outputs Energy That Rivals Small Stars', weight: 1, tier: 'B', score: 47, color: 'var(--tier-b)' },
  { label: 'Vitality Is a Structural Force Now', weight: 1, tier: 'B', score: 47, color: 'var(--tier-b)' },
  { label: 'Their Rest State Equals Others\' Maximum', weight: 1, tier: 'B', score: 47, color: 'var(--tier-b)' },
  { label: 'Energy Has Gravitational Properties', weight: 1, tier: 'B', score: 47, color: 'var(--tier-b)' },
  { label: 'Stamina That Outlasts Geological Time Periods', weight: 1, tier: 'B', score: 47, color: 'var(--tier-b)' },
  { label: 'Burns Hotter, Longer, Always', weight: 1, tier: 'B', score: 47, color: 'var(--tier-b)' },
  { label: 'Fatigue Laws Don\'t Apply in Their Vicinity', weight: 1, tier: 'B', score: 47, color: 'var(--tier-b)' },
  { label: 'Energy Output Comparable to Fusion Events', weight: 1, tier: 'B', score: 47, color: 'var(--tier-b)' },
  { label: 'Has Energized Failing Stars by Proximity', weight: 1, tier: 'B', score: 47, color: 'var(--tier-b)' },
  { label: 'Vitality: Its Own Cosmological Category', weight: 1, tier: 'B', score: 47, color: 'var(--tier-b)' },
  { label: 'Can\'t Be Drained — Energy Replenishes Faster Than Lost', weight: 1, tier: 'B', score: 47, color: 'var(--tier-b)' },
  { label: 'Warmth Has Its Own Weather Pattern', weight: 1, tier: 'B', score: 47, color: 'var(--tier-b)' },
  { label: 'Stamina Unchanged Across Centuries', weight: 1, tier: 'B', score: 47, color: 'var(--tier-b)' },
  { label: 'Outlasted Every Environment Tested In', weight: 1, tier: 'B', score: 47, color: 'var(--tier-b)' },
  { label: 'Doesn\'t Use Energy — Generates Surplus', weight: 1, tier: 'B', score: 47, color: 'var(--tier-b)' },
  { label: 'Energy That Has Never Once Decreased', weight: 1, tier: 'B', score: 47, color: 'var(--tier-b)' },

  // B+ (score: 52)
  { label: 'Stellar-Level Energy Output', weight: 1, tier: 'B+', score: 52, color: 'var(--tier-b-plus)' },
  { label: 'Stamina Measured in Eons', weight: 1, tier: 'B+', score: 52, color: 'var(--tier-b-plus)' },
  { label: 'Vitality Has Outlasted Multiple Cosmic Cycles', weight: 1, tier: 'B+', score: 52, color: 'var(--tier-b-plus)' },
  { label: 'Energy Field Affecting Adjacent Universes', weight: 1, tier: 'B+', score: 52, color: 'var(--tier-b-plus)' },
  { label: 'Could Power a Small Galaxy on Request', weight: 1, tier: 'B+', score: 52, color: 'var(--tier-b-plus)' },
  { label: 'Vitality That Stars Aspire To', weight: 1, tier: 'B+', score: 52, color: 'var(--tier-b-plus)' },
  { label: 'Output Self-Amplifies the More It\'s Needed', weight: 1, tier: 'B+', score: 52, color: 'var(--tier-b-plus)' },
  { label: 'Energy Signature Detected Across Dimensions', weight: 1, tier: 'B+', score: 52, color: 'var(--tier-b-plus)' },
  { label: 'Stamina Has Replaced Needing Things', weight: 1, tier: 'B+', score: 52, color: 'var(--tier-b-plus)' },
  { label: 'Has Never Rested — Not Once — Not a Dip', weight: 1, tier: 'B+', score: 52, color: 'var(--tier-b-plus)' },
  { label: 'Energy Restores Surrounding Environments', weight: 1, tier: 'B+', score: 52, color: 'var(--tier-b-plus)' },
  { label: 'Vitality Visible From Space as Light', weight: 1, tier: 'B+', score: 52, color: 'var(--tier-b-plus)' },
  { label: 'Doesn\'t Expire — Doesn\'t Deplete — Continues', weight: 1, tier: 'B+', score: 52, color: 'var(--tier-b-plus)' },
  { label: 'Outlasted Every Known Source of Power', weight: 1, tier: 'B+', score: 52, color: 'var(--tier-b-plus)' },
  { label: 'Energy Functions as a Localized Radiation Source', weight: 1, tier: 'B+', score: 52, color: 'var(--tier-b-plus)' },
  { label: 'Stamina Unaffected by Time, Distance, or Entropy', weight: 1, tier: 'B+', score: 52, color: 'var(--tier-b-plus)' },
  { label: 'Vitality Feeds Everything in Their Vicinity', weight: 1, tier: 'B+', score: 52, color: 'var(--tier-b-plus)' },
  { label: 'Has Outlasted the Heat Death in a Local Test', weight: 1, tier: 'B+', score: 52, color: 'var(--tier-b-plus)' },
  { label: 'Energy Grows the Longer the Session Lasts', weight: 1, tier: 'B+', score: 52, color: 'var(--tier-b-plus)' },
  { label: 'Could Charge a Dead Star — Has Done It', weight: 1, tier: 'B+', score: 52, color: 'var(--tier-b-plus)' },

  // A- (score: 57)
  { label: 'Infinite and Self-Sustaining', weight: 1, tier: 'A-', score: 57, color: 'var(--tier-a-minus)' },
  { label: 'Energy Outlasts Civilizations', weight: 1, tier: 'A-', score: 57, color: 'var(--tier-a-minus)' },
  { label: 'Vitality Has Revitalized Dead Systems', weight: 1, tier: 'A-', score: 57, color: 'var(--tier-a-minus)' },
  { label: 'Output Sufficient to Power Galaxies', weight: 1, tier: 'A-', score: 57, color: 'var(--tier-a-minus)' },
  { label: 'Energy Exists Beyond Entropy\'s Reach', weight: 1, tier: 'A-', score: 57, color: 'var(--tier-a-minus)' },
  { label: 'Has Been Going Since Before the Universe Cooled', weight: 1, tier: 'A-', score: 57, color: 'var(--tier-a-minus)' },
  { label: 'Fatigue Is a Myth They\'ve Disproved Personally', weight: 1, tier: 'A-', score: 57, color: 'var(--tier-a-minus)' },
  { label: 'Stamina Unchanged Across Millennia', weight: 1, tier: 'A-', score: 57, color: 'var(--tier-a-minus)' },
  { label: 'Energy Field Detectable From Other Universes', weight: 1, tier: 'A-', score: 57, color: 'var(--tier-a-minus)' },
  { label: 'Vitality That Acts as a Local Star', weight: 1, tier: 'A-', score: 57, color: 'var(--tier-a-minus)' },
  { label: 'Output Accelerates as Duration Increases', weight: 1, tier: 'A-', score: 57, color: 'var(--tier-a-minus)' },
  { label: 'Replenishes Dying Systems With Spare Vitality', weight: 1, tier: 'A-', score: 57, color: 'var(--tier-a-minus)' },
  { label: 'Can\'t Be Drained — Energy Fights Back', weight: 1, tier: 'A-', score: 57, color: 'var(--tier-a-minus)' },
  { label: 'Never Below Maximum — Per Every Recording', weight: 1, tier: 'A-', score: 57, color: 'var(--tier-a-minus)' },
  { label: 'Energy Level: Described as "A Problem"', weight: 1, tier: 'A-', score: 57, color: 'var(--tier-a-minus)' },
  { label: 'Stamina That Reverses Entropy Locally', weight: 1, tier: 'A-', score: 57, color: 'var(--tier-a-minus)' },
  { label: 'Vitality Visible as Visible Light to Observers', weight: 1, tier: 'A-', score: 57, color: 'var(--tier-a-minus)' },
  { label: 'Outlasted Every Recorded Cosmic Event', weight: 1, tier: 'A-', score: 57, color: 'var(--tier-a-minus)' },
  { label: 'Energy Is a Natural Law Around Them', weight: 1, tier: 'A-', score: 57, color: 'var(--tier-a-minus)' },
  { label: 'Has Never Not Been at Full Power', weight: 1, tier: 'A-', score: 57, color: 'var(--tier-a-minus)' },

  // A (score: 62)
  { label: 'Omniversal Energy Source', weight: 1, tier: 'A', score: 62, color: 'var(--tier-a)' },
  { label: 'Their Vitality Has Powered Entire Epochs', weight: 1, tier: 'A', score: 62, color: 'var(--tier-a)' },
  { label: 'Stamina That Outlasts Heat Death Scenarios', weight: 1, tier: 'A', score: 62, color: 'var(--tier-a)' },
  { label: 'Energy That Regenerates What It Exhausts', weight: 1, tier: 'A', score: 62, color: 'var(--tier-a)' },
  { label: 'Generates Energy Faster Than It Can Be Used', weight: 1, tier: 'A', score: 62, color: 'var(--tier-a)' },
  { label: 'Output Rivals Galaxies in Energy Density', weight: 1, tier: 'A', score: 62, color: 'var(--tier-a)' },
  { label: 'Vitality Exists as Its Own Dimensional Phenomenon', weight: 1, tier: 'A', score: 62, color: 'var(--tier-a)' },
  { label: 'Still at Maximum After the Current Universe\'s Age', weight: 1, tier: 'A', score: 62, color: 'var(--tier-a)' },
  { label: 'Energy That Prevents Entropy in Surrounding Space', weight: 1, tier: 'A', score: 62, color: 'var(--tier-a)' },
  { label: 'Has Never Needed Anything — Energy Is Self-Born', weight: 1, tier: 'A', score: 62, color: 'var(--tier-a)' },
  { label: 'Outlasted All Known Concepts of Duration', weight: 1, tier: 'A', score: 62, color: 'var(--tier-a)' },
  { label: 'Vitality Generates Its Own Laws', weight: 1, tier: 'A', score: 62, color: 'var(--tier-a)' },
  { label: 'Energy Field Has Its Own Gravitational Signature', weight: 1, tier: 'A', score: 62, color: 'var(--tier-a)' },
  { label: 'Fatigue Has No Pathway Into Their Biology', weight: 1, tier: 'A', score: 62, color: 'var(--tier-a)' },
  { label: 'Energy Has Always Been at This Level — No Building Required', weight: 1, tier: 'A', score: 62, color: 'var(--tier-a)' },
  { label: 'Stamina Archived as Cosmological Event', weight: 1, tier: 'A', score: 62, color: 'var(--tier-a)' },
  { label: 'Vitality Sustains Entire Realities Nearby', weight: 1, tier: 'A', score: 62, color: 'var(--tier-a)' },
  { label: 'Runs Hotter than Stars — Indefinitely', weight: 1, tier: 'A', score: 62, color: 'var(--tier-a)' },
  { label: 'Has No Energy Limit in Any Dimensional Recording', weight: 1, tier: 'A', score: 62, color: 'var(--tier-a)' },
  { label: 'Doesn\'t Need Energy — Is Energy', weight: 1, tier: 'A', score: 62, color: 'var(--tier-a)' },

  // A+ (score: 67)
  { label: 'Pre-Universal Vitality', weight: 1, tier: 'A+', score: 67, color: 'var(--tier-a-plus)' },
  { label: 'Energy That Seeded the Current Universe', weight: 1, tier: 'A+', score: 67, color: 'var(--tier-a-plus)' },
  { label: 'Vitality Predates All Known Cosmological Events', weight: 1, tier: 'A+', score: 67, color: 'var(--tier-a-plus)' },
  { label: 'Stamina That Outlasts the Concept of Time', weight: 1, tier: 'A+', score: 67, color: 'var(--tier-a-plus)' },
  { label: 'Output That Rebooted a Dying Galaxy — Casually', weight: 1, tier: 'A+', score: 67, color: 'var(--tier-a-plus)' },
  { label: 'Energy Never Measured; Instruments Gave Up', weight: 1, tier: 'A+', score: 67, color: 'var(--tier-a-plus)' },
  { label: 'Generates Life Energy in Adjacent Biomes', weight: 1, tier: 'A+', score: 67, color: 'var(--tier-a-plus)' },
  { label: 'Vitality That Persists After All Physical Laws Fail', weight: 1, tier: 'A+', score: 67, color: 'var(--tier-a-plus)' },
  { label: 'Their Energy Makes Nearby Entities More Alive', weight: 1, tier: 'A+', score: 67, color: 'var(--tier-a-plus)' },
  { label: 'Has Been at Full Power Since Before Time Started', weight: 1, tier: 'A+', score: 67, color: 'var(--tier-a-plus)' },
  { label: 'Stamina That Exceeds the Lifespan of All Known Suns', weight: 1, tier: 'A+', score: 67, color: 'var(--tier-a-plus)' },
  { label: 'Energy Level Fixed at "Maximum" Since Origin', weight: 1, tier: 'A+', score: 67, color: 'var(--tier-a-plus)' },
  { label: 'Vitality That Is Older Than the Concept of Fatigue', weight: 1, tier: 'A+', score: 67, color: 'var(--tier-a-plus)' },
  { label: 'Has Powered Through Events That Ended Galaxies', weight: 1, tier: 'A+', score: 67, color: 'var(--tier-a-plus)' },
  { label: 'Energy Output Is a Cosmological Constant', weight: 1, tier: 'A+', score: 67, color: 'var(--tier-a-plus)' },
  { label: 'Still Running at Full After Every Known Epoch', weight: 1, tier: 'A+', score: 67, color: 'var(--tier-a-plus)' },
  { label: 'Fatigue: Filed as Non-Applicable Before Birth', weight: 1, tier: 'A+', score: 67, color: 'var(--tier-a-plus)' },
  { label: 'Vitality That Outlasted Pre-Existence', weight: 1, tier: 'A+', score: 67, color: 'var(--tier-a-plus)' },
  { label: 'Energy Density Greater Than Singularity Events', weight: 1, tier: 'A+', score: 67, color: 'var(--tier-a-plus)' },
  { label: 'The Living Power Source of the Omniverse', weight: 1, tier: 'A+', score: 67, color: 'var(--tier-a-plus)' },

  // S- (score: 72)
  { label: 'Omniversal Energy Constant', weight: 1, tier: 'S-', score: 72, color: 'var(--tier-s-minus)' },
  { label: 'Vitality That Predates Pre-Time', weight: 1, tier: 'S-', score: 72, color: 'var(--tier-s-minus)' },
  { label: 'Energy Stronger Than the Laws That Govern It', weight: 1, tier: 'S-', score: 72, color: 'var(--tier-s-minus)' },
  { label: 'Has Never Not Been at Full Power — Ever', weight: 1, tier: 'S-', score: 72, color: 'var(--tier-s-minus)' },
  { label: 'Stamina That Powers Multiversal Systems', weight: 1, tier: 'S-', score: 72, color: 'var(--tier-s-minus)' },
  { label: 'Fueled Everything That Burns — Still Burning', weight: 1, tier: 'S-', score: 72, color: 'var(--tier-s-minus)' },
  { label: 'Energy Cannot Be Measured Without Causing a Problem', weight: 1, tier: 'S-', score: 72, color: 'var(--tier-s-minus)' },
  { label: 'Vitality Sustains Adjacent Dimensions', weight: 1, tier: 'S-', score: 72, color: 'var(--tier-s-minus)' },
  { label: 'Still Going After Every Universe Has Ended and Reformed', weight: 1, tier: 'S-', score: 72, color: 'var(--tier-s-minus)' },
  { label: 'Energy Field Is Now a Feature of Local Spacetime', weight: 1, tier: 'S-', score: 72, color: 'var(--tier-s-minus)' },
  { label: 'Has Made Failing Stars Live Again', weight: 1, tier: 'S-', score: 72, color: 'var(--tier-s-minus)' },
  { label: 'Stamina Operates Across Dimensional Boundaries', weight: 1, tier: 'S-', score: 72, color: 'var(--tier-s-minus)' },
  { label: 'Energy Output Never Recorded — Too Fast to Track', weight: 1, tier: 'S-', score: 72, color: 'var(--tier-s-minus)' },
  { label: 'Vitality That Brightens Surrounding Systems', weight: 1, tier: 'S-', score: 72, color: 'var(--tier-s-minus)' },
  { label: 'Outlasted the Last Universe Before This One', weight: 1, tier: 'S-', score: 72, color: 'var(--tier-s-minus)' },
  { label: 'Hasn\'t Stopped Running Since the First Moment', weight: 1, tier: 'S-', score: 72, color: 'var(--tier-s-minus)' },
  { label: 'Energy That Is Self-Generating at Infinite Rate', weight: 1, tier: 'S-', score: 72, color: 'var(--tier-s-minus)' },
  { label: 'Fatigue Has Never Had a Route to Them', weight: 1, tier: 'S-', score: 72, color: 'var(--tier-s-minus)' },
  { label: 'Stamina That Precedes the Concept of Time', weight: 1, tier: 'S-', score: 72, color: 'var(--tier-s-minus)' },
  { label: 'Exists at Full Vitality — Always — Across All Time', weight: 1, tier: 'S-', score: 72, color: 'var(--tier-s-minus)' },

  // S (score: 77)
  { label: 'The Living Engine', weight: 1, tier: 'S', score: 77, color: 'var(--tier-s)' },
  { label: 'Energy That Fuels the Omniverse', weight: 1, tier: 'S', score: 77, color: 'var(--tier-s)' },
  { label: 'Has Been Running Since Before Anything Else Existed', weight: 1, tier: 'S', score: 77, color: 'var(--tier-s)' },
  { label: 'Vitality That Was Here Before Physics', weight: 1, tier: 'S', score: 77, color: 'var(--tier-s)' },
  { label: 'Stamina That Outlasts Every Conceivable Duration', weight: 1, tier: 'S', score: 77, color: 'var(--tier-s)' },
  { label: 'The Only Energy Source That Cannot Be Extinguished', weight: 1, tier: 'S', score: 77, color: 'var(--tier-s)' },
  { label: 'Energy Powers Adjacent Universes Passively', weight: 1, tier: 'S', score: 77, color: 'var(--tier-s)' },
  { label: 'Still At Full Power After the Omniverse Ended', weight: 1, tier: 'S', score: 77, color: 'var(--tier-s)' },
  { label: 'Vitality That Replenishes What Was Lost Across Eons', weight: 1, tier: 'S', score: 77, color: 'var(--tier-s)' },
  { label: 'Has Outlasted Every Known Fuel Source in the Omniverse', weight: 1, tier: 'S', score: 77, color: 'var(--tier-s)' },
  { label: 'Energy Is the First and Last Thing in Any System', weight: 1, tier: 'S', score: 77, color: 'var(--tier-s)' },
  { label: 'Running Before Time Knew What Running Was', weight: 1, tier: 'S', score: 77, color: 'var(--tier-s)' },
  { label: 'Vitality That Makes Dead Things Stir Again', weight: 1, tier: 'S', score: 77, color: 'var(--tier-s)' },
  { label: 'Stamina: Eternally Constant Across All Omniverses', weight: 1, tier: 'S', score: 77, color: 'var(--tier-s)' },
  { label: 'Energy Flows Into Everything They Touch', weight: 1, tier: 'S', score: 77, color: 'var(--tier-s)' },
  { label: 'Fatigue Would Have to Be Invented For Them — Not Worth It', weight: 1, tier: 'S', score: 77, color: 'var(--tier-s)' },
  { label: 'Fueled the First Stars Indirectly', weight: 1, tier: 'S', score: 77, color: 'var(--tier-s)' },
  { label: 'Vitality Outlasts Its Own Meaning', weight: 1, tier: 'S', score: 77, color: 'var(--tier-s)' },
  { label: 'Their Presence Revives What Was Dying', weight: 1, tier: 'S', score: 77, color: 'var(--tier-s)' },
  { label: 'The Endless Battery — No Qualifier, No Limit', weight: 1, tier: 'S', score: 77, color: 'var(--tier-s)' },

  // S+ (score: 81)
  { label: 'Omniversal Prime Vitality', weight: 1, tier: 'S+', score: 81, color: 'var(--tier-s-plus)' },
  { label: 'Energy That Has Outlasted Every Concept of Ending', weight: 1, tier: 'S+', score: 81, color: 'var(--tier-s-plus)' },
  { label: 'Stamina: Infinite. Confirmed. No Exceptions.', weight: 1, tier: 'S+', score: 81, color: 'var(--tier-s-plus)' },
  { label: 'Vitality That Predates Pre-Existence', weight: 1, tier: 'S+', score: 81, color: 'var(--tier-s-plus)' },
  { label: 'Their Vitality Created the Laws That Define Energy', weight: 1, tier: 'S+', score: 81, color: 'var(--tier-s-plus)' },
  { label: 'Was Running Before There Was Anywhere to Run', weight: 1, tier: 'S+', score: 81, color: 'var(--tier-s-plus)' },
  { label: 'Stamina Unaffected by Any Condition Ever Recorded', weight: 1, tier: 'S+', score: 81, color: 'var(--tier-s-plus)' },
  { label: 'Energy That Self-Perpetuates Across Infinite Cycles', weight: 1, tier: 'S+', score: 81, color: 'var(--tier-s-plus)' },
  { label: 'Has Powered Through the Death of All Suns', weight: 1, tier: 'S+', score: 81, color: 'var(--tier-s-plus)' },
  { label: 'Vitality That Has Never Once Flickered', weight: 1, tier: 'S+', score: 81, color: 'var(--tier-s-plus)' },
  { label: 'Their Energy Is the Ambient Background of the Omniverse', weight: 1, tier: 'S+', score: 81, color: 'var(--tier-s-plus)' },
  { label: 'Doesn\'t Spend Energy — Generates More as Overhead', weight: 1, tier: 'S+', score: 81, color: 'var(--tier-s-plus)' },
  { label: 'Has Revived Entire Universal Systems Accidentally', weight: 1, tier: 'S+', score: 81, color: 'var(--tier-s-plus)' },
  { label: 'Still Burning at Pre-Creation Intensity', weight: 1, tier: 'S+', score: 81, color: 'var(--tier-s-plus)' },
  { label: 'Vitality Is a Feature of All Possible Realities', weight: 1, tier: 'S+', score: 81, color: 'var(--tier-s-plus)' },
  { label: 'Energy Outlasts Entropy — By Every Measurement', weight: 1, tier: 'S+', score: 81, color: 'var(--tier-s-plus)' },
  { label: 'Stamina That Seeded the Concept of Duration', weight: 1, tier: 'S+', score: 81, color: 'var(--tier-s-plus)' },
  { label: 'Running Since Before Running Was a Word', weight: 1, tier: 'S+', score: 81, color: 'var(--tier-s-plus)' },
  { label: 'Energy Reverts Entropy Across the Omniverse', weight: 1, tier: 'S+', score: 81, color: 'var(--tier-s-plus)' },
  { label: 'The Most Energetic Entity Across All Omniverses', weight: 1, tier: 'S+', score: 81, color: 'var(--tier-s-plus)' },

  // SS- (score: 85)
  { label: 'Absolute Vitality', weight: 1, tier: 'SS-', score: 85, color: 'var(--tier-ss-minus)' },
  { label: 'Energy That Existed Before Existence', weight: 1, tier: 'SS-', score: 85, color: 'var(--tier-ss-minus)' },
  { label: 'Powers the Entire Omniverse as a Passive Effect', weight: 1, tier: 'SS-', score: 85, color: 'var(--tier-ss-minus)' },
  { label: 'Stamina Cannot Be Exhausted — It Has Been Confirmed', weight: 1, tier: 'SS-', score: 85, color: 'var(--tier-ss-minus)' },
  { label: 'Vitality That Pre-Dates Physical Law', weight: 1, tier: 'SS-', score: 85, color: 'var(--tier-ss-minus)' },
  { label: 'Has Kept Going Through Every End of Every Universe', weight: 1, tier: 'SS-', score: 85, color: 'var(--tier-ss-minus)' },
  { label: 'Energy Creates Energy Without Source', weight: 1, tier: 'SS-', score: 85, color: 'var(--tier-ss-minus)' },
  { label: 'Their Energy Is What Made Fuel Possible', weight: 1, tier: 'SS-', score: 85, color: 'var(--tier-ss-minus)' },
  { label: 'Stamina That Gave Rise to the Concept of Time', weight: 1, tier: 'SS-', score: 85, color: 'var(--tier-ss-minus)' },
  { label: 'Has Never Had Less Than Full Vitality — Not Once', weight: 1, tier: 'SS-', score: 85, color: 'var(--tier-ss-minus)' },
  { label: 'Energy: The Omniversal Background Radiation Has Their Signature', weight: 1, tier: 'SS-', score: 85, color: 'var(--tier-ss-minus)' },
  { label: 'Outlasted Every Possible Ending of Everything', weight: 1, tier: 'SS-', score: 85, color: 'var(--tier-ss-minus)' },
  { label: 'Vitality Sustains What Would Die Without It', weight: 1, tier: 'SS-', score: 85, color: 'var(--tier-ss-minus)' },
  { label: 'Energy Amplitude: Omniversal Constant', weight: 1, tier: 'SS-', score: 85, color: 'var(--tier-ss-minus)' },
  { label: 'Still Running — Has Never Not Been Running', weight: 1, tier: 'SS-', score: 85, color: 'var(--tier-ss-minus)' },
  { label: 'Energy That Was the First Thing and Will Be the Last', weight: 1, tier: 'SS-', score: 85, color: 'var(--tier-ss-minus)' },
  { label: 'Fatigue Was Filed as Inapplicable Before Time Began', weight: 1, tier: 'SS-', score: 85, color: 'var(--tier-ss-minus)' },
  { label: 'Their Energy Level Has Never Changed — Not Even Slightly', weight: 1, tier: 'SS-', score: 85, color: 'var(--tier-ss-minus)' },
  { label: 'The Concept of Depletion Doesn\'t Know Their Name', weight: 1, tier: 'SS-', score: 85, color: 'var(--tier-ss-minus)' },
  { label: 'Stamina That Fueled the Big Bang as a Side Effect', weight: 1, tier: 'SS-', score: 85, color: 'var(--tier-ss-minus)' },

  // SS (score: 88)
  { label: 'The First Power', weight: 1, tier: 'SS', score: 88, color: 'var(--tier-ss)' },
  { label: 'Vitality That Preceded All Things', weight: 1, tier: 'SS', score: 88, color: 'var(--tier-ss)' },
  { label: 'Energy That Powers Omniversal Cycles', weight: 1, tier: 'SS', score: 88, color: 'var(--tier-ss)' },
  { label: 'Has Never, In Any Universe, Ever, Tired', weight: 1, tier: 'SS', score: 88, color: 'var(--tier-ss)' },
  { label: 'Stamina That Started Before Starting Existed', weight: 1, tier: 'SS', score: 88, color: 'var(--tier-ss)' },
  { label: 'Energy That Made All Other Energy Possible', weight: 1, tier: 'SS', score: 88, color: 'var(--tier-ss)' },
  { label: 'Vitality That Will Persist After All Things End', weight: 1, tier: 'SS', score: 88, color: 'var(--tier-ss)' },
  { label: 'Running Eternally — With Zero Sign of Slowing', weight: 1, tier: 'SS', score: 88, color: 'var(--tier-ss)' },
  { label: 'Has Powered Through Every Iteration of Reality', weight: 1, tier: 'SS', score: 88, color: 'var(--tier-ss)' },
  { label: 'Energy Level: "Infinite" Is Still Too Small a Word', weight: 1, tier: 'SS', score: 88, color: 'var(--tier-ss)' },
  { label: 'Outlasted the Omniverse — Repeatedly', weight: 1, tier: 'SS', score: 88, color: 'var(--tier-ss)' },
  { label: 'Their Energy Is What Sparked All Creation', weight: 1, tier: 'SS', score: 88, color: 'var(--tier-ss)' },
  { label: 'Fatigue Was Never a Feature of Their Design', weight: 1, tier: 'SS', score: 88, color: 'var(--tier-ss)' },
  { label: 'Has Never Approached 99% Capacity', weight: 1, tier: 'SS', score: 88, color: 'var(--tier-ss)' },
  { label: 'Vitality That Will Be Here After the Last Star Fades', weight: 1, tier: 'SS', score: 88, color: 'var(--tier-ss)' },
  { label: 'Energy Is Their Origin, Their Nature, and Their Constant', weight: 1, tier: 'SS', score: 88, color: 'var(--tier-ss)' },
  { label: 'Stamina: Built Into Pre-Cosmic Constants', weight: 1, tier: 'SS', score: 88, color: 'var(--tier-ss)' },
  { label: 'Running Before Running Was Invented — Still Running', weight: 1, tier: 'SS', score: 88, color: 'var(--tier-ss)' },
  { label: 'Energy Powers Things That Don\'t Know They Need Powering', weight: 1, tier: 'SS', score: 88, color: 'var(--tier-ss)' },
  { label: 'Omniversal Power Source — No Charge Required', weight: 1, tier: 'SS', score: 88, color: 'var(--tier-ss)' },

  // SS+ (score: 91)
  { label: 'Absolute Energy — Infinite, Eternal, Unstoppable', weight: 1, tier: 'SS+', score: 91, color: 'var(--tier-ss-plus)' },
  { label: 'Stamina That Has No Measurement System', weight: 1, tier: 'SS+', score: 91, color: 'var(--tier-ss-plus)' },
  { label: 'Vitality That Seeded Every Source of Energy in Existence', weight: 1, tier: 'SS+', score: 91, color: 'var(--tier-ss-plus)' },
  { label: 'Has Powered Things That Don\'t Exist Yet', weight: 1, tier: 'SS+', score: 91, color: 'var(--tier-ss-plus)' },
  { label: 'Running At Maximum Before the Concept of Time', weight: 1, tier: 'SS+', score: 91, color: 'var(--tier-ss-plus)' },
  { label: 'Energy That Cannot Be Conceptually Contained', weight: 1, tier: 'SS+', score: 91, color: 'var(--tier-ss-plus)' },
  { label: 'Has Never Not Been the Most Energetic Thing', weight: 1, tier: 'SS+', score: 91, color: 'var(--tier-ss-plus)' },
  { label: 'Outlasted All Possible Endings — Running Still', weight: 1, tier: 'SS+', score: 91, color: 'var(--tier-ss-plus)' },
  { label: 'Vitality That Gave Physics Its Starting Conditions', weight: 1, tier: 'SS+', score: 91, color: 'var(--tier-ss-plus)' },
  { label: 'Fatigue: Wasn\'t Even Included in Their Design', weight: 1, tier: 'SS+', score: 91, color: 'var(--tier-ss-plus)' },
  { label: 'Energy Was Here First — Everything Else Followed', weight: 1, tier: 'SS+', score: 91, color: 'var(--tier-ss-plus)' },
  { label: 'Stamina That Will Exist After Existence Ends', weight: 1, tier: 'SS+', score: 91, color: 'var(--tier-ss-plus)' },
  { label: 'Vitality That Is Intrinsic to All Dimensions', weight: 1, tier: 'SS+', score: 91, color: 'var(--tier-ss-plus)' },
  { label: 'Their Energy Level Has Never Been Anything But Maximum', weight: 1, tier: 'SS+', score: 91, color: 'var(--tier-ss-plus)' },
  { label: 'Running Through Every Possible End of Reality', weight: 1, tier: 'SS+', score: 91, color: 'var(--tier-ss-plus)' },
  { label: 'Has Revitalized Omniverses from Collapse — Accidentally', weight: 1, tier: 'SS+', score: 91, color: 'var(--tier-ss-plus)' },
  { label: 'Energy That Created Energy as a Concept', weight: 1, tier: 'SS+', score: 91, color: 'var(--tier-ss-plus)' },
  { label: 'Stamina Without Beginning or End', weight: 1, tier: 'SS+', score: 91, color: 'var(--tier-ss-plus)' },
  { label: 'All Fuel Is Downstream of Their Vitality', weight: 1, tier: 'SS+', score: 91, color: 'var(--tier-ss-plus)' },
  { label: 'The Singular, Absolute, Eternal Energy Source', weight: 1, tier: 'SS+', score: 91, color: 'var(--tier-ss-plus)' },

  // SSS- (score: 94)
  { label: 'Primordial Living Fuel', weight: 1, tier: 'SSS-', score: 94, color: 'var(--tier-sss-minus)' },
  { label: 'Energy That Has Never Known Decrease', weight: 1, tier: 'SSS-', score: 94, color: 'var(--tier-sss-minus)' },
  { label: 'Vitality That Pre-Seeded All Physical Constants', weight: 1, tier: 'SSS-', score: 94, color: 'var(--tier-sss-minus)' },
  { label: 'Stamina Predates Every Duration System', weight: 1, tier: 'SSS-', score: 94, color: 'var(--tier-sss-minus)' },
  { label: 'Still Running After Every Universe Ended', weight: 1, tier: 'SSS-', score: 94, color: 'var(--tier-sss-minus)' },
  { label: 'Energy That Cannot Be Named, Only Experienced', weight: 1, tier: 'SSS-', score: 94, color: 'var(--tier-sss-minus)' },
  { label: 'Has Provided Power to Every Known Cosmic Entity', weight: 1, tier: 'SSS-', score: 94, color: 'var(--tier-sss-minus)' },
  { label: 'Running Since the Moment Before Time', weight: 1, tier: 'SSS-', score: 94, color: 'var(--tier-sss-minus)' },
  { label: 'Vitality That Fueled the Big Bang as a Byproduct', weight: 1, tier: 'SSS-', score: 94, color: 'var(--tier-sss-minus)' },
  { label: 'The Pre-Universe Borrowed Energy From Them', weight: 1, tier: 'SSS-', score: 94, color: 'var(--tier-sss-minus)' },
  { label: 'Energy Output Cannot Be Contained by Any Physical Law', weight: 1, tier: 'SSS-', score: 94, color: 'var(--tier-sss-minus)' },
  { label: 'Omniversal Stamina Maximum: Filed Under Them', weight: 1, tier: 'SSS-', score: 94, color: 'var(--tier-sss-minus)' },
  { label: 'Has Never Depleted — Not Once Across All of Infinity', weight: 1, tier: 'SSS-', score: 94, color: 'var(--tier-sss-minus)' },
  { label: 'Vitality That Powers the Mechanism That Powers All Things', weight: 1, tier: 'SSS-', score: 94, color: 'var(--tier-sss-minus)' },
  { label: 'Energy Is Older Than Physics — They Were There First', weight: 1, tier: 'SSS-', score: 94, color: 'var(--tier-sss-minus)' },
  { label: 'Their Rest State Has More Energy Than Stars at Peak', weight: 1, tier: 'SSS-', score: 94, color: 'var(--tier-sss-minus)' },
  { label: 'Has Generated Enough Energy to Seed Multiple Omniverses', weight: 1, tier: 'SSS-', score: 94, color: 'var(--tier-sss-minus)' },
  { label: 'Everything That Burns Was Lit by Them', weight: 1, tier: 'SSS-', score: 94, color: 'var(--tier-sss-minus)' },
  { label: 'Stamina Registered as a Pre-Universal Origin Point', weight: 1, tier: 'SSS-', score: 94, color: 'var(--tier-sss-minus)' },
  { label: 'Vitality Without Floor, Without Ceiling, Without End', weight: 1, tier: 'SSS-', score: 94, color: 'var(--tier-sss-minus)' },

  // SSS (score: 97)
  { label: 'Eternal Boundless Energy', weight: 1, tier: 'SSS', score: 97, color: 'var(--tier-sss)' },
  { label: 'Vitality That Is Older Than All Possible Things', weight: 1, tier: 'SSS', score: 97, color: 'var(--tier-sss)' },
  { label: 'Energy That Will Continue After the Last Concept Ends', weight: 1, tier: 'SSS', score: 97, color: 'var(--tier-sss)' },
  { label: 'Still Running When Nothing Else Remains', weight: 1, tier: 'SSS', score: 97, color: 'var(--tier-sss)' },
  { label: 'Stamina That Is the Foundation of All Duration', weight: 1, tier: 'SSS', score: 97, color: 'var(--tier-sss)' },
  { label: 'Energy That Defined "Alive" by Existing', weight: 1, tier: 'SSS', score: 97, color: 'var(--tier-sss)' },
  { label: 'Has Never Had Less Energy in All of Eternity', weight: 1, tier: 'SSS', score: 97, color: 'var(--tier-sss)' },
  { label: 'Vitality That Sustains What Hasn\'t Been Created Yet', weight: 1, tier: 'SSS', score: 97, color: 'var(--tier-sss)' },
  { label: 'Energy Powered Pre-Time — Still Going', weight: 1, tier: 'SSS', score: 97, color: 'var(--tier-sss)' },
  { label: 'Stamina Is Not a Property — It Is Their Identity', weight: 1, tier: 'SSS', score: 97, color: 'var(--tier-sss)' },
  { label: 'Everything That Has Ever Burned Did So With Their Permission', weight: 1, tier: 'SSS', score: 97, color: 'var(--tier-sss)' },
  { label: 'The Energy Source All Others Are Downstream Of', weight: 1, tier: 'SSS', score: 97, color: 'var(--tier-sss)' },
  { label: 'Omniversal Power Constant — No Exception Possible', weight: 1, tier: 'SSS', score: 97, color: 'var(--tier-sss)' },
  { label: 'Running at Maximum Before Physics Had Constants', weight: 1, tier: 'SSS', score: 97, color: 'var(--tier-sss)' },
  { label: 'Vitality That Cannot Be Extinguished — Provably', weight: 1, tier: 'SSS', score: 97, color: 'var(--tier-sss)' },
  { label: 'Has Powered Everything Across All Timelines Always', weight: 1, tier: 'SSS', score: 97, color: 'var(--tier-sss)' },
  { label: 'Energy Output: Infinite. Duration: Infinite. Drop: None.', weight: 1, tier: 'SSS', score: 97, color: 'var(--tier-sss)' },
  { label: 'Still Going After the Last Universe Ends Again', weight: 1, tier: 'SSS', score: 97, color: 'var(--tier-sss)' },
  { label: 'Stamina Has Outlasted Every Definition of "Limit"', weight: 1, tier: 'SSS', score: 97, color: 'var(--tier-sss)' },
  { label: 'The Absolute Power Source — First, Last, Always', weight: 1, tier: 'SSS', score: 97, color: 'var(--tier-sss)' },

  // SSS+ (score: 99)
  { label: 'Absolute Perpetual Motion', weight: 1, tier: 'SSS+', score: 99, color: 'var(--tier-sss-plus)' },
  { label: 'Energy That Is Its Own Origin Story', weight: 1, tier: 'SSS+', score: 99, color: 'var(--tier-sss-plus)' },
  { label: 'Vitality That Created the Conditions for All Vitality', weight: 1, tier: 'SSS+', score: 99, color: 'var(--tier-sss-plus)' },
  { label: 'Has Never Not Been Running — Not in Pre-Time, Not Anywhere', weight: 1, tier: 'SSS+', score: 99, color: 'var(--tier-sss-plus)' },
  { label: 'Stamina That Will Be the Last Thing in All Omniverses', weight: 1, tier: 'SSS+', score: 99, color: 'var(--tier-sss-plus)' },
  { label: 'Energy Cannot Be Named — Only Referenced', weight: 1, tier: 'SSS+', score: 99, color: 'var(--tier-sss-plus)' },
  { label: 'The Big Bang Was Them Stretching', weight: 1, tier: 'SSS+', score: 99, color: 'var(--tier-sss-plus)' },
  { label: 'Vitality That Makes Everything Else Possible', weight: 1, tier: 'SSS+', score: 99, color: 'var(--tier-sss-plus)' },
  { label: 'Omniversal Energy Origin — First and Last', weight: 1, tier: 'SSS+', score: 99, color: 'var(--tier-sss-plus)' },
  { label: 'Running Without End, Without Decrease, Without a Known Purpose', weight: 1, tier: 'SSS+', score: 99, color: 'var(--tier-sss-plus)' },
  { label: 'Energy Level: Permanently Cosmic Maximum', weight: 1, tier: 'SSS+', score: 99, color: 'var(--tier-sss-plus)' },
  { label: 'Has No State Other Than Full Power — Always', weight: 1, tier: 'SSS+', score: 99, color: 'var(--tier-sss-plus)' },
  { label: 'Vitality That Is the Substrate of All Other Energy', weight: 1, tier: 'SSS+', score: 99, color: 'var(--tier-sss-plus)' },
  { label: 'Stamina So Complete That Time Requires Them', weight: 1, tier: 'SSS+', score: 99, color: 'var(--tier-sss-plus)' },
  { label: 'Their Energy Is Why "Energy" Is a Word', weight: 1, tier: 'SSS+', score: 99, color: 'var(--tier-sss-plus)' },
  { label: 'Fueling the Omniverse Before It Knew It Needed Fueling', weight: 1, tier: 'SSS+', score: 99, color: 'var(--tier-sss-plus)' },
  { label: 'Runs Everything — Including What Runs Everything', weight: 1, tier: 'SSS+', score: 99, color: 'var(--tier-sss-plus)' },
  { label: 'Energy Was Their Gift to the Universe on Day 1', weight: 1, tier: 'SSS+', score: 99, color: 'var(--tier-sss-plus)' },
  { label: 'Absolute Stamina — No Closing Statement Necessary', weight: 1, tier: 'SSS+', score: 99, color: 'var(--tier-sss-plus)' },
  { label: 'Omniversal Living Fuel — Cannot Be Extinguished', weight: 1, tier: 'SSS+', score: 99, color: 'var(--tier-sss-plus)' },

  // God (score: 100)
  { label: 'The Battery That Won\'t Die', weight: 1, tier: 'God', score: 100, color: 'var(--tier-god)' },
  { label: 'Infinite Energy — No Footnotes', weight: 1, tier: 'God', score: 100, color: 'var(--tier-god)' },
  { label: 'Vitality That Is Its Own Cosmology', weight: 1, tier: 'God', score: 100, color: 'var(--tier-god)' },
  { label: 'Running Before Running Existed — Still Running — Always Will Be', weight: 1, tier: 'God', score: 100, color: 'var(--tier-god)' },
  { label: 'Energy That Preceded Time and Will Outlast It', weight: 1, tier: 'God', score: 100, color: 'var(--tier-god)' },
  { label: 'Stamina: The Only Universal Constant', weight: 1, tier: 'God', score: 100, color: 'var(--tier-god)' },
  { label: 'All Energy Points Back to Them as Its Source', weight: 1, tier: 'God', score: 100, color: 'var(--tier-god)' },
  { label: 'Has Powered Every Universe That Has Ever Existed', weight: 1, tier: 'God', score: 100, color: 'var(--tier-god)' },
  { label: 'Vitality Is Not a Stat — It Is Their Fundamental Nature', weight: 1, tier: 'God', score: 100, color: 'var(--tier-god)' },
  { label: 'Energy That Cannot End Because It Was Never Finite', weight: 1, tier: 'God', score: 100, color: 'var(--tier-god)' },
  { label: 'Has Never Needed Fuel — Has Always Provided It', weight: 1, tier: 'God', score: 100, color: 'var(--tier-god)' },
  { label: 'Stamina That Is the Heartbeat of All Existence', weight: 1, tier: 'God', score: 100, color: 'var(--tier-god)' },
  { label: 'Energy Absolute — The First, The Last, The Only', weight: 1, tier: 'God', score: 100, color: 'var(--tier-god)' },
  { label: 'Their Idle Output Fuels Galaxies', weight: 1, tier: 'God', score: 100, color: 'var(--tier-god)' },
  { label: 'The Reason "Alive" Means Anything', weight: 1, tier: 'God', score: 100, color: 'var(--tier-god)' },
  { label: 'Omniversal Power: Total. Final. Unbounded.', weight: 1, tier: 'God', score: 100, color: 'var(--tier-god)' },
  { label: 'Vitality That Cannot Be Taken, Reduced, or Referenced Adequately', weight: 1, tier: 'God', score: 100, color: 'var(--tier-god)' },
  { label: 'Has Always Been Running — Has Never Stopped — Never Will', weight: 1, tier: 'God', score: 100, color: 'var(--tier-god)' },
  { label: 'Energy Was and Is and Will Be — Always Them', weight: 1, tier: 'God', score: 100, color: 'var(--tier-god)' },
  { label: 'The Eternal Flame That Cannot Die', weight: 1, tier: 'God', score: 100, color: 'var(--tier-god)' },
]
