import type { FlavorLabel } from './types'

export const energyLevelLabels: FlavorLabel[] = [
  { label: 'Naps More Than Acts',                    weight: 4, tier: 'F-',   score: 2,   color: '#555'    },
  { label: 'Visibly Drained at Rest',                weight: 4, tier: 'F',    score: 5,   color: '#666'    },
  { label: 'Makes It to Lunch',                      weight: 4, tier: 'F+',   score: 8,   color: '#777'    },
  { label: 'Normal Human Stamina',                   weight: 6, tier: 'E-',   score: 11,  color: '#6b7280' },
  { label: 'Active Day Without Exhaustion',          weight: 6, tier: 'E',    score: 14,  color: '#9ca3af' },
  { label: 'Rarely Tires',                           weight: 6, tier: 'E+',   score: 17,  color: '#d1d5db' },
  { label: 'Athlete-Level Stamina',                  weight: 8, tier: 'D-',   score: 20,  color: '#92400e' },
  { label: 'Extended Combat Capable',                weight: 8, tier: 'D',    score: 23,  color: '#b45309' },
  { label: 'Days Without Rest',                      weight: 8, tier: 'D+',   score: 26,  color: '#d97706' },
  { label: 'Tireless in Extended Combat',            weight: 8, tier: 'C-',   score: 30,  color: '#1d4ed8' },
  { label: 'Aura Visibly Radiates',                  weight: 8, tier: 'C',    score: 34,  color: '#2563eb' },
  { label: 'Energy Disrupts Electronics Nearby',     weight: 8, tier: 'C+',   score: 38,  color: '#3b82f6' },
  { label: 'Ki Presence Felt in the Room',           weight: 7, tier: 'B-',   score: 42,  color: '#065f46' },
  { label: 'Aura Combat Enhancement',                weight: 7, tier: 'B',    score: 47,  color: '#059669' },
  { label: 'Overflows with Restrained Power',        weight: 7, tier: 'B+',   score: 52,  color: '#34d399' },
  { label: 'Energy Warps the Environment',           weight: 5, tier: 'A-',   score: 57,  color: '#7c3aed' },
  { label: 'Power Level Detectable at Distance',     weight: 5, tier: 'A',    score: 62,  color: '#8b5cf6' },
  { label: 'Atmospheric Disturbance on Release',     weight: 5, tier: 'A+',   score: 67,  color: '#a78bfa' },
  { label: 'Continent-Scale Energy Presence',        weight: 4, tier: 'S-',   score: 72,  color: '#b91c1c' },
  { label: 'Planet Feels It When They Power Up',     weight: 4, tier: 'S',    score: 77,  color: '#dc2626' },
  { label: 'Solar System-Level Output',              weight: 4, tier: 'S+',   score: 81,  color: '#ef4444' },
  { label: 'Galactic Energy Signature',              weight: 3, tier: 'SS-',  score: 85,  color: '#ea580c' },
  { label: 'Universe Registers Their Presence',      weight: 3, tier: 'SS',   score: 88,  color: '#f97316' },
  { label: 'Energy Output Has Its Own Gravity',      weight: 3, tier: 'SS+',  score: 91,  color: '#fb923c' },
  { label: 'Powering Up Rearranges Stars',                  weight: 2, tier: 'SSS-',      score: 94,  color: '#ca8a04' },
  { label: 'Energy Level Is a Natural Phenomenon',          weight: 2, tier: 'SSS',       score: 97,  color: '#eab308' },
  { label: 'The Big Bang Was Practice',                     weight: 2, tier: 'SSS+',      score: 99,  color: '#fde047' },
  { label: 'Energy Signature Visible From Adjacent Galaxies',weight: 2, tier: 'Z-',       score: 101, color: '#0e7490' },
  { label: 'Powers Up and the Universe Dims Locally',       weight: 2, tier: 'Z',         score: 103, color: '#0891b2' },
  { label: 'Energy Output Rivals a Collapsing Galaxy',      weight: 2, tier: 'Z+',        score: 105, color: '#06b6d4' },
  { label: 'Output That Sustains Multiple Universes',       weight: 1, tier: 'ZZ-',       score: 107, color: '#3730a3' },
  { label: 'Energy Radiates Across Dimensional Barriers',   weight: 1, tier: 'ZZ',        score: 109, color: '#4f46e5' },
  { label: 'Power Level Is a Recognized Cosmic Event',      weight: 1, tier: 'ZZ+',       score: 111, color: '#818cf8' },
  { label: 'Energy Level Has Diplomatic Immunity',          weight: 1, tier: 'ZZZ-',      score: 113, color: '#9d174d' },
  { label: 'The Universe Has a Policy About Their Power-Ups',weight: 1, tier: 'ZZZ',      score: 115, color: '#be185d' },
  { label: 'Output Would Be Illegal in All Known Dimensions',weight: 1, tier: 'ZZZ+',     score: 117, color: '#ec4899' },
  { label: 'Energy Draws on the Divine Ether Directly',     weight: 1, tier: 'Celestial-',score: 119, color: '#075985' },
  { label: 'Power Level That Rivals Celestial Bodies',      weight: 1, tier: 'Celestial', score: 121, color: '#0284c7' },
  { label: 'Even Stars Dim in Comparison',                  weight: 1, tier: 'Celestial+',score: 123, color: '#38bdf8' },
  { label: 'Energy Output That Reshapes Divine Planes',     weight: 1, tier: 'Godly-',    score: 125, color: '#c026d3' },
  { label: 'Existence Itself Is Their Energy Source',       weight: 1, tier: 'Godly',     score: 127, color: '#e879f9' },
  { label: 'Energy That Predates the First Light',           weight: 1, tier: 'Primordial', score: 130, color: '#ffffff' },
  { label: 'Powers Up — Nearby Universes Dim in Response',  weight: 1, tier: 'Primordial+',score: 133, color: '#ccffff' },
  { label: 'Output Has No Upper Reference Point',           weight: 1, tier: 'Absolute-',  score: 137, color: '#99ffff' },
  { label: 'The First Spark of Existence Was Theirs',       weight: 1, tier: 'Absolute',   score: 144, color: '#00ffff' },
]
