import type { FlavorLabel } from './types'

export const fightingSkillLabels: FlavorLabel[] = [
  // F- (score: 2)
  { label: 'Hit Themselves More Than Opponents', weight: 1, tier: 'F-', score: 2, color: 'var(--tier-f-minus)' },
  { label: 'Lost a Fight to a Door', weight: 1, tier: 'F-', score: 2, color: 'var(--tier-f-minus)' },
  { label: 'Telegraphs Every Punch 3 Seconds Ahead', weight: 1, tier: 'F-', score: 2, color: 'var(--tier-f-minus)' },
  { label: 'Tripped Throwing a Punch', weight: 1, tier: 'F-', score: 2, color: 'var(--tier-f-minus)' },
  { label: 'Surrendered Before the Fight Started', weight: 1, tier: 'F-', score: 2, color: 'var(--tier-f-minus)' },
  { label: 'Punched Air — Missed', weight: 1, tier: 'F-', score: 2, color: 'var(--tier-f-minus)' },
  { label: 'Forgot How Limbs Work Mid-Combat', weight: 1, tier: 'F-', score: 2, color: 'var(--tier-f-minus)' },
  { label: 'Hurt by Own War Cry', weight: 1, tier: 'F-', score: 2, color: 'var(--tier-f-minus)' },
  { label: 'Technically Knows a Martial Art — Incorrectly', weight: 1, tier: 'F-', score: 2, color: 'var(--tier-f-minus)' },
  { label: 'Defeated by Someone\'s Granddaughter', weight: 1, tier: 'F-', score: 2, color: 'var(--tier-f-minus)' },
  { label: 'Fought a Broom. Lost.', weight: 1, tier: 'F-', score: 2, color: 'var(--tier-f-minus)' },
  { label: 'The Threat Assessment Said: Non-Combatant', weight: 1, tier: 'F-', score: 2, color: 'var(--tier-f-minus)' },
  { label: 'Stance Is Just Standing Awkwardly', weight: 1, tier: 'F-', score: 2, color: 'var(--tier-f-minus)' },
  { label: 'Pulled a Muscle Attempting a Battle Cry', weight: 1, tier: 'F-', score: 2, color: 'var(--tier-f-minus)' },
  { label: 'Accidentally Knocked Self Out', weight: 1, tier: 'F-', score: 2, color: 'var(--tier-f-minus)' },
  { label: 'Classified as Harmless by Every Enemy', weight: 1, tier: 'F-', score: 2, color: 'var(--tier-f-minus)' },
  { label: 'Couldn\'t Win an Argument, Let Alone a Fight', weight: 1, tier: 'F-', score: 2, color: 'var(--tier-f-minus)' },
  { label: 'Weapon Selection: Spoon', weight: 1, tier: 'F-', score: 2, color: 'var(--tier-f-minus)' },
  { label: 'Last Seen Running the Wrong Direction', weight: 1, tier: 'F-', score: 2, color: 'var(--tier-f-minus)' },
  { label: 'Does Not Know Their Own Reach', weight: 1, tier: 'F-', score: 2, color: 'var(--tier-f-minus)' },

  // F (score: 5)
  { label: 'Beginner Who Overestimates Themselves', weight: 1, tier: 'F', score: 5, color: 'var(--tier-f)' },
  { label: 'Stance Needs Work', weight: 1, tier: 'F', score: 5, color: 'var(--tier-f)' },
  { label: 'Swings Wide, Always', weight: 1, tier: 'F', score: 5, color: 'var(--tier-f)' },
  { label: 'Accidentally Won Once (Still Confused)', weight: 1, tier: 'F', score: 5, color: 'var(--tier-f)' },
  { label: 'Fights Like They\'re Swatting Flies', weight: 1, tier: 'F', score: 5, color: 'var(--tier-f)' },
  { label: 'Knows Two Moves — Both Fail', weight: 1, tier: 'F', score: 5, color: 'var(--tier-f)' },
  { label: 'Slow Enough to Dodge Their Own Attacks', weight: 1, tier: 'F', score: 5, color: 'var(--tier-f)' },
  { label: 'Once Blocked With Face', weight: 1, tier: 'F', score: 5, color: 'var(--tier-f)' },
  { label: 'Considered Threatening Only by Houseplants', weight: 1, tier: 'F', score: 5, color: 'var(--tier-f)' },
  { label: 'Unintentionally Fighting Style', weight: 1, tier: 'F', score: 5, color: 'var(--tier-f)' },
  { label: 'Watched a Lot of Fighting Videos', weight: 1, tier: 'F', score: 5, color: 'var(--tier-f)' },
  { label: 'Hurt an Opponent Once — Mutual Surprise', weight: 1, tier: 'F', score: 5, color: 'var(--tier-f)' },
  { label: 'Combat Instinct: Run, Secondarily Flail', weight: 1, tier: 'F', score: 5, color: 'var(--tier-f)' },
  { label: 'Occasionally Lands a Punch by Accident', weight: 1, tier: 'F', score: 5, color: 'var(--tier-f)' },
  { label: 'Technically Won Arm-Wrestling Once', weight: 1, tier: 'F', score: 5, color: 'var(--tier-f)' },
  { label: 'Flinches at Own Attacks', weight: 1, tier: 'F', score: 5, color: 'var(--tier-f)' },
  { label: 'Strategy: Hope for the Best', weight: 1, tier: 'F', score: 5, color: 'var(--tier-f)' },
  { label: 'Not Counted in Battle Plans', weight: 1, tier: 'F', score: 5, color: 'var(--tier-f)' },
  { label: 'Has a Fighting Style; It\'s Just Wrong', weight: 1, tier: 'F', score: 5, color: 'var(--tier-f)' },
  { label: 'Made Enemy Laugh — That\'s All', weight: 1, tier: 'F', score: 5, color: 'var(--tier-f)' },

  // F+ (score: 8)
  { label: 'Street Brawler Level', weight: 1, tier: 'F+', score: 8, color: 'var(--tier-f-plus)' },
  { label: 'Occasionally Blocks Hits', weight: 1, tier: 'F+', score: 8, color: 'var(--tier-f-plus)' },
  { label: 'Wins Bar Fights (Barely)', weight: 1, tier: 'F+', score: 8, color: 'var(--tier-f-plus)' },
  { label: 'Passable Brawler', weight: 1, tier: 'F+', score: 8, color: 'var(--tier-f-plus)' },
  { label: 'Has Done Some Damage in Their Time', weight: 1, tier: 'F+', score: 8, color: 'var(--tier-f-plus)' },
  { label: 'Knows When to Commit to a Swing', weight: 1, tier: 'F+', score: 8, color: 'var(--tier-f-plus)' },
  { label: 'Can Read a Basic Combo', weight: 1, tier: 'F+', score: 8, color: 'var(--tier-f-plus)' },
  { label: 'Technically Has a Style Now', weight: 1, tier: 'F+', score: 8, color: 'var(--tier-f-plus)' },
  { label: 'Beats Most Untrained Opponents', weight: 1, tier: 'F+', score: 8, color: 'var(--tier-f-plus)' },
  { label: 'No Longer Falls Down When Swinging', weight: 1, tier: 'F+', score: 8, color: 'var(--tier-f-plus)' },
  { label: 'Slow Counter Attack That Sometimes Works', weight: 1, tier: 'F+', score: 8, color: 'var(--tier-f-plus)' },
  { label: 'Clumsy but Committed', weight: 1, tier: 'F+', score: 8, color: 'var(--tier-f-plus)' },
  { label: 'Knows Not to Leave Chin Open', weight: 1, tier: 'F+', score: 8, color: 'var(--tier-f-plus)' },
  { label: 'Has a Finisher (It\'s a Shove)', weight: 1, tier: 'F+', score: 8, color: 'var(--tier-f-plus)' },
  { label: 'Makes Most Opponents Work for It', weight: 1, tier: 'F+', score: 8, color: 'var(--tier-f-plus)' },
  { label: 'Respectable Durability in a Fight', weight: 1, tier: 'F+', score: 8, color: 'var(--tier-f-plus)' },
  { label: 'Took a Hit and Kept Going', weight: 1, tier: 'F+', score: 8, color: 'var(--tier-f-plus)' },
  { label: 'Showed Up Ready to Fight', weight: 1, tier: 'F+', score: 8, color: 'var(--tier-f-plus)' },
  { label: 'Basic Defensive Instincts Present', weight: 1, tier: 'F+', score: 8, color: 'var(--tier-f-plus)' },
  { label: 'Scrappy if Desperate', weight: 1, tier: 'F+', score: 8, color: 'var(--tier-f-plus)' },

  // E- (score: 11)
  { label: 'Trained Fighter (Novice)', weight: 1, tier: 'E-', score: 11, color: 'var(--tier-e-minus)' },
  { label: 'Clean Footwork on Good Days', weight: 1, tier: 'E-', score: 11, color: 'var(--tier-e-minus)' },
  { label: 'Combo That Actually Connects', weight: 1, tier: 'E-', score: 11, color: 'var(--tier-e-minus)' },
  { label: 'Knows When to Dodge vs. Block', weight: 1, tier: 'E-', score: 11, color: 'var(--tier-e-minus)' },
  { label: 'Passes Entry-Level Combat Tests', weight: 1, tier: 'E-', score: 11, color: 'var(--tier-e-minus)' },
  { label: 'Consistent at Mid-Range', weight: 1, tier: 'E-', score: 11, color: 'var(--tier-e-minus)' },
  { label: 'Beat a Trained Soldier Once', weight: 1, tier: 'E-', score: 11, color: 'var(--tier-e-minus)' },
  { label: 'Respectable Guard Posture', weight: 1, tier: 'E-', score: 11, color: 'var(--tier-e-minus)' },
  { label: 'Reads Opponent\'s Tells', weight: 1, tier: 'E-', score: 11, color: 'var(--tier-e-minus)' },
  { label: 'Patient Fighter', weight: 1, tier: 'E-', score: 11, color: 'var(--tier-e-minus)' },
  { label: 'Won a Formal Match at Least Once', weight: 1, tier: 'E-', score: 11, color: 'var(--tier-e-minus)' },
  { label: 'Has a Reliable One-Two', weight: 1, tier: 'E-', score: 11, color: 'var(--tier-e-minus)' },
  { label: 'Studied Two Disciplines, Applies One Well', weight: 1, tier: 'E-', score: 11, color: 'var(--tier-e-minus)' },
  { label: 'Knows When to Disengage', weight: 1, tier: 'E-', score: 11, color: 'var(--tier-e-minus)' },
  { label: 'Good Spatial Awareness in a Brawl', weight: 1, tier: 'E-', score: 11, color: 'var(--tier-e-minus)' },
  { label: 'Adapts to Unexpected Attacks', weight: 1, tier: 'E-', score: 11, color: 'var(--tier-e-minus)' },
  { label: 'Calm Under Pressure', weight: 1, tier: 'E-', score: 11, color: 'var(--tier-e-minus)' },
  { label: 'Counter-Attack Timing Decent', weight: 1, tier: 'E-', score: 11, color: 'var(--tier-e-minus)' },
  { label: 'Not Winded After Three Rounds', weight: 1, tier: 'E-', score: 11, color: 'var(--tier-e-minus)' },
  { label: 'Can Chain Strikes Purposefully', weight: 1, tier: 'E-', score: 11, color: 'var(--tier-e-minus)' },

  // E (score: 14)
  { label: 'Competent Brawler', weight: 1, tier: 'E', score: 14, color: 'var(--tier-e)' },
  { label: 'Fights Efficiently, Without Waste', weight: 1, tier: 'E', score: 14, color: 'var(--tier-e)' },
  { label: 'Consistent Winner Against Most Opponents', weight: 1, tier: 'E', score: 14, color: 'var(--tier-e)' },
  { label: 'Knows When to End a Fight', weight: 1, tier: 'E', score: 14, color: 'var(--tier-e)' },
  { label: 'Seamless Combo Chains', weight: 1, tier: 'E', score: 14, color: 'var(--tier-e)' },
  { label: 'Exploits Openings Immediately', weight: 1, tier: 'E', score: 14, color: 'var(--tier-e)' },
  { label: 'Calm and Precise Mid-Fight', weight: 1, tier: 'E', score: 14, color: 'var(--tier-e)' },
  { label: 'Defeats Most Armed Opponents Unarmed', weight: 1, tier: 'E', score: 14, color: 'var(--tier-e)' },
  { label: 'Never Takes More Damage Than Dealt', weight: 1, tier: 'E', score: 14, color: 'var(--tier-e)' },
  { label: 'Reads Fights Like a Map', weight: 1, tier: 'E', score: 14, color: 'var(--tier-e)' },
  { label: 'Threat-Levels Opponents Instantly', weight: 1, tier: 'E', score: 14, color: 'var(--tier-e)' },
  { label: 'Can Fight Multiple Opponents Adequately', weight: 1, tier: 'E', score: 14, color: 'var(--tier-e)' },
  { label: 'Full Mastery of One Style', weight: 1, tier: 'E', score: 14, color: 'var(--tier-e)' },
  { label: 'Fights With Economy and Intent', weight: 1, tier: 'E', score: 14, color: 'var(--tier-e)' },
  { label: 'Rarely Loses in Close Range', weight: 1, tier: 'E', score: 14, color: 'var(--tier-e)' },
  { label: 'Uses Environment as a Weapon', weight: 1, tier: 'E', score: 14, color: 'var(--tier-e)' },
  { label: 'Feared on the Training Floor', weight: 1, tier: 'E', score: 14, color: 'var(--tier-e)' },
  { label: 'Turns Defense Into Offense Naturally', weight: 1, tier: 'E', score: 14, color: 'var(--tier-e)' },
  { label: 'Earns Opponent Respect', weight: 1, tier: 'E', score: 14, color: 'var(--tier-e)' },
  { label: 'Strike Library Growing Quickly', weight: 1, tier: 'E', score: 14, color: 'var(--tier-e)' },

  // E+ (score: 17)
  { label: 'Skilled Combatant', weight: 1, tier: 'E+', score: 17, color: 'var(--tier-e-plus)' },
  { label: 'Beats Veteran Soldiers Regularly', weight: 1, tier: 'E+', score: 17, color: 'var(--tier-e-plus)' },
  { label: 'Multi-Style Combatant', weight: 1, tier: 'E+', score: 17, color: 'var(--tier-e-plus)' },
  { label: 'Reads Fights Before They Start', weight: 1, tier: 'E+', score: 17, color: 'var(--tier-e-plus)' },
  { label: 'Nearly Effortless Takedowns', weight: 1, tier: 'E+', score: 17, color: 'var(--tier-e-plus)' },
  { label: 'Fights Three and Wins', weight: 1, tier: 'E+', score: 17, color: 'var(--tier-e-plus)' },
  { label: 'Attack Chains 5+ Deep', weight: 1, tier: 'E+', score: 17, color: 'var(--tier-e-plus)' },
  { label: 'Disarms in One Move', weight: 1, tier: 'E+', score: 17, color: 'var(--tier-e-plus)' },
  { label: 'Pressure Without Commitment', weight: 1, tier: 'E+', score: 17, color: 'var(--tier-e-plus)' },
  { label: 'Improvised Combat Styles on the Fly', weight: 1, tier: 'E+', score: 17, color: 'var(--tier-e-plus)' },
  { label: 'Made Trained Opponents Look Amateur', weight: 1, tier: 'E+', score: 17, color: 'var(--tier-e-plus)' },
  { label: 'Fights at 70% and Still Wins', weight: 1, tier: 'E+', score: 17, color: 'var(--tier-e-plus)' },
  { label: 'Threat Assessment: High', weight: 1, tier: 'E+', score: 17, color: 'var(--tier-e-plus)' },
  { label: 'Knocks Out With One Strike Routinely', weight: 1, tier: 'E+', score: 17, color: 'var(--tier-e-plus)' },
  { label: 'Fights Like They Have a Plan B', weight: 1, tier: 'E+', score: 17, color: 'var(--tier-e-plus)' },
  { label: 'Pinpoint Targeting Without Thinking', weight: 1, tier: 'E+', score: 17, color: 'var(--tier-e-plus)' },
  { label: 'Defense as Good as Offense', weight: 1, tier: 'E+', score: 17, color: 'var(--tier-e-plus)' },
  { label: 'Never Takes an Unnecessary Hit', weight: 1, tier: 'E+', score: 17, color: 'var(--tier-e-plus)' },
  { label: 'Opponent Regrets Starting It Immediately', weight: 1, tier: 'E+', score: 17, color: 'var(--tier-e-plus)' },
  { label: 'Can Fight Blindfolded and Win', weight: 1, tier: 'E+', score: 17, color: 'var(--tier-e-plus)' },

  // D- (score: 20)
  { label: 'Elite Warrior', weight: 1, tier: 'D-', score: 20, color: 'var(--tier-d-minus)' },
  { label: 'Fights Like a Machine', weight: 1, tier: 'D-', score: 20, color: 'var(--tier-d-minus)' },
  { label: 'Trained Armies Avoid Them', weight: 1, tier: 'D-', score: 20, color: 'var(--tier-d-minus)' },
  { label: 'Wins Before Opponent Swings', weight: 1, tier: 'D-', score: 20, color: 'var(--tier-d-minus)' },
  { label: 'Tactical Genius in Close Combat', weight: 1, tier: 'D-', score: 20, color: 'var(--tier-d-minus)' },
  { label: 'Neutralizes Any Style', weight: 1, tier: 'D-', score: 20, color: 'var(--tier-d-minus)' },
  { label: 'Ends Fights Before They Escalate', weight: 1, tier: 'D-', score: 20, color: 'var(--tier-d-minus)' },
  { label: 'Adjusts Mid-Strike', weight: 1, tier: 'D-', score: 20, color: 'var(--tier-d-minus)' },
  { label: 'Fights Groups Like They\'re One Target', weight: 1, tier: 'D-', score: 20, color: 'var(--tier-d-minus)' },
  { label: 'Studied Under Legendary Masters', weight: 1, tier: 'D-', score: 20, color: 'var(--tier-d-minus)' },
  { label: 'Defeated Champion Fighters Casually', weight: 1, tier: 'D-', score: 20, color: 'var(--tier-d-minus)' },
  { label: 'Zero Wasted Motion in Combat', weight: 1, tier: 'D-', score: 20, color: 'var(--tier-d-minus)' },
  { label: 'Weapon and Unarmed at Equal Level', weight: 1, tier: 'D-', score: 20, color: 'var(--tier-d-minus)' },
  { label: 'Opponents Freeze When They Move', weight: 1, tier: 'D-', score: 20, color: 'var(--tier-d-minus)' },
  { label: 'Makes Elite Fighters Look Sloppy', weight: 1, tier: 'D-', score: 20, color: 'var(--tier-d-minus)' },
  { label: 'Trained Instincts Override Thought', weight: 1, tier: 'D-', score: 20, color: 'var(--tier-d-minus)' },
  { label: 'Threat Level: Evacuate the Building', weight: 1, tier: 'D-', score: 20, color: 'var(--tier-d-minus)' },
  { label: 'Every Fight an Autopsy of Opponent\'s Weaknesses', weight: 1, tier: 'D-', score: 20, color: 'var(--tier-d-minus)' },
  { label: 'Outclasses Trained Units Alone', weight: 1, tier: 'D-', score: 20, color: 'var(--tier-d-minus)' },
  { label: 'Combat Flow Described as "Beautiful and Terrifying"', weight: 1, tier: 'D-', score: 20, color: 'var(--tier-d-minus)' },

  // D (score: 23)
  { label: 'Apex Combatant', weight: 1, tier: 'D', score: 23, color: 'var(--tier-d)' },
  { label: 'Made a Legion Back Down', weight: 1, tier: 'D', score: 23, color: 'var(--tier-d)' },
  { label: 'Attacks Hit Before They\'re Seen', weight: 1, tier: 'D', score: 23, color: 'var(--tier-d)' },
  { label: 'No Wasted Micro-Motion', weight: 1, tier: 'D', score: 23, color: 'var(--tier-d)' },
  { label: 'Fights Like Every Hit Is Calculated Beforehand', weight: 1, tier: 'D', score: 23, color: 'var(--tier-d)' },
  { label: 'Has Never Taken Damage From an Equal', weight: 1, tier: 'D', score: 23, color: 'var(--tier-d)' },
  { label: 'Flawless Combat Record', weight: 1, tier: 'D', score: 23, color: 'var(--tier-d)' },
  { label: 'Enemies Reassign Rather Than Fight Them', weight: 1, tier: 'D', score: 23, color: 'var(--tier-d)' },
  { label: 'Improvised Weapon Proficiency: Maximum', weight: 1, tier: 'D', score: 23, color: 'var(--tier-d)' },
  { label: 'Battlefield Chess Master', weight: 1, tier: 'D', score: 23, color: 'var(--tier-d)' },
  { label: 'Disarms a Crowd in Under 10 Seconds', weight: 1, tier: 'D', score: 23, color: 'var(--tier-d)' },
  { label: 'Breaks Opponent\'s Strategy by Move 2', weight: 1, tier: 'D', score: 23, color: 'var(--tier-d)' },
  { label: 'Uses the Room as a Weapon', weight: 1, tier: 'D', score: 23, color: 'var(--tier-d)' },
  { label: 'Studied Every Style. Mastered All.', weight: 1, tier: 'D', score: 23, color: 'var(--tier-d)' },
  { label: 'Combat Instinct Fires Before Thought', weight: 1, tier: 'D', score: 23, color: 'var(--tier-d)' },
  { label: 'Neutralizes Supers Without Powers', weight: 1, tier: 'D', score: 23, color: 'var(--tier-d)' },
  { label: 'Leaves Opponents Standing — Barely', weight: 1, tier: 'D', score: 23, color: 'var(--tier-d)' },
  { label: 'The Scariest Fighter in Any Room', weight: 1, tier: 'D', score: 23, color: 'var(--tier-d)' },
  { label: 'Fights 20 and Incapacitates All 20', weight: 1, tier: 'D', score: 23, color: 'var(--tier-d)' },
  { label: 'Combat Mastery: Certified Terrifying', weight: 1, tier: 'D', score: 23, color: 'var(--tier-d)' },

  // D+ (score: 26)
  { label: 'Warrior of Historic Note', weight: 1, tier: 'D+', score: 26, color: 'var(--tier-d-plus)' },
  { label: 'Armies Change Plans When They Show Up', weight: 1, tier: 'D+', score: 26, color: 'var(--tier-d-plus)' },
  { label: 'Fights Like They See 5 Moves Ahead', weight: 1, tier: 'D+', score: 26, color: 'var(--tier-d-plus)' },
  { label: 'Outlasted a Hundred-Man Gauntlet', weight: 1, tier: 'D+', score: 26, color: 'var(--tier-d-plus)' },
  { label: 'Combat Precision: Surgical', weight: 1, tier: 'D+', score: 26, color: 'var(--tier-d-plus)' },
  { label: 'Invincible in Close Combat — Near-Literally', weight: 1, tier: 'D+', score: 26, color: 'var(--tier-d-plus)' },
  { label: 'Has No Known Style — It\'s Something Else', weight: 1, tier: 'D+', score: 26, color: 'var(--tier-d-plus)' },
  { label: 'Wins Before Walking In', weight: 1, tier: 'D+', score: 26, color: 'var(--tier-d-plus)' },
  { label: 'Can Cause Injuries With Words Alone (Psychologically)', weight: 1, tier: 'D+', score: 26, color: 'var(--tier-d-plus)' },
  { label: 'Made a General Retire', weight: 1, tier: 'D+', score: 26, color: 'var(--tier-d-plus)' },
  { label: 'Fights Like They Choreographed the Scene', weight: 1, tier: 'D+', score: 26, color: 'var(--tier-d-plus)' },
  { label: 'Immune to Dirty Tricks', weight: 1, tier: 'D+', score: 26, color: 'var(--tier-d-plus)' },
  { label: 'The Fighting Style Textbooks Were Wrong; This Is Right', weight: 1, tier: 'D+', score: 26, color: 'var(--tier-d-plus)' },
  { label: 'Defeats Opponents Before They Realize', weight: 1, tier: 'D+', score: 26, color: 'var(--tier-d-plus)' },
  { label: 'Fights and Wins Without Injury', weight: 1, tier: 'D+', score: 26, color: 'var(--tier-d-plus)' },
  { label: 'Invents New Techniques Mid-Fight', weight: 1, tier: 'D+', score: 26, color: 'var(--tier-d-plus)' },
  { label: 'Opponents Call It Unfair', weight: 1, tier: 'D+', score: 26, color: 'var(--tier-d-plus)' },
  { label: 'Fights With Eyes Closed at This Level', weight: 1, tier: 'D+', score: 26, color: 'var(--tier-d-plus)' },
  { label: 'The Best Fighter for Miles in Any Direction', weight: 1, tier: 'D+', score: 26, color: 'var(--tier-d-plus)' },
  { label: 'Would Win Fighting Backwards on a Bad Day', weight: 1, tier: 'D+', score: 26, color: 'var(--tier-d-plus)' },

  // C- (score: 30)
  { label: 'Legendary Fighter', weight: 1, tier: 'C-', score: 30, color: 'var(--tier-c-minus)' },
  { label: 'Took Down Superhuman Threats Unarmed', weight: 1, tier: 'C-', score: 30, color: 'var(--tier-c-minus)' },
  { label: 'Fights More Than One Universe Would Allow', weight: 1, tier: 'C-', score: 30, color: 'var(--tier-c-minus)' },
  { label: 'No Longer Registered by Combat Systems', weight: 1, tier: 'C-', score: 30, color: 'var(--tier-c-minus)' },
  { label: 'Develops New Martial Art Every Conflict', weight: 1, tier: 'C-', score: 30, color: 'var(--tier-c-minus)' },
  { label: 'Rewrote the Definition of "Fighter"', weight: 1, tier: 'C-', score: 30, color: 'var(--tier-c-minus)' },
  { label: 'Battles Are Just Demonstrations at This Point', weight: 1, tier: 'C-', score: 30, color: 'var(--tier-c-minus)' },
  { label: 'Invincible (In Practice)', weight: 1, tier: 'C-', score: 30, color: 'var(--tier-c-minus)' },
  { label: 'Defeated a God in Sparring (Politely)', weight: 1, tier: 'C-', score: 30, color: 'var(--tier-c-minus)' },
  { label: 'Combat Leaves No Mark on Them', weight: 1, tier: 'C-', score: 30, color: 'var(--tier-c-minus)' },
  { label: 'Has Fought Every Style; None Threatens Them', weight: 1, tier: 'C-', score: 30, color: 'var(--tier-c-minus)' },
  { label: 'Moves Are Too Fast for Most to Document', weight: 1, tier: 'C-', score: 30, color: 'var(--tier-c-minus)' },
  { label: 'Fights Armies for Fun', weight: 1, tier: 'C-', score: 30, color: 'var(--tier-c-minus)' },
  { label: 'Invented a Fighting Style Per Opponent', weight: 1, tier: 'C-', score: 30, color: 'var(--tier-c-minus)' },
  { label: 'Wins by Just Existing in Combat Space', weight: 1, tier: 'C-', score: 30, color: 'var(--tier-c-minus)' },
  { label: 'Fought Fate and Won on Points', weight: 1, tier: 'C-', score: 30, color: 'var(--tier-c-minus)' },
  { label: 'Enemies Surrender on Sight', weight: 1, tier: 'C-', score: 30, color: 'var(--tier-c-minus)' },
  { label: 'Every Move Is a Signature Move', weight: 1, tier: 'C-', score: 30, color: 'var(--tier-c-minus)' },
  { label: 'No Opponent Has Come Close', weight: 1, tier: 'C-', score: 30, color: 'var(--tier-c-minus)' },
  { label: 'Combat Mastery: Officially Without Peer', weight: 1, tier: 'C-', score: 30, color: 'var(--tier-c-minus)' },

  // C (score: 34)
  { label: 'Transcendent Warrior', weight: 1, tier: 'C', score: 34, color: 'var(--tier-c)' },
  { label: 'Strikes Displace Shockwaves', weight: 1, tier: 'C', score: 34, color: 'var(--tier-c)' },
  { label: 'Fights Entire Armies to a Draw Alone', weight: 1, tier: 'C', score: 34, color: 'var(--tier-c)' },
  { label: 'Moves Exist Outside Normal Combat Frames', weight: 1, tier: 'C', score: 34, color: 'var(--tier-c)' },
  { label: 'Has a Style So Advanced It Renamed Itself', weight: 1, tier: 'C', score: 34, color: 'var(--tier-c)' },
  { label: 'Fighting Is Just Performance at This Level', weight: 1, tier: 'C', score: 34, color: 'var(--tier-c)' },
  { label: 'Neutralizes Supernatural Threats Mundanely', weight: 1, tier: 'C', score: 34, color: 'var(--tier-c)' },
  { label: 'Broke Reality Making a Point Mid-Fight', weight: 1, tier: 'C', score: 34, color: 'var(--tier-c)' },
  { label: 'Has a Personalized Nemesis by Now', weight: 1, tier: 'C', score: 34, color: 'var(--tier-c)' },
  { label: 'Opponents Are Objects to Rearrange', weight: 1, tier: 'C', score: 34, color: 'var(--tier-c)' },
  { label: 'Gods Were Concerned in Early Fights', weight: 1, tier: 'C', score: 34, color: 'var(--tier-c)' },
  { label: 'Wins Arguments by Demonstrating', weight: 1, tier: 'C', score: 34, color: 'var(--tier-c)' },
  { label: 'Could Fight a Concept and Win', weight: 1, tier: 'C', score: 34, color: 'var(--tier-c)' },
  { label: 'Has a Fighting Move Named After a Location They Destroyed', weight: 1, tier: 'C', score: 34, color: 'var(--tier-c)' },
  { label: 'Hits Opponents Who Haven\'t Moved Yet', weight: 1, tier: 'C', score: 34, color: 'var(--tier-c)' },
  { label: 'Combat Leaves Craters Now', weight: 1, tier: 'C', score: 34, color: 'var(--tier-c)' },
  { label: 'Wrote the Book on Combat (Accidentally)', weight: 1, tier: 'C', score: 34, color: 'var(--tier-c)' },
  { label: 'Invented Stances That Have No Counters', weight: 1, tier: 'C', score: 34, color: 'var(--tier-c)' },
  { label: 'Fights Are One-Sided From Minute One', weight: 1, tier: 'C', score: 34, color: 'var(--tier-c)' },
  { label: 'Combat Presence Tangibly Affects the Physics', weight: 1, tier: 'C', score: 34, color: 'var(--tier-c)' },

  // C+ (score: 38)
  { label: 'Mythological Combat Level', weight: 1, tier: 'C+', score: 38, color: 'var(--tier-c-plus)' },
  { label: 'One Strike Ends Mountains', weight: 1, tier: 'C+', score: 38, color: 'var(--tier-c-plus)' },
  { label: 'Has Fought Death Itself (Twice)', weight: 1, tier: 'C+', score: 38, color: 'var(--tier-c-plus)' },
  { label: 'Combat Style Is Its Own Force of Nature', weight: 1, tier: 'C+', score: 38, color: 'var(--tier-c-plus)' },
  { label: 'Wars Ended by Their Entry Into the Field', weight: 1, tier: 'C+', score: 38, color: 'var(--tier-c-plus)' },
  { label: 'Even Gods Stopped to Watch Once', weight: 1, tier: 'C+', score: 38, color: 'var(--tier-c-plus)' },
  { label: 'Strikes Resonate Across Parallel Battles', weight: 1, tier: 'C+', score: 38, color: 'var(--tier-c-plus)' },
  { label: 'Defeated a Deity Who Was Ready for Them', weight: 1, tier: 'C+', score: 38, color: 'var(--tier-c-plus)' },
  { label: 'Combat Precision Reroutes Rivers', weight: 1, tier: 'C+', score: 38, color: 'var(--tier-c-plus)' },
  { label: 'Fighting Style Named After a Disaster', weight: 1, tier: 'C+', score: 38, color: 'var(--tier-c-plus)' },
  { label: 'Opponent Count: Stopped Keeping Track', weight: 1, tier: 'C+', score: 38, color: 'var(--tier-c-plus)' },
  { label: 'Known in Dimensions That Fear Combat', weight: 1, tier: 'C+', score: 38, color: 'var(--tier-c-plus)' },
  { label: 'Invented a Move That Was Banned From Timelines', weight: 1, tier: 'C+', score: 38, color: 'var(--tier-c-plus)' },
  { label: 'Fights Concepts and Wins on Technicalities', weight: 1, tier: 'C+', score: 38, color: 'var(--tier-c-plus)' },
  { label: 'Rewrites Combat Theory by Existing', weight: 1, tier: 'C+', score: 38, color: 'var(--tier-c-plus)' },
  { label: 'Even Reality Flinches When They Wind Up', weight: 1, tier: 'C+', score: 38, color: 'var(--tier-c-plus)' },
  { label: 'Took on All Pantheons Simultaneously — Once', weight: 1, tier: 'C+', score: 38, color: 'var(--tier-c-plus)' },
  { label: 'Their Combat Presence Has a Kill Radius', weight: 1, tier: 'C+', score: 38, color: 'var(--tier-c-plus)' },
  { label: 'Victories Are Measured in Geological Terms', weight: 1, tier: 'C+', score: 38, color: 'var(--tier-c-plus)' },
  { label: 'Punches That Leave Dents in History', weight: 1, tier: 'C+', score: 38, color: 'var(--tier-c-plus)' },

  // B- (score: 42)
  { label: 'World-Ender Class Fighter', weight: 1, tier: 'B-', score: 42, color: 'var(--tier-b-minus)' },
  { label: 'Strikes Ripple Through the Timestream', weight: 1, tier: 'B-', score: 42, color: 'var(--tier-b-minus)' },
  { label: 'Has No Peers Left', weight: 1, tier: 'B-', score: 42, color: 'var(--tier-b-minus)' },
  { label: 'No Style Can Counter Theirs', weight: 1, tier: 'B-', score: 42, color: 'var(--tier-b-minus)' },
  { label: 'Fought All of History and Won', weight: 1, tier: 'B-', score: 42, color: 'var(--tier-b-minus)' },
  { label: 'Gods Trained Under Them', weight: 1, tier: 'B-', score: 42, color: 'var(--tier-b-minus)' },
  { label: 'Their Fighting Stance Cracked the Sky', weight: 1, tier: 'B-', score: 42, color: 'var(--tier-b-minus)' },
  { label: 'Killed the Concept of a Fair Fight', weight: 1, tier: 'B-', score: 42, color: 'var(--tier-b-minus)' },
  { label: 'Combat Resonance Across All Dimensions', weight: 1, tier: 'B-', score: 42, color: 'var(--tier-b-minus)' },
  { label: 'Fights Are Now Seismic Events', weight: 1, tier: 'B-', score: 42, color: 'var(--tier-b-minus)' },
  { label: 'Defeats Abstract Opponents', weight: 1, tier: 'B-', score: 42, color: 'var(--tier-b-minus)' },
  { label: 'Every Reality Respects the Win Record', weight: 1, tier: 'B-', score: 42, color: 'var(--tier-b-minus)' },
  { label: 'Causes Extinction Events in Practice Matches', weight: 1, tier: 'B-', score: 42, color: 'var(--tier-b-minus)' },
  { label: 'Opponent: Physics. Result: Win.', weight: 1, tier: 'B-', score: 42, color: 'var(--tier-b-minus)' },
  { label: 'Has a Villain Who Exists Just to Fight Them', weight: 1, tier: 'B-', score: 42, color: 'var(--tier-b-minus)' },
  { label: 'Their Punches Are Historical Events', weight: 1, tier: 'B-', score: 42, color: 'var(--tier-b-minus)' },
  { label: 'Fought Time and Knocked It Out', weight: 1, tier: 'B-', score: 42, color: 'var(--tier-b-minus)' },
  { label: 'Combat Instincts Predate Combat', weight: 1, tier: 'B-', score: 42, color: 'var(--tier-b-minus)' },
  { label: 'Fighting Style Is a Natural Disaster With Intent', weight: 1, tier: 'B-', score: 42, color: 'var(--tier-b-minus)' },
  { label: 'Multiversal Combat Record: Unbeaten', weight: 1, tier: 'B-', score: 42, color: 'var(--tier-b-minus)' },

  // B (score: 47)
  { label: 'Omniversal Warrior Class', weight: 1, tier: 'B', score: 47, color: 'var(--tier-b)' },
  { label: 'Defeats Concepts in Single Combat', weight: 1, tier: 'B', score: 47, color: 'var(--tier-b)' },
  { label: 'Their Techniques Altered Physics to Accommodate', weight: 1, tier: 'B', score: 47, color: 'var(--tier-b)' },
  { label: 'Fought Reality and Called It Warm-Up', weight: 1, tier: 'B', score: 47, color: 'var(--tier-b)' },
  { label: 'No Training Arena Can Hold Them', weight: 1, tier: 'B', score: 47, color: 'var(--tier-b)' },
  { label: 'One Punch Can End Epochs', weight: 1, tier: 'B', score: 47, color: 'var(--tier-b)' },
  { label: 'Combat Is Art — Terrifying Art', weight: 1, tier: 'B', score: 47, color: 'var(--tier-b)' },
  { label: 'Omniversal Threat Rating: Maximum', weight: 1, tier: 'B', score: 47, color: 'var(--tier-b)' },
  { label: 'Even the Concept of "Fighting" Lost to Them', weight: 1, tier: 'B', score: 47, color: 'var(--tier-b)' },
  { label: 'Battles Are Logged as Natural Disasters', weight: 1, tier: 'B', score: 47, color: 'var(--tier-b)' },
  { label: 'No Reinforcements Would Have Helped', weight: 1, tier: 'B', score: 47, color: 'var(--tier-b)' },
  { label: 'Multiversal Armies Wouldn\'t Be Enough', weight: 1, tier: 'B', score: 47, color: 'var(--tier-b)' },
  { label: 'Fought Every Dimension; None Gave Trouble', weight: 1, tier: 'B', score: 47, color: 'var(--tier-b)' },
  { label: 'Has a Body Count They Don\'t Discuss', weight: 1, tier: 'B', score: 47, color: 'var(--tier-b)' },
  { label: 'Their Stance Destroyed a Moon Once', weight: 1, tier: 'B', score: 47, color: 'var(--tier-b)' },
  { label: 'Physics Filed a Complaint', weight: 1, tier: 'B', score: 47, color: 'var(--tier-b)' },
  { label: 'Gods Fear the Rematch', weight: 1, tier: 'B', score: 47, color: 'var(--tier-b)' },
  { label: 'Combat Instinct Predates the Universe', weight: 1, tier: 'B', score: 47, color: 'var(--tier-b)' },
  { label: 'Their Punches Are Cited in Physics Papers (Cautiously)', weight: 1, tier: 'B', score: 47, color: 'var(--tier-b)' },
  { label: 'Beat Every Version of Themselves Too', weight: 1, tier: 'B', score: 47, color: 'var(--tier-b)' },

  // B+ (score: 52)
  { label: 'Reality-Tier Combatant', weight: 1, tier: 'B+', score: 52, color: 'var(--tier-b-plus)' },
  { label: 'Fights Faster Than Causality', weight: 1, tier: 'B+', score: 52, color: 'var(--tier-b-plus)' },
  { label: 'All Possible Opponents: Defeated', weight: 1, tier: 'B+', score: 52, color: 'var(--tier-b-plus)' },
  { label: 'Strikes Registered in Multiple Timelines', weight: 1, tier: 'B+', score: 52, color: 'var(--tier-b-plus)' },
  { label: 'Won a Fight That Hadn\'t Happened Yet', weight: 1, tier: 'B+', score: 52, color: 'var(--tier-b-plus)' },
  { label: 'Exists in a Combat State All Other States Defer To', weight: 1, tier: 'B+', score: 52, color: 'var(--tier-b-plus)' },
  { label: 'Fighting Them Creates New Legends Automatically', weight: 1, tier: 'B+', score: 52, color: 'var(--tier-b-plus)' },
  { label: 'Won Every Fight Including the Ones They Didn\'t Start', weight: 1, tier: 'B+', score: 52, color: 'var(--tier-b-plus)' },
  { label: 'Defeated Non-Physical Concepts in One Round', weight: 1, tier: 'B+', score: 52, color: 'var(--tier-b-plus)' },
  { label: 'Combat Style Caused a Paradigm Shift in History', weight: 1, tier: 'B+', score: 52, color: 'var(--tier-b-plus)' },
  { label: 'Fought Entropy and Put It on a Timer', weight: 1, tier: 'B+', score: 52, color: 'var(--tier-b-plus)' },
  { label: 'Absolute Tactical Supremacy Across All Realities', weight: 1, tier: 'B+', score: 52, color: 'var(--tier-b-plus)' },
  { label: 'Has No Style — It\'s Now Called "Combat"', weight: 1, tier: 'B+', score: 52, color: 'var(--tier-b-plus)' },
  { label: 'Fights in All Timelines Simultaneously', weight: 1, tier: 'B+', score: 52, color: 'var(--tier-b-plus)' },
  { label: 'Every Known Technique Is Just a Subset of Theirs', weight: 1, tier: 'B+', score: 52, color: 'var(--tier-b-plus)' },
  { label: 'Invented Combat; Perfected It Shortly After', weight: 1, tier: 'B+', score: 52, color: 'var(--tier-b-plus)' },
  { label: 'Reality Itself Doesn\'t Block for Free Anymore', weight: 1, tier: 'B+', score: 52, color: 'var(--tier-b-plus)' },
  { label: 'Omniversal Record: Every Match, Every Outcome', weight: 1, tier: 'B+', score: 52, color: 'var(--tier-b-plus)' },
  { label: 'Stars Shift to Accommodate Their Swings', weight: 1, tier: 'B+', score: 52, color: 'var(--tier-b-plus)' },
  { label: 'Death Rescheduled to Avoid the Fight', weight: 1, tier: 'B+', score: 52, color: 'var(--tier-b-plus)' },

  // A- (score: 57)
  { label: 'Absolute Combat Deity', weight: 1, tier: 'A-', score: 57, color: 'var(--tier-a-minus)' },
  { label: 'Punches Reach the Afterlife', weight: 1, tier: 'A-', score: 57, color: 'var(--tier-a-minus)' },
  { label: 'Fights Are Now Multiversal Incidents', weight: 1, tier: 'A-', score: 57, color: 'var(--tier-a-minus)' },
  { label: 'No Combat System Can Categorize Them', weight: 1, tier: 'A-', score: 57, color: 'var(--tier-a-minus)' },
  { label: 'Defeated the Idea of Being Beaten', weight: 1, tier: 'A-', score: 57, color: 'var(--tier-a-minus)' },
  { label: 'Known in All Layers of Reality as a Threat', weight: 1, tier: 'A-', score: 57, color: 'var(--tier-a-minus)' },
  { label: 'Combat Instinct Predates the Concept of Fighting', weight: 1, tier: 'A-', score: 57, color: 'var(--tier-a-minus)' },
  { label: 'Their Fists Are a Natural Law', weight: 1, tier: 'A-', score: 57, color: 'var(--tier-a-minus)' },
  { label: 'Punched the Void — It Apologized', weight: 1, tier: 'A-', score: 57, color: 'var(--tier-a-minus)' },
  { label: 'Even Paradoxes Don\'t Want This Smoke', weight: 1, tier: 'A-', score: 57, color: 'var(--tier-a-minus)' },
  { label: 'Fights Timelines, Not Opponents', weight: 1, tier: 'A-', score: 57, color: 'var(--tier-a-minus)' },
  { label: 'Has No Stance Because They Are the Stance', weight: 1, tier: 'A-', score: 57, color: 'var(--tier-a-minus)' },
  { label: 'Created Violence and Then Mastered It', weight: 1, tier: 'A-', score: 57, color: 'var(--tier-a-minus)' },
  { label: 'Entire Universes Trained to Contain Them', weight: 1, tier: 'A-', score: 57, color: 'var(--tier-a-minus)' },
  { label: 'The Concept of Losing Doesn\'t Apply', weight: 1, tier: 'A-', score: 57, color: 'var(--tier-a-minus)' },
  { label: 'Fought Every God, Every Timeline, Every Outcome', weight: 1, tier: 'A-', score: 57, color: 'var(--tier-a-minus)' },
  { label: 'Their Strike Echoes Were Felt Before the Universe Cooled', weight: 1, tier: 'A-', score: 57, color: 'var(--tier-a-minus)' },
  { label: 'Combat Expertise: No Longer Measurable', weight: 1, tier: 'A-', score: 57, color: 'var(--tier-a-minus)' },
  { label: 'Won a Fight Against Infinite Versions of Themselves', weight: 1, tier: 'A-', score: 57, color: 'var(--tier-a-minus)' },
  { label: 'Omniversal Win Rate: 100%. No Rematches Scheduled.', weight: 1, tier: 'A-', score: 57, color: 'var(--tier-a-minus)' },

  // A (score: 62)
  { label: 'Transcendent Combat Entity', weight: 1, tier: 'A', score: 62, color: 'var(--tier-a)' },
  { label: 'Fighting Them Ended a War by Discouraging Further Effort', weight: 1, tier: 'A', score: 62, color: 'var(--tier-a)' },
  { label: 'Moves Registered as Geological Events', weight: 1, tier: 'A', score: 62, color: 'var(--tier-a)' },
  { label: 'Absolute Tactical Supremacy — All Realities', weight: 1, tier: 'A', score: 62, color: 'var(--tier-a)' },
  { label: 'Fought the Omniverse and Set Records', weight: 1, tier: 'A', score: 62, color: 'var(--tier-a)' },
  { label: 'Punched the Fabric of Space Tighter', weight: 1, tier: 'A', score: 62, color: 'var(--tier-a)' },
  { label: 'Wins Before the Opponent Exists', weight: 1, tier: 'A', score: 62, color: 'var(--tier-a)' },
  { label: 'The Concept of "Defeat" Has Never Applied', weight: 1, tier: 'A', score: 62, color: 'var(--tier-a)' },
  { label: 'Their Techniques Were Banned by the Omniverse Council', weight: 1, tier: 'A', score: 62, color: 'var(--tier-a)' },
  { label: 'Fought the Original Fighter — Won in Round 1', weight: 1, tier: 'A', score: 62, color: 'var(--tier-a)' },
  { label: 'Caused Existential Crises by Just Fighting Well', weight: 1, tier: 'A', score: 62, color: 'var(--tier-a)' },
  { label: 'Fighting Style: Classified Cosmic Threat', weight: 1, tier: 'A', score: 62, color: 'var(--tier-a)' },
  { label: 'Destroyed the Concept of "Invincible" Opponents', weight: 1, tier: 'A', score: 62, color: 'var(--tier-a)' },
  { label: 'Fights With All of History Behind Each Strike', weight: 1, tier: 'A', score: 62, color: 'var(--tier-a)' },
  { label: 'The Omniverse Added Extra Rules for Them', weight: 1, tier: 'A', score: 62, color: 'var(--tier-a)' },
  { label: 'Finished a Fight Before It Was Scheduled', weight: 1, tier: 'A', score: 62, color: 'var(--tier-a)' },
  { label: 'Omniversal Martial Arts Hall of Fame — Sole Member', weight: 1, tier: 'A', score: 62, color: 'var(--tier-a)' },
  { label: 'Invented the Last Fighting Technique', weight: 1, tier: 'A', score: 62, color: 'var(--tier-a)' },
  { label: 'Even Victory Fears Them', weight: 1, tier: 'A', score: 62, color: 'var(--tier-a)' },
  { label: 'Combat Mastery: Final Form. No Further Tiers.', weight: 1, tier: 'A', score: 62, color: 'var(--tier-a)' },

  // A+ (score: 67)
  { label: 'The Living Weapon', weight: 1, tier: 'A+', score: 67, color: 'var(--tier-a-plus)' },
  { label: 'Fighting Is Breathing — Both Are Effortless', weight: 1, tier: 'A+', score: 67, color: 'var(--tier-a-plus)' },
  { label: 'Omniversal Combat Perfect Score', weight: 1, tier: 'A+', score: 67, color: 'var(--tier-a-plus)' },
  { label: 'Their Presence Ended Multiple Wars at Once', weight: 1, tier: 'A+', score: 67, color: 'var(--tier-a-plus)' },
  { label: 'Struck a Timeline and Rerouted It', weight: 1, tier: 'A+', score: 67, color: 'var(--tier-a-plus)' },
  { label: 'Fights Causal Structures and Wins', weight: 1, tier: 'A+', score: 67, color: 'var(--tier-a-plus)' },
  { label: 'Fists That Have Rights Under Cosmic Law', weight: 1, tier: 'A+', score: 67, color: 'var(--tier-a-plus)' },
  { label: 'Defeated All Possible Futures in Combat', weight: 1, tier: 'A+', score: 67, color: 'var(--tier-a-plus)' },
  { label: 'No Technique Has Ever Worked on Them', weight: 1, tier: 'A+', score: 67, color: 'var(--tier-a-plus)' },
  { label: 'Even the Void Won\'t Fight Them', weight: 1, tier: 'A+', score: 67, color: 'var(--tier-a-plus)' },
  { label: 'Fighting Style: Renamed "Inevitable"', weight: 1, tier: 'A+', score: 67, color: 'var(--tier-a-plus)' },
  { label: 'All Combat Comes From What They Started', weight: 1, tier: 'A+', score: 67, color: 'var(--tier-a-plus)' },
  { label: 'Omniversal Winner Before Time Began', weight: 1, tier: 'A+', score: 67, color: 'var(--tier-a-plus)' },
  { label: 'Opponent Count: All. Win Rate: All.', weight: 1, tier: 'A+', score: 67, color: 'var(--tier-a-plus)' },
  { label: 'Invented "Ending It Quickly" as a Mercy', weight: 1, tier: 'A+', score: 67, color: 'var(--tier-a-plus)' },
  { label: 'Pre-Existence Already Had Them on Threat Watch', weight: 1, tier: 'A+', score: 67, color: 'var(--tier-a-plus)' },
  { label: 'Their Strikes Are Measured in Civilizations Displaced', weight: 1, tier: 'A+', score: 67, color: 'var(--tier-a-plus)' },
  { label: 'Defeated Gods Who Were Ready for It', weight: 1, tier: 'A+', score: 67, color: 'var(--tier-a-plus)' },
  { label: 'Rewrote What "Skilled" Means by Existing', weight: 1, tier: 'A+', score: 67, color: 'var(--tier-a-plus)' },
  { label: 'Omniversal Champion — All Dimensions — Simultaneous', weight: 1, tier: 'A+', score: 67, color: 'var(--tier-a-plus)' },

  // S- (score: 72)
  { label: 'Absolute Combat Apex', weight: 1, tier: 'S-', score: 72, color: 'var(--tier-s-minus)' },
  { label: 'Fights Outside Time', weight: 1, tier: 'S-', score: 72, color: 'var(--tier-s-minus)' },
  { label: 'Combat Mastery: Omniversal Maximum', weight: 1, tier: 'S-', score: 72, color: 'var(--tier-s-minus)' },
  { label: 'Invented the First Strike and the Last', weight: 1, tier: 'S-', score: 72, color: 'var(--tier-s-minus)' },
  { label: 'The Universe Had to Invent Rules to Handle Them', weight: 1, tier: 'S-', score: 72, color: 'var(--tier-s-minus)' },
  { label: 'Omniversal Win Record: Infinite', weight: 1, tier: 'S-', score: 72, color: 'var(--tier-s-minus)' },
  { label: 'Caused Void to Flinch', weight: 1, tier: 'S-', score: 72, color: 'var(--tier-s-minus)' },
  { label: 'Fighting Them Is a Religious Experience', weight: 1, tier: 'S-', score: 72, color: 'var(--tier-s-minus)' },
  { label: 'Punches Echo in Pre-Time', weight: 1, tier: 'S-', score: 72, color: 'var(--tier-s-minus)' },
  { label: 'Every Combat Technique Is a Descendant of Theirs', weight: 1, tier: 'S-', score: 72, color: 'var(--tier-s-minus)' },
  { label: 'Wins All Combat — Including the Ones They Sat Out', weight: 1, tier: 'S-', score: 72, color: 'var(--tier-s-minus)' },
  { label: 'Has No Known Weakness in Any Universe', weight: 1, tier: 'S-', score: 72, color: 'var(--tier-s-minus)' },
  { label: 'Fighting Is Simply What They Are', weight: 1, tier: 'S-', score: 72, color: 'var(--tier-s-minus)' },
  { label: 'Combat Became a Law of Physics After Them', weight: 1, tier: 'S-', score: 72, color: 'var(--tier-s-minus)' },
  { label: 'Even the Heat Death Won\'t Risk It', weight: 1, tier: 'S-', score: 72, color: 'var(--tier-s-minus)' },
  { label: 'Created New Forms of Pain Nobody Had Names For', weight: 1, tier: 'S-', score: 72, color: 'var(--tier-s-minus)' },
  { label: 'Defeated All Versions of Themselves in Parallel', weight: 1, tier: 'S-', score: 72, color: 'var(--tier-s-minus)' },
  { label: 'Every Universe Adjusted Physics Around Their Moves', weight: 1, tier: 'S-', score: 72, color: 'var(--tier-s-minus)' },
  { label: 'Their Warm-Up Destabilizes Realities', weight: 1, tier: 'S-', score: 72, color: 'var(--tier-s-minus)' },
  { label: 'The Last Fighter Needed for Anything', weight: 1, tier: 'S-', score: 72, color: 'var(--tier-s-minus)' },

  // S (score: 77)
  { label: 'Combat God', weight: 1, tier: 'S', score: 77, color: 'var(--tier-s)' },
  { label: 'Exists Outside Any Fighting System', weight: 1, tier: 'S', score: 77, color: 'var(--tier-s)' },
  { label: 'Strikes Reach Causality\'s Foundation', weight: 1, tier: 'S', score: 77, color: 'var(--tier-s)' },
  { label: 'Created Combat; Hasn\'t Lost Since', weight: 1, tier: 'S', score: 77, color: 'var(--tier-s)' },
  { label: 'Their Training Regimen Collapsed a Star', weight: 1, tier: 'S', score: 77, color: 'var(--tier-s)' },
  { label: 'Omniversal Sole Combat Authority', weight: 1, tier: 'S', score: 77, color: 'var(--tier-s)' },
  { label: 'Every Victory Is Over Something That Shouldn\'t Be Beatable', weight: 1, tier: 'S', score: 77, color: 'var(--tier-s)' },
  { label: 'Fighting Style: "Extinction-Adjacent"', weight: 1, tier: 'S', score: 77, color: 'var(--tier-s)' },
  { label: 'Even Infinite Armies Were Not Enough', weight: 1, tier: 'S', score: 77, color: 'var(--tier-s)' },
  { label: 'Wrote the Final Chapter in All Martial History', weight: 1, tier: 'S', score: 77, color: 'var(--tier-s)' },
  { label: 'All Combat Since Theirs Is Fan Fiction', weight: 1, tier: 'S', score: 77, color: 'var(--tier-s)' },
  { label: 'Has Never Taken Damage From Anything', weight: 1, tier: 'S', score: 77, color: 'var(--tier-s)' },
  { label: 'Battles Are Just Pre-Arranged Losses for Everyone Else', weight: 1, tier: 'S', score: 77, color: 'var(--tier-s)' },
  { label: 'Pre-Universal Warriors Feared the Prophecy of Them', weight: 1, tier: 'S', score: 77, color: 'var(--tier-s)' },
  { label: 'Knows How to Win Every Fight Including Ones Not Invented Yet', weight: 1, tier: 'S', score: 77, color: 'var(--tier-s)' },
  { label: 'Their Punches Are Cited as Evidence of Chaos Theory', weight: 1, tier: 'S', score: 77, color: 'var(--tier-s)' },
  { label: 'Omniversal Combat Record: No Close Matches', weight: 1, tier: 'S', score: 77, color: 'var(--tier-s)' },
  { label: 'Their Stance Is a Sacred Geometry', weight: 1, tier: 'S', score: 77, color: 'var(--tier-s)' },
  { label: 'Won in Every Possible Timeline by Default', weight: 1, tier: 'S', score: 77, color: 'var(--tier-s)' },
  { label: 'The Universe Filed Them Under "Unchallengeable"', weight: 1, tier: 'S', score: 77, color: 'var(--tier-s)' },

  // S+ (score: 81)
  { label: 'Omniversal Combat Supreme', weight: 1, tier: 'S+', score: 81, color: 'var(--tier-s-plus)' },
  { label: 'Defeats Non-Existent Opponents', weight: 1, tier: 'S+', score: 81, color: 'var(--tier-s-plus)' },
  { label: 'Pre-Reality Was Afraid of the Match', weight: 1, tier: 'S+', score: 81, color: 'var(--tier-s-plus)' },
  { label: 'Cosmic Win Rate: 100% Across All Simulations', weight: 1, tier: 'S+', score: 81, color: 'var(--tier-s-plus)' },
  { label: 'Their Combat Style Is a Natural Force', weight: 1, tier: 'S+', score: 81, color: 'var(--tier-s-plus)' },
  { label: 'Won the First Battle Before The Universe Formed', weight: 1, tier: 'S+', score: 81, color: 'var(--tier-s-plus)' },
  { label: 'Has Mastered Every Move That Will Ever Exist', weight: 1, tier: 'S+', score: 81, color: 'var(--tier-s-plus)' },
  { label: 'Punches That Reset Entropy Counters', weight: 1, tier: 'S+', score: 81, color: 'var(--tier-s-plus)' },
  { label: 'Gods Yield Before the Match', weight: 1, tier: 'S+', score: 81, color: 'var(--tier-s-plus)' },
  { label: 'No Concept of Losing Applicable Here', weight: 1, tier: 'S+', score: 81, color: 'var(--tier-s-plus)' },
  { label: 'Fights Ended the Timelines They Occurred In', weight: 1, tier: 'S+', score: 81, color: 'var(--tier-s-plus)' },
  { label: 'Even the Concept of "Fair" Doesn\'t Apply', weight: 1, tier: 'S+', score: 81, color: 'var(--tier-s-plus)' },
  { label: 'Every Technique in Existence: Known and Surpassed', weight: 1, tier: 'S+', score: 81, color: 'var(--tier-s-plus)' },
  { label: 'Pre-Combat Presence Alone Causes Damage', weight: 1, tier: 'S+', score: 81, color: 'var(--tier-s-plus)' },
  { label: 'Their Shadow Has a Higher Win Rate Than Most', weight: 1, tier: 'S+', score: 81, color: 'var(--tier-s-plus)' },
  { label: 'Combat Instinct Predates the Concept of Consciousness', weight: 1, tier: 'S+', score: 81, color: 'var(--tier-s-plus)' },
  { label: 'Cosmic Entities Consider Them a Peer', weight: 1, tier: 'S+', score: 81, color: 'var(--tier-s-plus)' },
  { label: 'Omniversal Champion at Everything, Simultaneously', weight: 1, tier: 'S+', score: 81, color: 'var(--tier-s-plus)' },
  { label: 'Beat Every Opponent — Including Those Not Yet Invented', weight: 1, tier: 'S+', score: 81, color: 'var(--tier-s-plus)' },
  { label: 'Fighting Them Is Classified as a Cosmological Event', weight: 1, tier: 'S+', score: 81, color: 'var(--tier-s-plus)' },

  // SS- (score: 85)
  { label: 'Primordial Combatant', weight: 1, tier: 'SS-', score: 85, color: 'var(--tier-ss-minus)' },
  { label: 'Existed to Fight Before Existence Existed', weight: 1, tier: 'SS-', score: 85, color: 'var(--tier-ss-minus)' },
  { label: 'No Being Has Landed a Strike', weight: 1, tier: 'SS-', score: 85, color: 'var(--tier-ss-minus)' },
  { label: 'Invented Every Martial Art Before Being Born', weight: 1, tier: 'SS-', score: 85, color: 'var(--tier-ss-minus)' },
  { label: 'Omniversal Combat Record: No Opponents Found Worthy', weight: 1, tier: 'SS-', score: 85, color: 'var(--tier-ss-minus)' },
  { label: 'Their Strikes Pre-Date Time', weight: 1, tier: 'SS-', score: 85, color: 'var(--tier-ss-minus)' },
  { label: 'Punched the Void — The Void Changed Directions', weight: 1, tier: 'SS-', score: 85, color: 'var(--tier-ss-minus)' },
  { label: 'Combat Is Not a Skill — It\'s Their Identity', weight: 1, tier: 'SS-', score: 85, color: 'var(--tier-ss-minus)' },
  { label: 'Lost Nothing Across All Infinities', weight: 1, tier: 'SS-', score: 85, color: 'var(--tier-ss-minus)' },
  { label: 'The Fabric of Reality Has Scars From Their Training', weight: 1, tier: 'SS-', score: 85, color: 'var(--tier-ss-minus)' },
  { label: 'All Fighting Styles Are Wrong; They Are Correct', weight: 1, tier: 'SS-', score: 85, color: 'var(--tier-ss-minus)' },
  { label: 'Pre-Universal Combat Champion', weight: 1, tier: 'SS-', score: 85, color: 'var(--tier-ss-minus)' },
  { label: 'Even Gods Concede First', weight: 1, tier: 'SS-', score: 85, color: 'var(--tier-ss-minus)' },
  { label: 'Beat Every Dimension Before Visiting', weight: 1, tier: 'SS-', score: 85, color: 'var(--tier-ss-minus)' },
  { label: 'Their Defeat Is Not a Concept Physics Supports', weight: 1, tier: 'SS-', score: 85, color: 'var(--tier-ss-minus)' },
  { label: 'Fights in All Possible Timelines at Once', weight: 1, tier: 'SS-', score: 85, color: 'var(--tier-ss-minus)' },
  { label: 'Won Every Future Battle Before It Was Scheduled', weight: 1, tier: 'SS-', score: 85, color: 'var(--tier-ss-minus)' },
  { label: 'Omniversal Threat Assessment: "Inconceivable"', weight: 1, tier: 'SS-', score: 85, color: 'var(--tier-ss-minus)' },
  { label: 'Causes Battles to Pre-Surrender Across Timelines', weight: 1, tier: 'SS-', score: 85, color: 'var(--tier-ss-minus)' },
  { label: 'Their Fighting Wrote The Physical Laws Governing Violence', weight: 1, tier: 'SS-', score: 85, color: 'var(--tier-ss-minus)' },

  // SS (score: 88)
  { label: 'The Living Fight', weight: 1, tier: 'SS', score: 88, color: 'var(--tier-ss)' },
  { label: 'Combat Perfection — Absolute', weight: 1, tier: 'SS', score: 88, color: 'var(--tier-ss)' },
  { label: 'Defeated the Concept of Combat to Prove a Point', weight: 1, tier: 'SS', score: 88, color: 'var(--tier-ss)' },
  { label: 'No Opponent Has Ever Scored a Point', weight: 1, tier: 'SS', score: 88, color: 'var(--tier-ss)' },
  { label: 'Omniversal Unchallenged Combatant', weight: 1, tier: 'SS', score: 88, color: 'var(--tier-ss)' },
  { label: 'All Reality Considers Them Unbeatable', weight: 1, tier: 'SS', score: 88, color: 'var(--tier-ss)' },
  { label: 'Their Footsteps Are Registered as Attacks', weight: 1, tier: 'SS', score: 88, color: 'var(--tier-ss)' },
  { label: 'Even Mathematics Yields to Their Strike Vectors', weight: 1, tier: 'SS', score: 88, color: 'var(--tier-ss)' },
  { label: 'Invented Combat Before Anything Could Fight Back', weight: 1, tier: 'SS', score: 88, color: 'var(--tier-ss)' },
  { label: 'Punched the Origin Point of Violence — It Agreed', weight: 1, tier: 'SS', score: 88, color: 'var(--tier-ss)' },
  { label: 'No Entity in the Omniverse Has Survived Round 1', weight: 1, tier: 'SS', score: 88, color: 'var(--tier-ss)' },
  { label: 'Won Every Match in Every Possible Universe Simultaneously', weight: 1, tier: 'SS', score: 88, color: 'var(--tier-ss)' },
  { label: 'Fighting Style: Renamed "The End"', weight: 1, tier: 'SS', score: 88, color: 'var(--tier-ss)' },
  { label: 'Omniversal Combat Master — No Category Could Contain Them', weight: 1, tier: 'SS', score: 88, color: 'var(--tier-ss)' },
  { label: 'Defeated the Last Possible Opponent: Themselves. Won.', weight: 1, tier: 'SS', score: 88, color: 'var(--tier-ss)' },
  { label: 'The Concept of Fighting Surrendered to Them', weight: 1, tier: 'SS', score: 88, color: 'var(--tier-ss)' },
  { label: 'All Combat Theory Was Derived From Their Movements', weight: 1, tier: 'SS', score: 88, color: 'var(--tier-ss)' },
  { label: 'The Void Filed a Restraining Order', weight: 1, tier: 'SS', score: 88, color: 'var(--tier-ss)' },
  { label: 'Trained Since Before Physics Had Constants', weight: 1, tier: 'SS', score: 88, color: 'var(--tier-ss)' },
  { label: 'Omniversal Fear Rating: "Please Don\'t"', weight: 1, tier: 'SS', score: 88, color: 'var(--tier-ss)' },

  // SS+ (score: 91)
  { label: 'Perfect Combatant — All Senses', weight: 1, tier: 'SS+', score: 91, color: 'var(--tier-ss-plus)' },
  { label: 'Combat Is Just Gravity Here — Inescapable', weight: 1, tier: 'SS+', score: 91, color: 'var(--tier-ss-plus)' },
  { label: 'Exists at a Level Where All Others Are Amateurs', weight: 1, tier: 'SS+', score: 91, color: 'var(--tier-ss-plus)' },
  { label: 'Reality Pauses When They Wind Up', weight: 1, tier: 'SS+', score: 91, color: 'var(--tier-ss-plus)' },
  { label: 'Omniversal Fight Outcome: Always the Same', weight: 1, tier: 'SS+', score: 91, color: 'var(--tier-ss-plus)' },
  { label: 'Defeated Every Future Opponent Before the Fight', weight: 1, tier: 'SS+', score: 91, color: 'var(--tier-ss-plus)' },
  { label: 'Won Before the Universe Knew There Was a Match', weight: 1, tier: 'SS+', score: 91, color: 'var(--tier-ss-plus)' },
  { label: 'Their Strikes Are Founding Events of Cosmologies', weight: 1, tier: 'SS+', score: 91, color: 'var(--tier-ss-plus)' },
  { label: 'No Timeline Shows Them Losing', weight: 1, tier: 'SS+', score: 91, color: 'var(--tier-ss-plus)' },
  { label: 'The Omniverse Pre-Surrendered to Save Time', weight: 1, tier: 'SS+', score: 91, color: 'var(--tier-ss-plus)' },
  { label: 'Every Dimension Has Signed the Concession', weight: 1, tier: 'SS+', score: 91, color: 'var(--tier-ss-plus)' },
  { label: 'Invented All Combat — Before Being Born', weight: 1, tier: 'SS+', score: 91, color: 'var(--tier-ss-plus)' },
  { label: 'Fighting Style Cannot Be Mimicked — Laws of Physics Prohibit It', weight: 1, tier: 'SS+', score: 91, color: 'var(--tier-ss-plus)' },
  { label: 'Even the Concept of "Power" Yields to Their Style', weight: 1, tier: 'SS+', score: 91, color: 'var(--tier-ss-plus)' },
  { label: 'Won the Primordial Fight That Created Combat', weight: 1, tier: 'SS+', score: 91, color: 'var(--tier-ss-plus)' },
  { label: 'Pre-Time Record: Undefeated', weight: 1, tier: 'SS+', score: 91, color: 'var(--tier-ss-plus)' },
  { label: 'The Universe\'s Ranking System Simply Returns "N/A"', weight: 1, tier: 'SS+', score: 91, color: 'var(--tier-ss-plus)' },
  { label: 'All Possible Combat: Won in Advance', weight: 1, tier: 'SS+', score: 91, color: 'var(--tier-ss-plus)' },
  { label: 'Authored the First and Last Martial Law', weight: 1, tier: 'SS+', score: 91, color: 'var(--tier-ss-plus)' },
  { label: 'Omniversal Apex — No Further Rankings Applicable', weight: 1, tier: 'SS+', score: 91, color: 'var(--tier-ss-plus)' },

  // SSS- (score: 94)
  { label: 'Pre-Universal Combat Legend', weight: 1, tier: 'SSS-', score: 94, color: 'var(--tier-sss-minus)' },
  { label: 'Defined Combat by Being Its First Practitioner', weight: 1, tier: 'SSS-', score: 94, color: 'var(--tier-sss-minus)' },
  { label: 'Won Before the Concept of "Winning" Was Created', weight: 1, tier: 'SSS-', score: 94, color: 'var(--tier-sss-minus)' },
  { label: 'The Entire Omniverse Is Their Sparring History', weight: 1, tier: 'SSS-', score: 94, color: 'var(--tier-sss-minus)' },
  { label: 'Fighting Them Is A Philosophical Footnote', weight: 1, tier: 'SSS-', score: 94, color: 'var(--tier-sss-minus)' },
  { label: 'Never Lost. Never Will. That\'s Not How They Work.', weight: 1, tier: 'SSS-', score: 94, color: 'var(--tier-sss-minus)' },
  { label: 'Invented Violence by Accident, Then Perfected It', weight: 1, tier: 'SSS-', score: 94, color: 'var(--tier-sss-minus)' },
  { label: 'All Martial Arts Are Degraded Copies of Their Style', weight: 1, tier: 'SSS-', score: 94, color: 'var(--tier-sss-minus)' },
  { label: 'Their Punches Have Personal Pronouns in Cosmological Law', weight: 1, tier: 'SSS-', score: 94, color: 'var(--tier-sss-minus)' },
  { label: 'Gods Created Themselves to Eventually Lose to Them', weight: 1, tier: 'SSS-', score: 94, color: 'var(--tier-sss-minus)' },
  { label: 'Omniversal Perfect Record — No Exceptions — All Time', weight: 1, tier: 'SSS-', score: 94, color: 'var(--tier-sss-minus)' },
  { label: 'Their Fighting Filled in the Blanks of Causality', weight: 1, tier: 'SSS-', score: 94, color: 'var(--tier-sss-minus)' },
  { label: 'Beat Every Version of Every Opponent in Every Timeline', weight: 1, tier: 'SSS-', score: 94, color: 'var(--tier-sss-minus)' },
  { label: 'Pre-Existence Was Already Their Sparring Partner', weight: 1, tier: 'SSS-', score: 94, color: 'var(--tier-sss-minus)' },
  { label: 'The Final Fighting Style Was Named After Them', weight: 1, tier: 'SSS-', score: 94, color: 'var(--tier-sss-minus)' },
  { label: 'Created the Martial Form That Ended All Debates', weight: 1, tier: 'SSS-', score: 94, color: 'var(--tier-sss-minus)' },
  { label: 'Was the Reason the Rules of Engagement Exist', weight: 1, tier: 'SSS-', score: 94, color: 'var(--tier-sss-minus)' },
  { label: 'All Fights Since Theirs Are Tributes', weight: 1, tier: 'SSS-', score: 94, color: 'var(--tier-sss-minus)' },
  { label: 'Combat Itself Kneels Before Them', weight: 1, tier: 'SSS-', score: 94, color: 'var(--tier-sss-minus)' },
  { label: 'Defined "Victory" Before There Was Anything to Win', weight: 1, tier: 'SSS-', score: 94, color: 'var(--tier-sss-minus)' },

  // SSS (score: 97)
  { label: 'Absolute Combatant', weight: 1, tier: 'SSS', score: 97, color: 'var(--tier-sss)' },
  { label: 'Won Every Fight in All Possible Omniverses', weight: 1, tier: 'SSS', score: 97, color: 'var(--tier-sss)' },
  { label: 'Their Technique Created Physics as a Side Effect', weight: 1, tier: 'SSS', score: 97, color: 'var(--tier-sss)' },
  { label: 'Invented Combat — Nobody Else Is Original Since', weight: 1, tier: 'SSS', score: 97, color: 'var(--tier-sss)' },
  { label: 'The Concept of "Skill" Defers to Them', weight: 1, tier: 'SSS', score: 97, color: 'var(--tier-sss)' },
  { label: 'Pre-Universe Record: Unbroken', weight: 1, tier: 'SSS', score: 97, color: 'var(--tier-sss)' },
  { label: 'All Combat in All Dimensions Leads Back to One Match — Theirs', weight: 1, tier: 'SSS', score: 97, color: 'var(--tier-sss)' },
  { label: 'Omniversal Combat Finale: Already Won', weight: 1, tier: 'SSS', score: 97, color: 'var(--tier-sss)' },
  { label: 'Their First Punch Set Physics Into Motion', weight: 1, tier: 'SSS', score: 97, color: 'var(--tier-sss)' },
  { label: 'Fights Time Itself for Fun — Still Wins', weight: 1, tier: 'SSS', score: 97, color: 'var(--tier-sss)' },
  { label: 'No Entity That Has Fought Them Has Won Round 1', weight: 1, tier: 'SSS', score: 97, color: 'var(--tier-sss)' },
  { label: 'Even Infinity Has a Loss on Their Record', weight: 1, tier: 'SSS', score: 97, color: 'var(--tier-sss)' },
  { label: 'Defeated "Impossible" in a Three-Round Match', weight: 1, tier: 'SSS', score: 97, color: 'var(--tier-sss)' },
  { label: 'All Combat Laws Were Written to Describe Them', weight: 1, tier: 'SSS', score: 97, color: 'var(--tier-sss)' },
  { label: 'Their Punches Wrote the Original Laws of Physics', weight: 1, tier: 'SSS', score: 97, color: 'var(--tier-sss)' },
  { label: 'Omniversal Champion: Every Category, Every Epoch', weight: 1, tier: 'SSS', score: 97, color: 'var(--tier-sss)' },
  { label: 'Even Non-Combat Entities Concede by Default', weight: 1, tier: 'SSS', score: 97, color: 'var(--tier-sss)' },
  { label: 'The Universe Named Aggression After Them', weight: 1, tier: 'SSS', score: 97, color: 'var(--tier-sss)' },
  { label: 'Won the Pre-Combat That Seeded All Fighting', weight: 1, tier: 'SSS', score: 97, color: 'var(--tier-sss)' },
  { label: 'Created The Concept of "Unbeatable" by Being It', weight: 1, tier: 'SSS', score: 97, color: 'var(--tier-sss)' },

  // SSS+ (score: 99)
  { label: 'The Perfect Fighter', weight: 1, tier: 'SSS+', score: 99, color: 'var(--tier-sss-plus)' },
  { label: 'Has No Record — Records Were Invented To Describe Them', weight: 1, tier: 'SSS+', score: 99, color: 'var(--tier-sss-plus)' },
  { label: 'All Fighting Is Derivative of One Being: Them', weight: 1, tier: 'SSS+', score: 99, color: 'var(--tier-sss-plus)' },
  { label: 'No Victory Has Been By Chance — All Were Inevitable', weight: 1, tier: 'SSS+', score: 99, color: 'var(--tier-sss-plus)' },
  { label: 'Won the Fight That Created the First Opponent', weight: 1, tier: 'SSS+', score: 99, color: 'var(--tier-sss-plus)' },
  { label: 'Combat Is Not What They Do — It Is What They Are', weight: 1, tier: 'SSS+', score: 99, color: 'var(--tier-sss-plus)' },
  { label: 'Omniversal Singular Combat Supremacy', weight: 1, tier: 'SSS+', score: 99, color: 'var(--tier-sss-plus)' },
  { label: 'Fought the Void. The Void Forfeited.', weight: 1, tier: 'SSS+', score: 99, color: 'var(--tier-sss-plus)' },
  { label: 'No Possible Outcome Includes Their Defeat', weight: 1, tier: 'SSS+', score: 99, color: 'var(--tier-sss-plus)' },
  { label: 'Every Combat Law Was Written Retroactively for Them', weight: 1, tier: 'SSS+', score: 99, color: 'var(--tier-sss-plus)' },
  { label: 'Caused the First Strike — Hasn\'t Stopped Since', weight: 1, tier: 'SSS+', score: 99, color: 'var(--tier-sss-plus)' },
  { label: 'The Word "Fighter" Was Created in Their Honor', weight: 1, tier: 'SSS+', score: 99, color: 'var(--tier-sss-plus)' },
  { label: 'The Origin of All Conflict Is Just Them Training', weight: 1, tier: 'SSS+', score: 99, color: 'var(--tier-sss-plus)' },
  { label: 'Omniversal Martial Summit: Chaired by Them, Won by Them', weight: 1, tier: 'SSS+', score: 99, color: 'var(--tier-sss-plus)' },
  { label: 'All Combat Forms Are Footnotes to Their First Bout', weight: 1, tier: 'SSS+', score: 99, color: 'var(--tier-sss-plus)' },
  { label: 'Even the Void Admits: Impressive', weight: 1, tier: 'SSS+', score: 99, color: 'var(--tier-sss-plus)' },
  { label: 'Absolute Limit of All Fighting Potential', weight: 1, tier: 'SSS+', score: 99, color: 'var(--tier-sss-plus)' },
  { label: 'The First and Last Perfect Combatant', weight: 1, tier: 'SSS+', score: 99, color: 'var(--tier-sss-plus)' },
  { label: 'Undefeated, Undamageable, Unquestioned', weight: 1, tier: 'SSS+', score: 99, color: 'var(--tier-sss-plus)' },
  { label: 'Combat Perfection — Defined, Achieved, Owned', weight: 1, tier: 'SSS+', score: 99, color: 'var(--tier-sss-plus)' },

  // God (score: 100)
  { label: 'Ended Wars by Entering the Zip Code', weight: 1, tier: 'God', score: 100, color: 'var(--tier-god)' },
  { label: 'The Concept of Combat Was Created for Them', weight: 1, tier: 'God', score: 100, color: 'var(--tier-god)' },
  { label: 'Perfected Fighting Before There Was Anything to Fight', weight: 1, tier: 'God', score: 100, color: 'var(--tier-god)' },
  { label: 'Omniversal Singular Apex — No Peer Exists or Will Ever Exist', weight: 1, tier: 'God', score: 100, color: 'var(--tier-god)' },
  { label: 'The Pre-Universe\'s First and Only Loss Was to Them', weight: 1, tier: 'God', score: 100, color: 'var(--tier-god)' },
  { label: 'Their Fights Created the Laws of Physics as a Byproduct', weight: 1, tier: 'God', score: 100, color: 'var(--tier-god)' },
  { label: 'Absolute Combat. No Modifier Needed.', weight: 1, tier: 'God', score: 100, color: 'var(--tier-god)' },
  { label: 'Invented the First Move — All Others Followed Involuntarily', weight: 1, tier: 'God', score: 100, color: 'var(--tier-god)' },
  { label: 'Every Dimension Has Surrendered Pre-Emptively', weight: 1, tier: 'God', score: 100, color: 'var(--tier-god)' },
  { label: 'Nothing Has Survived a Full Encounter', weight: 1, tier: 'God', score: 100, color: 'var(--tier-god)' },
  { label: 'The Concept of "Opponent" Filed for Retirement', weight: 1, tier: 'God', score: 100, color: 'var(--tier-god)' },
  { label: 'All Combat From the First to Last Is Theirs', weight: 1, tier: 'God', score: 100, color: 'var(--tier-god)' },
  { label: 'Fighting Style: Named "The End of All Arguments"', weight: 1, tier: 'God', score: 100, color: 'var(--tier-god)' },
  { label: 'Won Before the Universe Had Any Stakes to Lose', weight: 1, tier: 'God', score: 100, color: 'var(--tier-god)' },
  { label: 'The First Fist. The Last Word. Same Entity.', weight: 1, tier: 'God', score: 100, color: 'var(--tier-god)' },
  { label: 'The Universe Ended Combat as a Concept After Them', weight: 1, tier: 'God', score: 100, color: 'var(--tier-god)' },
  { label: 'Omniversal Combat Record Requires Infinite Storage', weight: 1, tier: 'God', score: 100, color: 'var(--tier-god)' },
  { label: 'Brought Peace by Making All Fighting Pointless', weight: 1, tier: 'God', score: 100, color: 'var(--tier-god)' },
  { label: 'Even Death Pre-Yields at Their Approach', weight: 1, tier: 'God', score: 100, color: 'var(--tier-god)' },
  { label: 'The Last Fighter. Nothing Else Is Needed.', weight: 1, tier: 'God', score: 100, color: 'var(--tier-god)' },
]
