import type { FlavorLabel } from './types'

export const fightingSkillLabels: FlavorLabel[] = [
  { label: 'Swings and Misses Stationary Objects', weight: 1, tier: 'F-',   score: 2,   color: '#555'    },
  { label: 'Flails with Intent',                   weight: 1, tier: 'F',    score: 5,   color: '#666'    },
  { label: 'Slightly Threatening',                 weight: 1, tier: 'F+',   score: 8,   color: '#777'    },
  { label: 'Street-Fight Capable',                 weight: 1, tier: 'E-',   score: 11,  color: '#6b7280' },
  { label: 'Won a Fight Once',                     weight: 1, tier: 'E',    score: 14,  color: '#9ca3af' },
  { label: 'Trained Amateur',                      weight: 1, tier: 'E+',   score: 17,  color: '#d1d5db' },
  { label: 'Competent Fighter',                    weight: 1, tier: 'D-',   score: 20,  color: '#92400e' },
  { label: 'Disciplined Combatant',                weight: 1, tier: 'D',    score: 23,  color: '#b45309' },
  { label: 'Professional Grade',                   weight: 1, tier: 'D+',   score: 26,  color: '#d97706' },
  { label: 'Special Forces Caliber',               weight: 1, tier: 'C-',   score: 30,  color: '#1d4ed8' },
  { label: 'Elite Military Rank',                  weight: 1, tier: 'C',    score: 34,  color: '#2563eb' },
  { label: 'Master of Multiple Arts',              weight: 1, tier: 'C+',   score: 38,  color: '#3b82f6' },
  { label: 'Legendary Duel Record',                weight: 1, tier: 'B-',   score: 42,  color: '#065f46' },
  { label: 'Undefeated in Conventional Combat',    weight: 1, tier: 'B',    score: 47,  color: '#059669' },
  { label: 'Could Train Armies Alone',             weight: 1, tier: 'B+',   score: 52,  color: '#34d399' },
  { label: 'Fights Armies Single-Handedly',        weight: 1, tier: 'A-',   score: 57,  color: '#7c3aed' },
  { label: 'No Weapon Can Compensate',             weight: 1, tier: 'A',    score: 62,  color: '#8b5cf6' },
  { label: 'Combat Instinct Beyond Human',         weight: 1, tier: 'A+',   score: 67,  color: '#a78bfa' },
  { label: 'Defines the Art of Fighting',          weight: 1, tier: 'S-',   score: 72,  color: '#b91c1c' },
  { label: 'Gods Hire Them as Bodyguards',         weight: 1, tier: 'S',    score: 77,  color: '#dc2626' },
  { label: 'Fighting Style Is a Natural Law',      weight: 1, tier: 'S+',   score: 81,  color: '#ef4444' },
  { label: 'Wins Before the Fight Starts',         weight: 1, tier: 'SS-',  score: 85,  color: '#ea580c' },
  { label: 'Fighting Mastery Made Manifest',       weight: 1, tier: 'SS',   score: 88,  color: '#f97316' },
  { label: 'Defeats the Concept of Defeat',        weight: 1, tier: 'SS+',  score: 91,  color: '#fb923c' },
  { label: 'Combat Is a Formality',                weight: 1, tier: 'SSS-', score: 94,  color: '#ca8a04' },
  { label: 'Has Won Every Fight That Will Ever Exist', weight: 1, tier: 'SSS', score: 97, color: '#eab308' },
  { label: 'You Are Already Defeated',             weight: 1, tier: 'SSS+', score: 99,  color: '#fde047' },
  { label: 'Violence Concedes',                    weight: 1, tier: 'God',  score: 100, color: '#e879f9' },
]
