import type { FlavorLabel } from './types'

export const fightingSkillLabels: FlavorLabel[] = [
  { label: 'Swings and Misses Stationary Objects', weight: 4, tier: 'F-',   score: 2,   color: '#555'    },
  { label: 'Flails with Intent',                   weight: 4, tier: 'F',    score: 5,   color: '#666'    },
  { label: 'Slightly Threatening',                 weight: 4, tier: 'F+',   score: 8,   color: '#777'    },
  { label: 'Street-Fight Capable',                 weight: 6, tier: 'E-',   score: 11,  color: '#6b7280' },
  { label: 'Won a Fight Once',                     weight: 6, tier: 'E',    score: 14,  color: '#9ca3af' },
  { label: 'Trained Amateur',                      weight: 6, tier: 'E+',   score: 17,  color: '#d1d5db' },
  { label: 'Competent Fighter',                    weight: 8, tier: 'D-',   score: 20,  color: '#92400e' },
  { label: 'Disciplined Combatant',                weight: 8, tier: 'D',    score: 23,  color: '#b45309' },
  { label: 'Professional Grade',                   weight: 8, tier: 'D+',   score: 26,  color: '#d97706' },
  { label: 'Special Forces Caliber',               weight: 8, tier: 'C-',   score: 30,  color: '#1d4ed8' },
  { label: 'Elite Military Rank',                  weight: 8, tier: 'C',    score: 34,  color: '#2563eb' },
  { label: 'Master of Multiple Arts',              weight: 8, tier: 'C+',   score: 38,  color: '#3b82f6' },
  { label: 'Legendary Duel Record',                weight: 7, tier: 'B-',   score: 42,  color: '#065f46' },
  { label: 'Undefeated in Conventional Combat',    weight: 7, tier: 'B',    score: 47,  color: '#059669' },
  { label: 'Could Train Armies Alone',             weight: 7, tier: 'B+',   score: 52,  color: '#34d399' },
  { label: 'Fights Armies Single-Handedly',        weight: 5, tier: 'A-',   score: 57,  color: '#7c3aed' },
  { label: 'No Weapon Can Compensate',             weight: 5, tier: 'A',    score: 62,  color: '#8b5cf6' },
  { label: 'Combat Instinct Beyond Human',         weight: 5, tier: 'A+',   score: 67,  color: '#a78bfa' },
  { label: 'Defines the Art of Fighting',          weight: 4, tier: 'S-',   score: 72,  color: '#b91c1c' },
  { label: 'Gods Hire Them as Bodyguards',         weight: 4, tier: 'S',    score: 77,  color: '#dc2626' },
  { label: 'Fighting Style Is a Natural Law',      weight: 4, tier: 'S+',   score: 81,  color: '#ef4444' },
  { label: 'Wins Before the Fight Starts',         weight: 3, tier: 'SS-',  score: 85,  color: '#ea580c' },
  { label: 'Fighting Mastery Made Manifest',       weight: 3, tier: 'SS',   score: 88,  color: '#f97316' },
  { label: 'Defeats the Concept of Defeat',        weight: 3, tier: 'SS+',  score: 91,  color: '#fb923c' },
  { label: 'Combat Is a Formality',                        weight: 2, tier: 'SSS-',      score: 94,  color: '#ca8a04' },
  { label: 'Has Won Every Fight That Will Ever Exist',     weight: 2, tier: 'SSS',       score: 97,  color: '#eab308' },
  { label: 'You Are Already Defeated',                     weight: 2, tier: 'SSS+',      score: 99,  color: '#fde047' },
  { label: 'Defeats Opponents Across Parallel Timelines',  weight: 2, tier: 'Z-',        score: 101, color: '#0e7490' },
  { label: 'Combat Style That Predates Fighting',          weight: 2, tier: 'Z',         score: 103, color: '#0891b2' },
  { label: 'Wins Fights That Have Not Been Declared Yet',  weight: 2, tier: 'Z+',        score: 105, color: '#06b6d4' },
  { label: 'Every Move Is the Finishing Blow',             weight: 1, tier: 'ZZ-',       score: 107, color: '#3730a3' },
  { label: 'The Battlefield Sides Against Their Opponent', weight: 1, tier: 'ZZ',        score: 109, color: '#4f46e5' },
  { label: 'Fighting Style That Defines What Combat Is',   weight: 1, tier: 'ZZ+',       score: 111, color: '#818cf8' },
  { label: 'Transcends Martial Limitation Entirely',       weight: 1, tier: 'ZZZ-',      score: 113, color: '#9d174d' },
  { label: 'Violence Invented Itself to Imitate Them',     weight: 1, tier: 'ZZZ',       score: 115, color: '#be185d' },
  { label: 'Enemies Forfeit Across Dimensions',            weight: 1, tier: 'ZZZ+',      score: 117, color: '#ec4899' },
  { label: 'Combat Technique Blessed by the Divine',       weight: 1, tier: 'Celestial-',score: 119, color: '#075985' },
  { label: 'Fights With the Weight of Cosmic Law',         weight: 1, tier: 'Celestial', score: 121, color: '#0284c7' },
  { label: 'Even Gods Would Rather Not Fight Them',        weight: 1, tier: 'Celestial+',score: 123, color: '#38bdf8' },
  { label: 'Every Strike Is an Act of Creation',           weight: 1, tier: 'Godly-',    score: 125, color: '#c026d3' },
  { label: 'Violence Concedes',                            weight: 1, tier: 'Godly',     score: 127, color: '#e879f9' },
  { label: 'Fought Before Time Had Rounds',                  weight: 1, tier: 'Primordial', score: 130, color: '#ffffff' },
  { label: 'Combat Style That Predates the Concept of War', weight: 1, tier: 'Primordial+',score: 133, color: '#ccffff' },
  { label: 'Martial Arts History References Them as Source', weight: 1, tier: 'Absolute-',  score: 137, color: '#99ffff' },
  { label: 'Every Strike Is the First and Last in History', weight: 1, tier: 'Absolute',   score: 144, color: '#00ffff' },
]
