import type { FlavorLabel } from './types'

// IQ scale: F- = vegetable / no comprehension, mortal mid-range = literate adult,
// A range = genius (Einstein-class), SSS = peak fictional thinker,
// Cosmic+ = post-mortal cognition, Infinite+ = beyond infinite intellect.
export const iqLabels: FlavorLabel[] = [
  { label: 'Vegetable IQ',                                   weight: 4, tier: 'F-',            score: 2,   color: '#2c2c2c' },
  { label: 'Outsmarted by Doorknobs',                        weight: 4, tier: 'F',             score: 5,   color: '#404040' },
  { label: 'Forgets Why They Entered a Room',                weight: 4, tier: 'F+',            score: 8,   color: '#525252' },
  { label: 'Below-Average Comprehension',                    weight: 6, tier: 'E-',            score: 11,  color: '#4b5563' },
  { label: 'Average Human Intelligence',                     weight: 6, tier: 'E',             score: 14,  color: '#64748b' },
  { label: 'Picks Things Up at a Normal Pace',               weight: 6, tier: 'E+',            score: 17,  color: '#94a3b8' },
  { label: 'Quick on the Uptake',                            weight: 8, tier: 'D-',            score: 20,  color: '#14532d' },
  { label: 'Reliable Problem Solver',                        weight: 8, tier: 'D',             score: 23,  color: '#166534' },
  { label: 'Top of the Class',                               weight: 8, tier: 'D+',            score: 26,  color: '#22c55e' },
  { label: 'Honors Student',                                 weight: 8, tier: 'C-',            score: 30,  color: '#047857' },
  { label: 'Gifted Intellect',                               weight: 9, tier: 'C',             score: 34,  color: '#059669' },
  { label: 'Skips Several Grades',                           weight: 8, tier: 'C+',            score: 38,  color: '#10b981' },
  { label: 'PhD-Tier Mind',                                  weight: 7, tier: 'B-',            score: 42,  color: '#115e59' },
  { label: 'Multidisciplinary Expert',                       weight: 7, tier: 'B',             score: 47,  color: '#0d9488' },
  { label: 'Genius-Adjacent Reasoning',                      weight: 7, tier: 'B+',            score: 52,  color: '#14b8a6' },
  { label: 'Genius IQ',                                      weight: 5, tier: 'A-',            score: 57,  color: '#155e75' },
  { label: 'Einstein-Class Intellect',                       weight: 5, tier: 'A',             score: 62,  color: '#0e7490' },
  { label: 'Polymath of the Century',                        weight: 5, tier: 'A+',            score: 67,  color: '#06b6d4' },
  { label: 'Superhuman Pattern Recognition',                 weight: 4, tier: 'S-',            score: 72,  color: '#0c4a6e' },
  { label: 'Solves Problems in Hours That Took Humanity Centuries', weight: 4, tier: 'S',     score: 77,  color: '#0369a1' },
  { label: 'Reads Causality Like a Map',                     weight: 4, tier: 'S+',            score: 81,  color: '#0ea5e9' },
  { label: 'Thinks Several Moves Ahead of Everyone Alive',   weight: 3, tier: 'SS-',           score: 85,  color: '#1e3a8a' },
  { label: 'Strategic Mastermind',                           weight: 3, tier: 'SS',            score: 88,  color: '#2563eb' },
  { label: 'Anticipates Events Before They Happen',          weight: 3, tier: 'SS+',           score: 91,  color: '#3b82f6' },
  { label: 'Comprehends the Almost-Unknowable',              weight: 1, tier: 'SSS-',          score: 94,  color: '#4338ca' },
  { label: 'Treats the World Like a Homework Problem',       weight: 1, tier: 'SSS',           score: 97,  color: '#4f46e5' },
  { label: 'Simulates Every Plausible Outcome at Once',      weight: 1, tier: 'SSS+',          score: 99,  color: '#6366f1' },
  { label: 'Understands the Rules Behind the Rules',         weight: 1, tier: 'Z-',            score: 101, color: '#5b21b6' },
  { label: 'Thinks in Dimensions Humans Cannot Name',        weight: 1, tier: 'Z',             score: 103, color: '#7c3aed' },
  { label: 'Reads Reality Like Source Code',                 weight: 1, tier: 'Z+',            score: 105, color: '#8b5cf6' },
  { label: 'Models Every Possible Outcome in Realtime',      weight: 0.7, tier: 'ZZ-',           score: 107, color: '#86198f' },
  { label: 'Solves Problems Reality Has Not Posed Yet',      weight: 0.7, tier: 'ZZ',            score: 109, color: '#a21caf' },
  { label: 'Knows the Answer Before the Question Exists',    weight: 0.7, tier: 'ZZ+',           score: 111, color: '#c026d3' },
  { label: 'Understanding Is Their Default State',           weight: 0.5, tier: 'ZZZ-',          score: 113, color: '#be185d' },
  { label: 'Has Already Considered Every Future',            weight: 0.5, tier: 'ZZZ',           score: 115, color: '#db2777' },
  { label: 'Thought Is Faster Than Causality',               weight: 0.5, tier: 'ZZZ+',          score: 117, color: '#ec4899' },
  { label: 'Cosmic-Scale Awareness',                         weight: 0.35, tier: 'Cosmic-',       score: 119, color: '#0e6b8a' },
  { label: 'Holds the History of Galaxies in Working Memory',weight: 0.35, tier: 'Cosmic',        score: 121, color: '#0891b2' },
  { label: 'Cosmos Files Reports to Them',                   weight: 0.35, tier: 'Cosmic+',       score: 123, color: '#06b6d4' },
  { label: 'Has Outlived Every Idea They Ever Had',          weight: 0.25, tier: 'Immortal-',     score: 125, color: '#d946ef' },
  { label: 'Mind Predates Most Civilizations',               weight: 0.25, tier: 'Immortal',      score: 127, color: '#ec4899' },
  { label: 'Memory Spans Forgotten Epochs',                  weight: 0.25, tier: 'Immortal+',     score: 129, color: '#f472b6' },
  { label: 'Divine Beings Take Notes',                       weight: 0.2, tier: 'Celestial-',    score: 131, color: '#831843' },
  { label: 'Intellect Spans All Planes',                     weight: 0.2, tier: 'Celestial',     score: 133, color: '#9d174d' },
  { label: 'Even Pantheons Consult Them',                    weight: 0.2, tier: 'Celestial+',    score: 135, color: '#be185d' },
  { label: 'Understands Things Gods Refuse to Touch',        weight: 0.15, tier: 'Godly-',        score: 137, color: '#f9a8d4' },
  { label: 'Knows What the Gods Forgot',                     weight: 0.15, tier: 'Godly',         score: 139, color: '#f472b6' },
  { label: 'Author of Divine Knowledge',                     weight: 0.15, tier: 'Godly+',        score: 141, color: '#ec4899' },
  { label: 'Predates the Concept of Thought',                weight: 0.1, tier: 'Primordial-',   score: 143, color: '#d4d4d8' },
  { label: 'The First Mind Ever',                            weight: 0.1, tier: 'Primordial',    score: 145, color: '#e4e4e7' },
  { label: 'Authored the Idea of "Knowing"',                 weight: 0.1, tier: 'Primordial+',   score: 147, color: '#fafafa' },
  { label: 'Absolute Comprehension',                         weight: 0.07, tier: 'Absolute-',     score: 149, color: '#7dd3fc' },
  { label: 'Knowing Things Into Existence',                  weight: 0.07, tier: 'Absolute',      score: 151, color: '#38bdf8' },
  { label: 'Reality Defers to Their Conclusions',            weight: 0.07, tier: 'Absolute+',     score: 153, color: '#0ea5e9' },
  { label: 'Beyond Knowing as a Concept',                    weight: 0.05, tier: 'Transcendent-', score: 155, color: '#84cc16' },
  { label: 'Comprehension Itself Transcends Them',           weight: 0.05, tier: 'Transcendent',  score: 157, color: '#65a30d' },
  { label: 'Even Awareness Bows in Their Presence',          weight: 0.05, tier: 'Transcendent+', score: 159, color: '#4d7c0f' },
  { label: 'Infinite Intellect',                             weight: 0.03, tier: 'Infinite-',     score: 161, color: '#525252' },
  { label: 'Truly Infinite Mind',                            weight: 0.03, tier: 'Infinite',      score: 163, color: '#262626' },
  { label: 'Beyond Infinite IQ',                             weight: 0.03, tier: 'Infinite+',     score: 165, color: '#000000' },
]
