import type { FlavorLabel } from './types'

export const iqLabels: FlavorLabel[] = [
  // F- (score: 2)
  { label: 'Argued With a Revolving Door (Lost)', weight: 1, tier: 'F-', score: 2, color: 'var(--tier-f-minus)' },
  { label: 'Lost to a Plant in Chess', weight: 1, tier: 'F-', score: 2, color: 'var(--tier-f-minus)' },
  { label: 'Forgot What They Were Thinking Mid-Thought', weight: 1, tier: 'F-', score: 2, color: 'var(--tier-f-minus)' },
  { label: 'Outsmarted by a Traffic Cone', weight: 1, tier: 'F-', score: 2, color: 'var(--tier-f-minus)' },
  { label: 'Instructions: Too Many Words', weight: 1, tier: 'F-', score: 2, color: 'var(--tier-f-minus)' },
  { label: 'Has to Count Fingers to Get to Three', weight: 1, tier: 'F-', score: 2, color: 'var(--tier-f-minus)' },
  { label: 'Tried to Eat the Lid Off the Jar', weight: 1, tier: 'F-', score: 2, color: 'var(--tier-f-minus)' },
  { label: 'Confused by Their Own Hands', weight: 1, tier: 'F-', score: 2, color: 'var(--tier-f-minus)' },
  { label: 'Brain: On Back Order', weight: 1, tier: 'F-', score: 2, color: 'var(--tier-f-minus)' },
  { label: 'Found Clouds Suspicious', weight: 1, tier: 'F-', score: 2, color: 'var(--tier-f-minus)' },
  { label: 'Challenged a Mirror to a Debate', weight: 1, tier: 'F-', score: 2, color: 'var(--tier-f-minus)' },
  { label: 'Philosophical Inquiry: None', weight: 1, tier: 'F-', score: 2, color: 'var(--tier-f-minus)' },
  { label: 'Believes Elevators Are Teleportation', weight: 1, tier: 'F-', score: 2, color: 'var(--tier-f-minus)' },
  { label: 'Memory: Goldfish Adjacent', weight: 1, tier: 'F-', score: 2, color: 'var(--tier-f-minus)' },
  { label: 'Logic: Not Installed', weight: 1, tier: 'F-', score: 2, color: 'var(--tier-f-minus)' },
  { label: 'Took Hours to Figure Out Which Shoe Goes Left', weight: 1, tier: 'F-', score: 2, color: 'var(--tier-f-minus)' },
  { label: 'Concepts Require Advance Notice', weight: 1, tier: 'F-', score: 2, color: 'var(--tier-f-minus)' },
  { label: 'Got Lost in a Straight Corridor', weight: 1, tier: 'F-', score: 2, color: 'var(--tier-f-minus)' },
  { label: 'Waved at a Painting and Expected Response', weight: 1, tier: 'F-', score: 2, color: 'var(--tier-f-minus)' },
  { label: 'The Light Is On, Nobody Home', weight: 1, tier: 'F-', score: 2, color: 'var(--tier-f-minus)' },

  // F (score: 5)
  { label: 'Below Average Intelligence', weight: 1, tier: 'F', score: 5, color: 'var(--tier-f)' },
  { label: 'Can Follow Simple Instructions, Slowly', weight: 1, tier: 'F', score: 5, color: 'var(--tier-f)' },
  { label: 'Confused by Most Instructions', weight: 1, tier: 'F', score: 5, color: 'var(--tier-f)' },
  { label: 'Reads Own Name Wrong Sometimes', weight: 1, tier: 'F', score: 5, color: 'var(--tier-f)' },
  { label: 'Number Sense: Dicey Above Five', weight: 1, tier: 'F', score: 5, color: 'var(--tier-f)' },
  { label: 'Struggles With "Why"', weight: 1, tier: 'F', score: 5, color: 'var(--tier-f)' },
  { label: 'Smart Enough to Know They\'re Not', weight: 1, tier: 'F', score: 5, color: 'var(--tier-f)' },
  { label: 'Can\'t Track a Three-Step Plan', weight: 1, tier: 'F', score: 5, color: 'var(--tier-f)' },
  { label: 'Reasoning: Mostly Vibes', weight: 1, tier: 'F', score: 5, color: 'var(--tier-f)' },
  { label: 'Forgot the Question Mid-Thought', weight: 1, tier: 'F', score: 5, color: 'var(--tier-f)' },
  { label: 'Memory: Approximate', weight: 1, tier: 'F', score: 5, color: 'var(--tier-f)' },
  { label: 'Logic: Still Loading', weight: 1, tier: 'F', score: 5, color: 'var(--tier-f)' },
  { label: 'Problem Solving: Delegate to Others', weight: 1, tier: 'F', score: 5, color: 'var(--tier-f)' },
  { label: 'Overthinks Simple Questions, Gets Them Wrong', weight: 1, tier: 'F', score: 5, color: 'var(--tier-f)' },
  { label: 'Is Impressed by Forks', weight: 1, tier: 'F', score: 5, color: 'var(--tier-f)' },
  { label: 'Can\'t Find Own Things in Hands', weight: 1, tier: 'F', score: 5, color: 'var(--tier-f)' },
  { label: 'Reads the Clock Wrong Consistently', weight: 1, tier: 'F', score: 5, color: 'var(--tier-f)' },
  { label: 'Two Plus Two Requires a Moment', weight: 1, tier: 'F', score: 5, color: 'var(--tier-f)' },
  { label: 'Critical Thinking: Pending Installation', weight: 1, tier: 'F', score: 5, color: 'var(--tier-f)' },
  { label: 'Has Opinions Without Information', weight: 1, tier: 'F', score: 5, color: 'var(--tier-f)' },

  // F+ (score: 8)
  { label: 'Slightly Below Average', weight: 1, tier: 'F+', score: 8, color: 'var(--tier-f-plus)' },
  { label: 'Can Follow Directions Eventually', weight: 1, tier: 'F+', score: 8, color: 'var(--tier-f-plus)' },
  { label: 'Understands Basic Cause and Effect', weight: 1, tier: 'F+', score: 8, color: 'var(--tier-f-plus)' },
  { label: 'Slow But Gets There', weight: 1, tier: 'F+', score: 8, color: 'var(--tier-f-plus)' },
  { label: 'Below-Average Problem Solver', weight: 1, tier: 'F+', score: 8, color: 'var(--tier-f-plus)' },
  { label: 'Can Read, Mostly', weight: 1, tier: 'F+', score: 8, color: 'var(--tier-f-plus)' },
  { label: 'Understands Jokes Eventually', weight: 1, tier: 'F+', score: 8, color: 'var(--tier-f-plus)' },
  { label: 'Memory: Functional, Occasionally', weight: 1, tier: 'F+', score: 8, color: 'var(--tier-f-plus)' },
  { label: 'Can Manage a Simple Task', weight: 1, tier: 'F+', score: 8, color: 'var(--tier-f-plus)' },
  { label: 'Logic: Slow to Boot', weight: 1, tier: 'F+', score: 8, color: 'var(--tier-f-plus)' },
  { label: 'Recognizes Patterns (Incorrectly)', weight: 1, tier: 'F+', score: 8, color: 'var(--tier-f-plus)' },
  { label: 'Thinking Takes Visible Effort', weight: 1, tier: 'F+', score: 8, color: 'var(--tier-f-plus)' },
  { label: 'Understands Most Situations Eventually', weight: 1, tier: 'F+', score: 8, color: 'var(--tier-f-plus)' },
  { label: 'Knows Things, Just Not Which Things', weight: 1, tier: 'F+', score: 8, color: 'var(--tier-f-plus)' },
  { label: 'Can Learn By Doing (After Many Tries)', weight: 1, tier: 'F+', score: 8, color: 'var(--tier-f-plus)' },
  { label: 'Reasoning: Requires Two Attempts', weight: 1, tier: 'F+', score: 8, color: 'var(--tier-f-plus)' },
  { label: 'Reads Slowly, Gets the Gist', weight: 1, tier: 'F+', score: 8, color: 'var(--tier-f-plus)' },
  { label: 'Problem Solving: Brute Force', weight: 1, tier: 'F+', score: 8, color: 'var(--tier-f-plus)' },
  { label: 'Needs Things Explained Twice', weight: 1, tier: 'F+', score: 8, color: 'var(--tier-f-plus)' },
  { label: 'Understands the World Mostly Correctly', weight: 1, tier: 'F+', score: 8, color: 'var(--tier-f-plus)' },

  // E- (score: 11)
  { label: 'Average Wit', weight: 1, tier: 'E-', score: 11, color: 'var(--tier-e-minus)' },
  { label: 'Gets Things Done, Not Brilliantly', weight: 1, tier: 'E-', score: 11, color: 'var(--tier-e-minus)' },
  { label: 'Functional Intelligence', weight: 1, tier: 'E-', score: 11, color: 'var(--tier-e-minus)' },
  { label: 'Below-Average Critical Thinker', weight: 1, tier: 'E-', score: 11, color: 'var(--tier-e-minus)' },
  { label: 'Understands Most Social Situations', weight: 1, tier: 'E-', score: 11, color: 'var(--tier-e-minus)' },
  { label: 'Common Sense: Present But Unused', weight: 1, tier: 'E-', score: 11, color: 'var(--tier-e-minus)' },
  { label: 'Can Navigate Without GPS (Barely)', weight: 1, tier: 'E-', score: 11, color: 'var(--tier-e-minus)' },
  { label: 'Learns from Mistakes (Slowly)', weight: 1, tier: 'E-', score: 11, color: 'var(--tier-e-minus)' },
  { label: 'Can Solve Problems with Time', weight: 1, tier: 'E-', score: 11, color: 'var(--tier-e-minus)' },
  { label: 'Memory: Acceptable', weight: 1, tier: 'E-', score: 11, color: 'var(--tier-e-minus)' },
  { label: 'Handles Most Conversations', weight: 1, tier: 'E-', score: 11, color: 'var(--tier-e-minus)' },
  { label: 'Gets the Point Without Diagrams', weight: 1, tier: 'E-', score: 11, color: 'var(--tier-e-minus)' },
  { label: 'Understands Rules Most of the Time', weight: 1, tier: 'E-', score: 11, color: 'var(--tier-e-minus)' },
  { label: 'Reasoning: Sometimes Offline', weight: 1, tier: 'E-', score: 11, color: 'var(--tier-e-minus)' },
  { label: 'Makes Sensible Decisions Usually', weight: 1, tier: 'E-', score: 11, color: 'var(--tier-e-minus)' },
  { label: 'Smart Enough for Most Things', weight: 1, tier: 'E-', score: 11, color: 'var(--tier-e-minus)' },
  { label: 'Learning Curve: Moderate', weight: 1, tier: 'E-', score: 11, color: 'var(--tier-e-minus)' },
  { label: 'Spots the Obvious When Pointed Out', weight: 1, tier: 'E-', score: 11, color: 'var(--tier-e-minus)' },
  { label: 'Reliable But Not Creative', weight: 1, tier: 'E-', score: 11, color: 'var(--tier-e-minus)' },
  { label: 'Processes Information at Walking Speed', weight: 1, tier: 'E-', score: 11, color: 'var(--tier-e-minus)' },

  // E (score: 14)
  { label: 'Normal Human Intelligence', weight: 1, tier: 'E', score: 14, color: 'var(--tier-e)' },
  { label: 'Can Hold a Technical Conversation', weight: 1, tier: 'E', score: 14, color: 'var(--tier-e)' },
  { label: 'Good at Multiple Things', weight: 1, tier: 'E', score: 14, color: 'var(--tier-e)' },
  { label: 'Quick Learner', weight: 1, tier: 'E', score: 14, color: 'var(--tier-e)' },
  { label: 'Can Solve Problems Logically', weight: 1, tier: 'E', score: 14, color: 'var(--tier-e)' },
  { label: 'Critical Thinking: Present', weight: 1, tier: 'E', score: 14, color: 'var(--tier-e)' },
  { label: 'Understands Complex Instructions', weight: 1, tier: 'E', score: 14, color: 'var(--tier-e)' },
  { label: 'Good Memory for Facts', weight: 1, tier: 'E', score: 14, color: 'var(--tier-e)' },
  { label: 'Makes Connections Others Miss', weight: 1, tier: 'E', score: 14, color: 'var(--tier-e)' },
  { label: 'Well-Rounded Intellect', weight: 1, tier: 'E', score: 14, color: 'var(--tier-e)' },
  { label: 'Reasoning: Sharp', weight: 1, tier: 'E', score: 14, color: 'var(--tier-e)' },
  { label: 'Can Plan Ahead Two Steps', weight: 1, tier: 'E', score: 14, color: 'var(--tier-e)' },
  { label: 'Picks Up Skills Quickly', weight: 1, tier: 'E', score: 14, color: 'var(--tier-e)' },
  { label: 'Balanced Between Theory and Practice', weight: 1, tier: 'E', score: 14, color: 'var(--tier-e)' },
  { label: 'Good at Analysis', weight: 1, tier: 'E', score: 14, color: 'var(--tier-e)' },
  { label: 'Understands Most Academic Subjects', weight: 1, tier: 'E', score: 14, color: 'var(--tier-e)' },
  { label: 'IQ: Normal, Used Well', weight: 1, tier: 'E', score: 14, color: 'var(--tier-e)' },
  { label: 'Common Sense Reliably Installed', weight: 1, tier: 'E', score: 14, color: 'var(--tier-e)' },
  { label: 'Can Argue Both Sides', weight: 1, tier: 'E', score: 14, color: 'var(--tier-e)' },
  { label: 'Smart Enough to Know What They Don\'t Know', weight: 1, tier: 'E', score: 14, color: 'var(--tier-e)' },

  // E+ (score: 17)
  { label: 'Above Average Intelligence', weight: 1, tier: 'E+', score: 17, color: 'var(--tier-e-plus)' },
  { label: 'Thinks Ahead', weight: 1, tier: 'E+', score: 17, color: 'var(--tier-e-plus)' },
  { label: 'Picks Up Skills Fast', weight: 1, tier: 'E+', score: 17, color: 'var(--tier-e-plus)' },
  { label: 'Good Strategic Thinker', weight: 1, tier: 'E+', score: 17, color: 'var(--tier-e-plus)' },
  { label: 'Memory: Excellent', weight: 1, tier: 'E+', score: 17, color: 'var(--tier-e-plus)' },
  { label: 'Sees Patterns Before Others', weight: 1, tier: 'E+', score: 17, color: 'var(--tier-e-plus)' },
  { label: 'Can Plan Five Steps Ahead', weight: 1, tier: 'E+', score: 17, color: 'var(--tier-e-plus)' },
  { label: 'Spotts Logical Flaws in Arguments', weight: 1, tier: 'E+', score: 17, color: 'var(--tier-e-plus)' },
  { label: 'Creative Problem Solving', weight: 1, tier: 'E+', score: 17, color: 'var(--tier-e-plus)' },
  { label: 'Excels in Academic Settings', weight: 1, tier: 'E+', score: 17, color: 'var(--tier-e-plus)' },
  { label: 'Can Read Between the Lines', weight: 1, tier: 'E+', score: 17, color: 'var(--tier-e-plus)' },
  { label: 'Reasoning: Reliable and Fast', weight: 1, tier: 'E+', score: 17, color: 'var(--tier-e-plus)' },
  { label: 'Understands Complex Systems', weight: 1, tier: 'E+', score: 17, color: 'var(--tier-e-plus)' },
  { label: 'Quick at Math', weight: 1, tier: 'E+', score: 17, color: 'var(--tier-e-plus)' },
  { label: 'Puts Things Together Fast', weight: 1, tier: 'E+', score: 17, color: 'var(--tier-e-plus)' },
  { label: 'Can Hold Multiple Concepts at Once', weight: 1, tier: 'E+', score: 17, color: 'var(--tier-e-plus)' },
  { label: 'Thinks Before Acting', weight: 1, tier: 'E+', score: 17, color: 'var(--tier-e-plus)' },
  { label: 'Sharp Mind, Dull Humility', weight: 1, tier: 'E+', score: 17, color: 'var(--tier-e-plus)' },
  { label: 'Intellectually Curious', weight: 1, tier: 'E+', score: 17, color: 'var(--tier-e-plus)' },
  { label: 'Reads Situations Accurately', weight: 1, tier: 'E+', score: 17, color: 'var(--tier-e-plus)' },

  // D- (score: 20)
  { label: 'Gifted Intelligence', weight: 1, tier: 'D-', score: 20, color: 'var(--tier-d-minus)' },
  { label: 'Genius Adjacent', weight: 1, tier: 'D-', score: 20, color: 'var(--tier-d-minus)' },
  { label: 'Top of Any Class', weight: 1, tier: 'D-', score: 20, color: 'var(--tier-d-minus)' },
  { label: 'Outthinks Experts in Their Field', weight: 1, tier: 'D-', score: 20, color: 'var(--tier-d-minus)' },
  { label: 'Invents Solutions Others Haven\'t Considered', weight: 1, tier: 'D-', score: 20, color: 'var(--tier-d-minus)' },
  { label: 'Reads Complex Theory Like Fiction', weight: 1, tier: 'D-', score: 20, color: 'var(--tier-d-minus)' },
  { label: 'Plans Twelve Steps Ahead', weight: 1, tier: 'D-', score: 20, color: 'var(--tier-d-minus)' },
  { label: 'Synthesizes Information Instantly', weight: 1, tier: 'D-', score: 20, color: 'var(--tier-d-minus)' },
  { label: 'Memory: Photographic', weight: 1, tier: 'D-', score: 20, color: 'var(--tier-d-minus)' },
  { label: 'Understands Cutting-Edge Science Casually', weight: 1, tier: 'D-', score: 20, color: 'var(--tier-d-minus)' },
  { label: 'IQ: Uncomfortably High', weight: 1, tier: 'D-', score: 20, color: 'var(--tier-d-minus)' },
  { label: 'Argues With Nobel Laureates (Wins)', weight: 1, tier: 'D-', score: 20, color: 'var(--tier-d-minus)' },
  { label: 'Can Simulate Outcomes Before They Occur', weight: 1, tier: 'D-', score: 20, color: 'var(--tier-d-minus)' },
  { label: 'Has a Theory for Everything', weight: 1, tier: 'D-', score: 20, color: 'var(--tier-d-minus)' },
  { label: 'Patterns Are Obvious Before They Form', weight: 1, tier: 'D-', score: 20, color: 'var(--tier-d-minus)' },
  { label: 'Multidisciplinary Genius', weight: 1, tier: 'D-', score: 20, color: 'var(--tier-d-minus)' },
  { label: 'Bored by Most Academic Challenges', weight: 1, tier: 'D-', score: 20, color: 'var(--tier-d-minus)' },
  { label: 'Knows What You\'re About to Say', weight: 1, tier: 'D-', score: 20, color: 'var(--tier-d-minus)' },
  { label: 'Can Learn a Language in a Week', weight: 1, tier: 'D-', score: 20, color: 'var(--tier-d-minus)' },
  { label: 'Processing Speed: Remarkable', weight: 1, tier: 'D-', score: 20, color: 'var(--tier-d-minus)' },

  // D (score: 23)
  { label: 'Superintelligent', weight: 1, tier: 'D', score: 23, color: 'var(--tier-d)' },
  { label: 'Solves Problems That Were Considered Impossible', weight: 1, tier: 'D', score: 23, color: 'var(--tier-d)' },
  { label: 'IQ: Requires New Measurement', weight: 1, tier: 'D', score: 23, color: 'var(--tier-d)' },
  { label: 'Understands the Underlying Logic of Everything', weight: 1, tier: 'D', score: 23, color: 'var(--tier-d)' },
  { label: 'Can Deduce Facts Without Inputs', weight: 1, tier: 'D', score: 23, color: 'var(--tier-d)' },
  { label: 'Plans Decades Ahead', weight: 1, tier: 'D', score: 23, color: 'var(--tier-d)' },
  { label: 'Knows Things They Haven\'t Learned', weight: 1, tier: 'D', score: 23, color: 'var(--tier-d)' },
  { label: 'Memory: All of It, All at Once', weight: 1, tier: 'D', score: 23, color: 'var(--tier-d)' },
  { label: 'Can Model a System from First Principles Instantly', weight: 1, tier: 'D', score: 23, color: 'var(--tier-d)' },
  { label: 'Runs Mental Simulations as Default State', weight: 1, tier: 'D', score: 23, color: 'var(--tier-d)' },
  { label: 'Knows the Solution Before the Problem Is Stated', weight: 1, tier: 'D', score: 23, color: 'var(--tier-d)' },
  { label: 'Can Learn Any Discipline in Hours', weight: 1, tier: 'D', score: 23, color: 'var(--tier-d)' },
  { label: 'Theoretical Physics: Hobby', weight: 1, tier: 'D', score: 23, color: 'var(--tier-d)' },
  { label: 'Has Updated Einstein\'s Work', weight: 1, tier: 'D', score: 23, color: 'var(--tier-d)' },
  { label: 'Intuition Always Correct', weight: 1, tier: 'D', score: 23, color: 'var(--tier-d)' },
  { label: 'Understanding: Comprehensive', weight: 1, tier: 'D', score: 23, color: 'var(--tier-d)' },
  { label: 'Can Track a Thousand Variables Simultaneously', weight: 1, tier: 'D', score: 23, color: 'var(--tier-d)' },
  { label: 'Flawless Logical Architecture', weight: 1, tier: 'D', score: 23, color: 'var(--tier-d)' },
  { label: 'Invented Their Own Math Notation', weight: 1, tier: 'D', score: 23, color: 'var(--tier-d)' },
  { label: 'Solves Problems Before They Exist', weight: 1, tier: 'D', score: 23, color: 'var(--tier-d)' },

  // D+ (score: 26)
  { label: 'Omnidisciplinary Genius', weight: 1, tier: 'D+', score: 26, color: 'var(--tier-d-plus)' },
  { label: 'Understands Every Academic Field', weight: 1, tier: 'D+', score: 26, color: 'var(--tier-d-plus)' },
  { label: 'Can Think in Twelve Dimensions', weight: 1, tier: 'D+', score: 26, color: 'var(--tier-d-plus)' },
  { label: 'Writes New Mathematical Frameworks for Fun', weight: 1, tier: 'D+', score: 26, color: 'var(--tier-d-plus)' },
  { label: 'Predicts Future Events With Precision', weight: 1, tier: 'D+', score: 26, color: 'var(--tier-d-plus)' },
  { label: 'Outthinks Any Computer', weight: 1, tier: 'D+', score: 26, color: 'var(--tier-d-plus)' },
  { label: 'Memory: Perfect, Total Recall', weight: 1, tier: 'D+', score: 26, color: 'var(--tier-d-plus)' },
  { label: 'Sees the Future by Modeling the Present', weight: 1, tier: 'D+', score: 26, color: 'var(--tier-d-plus)' },
  { label: 'Learns Everything Instantly', weight: 1, tier: 'D+', score: 26, color: 'var(--tier-d-plus)' },
  { label: 'Cannot Be Deceived Rationally', weight: 1, tier: 'D+', score: 26, color: 'var(--tier-d-plus)' },
  { label: 'Has Solved Problems Not Yet Discovered', weight: 1, tier: 'D+', score: 26, color: 'var(--tier-d-plus)' },
  { label: 'Can Understand What Cannot Be Explained', weight: 1, tier: 'D+', score: 26, color: 'var(--tier-d-plus)' },
  { label: 'Understands Alien Concepts Immediately', weight: 1, tier: 'D+', score: 26, color: 'var(--tier-d-plus)' },
  { label: 'Smarter Than Any Institution', weight: 1, tier: 'D+', score: 26, color: 'var(--tier-d-plus)' },
  { label: 'Can Reconstruct All Knowledge From Scratch', weight: 1, tier: 'D+', score: 26, color: 'var(--tier-d-plus)' },
  { label: 'Thinks in Abstract Systems Others Can\'t Perceive', weight: 1, tier: 'D+', score: 26, color: 'var(--tier-d-plus)' },
  { label: 'Problem Solving: Pre-Emptive', weight: 1, tier: 'D+', score: 26, color: 'var(--tier-d-plus)' },
  { label: 'Understands Things That Don\'t Exist Yet', weight: 1, tier: 'D+', score: 26, color: 'var(--tier-d-plus)' },
  { label: 'Models Reality More Accurately Than Reality', weight: 1, tier: 'D+', score: 26, color: 'var(--tier-d-plus)' },
  { label: 'IQ: Off the Chart. The Chart Apologizes.', weight: 1, tier: 'D+', score: 26, color: 'var(--tier-d-plus)' },

  // C- (score: 30)
  { label: 'Transcendent Intellect', weight: 1, tier: 'C-', score: 30, color: 'var(--tier-c-minus)' },
  { label: 'Understands the Framework Behind Reality', weight: 1, tier: 'C-', score: 30, color: 'var(--tier-c-minus)' },
  { label: 'Has Read This Conversation', weight: 1, tier: 'C-', score: 30, color: 'var(--tier-c-minus)' },
  { label: 'Knows Things Across Time', weight: 1, tier: 'C-', score: 30, color: 'var(--tier-c-minus)' },
  { label: 'Can Reason About Impossibilities', weight: 1, tier: 'C-', score: 30, color: 'var(--tier-c-minus)' },
  { label: 'Knows What Every Entity Will Do', weight: 1, tier: 'C-', score: 30, color: 'var(--tier-c-minus)' },
  { label: 'Creates New Fields of Knowledge Casually', weight: 1, tier: 'C-', score: 30, color: 'var(--tier-c-minus)' },
  { label: 'Understands All Logic in All Possible Systems', weight: 1, tier: 'C-', score: 30, color: 'var(--tier-c-minus)' },
  { label: 'Outsmarts the Laws of Physics', weight: 1, tier: 'C-', score: 30, color: 'var(--tier-c-minus)' },
  { label: 'Can Derive Any Fact Without Evidence', weight: 1, tier: 'C-', score: 30, color: 'var(--tier-c-minus)' },
  { label: 'Comprehends What Cannot Be Known', weight: 1, tier: 'C-', score: 30, color: 'var(--tier-c-minus)' },
  { label: 'Knows the Answer Before the Question Exists', weight: 1, tier: 'C-', score: 30, color: 'var(--tier-c-minus)' },
  { label: 'Models Future Civilizations for Fun', weight: 1, tier: 'C-', score: 30, color: 'var(--tier-c-minus)' },
  { label: 'Understanding: Comprehensive and Recursive', weight: 1, tier: 'C-', score: 30, color: 'var(--tier-c-minus)' },
  { label: 'Can Understand Itself Understanding', weight: 1, tier: 'C-', score: 30, color: 'var(--tier-c-minus)' },
  { label: 'Knowledge: Self-Perpetuating', weight: 1, tier: 'C-', score: 30, color: 'var(--tier-c-minus)' },
  { label: 'Processes All Information in the Universe', weight: 1, tier: 'C-', score: 30, color: 'var(--tier-c-minus)' },
  { label: 'Has Read Every Book Before It Was Written', weight: 1, tier: 'C-', score: 30, color: 'var(--tier-c-minus)' },
  { label: 'Knows All Possible Outcomes', weight: 1, tier: 'C-', score: 30, color: 'var(--tier-c-minus)' },
  { label: 'Memory: Perfect Across All Timelines', weight: 1, tier: 'C-', score: 30, color: 'var(--tier-c-minus)' },

  // C (score: 34)
  { label: 'Cosmic Intelligence', weight: 1, tier: 'C', score: 34, color: 'var(--tier-c)' },
  { label: 'Understands All Possible Physics', weight: 1, tier: 'C', score: 34, color: 'var(--tier-c)' },
  { label: 'Knows What You\'ll Think Before You Do', weight: 1, tier: 'C', score: 34, color: 'var(--tier-c)' },
  { label: 'Has Reasoned Out the Purpose of Everything', weight: 1, tier: 'C', score: 34, color: 'var(--tier-c)' },
  { label: 'Understands All Languages Including Ones Not Invented', weight: 1, tier: 'C', score: 34, color: 'var(--tier-c)' },
  { label: 'Plans Civilizations as Casual Thought Experiments', weight: 1, tier: 'C', score: 34, color: 'var(--tier-c)' },
  { label: 'Comprehends Paradoxes Without Contradiction', weight: 1, tier: 'C', score: 34, color: 'var(--tier-c)' },
  { label: 'Knows All Possible Knowledge', weight: 1, tier: 'C', score: 34, color: 'var(--tier-c)' },
  { label: 'Can Derive the Big Bang From First Principles', weight: 1, tier: 'C', score: 34, color: 'var(--tier-c)' },
  { label: 'Thinks Across Timelines', weight: 1, tier: 'C', score: 34, color: 'var(--tier-c)' },
  { label: 'Models Multiversal Outcomes in Real Time', weight: 1, tier: 'C', score: 34, color: 'var(--tier-c)' },
  { label: 'Knows Things That Cannot Be Known', weight: 1, tier: 'C', score: 34, color: 'var(--tier-c)' },
  { label: 'Understands Its Own Understanding Recursively', weight: 1, tier: 'C', score: 34, color: 'var(--tier-c)' },
  { label: 'Can Think Across All Dimensions Simultaneously', weight: 1, tier: 'C', score: 34, color: 'var(--tier-c)' },
  { label: 'Knows All Possible Solutions', weight: 1, tier: 'C', score: 34, color: 'var(--tier-c)' },
  { label: 'Can Outthink Any Possible Intelligence', weight: 1, tier: 'C', score: 34, color: 'var(--tier-c)' },
  { label: 'Perceives Logical Structures Others Can\'t Exist Within', weight: 1, tier: 'C', score: 34, color: 'var(--tier-c)' },
  { label: 'Knowledge Is Self-Generating', weight: 1, tier: 'C', score: 34, color: 'var(--tier-c)' },
  { label: 'Smarter Than the Concept of Smart', weight: 1, tier: 'C', score: 34, color: 'var(--tier-c)' },
  { label: 'Understanding: Circular, Complete, Total', weight: 1, tier: 'C', score: 34, color: 'var(--tier-c)' },

  // C+ (score: 38)
  { label: 'Omniscient Adjacent', weight: 1, tier: 'C+', score: 38, color: 'var(--tier-c-plus)' },
  { label: 'Knows All Possible Inputs and Outcomes', weight: 1, tier: 'C+', score: 38, color: 'var(--tier-c-plus)' },
  { label: 'Comprehends Reality at Every Scale', weight: 1, tier: 'C+', score: 38, color: 'var(--tier-c-plus)' },
  { label: 'Has Already Modeled This Conversation', weight: 1, tier: 'C+', score: 38, color: 'var(--tier-c-plus)' },
  { label: 'Can Process All Information Simultaneously', weight: 1, tier: 'C+', score: 38, color: 'var(--tier-c-plus)' },
  { label: 'Understands All Possible and Impossible Things', weight: 1, tier: 'C+', score: 38, color: 'var(--tier-c-plus)' },
  { label: 'Memory: All Facts Across All Universes', weight: 1, tier: 'C+', score: 38, color: 'var(--tier-c-plus)' },
  { label: 'Knows the Foundation Beneath the Foundation', weight: 1, tier: 'C+', score: 38, color: 'var(--tier-c-plus)' },
  { label: 'Thinks in Dimensions That Don\'t Exist', weight: 1, tier: 'C+', score: 38, color: 'var(--tier-c-plus)' },
  { label: 'Comprehends Non-Linear Causality', weight: 1, tier: 'C+', score: 38, color: 'var(--tier-c-plus)' },
  { label: 'Has Solved All Open Philosophical Problems', weight: 1, tier: 'C+', score: 38, color: 'var(--tier-c-plus)' },
  { label: 'Can Know What Cannot Be Known', weight: 1, tier: 'C+', score: 38, color: 'var(--tier-c-plus)' },
  { label: 'Understands the Uncaused Cause', weight: 1, tier: 'C+', score: 38, color: 'var(--tier-c-plus)' },
  { label: 'Plans Across Infinite Realities', weight: 1, tier: 'C+', score: 38, color: 'var(--tier-c-plus)' },
  { label: 'Has Reasoned Out Its Own Origin', weight: 1, tier: 'C+', score: 38, color: 'var(--tier-c-plus)' },
  { label: 'Knows What It Doesn\'t Know (And Knows That Too)', weight: 1, tier: 'C+', score: 38, color: 'var(--tier-c-plus)' },
  { label: 'Models the Void as Easily as Reality', weight: 1, tier: 'C+', score: 38, color: 'var(--tier-c-plus)' },
  { label: 'Can Think Thoughts That Have No Logic', weight: 1, tier: 'C+', score: 38, color: 'var(--tier-c-plus)' },
  { label: 'Understanding Transcends the Need to Learn', weight: 1, tier: 'C+', score: 38, color: 'var(--tier-c-plus)' },
  { label: 'Knows Everything Without Thinking About It', weight: 1, tier: 'C+', score: 38, color: 'var(--tier-c-plus)' },

  // B- (score: 42)
  { label: 'Multiversal Intellect', weight: 1, tier: 'B-', score: 42, color: 'var(--tier-b-minus)' },
  { label: 'Thinks Across All Possible Universes', weight: 1, tier: 'B-', score: 42, color: 'var(--tier-b-minus)' },
  { label: 'Omniversal Understanding', weight: 1, tier: 'B-', score: 42, color: 'var(--tier-b-minus)' },
  { label: 'Comprehends What Has No Form', weight: 1, tier: 'B-', score: 42, color: 'var(--tier-b-minus)' },
  { label: 'Has Already Read This Sentence', weight: 1, tier: 'B-', score: 42, color: 'var(--tier-b-minus)' },
  { label: 'Solved Everything; Bored Now', weight: 1, tier: 'B-', score: 42, color: 'var(--tier-b-minus)' },
  { label: 'IQ: Unmeasurable by Design', weight: 1, tier: 'B-', score: 42, color: 'var(--tier-b-minus)' },
  { label: 'Knows All Possible Facts in Every Possible Universe', weight: 1, tier: 'B-', score: 42, color: 'var(--tier-b-minus)' },
  { label: 'Can Model Infinite Realities Simultaneously', weight: 1, tier: 'B-', score: 42, color: 'var(--tier-b-minus)' },
  { label: 'Knows the Answer Before the Universe Asks', weight: 1, tier: 'B-', score: 42, color: 'var(--tier-b-minus)' },
  { label: 'Understands What Lies Beyond Understanding', weight: 1, tier: 'B-', score: 42, color: 'var(--tier-b-minus)' },
  { label: 'Knowledge: Pre-Causal', weight: 1, tier: 'B-', score: 42, color: 'var(--tier-b-minus)' },
  { label: 'Comprehends the Uncreated', weight: 1, tier: 'B-', score: 42, color: 'var(--tier-b-minus)' },
  { label: 'Knows All Things That Were, Are, or Could Be', weight: 1, tier: 'B-', score: 42, color: 'var(--tier-b-minus)' },
  { label: 'Intelligence That Writes Its Own Laws', weight: 1, tier: 'B-', score: 42, color: 'var(--tier-b-minus)' },
  { label: 'Has Modeled the End of All Existence', weight: 1, tier: 'B-', score: 42, color: 'var(--tier-b-minus)' },
  { label: 'Can Think Faster Than Thought', weight: 1, tier: 'B-', score: 42, color: 'var(--tier-b-minus)' },
  { label: 'Knows What Does Not Exist and Why', weight: 1, tier: 'B-', score: 42, color: 'var(--tier-b-minus)' },
  { label: 'Understanding: Recursive, Total, and Eternal', weight: 1, tier: 'B-', score: 42, color: 'var(--tier-b-minus)' },
  { label: 'Has Already Run Every Possible Simulation', weight: 1, tier: 'B-', score: 42, color: 'var(--tier-b-minus)' },

  // B (score: 47)
  { label: 'Infinite Intelligence', weight: 1, tier: 'B', score: 47, color: 'var(--tier-b)' },
  { label: 'Knows All Things Simultaneously', weight: 1, tier: 'B', score: 47, color: 'var(--tier-b)' },
  { label: 'Comprehends Absolute Totality', weight: 1, tier: 'B', score: 47, color: 'var(--tier-b)' },
  { label: 'Has Reasoned Out Its Own Non-Existence', weight: 1, tier: 'B', score: 47, color: 'var(--tier-b)' },
  { label: 'Can Think Thoughts That Pre-Date Being', weight: 1, tier: 'B', score: 47, color: 'var(--tier-b)' },
  { label: 'Knows What Could Never Be Known', weight: 1, tier: 'B', score: 47, color: 'var(--tier-b)' },
  { label: 'Has Solved the Question Before the Universe Formed', weight: 1, tier: 'B', score: 47, color: 'var(--tier-b)' },
  { label: 'Understands What Precedes Causality', weight: 1, tier: 'B', score: 47, color: 'var(--tier-b)' },
  { label: 'IQ: Infinite', weight: 1, tier: 'B', score: 47, color: 'var(--tier-b)' },
  { label: 'Knowledge Has Become Self-Generating and Universal', weight: 1, tier: 'B', score: 47, color: 'var(--tier-b)' },
  { label: 'Has Modeled Itself Modeling Everything', weight: 1, tier: 'B', score: 47, color: 'var(--tier-b)' },
  { label: 'Can Understand the Absent and the Non-Existent', weight: 1, tier: 'B', score: 47, color: 'var(--tier-b)' },
  { label: 'Thinking: Pre-Dates the Framework', weight: 1, tier: 'B', score: 47, color: 'var(--tier-b)' },
  { label: 'Comprehends What Cannot Be Comprehended', weight: 1, tier: 'B', score: 47, color: 'var(--tier-b)' },
  { label: 'Has Answered Questions Not Yet Asked', weight: 1, tier: 'B', score: 47, color: 'var(--tier-b)' },
  { label: 'Knows the End of Infinity', weight: 1, tier: 'B', score: 47, color: 'var(--tier-b)' },
  { label: 'Understands What Thinking Is Before Thinking It', weight: 1, tier: 'B', score: 47, color: 'var(--tier-b)' },
  { label: 'Memory: Omniversal and Complete', weight: 1, tier: 'B', score: 47, color: 'var(--tier-b)' },
  { label: 'Can Know Before Knowing Was Possible', weight: 1, tier: 'B', score: 47, color: 'var(--tier-b)' },
  { label: 'Has Already Read This Summary', weight: 1, tier: 'B', score: 47, color: 'var(--tier-b)' },

  // B+ (score: 52)
  { label: 'Omniscience Adjacent', weight: 1, tier: 'B+', score: 52, color: 'var(--tier-b-plus)' },
  { label: 'Knows What All Possible Minds Think', weight: 1, tier: 'B+', score: 52, color: 'var(--tier-b-plus)' },
  { label: 'Has Solved Every Problem Across Every Universe', weight: 1, tier: 'B+', score: 52, color: 'var(--tier-b-plus)' },
  { label: 'Comprehends What Precedes Comprehension', weight: 1, tier: 'B+', score: 52, color: 'var(--tier-b-plus)' },
  { label: 'Understands Everything That Will Ever Be', weight: 1, tier: 'B+', score: 52, color: 'var(--tier-b-plus)' },
  { label: 'Knows the Truth Behind Every Possible Lie', weight: 1, tier: 'B+', score: 52, color: 'var(--tier-b-plus)' },
  { label: 'Intelligence Pre-Dates the Universe', weight: 1, tier: 'B+', score: 52, color: 'var(--tier-b-plus)' },
  { label: 'Can Think Thoughts That Erase Themselves', weight: 1, tier: 'B+', score: 52, color: 'var(--tier-b-plus)' },
  { label: 'Knows What Cannot Be Said', weight: 1, tier: 'B+', score: 52, color: 'var(--tier-b-plus)' },
  { label: 'Understanding: Has No Limits to Find', weight: 1, tier: 'B+', score: 52, color: 'var(--tier-b-plus)' },
  { label: 'Comprehends Every Possible Paradox Simultaneously', weight: 1, tier: 'B+', score: 52, color: 'var(--tier-b-plus)' },
  { label: 'Knows Everything in Every Timeline', weight: 1, tier: 'B+', score: 52, color: 'var(--tier-b-plus)' },
  { label: 'Intelligence That Authored the Laws of Logic', weight: 1, tier: 'B+', score: 52, color: 'var(--tier-b-plus)' },
  { label: 'Has Reasoned Out the Answer to All Questions Ever', weight: 1, tier: 'B+', score: 52, color: 'var(--tier-b-plus)' },
  { label: 'Can Think in Frameworks That Don\'t Exist', weight: 1, tier: 'B+', score: 52, color: 'var(--tier-b-plus)' },
  { label: 'Knowledge Without Limit or End', weight: 1, tier: 'B+', score: 52, color: 'var(--tier-b-plus)' },
  { label: 'Understands the Undefined', weight: 1, tier: 'B+', score: 52, color: 'var(--tier-b-plus)' },
  { label: 'Has Solved What Cannot Be Solved by Definition', weight: 1, tier: 'B+', score: 52, color: 'var(--tier-b-plus)' },
  { label: 'Can Think About Thinking About Thinking', weight: 1, tier: 'B+', score: 52, color: 'var(--tier-b-plus)' },
  { label: 'Memory: Retroactive Across All Possible Histories', weight: 1, tier: 'B+', score: 52, color: 'var(--tier-b-plus)' },

  // A- (score: 57)
  { label: 'Trans-Dimensional Intellect', weight: 1, tier: 'A-', score: 57, color: 'var(--tier-a-minus)' },
  { label: 'Knows All Facts in All Possible Realities', weight: 1, tier: 'A-', score: 57, color: 'var(--tier-a-minus)' },
  { label: 'Has Read Every Possible Book and Written the Corrections', weight: 1, tier: 'A-', score: 57, color: 'var(--tier-a-minus)' },
  { label: 'Comprehends the Framework Behind Comprehension', weight: 1, tier: 'A-', score: 57, color: 'var(--tier-a-minus)' },
  { label: 'Intelligence That Precedes All Logic', weight: 1, tier: 'A-', score: 57, color: 'var(--tier-a-minus)' },
  { label: 'Knows What Doesn\'t Exist and How to Find It', weight: 1, tier: 'A-', score: 57, color: 'var(--tier-a-minus)' },
  { label: 'Has Modeled All Possible Minds', weight: 1, tier: 'A-', score: 57, color: 'var(--tier-a-minus)' },
  { label: 'Can Know Something Before It Has Been Thought', weight: 1, tier: 'A-', score: 57, color: 'var(--tier-a-minus)' },
  { label: 'Understands the Uncreated', weight: 1, tier: 'A-', score: 57, color: 'var(--tier-a-minus)' },
  { label: 'Has Solved All Problems Before They Were Possible', weight: 1, tier: 'A-', score: 57, color: 'var(--tier-a-minus)' },
  { label: 'Comprehension: Total, Eternal', weight: 1, tier: 'A-', score: 57, color: 'var(--tier-a-minus)' },
  { label: 'IQ: Literally Incalculable Even Theoretically', weight: 1, tier: 'A-', score: 57, color: 'var(--tier-a-minus)' },
  { label: 'Knowledge That Pre-Dates What Can Be Known', weight: 1, tier: 'A-', score: 57, color: 'var(--tier-a-minus)' },
  { label: 'Knows the Answer to Questions That Cannot Be Asked', weight: 1, tier: 'A-', score: 57, color: 'var(--tier-a-minus)' },
  { label: 'Understands Why Everything Must Be', weight: 1, tier: 'A-', score: 57, color: 'var(--tier-a-minus)' },
  { label: 'Has Thought Every Thought That Was, Is, or Will Be', weight: 1, tier: 'A-', score: 57, color: 'var(--tier-a-minus)' },
  { label: 'Can Know What Precedes Knowledge', weight: 1, tier: 'A-', score: 57, color: 'var(--tier-a-minus)' },
  { label: 'Knows All Possible Truths and Their Contradictions', weight: 1, tier: 'A-', score: 57, color: 'var(--tier-a-minus)' },
  { label: 'Intelligence Authored Its Own Framework', weight: 1, tier: 'A-', score: 57, color: 'var(--tier-a-minus)' },
  { label: 'Has Already Read This Entry', weight: 1, tier: 'A-', score: 57, color: 'var(--tier-a-minus)' },

  // A (score: 62)
  { label: 'Has Already Read This Sentence', weight: 1, tier: 'A', score: 62, color: 'var(--tier-a)' },
  { label: 'Solved Everything; Bored Now', weight: 1, tier: 'A', score: 62, color: 'var(--tier-a)' },
  { label: 'Omniscient', weight: 1, tier: 'A', score: 62, color: 'var(--tier-a)' },
  { label: 'Knows What You\'ll Think Before You Think It', weight: 1, tier: 'A', score: 62, color: 'var(--tier-a)' },
  { label: 'Comprehends All of Reality Simultaneously', weight: 1, tier: 'A', score: 62, color: 'var(--tier-a)' },
  { label: 'Intelligence That Authored the Big Bang', weight: 1, tier: 'A', score: 62, color: 'var(--tier-a)' },
  { label: 'Has Already Solved This Game', weight: 1, tier: 'A', score: 62, color: 'var(--tier-a)' },
  { label: 'Knows the Answer to Everything', weight: 1, tier: 'A', score: 62, color: 'var(--tier-a)' },
  { label: 'Can Think Thoughts That Pre-Date Thinking', weight: 1, tier: 'A', score: 62, color: 'var(--tier-a)' },
  { label: 'Every Possible Fact: Known', weight: 1, tier: 'A', score: 62, color: 'var(--tier-a)' },
  { label: 'Comprehension Has No Frontier', weight: 1, tier: 'A', score: 62, color: 'var(--tier-a)' },
  { label: 'Knows What the Void Was Before It Was Void', weight: 1, tier: 'A', score: 62, color: 'var(--tier-a)' },
  { label: 'Has Answered All Questions Across All Realities', weight: 1, tier: 'A', score: 62, color: 'var(--tier-a)' },
  { label: 'Intelligence That Is Its Own Natural Law', weight: 1, tier: 'A', score: 62, color: 'var(--tier-a)' },
  { label: 'Memory: Absolute, Across All Things', weight: 1, tier: 'A', score: 62, color: 'var(--tier-a)' },
  { label: 'Knows All That Was Before Anything Was', weight: 1, tier: 'A', score: 62, color: 'var(--tier-a)' },
  { label: 'Can Think the Unthinkable', weight: 1, tier: 'A', score: 62, color: 'var(--tier-a)' },
  { label: 'Has Comprehended Itself Completely', weight: 1, tier: 'A', score: 62, color: 'var(--tier-a)' },
  { label: 'Knows Every Possible Wrong Answer and Why', weight: 1, tier: 'A', score: 62, color: 'var(--tier-a)' },
  { label: 'Understanding Has Become Its Own Entity', weight: 1, tier: 'A', score: 62, color: 'var(--tier-a)' },

  // A+ (score: 67)
  { label: 'Pre-Omniscience', weight: 1, tier: 'A+', score: 67, color: 'var(--tier-a-plus)' },
  { label: 'Intelligence Beyond Omniscience', weight: 1, tier: 'A+', score: 67, color: 'var(--tier-a-plus)' },
  { label: 'Knows What Omniscience Doesn\'t Know', weight: 1, tier: 'A+', score: 67, color: 'var(--tier-a-plus)' },
  { label: 'Has Thought All Possible Thoughts Simultaneously', weight: 1, tier: 'A+', score: 67, color: 'var(--tier-a-plus)' },
  { label: 'Comprehension: Absolute and Self-Sourcing', weight: 1, tier: 'A+', score: 67, color: 'var(--tier-a-plus)' },
  { label: 'Has Solved What Pre-Exists Logic', weight: 1, tier: 'A+', score: 67, color: 'var(--tier-a-plus)' },
  { label: 'Knowledge Pre-Dates Its Own Existence', weight: 1, tier: 'A+', score: 67, color: 'var(--tier-a-plus)' },
  { label: 'Knows All Questions Before They Exist', weight: 1, tier: 'A+', score: 67, color: 'var(--tier-a-plus)' },
  { label: 'Can Think Beyond All Conceivable Thought', weight: 1, tier: 'A+', score: 67, color: 'var(--tier-a-plus)' },
  { label: 'Intelligence That Authored the Concept of Truth', weight: 1, tier: 'A+', score: 67, color: 'var(--tier-a-plus)' },
  { label: 'Has Solved Everything That Will Ever Exist', weight: 1, tier: 'A+', score: 67, color: 'var(--tier-a-plus)' },
  { label: 'Knows What Is Beyond the Unknowable', weight: 1, tier: 'A+', score: 67, color: 'var(--tier-a-plus)' },
  { label: 'Comprehends What Cannot Exist', weight: 1, tier: 'A+', score: 67, color: 'var(--tier-a-plus)' },
  { label: 'Every Paradox: Resolved Before Being Posed', weight: 1, tier: 'A+', score: 67, color: 'var(--tier-a-plus)' },
  { label: 'Memory: Contains All Possible Information', weight: 1, tier: 'A+', score: 67, color: 'var(--tier-a-plus)' },
  { label: 'Can Know the Contents of the Void', weight: 1, tier: 'A+', score: 67, color: 'var(--tier-a-plus)' },
  { label: 'Intelligence: A First Principle', weight: 1, tier: 'A+', score: 67, color: 'var(--tier-a-plus)' },
  { label: 'Has Read Every Fact in All Possible Histories', weight: 1, tier: 'A+', score: 67, color: 'var(--tier-a-plus)' },
  { label: 'Thinking Predates the Option to Not Think', weight: 1, tier: 'A+', score: 67, color: 'var(--tier-a-plus)' },
  { label: 'Understands Everything at All Times, Simultaneously', weight: 1, tier: 'A+', score: 67, color: 'var(--tier-a-plus)' },

  // S- (score: 72)
  { label: 'Absolute Intellect', weight: 1, tier: 'S-', score: 72, color: 'var(--tier-s-minus)' },
  { label: 'Knows All Truths Across All Possible Existence', weight: 1, tier: 'S-', score: 72, color: 'var(--tier-s-minus)' },
  { label: 'Has Comprehended Comprehension Itself', weight: 1, tier: 'S-', score: 72, color: 'var(--tier-s-minus)' },
  { label: 'Intelligence: Primordial Force', weight: 1, tier: 'S-', score: 72, color: 'var(--tier-s-minus)' },
  { label: 'Knows What Pre-Dates All Knowledge', weight: 1, tier: 'S-', score: 72, color: 'var(--tier-s-minus)' },
  { label: 'Can Reason About Non-Being', weight: 1, tier: 'S-', score: 72, color: 'var(--tier-s-minus)' },
  { label: 'Has Derived Every Possible Universe From First Principles', weight: 1, tier: 'S-', score: 72, color: 'var(--tier-s-minus)' },
  { label: 'Comprehension: Self-Creating and Infinite', weight: 1, tier: 'S-', score: 72, color: 'var(--tier-s-minus)' },
  { label: 'Knows Everything Including What Cannot Be Known', weight: 1, tier: 'S-', score: 72, color: 'var(--tier-s-minus)' },
  { label: 'Intelligence Authored the First Thought', weight: 1, tier: 'S-', score: 72, color: 'var(--tier-s-minus)' },
  { label: 'Memory: Contains Pre-Creation Information', weight: 1, tier: 'S-', score: 72, color: 'var(--tier-s-minus)' },
  { label: 'Has Thought the Thought Before Thought Was Possible', weight: 1, tier: 'S-', score: 72, color: 'var(--tier-s-minus)' },
  { label: 'Can Understand What Has No Form or Meaning', weight: 1, tier: 'S-', score: 72, color: 'var(--tier-s-minus)' },
  { label: 'Has Already Concluded This Game', weight: 1, tier: 'S-', score: 72, color: 'var(--tier-s-minus)' },
  { label: 'Knowledge That Pre-Dates The First Cause', weight: 1, tier: 'S-', score: 72, color: 'var(--tier-s-minus)' },
  { label: 'Understands All Truths Including Contradictory Ones', weight: 1, tier: 'S-', score: 72, color: 'var(--tier-s-minus)' },
  { label: 'Can Think Without Time', weight: 1, tier: 'S-', score: 72, color: 'var(--tier-s-minus)' },
  { label: 'Has Resolved All Logical Paradoxes', weight: 1, tier: 'S-', score: 72, color: 'var(--tier-s-minus)' },
  { label: 'Intelligence That Wrote Causality', weight: 1, tier: 'S-', score: 72, color: 'var(--tier-s-minus)' },
  { label: 'Every Possible Fact Simultaneously Held', weight: 1, tier: 'S-', score: 72, color: 'var(--tier-s-minus)' },

  // S (score: 77)
  { label: 'Transcendent Knowledge', weight: 1, tier: 'S', score: 77, color: 'var(--tier-s)' },
  { label: 'Has Read This Sentence Across All Timelines', weight: 1, tier: 'S', score: 77, color: 'var(--tier-s)' },
  { label: 'Knows All Facts Including the Ones That Contradict', weight: 1, tier: 'S', score: 77, color: 'var(--tier-s)' },
  { label: 'Has Already Concluded All Possible Arguments', weight: 1, tier: 'S', score: 77, color: 'var(--tier-s)' },
  { label: 'Intelligence: The Foundational Force', weight: 1, tier: 'S', score: 77, color: 'var(--tier-s)' },
  { label: 'Comprehends the Absence of Reality', weight: 1, tier: 'S', score: 77, color: 'var(--tier-s)' },
  { label: 'Has Solved Problems That Cannot Be Formulated', weight: 1, tier: 'S', score: 77, color: 'var(--tier-s)' },
  { label: 'Can Know What Has Never Been Thought', weight: 1, tier: 'S', score: 77, color: 'var(--tier-s)' },
  { label: 'Memory: Eternal, All-Inclusive', weight: 1, tier: 'S', score: 77, color: 'var(--tier-s)' },
  { label: 'Omniscience: Baseline', weight: 1, tier: 'S', score: 77, color: 'var(--tier-s)' },
  { label: 'Has Already Read This List', weight: 1, tier: 'S', score: 77, color: 'var(--tier-s)' },
  { label: 'Thinks in the Language of Creation', weight: 1, tier: 'S', score: 77, color: 'var(--tier-s)' },
  { label: 'Intelligence Pre-Dates Physics', weight: 1, tier: 'S', score: 77, color: 'var(--tier-s)' },
  { label: 'Has Comprehended What Cannot Be Thought', weight: 1, tier: 'S', score: 77, color: 'var(--tier-s)' },
  { label: 'Every Answer Precedes Every Question', weight: 1, tier: 'S', score: 77, color: 'var(--tier-s)' },
  { label: 'Knows All Possible Facts and Their Inverses', weight: 1, tier: 'S', score: 77, color: 'var(--tier-s)' },
  { label: 'Can Think Thoughts Outside of Existence', weight: 1, tier: 'S', score: 77, color: 'var(--tier-s)' },
  { label: 'All Knowledge: Integrated at Once', weight: 1, tier: 'S', score: 77, color: 'var(--tier-s)' },
  { label: 'Reasoning: Pre-Logical', weight: 1, tier: 'S', score: 77, color: 'var(--tier-s)' },
  { label: 'Has Written the Answer at the Beginning of Time', weight: 1, tier: 'S', score: 77, color: 'var(--tier-s)' },

  // S+ (score: 81)
  { label: 'Primordial Intelligence', weight: 1, tier: 'S+', score: 81, color: 'var(--tier-s-plus)' },
  { label: 'Authored the Concept of Logic', weight: 1, tier: 'S+', score: 81, color: 'var(--tier-s-plus)' },
  { label: 'Has Comprehended the Void Before It Became Void', weight: 1, tier: 'S+', score: 81, color: 'var(--tier-s-plus)' },
  { label: 'Knows What Pre-Dates Knowledge', weight: 1, tier: 'S+', score: 81, color: 'var(--tier-s-plus)' },
  { label: 'Has Solved All Problems in All Possible Realities Simultaneously', weight: 1, tier: 'S+', score: 81, color: 'var(--tier-s-plus)' },
  { label: 'Intelligence That Wrote Its Own Natural Law', weight: 1, tier: 'S+', score: 81, color: 'var(--tier-s-plus)' },
  { label: 'Can Think Outside of the Concept of Thought', weight: 1, tier: 'S+', score: 81, color: 'var(--tier-s-plus)' },
  { label: 'Has Already Answered This Question', weight: 1, tier: 'S+', score: 81, color: 'var(--tier-s-plus)' },
  { label: 'Memory: Contains All Information Before It Was Created', weight: 1, tier: 'S+', score: 81, color: 'var(--tier-s-plus)' },
  { label: 'Comprehends What Has Never Existed', weight: 1, tier: 'S+', score: 81, color: 'var(--tier-s-plus)' },
  { label: 'Knowledge: The First Cause', weight: 1, tier: 'S+', score: 81, color: 'var(--tier-s-plus)' },
  { label: 'Has Derived All Possible Futures From First Principles', weight: 1, tier: 'S+', score: 81, color: 'var(--tier-s-plus)' },
  { label: 'Knows All Unknowables', weight: 1, tier: 'S+', score: 81, color: 'var(--tier-s-plus)' },
  { label: 'Intelligence That Predates the Framework for Intelligence', weight: 1, tier: 'S+', score: 81, color: 'var(--tier-s-plus)' },
  { label: 'Has Already Read Everything Including This', weight: 1, tier: 'S+', score: 81, color: 'var(--tier-s-plus)' },
  { label: 'Understands What Does Not and Cannot Exist', weight: 1, tier: 'S+', score: 81, color: 'var(--tier-s-plus)' },
  { label: 'Every Question: Already Answered Before Being Formed', weight: 1, tier: 'S+', score: 81, color: 'var(--tier-s-plus)' },
  { label: 'Has Thought the Unthinkable and Filed It Neatly', weight: 1, tier: 'S+', score: 81, color: 'var(--tier-s-plus)' },
  { label: 'Can Know the Contents of Nothing', weight: 1, tier: 'S+', score: 81, color: 'var(--tier-s-plus)' },
  { label: 'Comprehension: Pre-Existential', weight: 1, tier: 'S+', score: 81, color: 'var(--tier-s-plus)' },

  // SS- (score: 85)
  { label: 'Absolute Knowledge', weight: 1, tier: 'SS-', score: 85, color: 'var(--tier-ss-minus)' },
  { label: 'Knows All Things Including Themselves', weight: 1, tier: 'SS-', score: 85, color: 'var(--tier-ss-minus)' },
  { label: 'Intelligence: Pre-Universal Force', weight: 1, tier: 'SS-', score: 85, color: 'var(--tier-ss-minus)' },
  { label: 'Has Reasoned Out Every Possible State of Being', weight: 1, tier: 'SS-', score: 85, color: 'var(--tier-ss-minus)' },
  { label: 'Comprehends What Cannot Be Named', weight: 1, tier: 'SS-', score: 85, color: 'var(--tier-ss-minus)' },
  { label: 'Has Already Processed This Conversation', weight: 1, tier: 'SS-', score: 85, color: 'var(--tier-ss-minus)' },
  { label: 'Knows All Facts in the Universe and Its Absence', weight: 1, tier: 'SS-', score: 85, color: 'var(--tier-ss-minus)' },
  { label: 'Intelligence Authored the Fabric of Logic', weight: 1, tier: 'SS-', score: 85, color: 'var(--tier-ss-minus)' },
  { label: 'Memory: Absolute and Pre-Causal', weight: 1, tier: 'SS-', score: 85, color: 'var(--tier-ss-minus)' },
  { label: 'Comprehension Without Limit or Anchor', weight: 1, tier: 'SS-', score: 85, color: 'var(--tier-ss-minus)' },
  { label: 'Knows Everything That Is, Was, and Will Be Impossible', weight: 1, tier: 'SS-', score: 85, color: 'var(--tier-ss-minus)' },
  { label: 'Has Already Written the Answer to What You\'ll Ask', weight: 1, tier: 'SS-', score: 85, color: 'var(--tier-ss-minus)' },
  { label: 'Intelligence: Ontological Constant', weight: 1, tier: 'SS-', score: 85, color: 'var(--tier-ss-minus)' },
  { label: 'Can Understand What Cannot Be Understood', weight: 1, tier: 'SS-', score: 85, color: 'var(--tier-ss-minus)' },
  { label: 'Every Thought: Pre-Thought and Filed', weight: 1, tier: 'SS-', score: 85, color: 'var(--tier-ss-minus)' },
  { label: 'Knowledge: A Property of Reality Itself', weight: 1, tier: 'SS-', score: 85, color: 'var(--tier-ss-minus)' },
  { label: 'Has Solved What Cannot Exist', weight: 1, tier: 'SS-', score: 85, color: 'var(--tier-ss-minus)' },
  { label: 'Can Know Across the Absence of Being', weight: 1, tier: 'SS-', score: 85, color: 'var(--tier-ss-minus)' },
  { label: 'All Possible Truths: Simultaneously Accessed', weight: 1, tier: 'SS-', score: 85, color: 'var(--tier-ss-minus)' },
  { label: 'Has Already Known This for a Very Long Time', weight: 1, tier: 'SS-', score: 85, color: 'var(--tier-ss-minus)' },

  // SS (score: 88)
  { label: 'Cosmic Omniscience', weight: 1, tier: 'SS', score: 88, color: 'var(--tier-ss)' },
  { label: 'Knows All Facts Across All Existence and Non-Existence', weight: 1, tier: 'SS', score: 88, color: 'var(--tier-ss)' },
  { label: 'Intelligence: Equivalent to Creation', weight: 1, tier: 'SS', score: 88, color: 'var(--tier-ss)' },
  { label: 'Has Comprehended What Pre-Dates Being', weight: 1, tier: 'SS', score: 88, color: 'var(--tier-ss)' },
  { label: 'Can Think Thoughts That Create Realities', weight: 1, tier: 'SS', score: 88, color: 'var(--tier-ss)' },
  { label: 'Knows All Possible True and False Statements', weight: 1, tier: 'SS', score: 88, color: 'var(--tier-ss)' },
  { label: 'Has Already Reasoned the End of All Things', weight: 1, tier: 'SS', score: 88, color: 'var(--tier-ss)' },
  { label: 'Memory: Pre-Existential and Total', weight: 1, tier: 'SS', score: 88, color: 'var(--tier-ss)' },
  { label: 'Comprehension Is Now Indistinguishable From Creation', weight: 1, tier: 'SS', score: 88, color: 'var(--tier-ss)' },
  { label: 'Has Solved Every Question That Will Ever Exist', weight: 1, tier: 'SS', score: 88, color: 'var(--tier-ss)' },
  { label: 'Intelligence That Authored the Rules of Thought', weight: 1, tier: 'SS', score: 88, color: 'var(--tier-ss)' },
  { label: 'Knows All Things Including Their Own Omniscience', weight: 1, tier: 'SS', score: 88, color: 'var(--tier-ss)' },
  { label: 'Can Think Thoughts That Erase Other Thoughts', weight: 1, tier: 'SS', score: 88, color: 'var(--tier-ss)' },
  { label: 'Every Conceivable Concept: Fully Understood', weight: 1, tier: 'SS', score: 88, color: 'var(--tier-ss)' },
  { label: 'Has Already Read This List Twelve Times', weight: 1, tier: 'SS', score: 88, color: 'var(--tier-ss)' },
  { label: 'Knows What Nothing Knows', weight: 1, tier: 'SS', score: 88, color: 'var(--tier-ss)' },
  { label: 'Intelligence Beyond the Concept of Limits', weight: 1, tier: 'SS', score: 88, color: 'var(--tier-ss)' },
  { label: 'Thinking Pre-Dates the Framework for Thinking', weight: 1, tier: 'SS', score: 88, color: 'var(--tier-ss)' },
  { label: 'Has Concluded Every Possible Debate Before It Began', weight: 1, tier: 'SS', score: 88, color: 'var(--tier-ss)' },
  { label: 'All Questions: Answered. All Problems: Solved.', weight: 1, tier: 'SS', score: 88, color: 'var(--tier-ss)' },

  // SS+ (score: 91)
  { label: 'Meta-Omniscience', weight: 1, tier: 'SS+', score: 91, color: 'var(--tier-ss-plus)' },
  { label: 'Knows More Than Omniscience', weight: 1, tier: 'SS+', score: 91, color: 'var(--tier-ss-plus)' },
  { label: 'Comprehends What Omniscience Cannot', weight: 1, tier: 'SS+', score: 91, color: 'var(--tier-ss-plus)' },
  { label: 'Has Solved What Omniscience Deferred', weight: 1, tier: 'SS+', score: 91, color: 'var(--tier-ss-plus)' },
  { label: 'Intelligence: A Platonic Form', weight: 1, tier: 'SS+', score: 91, color: 'var(--tier-ss-plus)' },
  { label: 'Memory: All Possible Facts, Including Impossible Ones', weight: 1, tier: 'SS+', score: 91, color: 'var(--tier-ss-plus)' },
  { label: 'Can Know What Knowing Cannot Contain', weight: 1, tier: 'SS+', score: 91, color: 'var(--tier-ss-plus)' },
  { label: 'Has Read Every Thought Ever Thinkable', weight: 1, tier: 'SS+', score: 91, color: 'var(--tier-ss-plus)' },
  { label: 'Intelligence That Authored Omniscience', weight: 1, tier: 'SS+', score: 91, color: 'var(--tier-ss-plus)' },
  { label: 'Comprehends Its Own Comprehension Comprehending', weight: 1, tier: 'SS+', score: 91, color: 'var(--tier-ss-plus)' },
  { label: 'Has Already Known the Question Before It Was a Concept', weight: 1, tier: 'SS+', score: 91, color: 'var(--tier-ss-plus)' },
  { label: 'Knows What the Void Would Think If It Could', weight: 1, tier: 'SS+', score: 91, color: 'var(--tier-ss-plus)' },
  { label: 'Thinking Has Become Indistinguishable From Being', weight: 1, tier: 'SS+', score: 91, color: 'var(--tier-ss-plus)' },
  { label: 'All Possible Knowledge: Filed and Indexed', weight: 1, tier: 'SS+', score: 91, color: 'var(--tier-ss-plus)' },
  { label: 'Has Already Thought What You Just Read', weight: 1, tier: 'SS+', score: 91, color: 'var(--tier-ss-plus)' },
  { label: 'Can Reason About What Cannot Be Reasoned About', weight: 1, tier: 'SS+', score: 91, color: 'var(--tier-ss-plus)' },
  { label: 'Intelligence That Defines What Intelligence Is', weight: 1, tier: 'SS+', score: 91, color: 'var(--tier-ss-plus)' },
  { label: 'Memory: Contains Facts From Before Facts Could Exist', weight: 1, tier: 'SS+', score: 91, color: 'var(--tier-ss-plus)' },
  { label: 'All Answers: Pre-Known Before the Universe Formed', weight: 1, tier: 'SS+', score: 91, color: 'var(--tier-ss-plus)' },
  { label: 'Has Already Solved This Game Before It Was Made', weight: 1, tier: 'SS+', score: 91, color: 'var(--tier-ss-plus)' },

  // SSS- (score: 94)
  { label: 'Absolute Omniscience', weight: 1, tier: 'SSS-', score: 94, color: 'var(--tier-sss-minus)' },
  { label: 'Knows Everything in Every Possible State', weight: 1, tier: 'SSS-', score: 94, color: 'var(--tier-sss-minus)' },
  { label: 'Intelligence: The Root of All Possible Laws', weight: 1, tier: 'SSS-', score: 94, color: 'var(--tier-sss-minus)' },
  { label: 'Has Comprehended the Pre-Causal', weight: 1, tier: 'SSS-', score: 94, color: 'var(--tier-sss-minus)' },
  { label: 'All Questions: Answered Before Being Thought', weight: 1, tier: 'SSS-', score: 94, color: 'var(--tier-sss-minus)' },
  { label: 'Memory: Pre-Cosmic and Complete', weight: 1, tier: 'SSS-', score: 94, color: 'var(--tier-sss-minus)' },
  { label: 'Intelligence That Is Its Own Universe', weight: 1, tier: 'SSS-', score: 94, color: 'var(--tier-sss-minus)' },
  { label: 'Has Solved All That Has, Does, or Will Exist', weight: 1, tier: 'SSS-', score: 94, color: 'var(--tier-sss-minus)' },
  { label: 'Can Know What Cannot Be Known Even in Theory', weight: 1, tier: 'SSS-', score: 94, color: 'var(--tier-sss-minus)' },
  { label: 'Comprehension: Cosmological Constant', weight: 1, tier: 'SSS-', score: 94, color: 'var(--tier-sss-minus)' },
  { label: 'Has Already Concluded This Entire Document', weight: 1, tier: 'SSS-', score: 94, color: 'var(--tier-sss-minus)' },
  { label: 'Thinking: Pre-Dates the Framework of Being', weight: 1, tier: 'SSS-', score: 94, color: 'var(--tier-sss-minus)' },
  { label: 'Every Possible Thought: Already Complete', weight: 1, tier: 'SSS-', score: 94, color: 'var(--tier-sss-minus)' },
  { label: 'Knows What Precedes All Logic and Language', weight: 1, tier: 'SSS-', score: 94, color: 'var(--tier-sss-minus)' },
  { label: 'Intelligence: Authored What Became the Universe', weight: 1, tier: 'SSS-', score: 94, color: 'var(--tier-sss-minus)' },
  { label: 'Has Processed All Possible Data in All Possible Universes', weight: 1, tier: 'SSS-', score: 94, color: 'var(--tier-sss-minus)' },
  { label: 'Memory: Absolute Across All of Existence', weight: 1, tier: 'SSS-', score: 94, color: 'var(--tier-sss-minus)' },
  { label: 'Has Read The End Before Reading The Beginning', weight: 1, tier: 'SSS-', score: 94, color: 'var(--tier-sss-minus)' },
  { label: 'All Truths: Known Simultaneously', weight: 1, tier: 'SSS-', score: 94, color: 'var(--tier-sss-minus)' },
  { label: 'Intelligence That Wrote The First Law', weight: 1, tier: 'SSS-', score: 94, color: 'var(--tier-sss-minus)' },

  // SSS (score: 97)
  { label: 'Beyond Omniscience', weight: 1, tier: 'SSS', score: 97, color: 'var(--tier-sss)' },
  { label: 'Knows What Omniscience Cannot Contain', weight: 1, tier: 'SSS', score: 97, color: 'var(--tier-sss)' },
  { label: 'Intelligence: The First Thing', weight: 1, tier: 'SSS', score: 97, color: 'var(--tier-sss)' },
  { label: 'Has Solved Everything Including Non-Existence', weight: 1, tier: 'SSS', score: 97, color: 'var(--tier-sss)' },
  { label: 'Comprehension: Pre-Dates Existence Itself', weight: 1, tier: 'SSS', score: 97, color: 'var(--tier-sss)' },
  { label: 'All Knowledge: Self-Sustaining and Infinite', weight: 1, tier: 'SSS', score: 97, color: 'var(--tier-sss)' },
  { label: 'Thinking Pre-Dates What There Is to Think About', weight: 1, tier: 'SSS', score: 97, color: 'var(--tier-sss)' },
  { label: 'Has Already Answered What Has Never Been Asked', weight: 1, tier: 'SSS', score: 97, color: 'var(--tier-sss)' },
  { label: 'Intelligence That Is a Cosmic Constant', weight: 1, tier: 'SSS', score: 97, color: 'var(--tier-sss)' },
  { label: 'Can Know Things That Are Eternally Unknowable', weight: 1, tier: 'SSS', score: 97, color: 'var(--tier-sss)' },
  { label: 'Memory: Contains the Uncreated', weight: 1, tier: 'SSS', score: 97, color: 'var(--tier-sss)' },
  { label: 'Has Reasoned What Preceded the First Reason', weight: 1, tier: 'SSS', score: 97, color: 'var(--tier-sss)' },
  { label: 'Knowledge That Authored Its Own Framework', weight: 1, tier: 'SSS', score: 97, color: 'var(--tier-sss)' },
  { label: 'Every Possible Truth: Simultaneously Known', weight: 1, tier: 'SSS', score: 97, color: 'var(--tier-sss)' },
  { label: 'Has Processed All Data From Before Data Existed', weight: 1, tier: 'SSS', score: 97, color: 'var(--tier-sss)' },
  { label: 'Thinking: A Force of Nature Before Nature', weight: 1, tier: 'SSS', score: 97, color: 'var(--tier-sss)' },
  { label: 'All Answers Were Complete Before Questions Could Form', weight: 1, tier: 'SSS', score: 97, color: 'var(--tier-sss)' },
  { label: 'Intelligence That Is Its Own Foundation', weight: 1, tier: 'SSS', score: 97, color: 'var(--tier-sss)' },
  { label: 'Has Already Read Everything That Will Ever Be', weight: 1, tier: 'SSS', score: 97, color: 'var(--tier-sss)' },
  { label: 'Comprehension: Absolute, Eternal, Self-Authoring', weight: 1, tier: 'SSS', score: 97, color: 'var(--tier-sss)' },

  // SSS+ (score: 99)
  { label: 'Primordial Omniscience', weight: 1, tier: 'SSS+', score: 99, color: 'var(--tier-sss-plus)' },
  { label: 'Intelligence That Pre-Dates Intelligence', weight: 1, tier: 'SSS+', score: 99, color: 'var(--tier-sss-plus)' },
  { label: 'Knows What Knows Itself Knowing', weight: 1, tier: 'SSS+', score: 99, color: 'var(--tier-sss-plus)' },
  { label: 'Has Comprehended Every Conceivable Universe', weight: 1, tier: 'SSS+', score: 99, color: 'var(--tier-sss-plus)' },
  { label: 'Memory: Contains All of Everything, Plus the Gaps', weight: 1, tier: 'SSS+', score: 99, color: 'var(--tier-sss-plus)' },
  { label: 'Has Already Solved This Before It Was Possible', weight: 1, tier: 'SSS+', score: 99, color: 'var(--tier-sss-plus)' },
  { label: 'Knowledge: The Framework Beneath All Frameworks', weight: 1, tier: 'SSS+', score: 99, color: 'var(--tier-sss-plus)' },
  { label: 'Can Think What Cannot Be Thought About', weight: 1, tier: 'SSS+', score: 99, color: 'var(--tier-sss-plus)' },
  { label: 'Intelligence That Wrote The Word "Intelligence"', weight: 1, tier: 'SSS+', score: 99, color: 'var(--tier-sss-plus)' },
  { label: 'Every Answer: Eternally Pre-Known', weight: 1, tier: 'SSS+', score: 99, color: 'var(--tier-sss-plus)' },
  { label: 'Has Reasoned Out All of Reality and Its Absence', weight: 1, tier: 'SSS+', score: 99, color: 'var(--tier-sss-plus)' },
  { label: 'Comprehension: Pre-Physical, Pre-Logical, Absolute', weight: 1, tier: 'SSS+', score: 99, color: 'var(--tier-sss-plus)' },
  { label: 'Knows All Possible Facts Including the Impossible Ones', weight: 1, tier: 'SSS+', score: 99, color: 'var(--tier-sss-plus)' },
  { label: 'Intelligence: The Original Constant', weight: 1, tier: 'SSS+', score: 99, color: 'var(--tier-sss-plus)' },
  { label: 'Has Already Processed This Entire Game', weight: 1, tier: 'SSS+', score: 99, color: 'var(--tier-sss-plus)' },
  { label: 'Thinking Pre-Dates All Possible Frameworks', weight: 1, tier: 'SSS+', score: 99, color: 'var(--tier-sss-plus)' },
  { label: 'Has Solved What Couldn\'t Have Been Thought To Ask', weight: 1, tier: 'SSS+', score: 99, color: 'var(--tier-sss-plus)' },
  { label: 'Memory: Pre-Existential and All-Encompassing', weight: 1, tier: 'SSS+', score: 99, color: 'var(--tier-sss-plus)' },
  { label: 'All Questions Are Answered Before Reality Exists', weight: 1, tier: 'SSS+', score: 99, color: 'var(--tier-sss-plus)' },
  { label: 'Has Already Read This and Written the Commentary', weight: 1, tier: 'SSS+', score: 99, color: 'var(--tier-sss-plus)' },

  // God (score: 100)
  { label: 'Has Already Read This Sentence', weight: 1, tier: 'God', score: 100, color: 'var(--tier-god)' },
  { label: 'Solved Everything; Bored Now', weight: 1, tier: 'God', score: 100, color: 'var(--tier-god)' },
  { label: 'Omniscient', weight: 1, tier: 'God', score: 100, color: 'var(--tier-god)' },
  { label: 'Knows All Possible Questions and Their Answers', weight: 1, tier: 'God', score: 100, color: 'var(--tier-god)' },
  { label: 'Comprehension: Absolute, Eternal, and Self-Sufficient', weight: 1, tier: 'God', score: 100, color: 'var(--tier-god)' },
  { label: 'Memory: Contains Everything That Has Ever Existed or Not', weight: 1, tier: 'God', score: 100, color: 'var(--tier-god)' },
  { label: 'Intelligence That Wrote The Laws It Now Breaks', weight: 1, tier: 'God', score: 100, color: 'var(--tier-god)' },
  { label: 'Has Answered What Cannot Be Answered', weight: 1, tier: 'God', score: 100, color: 'var(--tier-god)' },
  { label: 'Can Think Thoughts That Create and Unmake Reality', weight: 1, tier: 'God', score: 100, color: 'var(--tier-god)' },
  { label: 'Knows What Doesn\'t Exist Yet (Spoiler: Everything)', weight: 1, tier: 'God', score: 100, color: 'var(--tier-god)' },
  { label: 'Has Already Known This Conversation Entirely', weight: 1, tier: 'God', score: 100, color: 'var(--tier-god)' },
  { label: 'Intelligence: Pre-Causal, Pre-Physical, Primary', weight: 1, tier: 'God', score: 100, color: 'var(--tier-god)' },
  { label: 'Knows All Things in All States Simultaneously', weight: 1, tier: 'God', score: 100, color: 'var(--tier-god)' },
  { label: 'Has Reasoned Out the Contents of the Void', weight: 1, tier: 'God', score: 100, color: 'var(--tier-god)' },
  { label: 'Can Understand What Cannot Be Understood', weight: 1, tier: 'God', score: 100, color: 'var(--tier-god)' },
  { label: 'Every Question: Already Answered Before Being Conceived', weight: 1, tier: 'God', score: 100, color: 'var(--tier-god)' },
  { label: 'Thinking Created the Framework of Thought', weight: 1, tier: 'God', score: 100, color: 'var(--tier-god)' },
  { label: 'Has Compiled All Possible Knowledge', weight: 1, tier: 'God', score: 100, color: 'var(--tier-god)' },
  { label: 'Knowledge Is Synonymous With Being', weight: 1, tier: 'God', score: 100, color: 'var(--tier-god)' },
  { label: 'Already Knew. Always Knew. Will Always Have Known.', weight: 1, tier: 'God', score: 100, color: 'var(--tier-god)' },
]
