import type { FlavorLabel } from './types'

export const iqLabels: FlavorLabel[] = [
  { label: 'Doors Are a Recurring Challenge',       weight: 4, tier: 'F-',   score: 2,   color: '#555'    },
  { label: 'Twice Outsmarted by a Door',            weight: 4, tier: 'F',    score: 5,   color: '#666'    },
  { label: 'Functional but Slow',                   weight: 4, tier: 'F+',   score: 8,   color: '#777'    },
  { label: 'Below-Average Street Smarts',           weight: 6, tier: 'E-',   score: 11,  color: '#6b7280' },
  { label: 'Average Intelligence',                  weight: 6, tier: 'E',    score: 14,  color: '#9ca3af' },
  { label: 'Picks Things Up Quickly',               weight: 6, tier: 'E+',   score: 17,  color: '#d1d5db' },
  { label: 'Sharp Thinker',                         weight: 8, tier: 'D-',   score: 20,  color: '#92400e' },
  { label: 'Above-Average Problem Solver',          weight: 8, tier: 'D',    score: 23,  color: '#b45309' },
  { label: 'Top of the Class',                      weight: 8, tier: 'D+',   score: 26,  color: '#d97706' },
  { label: 'Gifted Intellect',                      weight: 8, tier: 'C-',   score: 30,  color: '#1d4ed8' },
  { label: 'Genius Level',                          weight: 8, tier: 'C',    score: 34,  color: '#2563eb' },
  { label: 'Expert in Multiple Fields',             weight: 8, tier: 'C+',   score: 38,  color: '#3b82f6' },
  { label: 'Einstein-Level Mind',                   weight: 7, tier: 'B-',   score: 42,  color: '#065f46' },
  { label: 'Solved Unsolvable Problems',            weight: 7, tier: 'B',    score: 47,  color: '#059669' },
  { label: 'Comprehends What Others Cannot',        weight: 7, tier: 'B+',   score: 52,  color: '#34d399' },
  { label: 'Strategic Mastermind',                  weight: 5, tier: 'A-',   score: 57,  color: '#7c3aed' },
  { label: 'Predicts Events Before They Happen',    weight: 5, tier: 'A',    score: 62,  color: '#8b5cf6' },
  { label: 'Understands the Nature of Reality',     weight: 5, tier: 'A+',   score: 67,  color: '#a78bfa' },
  { label: 'Calculates Infinity in Realtime',       weight: 4, tier: 'S-',   score: 72,  color: '#b91c1c' },
  { label: 'Omniscient-Adjacent Reasoning',         weight: 4, tier: 'S',    score: 77,  color: '#dc2626' },
  { label: 'Perceives Alternate Timelines',         weight: 4, tier: 'S+',   score: 81,  color: '#ef4444' },
  { label: 'Thinks at the Speed of Light',          weight: 3, tier: 'SS-',  score: 85,  color: '#ea580c' },
  { label: "Knows Things That Haven't Happened Yet", weight: 3, tier: 'SS',  score: 88,  color: '#f97316' },
  { label: 'Intelligence Is a Limiter for Others',  weight: 3, tier: 'SS+',  score: 91,  color: '#fb923c' },
  { label: 'Comprehends the Unknowable',                    weight: 2, tier: 'SSS-',      score: 94,  color: '#ca8a04' },
  { label: 'The Universe Is a Homework Problem',           weight: 2, tier: 'SSS',       score: 97,  color: '#eab308' },
  { label: 'Runs Simulations of All Outcomes',             weight: 2, tier: 'SSS+',      score: 99,  color: '#fde047' },
  { label: 'Comprehends Things That Exist in No Universe', weight: 2, tier: 'Z-',        score: 101, color: '#0e7490' },
  { label: 'Understands the Rules Behind the Rules',       weight: 2, tier: 'Z',         score: 103, color: '#0891b2' },
  { label: 'Thinks in Dimensions Humans Cannot Name',      weight: 2, tier: 'Z+',        score: 105, color: '#06b6d4' },
  { label: 'Perceives All Simultaneous Realities at Once', weight: 1, tier: 'ZZ-',       score: 107, color: '#3730a3' },
  { label: 'Solves Problems That Do Not Exist Yet',        weight: 1, tier: 'ZZ',        score: 109, color: '#4f46e5' },
  { label: 'Has Modeled Every Outcome Everywhere',         weight: 1, tier: 'ZZ+',       score: 111, color: '#818cf8' },
  { label: 'Intelligence Is Now a Cosmic Constant',        weight: 1, tier: 'ZZZ-',      score: 113, color: '#9d174d' },
  { label: 'Knows the Questions Before Reality Does',      weight: 1, tier: 'ZZZ',       score: 115, color: '#be185d' },
  { label: 'Understanding Is Their Default State',         weight: 1, tier: 'ZZZ+',      score: 117, color: '#ec4899' },
  { label: 'Comprehends Divine Will Intuitively',          weight: 1, tier: 'Celestial-',score: 119, color: '#075985' },
  { label: 'Intellect That Spans All Planes of Existence', weight: 1, tier: 'Celestial', score: 121, color: '#0284c7' },
  { label: 'Even Gods Consult Them',                       weight: 1, tier: 'Celestial+',score: 123, color: '#38bdf8' },
  { label: 'Understands Things That Gods Do Not',          weight: 1, tier: 'Godly-',    score: 125, color: '#c026d3' },
  { label: 'Became the Answer',                            weight: 1, tier: 'Godly',     score: 127, color: '#e879f9' },
  { label: 'Intelligence Predates Thought Itself',           weight: 1, tier: 'Primordial', score: 130, color: '#ffffff' },
  { label: 'Solved Every Equation Before Math Was Invented', weight: 1, tier: 'Primordial+',score: 133, color: '#ccffff' },
  { label: 'Understands the Architecture Behind All Things', weight: 1, tier: 'Absolute-',  score: 137, color: '#99ffff' },
  { label: 'Thought Recognizes Itself in Them',              weight: 1, tier: 'Absolute',   score: 144, color: '#00ffff' },
]
