import type { FlavorLabel } from './types'

export const potentialLabels: FlavorLabel[] = [
  // F- (score: 2)
  { label: 'Peaked at Birth', weight: 1, tier: 'F-', score: 2, color: 'var(--tier-f-minus)' },
  { label: 'Ceiling: Already Reached', weight: 1, tier: 'F-', score: 2, color: 'var(--tier-f-minus)' },
  { label: 'Growth: Theoretical', weight: 1, tier: 'F-', score: 2, color: 'var(--tier-f-minus)' },
  { label: 'Best Days Were Prenatal', weight: 1, tier: 'F-', score: 2, color: 'var(--tier-f-minus)' },
  { label: 'Downward Trend — Long-Term', weight: 1, tier: 'F-', score: 2, color: 'var(--tier-f-minus)' },
  { label: 'Maximum Potential Achieved: 12%', weight: 1, tier: 'F-', score: 2, color: 'var(--tier-f-minus)' },
  { label: 'Has Hit Their Limit Every Day', weight: 1, tier: 'F-', score: 2, color: 'var(--tier-f-minus)' },
  { label: 'Growth Arc: Non-Existent', weight: 1, tier: 'F-', score: 2, color: 'var(--tier-f-minus)' },
  { label: 'Training Does Nothing', weight: 1, tier: 'F-', score: 2, color: 'var(--tier-f-minus)' },
  { label: 'Destiny: Shrug Emoji', weight: 1, tier: 'F-', score: 2, color: 'var(--tier-f-minus)' },
  { label: 'Potential: Classified as "None Found"', weight: 1, tier: 'F-', score: 2, color: 'var(--tier-f-minus)' },
  { label: 'Natural-Born Plateau', weight: 1, tier: 'F-', score: 2, color: 'var(--tier-f-minus)' },
  { label: 'Coaches Gave Up By Week 2', weight: 1, tier: 'F-', score: 2, color: 'var(--tier-f-minus)' },
  { label: 'Future: Identical to Present', weight: 1, tier: 'F-', score: 2, color: 'var(--tier-f-minus)' },
  { label: 'Power Level Increasing: False', weight: 1, tier: 'F-', score: 2, color: 'var(--tier-f-minus)' },
  { label: 'Self-Improvement Books Bounce Off', weight: 1, tier: 'F-', score: 2, color: 'var(--tier-f-minus)' },
  { label: 'Refuses the Call — Every Single Time', weight: 1, tier: 'F-', score: 2, color: 'var(--tier-f-minus)' },
  { label: 'Montage: Skipped', weight: 1, tier: 'F-', score: 2, color: 'var(--tier-f-minus)' },
  { label: 'Level Up? Never Heard of It', weight: 1, tier: 'F-', score: 2, color: 'var(--tier-f-minus)' },
  { label: 'The Ceiling Is Also the Floor', weight: 1, tier: 'F-', score: 2, color: 'var(--tier-f-minus)' },

  // F (score: 5)
  { label: 'Growth Theoretically Possible', weight: 1, tier: 'F', score: 5, color: 'var(--tier-f)' },
  { label: 'Ceiling: Low but Not Nonexistent', weight: 1, tier: 'F', score: 5, color: 'var(--tier-f)' },
  { label: 'Will Level Up — Slowly and Minimally', weight: 1, tier: 'F', score: 5, color: 'var(--tier-f)' },
  { label: 'Has Potential — Critics Disagree', weight: 1, tier: 'F', score: 5, color: 'var(--tier-f)' },
  { label: 'Training Produces Negligible Gains', weight: 1, tier: 'F', score: 5, color: 'var(--tier-f)' },
  { label: 'Best Described as "Flatline With Bumps"', weight: 1, tier: 'F', score: 5, color: 'var(--tier-f)' },
  { label: 'Once Improved by 2% — Celebrated', weight: 1, tier: 'F', score: 5, color: 'var(--tier-f)' },
  { label: 'Not Without Potential — Just Without Much', weight: 1, tier: 'F', score: 5, color: 'var(--tier-f)' },
  { label: 'Growth Arc: Gradual Crawl', weight: 1, tier: 'F', score: 5, color: 'var(--tier-f)' },
  { label: 'Limited Headroom', weight: 1, tier: 'F', score: 5, color: 'var(--tier-f)' },
  { label: 'Destiny: Modest', weight: 1, tier: 'F', score: 5, color: 'var(--tier-f)' },
  { label: 'Coaches Cautiously Optimistic', weight: 1, tier: 'F', score: 5, color: 'var(--tier-f)' },
  { label: 'Small Room at the Top', weight: 1, tier: 'F', score: 5, color: 'var(--tier-f)' },
  { label: 'Slow Grower, Modest Bloomer', weight: 1, tier: 'F', score: 5, color: 'var(--tier-f)' },
  { label: 'Potential Reads: "Technically Positive"', weight: 1, tier: 'F', score: 5, color: 'var(--tier-f)' },
  { label: 'Has Progress — It\'s Just Small', weight: 1, tier: 'F', score: 5, color: 'var(--tier-f)' },
  { label: 'Future Looks Like Present, Slightly Shuffled', weight: 1, tier: 'F', score: 5, color: 'var(--tier-f)' },
  { label: 'Mild Upside', weight: 1, tier: 'F', score: 5, color: 'var(--tier-f)' },
  { label: 'Hard Work Has Modest Returns', weight: 1, tier: 'F', score: 5, color: 'var(--tier-f)' },
  { label: 'Would Be Inspiring in a Very Specific Context', weight: 1, tier: 'F', score: 5, color: 'var(--tier-f)' },

  // F+ (score: 8)
  { label: 'Definite Upside', weight: 1, tier: 'F+', score: 8, color: 'var(--tier-f-plus)' },
  { label: 'Solid Growth with Consistent Effort', weight: 1, tier: 'F+', score: 8, color: 'var(--tier-f-plus)' },
  { label: 'Above-Average Growth Trajectory', weight: 1, tier: 'F+', score: 8, color: 'var(--tier-f-plus)' },
  { label: 'Will Become Notable if They Try', weight: 1, tier: 'F+', score: 8, color: 'var(--tier-f-plus)' },
  { label: 'Ceiling: Respectable', weight: 1, tier: 'F+', score: 8, color: 'var(--tier-f-plus)' },
  { label: 'Late Bloomer Tendencies', weight: 1, tier: 'F+', score: 8, color: 'var(--tier-f-plus)' },
  { label: 'Growing at a Notable Clip', weight: 1, tier: 'F+', score: 8, color: 'var(--tier-f-plus)' },
  { label: 'Has Room to Grow and Uses It', weight: 1, tier: 'F+', score: 8, color: 'var(--tier-f-plus)' },
  { label: 'Responds to Training Well', weight: 1, tier: 'F+', score: 8, color: 'var(--tier-f-plus)' },
  { label: 'Strong Fundamentals, Real Headroom', weight: 1, tier: 'F+', score: 8, color: 'var(--tier-f-plus)' },
  { label: 'Progression Visible to Naked Eye', weight: 1, tier: 'F+', score: 8, color: 'var(--tier-f-plus)' },
  { label: 'Power Curve Pointing Up', weight: 1, tier: 'F+', score: 8, color: 'var(--tier-f-plus)' },
  { label: 'Mentors Actually Interested', weight: 1, tier: 'F+', score: 8, color: 'var(--tier-f-plus)' },
  { label: 'Developing Noticeably', weight: 1, tier: 'F+', score: 8, color: 'var(--tier-f-plus)' },
  { label: 'Improving Season After Season', weight: 1, tier: 'F+', score: 8, color: 'var(--tier-f-plus)' },
  { label: 'Better Than Yesterday, Reliably', weight: 1, tier: 'F+', score: 8, color: 'var(--tier-f-plus)' },
  { label: 'Rising Trend', weight: 1, tier: 'F+', score: 8, color: 'var(--tier-f-plus)' },
  { label: 'Growth Rate: Encouraging', weight: 1, tier: 'F+', score: 8, color: 'var(--tier-f-plus)' },
  { label: 'Invested in Their Own Improvement', weight: 1, tier: 'F+', score: 8, color: 'var(--tier-f-plus)' },
  { label: 'Upward Momentum Building', weight: 1, tier: 'F+', score: 8, color: 'var(--tier-f-plus)' },

  // E- (score: 11)
  { label: 'Clear High Ceiling', weight: 1, tier: 'E-', score: 11, color: 'var(--tier-e-minus)' },
  { label: 'Recognized Talent', weight: 1, tier: 'E-', score: 11, color: 'var(--tier-e-minus)' },
  { label: 'Will Be Powerful Eventually', weight: 1, tier: 'E-', score: 11, color: 'var(--tier-e-minus)' },
  { label: 'Coaches Scrambling to Sign Them', weight: 1, tier: 'E-', score: 11, color: 'var(--tier-e-minus)' },
  { label: 'Growth Compounding Reliably', weight: 1, tier: 'E-', score: 11, color: 'var(--tier-e-minus)' },
  { label: 'Progress Per Session: Notable', weight: 1, tier: 'E-', score: 11, color: 'var(--tier-e-minus)' },
  { label: 'Power Level Rising Measurably', weight: 1, tier: 'E-', score: 11, color: 'var(--tier-e-minus)' },
  { label: 'Limitless-Adjacent', weight: 1, tier: 'E-', score: 11, color: 'var(--tier-e-minus)' },
  { label: 'Accelerating Toward Greatness', weight: 1, tier: 'E-', score: 11, color: 'var(--tier-e-minus)' },
  { label: 'Every Setback Makes Them Stronger (Literally)', weight: 1, tier: 'E-', score: 11, color: 'var(--tier-e-minus)' },
  { label: 'Destiny: Promising', weight: 1, tier: 'E-', score: 11, color: 'var(--tier-e-minus)' },
  { label: 'Gets Notably Better Each Arc', weight: 1, tier: 'E-', score: 11, color: 'var(--tier-e-minus)' },
  { label: 'Will Surpass Their Teacher — On Schedule', weight: 1, tier: 'E-', score: 11, color: 'var(--tier-e-minus)' },
  { label: 'Rivals Already Watching Nervously', weight: 1, tier: 'E-', score: 11, color: 'var(--tier-e-minus)' },
  { label: 'Pattern: Steady Gains, Accelerating', weight: 1, tier: 'E-', score: 11, color: 'var(--tier-e-minus)' },
  { label: 'Consistently Outpaces Expectations', weight: 1, tier: 'E-', score: 11, color: 'var(--tier-e-minus)' },
  { label: 'Training Converts Efficiently', weight: 1, tier: 'E-', score: 11, color: 'var(--tier-e-minus)' },
  { label: 'Prodigious Development Rate', weight: 1, tier: 'E-', score: 11, color: 'var(--tier-e-minus)' },
  { label: 'Progress Arc: Steep', weight: 1, tier: 'E-', score: 11, color: 'var(--tier-e-minus)' },
  { label: 'Has Multiple Mentors Competing for Access', weight: 1, tier: 'E-', score: 11, color: 'var(--tier-e-minus)' },

  // E (score: 14)
  { label: 'Outstanding Growth Potential', weight: 1, tier: 'E', score: 14, color: 'var(--tier-e)' },
  { label: 'Power Curve: Exponential', weight: 1, tier: 'E', score: 14, color: 'var(--tier-e)' },
  { label: 'Already Better Than Where They Started by a Lot', weight: 1, tier: 'E', score: 14, color: 'var(--tier-e)' },
  { label: 'Will Likely Surpass Current Peers', weight: 1, tier: 'E', score: 14, color: 'var(--tier-e)' },
  { label: 'Talent Scouts Using the Word "Exceptional"', weight: 1, tier: 'E', score: 14, color: 'var(--tier-e)' },
  { label: 'On Track for Legacy-Level Achievement', weight: 1, tier: 'E', score: 14, color: 'var(--tier-e)' },
  { label: 'Growth Outlier — Statistically Unusual', weight: 1, tier: 'E', score: 14, color: 'var(--tier-e)' },
  { label: 'Every Session Is a New Personal Best', weight: 1, tier: 'E', score: 14, color: 'var(--tier-e)' },
  { label: 'Ceiling: Not Currently Visible', weight: 1, tier: 'E', score: 14, color: 'var(--tier-e)' },
  { label: 'Potential Recognized Across Fields', weight: 1, tier: 'E', score: 14, color: 'var(--tier-e)' },
  { label: 'Progress Is Embarrassing to Their Peers', weight: 1, tier: 'E', score: 14, color: 'var(--tier-e)' },
  { label: 'Learns From Defeat Faster Than Others Learn at All', weight: 1, tier: 'E', score: 14, color: 'var(--tier-e)' },
  { label: 'Rivals: "Please Stop Training"', weight: 1, tier: 'E', score: 14, color: 'var(--tier-e)' },
  { label: 'Progression Speed: Alarming', weight: 1, tier: 'E', score: 14, color: 'var(--tier-e)' },
  { label: 'Can\'t Train Them Enough to Contain It', weight: 1, tier: 'E', score: 14, color: 'var(--tier-e)' },
  { label: 'Development Happened Faster Than Expected', weight: 1, tier: 'E', score: 14, color: 'var(--tier-e)' },
  { label: 'Unprecedented Growth at Every Stage', weight: 1, tier: 'E', score: 14, color: 'var(--tier-e)' },
  { label: 'Will Surpass Their Teacher — Early', weight: 1, tier: 'E', score: 14, color: 'var(--tier-e)' },
  { label: 'Institutions Are Building Programs Around Them', weight: 1, tier: 'E', score: 14, color: 'var(--tier-e)' },
  { label: 'Limitless by Most Definitions', weight: 1, tier: 'E', score: 14, color: 'var(--tier-e)' },

  // E+ (score: 17)
  { label: 'Prodigy-Class Potential', weight: 1, tier: 'E+', score: 17, color: 'var(--tier-e-plus)' },
  { label: 'Growth Scares Their Instructors', weight: 1, tier: 'E+', score: 17, color: 'var(--tier-e-plus)' },
  { label: 'Will Be Historic — Timeline Uncertain', weight: 1, tier: 'E+', score: 17, color: 'var(--tier-e-plus)' },
  { label: 'Ceiling: Conceptually Hard to Identify', weight: 1, tier: 'E+', score: 17, color: 'var(--tier-e-plus)' },
  { label: 'Absorbs Power Faster Than Instructed', weight: 1, tier: 'E+', score: 17, color: 'var(--tier-e-plus)' },
  { label: 'Development Timeline: "Unnervingly Fast"', weight: 1, tier: 'E+', score: 17, color: 'var(--tier-e-plus)' },
  { label: 'Rivals Filing Emotional Support Requests', weight: 1, tier: 'E+', score: 17, color: 'var(--tier-e-plus)' },
  { label: 'Progress Outpaces Programs Designed for It', weight: 1, tier: 'E+', score: 17, color: 'var(--tier-e-plus)' },
  { label: 'Potential Curve: Near-Vertical', weight: 1, tier: 'E+', score: 17, color: 'var(--tier-e-plus)' },
  { label: 'Teacher\'s Favorite by Necessity', weight: 1, tier: 'E+', score: 17, color: 'var(--tier-e-plus)' },
  { label: 'Legend Status: If They Keep Going', weight: 1, tier: 'E+', score: 17, color: 'var(--tier-e-plus)' },
  { label: 'Breaks Training Records by Existing', weight: 1, tier: 'E+', score: 17, color: 'var(--tier-e-plus)' },
  { label: 'Gains Per Session: Off the Chart', weight: 1, tier: 'E+', score: 17, color: 'var(--tier-e-plus)' },
  { label: 'The Chosen One — According to Available Data', weight: 1, tier: 'E+', score: 17, color: 'var(--tier-e-plus)' },
  { label: 'Has Multiple Prophecies Already', weight: 1, tier: 'E+', score: 17, color: 'var(--tier-e-plus)' },
  { label: 'Destiny: Luminous', weight: 1, tier: 'E+', score: 17, color: 'var(--tier-e-plus)' },
  { label: 'Power Unlocking Faster Than Designed', weight: 1, tier: 'E+', score: 17, color: 'var(--tier-e-plus)' },
  { label: 'Everyone Around Them Is a Fan of Their Ceiling', weight: 1, tier: 'E+', score: 17, color: 'var(--tier-e-plus)' },
  { label: 'Rivals: Retired Early Due to Morale', weight: 1, tier: 'E+', score: 17, color: 'var(--tier-e-plus)' },
  { label: 'Potential That Makes Rivals Question Career Choices', weight: 1, tier: 'E+', score: 17, color: 'var(--tier-e-plus)' },

  // D- (score: 20)
  { label: 'Generational Talent', weight: 1, tier: 'D-', score: 20, color: 'var(--tier-d-minus)' },
  { label: 'Power Level Grows Without Training', weight: 1, tier: 'D-', score: 20, color: 'var(--tier-d-minus)' },
  { label: 'Ceiling: Technically Undefined', weight: 1, tier: 'D-', score: 20, color: 'var(--tier-d-minus)' },
  { label: 'Institutions Restructured Around Them', weight: 1, tier: 'D-', score: 20, color: 'var(--tier-d-minus)' },
  { label: 'One Day Will Be the Strongest in the Room — Always', weight: 1, tier: 'D-', score: 20, color: 'var(--tier-d-minus)' },
  { label: 'Legend-Class Growth Arc', weight: 1, tier: 'D-', score: 20, color: 'var(--tier-d-minus)' },
  { label: 'Naturally Transcends Technique Limits', weight: 1, tier: 'D-', score: 20, color: 'var(--tier-d-minus)' },
  { label: 'Has Surpassed Their Mentors Already', weight: 1, tier: 'D-', score: 20, color: 'var(--tier-d-minus)' },
  { label: 'Opponents Learn What "Surpassed" Means Firsthand', weight: 1, tier: 'D-', score: 20, color: 'var(--tier-d-minus)' },
  { label: 'Potential Is Now a Danger to Others', weight: 1, tier: 'D-', score: 20, color: 'var(--tier-d-minus)' },
  { label: 'Rivals: Officially Quit', weight: 1, tier: 'D-', score: 20, color: 'var(--tier-d-minus)' },
  { label: 'Can\'t Be Trained — Can Only Grow', weight: 1, tier: 'D-', score: 20, color: 'var(--tier-d-minus)' },
  { label: 'Every Setback Is an Upgrade', weight: 1, tier: 'D-', score: 20, color: 'var(--tier-d-minus)' },
  { label: 'Growth Arc: "Please Slow Down"', weight: 1, tier: 'D-', score: 20, color: 'var(--tier-d-minus)' },
  { label: 'Past Peak: Irrelevant — Too Much Left', weight: 1, tier: 'D-', score: 20, color: 'var(--tier-d-minus)' },
  { label: 'Surpasses Limits Before Others Know They Had One', weight: 1, tier: 'D-', score: 20, color: 'var(--tier-d-minus)' },
  { label: 'Potential Recognized in Other Disciplines Simultaneously', weight: 1, tier: 'D-', score: 20, color: 'var(--tier-d-minus)' },
  { label: 'Destiny: Monumental', weight: 1, tier: 'D-', score: 20, color: 'var(--tier-d-minus)' },
  { label: 'Teachers Now Describe Themselves as Witnesses', weight: 1, tier: 'D-', score: 20, color: 'var(--tier-d-minus)' },
  { label: 'Will Redefine the Standard', weight: 1, tier: 'D-', score: 20, color: 'var(--tier-d-minus)' },

  // D (score: 23)
  { label: 'Superhuman Growth Rate', weight: 1, tier: 'D', score: 23, color: 'var(--tier-d)' },
  { label: 'Power Outpaces All Training Frameworks', weight: 1, tier: 'D', score: 23, color: 'var(--tier-d)' },
  { label: 'Breaks Ceilings Passively', weight: 1, tier: 'D', score: 23, color: 'var(--tier-d)' },
  { label: 'New Limits Created Just to Watch Them Break', weight: 1, tier: 'D', score: 23, color: 'var(--tier-d)' },
  { label: 'Potential Beyond Any Known Scale', weight: 1, tier: 'D', score: 23, color: 'var(--tier-d)' },
  { label: 'Prophecies About Them Are Already Outdated', weight: 1, tier: 'D', score: 23, color: 'var(--tier-d)' },
  { label: 'The Chosen One (Category: Multiple)', weight: 1, tier: 'D', score: 23, color: 'var(--tier-d)' },
  { label: 'Institutions Have No Framework for Their Growth', weight: 1, tier: 'D', score: 23, color: 'var(--tier-d)' },
  { label: 'Defeated Their Future Self and Got Stronger', weight: 1, tier: 'D', score: 23, color: 'var(--tier-d)' },
  { label: 'Potential: Cosmic Category', weight: 1, tier: 'D', score: 23, color: 'var(--tier-d)' },
  { label: 'Ceiling Has Never Been Found — Not for Lack of Looking', weight: 1, tier: 'D', score: 23, color: 'var(--tier-d)' },
  { label: 'Progress Alerts Generated Automatically', weight: 1, tier: 'D', score: 23, color: 'var(--tier-d)' },
  { label: 'Training Creates Power Spikes Visible to Others', weight: 1, tier: 'D', score: 23, color: 'var(--tier-d)' },
  { label: 'Naturally Exceeds Their Own Limits', weight: 1, tier: 'D', score: 23, color: 'var(--tier-d)' },
  { label: 'Has More Untapped Potential Than Others Have Total', weight: 1, tier: 'D', score: 23, color: 'var(--tier-d)' },
  { label: 'Destiny: History-Altering', weight: 1, tier: 'D', score: 23, color: 'var(--tier-d)' },
  { label: 'Power Increases Detected Without Provocation', weight: 1, tier: 'D', score: 23, color: 'var(--tier-d)' },
  { label: 'Growth Is Becoming a Structural Hazard', weight: 1, tier: 'D', score: 23, color: 'var(--tier-d)' },
  { label: 'Everyone Near Them Gets Better Just Watching', weight: 1, tier: 'D', score: 23, color: 'var(--tier-d)' },
  { label: 'Documented as "The Potential Problem" by Analysts', weight: 1, tier: 'D', score: 23, color: 'var(--tier-d)' },

  // D+ (score: 26)
  { label: 'Civilization-Level Potential', weight: 1, tier: 'D+', score: 26, color: 'var(--tier-d-plus)' },
  { label: 'Peak: Not Yet — Not By Far', weight: 1, tier: 'D+', score: 26, color: 'var(--tier-d-plus)' },
  { label: 'Has Broken Records in Fields They Haven\'t Tried', weight: 1, tier: 'D+', score: 26, color: 'var(--tier-d-plus)' },
  { label: 'Potential Noted by Beings Outside This Dimension', weight: 1, tier: 'D+', score: 26, color: 'var(--tier-d-plus)' },
  { label: 'Growth Curve: Vertical and Accelerating', weight: 1, tier: 'D+', score: 26, color: 'var(--tier-d-plus)' },
  { label: 'Progression Has Changed What "Possible" Means', weight: 1, tier: 'D+', score: 26, color: 'var(--tier-d-plus)' },
  { label: 'Will Outgrow This Planet', weight: 1, tier: 'D+', score: 26, color: 'var(--tier-d-plus)' },
  { label: 'Destiny: "Could Go Either Way — Magnificently"', weight: 1, tier: 'D+', score: 26, color: 'var(--tier-d-plus)' },
  { label: 'Power Grows Overnight Without Permission', weight: 1, tier: 'D+', score: 26, color: 'var(--tier-d-plus)' },
  { label: 'All Prophecies Point at Them — Nervously', weight: 1, tier: 'D+', score: 26, color: 'var(--tier-d-plus)' },
  { label: 'Has Already Outlived the Concept of Their Ceiling', weight: 1, tier: 'D+', score: 26, color: 'var(--tier-d-plus)' },
  { label: 'Potential Alert: Systemic Concern', weight: 1, tier: 'D+', score: 26, color: 'var(--tier-d-plus)' },
  { label: 'Powers Activate in Adjacent Fields Without Prompting', weight: 1, tier: 'D+', score: 26, color: 'var(--tier-d-plus)' },
  { label: 'Has Never Reached Their Limit; Theorists Dispute if One Exists', weight: 1, tier: 'D+', score: 26, color: 'var(--tier-d-plus)' },
  { label: 'Defeats Their Stronger Self, Becomes Stronger', weight: 1, tier: 'D+', score: 26, color: 'var(--tier-d-plus)' },
  { label: 'Progressed More in a Month Than Others in Decades', weight: 1, tier: 'D+', score: 26, color: 'var(--tier-d-plus)' },
  { label: 'Will Have Disciples Before Fully Grown', weight: 1, tier: 'D+', score: 26, color: 'var(--tier-d-plus)' },
  { label: 'Power Accumulation Rate: Alarming', weight: 1, tier: 'D+', score: 26, color: 'var(--tier-d-plus)' },
  { label: 'Institutions Filed Their Potential as "Not Our Problem"', weight: 1, tier: 'D+', score: 26, color: 'var(--tier-d-plus)' },
  { label: 'Has Powers That Were Theorized Not to Exist Yet', weight: 1, tier: 'D+', score: 26, color: 'var(--tier-d-plus)' },

  // C- (score: 30)
  { label: 'Transcendent Growth Rate', weight: 1, tier: 'C-', score: 30, color: 'var(--tier-c-minus)' },
  { label: 'Cannot Be Contained by Any Training System', weight: 1, tier: 'C-', score: 30, color: 'var(--tier-c-minus)' },
  { label: 'Potential Made Other Potential Look Embarrassed', weight: 1, tier: 'C-', score: 30, color: 'var(--tier-c-minus)' },
  { label: 'Growth Arc: Rewrote the Concept', weight: 1, tier: 'C-', score: 30, color: 'var(--tier-c-minus)' },
  { label: 'Ceiling: Revised Upward Daily', weight: 1, tier: 'C-', score: 30, color: 'var(--tier-c-minus)' },
  { label: 'Has Powers From Future Training', weight: 1, tier: 'C-', score: 30, color: 'var(--tier-c-minus)' },
  { label: 'Observers Are Writing Timelines for Them', weight: 1, tier: 'C-', score: 30, color: 'var(--tier-c-minus)' },
  { label: 'Potential That Gets Its Own Story Arc', weight: 1, tier: 'C-', score: 30, color: 'var(--tier-c-minus)' },
  { label: 'Power Level Rising Continuously Without Input', weight: 1, tier: 'C-', score: 30, color: 'var(--tier-c-minus)' },
  { label: 'Can Access Abilities No One Taught Them', weight: 1, tier: 'C-', score: 30, color: 'var(--tier-c-minus)' },
  { label: 'Every Roadblock Becomes a Power Source', weight: 1, tier: 'C-', score: 30, color: 'var(--tier-c-minus)' },
  { label: 'Destiny Wrote Itself Around Their Timeline', weight: 1, tier: 'C-', score: 30, color: 'var(--tier-c-minus)' },
  { label: 'Has Already Accessed Powers Meant for Phase 3', weight: 1, tier: 'C-', score: 30, color: 'var(--tier-c-minus)' },
  { label: 'The Multiverse Sent Scouts', weight: 1, tier: 'C-', score: 30, color: 'var(--tier-c-minus)' },
  { label: 'Growth Causes Disruption in Adjacent Fields', weight: 1, tier: 'C-', score: 30, color: 'var(--tier-c-minus)' },
  { label: 'Power Level Growing Faster Than Documentation Supports', weight: 1, tier: 'C-', score: 30, color: 'var(--tier-c-minus)' },
  { label: 'Potential Is Now a Political Issue', weight: 1, tier: 'C-', score: 30, color: 'var(--tier-c-minus)' },
  { label: 'Training Is Just Practice for What They Become Naturally', weight: 1, tier: 'C-', score: 30, color: 'var(--tier-c-minus)' },
  { label: 'Ceiling: Yes, It Exists. No, They Won\'t Find It.', weight: 1, tier: 'C-', score: 30, color: 'var(--tier-c-minus)' },
  { label: 'Have Powers That Were Future-Scheduled', weight: 1, tier: 'C-', score: 30, color: 'var(--tier-c-minus)' },

  // C (score: 34)
  { label: 'World-Altering Potential', weight: 1, tier: 'C', score: 34, color: 'var(--tier-c)' },
  { label: 'Each Growth Spike Changes the Field They\'re In', weight: 1, tier: 'C', score: 34, color: 'var(--tier-c)' },
  { label: 'Power Trajectory: Off All Known Charts', weight: 1, tier: 'C', score: 34, color: 'var(--tier-c)' },
  { label: 'Growing Into Something That Doesn\'t Have a Name Yet', weight: 1, tier: 'C', score: 34, color: 'var(--tier-c)' },
  { label: 'The Ceiling Retired When They Appeared', weight: 1, tier: 'C', score: 34, color: 'var(--tier-c)' },
  { label: 'Potential Caused Structural Concerns Offworld', weight: 1, tier: 'C', score: 34, color: 'var(--tier-c)' },
  { label: 'Destiny: Civilizational', weight: 1, tier: 'C', score: 34, color: 'var(--tier-c)' },
  { label: 'Growth Is Now in Its Own Category: "Theirs"', weight: 1, tier: 'C', score: 34, color: 'var(--tier-c)' },
  { label: 'Every Growth Phase Outlasts the Predictions', weight: 1, tier: 'C', score: 34, color: 'var(--tier-c)' },
  { label: 'Has Already Become More Than the Prophecies Described', weight: 1, tier: 'C', score: 34, color: 'var(--tier-c)' },
  { label: 'Powers Keep Activating in Fields They Haven\'t Visited', weight: 1, tier: 'C', score: 34, color: 'var(--tier-c)' },
  { label: 'The Universe Is Investing in Their Upside', weight: 1, tier: 'C', score: 34, color: 'var(--tier-c)' },
  { label: 'Potential So Vast It Creates Its Own Gravity', weight: 1, tier: 'C', score: 34, color: 'var(--tier-c)' },
  { label: 'Will One Day Have No Peers — On Any Scale', weight: 1, tier: 'C', score: 34, color: 'var(--tier-c)' },
  { label: 'There Is No "Limit" in Any Available Language', weight: 1, tier: 'C', score: 34, color: 'var(--tier-c)' },
  { label: 'Growth Events Trigger Across Multiple Dimensions', weight: 1, tier: 'C', score: 34, color: 'var(--tier-c)' },
  { label: 'Powers Appear Spontaneously — Nobody Ordered Them', weight: 1, tier: 'C', score: 34, color: 'var(--tier-c)' },
  { label: 'Achieved Enlightenment — Kept Going', weight: 1, tier: 'C', score: 34, color: 'var(--tier-c)' },
  { label: 'Power Scale: Request Filed to Create a New One', weight: 1, tier: 'C', score: 34, color: 'var(--tier-c)' },
  { label: 'The Multiverse Hired Extra Analysts', weight: 1, tier: 'C', score: 34, color: 'var(--tier-c)' },

  // C+ (score: 38)
  { label: 'Cosmic-Scale Potential', weight: 1, tier: 'C+', score: 38, color: 'var(--tier-c-plus)' },
  { label: 'Growing Into a Force of Nature', weight: 1, tier: 'C+', score: 38, color: 'var(--tier-c-plus)' },
  { label: 'Transcendence: On Schedule', weight: 1, tier: 'C+', score: 38, color: 'var(--tier-c-plus)' },
  { label: 'Power Doesn\'t Need Triggers Anymore', weight: 1, tier: 'C+', score: 38, color: 'var(--tier-c-plus)' },
  { label: 'Every Previous Peak Was Just the Starting Line', weight: 1, tier: 'C+', score: 38, color: 'var(--tier-c-plus)' },
  { label: 'Potential Is a Universal Constant Now', weight: 1, tier: 'C+', score: 38, color: 'var(--tier-c-plus)' },
  { label: 'Has Already Outgrown Every Known Framework', weight: 1, tier: 'C+', score: 38, color: 'var(--tier-c-plus)' },
  { label: 'Growing Faster Than Conceptual Updates Allow', weight: 1, tier: 'C+', score: 38, color: 'var(--tier-c-plus)' },
  { label: 'Ceiling: Not Applicable', weight: 1, tier: 'C+', score: 38, color: 'var(--tier-c-plus)' },
  { label: 'Destiny: Cosmic Force', weight: 1, tier: 'C+', score: 38, color: 'var(--tier-c-plus)' },
  { label: 'Growth Caused Adjacent Realities to Shift', weight: 1, tier: 'C+', score: 38, color: 'var(--tier-c-plus)' },
  { label: 'Power Accumulation: Self-Sustaining and Accelerating', weight: 1, tier: 'C+', score: 38, color: 'var(--tier-c-plus)' },
  { label: 'Training Is No Longer the Bottleneck', weight: 1, tier: 'C+', score: 38, color: 'var(--tier-c-plus)' },
  { label: 'Breaks Growth Records That Were Named After Previous Outliers', weight: 1, tier: 'C+', score: 38, color: 'var(--tier-c-plus)' },
  { label: 'Powers Emerge Spontaneously From Growth Events', weight: 1, tier: 'C+', score: 38, color: 'var(--tier-c-plus)' },
  { label: 'Has More Unlocked Potential Than Most Have Total', weight: 1, tier: 'C+', score: 38, color: 'var(--tier-c-plus)' },
  { label: 'Potential Registered as Geopolitical Factor', weight: 1, tier: 'C+', score: 38, color: 'var(--tier-c-plus)' },
  { label: 'Multiversal Potential Watchers Assigned Exclusively', weight: 1, tier: 'C+', score: 38, color: 'var(--tier-c-plus)' },
  { label: 'Growth Continues During Sleep', weight: 1, tier: 'C+', score: 38, color: 'var(--tier-c-plus)' },
  { label: 'Becoming Something Categorically New', weight: 1, tier: 'C+', score: 38, color: 'var(--tier-c-plus)' },

  // B- (score: 42)
  { label: 'Existential-Level Potential', weight: 1, tier: 'B-', score: 42, color: 'var(--tier-b-minus)' },
  { label: 'Outgrew the Universe Once Already', weight: 1, tier: 'B-', score: 42, color: 'var(--tier-b-minus)' },
  { label: 'Potential Has Its Own Gravitational Field', weight: 1, tier: 'B-', score: 42, color: 'var(--tier-b-minus)' },
  { label: 'Every Destiny Track Points to Them', weight: 1, tier: 'B-', score: 42, color: 'var(--tier-b-minus)' },
  { label: 'Growth Disrupts Adjacent Timelines', weight: 1, tier: 'B-', score: 42, color: 'var(--tier-b-minus)' },
  { label: 'Ceiling: Undefined, Possibly Imaginary', weight: 1, tier: 'B-', score: 42, color: 'var(--tier-b-minus)' },
  { label: 'Power Increase Rate: Requiring New Mathematics', weight: 1, tier: 'B-', score: 42, color: 'var(--tier-b-minus)' },
  { label: 'All Possible Versions of Themselves Also Have This Much', weight: 1, tier: 'B-', score: 42, color: 'var(--tier-b-minus)' },
  { label: 'Growth Events Affect Local Physics', weight: 1, tier: 'B-', score: 42, color: 'var(--tier-b-minus)' },
  { label: 'Becoming Something Else Entirely — Rapidly', weight: 1, tier: 'B-', score: 42, color: 'var(--tier-b-minus)' },
  { label: 'No Version of Any Future Shows Them Capping', weight: 1, tier: 'B-', score: 42, color: 'var(--tier-b-minus)' },
  { label: 'Will Outgrow the Concept of "Having Potential"', weight: 1, tier: 'B-', score: 42, color: 'var(--tier-b-minus)' },
  { label: 'Has Powers That Are 30 Arcs Away for Everyone Else', weight: 1, tier: 'B-', score: 42, color: 'var(--tier-b-minus)' },
  { label: 'Growing at a Rate That Strains the Observer\'s Ability to Describe', weight: 1, tier: 'B-', score: 42, color: 'var(--tier-b-minus)' },
  { label: 'Potential: "Please File With Cosmic Oversight"', weight: 1, tier: 'B-', score: 42, color: 'var(--tier-b-minus)' },
  { label: 'Prophecies About Them Revised Weekly', weight: 1, tier: 'B-', score: 42, color: 'var(--tier-b-minus)' },
  { label: 'Every Growth Phase Is Larger Than All Previous', weight: 1, tier: 'B-', score: 42, color: 'var(--tier-b-minus)' },
  { label: 'Reality Is Trying to Keep Up', weight: 1, tier: 'B-', score: 42, color: 'var(--tier-b-minus)' },
  { label: 'Potential That Needs a Liability Waiver', weight: 1, tier: 'B-', score: 42, color: 'var(--tier-b-minus)' },
  { label: 'Being Near Them Makes Others Feel Their Own Limits More', weight: 1, tier: 'B-', score: 42, color: 'var(--tier-b-minus)' },

  // B (score: 47)
  { label: 'Omniversal Growth Trajectory', weight: 1, tier: 'B', score: 47, color: 'var(--tier-b)' },
  { label: 'No Scale Captures Their Ceiling', weight: 1, tier: 'B', score: 47, color: 'var(--tier-b)' },
  { label: 'Growth Causes Dimensional Instability', weight: 1, tier: 'B', score: 47, color: 'var(--tier-b)' },
  { label: 'Power Increases Between Conversations', weight: 1, tier: 'B', score: 47, color: 'var(--tier-b)' },
  { label: 'Destiny: Cosmic Scale, Open-Ended', weight: 1, tier: 'B', score: 47, color: 'var(--tier-b)' },
  { label: 'Potential That Bends Space', weight: 1, tier: 'B', score: 47, color: 'var(--tier-b)' },
  { label: 'Power Accumulating Faster Than Thermodynamics Allows', weight: 1, tier: 'B', score: 47, color: 'var(--tier-b)' },
  { label: 'Has Potential In Disciplines That Haven\'t Been Invented', weight: 1, tier: 'B', score: 47, color: 'var(--tier-b)' },
  { label: 'Ceiling: The Concept Doesn\'t Translate to Their Language', weight: 1, tier: 'B', score: 47, color: 'var(--tier-b)' },
  { label: 'Progressing Toward Something Without a Name', weight: 1, tier: 'B', score: 47, color: 'var(--tier-b)' },
  { label: 'Growth Events Cause Interference in Other Dimensions', weight: 1, tier: 'B', score: 47, color: 'var(--tier-b)' },
  { label: 'Potential Measurement Classified as "Impossible"', weight: 1, tier: 'B', score: 47, color: 'var(--tier-b)' },
  { label: 'Every Power Acquired Unlocks Four More', weight: 1, tier: 'B', score: 47, color: 'var(--tier-b)' },
  { label: 'Will Grow Past the Concept of Growth', weight: 1, tier: 'B', score: 47, color: 'var(--tier-b)' },
  { label: 'All Possible Timelines Agree: They\'re Getting Stronger', weight: 1, tier: 'B', score: 47, color: 'var(--tier-b)' },
  { label: 'Potential Has Outlived Every System Built to Contain It', weight: 1, tier: 'B', score: 47, color: 'var(--tier-b)' },
  { label: 'Becoming Something Even the Omniverse Hasn\'t Named', weight: 1, tier: 'B', score: 47, color: 'var(--tier-b)' },
  { label: 'All Growth Is Leading Somewhere Unprecedented', weight: 1, tier: 'B', score: 47, color: 'var(--tier-b)' },
  { label: 'The Concept of "Peak" Is a Personal Insult', weight: 1, tier: 'B', score: 47, color: 'var(--tier-b)' },
  { label: 'Potential Alert: Filed Under "Why Is This Happening"', weight: 1, tier: 'B', score: 47, color: 'var(--tier-b)' },

  // B+ (score: 52)
  { label: 'Multiversal Growth Event', weight: 1, tier: 'B+', score: 52, color: 'var(--tier-b-plus)' },
  { label: 'Each Growth Phase Is Bigger Than the Last Universe', weight: 1, tier: 'B+', score: 52, color: 'var(--tier-b-plus)' },
  { label: 'Potential Observed From Outside Spacetime', weight: 1, tier: 'B+', score: 52, color: 'var(--tier-b-plus)' },
  { label: 'Powers Self-Upgrade Without Instruction', weight: 1, tier: 'B+', score: 52, color: 'var(--tier-b-plus)' },
  { label: 'Destiny Revised Hourly', weight: 1, tier: 'B+', score: 52, color: 'var(--tier-b-plus)' },
  { label: 'Power Events Detectable From Other Omniverses', weight: 1, tier: 'B+', score: 52, color: 'var(--tier-b-plus)' },
  { label: 'Growing Beyond What Growth Can Describe', weight: 1, tier: 'B+', score: 52, color: 'var(--tier-b-plus)' },
  { label: 'Potential That Has No Analogue in Any Data Set', weight: 1, tier: 'B+', score: 52, color: 'var(--tier-b-plus)' },
  { label: 'Ceiling: Retired and Moved Away', weight: 1, tier: 'B+', score: 52, color: 'var(--tier-b-plus)' },
  { label: 'All Futures Agree: Something Unprecedented Is Coming', weight: 1, tier: 'B+', score: 52, color: 'var(--tier-b-plus)' },
  { label: 'Will Become the Standard That All Future Beings Fail to Meet', weight: 1, tier: 'B+', score: 52, color: 'var(--tier-b-plus)' },
  { label: 'Growing Toward a Form With No Prior Template', weight: 1, tier: 'B+', score: 52, color: 'var(--tier-b-plus)' },
  { label: 'Potential Has Exceeded the Models Used to Track It', weight: 1, tier: 'B+', score: 52, color: 'var(--tier-b-plus)' },
  { label: 'Power Acquisition: Now Continuous and Unasked For', weight: 1, tier: 'B+', score: 52, color: 'var(--tier-b-plus)' },
  { label: 'All Parallel Selves Also Headed to The Same Place', weight: 1, tier: 'B+', score: 52, color: 'var(--tier-b-plus)' },
  { label: 'Every Increment Is Still Not Their Ceiling', weight: 1, tier: 'B+', score: 52, color: 'var(--tier-b-plus)' },
  { label: 'Becoming Something That Has Never Been', weight: 1, tier: 'B+', score: 52, color: 'var(--tier-b-plus)' },
  { label: 'Growth Filed as Omniversal Anomaly', weight: 1, tier: 'B+', score: 52, color: 'var(--tier-b-plus)' },
  { label: 'Will One Day Surpass the Idea of "Above"', weight: 1, tier: 'B+', score: 52, color: 'var(--tier-b-plus)' },
  { label: 'Every New Power Is a Preview of What\'s Next', weight: 1, tier: 'B+', score: 52, color: 'var(--tier-b-plus)' },

  // A- (score: 57)
  { label: 'Pre-Universal Potential Class', weight: 1, tier: 'A-', score: 57, color: 'var(--tier-a-minus)' },
  { label: 'Potential Has Altered the Laws of Their Own Universe', weight: 1, tier: 'A-', score: 57, color: 'var(--tier-a-minus)' },
  { label: 'Growth Events Cause Recalibrations Across the Omniverse', weight: 1, tier: 'A-', score: 57, color: 'var(--tier-a-minus)' },
  { label: 'Growing Toward Something the Universe Can\'t Contain', weight: 1, tier: 'A-', score: 57, color: 'var(--tier-a-minus)' },
  { label: 'Every Power Is a Seed for More Power', weight: 1, tier: 'A-', score: 57, color: 'var(--tier-a-minus)' },
  { label: 'Will Become a Natural Force Before "Finished"', weight: 1, tier: 'A-', score: 57, color: 'var(--tier-a-minus)' },
  { label: 'All Destiny Paths End in Something Cosmic', weight: 1, tier: 'A-', score: 57, color: 'var(--tier-a-minus)' },
  { label: 'Omniversal Growth Anomaly — Still Accelerating', weight: 1, tier: 'A-', score: 57, color: 'var(--tier-a-minus)' },
  { label: 'Powers Don\'t Cap; They Evolve', weight: 1, tier: 'A-', score: 57, color: 'var(--tier-a-minus)' },
  { label: 'Becoming Something Else Entirely — Continually', weight: 1, tier: 'A-', score: 57, color: 'var(--tier-a-minus)' },
  { label: 'Potential That Made Reality File an Emergency Report', weight: 1, tier: 'A-', score: 57, color: 'var(--tier-a-minus)' },
  { label: 'Growth: Something New Every Day — None Smaller Than Yesterday', weight: 1, tier: 'A-', score: 57, color: 'var(--tier-a-minus)' },
  { label: 'All Possible Futures Led to This Trajectory', weight: 1, tier: 'A-', score: 57, color: 'var(--tier-a-minus)' },
  { label: 'Potential Has No Parallel in Any Universe or Beyond', weight: 1, tier: 'A-', score: 57, color: 'var(--tier-a-minus)' },
  { label: 'Will Outgrow the Concept of Growing', weight: 1, tier: 'A-', score: 57, color: 'var(--tier-a-minus)' },
  { label: 'Power Nodes Unlocking In Cascade', weight: 1, tier: 'A-', score: 57, color: 'var(--tier-a-minus)' },
  { label: 'Even Their Limit Has No Limit', weight: 1, tier: 'A-', score: 57, color: 'var(--tier-a-minus)' },
  { label: 'Growth Events Leave Marks on the Timeline', weight: 1, tier: 'A-', score: 57, color: 'var(--tier-a-minus)' },
  { label: 'The Omniverse Set Aside Resources for Their Growth', weight: 1, tier: 'A-', score: 57, color: 'var(--tier-a-minus)' },
  { label: 'Every Stage Is a New Class of Being', weight: 1, tier: 'A-', score: 57, color: 'var(--tier-a-minus)' },

  // A (score: 62)
  { label: 'Omniversal Potential Pinnacle', weight: 1, tier: 'A', score: 62, color: 'var(--tier-a)' },
  { label: 'Potential Visible From Other Omniverses', weight: 1, tier: 'A', score: 62, color: 'var(--tier-a)' },
  { label: 'Growing Into a Concept That Didn\'t Exist Before', weight: 1, tier: 'A', score: 62, color: 'var(--tier-a)' },
  { label: 'Has Unlocked Abilities Reserved for Post-Universe Beings', weight: 1, tier: 'A', score: 62, color: 'var(--tier-a)' },
  { label: 'Every Growth Phase Rewrites Their Own Lore', weight: 1, tier: 'A', score: 62, color: 'var(--tier-a)' },
  { label: 'Potential Is a Universal Origin Story Waiting to Happen', weight: 1, tier: 'A', score: 62, color: 'var(--tier-a)' },
  { label: 'Ceiling: No Longer Applicable in Any Dimension', weight: 1, tier: 'A', score: 62, color: 'var(--tier-a)' },
  { label: 'Destiny: "Something New — Something Without Name"', weight: 1, tier: 'A', score: 62, color: 'var(--tier-a)' },
  { label: 'Power Events Have Become Cosmological Benchmarks', weight: 1, tier: 'A', score: 62, color: 'var(--tier-a)' },
  { label: 'All Growth Spirals Upward With No Terminal Point', weight: 1, tier: 'A', score: 62, color: 'var(--tier-a)' },
  { label: 'Ascending Beyond What Ascending Means', weight: 1, tier: 'A', score: 62, color: 'var(--tier-a)' },
  { label: 'Powers Emerge Before the Need for Them Does', weight: 1, tier: 'A', score: 62, color: 'var(--tier-a)' },
  { label: 'All Futures Have Surrendered Their Outcomes to Them', weight: 1, tier: 'A', score: 62, color: 'var(--tier-a)' },
  { label: 'Potential Is Now a Force Rather Than a Trait', weight: 1, tier: 'A', score: 62, color: 'var(--tier-a)' },
  { label: 'Growing Toward the Edge of What "Possible" Means', weight: 1, tier: 'A', score: 62, color: 'var(--tier-a)' },
  { label: 'Omniversal Upward Trajectory — No Plateau Detected', weight: 1, tier: 'A', score: 62, color: 'var(--tier-a)' },
  { label: 'Becomes More Each Time They\'re Observed', weight: 1, tier: 'A', score: 62, color: 'var(--tier-a)' },
  { label: 'Growth Caused a Restructuring of Nearby Cosmologies', weight: 1, tier: 'A', score: 62, color: 'var(--tier-a)' },
  { label: 'All Possible Selves Also Boundless', weight: 1, tier: 'A', score: 62, color: 'var(--tier-a)' },
  { label: 'The Last Stage Is Not Visible Yet — Even to Them', weight: 1, tier: 'A', score: 62, color: 'var(--tier-a)' },

  // A+ (score: 67)
  { label: 'Primordial Potential Class', weight: 1, tier: 'A+', score: 67, color: 'var(--tier-a-plus)' },
  { label: 'Has Already Surpassed Beings That Don\'t Exist Yet', weight: 1, tier: 'A+', score: 67, color: 'var(--tier-a-plus)' },
  { label: 'Every Power Generates Future Powers as a Byproduct', weight: 1, tier: 'A+', score: 67, color: 'var(--tier-a-plus)' },
  { label: 'Becoming Something the Omniverse Can\'t Categorize', weight: 1, tier: 'A+', score: 67, color: 'var(--tier-a-plus)' },
  { label: 'Growth Events Alter the Pre-Universe Record', weight: 1, tier: 'A+', score: 67, color: 'var(--tier-a-plus)' },
  { label: 'Potential That Invented Its Own Measurement System', weight: 1, tier: 'A+', score: 67, color: 'var(--tier-a-plus)' },
  { label: 'No Terminal State in Any Model', weight: 1, tier: 'A+', score: 67, color: 'var(--tier-a-plus)' },
  { label: 'Surpassed Their Theoretical Maximum Last Tuesday', weight: 1, tier: 'A+', score: 67, color: 'var(--tier-a-plus)' },
  { label: 'All Possible Ceilings Have Stepped Aside', weight: 1, tier: 'A+', score: 67, color: 'var(--tier-a-plus)' },
  { label: 'Potential Cannot Be Expressed Without New Mathematics', weight: 1, tier: 'A+', score: 67, color: 'var(--tier-a-plus)' },
  { label: 'Growing Into a Category That Requires a New Cosmology to Describe', weight: 1, tier: 'A+', score: 67, color: 'var(--tier-a-plus)' },
  { label: 'Potential Measurement Filed Under "Unsolved"', weight: 1, tier: 'A+', score: 67, color: 'var(--tier-a-plus)' },
  { label: 'Destined to Rewrite What "Destiny" Means', weight: 1, tier: 'A+', score: 67, color: 'var(--tier-a-plus)' },
  { label: 'Even the Pre-Universe Has No Comparable Case', weight: 1, tier: 'A+', score: 67, color: 'var(--tier-a-plus)' },
  { label: 'Growth Arc: Started, Never Ended, Still Going', weight: 1, tier: 'A+', score: 67, color: 'var(--tier-a-plus)' },
  { label: 'Future Versions of Them Already Existed; They\'re Catching Up', weight: 1, tier: 'A+', score: 67, color: 'var(--tier-a-plus)' },
  { label: 'All Powers Are Phase 1 of Something Bigger', weight: 1, tier: 'A+', score: 67, color: 'var(--tier-a-plus)' },
  { label: 'Nothing Has Ever Capped Their Progression', weight: 1, tier: 'A+', score: 67, color: 'var(--tier-a-plus)' },
  { label: 'The Omniverse Is Growing to Keep Up With Them', weight: 1, tier: 'A+', score: 67, color: 'var(--tier-a-plus)' },
  { label: 'Potential That Redefined What "Potential" Means', weight: 1, tier: 'A+', score: 67, color: 'var(--tier-a-plus)' },

  // S- (score: 72)
  { label: 'Transcendent Potential Class', weight: 1, tier: 'S-', score: 72, color: 'var(--tier-s-minus)' },
  { label: 'Growing Beyond Time\'s Ability to Contain the Arc', weight: 1, tier: 'S-', score: 72, color: 'var(--tier-s-minus)' },
  { label: 'Has Unlocked All Previously Theoretical Abilities', weight: 1, tier: 'S-', score: 72, color: 'var(--tier-s-minus)' },
  { label: 'Ceiling: Filed Missing Persons Report', weight: 1, tier: 'S-', score: 72, color: 'var(--tier-s-minus)' },
  { label: 'Powers Precede Their Own Need', weight: 1, tier: 'S-', score: 72, color: 'var(--tier-s-minus)' },
  { label: 'Growth Is a Cosmological Constant Now', weight: 1, tier: 'S-', score: 72, color: 'var(--tier-s-minus)' },
  { label: 'Becoming Something Else Entirely — Regularly', weight: 1, tier: 'S-', score: 72, color: 'var(--tier-s-minus)' },
  { label: 'No Dimension Has a Measurement for Their Upside', weight: 1, tier: 'S-', score: 72, color: 'var(--tier-s-minus)' },
  { label: 'Every Iteration Is Stronger — Infinitely', weight: 1, tier: 'S-', score: 72, color: 'var(--tier-s-minus)' },
  { label: 'Power Events Are Now Named After Them', weight: 1, tier: 'S-', score: 72, color: 'var(--tier-s-minus)' },
  { label: 'Outgrowing "Becoming" and Moving Toward "Already"', weight: 1, tier: 'S-', score: 72, color: 'var(--tier-s-minus)' },
  { label: 'Potential Is a Structural Feature of the Omniverse Now', weight: 1, tier: 'S-', score: 72, color: 'var(--tier-s-minus)' },
  { label: 'All Futures Are Simply Later Versions of Them', weight: 1, tier: 'S-', score: 72, color: 'var(--tier-s-minus)' },
  { label: 'Growth Events Visible From Adjacent Cosmologies', weight: 1, tier: 'S-', score: 72, color: 'var(--tier-s-minus)' },
  { label: 'The Concept of "More" Was Designed for Them', weight: 1, tier: 'S-', score: 72, color: 'var(--tier-s-minus)' },
  { label: 'Powers Now Emerging That Have No Prior Basis in Reality', weight: 1, tier: 'S-', score: 72, color: 'var(--tier-s-minus)' },
  { label: 'All Possible Trajectories Lead to "Beyond"', weight: 1, tier: 'S-', score: 72, color: 'var(--tier-s-minus)' },
  { label: 'The Omniverse Has Allocated Headroom Specifically for Them', weight: 1, tier: 'S-', score: 72, color: 'var(--tier-s-minus)' },
  { label: 'Their Minimum State Is Another Being\'s Maximum', weight: 1, tier: 'S-', score: 72, color: 'var(--tier-s-minus)' },
  { label: 'The Future Is Smaller Than Their Potential', weight: 1, tier: 'S-', score: 72, color: 'var(--tier-s-minus)' },

  // S (score: 77)
  { label: 'Singular Potential — No Comparison Found', weight: 1, tier: 'S', score: 77, color: 'var(--tier-s)' },
  { label: 'Potential That Pre-Dates This Universe', weight: 1, tier: 'S', score: 77, color: 'var(--tier-s)' },
  { label: 'Every Existing Power Is Still Early Phase', weight: 1, tier: 'S', score: 77, color: 'var(--tier-s)' },
  { label: 'Growing Past What Growth Even Means', weight: 1, tier: 'S', score: 77, color: 'var(--tier-s)' },
  { label: 'All Possible Futures Are Just Early Stages', weight: 1, tier: 'S', score: 77, color: 'var(--tier-s)' },
  { label: 'Power Accumulation Is Now Continuous and Exponential', weight: 1, tier: 'S', score: 77, color: 'var(--tier-s)' },
  { label: 'Becoming Something That Will Require New Cosmologies to Describe', weight: 1, tier: 'S', score: 77, color: 'var(--tier-s)' },
  { label: 'Their Current Form Is Called "Early"', weight: 1, tier: 'S', score: 77, color: 'var(--tier-s)' },
  { label: 'Has Already Surpassed What They\'re Becoming', weight: 1, tier: 'S', score: 77, color: 'var(--tier-s)' },
  { label: 'Potential Has Destabilized Prophecy Systems', weight: 1, tier: 'S', score: 77, color: 'var(--tier-s)' },
  { label: 'All Forms Are Chrysalis Stages', weight: 1, tier: 'S', score: 77, color: 'var(--tier-s)' },
  { label: 'Growing Toward a Form That Cannot Be Named Yet', weight: 1, tier: 'S', score: 77, color: 'var(--tier-s)' },
  { label: 'Their Potential Defined "Limitless" as Insufficient', weight: 1, tier: 'S', score: 77, color: 'var(--tier-s)' },
  { label: 'Omniversal Potential Maximum: Still Provisional', weight: 1, tier: 'S', score: 77, color: 'var(--tier-s)' },
  { label: 'Every Next Phase Is Larger Than All Prior Combined', weight: 1, tier: 'S', score: 77, color: 'var(--tier-s)' },
  { label: 'Their Growth Rate Is Its Own Force of Nature', weight: 1, tier: 'S', score: 77, color: 'var(--tier-s)' },
  { label: 'The Omniverse Took Notes', weight: 1, tier: 'S', score: 77, color: 'var(--tier-s)' },
  { label: 'Power Projection: Infinite — Revision Pending', weight: 1, tier: 'S', score: 77, color: 'var(--tier-s)' },
  { label: 'Growing Into a Role That Has No Historical Precedent', weight: 1, tier: 'S', score: 77, color: 'var(--tier-s)' },
  { label: 'Absolute Potential — Still Unlocking', weight: 1, tier: 'S', score: 77, color: 'var(--tier-s)' },

  // S+ (score: 81)
  { label: 'Omniversal Apex Growth Class', weight: 1, tier: 'S+', score: 81, color: 'var(--tier-s-plus)' },
  { label: 'Their Potential Is a Primordial Force', weight: 1, tier: 'S+', score: 81, color: 'var(--tier-s-plus)' },
  { label: 'Growth Continues After Time Ends', weight: 1, tier: 'S+', score: 81, color: 'var(--tier-s-plus)' },
  { label: 'Has Powers Reserved for What Comes After Existence', weight: 1, tier: 'S+', score: 81, color: 'var(--tier-s-plus)' },
  { label: 'Potential Has No Horizon — In Any Direction', weight: 1, tier: 'S+', score: 81, color: 'var(--tier-s-plus)' },
  { label: 'Growing Beyond the Ability of Anything to Model', weight: 1, tier: 'S+', score: 81, color: 'var(--tier-s-plus)' },
  { label: 'All Previous Maximums Are Now Their Baseline', weight: 1, tier: 'S+', score: 81, color: 'var(--tier-s-plus)' },
  { label: 'Every Power They\'ve Gained Is Labeled "Phase 1"', weight: 1, tier: 'S+', score: 81, color: 'var(--tier-s-plus)' },
  { label: 'Potential That Birthed New Universal Laws', weight: 1, tier: 'S+', score: 81, color: 'var(--tier-s-plus)' },
  { label: 'The Concept of "Reaching Full Potential" Was Retired for Them', weight: 1, tier: 'S+', score: 81, color: 'var(--tier-s-plus)' },
  { label: 'Every Tier They Achieve Is a Larval Stage', weight: 1, tier: 'S+', score: 81, color: 'var(--tier-s-plus)' },
  { label: 'Omniversal Trajectory: No Terminus Identified', weight: 1, tier: 'S+', score: 81, color: 'var(--tier-s-plus)' },
  { label: 'Growth Has Its Own Observer Systems Now', weight: 1, tier: 'S+', score: 81, color: 'var(--tier-s-plus)' },
  { label: 'Powers Emerging That Have No Context Yet', weight: 1, tier: 'S+', score: 81, color: 'var(--tier-s-plus)' },
  { label: 'Will Surpass the Concept of Surpassing', weight: 1, tier: 'S+', score: 81, color: 'var(--tier-s-plus)' },
  { label: 'Every Moment They Exist Is Growth', weight: 1, tier: 'S+', score: 81, color: 'var(--tier-s-plus)' },
  { label: 'All Other Potential Is a Footnote to Theirs', weight: 1, tier: 'S+', score: 81, color: 'var(--tier-s-plus)' },
  { label: 'Potential Has Never Stopped Increasing — Ever', weight: 1, tier: 'S+', score: 81, color: 'var(--tier-s-plus)' },
  { label: 'Ceiling: Resigned. Filed Exit Interview.', weight: 1, tier: 'S+', score: 81, color: 'var(--tier-s-plus)' },
  { label: 'The Omniverse Itself Is Their Horizon', weight: 1, tier: 'S+', score: 81, color: 'var(--tier-s-plus)' },

  // SS- (score: 85)
  { label: 'Boundless by Design', weight: 1, tier: 'SS-', score: 85, color: 'var(--tier-ss-minus)' },
  { label: 'Potential Exceeds All Possible Measurement Systems', weight: 1, tier: 'SS-', score: 85, color: 'var(--tier-ss-minus)' },
  { label: 'Becoming Something Entirely Without Precedent', weight: 1, tier: 'SS-', score: 85, color: 'var(--tier-ss-minus)' },
  { label: 'Growth Is the Only Constant in Their Existence', weight: 1, tier: 'SS-', score: 85, color: 'var(--tier-ss-minus)' },
  { label: 'Their Current Peak Is Someone Else\'s Theoretical Maximum', weight: 1, tier: 'SS-', score: 85, color: 'var(--tier-ss-minus)' },
  { label: 'Potential That Caused the Omniverse to Add New Categories', weight: 1, tier: 'SS-', score: 85, color: 'var(--tier-ss-minus)' },
  { label: 'Has Powered Past All Known "Final Forms"', weight: 1, tier: 'SS-', score: 85, color: 'var(--tier-ss-minus)' },
  { label: 'No Progression System Designed Could Track Them', weight: 1, tier: 'SS-', score: 85, color: 'var(--tier-ss-minus)' },
  { label: 'Growing Past the Laws That Govern Growth', weight: 1, tier: 'SS-', score: 85, color: 'var(--tier-ss-minus)' },
  { label: 'Every Form Has Been a Trial Run', weight: 1, tier: 'SS-', score: 85, color: 'var(--tier-ss-minus)' },
  { label: 'Power Events Alter Fundamental Constants', weight: 1, tier: 'SS-', score: 85, color: 'var(--tier-ss-minus)' },
  { label: 'Potential That Is Older Than Everything But Them', weight: 1, tier: 'SS-', score: 85, color: 'var(--tier-ss-minus)' },
  { label: 'All Power Systems Are Subsets of Theirs', weight: 1, tier: 'SS-', score: 85, color: 'var(--tier-ss-minus)' },
  { label: 'Growth Arc: Still Rising From Before the Universe Existed', weight: 1, tier: 'SS-', score: 85, color: 'var(--tier-ss-minus)' },
  { label: 'Has Already Surpassed Where They\'re Going', weight: 1, tier: 'SS-', score: 85, color: 'var(--tier-ss-minus)' },
  { label: 'All Possible Growth Frameworks Deemed Insufficient', weight: 1, tier: 'SS-', score: 85, color: 'var(--tier-ss-minus)' },
  { label: 'The Concept of "Unrealized Potential" Was Retired for Them', weight: 1, tier: 'SS-', score: 85, color: 'var(--tier-ss-minus)' },
  { label: 'Powers Have Begun Pre-Unlocking for Events Not Yet Scheduled', weight: 1, tier: 'SS-', score: 85, color: 'var(--tier-ss-minus)' },
  { label: 'All Possible Beings With Potential: Less', weight: 1, tier: 'SS-', score: 85, color: 'var(--tier-ss-minus)' },
  { label: 'Becoming Something the Omniverse Has No Template For', weight: 1, tier: 'SS-', score: 85, color: 'var(--tier-ss-minus)' },

  // SS (score: 88)
  { label: 'Omniversal Maximum Potential', weight: 1, tier: 'SS', score: 88, color: 'var(--tier-ss)' },
  { label: 'Has No Final Form — Each One Becomes a New Starting Point', weight: 1, tier: 'SS', score: 88, color: 'var(--tier-ss)' },
  { label: 'Potential Runs Deeper Than Existence Goes', weight: 1, tier: 'SS', score: 88, color: 'var(--tier-ss)' },
  { label: 'Growth Does Not Slow, Stop, or Plateau — Ever', weight: 1, tier: 'SS', score: 88, color: 'var(--tier-ss)' },
  { label: 'Becoming Something Even Omniversal Entities Cannot Describe', weight: 1, tier: 'SS', score: 88, color: 'var(--tier-ss)' },
  { label: 'All Predictions About Their Ceiling Were Wrong — Always', weight: 1, tier: 'SS', score: 88, color: 'var(--tier-ss)' },
  { label: 'Their Baseline Surpasses Most Beings\' Full Potential', weight: 1, tier: 'SS', score: 88, color: 'var(--tier-ss)' },
  { label: 'Growth Continues After the Concept of Growth Ends', weight: 1, tier: 'SS', score: 88, color: 'var(--tier-ss)' },
  { label: 'All Futures Were Designed As Infrastructure for Their Rise', weight: 1, tier: 'SS', score: 88, color: 'var(--tier-ss)' },
  { label: 'Power Growth Is Self-Perpetuating Across All Planes', weight: 1, tier: 'SS', score: 88, color: 'var(--tier-ss)' },
  { label: 'Every Achieved Level Is Just the Scaffold for the Next', weight: 1, tier: 'SS', score: 88, color: 'var(--tier-ss)' },
  { label: 'The Omniverse Allocated Space for Their Trajectory', weight: 1, tier: 'SS', score: 88, color: 'var(--tier-ss)' },
  { label: 'Has Never Been "Fully Grown"', weight: 1, tier: 'SS', score: 88, color: 'var(--tier-ss)' },
  { label: 'Potential Has No Ceiling in Any Dimensional Model', weight: 1, tier: 'SS', score: 88, color: 'var(--tier-ss)' },
  { label: 'Growing Into the Answer to What the Universe Was Building To', weight: 1, tier: 'SS', score: 88, color: 'var(--tier-ss)' },
  { label: 'Has Activated Powers That Would Only Exist After Heat Death', weight: 1, tier: 'SS', score: 88, color: 'var(--tier-ss)' },
  { label: 'No Possible State Is Their Final State', weight: 1, tier: 'SS', score: 88, color: 'var(--tier-ss)' },
  { label: 'Growing Past the End of All Possible Things', weight: 1, tier: 'SS', score: 88, color: 'var(--tier-ss)' },
  { label: 'Potential That Is Itself a Universe in Formation', weight: 1, tier: 'SS', score: 88, color: 'var(--tier-ss)' },
  { label: 'Omniversal Record: Most Potential, No Ceiling Confirmed', weight: 1, tier: 'SS', score: 88, color: 'var(--tier-ss)' },

  // SS+ (score: 91)
  { label: 'Absolute Potential, Infinite Headroom', weight: 1, tier: 'SS+', score: 91, color: 'var(--tier-ss-plus)' },
  { label: 'Growing into Something That Hasn\'t Been Imagined Yet', weight: 1, tier: 'SS+', score: 91, color: 'var(--tier-ss-plus)' },
  { label: 'All Models Fail to Predict Their Next Stage', weight: 1, tier: 'SS+', score: 91, color: 'var(--tier-ss-plus)' },
  { label: 'Has Surpassed Every Prophecy on File', weight: 1, tier: 'SS+', score: 91, color: 'var(--tier-ss-plus)' },
  { label: 'Growth Is Now Counted in Cosmological Epochs', weight: 1, tier: 'SS+', score: 91, color: 'var(--tier-ss-plus)' },
  { label: 'Potential Is Now a Property of Their Vicinity', weight: 1, tier: 'SS+', score: 91, color: 'var(--tier-ss-plus)' },
  { label: 'Every Form Is An Early Draft', weight: 1, tier: 'SS+', score: 91, color: 'var(--tier-ss-plus)' },
  { label: 'The Omniverse Grows to Accommodate Them', weight: 1, tier: 'SS+', score: 91, color: 'var(--tier-ss-plus)' },
  { label: 'Powers Have Begun Spontaneously Inventing New Categories', weight: 1, tier: 'SS+', score: 91, color: 'var(--tier-ss-plus)' },
  { label: 'Potential That Has Never Once Declined or Capped', weight: 1, tier: 'SS+', score: 91, color: 'var(--tier-ss-plus)' },
  { label: 'All Future Beings Point Back to Their Growth as the Template', weight: 1, tier: 'SS+', score: 91, color: 'var(--tier-ss-plus)' },
  { label: 'Growth Does Not Require Time Anymore', weight: 1, tier: 'SS+', score: 91, color: 'var(--tier-ss-plus)' },
  { label: 'Potential Is the Primary Feature of Their Existence', weight: 1, tier: 'SS+', score: 91, color: 'var(--tier-ss-plus)' },
  { label: 'All Possible Growth Was Seeded by Their First Instance', weight: 1, tier: 'SS+', score: 91, color: 'var(--tier-ss-plus)' },
  { label: 'Becoming Something That Needs a New Tier System', weight: 1, tier: 'SS+', score: 91, color: 'var(--tier-ss-plus)' },
  { label: 'Omniversal Potential: Infinite. No Asterisks.', weight: 1, tier: 'SS+', score: 91, color: 'var(--tier-ss-plus)' },
  { label: 'The Concept of "Limit" Gave Up Following Them', weight: 1, tier: 'SS+', score: 91, color: 'var(--tier-ss-plus)' },
  { label: 'Has Always Been Growing — Even Before Birth', weight: 1, tier: 'SS+', score: 91, color: 'var(--tier-ss-plus)' },
  { label: 'Became Stronger Simply by Being Observed', weight: 1, tier: 'SS+', score: 91, color: 'var(--tier-ss-plus)' },
  { label: 'Every Version of Them Exceeds the Previous — Always', weight: 1, tier: 'SS+', score: 91, color: 'var(--tier-ss-plus)' },

  // SSS- (score: 94)
  { label: 'Pre-Cosmic Potential Class', weight: 1, tier: 'SSS-', score: 94, color: 'var(--tier-sss-minus)' },
  { label: 'All Power Ever Expressed Was a Warm-Up', weight: 1, tier: 'SSS-', score: 94, color: 'var(--tier-sss-minus)' },
  { label: 'Becoming Something That Invents Its Own Context', weight: 1, tier: 'SSS-', score: 94, color: 'var(--tier-sss-minus)' },
  { label: 'Growing Past the Concept of "What Comes Next"', weight: 1, tier: 'SSS-', score: 94, color: 'var(--tier-sss-minus)' },
  { label: 'Potential That Pre-Dates All Possible Ceilings', weight: 1, tier: 'SSS-', score: 94, color: 'var(--tier-sss-minus)' },
  { label: 'Powers Emerge Across All Possible Planes Simultaneously', weight: 1, tier: 'SSS-', score: 94, color: 'var(--tier-sss-minus)' },
  { label: 'Growth Has Become a Universal Organizing Principle', weight: 1, tier: 'SSS-', score: 94, color: 'var(--tier-sss-minus)' },
  { label: 'Has Unlocked Final Forms That Were Never Theorized', weight: 1, tier: 'SSS-', score: 94, color: 'var(--tier-sss-minus)' },
  { label: 'Every Ceiling They\'ve Broken Becomes the Floor', weight: 1, tier: 'SSS-', score: 94, color: 'var(--tier-sss-minus)' },
  { label: 'Potential Has Always Been Growing — Even In Reverse Time', weight: 1, tier: 'SSS-', score: 94, color: 'var(--tier-sss-minus)' },
  { label: 'Will One Day Contain All Possible Potential Within Themselves', weight: 1, tier: 'SSS-', score: 94, color: 'var(--tier-sss-minus)' },
  { label: 'Growing Toward the Final Answer to What Power Is', weight: 1, tier: 'SSS-', score: 94, color: 'var(--tier-sss-minus)' },
  { label: 'All Dimensions Report Upward Movement — No Exceptions', weight: 1, tier: 'SSS-', score: 94, color: 'var(--tier-sss-minus)' },
  { label: 'The Universe Grew Itself Around Their Potential', weight: 1, tier: 'SSS-', score: 94, color: 'var(--tier-sss-minus)' },
  { label: 'Omniversal Growth Constant — Non-Negotiable', weight: 1, tier: 'SSS-', score: 94, color: 'var(--tier-sss-minus)' },
  { label: 'Potential Extends Past the Death and Rebirth of the Omniverse', weight: 1, tier: 'SSS-', score: 94, color: 'var(--tier-sss-minus)' },
  { label: 'Has Outgrown All Possible Forms — Continues Growing', weight: 1, tier: 'SSS-', score: 94, color: 'var(--tier-sss-minus)' },
  { label: 'Everything That Exists Is a Draft of What They Will Become', weight: 1, tier: 'SSS-', score: 94, color: 'var(--tier-sss-minus)' },
  { label: 'The Ceiling Was a Visiting Entity — It Left', weight: 1, tier: 'SSS-', score: 94, color: 'var(--tier-sss-minus)' },
  { label: 'Potential That Seeded the Original Laws of Physics', weight: 1, tier: 'SSS-', score: 94, color: 'var(--tier-sss-minus)' },

  // SSS (score: 97)
  { label: 'Potential That Has No Completion Date', weight: 1, tier: 'SSS', score: 97, color: 'var(--tier-sss)' },
  { label: 'The Final Form Is Still Ahead — Infinitely', weight: 1, tier: 'SSS', score: 97, color: 'var(--tier-sss)' },
  { label: 'Growing Into the Mechanism That Powers All Things', weight: 1, tier: 'SSS', score: 97, color: 'var(--tier-sss)' },
  { label: 'Has Already Surpassed the Being They Are Becoming', weight: 1, tier: 'SSS', score: 97, color: 'var(--tier-sss)' },
  { label: 'Potential: Infinite. Growth Rate: Accelerating. Ceiling: N/A.', weight: 1, tier: 'SSS', score: 97, color: 'var(--tier-sss)' },
  { label: 'Everything Is Just the Introduction for What They Become', weight: 1, tier: 'SSS', score: 97, color: 'var(--tier-sss)' },
  { label: 'Has No True State — Only Successive Surpassings', weight: 1, tier: 'SSS', score: 97, color: 'var(--tier-sss)' },
  { label: 'The Omniverse Is Infrastructure for Their Growth', weight: 1, tier: 'SSS', score: 97, color: 'var(--tier-sss)' },
  { label: 'All Possible Power Has a Sign on It That Says "For Them"', weight: 1, tier: 'SSS', score: 97, color: 'var(--tier-sss)' },
  { label: 'Growth Is All They Do — Without Interruption — Across Infinity', weight: 1, tier: 'SSS', score: 97, color: 'var(--tier-sss)' },
  { label: 'Potential Seeded Every Law of Physics That Allows for Growth', weight: 1, tier: 'SSS', score: 97, color: 'var(--tier-sss)' },
  { label: 'Will Outgrow the Omniverse — Then Keep Going', weight: 1, tier: 'SSS', score: 97, color: 'var(--tier-sss)' },
  { label: 'Becoming Everything While Still Becoming More', weight: 1, tier: 'SSS', score: 97, color: 'var(--tier-sss)' },
  { label: 'The Concept of "Almost There" Has Never Applied', weight: 1, tier: 'SSS', score: 97, color: 'var(--tier-sss)' },
  { label: 'Every New Power Is the Smallest Power They\'ll Ever Have', weight: 1, tier: 'SSS', score: 97, color: 'var(--tier-sss)' },
  { label: 'Growth Has Become an Omniversal Foundational Law', weight: 1, tier: 'SSS', score: 97, color: 'var(--tier-sss)' },
  { label: 'Has More Unrealized Potential Now Than They Did at the Start', weight: 1, tier: 'SSS', score: 97, color: 'var(--tier-sss)' },
  { label: 'Powers From Their Future Are Already Leaking Into Their Present', weight: 1, tier: 'SSS', score: 97, color: 'var(--tier-sss)' },
  { label: 'Absolute Potential — Still Incomplete — Always', weight: 1, tier: 'SSS', score: 97, color: 'var(--tier-sss)' },
  { label: 'The Only Being Whose Trajectory Has No Destination', weight: 1, tier: 'SSS', score: 97, color: 'var(--tier-sss)' },

  // SSS+ (score: 99)
  { label: 'Limitless Potential — No Qualifier Needed', weight: 1, tier: 'SSS+', score: 99, color: 'var(--tier-sss-plus)' },
  { label: 'Potential That Defines "Becoming" as a Category', weight: 1, tier: 'SSS+', score: 99, color: 'var(--tier-sss-plus)' },
  { label: 'Growing Past What the Word "Infinite" Can Contain', weight: 1, tier: 'SSS+', score: 99, color: 'var(--tier-sss-plus)' },
  { label: 'Every Power Is a Single Brushstroke on the Final Picture', weight: 1, tier: 'SSS+', score: 99, color: 'var(--tier-sss-plus)' },
  { label: 'Omniversal Potential Cap: Unapplicable', weight: 1, tier: 'SSS+', score: 99, color: 'var(--tier-sss-plus)' },
  { label: 'Will Become What All Things Were Growing Toward', weight: 1, tier: 'SSS+', score: 99, color: 'var(--tier-sss-plus)' },
  { label: 'Their Potential Is the Universe\'s Most Important Feature', weight: 1, tier: 'SSS+', score: 99, color: 'var(--tier-sss-plus)' },
  { label: 'Potential Embedded in the Cosmological Constant', weight: 1, tier: 'SSS+', score: 99, color: 'var(--tier-sss-plus)' },
  { label: 'Has Always Been Growing; Will Always Be Growing', weight: 1, tier: 'SSS+', score: 99, color: 'var(--tier-sss-plus)' },
  { label: 'All Power Systems Are Scaffolding for Their Growth', weight: 1, tier: 'SSS+', score: 99, color: 'var(--tier-sss-plus)' },
  { label: 'Growing Into the Final Shape of Everything', weight: 1, tier: 'SSS+', score: 99, color: 'var(--tier-sss-plus)' },
  { label: 'The Universe Was Built With Their Growth in Mind', weight: 1, tier: 'SSS+', score: 99, color: 'var(--tier-sss-plus)' },
  { label: 'Has No Peak — Only Next Summits — Forever', weight: 1, tier: 'SSS+', score: 99, color: 'var(--tier-sss-plus)' },
  { label: 'Their Minimum State Is Another Being\'s Absolute Maximum', weight: 1, tier: 'SSS+', score: 99, color: 'var(--tier-sss-plus)' },
  { label: 'Potential That Preceded and Will Outlast Everything', weight: 1, tier: 'SSS+', score: 99, color: 'var(--tier-sss-plus)' },
  { label: 'Became the Reason Growth Exists as a Concept', weight: 1, tier: 'SSS+', score: 99, color: 'var(--tier-sss-plus)' },
  { label: 'Every Possible Form Is Still Just the Beginning', weight: 1, tier: 'SSS+', score: 99, color: 'var(--tier-sss-plus)' },
  { label: 'Absolute Potency — In Every Possible Sense — All At Once', weight: 1, tier: 'SSS+', score: 99, color: 'var(--tier-sss-plus)' },
  { label: 'The Pre-Universe Was Just a Draft of Their Origin', weight: 1, tier: 'SSS+', score: 99, color: 'var(--tier-sss-plus)' },
  { label: 'Every Power They\'ll Ever Have Is Already Waiting', weight: 1, tier: 'SSS+', score: 99, color: 'var(--tier-sss-plus)' },

  // God (score: 100)
  { label: 'Becoming Something Else Entirely', weight: 1, tier: 'God', score: 100, color: 'var(--tier-god)' },
  { label: 'Potential Without End, Without Limit, Without Precedent', weight: 1, tier: 'God', score: 100, color: 'var(--tier-god)' },
  { label: 'Growing Into the Origin Point of All Possibility', weight: 1, tier: 'God', score: 100, color: 'var(--tier-god)' },
  { label: 'Their Growth Arc IS the Universe\'s Main Plot', weight: 1, tier: 'God', score: 100, color: 'var(--tier-god)' },
  { label: 'All Things Are Prologue to What They Become', weight: 1, tier: 'God', score: 100, color: 'var(--tier-god)' },
  { label: 'Becoming What the Omniverse Was Designed to Produce', weight: 1, tier: 'God', score: 100, color: 'var(--tier-god)' },
  { label: 'Has No Ceiling. Has Never Had a Ceiling. Will Never Have a Ceiling.', weight: 1, tier: 'God', score: 100, color: 'var(--tier-god)' },
  { label: 'Every Atom in Existence Is Infrastructure for Their Growth', weight: 1, tier: 'God', score: 100, color: 'var(--tier-god)' },
  { label: 'The Concept of "Limit" Was Retired the Day They Were Born', weight: 1, tier: 'God', score: 100, color: 'var(--tier-god)' },
  { label: 'Absolute Potential — The Final Answer to All Growth', weight: 1, tier: 'God', score: 100, color: 'var(--tier-god)' },
  { label: 'Is Not a Being With Potential — Is Potential Itself', weight: 1, tier: 'God', score: 100, color: 'var(--tier-god)' },
  { label: 'Every Phase of Existence Was Just Setup for This', weight: 1, tier: 'God', score: 100, color: 'var(--tier-god)' },
  { label: 'Growing Into the Force That Powers All Growing', weight: 1, tier: 'God', score: 100, color: 'var(--tier-god)' },
  { label: 'Pre-Existence Was Their Origin State', weight: 1, tier: 'God', score: 100, color: 'var(--tier-god)' },
  { label: 'Their Destiny Was Too Large for Any One Universe to Contain', weight: 1, tier: 'God', score: 100, color: 'var(--tier-god)' },
  { label: 'No Stage Has Been Their Last', weight: 1, tier: 'God', score: 100, color: 'var(--tier-god)' },
  { label: 'The Universe Is Growing to Become Worthy of Them', weight: 1, tier: 'God', score: 100, color: 'var(--tier-god)' },
  { label: 'All Possible Power Points Back to Their Potential', weight: 1, tier: 'God', score: 100, color: 'var(--tier-god)' },
  { label: 'The Ceiling Is Them; They Are Below It; They Are Rising', weight: 1, tier: 'God', score: 100, color: 'var(--tier-god)' },
  { label: 'Potential Absolute — Growing Still', weight: 1, tier: 'God', score: 100, color: 'var(--tier-god)' },
]
