import type { FlavorLabel } from './types'

// Potential scale: F- = peaked in childhood, mortal mid = late bloomer,
// A range = generational prodigy, S+ = limitless ascendant trajectory,
// SS-SSS = will outgrow every limit, Cosmic+ = post-mortal growth curve,
// Infinite+ = potential beyond infinity.
export const potentialLabels: FlavorLabel[] = [
  { label: 'Peaked in Childhood',                            weight: 4, tier: 'F-',            score: 2,   color: '#2c2c2c' },
  { label: 'Plateau Reached Yesterday',                      weight: 4, tier: 'F',             score: 5,   color: '#404040' },
  { label: 'No Visible Ceiling Movement',                    weight: 4, tier: 'F+',            score: 8,   color: '#525252' },
  { label: 'Slow Grower',                                    weight: 6, tier: 'E-',            score: 11,  color: '#4b5563' },
  { label: 'Normal Trajectory',                              weight: 6, tier: 'E',             score: 14,  color: '#64748b' },
  { label: 'Steady Improvement',                             weight: 6, tier: 'E+',            score: 17,  color: '#94a3b8' },
  { label: 'Late Bloomer With Promise',                      weight: 8, tier: 'D-',            score: 20,  color: '#14532d' },
  { label: 'Quietly Climbing',                               weight: 8, tier: 'D',             score: 23,  color: '#166534' },
  { label: 'Coach Sees Something',                           weight: 8, tier: 'D+',            score: 26,  color: '#22c55e' },
  { label: 'Visibly Gifted',                                 weight: 8, tier: 'C-',            score: 30,  color: '#047857' },
  { label: 'High Ceiling',                                   weight: 9, tier: 'C',             score: 34,  color: '#059669' },
  { label: 'Promising Career Ahead',                         weight: 8, tier: 'C+',            score: 38,  color: '#10b981' },
  { label: 'Top-of-Class Trajectory',                        weight: 7, tier: 'B-',            score: 42,  color: '#115e59' },
  { label: 'Will Be Famous in This Field',                   weight: 7, tier: 'B',             score: 47,  color: '#0d9488' },
  { label: 'Peak Human Growth Curve',                        weight: 7, tier: 'B+',            score: 52,  color: '#14b8a6' },
  { label: 'Generational Prodigy',                           weight: 5, tier: 'A-',            score: 57,  color: '#155e75' },
  { label: 'Will Redefine the Field',                        weight: 5, tier: 'A',             score: 62,  color: '#0e7490' },
  { label: 'No Visible Ceiling',                             weight: 5, tier: 'A+',            score: 67,  color: '#06b6d4' },
  { label: 'Limitless Upward Trajectory',                    weight: 4, tier: 'S-',            score: 72,  color: '#0c4a6e' },
  { label: 'Will Surpass Their Teachers',                    weight: 4, tier: 'S',             score: 77,  color: '#0369a1' },
  { label: 'Doubles in Power Every Crisis',                  weight: 4, tier: 'S+',            score: 81,  color: '#0ea5e9' },
  { label: 'Outgrows Every Scale They Are Measured On',      weight: 3, tier: 'SS-',           score: 85,  color: '#1e3a8a' },
  { label: 'Ceiling Re-Calibrates Around Them',              weight: 3, tier: 'SS',            score: 88,  color: '#2563eb' },
  { label: 'Always One Tier Beneath What They Will Be',      weight: 3, tier: 'SS+',           score: 91,  color: '#3b82f6' },
  { label: 'Future Self Sends Postcards',                    weight: 2, tier: 'SSS-',          score: 94,  color: '#4338ca' },
  { label: 'Trajectory Has No Endpoint',                     weight: 2, tier: 'SSS',           score: 97,  color: '#4f46e5' },
  { label: 'Will Outgrow This Universe',                     weight: 2, tier: 'SSS+',          score: 99,  color: '#6366f1' },
  { label: 'Outgrows the Universe Within a Year',            weight: 2, tier: 'Z-',            score: 101, color: '#5b21b6' },
  { label: 'Growth Curve Penetrates Other Realities',        weight: 2, tier: 'Z',             score: 103, color: '#7c3aed' },
  { label: 'Multiverse Cannot Contain Their Future',         weight: 2, tier: 'Z+',            score: 105, color: '#8b5cf6' },
  { label: 'Trajectory Bends Reality Around Them',           weight: 1, tier: 'ZZ-',           score: 107, color: '#86198f' },
  { label: 'Growth That Outpaces Time',                      weight: 1, tier: 'ZZ',            score: 109, color: '#a21caf' },
  { label: 'Always Becoming Stronger Even Standing Still',   weight: 1, tier: 'ZZ+',           score: 111, color: '#c026d3' },
  { label: 'Power Curve Predates the Word "Limit"',          weight: 1, tier: 'ZZZ-',          score: 113, color: '#be185d' },
  { label: 'Will Outlive Every Scale of Measurement',        weight: 1, tier: 'ZZZ',           score: 115, color: '#db2777' },
  { label: 'Already Stronger Than Anything Recorded',        weight: 1, tier: 'ZZZ+',          score: 117, color: '#ec4899' },
  { label: 'Cosmic-Class Growth Trajectory',                 weight: 1, tier: 'Cosmic-',       score: 119, color: '#0e6b8a' },
  { label: 'Will Outgrow Cosmic Forces',                     weight: 1, tier: 'Cosmic',        score: 121, color: '#0891b2' },
  { label: 'Cosmic Order Recalibrates Around Their Future',  weight: 1, tier: 'Cosmic+',       score: 123, color: '#06b6d4' },
  { label: 'Has Endless Tomorrow',                           weight: 1, tier: 'Immortal-',     score: 125, color: '#d946ef' },
  { label: 'Immortal-Class Growth',                          weight: 1, tier: 'Immortal',      score: 127, color: '#ec4899' },
  { label: 'Every Era Is Their Adolescence',                 weight: 1, tier: 'Immortal+',     score: 129, color: '#f472b6' },
  { label: 'Will Surpass the Divine',                        weight: 1, tier: 'Celestial-',    score: 131, color: '#831843' },
  { label: 'Pantheons Watch Their Growth Curve',             weight: 1, tier: 'Celestial',     score: 133, color: '#9d174d' },
  { label: 'Will Eventually Outgrow Heaven',                 weight: 1, tier: 'Celestial+',    score: 135, color: '#be185d' },
  { label: 'Future Form Outranks Every God',                 weight: 1, tier: 'Godly-',        score: 137, color: '#f9a8d4' },
  { label: 'Will One Day Author the New Pantheon',           weight: 1, tier: 'Godly',         score: 139, color: '#f472b6' },
  { label: 'Their Eventual Self Predates All Divinity',      weight: 1, tier: 'Godly+',        score: 141, color: '#ec4899' },
  { label: 'Predates the Concept of Becoming',               weight: 1, tier: 'Primordial-',   score: 143, color: '#d4d4d8' },
  { label: 'Will Have Always Been Limitless',                weight: 1, tier: 'Primordial',    score: 145, color: '#e4e4e7' },
  { label: 'Authors the Idea of Growth Itself',              weight: 1, tier: 'Primordial+',   score: 147, color: '#fafafa' },
  { label: 'Absolute Trajectory',                            weight: 1, tier: 'Absolute-',     score: 149, color: '#7dd3fc' },
  { label: 'Reality Cannot Cap Them',                        weight: 1, tier: 'Absolute',      score: 151, color: '#38bdf8' },
  { label: 'Power Climbs By Their Existing',                 weight: 1, tier: 'Absolute+',     score: 153, color: '#0ea5e9' },
  { label: 'Beyond the Idea of "More"',                      weight: 1, tier: 'Transcendent-', score: 155, color: '#84cc16' },
  { label: 'Growth Transcends Itself in Them',               weight: 1, tier: 'Transcendent',  score: 157, color: '#65a30d' },
  { label: 'They Are the Direction Power Walks Toward',      weight: 1, tier: 'Transcendent+', score: 159, color: '#4d7c0f' },
  { label: 'Infinite Potential',                             weight: 1, tier: 'Infinite-',     score: 161, color: '#525252' },
  { label: 'Truly Infinite Growth Curve',                    weight: 1, tier: 'Infinite',      score: 163, color: '#262626' },
  { label: 'Beyond Infinite Potential',                      weight: 1, tier: 'Infinite+',     score: 165, color: '#000000' },
]
