import type { FlavorLabel } from './types'

export const potentialLabels: FlavorLabel[] = [
  { label: 'Has Peaked Already (It Was Low)',             weight: 1, tier: 'F-',   score: 2,   color: '#555'    },
  { label: 'Growth Ceiling: Visible',                     weight: 1, tier: 'F',    score: 5,   color: '#666'    },
  { label: 'Modest Upside',                               weight: 1, tier: 'F+',   score: 8,   color: '#777'    },
  { label: 'Could Get a Bit Better',                      weight: 1, tier: 'E-',   score: 11,  color: '#6b7280' },
  { label: 'Standard Human Ceiling',                      weight: 1, tier: 'E',    score: 14,  color: '#9ca3af' },
  { label: 'Above-Average Growth Rate',                   weight: 1, tier: 'E+',   score: 17,  color: '#d1d5db' },
  { label: 'Noticeable Improvement Capacity',             weight: 1, tier: 'D-',   score: 20,  color: '#92400e' },
  { label: 'Will Get Significantly Stronger',             weight: 1, tier: 'D',    score: 23,  color: '#b45309' },
  { label: 'High Ceiling for Their Class',                weight: 1, tier: 'D+',   score: 26,  color: '#d97706' },
  { label: 'Exceptional Growth Ahead',                    weight: 1, tier: 'C-',   score: 30,  color: '#1d4ed8' },
  { label: 'Elite Tier Achievable',                       weight: 1, tier: 'C',    score: 34,  color: '#2563eb' },
  { label: 'No Ceiling in Sight',                         weight: 1, tier: 'C+',   score: 38,  color: '#3b82f6' },
  { label: 'The Stories Will Talk About This',            weight: 1, tier: 'B-',   score: 42,  color: '#065f46' },
  { label: 'Legendary Tier Ceiling',                      weight: 1, tier: 'B',    score: 47,  color: '#059669' },
  { label: 'Could Rewrite Power Rankings',                weight: 1, tier: 'B+',   score: 52,  color: '#34d399' },
  { label: 'Era-Defining Growth',                         weight: 1, tier: 'A-',   score: 57,  color: '#7c3aed' },
  { label: 'Defies Power Progression Logic',              weight: 1, tier: 'A',    score: 62,  color: '#8b5cf6' },
  { label: 'Infinite Potential, Unverified',              weight: 1, tier: 'A+',   score: 67,  color: '#a78bfa' },
  { label: 'Power Scale Has No Box for This',             weight: 1, tier: 'S-',   score: 72,  color: '#b91c1c' },
  { label: 'Growth Attracts Universal Attention',         weight: 1, tier: 'S',    score: 77,  color: '#dc2626' },
  { label: 'Could Challenge the Greatest',                weight: 1, tier: 'S+',   score: 81,  color: '#ef4444' },
  { label: 'Reality Adjusts to Accommodate Growth',       weight: 1, tier: 'SS-',  score: 85,  color: '#ea580c' },
  { label: 'Powered by Narrative',                        weight: 1, tier: 'SS',   score: 88,  color: '#f97316' },
  { label: 'Growth Is Retroactive',                       weight: 1, tier: 'SS+',  score: 91,  color: '#fb923c' },
  { label: 'Breaks Ceilings It Has Not Reached Yet',      weight: 1, tier: 'SSS-', score: 94,  color: '#ca8a04' },
  { label: 'The Timeline Fears Their Future Self',        weight: 1, tier: 'SSS',  score: 97,  color: '#eab308' },
  { label: 'Current Power Is a Rounding Error',           weight: 1, tier: 'SSS+', score: 99,  color: '#fde047' },
  { label: 'What They Will Become Has No Name',           weight: 1, tier: 'God',  score: 100, color: '#e879f9' },
]
