// powers-absurd.ts — Absurd/comedic powers for Wheel of Fate.
// Re-exported from powers.ts. No default export.
// weight: 3 = common (3x more likely than epicPowers weight: 1)

import type { SimpleItem } from './types'

export const absurdPowers: SimpleItem[] = [
  // — Sensory & Physical Absurdities —
  { label: 'Aggressive Sneezing', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Balding', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Wet Sock Awareness', weight: 3, element: 'Water', grade: 'F' },
  { label: 'Ability to Sense Nearby Vending Machines', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Uncontrollable Finger-Gunning', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'The Ability to Make Things Slightly Damp', weight: 3, element: 'Water', grade: 'F' },
  { label: 'Immune to Paper Cuts', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Sentient Hair', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Inability to Whisper Quietly', weight: 3, element: 'Sound', grade: 'F' },
  { label: 'Sixth Sense for When Someone Is About to Sneeze', weight: 3, element: 'Psychic', grade: 'F' },
  { label: 'The Power to Turn Milk Slightly Sour', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Uncontrollable Hiccuping (Combat Viable)', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Sneezing at Inopportune Times', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'The Gift of Yawning at Crucial Moments', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Narcolepsy (Weaponized)', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Ability to Fall Asleep in Any Situation', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Inappropriate Laughter (Combat Viable)', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Pocket Dimension (Lint Only)', weight: 3, element: 'Arcane', grade: 'F' },
  { label: 'The Ability to Find Everything Except What You Need', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'The Gift of Finding Money in Old Coats', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Phantom Phone Checking', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Vibration Hallucination', weight: 3, element: 'Psychic', grade: 'F' },
  { label: 'Doorway Memory Wipe', weight: 3, element: 'Psychic', grade: 'F' },
  { label: 'The Ability to Forget Why You Opened the Fridge', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Immediate Name Amnesia', weight: 3, element: 'Psychic', grade: 'F' },
  { label: 'The Gift of Recognising Faces But Not Contexts', weight: 3, element: 'Psychic', grade: 'F' },
  { label: 'Recall Failure (Embarrassingly Specific)', weight: 3, element: 'Psychic', grade: 'F' },

  // — Social Skills (Lethal) —
  { label: 'Catastrophic Punctuality', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Aggressive Jaywalking', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Can Always Find Parking', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Compulsive Grocery Store Aisle Blocking', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Aisle Obstruction Field', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Pavement Blocking Formation', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'The Power to Stand Exactly Where Others Need to Go', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Queue Personhood', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Threshold Loitering', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Photobombing', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Uninvited Arrival', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Crashing Events (Expertly)', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Flaking Mastery', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'The Gift of Arriving Just After the Moment Passes', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Perpetual Tardiness Aura', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Oblivious Confidence', weight: 3, element: 'Neutral', grade: 'F' },

  // — Passive Aggression & The Look —
  { label: 'Dramatic Eye Roll (Weapon Grade)', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Disapproving Glance (Area of Effect)', weight: 3, element: 'Psychic', grade: 'F' },
  { label: 'The Look', weight: 3, element: 'Psychic', grade: 'F' },
  { label: 'Unimpressed Stare', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Raised Eyebrow (Devastating)', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'The Withering Comment', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Weaponized Disappointment', weight: 3, element: 'Psychic', grade: 'F' },
  { label: 'Guilt Trip Masterclass', weight: 3, element: 'Psychic', grade: 'F' },
  { label: 'The Silent Treatment (Nuclear Option)', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Ability to Make Anyone Feel Bad for Not Calling', weight: 3, element: 'Psychic', grade: 'F' },
  { label: 'Passive Aggressive Silence', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'The Power of an Audible Sigh', weight: 3, element: 'Sound', grade: 'F' },
  { label: 'Exasperated Exhale', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Polite Seething', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'The Gift of Saying "Fine" When Not Fine', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Passive-Aggressive Post-It Note Generation', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Compulsive Unsolicited Advice', weight: 3, element: 'Neutral', grade: 'F' },

  // — Dubious Expertise —
  { label: 'Always Knows the Correct Wine Pairing', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'The Gift of Extremely Specific Trivia', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Retroactive Wisdom', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Hindsight Embodiment', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Confident Incorrectness', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'The Power to Mispronounce Words Convincingly', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Mansplaining Mastery', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Hot Takes (Room Temperature)', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Thought Leadership Aura', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Immunity to Spoilers', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Unerring Tupperware Lid Matching', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Ability to Fold a Fitted Sheet Perfectly', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Power to Communicate Only in Riddles', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'The Gift of Extremely Accurate Vibes', weight: 3, element: 'Psychic', grade: 'F' },
  { label: 'Auditory Pizza Summoning', weight: 3, element: 'Sound', grade: 'F' },

  // — Emotional & Mental Superpowers —
  { label: 'Analysis Paralysis (Weaponized)', weight: 3, element: 'Psychic', grade: 'F' },
  { label: 'Overthinking Mastery', weight: 3, element: 'Psychic', grade: 'F' },
  { label: 'Catastrophizing', weight: 3, element: 'Psychic', grade: 'F' },
  { label: 'Paranoia (Minor But Persistent)', weight: 3, element: 'Psychic', grade: 'F' },
  { label: 'Doom Scrolling Mastery', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Midnight Mortification Generation', weight: 3, element: 'Psychic', grade: 'F' },
  { label: 'The Power to Remember Every Mistake at 3am', weight: 3, element: 'Psychic', grade: 'F' },
  { label: '3am Thought Projection', weight: 3, element: 'Psychic', grade: 'F' },
  { label: 'Tired but Wired State', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Cringe Storage', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Selective Memory Mastery', weight: 3, element: 'Psychic', grade: 'F' },
  { label: 'Pre-Emptive Regret', weight: 3, element: 'Psychic', grade: 'F' },
  { label: 'Chronic Over-Apologizing Given Physical Form', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Tangent Mastery', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Foot in Mouth Projection', weight: 3, element: 'Neutral', grade: 'F' },

  // — Cinematic & Narrative Awareness —
  { label: 'Spontaneous Jazz Hands', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Spontaneous Air Guitar', weight: 3, element: 'Sound', grade: 'F' },
  { label: 'Dramatic Cape Billowing (No Wind Required)', weight: 3, element: 'Wind', grade: 'F' },
  { label: 'Hair Flip Mastery', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'The Power to Look Good Running Away', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Photogenic Battle Stance', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Cinematic Slow Motion (Self)', weight: 3, element: 'Time', grade: 'F' },
  { label: 'Background Music Awareness', weight: 3, element: 'Sound', grade: 'F' },
  { label: 'The Ability to Monologue Without Losing the Fight', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Villain Laugh (Infectious)', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Heroic Pose Generation', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Dramatic Lighting Attraction', weight: 3, element: 'Light', grade: 'F' },
  { label: 'Foreshadowing Sense', weight: 3, element: 'Psychic', grade: 'F' },
  { label: "Chekhov's Gun Awareness", weight: 3, element: 'Psychic', grade: 'F' },
  { label: 'Perfectly Timed Arrivals (Dramatic Only)', weight: 3, element: 'Neutral', grade: 'F' },

  // — Food & Social Chaos —
  { label: 'The Power to Eat the Last Slice', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Food Disappearance Aura', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'The Ability to Eat Off Others\' Plates', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'The Gift of Ordering for Everyone', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'One-Upping Mastery', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Humble Brag Generation', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Awkward Silence Generation', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'The Gift of Saying the Wrong Thing', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Topic Derailment', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'The Ability to Make it About Themselves', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Aggressive Normalcy', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Moving the Goalposts Mastery', weight: 3, element: 'Neutral', grade: 'F' },

  // — Digital & Social Media —
  { label: 'Left on Read Mastery', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Read Receipt Weaponization', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Digital Ghosting', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'The Power to Vague-Post', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Subtweet Mastery', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Cryptic Story Posting', weight: 3, element: 'Neutral', grade: 'F' },

  // — Bureaucracy & Admin —
  { label: 'Bureaucratic Judo', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Form-Filling Mastery', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Waiting Room Manifestation', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Hold Music Projection', weight: 3, element: 'Sound', grade: 'F' },
  { label: 'The Gift of Eternal Pending Status', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Meeting After a Meeting', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'The Power to Make Elevators Arrive Immediately', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Aggressive Eye Contact Maintenance', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'The Gift of a Quick Chat That Isn\'t', weight: 3, element: 'Neutral', grade: 'F' },

  // — Tech (Best Of) —
  { label: 'Have You Tried Turning It Off and On Again', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'The Gift of "It Works on My Machine"', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'YOLO Deploy', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Commit Message Minimalism ("Fix")', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'The Ability to Leave TODOs Forever', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Technical Debt Generation', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'The Gift of Hacks That Become Load-Bearing', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Stack Overflow Copy-Paste Mastery', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Premature Optimization', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'The Power to Ship to Production on a Friday', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'node_modules Expansion', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Dunning-Kruger Embodiment', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'The Gift of "Don\'t Touch This"', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Butterfly Effect (IT)', weight: 3, element: 'Chaos', grade: 'F' },
  { label: 'Yak Shaving Mastery', weight: 3, element: 'Neutral', grade: 'F' },

  // — Procrastination & Chaos —
  { label: 'Procrastination Weaponized', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Five More Minutes Mastery', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Snooze Button Mastery (Ninth Time)', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Almost-Done Energy', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Perpetual Beta Mode', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'The Gift of Infinite Preparation', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Bikeshedding (Weaponized)', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Side Quest Multiplication', weight: 3, element: 'Chaos', grade: 'F' },
  { label: 'Cascading Issue Manifestation', weight: 3, element: 'Chaos', grade: 'F' },
  { label: 'The Ability to Make Things Worse While Helping', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Chaos Addition', weight: 3, element: 'Chaos', grade: 'F' },
]
