import type { FlavorLabel } from './types'

// Power Mastery scale: F- = cannot use their own gift, mortal mid = trained specialist,
// A range = master-class user, S+ = peerless prodigy, SS-SSS = improvises new powers,
// Cosmic+ = post-mortal command, Infinite+ = mastery beyond limit.
export const powerMasteryLabels: FlavorLabel[] = [
  { label: 'Cannot Activate Their Own Gift',                 weight: 4, tier: 'F-',            score: 2,   color: '#4a4a4a' },
  { label: 'Misfires Constantly',                            weight: 4, tier: 'F',             score: 5,   color: '#5c5c5c' },
  { label: 'Fires on the Wrong Target',                      weight: 4, tier: 'F+',            score: 8,   color: '#6e6e6e' },
  { label: 'Learning the Basics',                            weight: 6, tier: 'E-',            score: 11,  color: '#6b7280' },
  { label: 'Reliable on a Calm Day',                         weight: 6, tier: 'E',             score: 14,  color: '#9ca3af' },
  { label: 'Decent Control',                                 weight: 6, tier: 'E+',            score: 17,  color: '#d1d5db' },
  { label: 'Solid Practitioner',                             weight: 8, tier: 'D-',            score: 20,  color: '#92400e' },
  { label: 'Confident User',                                 weight: 8, tier: 'D',             score: 23,  color: '#b45309' },
  { label: 'Trained Specialist',                             weight: 8, tier: 'D+',            score: 26,  color: '#d97706' },
  { label: 'Veteran Caster',                                 weight: 8, tier: 'C-',            score: 30,  color: '#1d4ed8' },
  { label: 'Multi-Disciplinary User',                        weight: 9, tier: 'C',             score: 34,  color: '#2563eb' },
  { label: 'Combat-Ready Specialist',                        weight: 8, tier: 'C+',            score: 38,  color: '#3b82f6' },
  { label: 'Elite User',                                     weight: 7, tier: 'B-',            score: 42,  color: '#065f46' },
  { label: 'Mastered Their Discipline',                      weight: 7, tier: 'B',             score: 47,  color: '#059669' },
  { label: 'Peak Practitioner',                              weight: 7, tier: 'B+',            score: 52,  color: '#34d399' },
  { label: 'Master-Class Wielder',                           weight: 5, tier: 'A-',            score: 57,  color: '#7c3aed' },
  { label: 'Generation-Defining Talent',                     weight: 5, tier: 'A',             score: 62,  color: '#8b5cf6' },
  { label: 'Author of Their Own Technique',                  weight: 5, tier: 'A+',            score: 67,  color: '#a78bfa' },
  { label: 'Superhuman Command',                             weight: 4, tier: 'S-',            score: 72,  color: '#b91c1c' },
  { label: 'Bends Their Power to Any Shape',                 weight: 4, tier: 'S',             score: 77,  color: '#dc2626' },
  { label: 'Improvises New Applications Mid-Fight',          weight: 4, tier: 'S+',            score: 81,  color: '#ef4444' },
  { label: 'Invents New Powers on the Fly',                  weight: 3, tier: 'SS-',           score: 85,  color: '#ea580c' },
  { label: 'Powers Behave Differently Just For Them',        weight: 3, tier: 'SS',            score: 88,  color: '#f97316' },
  { label: 'Considered the Definition of Their Power',       weight: 3, tier: 'SS+',           score: 91,  color: '#fb923c' },
  { label: 'Power Obeys Their Will Implicitly',              weight: 2, tier: 'SSS-',          score: 94,  color: '#ca8a04' },
  { label: 'Powers Defer to Their Style',                    weight: 2, tier: 'SSS',           score: 97,  color: '#eab308' },
  { label: 'Defines What Their Power Can Do',                weight: 2, tier: 'SSS+',          score: 99,  color: '#fde047' },
  { label: 'Reality Allows New Powers in Their Hands',       weight: 2, tier: 'Z-',            score: 101, color: '#be185d' },
  { label: 'Powers Across Universes Sync to Them',           weight: 2, tier: 'Z',             score: 103, color: '#db2777' },
  { label: 'Mastery Spans Every Possibility',                weight: 2, tier: 'Z+',            score: 105, color: '#ec4899' },
  { label: 'Has Mastered Powers That Do Not Exist',          weight: 1, tier: 'ZZ-',           score: 107, color: '#6d28d9' },
  { label: 'Powers Become More Themselves in Their Use',     weight: 1, tier: 'ZZ',            score: 109, color: '#7c3aed' },
  { label: 'Multiversal Master of Every Discipline',         weight: 1, tier: 'ZZ+',           score: 111, color: '#8b5cf6' },
  { label: 'Mastery That Outlives the Power',                weight: 1, tier: 'ZZZ-',          score: 113, color: '#0e7490' },
  { label: 'Their Will Is the Source Code of the Power',     weight: 1, tier: 'ZZZ',           score: 115, color: '#06b6d4' },
  { label: 'Power Defines Itself By Them',                   weight: 1, tier: 'ZZZ+',          score: 117, color: '#22d3ee' },
  { label: 'Cosmic-Class Wielder',                           weight: 1, tier: 'Cosmic-',       score: 119, color: '#0e6b8a' },
  { label: 'Cosmic Forces Take Notes',                       weight: 1, tier: 'Cosmic',        score: 121, color: '#0891b2' },
  { label: 'Reality Adjusts the Rules for Them',             weight: 1, tier: 'Cosmic+',       score: 123, color: '#06b6d4' },
  { label: 'Mastery That Refuses to Fade',                   weight: 1, tier: 'Immortal-',     score: 125, color: '#d946ef' },
  { label: 'Immortal-Class Practitioner',                    weight: 1, tier: 'Immortal',      score: 127, color: '#ec4899' },
  { label: 'Has Mastered Powers Across Forgotten Ages',      weight: 1, tier: 'Immortal+',     score: 129, color: '#f472b6' },
  { label: 'Powers Bow to Their Divine Will',                weight: 1, tier: 'Celestial-',    score: 131, color: '#831843' },
  { label: 'Even Gods Borrow Their Notes',                   weight: 1, tier: 'Celestial',     score: 133, color: '#9d174d' },
  { label: 'Pantheons Cite Them as the Source',              weight: 1, tier: 'Celestial+',    score: 135, color: '#be185d' },
  { label: 'Author of How a God Uses Their Gift',            weight: 1, tier: 'Godly-',        score: 137, color: '#f9a8d4' },
  { label: 'Has Mastered the Concept of "Power"',            weight: 1, tier: 'Godly',         score: 139, color: '#f472b6' },
  { label: 'Gods Apprentice Themselves to Them',             weight: 1, tier: 'Godly+',        score: 141, color: '#ec4899' },
  { label: 'Predates the Idea of Mastery',                   weight: 1, tier: 'Primordial-',   score: 143, color: '#d4d4d8' },
  { label: 'Authored the First Use of Any Power',            weight: 1, tier: 'Primordial',    score: 145, color: '#e4e4e7' },
  { label: 'Originator of Every Discipline',                 weight: 1, tier: 'Primordial+',   score: 147, color: '#fafafa' },
  { label: 'Absolute Mastery',                               weight: 1, tier: 'Absolute-',     score: 149, color: '#7dd3fc' },
  { label: 'Power Obeys As a Property of Their Existence',   weight: 1, tier: 'Absolute',      score: 151, color: '#38bdf8' },
  { label: 'Mastery That Wrote the First Rule',              weight: 1, tier: 'Absolute+',     score: 153, color: '#0ea5e9' },
  { label: 'Beyond the Idea of Mastery',                     weight: 1, tier: 'Transcendent-', score: 155, color: '#84cc16' },
  { label: 'Mastery Transcends Itself in Their Grip',        weight: 1, tier: 'Transcendent',  score: 157, color: '#65a30d' },
  { label: 'Wields Things Beyond the Word "Power"',          weight: 1, tier: 'Transcendent+', score: 159, color: '#4d7c0f' },
  { label: 'Infinite Mastery',                               weight: 1, tier: 'Infinite-',     score: 161, color: '#525252' },
  { label: 'Truly Infinite Command',                         weight: 1, tier: 'Infinite',      score: 163, color: '#262626' },
  { label: 'Beyond Infinite Power Mastery',                  weight: 1, tier: 'Infinite+',     score: 165, color: '#000000' },
]
