// powers-absurd.ts — Absurd/comedic powers for Wheel of Fate.
// Re-exported from powers.ts. No default export.
// weight: 3 = common (3x more likely than epicPowers weight: 1)

import type { SimpleItem } from './types'

export const absurdPowers: SimpleItem[] = [
  // — Sensory & Physical Absurdities —
  { label: 'Aggressive Sneezing', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Balding', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Wet Sock Awareness', weight: 3, element: 'Water', grade: 'F' },
  { label: 'Ability to Sense Nearby Vending Machines', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Uncontrollable Finger-Gunning', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'The Ability to Make Things Slightly Damp', weight: 3, element: 'Water', grade: 'F' },
  { label: 'Immune to Paper Cuts', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Sentient Hair', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Inability to Whisper Quietly', weight: 3, element: 'Sound', grade: 'F' },
  { label: 'Sixth Sense for When Someone Is About to Sneeze', weight: 3, element: 'Psychic', grade: 'F' },
  { label: 'The Power to Turn Milk Slightly Sour', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Uncontrollable Hiccuping (Combat Viable)', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Sneezing at Inopportune Times', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'The Gift of Yawning at Crucial Moments', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Narcolepsy (Weaponized)', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Ability to Fall Asleep in Any Situation', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Inappropriate Laughter (Combat Viable)', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Pocket Dimension (Lint Only)', weight: 3, element: 'Arcane', grade: 'F' },
  { label: 'The Ability to Find Everything Except What You Need', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'The Gift of Finding Money in Old Coats', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Phantom Phone Checking', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Vibration Hallucination', weight: 3, element: 'Psychic', grade: 'F' },
  { label: 'Doorway Memory Wipe', weight: 3, element: 'Psychic', grade: 'F' },
  { label: 'The Ability to Forget Why You Opened the Fridge', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Immediate Name Amnesia', weight: 3, element: 'Psychic', grade: 'F' },
  { label: 'The Gift of Recognising Faces But Not Contexts', weight: 3, element: 'Psychic', grade: 'F' },
  { label: 'Recall Failure (Embarrassingly Specific)', weight: 3, element: 'Psychic', grade: 'F' },

  // — Social Skills (Lethal) —
  { label: 'Catastrophic Punctuality', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Aggressive Jaywalking', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Can Always Find Parking', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Compulsive Grocery Store Aisle Blocking', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Aisle Obstruction Field', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Pavement Blocking Formation', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'The Power to Stand Exactly Where Others Need to Go', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Queue Personhood', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Threshold Loitering', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Photobombing', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Uninvited Arrival', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Crashing Events (Expertly)', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Flaking Mastery', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'The Gift of Arriving Just After the Moment Passes', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Perpetual Tardiness Aura', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Oblivious Confidence', weight: 3, element: 'Neutral', grade: 'F' },

  // — Passive Aggression & The Look —
  { label: 'Dramatic Eye Roll (Weapon Grade)', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Disapproving Glance (Area of Effect)', weight: 3, element: 'Psychic', grade: 'F' },
  { label: 'The Look', weight: 3, element: 'Psychic', grade: 'F' },
  { label: 'Unimpressed Stare', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Raised Eyebrow (Devastating)', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'The Withering Comment', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Weaponized Disappointment', weight: 3, element: 'Psychic', grade: 'F' },
  { label: 'Guilt Trip Masterclass', weight: 3, element: 'Psychic', grade: 'F' },
  { label: 'The Silent Treatment (Nuclear Option)', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Ability to Make Anyone Feel Bad for Not Calling', weight: 3, element: 'Psychic', grade: 'F' },
  { label: 'Passive Aggressive Silence', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'The Power of an Audible Sigh', weight: 3, element: 'Sound', grade: 'F' },
  { label: 'Exasperated Exhale', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Polite Seething', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'The Gift of Saying "Fine" When Not Fine', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Passive-Aggressive Post-It Note Generation', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Compulsive Unsolicited Advice', weight: 3, element: 'Neutral', grade: 'F' },

  // — Dubious Expertise —
  { label: 'Always Knows the Correct Wine Pairing', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'The Gift of Extremely Specific Trivia', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Retroactive Wisdom', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Hindsight Embodiment', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Confident Incorrectness', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'The Power to Mispronounce Words Convincingly', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Mansplaining Mastery', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Hot Takes (Room Temperature)', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Thought Leadership Aura', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Immunity to Spoilers', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Unerring Tupperware Lid Matching', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Ability to Fold a Fitted Sheet Perfectly', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Power to Communicate Only in Riddles', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'The Gift of Extremely Accurate Vibes', weight: 3, element: 'Psychic', grade: 'F' },
  { label: 'Auditory Pizza Summoning', weight: 3, element: 'Sound', grade: 'F' },

  // — Emotional & Mental Superpowers —
  { label: 'Analysis Paralysis (Weaponized)', weight: 3, element: 'Psychic', grade: 'F' },
  { label: 'Overthinking Mastery', weight: 3, element: 'Psychic', grade: 'F' },
  { label: 'Catastrophizing', weight: 3, element: 'Psychic', grade: 'F' },
  { label: 'Paranoia (Minor But Persistent)', weight: 3, element: 'Psychic', grade: 'F' },
  { label: 'Doom Scrolling Mastery', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Midnight Mortification Generation', weight: 3, element: 'Psychic', grade: 'F' },
  { label: 'The Power to Remember Every Mistake at 3am', weight: 3, element: 'Psychic', grade: 'F' },
  { label: '3am Thought Projection', weight: 3, element: 'Psychic', grade: 'F' },
  { label: 'Tired but Wired State', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Cringe Storage', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Selective Memory Mastery', weight: 3, element: 'Psychic', grade: 'F' },
  { label: 'Pre-Emptive Regret', weight: 3, element: 'Psychic', grade: 'F' },
  { label: 'Chronic Over-Apologizing Given Physical Form', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Tangent Mastery', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Foot in Mouth Projection', weight: 3, element: 'Neutral', grade: 'F' },

  // — Cinematic & Narrative Awareness —
  { label: 'Spontaneous Jazz Hands', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Spontaneous Air Guitar', weight: 3, element: 'Sound', grade: 'F' },
  { label: 'Dramatic Cape Billowing (No Wind Required)', weight: 3, element: 'Wind', grade: 'F' },
  { label: 'Hair Flip Mastery', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'The Power to Look Good Running Away', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Photogenic Battle Stance', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Cinematic Slow Motion (Self)', weight: 3, element: 'Time', grade: 'F' },
  { label: 'Background Music Awareness', weight: 3, element: 'Sound', grade: 'F' },
  { label: 'The Ability to Monologue Without Losing the Fight', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Villain Laugh (Infectious)', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Heroic Pose Generation', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Dramatic Lighting Attraction', weight: 3, element: 'Light', grade: 'F' },
  { label: 'Foreshadowing Sense', weight: 3, element: 'Psychic', grade: 'F' },
  { label: "Chekhov's Gun Awareness", weight: 3, element: 'Psychic', grade: 'F' },
  { label: 'Perfectly Timed Arrivals (Dramatic Only)', weight: 3, element: 'Neutral', grade: 'F' },

  // — Food & Social Chaos —
  { label: 'The Power to Eat the Last Slice', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Food Disappearance Aura', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'The Ability to Eat Off Others\' Plates', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'The Gift of Ordering for Everyone', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'One-Upping Mastery', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Humble Brag Generation', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Awkward Silence Generation', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'The Gift of Saying the Wrong Thing', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Topic Derailment', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'The Ability to Make it About Themselves', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Aggressive Normalcy', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Moving the Goalposts Mastery', weight: 3, element: 'Neutral', grade: 'F' },

  // — Digital & Social Media —
  { label: 'Left on Read Mastery', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Read Receipt Weaponization', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Digital Ghosting', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'The Power to Vague-Post', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Subtweet Mastery', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Cryptic Story Posting', weight: 3, element: 'Neutral', grade: 'F' },

  // — Bureaucracy & Admin —
  { label: 'Bureaucratic Judo', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Form-Filling Mastery', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Waiting Room Manifestation', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Hold Music Projection', weight: 3, element: 'Sound', grade: 'F' },
  { label: 'The Gift of Eternal Pending Status', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Meeting After a Meeting', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'The Power to Make Elevators Arrive Immediately', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Aggressive Eye Contact Maintenance', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'The Gift of a Quick Chat That Isn\'t', weight: 3, element: 'Neutral', grade: 'F' },

  // — Tech (Best Of) —
  { label: 'Have You Tried Turning It Off and On Again', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'The Gift of "It Works on My Machine"', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'YOLO Deploy', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Commit Message Minimalism ("Fix")', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'The Ability to Leave TODOs Forever', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Technical Debt Generation', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'The Gift of Hacks That Become Load-Bearing', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Stack Overflow Copy-Paste Mastery', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Premature Optimization', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'The Power to Ship to Production on a Friday', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'node_modules Expansion', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Dunning-Kruger Embodiment', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'The Gift of "Don\'t Touch This"', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Butterfly Effect (IT)', weight: 3, element: 'Chaos', grade: 'F' },
  { label: 'Yak Shaving Mastery', weight: 3, element: 'Neutral', grade: 'F' },

  // — Procrastination & Chaos —
  { label: 'Procrastination Weaponized', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Five More Minutes Mastery', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Snooze Button Mastery (Ninth Time)', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Almost-Done Energy', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Perpetual Beta Mode', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'The Gift of Infinite Preparation', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Bikeshedding (Weaponized)', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Side Quest Multiplication', weight: 3, element: 'Chaos', grade: 'F' },
  { label: 'Cascading Issue Manifestation', weight: 3, element: 'Chaos', grade: 'F' },
  { label: 'The Ability to Make Things Worse While Helping', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Chaos Addition', weight: 3, element: 'Chaos', grade: 'F' },

  // — Internet & Digital —
  { label: 'Infinite Tab Opening', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'The Power of Caps Lock', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Password Forgetting (Instant)', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Reply-All Mastery', weight: 3, element: 'Chaos', grade: 'F' },
  { label: 'Screenshot Without Cropping', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Typing While Looking Away', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Autocorrect Misfire', weight: 3, element: 'Chaos', grade: 'F' },
  { label: 'Typing "On My Way" (Still in Bed)', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'The Seen-Not-Replied', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Read Receipt Manipulation', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'LinkedIn Endorsement Spam', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Unsolicited Life Advice (Twitter DM)', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Ratio Survivorship', weight: 3, element: 'Chaos', grade: 'F' },
  { label: 'Hot Take Generation', weight: 3, element: 'Fire', grade: 'F' },
  { label: 'WiFi Dowsing', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Buffering Endurance', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'The Skip Ad Button Anticipation', weight: 3, element: 'Neutral', grade: 'F' },
  { label: '404 Acceptance', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Cookie Consent Fatigue Resistance', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Pop-Up Ad Immunity (Partial)', weight: 3, element: 'Neutral', grade: 'F' },

  // — Food & Consumption —
  { label: 'Cereal Before Milk Justification', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Pineapple on Pizza Defense', weight: 3, element: 'Fire', grade: 'F' },
  { label: 'Microwave Timing (Exact Minutes Only)', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'The Cold Pizza Enhancement', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Instant Noodle Alchemy', weight: 3, element: 'Fire', grade: 'F' },
  { label: 'Calorie-Denial Field', weight: 3, element: 'Neutral', grade: 'F' },
  { label: '"Just One More Bite" Materialization', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Drive-Through Order Corruption', weight: 3, element: 'Chaos', grade: 'F' },
  { label: 'Condiment Hoarding', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'The Last Slice Hesitation', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Coffee Dependency Channeling', weight: 3, element: 'Fire', grade: 'F' },
  { label: 'Tea Snobbery Aura', weight: 3, element: 'Water', grade: 'F' },
  { label: 'Energy Drink Addiction Manifestation', weight: 3, element: 'Lightning', grade: 'F' },
  { label: 'The Invisible Snack Drawer', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Midnight Fridge Magnetism', weight: 3, element: 'Neutral', grade: 'F' },

  // — Sleep & Laziness —
  { label: 'Gravity Amplification (Self)', weight: 3, element: 'Earth', grade: 'F' },
  { label: 'Horizontal Meditation', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Alarm Snooze Multiplication', weight: 3, element: 'Chaos', grade: 'F' },
  { label: '"Five More Minutes" Distortion', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'The Nap That Ate the Day', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Blanket Fortress Construction', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Productive Sleeping', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Dream Continuity (When Late)', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'The Heroic Lie-Down', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Couch Anchoring', weight: 3, element: 'Earth', grade: 'F' },

  // — Social Awkwardness —
  { label: 'Elevator Silence Mastery', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Wrong Name Memory Lock', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'The Premature Wave (Wrong Person)', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Staircase Comeback Generator', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'The Mumbled Introduction', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Laugh Too Early (Wrong Moment)', weight: 3, element: 'Chaos', grade: 'F' },
  { label: 'Ghost Protocol Activation', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'The Overshare Aura', weight: 3, element: 'Neutral', grade: 'F' },
  { label: '"Sorry" Overuse Field', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Unnecessary Explanation Cascade', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'The Accidental Insult (Meant as Compliment)', weight: 3, element: 'Chaos', grade: 'F' },
  { label: 'Unsolicited Opinion Burst', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'The Group Chat Read Without Response', weight: 3, element: 'Neutral', grade: 'F' },
  { label: '"We Should Hang Out" Manifestation (Never Happens)', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Forgotten Birthday Awareness (Post-Midnight)', weight: 3, element: 'Neutral', grade: 'F' },

  // — Petty Superpowers —
  { label: 'Grocery Bag One-Trip Obsession', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Right Lane Righteousness', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Parking Spot Telepathy', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Checkout Queue Curse', weight: 3, element: 'Chaos', grade: 'F' },
  { label: 'The Slow Walker Force Field', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Middle Seat Magnet', weight: 3, element: 'Earth', grade: 'F' },
  { label: 'Broken Escalator Selection', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Wrong Toilet Paper Direction Fury', weight: 3, element: 'Chaos', grade: 'F' },
  { label: 'TV Remote Misplacement', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Pen Without Ink Discovery', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Charger Cable Tangle Mastery', weight: 3, element: 'Lightning', grade: 'F' },
  { label: 'Single AirPod Falling', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'The Phantom Notification', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Low Battery Anxiety', weight: 3, element: 'Lightning', grade: 'F' },
  { label: 'Wrong Side of the Pillow Heat', weight: 3, element: 'Fire', grade: 'F' },

  // — Work & Meetings —
  { label: 'Meeting That Could Have Been an Email', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Muted on Zoom (Unaware)', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Background Chaos Projection', weight: 3, element: 'Chaos', grade: 'F' },
  { label: 'The Accidental Screen Share', weight: 3, element: 'Chaos', grade: 'F' },
  { label: 'Action Items (Never Actioned)', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Synergy Invocation', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Circle-Back Summoning', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Bandwidth Complaint', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Pivot Execution (Wrong Direction)', weight: 3, element: 'Chaos', grade: 'F' },
  { label: 'KPI Generation (Meaningless)', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'The Hallway Debrief', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Passive-Aggressive Reply-All', weight: 3, element: 'Neutral', grade: 'F' },
  { label: '"Per My Last Email" Materialization', weight: 3, element: 'Fire', grade: 'F' },
  { label: 'Out-of-Office Misconfiguration', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Deadline Amnesia Field', weight: 3, element: 'Neutral', grade: 'F' },

  // — Chaotic Neutral Powers —
  { label: 'Furniture Corner Detection (With Shins)', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Stubbed Toe Amplification', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Sock Loss (Dryer)', weight: 3, element: 'Chaos', grade: 'F' },
  { label: 'Umbrella Forgetfulness (On Rain Days)', weight: 3, element: 'Water', grade: 'F' },
  { label: 'Key Pocket Confusion', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Wallet Pocket Rotation', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'The Perpetual Unread Email', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Desktop Icon Chaos', weight: 3, element: 'Chaos', grade: 'F' },
  { label: 'Download Folder Hoarding', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Document Naming Convention Abandonment', weight: 3, element: 'Chaos', grade: 'F' },
  { label: 'Version_Final_FINAL2_USE_THIS', weight: 3, element: 'Chaos', grade: 'F' },
  { label: 'Git Commit "Fixed stuff"', weight: 3, element: 'Chaos', grade: 'F' },
  { label: 'Comment Block Archaeology', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Stack Overflow Copy-Paste (Without Reading)', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Works on My Machine Assertion', weight: 3, element: 'Neutral', grade: 'F' },

  // — Minor Elemental Chaos —
  { label: 'Spilled Drink Instinct (Wrong Direction)', weight: 3, element: 'Water', grade: 'F' },
  { label: 'Static Electricity Generation', weight: 3, element: 'Lightning', grade: 'F' },
  { label: 'Sunburn Acquisition', weight: 3, element: 'Fire', grade: 'F' },
  { label: 'Rain Radar Miscalibration', weight: 3, element: 'Water', grade: 'F' },
  { label: 'Ice Cube Tray Refill Avoidance', weight: 3, element: 'Ice', grade: 'F' },
  { label: 'Windswept Hairstyle (Against Will)', weight: 3, element: 'Wind', grade: 'F' },
  { label: 'Sand in Everything', weight: 3, element: 'Earth', grade: 'F' },
  { label: 'Fog Summoning (Car Windows)', weight: 3, element: 'Water', grade: 'F' },
  { label: 'The Eternal Sunglasses Search', weight: 3, element: 'Light', grade: 'F' },
  { label: 'Shade Avoidance (Cloudy Day)', weight: 3, element: 'Neutral', grade: 'F' },

  // — Absurd Utility Powers —
  { label: 'Shoelace Untying (Both at Once)', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Bag Rip at Maximum Capacity', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Button Popping (Critical Moment)', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'IKEA Instructions Confusion Field', weight: 3, element: 'Chaos', grade: 'F' },
  { label: 'The Stripped Screw Encounter', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Wrong Allen Key Selection', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'The Extra Screw (After Assembly)', weight: 3, element: 'Chaos', grade: 'F' },
  { label: 'Paint Drip Materialization', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Wallpaper Bubble Manifestation', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'The Crooked Picture Frame Curse', weight: 3, element: 'Neutral', grade: 'F' },

  // — Meta Absurdity —
  { label: 'Being Chosen by the Wheel', weight: 3, element: 'Chaos', grade: 'F' },
  { label: 'Rerolling Compulsion', weight: 3, element: 'Chaos', grade: 'F' },
  { label: 'Power Explanation (Takes Longer Than Fight)', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Tragic Backstory Construction', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Power Level Reading (Inaccurate)', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Transformation Sequence (Takes 5 Episodes)', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'The Pointless Training Arc', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Filler Episode Generation', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Rival Appearance (Convenient Timing)', weight: 3, element: 'Chaos', grade: 'F' },
  { label: 'Power of Friendship (Inconsistent)', weight: 3, element: 'Light', grade: 'F' },
  { label: 'The Final Form (Immediately Surpassed)', weight: 3, element: 'Chaos', grade: 'F' },
  { label: 'Villain Monologue Immunity', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Flashback Overuse', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Convenient Amnesia', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Plot Armor (Temporary)', weight: 3, element: 'Light', grade: 'F' },

  // — Random Mundane Superpowers —
  { label: 'Perfect Parallel Park (Once)', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Exact Change Production', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Lottery Ticket Non-Winning', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'The Unopenable Jar (Solved Eventually)', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Remote Clicking (Wrong Direction)', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Prescription Label Misread', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Instruction Manual Rejection', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Terms & Conditions Acceptance (Unread)', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'The Phantom Itch', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Hiccup Summoning', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Sneezing Into Elbow (Sometimes)', weight: 3, element: 'Wind', grade: 'F' },
  { label: 'Wrong Name Spelling Persistence', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'The Misplaced Apostrophe', weight: 3, element: 'Chaos', grade: 'F' },
  { label: '"Their" vs "There" Confusion', weight: 3, element: 'Chaos', grade: 'F' },
  { label: 'Air Quotes (Excessive)', weight: 3, element: 'Wind', grade: 'F' },

  // — Doomscrolling & Modern Curses —
  { label: 'Doomscrolling Endurance', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Conspiracy Rabbit Hole Entry', weight: 3, element: 'Chaos', grade: 'F' },
  { label: 'Clickbait Resistance (Low)', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Algorithm Prediction Avoidance (Failure)', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Ad Targeting Accuracy Spite', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Unsubscribe Loop Entry', weight: 3, element: 'Chaos', grade: 'F' },
  { label: 'Two-Factor Authentication Annoyance', weight: 3, element: 'Lightning', grade: 'F' },
  { label: 'Password Complexity Rejection', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'CAPTCHA Failure (Third Attempt)', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Browser History Anxiety', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Cloud Storage Full Paralysis', weight: 3, element: 'Wind', grade: 'F' },
  { label: 'App Update Deferral (Forever)', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'OS Update Snooze Mastery', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Bluetooth Pairing Ceremony', weight: 3, element: 'Lightning', grade: 'F' },
  { label: '"Unable to Connect" Acceptance', weight: 3, element: 'Neutral', grade: 'F' },

  // — Strangely Specific —
  { label: 'Wet Sock Endurance', weight: 3, element: 'Water', grade: 'F' },
  { label: 'Paper Cut Survivorship', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Popcorn Kernel Tooth Wedge', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'The Phantom Vibration', weight: 3, element: 'Lightning', grade: 'F' },
  { label: 'Earbud Tangle Physics', weight: 3, element: 'Chaos', grade: 'F' },
  { label: 'Staple Jam Induction', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Paper Jam Summoning', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Toner Low Manifestation', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'The Stuck Zipper', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Hair Tie Snap (Mid-Ponytail)', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Glasses Sliding Down Nose', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Contact Lens Fold (In Eye)', weight: 3, element: 'Water', grade: 'F' },
  { label: 'The Permanent Pen on Skin Mark', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Ink Blob on Final Draft', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Signature Looking Different Every Time', weight: 3, element: 'Chaos', grade: 'F' },

  // — Bonus Absurd Utilities —
  { label: 'The Rhetorical Question (Answered)', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Overly Detailed Story Tangent', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'The Humblebrag Activation', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Name Drop (Irrelevant)', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'One-Upper Compulsion', weight: 3, element: 'Neutral', grade: 'F' },
  { label: '"Actually" Invocation', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Devil\'s Advocate Summoning (Always)', weight: 3, element: 'Chaos', grade: 'F' },
  { label: 'Nit-Picking Aura', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Grammar Correction (Aloud)', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Fun Fact Injection (Unprompted)', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'The "Well, Technically" Shield', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Unsolicited Product Review', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Loud Chewing Manifestation', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Pen Clicking Compulsion', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Toe Tapping (In Library)', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'The Public Phone Call (Speaker Mode)', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Headphone Jack Regret', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Dongle Dependency', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'The Dying Laptop Fan Symphony', weight: 3, element: 'Wind', grade: 'F' },
  { label: 'Overheating Lap Endurance', weight: 3, element: 'Fire', grade: 'F' },
  { label: 'The Eternal Software License', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Subscription Cancellation Maze Navigation', weight: 3, element: 'Chaos', grade: 'F' },
  { label: 'Free Trial to Paid (Oops)', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Mystery Bank Charge Acceptance', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Coupon Expiry (Day Before Use)', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Loyalty Points Expiration', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Gift Card Balance ($0.73 Remaining)', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Return Window Missed by One Day', weight: 3, element: 'Chaos', grade: 'F' },
  { label: 'Warranty Expiry (Day of Failure)', weight: 3, element: 'Chaos', grade: 'F' },
  { label: 'The Helpful Error Message ("Something went wrong")', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Ctrl+Z (Life)', weight: 3, element: 'Chaos', grade: 'F' },
]
