// powers-epic.ts — Epic/serious powers for Wheel of Fate.
// Re-exported from powers.ts. No default export.

import type { SimpleItem } from './types'

export const epicPowers: SimpleItem[] = [
  { label: 'Shadow Manipulation', weight: 1 },
  { label: 'Time Reversal', weight: 1 },
  { label: 'Reality Anchor', weight: 1 },
  { label: 'Absolute Zero Aura', weight: 1 },
  { label: 'Molecular Reconstruction', weight: 1 },
  { label: 'Dimensional Rifting', weight: 1 },
  { label: 'Soul Absorption', weight: 1 },
  { label: 'Chrono Displacement', weight: 1 },
  { label: 'Gravitational Mastery', weight: 1 },
  { label: 'Elemental Convergence', weight: 1 },
  { label: 'Psychic Dominion', weight: 1 },
  { label: 'Void Walking', weight: 1 },
  { label: 'Star Forge', weight: 1 },
  { label: 'Blood Alchemy', weight: 1 },
  { label: 'Dream Invasion', weight: 1 },
  { label: 'Neural Override', weight: 1 },
  { label: 'Seismic Command', weight: 1 },
  { label: 'Spectral Form', weight: 1 },
  { label: 'Phoenix Rebirth', weight: 1 },
  { label: 'Temporal Echo', weight: 1 },
  { label: 'Celestial Binding', weight: 1 },
  { label: 'Entropy Control', weight: 1 },
  { label: 'Light Refraction', weight: 1 },
  { label: 'Bone Architecture', weight: 1 },
  { label: 'Memory Erasure', weight: 1 },
  { label: 'Sound Shaping', weight: 1 },
  { label: 'Probability Manipulation', weight: 1 },
  { label: 'Weather Dominion', weight: 1 },
  { label: 'Telekinetic Surge', weight: 1 },
  { label: 'Cosmic Awareness', weight: 1 },
  { label: 'Plasma Generation', weight: 1 },
  { label: 'Quantum Tunneling', weight: 1 },
  { label: 'Aura Reading', weight: 1 },
  { label: 'Mana Drain', weight: 1 },
  { label: 'Petrification Touch', weight: 1 },
  { label: 'Lightning Mastery', weight: 1 },
  { label: 'Healing Factor', weight: 1 },
  { label: 'Invulnerability', weight: 1 },
  { label: 'Super Strength', weight: 1 },
  { label: 'Super Speed', weight: 1 },
  { label: 'Flight', weight: 1 },
  { label: 'Invisibility', weight: 1 },
  { label: 'Teleportation', weight: 1 },
  { label: 'Telepathy', weight: 1 },
  { label: 'Telekinesis', weight: 1 },
  { label: 'Precognition', weight: 1 },
  { label: 'Pyrokinesis', weight: 1 },
  { label: 'Hydrokinesis', weight: 1 },
  { label: 'Electrokinesis', weight: 1 },
  { label: 'Cryokinesis', weight: 1 },
  { label: 'Terrakinesis', weight: 1 },
  { label: 'Aerokinesis', weight: 1 },
  { label: 'Photokinesis', weight: 1 },
  { label: 'Umbrakinesis', weight: 1 },
  { label: 'Necromancy', weight: 1 },
  { label: 'Conjuration', weight: 1 },
  { label: 'Illusion Mastery', weight: 1 },
  { label: 'Divination', weight: 1 },
  { label: 'Transmutation', weight: 1 },
  { label: 'Abjuration', weight: 1 },
  { label: 'Enchantment Mastery', weight: 1 },
  { label: 'Evocation', weight: 1 },
  { label: 'Astral Projection', weight: 1 },
  { label: 'Soul Vision', weight: 1 },
  { label: 'Arcane Sight', weight: 1 },
  { label: 'Reality Warping', weight: 1 },
  { label: 'Dimensional Pocket', weight: 1 },
  { label: 'Time Stop', weight: 1 },
  { label: 'Chronolock', weight: 1 },
  { label: 'Event Horizon Creation', weight: 1 },
  { label: 'Stellar Detonation', weight: 1 },
  { label: 'Matter Disintegration', weight: 1 },
  { label: 'Molecular Vibration', weight: 1 },
  { label: 'Atomic Restructuring', weight: 1 },
  { label: 'Nuclear Pulse', weight: 1 },
  { label: 'Dark Energy Manipulation', weight: 1 },
  { label: 'Antimatter Generation', weight: 1 },
  { label: 'Graviton Control', weight: 1 },
  { label: 'Space Folding', weight: 1 },
  { label: 'Wormhole Creation', weight: 1 },
  { label: 'Dimensional Lock', weight: 1 },
  { label: 'Pocket Universe Creation', weight: 1 },
  { label: 'Causality Violation', weight: 1 },
  { label: 'Paradox Weaponization', weight: 1 },
  { label: 'Fate Threading', weight: 1 },
  { label: 'Destiny Alteration', weight: 1 },
  { label: 'Death Defiance', weight: 1 },
  { label: 'Soul Forge', weight: 1 },
  { label: 'Life Force Drain', weight: 1 },
  { label: 'Vitality Transfer', weight: 1 },
  { label: 'Organ Manipulation', weight: 1 },
  { label: 'Cellular Regeneration', weight: 1 },
  { label: 'Biological Control', weight: 1 },
  { label: 'Pathogen Generation', weight: 1 },
  { label: 'Toxin Immunity', weight: 1 },
  { label: 'Venom Synthesis', weight: 1 },
  { label: 'Pheromone Control', weight: 1 },
  { label: 'Echo Location', weight: 1 },
  { label: 'Thermoregulation Mastery', weight: 1 },
  { label: 'Pressure Immunity', weight: 1 },
  { label: 'Radiation Resistance', weight: 1 },
  { label: 'Electromagnetic Control', weight: 1 },
  { label: 'Magnetism Mastery', weight: 1 },
  { label: 'Static Field Generation', weight: 1 },
  { label: 'Arc Lightning', weight: 1 },
  { label: 'Ball Lightning Conjuration', weight: 1 },
  { label: 'Thunderclap Generation', weight: 1 },
  { label: 'Sonic Boom', weight: 1 },
  { label: 'Subsonic Disruption', weight: 1 },
  { label: 'Infrasonic Domination', weight: 1 },
  { label: 'Ultrasonic Projection', weight: 1 },
  { label: 'Resonance Shattering', weight: 1 },
  { label: 'Harmonic Disruption', weight: 1 },
  { label: 'Frequency Mastery', weight: 1 },
  { label: 'Waveform Collapse', weight: 1 },
  { label: 'Quantum Entanglement', weight: 1 },
  { label: 'Superposition State', weight: 1 },
  { label: 'Schrodinger Existence', weight: 1 },
  { label: 'Heisenberg Lock', weight: 1 },
  { label: 'Wave Function Collapse', weight: 1 },
  { label: 'Vacuum Energy Tap', weight: 1 },
  { label: 'Zero-Point Extraction', weight: 1 },
  { label: 'Dark Matter Interface', weight: 1 },
  { label: 'Cosmic String Manipulation', weight: 1 },
  { label: 'Spacetime Curvature Control', weight: 1 },
  { label: 'Chronofield Projection', weight: 1 },
  { label: 'Time Bubble Creation', weight: 1 },
  { label: 'Age Acceleration', weight: 1 },
  { label: 'Age Reversal', weight: 1 },
  { label: 'Temporal Stasis', weight: 1 },
  { label: 'Causal Loop Engineering', weight: 1 },
  { label: 'Timeline Navigation', weight: 1 },
  { label: 'Parallel Self Summoning', weight: 1 },
  { label: 'Multiverse Awareness', weight: 1 },
  { label: 'Omniversal Sight', weight: 1 },
  { label: 'Concept Destruction', weight: 1 },
  { label: 'Abstract Manipulation', weight: 1 },
  { label: 'Narrative Control', weight: 1 },
  { label: 'Meta-Fiction Awareness', weight: 1 },
  { label: 'Fourth Wall Bypass', weight: 1 },
  { label: 'Author Override', weight: 1 },
  { label: 'Plot Armour Generation', weight: 1 },
  { label: 'Deus Ex Machina Summoning', weight: 1 },
  { label: 'Retcon Field', weight: 1 },
  { label: 'Canon Manipulation', weight: 1 },
  { label: 'Continuity Anchor', weight: 1 },
  { label: 'Omniscience (Partial)', weight: 1 },
  { label: 'Omnipotence (Weekend Only)', weight: 1 },
  { label: 'Omnipresence (Local)', weight: 1 },
  { label: 'Elemental Immunity', weight: 1 },
  { label: 'Elemental Mastery', weight: 1 },
  { label: 'Mana Sight', weight: 1 },
  { label: 'Mana Overcharge', weight: 1 },
  { label: 'Spell Absorption', weight: 1 },
  { label: 'Magic Reflection', weight: 1 },
  { label: 'Arcane Explosion', weight: 1 },
  { label: 'Mana Construct Creation', weight: 1 },
  { label: 'Golem Forging', weight: 1 },
  { label: 'Homunculus Creation', weight: 1 },
  { label: 'Familiar Bonding', weight: 1 },
  { label: 'Bestiary Mastery', weight: 1 },
  { label: 'Monster Taming', weight: 1 },
  { label: 'Beast Transformation', weight: 1 },
  { label: 'Chimera Form', weight: 1 },
  { label: 'Dragon Form', weight: 1 },
  { label: 'Titan Form', weight: 1 },
  { label: 'Ethereal Form', weight: 1 },
  { label: 'Gaseous Form', weight: 1 },
  { label: 'Liquid Form', weight: 1 },
  { label: 'Crystalline Form', weight: 1 },
  { label: 'Iron Form', weight: 1 },
  { label: 'Void Form', weight: 1 },
  { label: 'Radiant Form', weight: 1 },
  { label: 'Abyssal Form', weight: 1 },
  { label: 'Cosmic Form', weight: 1 },
  { label: 'True Form Revelation', weight: 1 },
  { label: 'Shapeshifting', weight: 1 },
  { label: 'Mimicry', weight: 1 },
  { label: 'Power Copying', weight: 1 },
  { label: 'Skill Absorption', weight: 1 },
  { label: 'Talent Stealing', weight: 1 },
  { label: 'Memory Reading', weight: 1 },
  { label: 'Emotion Sensing', weight: 1 },
  { label: 'Empathic Healing', weight: 1 },
  { label: 'Pain Transference', weight: 1 },
  { label: 'Fear Projection', weight: 1 },
  { label: 'Courage Aura', weight: 1 },
  { label: 'Despair Field', weight: 1 },
  { label: 'Hope Generation', weight: 1 },
  { label: 'Anger Amplification', weight: 1 },
  { label: 'Calm Aura', weight: 1 },
  { label: 'Madness Induction', weight: 1 },
  { label: 'Sanity Restoration', weight: 1 },
  { label: 'Mind Fortress', weight: 1 },
  { label: 'Psychic Shield', weight: 1 },
  { label: 'Neural Firewall', weight: 1 },
  { label: 'Brainwave Jamming', weight: 1 },
  { label: 'Collective Intelligence', weight: 1 },
  { label: 'Hivemind Creation', weight: 1 },
  { label: 'Psychic Network', weight: 1 },
  { label: 'Swarm Intelligence', weight: 1 },
  { label: 'Distributed Consciousness', weight: 1 },
  { label: 'Soul Splitting', weight: 1 },
  { label: 'Ego Projection', weight: 1 },
  { label: 'Superego Manifestation', weight: 1 },
  { label: 'Id Unleashing', weight: 1 },
  { label: 'Archetype Summoning', weight: 1 },
  { label: 'Concept Embodiment', weight: 1 },
  { label: 'Virtue Manifestation', weight: 1 },
  { label: 'Sin Embodiment', weight: 1 },
  { label: 'Death Personification', weight: 1 },
  { label: 'Life Personification', weight: 1 },
  { label: 'War Embodiment', weight: 1 },
  { label: 'Peace Manifestation', weight: 1 },
  { label: 'Knowledge Absorption', weight: 1 },
  { label: 'Wisdom Attainment', weight: 1 },
  { label: 'Truth Perception', weight: 1 },
  { label: 'Lie Detection (Perfect)', weight: 1 },
  { label: 'Pattern Recognition (Cosmic)', weight: 1 },
  { label: 'Logical Omniscience', weight: 1 },
  { label: 'Intuitive Mastery', weight: 1 },
  { label: 'Genius Intellect', weight: 1 },
  { label: 'Perfect Memory', weight: 1 },
  { label: 'Photographic Recall', weight: 1 },
  { label: 'Eidetic Memory', weight: 1 },
  { label: 'Total Recall', weight: 1 },
  { label: 'Future Memory', weight: 1 },
  { label: 'Past Life Access', weight: 1 },
  { label: 'Ancestral Knowledge', weight: 1 },
  { label: 'Genetic Memory', weight: 1 },
  { label: 'Racial Memory Tap', weight: 1 },
  { label: 'Collective Unconscious Access', weight: 1 },
  { label: 'Akashic Record Reading', weight: 1 },
  { label: 'Universal Truth Access', weight: 1 },
  { label: 'Fundamental Force Control', weight: 1 },
  { label: 'Strong Force Manipulation', weight: 1 },
  { label: 'Weak Force Control', weight: 1 },
  { label: 'Gravity Well Creation', weight: 1 },
  { label: 'Inertia Negation', weight: 1 },
  { label: 'Momentum Redirection', weight: 1 },
  { label: 'Friction Control', weight: 1 },
  { label: 'Velocity Mastery', weight: 1 },
  { label: 'Acceleration Manipulation', weight: 1 },
  { label: 'Terminal Velocity Defiance', weight: 1 },
  { label: 'Kinetic Energy Absorption', weight: 1 },
  { label: 'Kinetic Energy Release', weight: 1 },
  { label: 'Potential Energy Conversion', weight: 1 },
  { label: 'Thermal Energy Control', weight: 1 },
  { label: 'Chemical Energy Mastery', weight: 1 },
  { label: 'Nuclear Energy Tap', weight: 1 },
  { label: 'Solar Energy Absorption', weight: 1 },
  { label: 'Stellar Radiation Immunity', weight: 1 },
  { label: 'Cosmic Ray Channeling', weight: 1 },
  { label: 'Pulsar Frequency Emission', weight: 1 },
  { label: 'Magnetar Field Generation', weight: 1 },
  { label: 'Quasar Power Tap', weight: 1 },
  { label: 'Black Hole Creation (Contained)', weight: 1 },
  { label: 'White Hole Emergence', weight: 1 },
  { label: 'Supernova Channeling', weight: 1 },
  { label: 'Nebula Shaping', weight: 1 },
  { label: 'Galaxy Manipulation', weight: 1 },
  { label: 'Universal Constant Adjustment', weight: 1 },
  { label: 'Planck Scale Control', weight: 1 },
  { label: 'String Theory Mastery', weight: 1 },
  { label: 'Brane World Navigation', weight: 1 },
  { label: 'Dimensional Frequency Tuning', weight: 1 },
  { label: 'Infernal Command', weight: 1 },
  { label: 'Celestial Authority', weight: 1 },
  { label: 'Divine Smite', weight: 1 },
  { label: 'Unholy Corruption', weight: 1 },
  { label: 'Holy Cleansing', weight: 1 },
  { label: 'Radiant Burst', weight: 1 },
  { label: 'Shadow Bolt', weight: 1 },
  { label: 'Void Pulse', weight: 1 },
  { label: 'Arcane Missile', weight: 1 },
  { label: 'Force Wave', weight: 1 },
  { label: 'Shock Nova', weight: 1 },
  { label: 'Frost Nova', weight: 1 },
  { label: 'Fire Storm', weight: 1 },
  { label: 'Meteor Strike', weight: 1 },
  { label: 'Comet Call', weight: 1 },
  { label: 'Blizzard', weight: 1 },
  { label: 'Tsunami Conjuration', weight: 1 },
  { label: 'Sandstorm Mastery', weight: 1 },
  { label: 'Volcanic Eruption', weight: 1 },
  { label: 'Earthquake Generation', weight: 1 },
  { label: 'Hurricane Force', weight: 1 },
  { label: 'Tornado Creation', weight: 1 },
  { label: 'Lightning Storm', weight: 1 },
  { label: 'Hailstorm', weight: 1 },
  { label: 'Acid Rain', weight: 1 },
  { label: 'Blood Rain', weight: 1 },
  { label: 'Plague Cloud', weight: 1 },
  { label: 'Death Mist', weight: 1 },
  { label: 'Soul Storm', weight: 1 },
  { label: 'Arcane Tempest', weight: 1 },
  { label: 'Dimensional Tear', weight: 1 },
  { label: 'Reality Fracture', weight: 1 },
  { label: 'Space Collapse', weight: 1 },
  { label: 'Gravity Crush', weight: 1 },
  { label: 'Time Fracture', weight: 1 },
  { label: 'Temporal Shockwave', weight: 1 },
  { label: 'Causal Rift', weight: 1 },
  { label: 'Paradox Bomb', weight: 1 },
  { label: 'Entropy Wave', weight: 1 },
  { label: 'Order Pulse', weight: 1 },
  { label: 'Chaos Nova', weight: 1 },
  { label: 'Law Enforcement (Cosmic)', weight: 1 },
  { label: 'Balance Restoration', weight: 1 },
  { label: 'Equilibrium Manipulation', weight: 1 },
  { label: 'Duality Mastery', weight: 1 },
  { label: 'Yin-Yang Control', weight: 1 },
  { label: 'Harmonic Convergence', weight: 1 },
  { label: 'Dissonance Weaponization', weight: 1 },
  { label: 'Resonance Amplification', weight: 1 },
  { label: 'Frequency Lock', weight: 1 },
  { label: 'Vibration Control', weight: 1 },
  { label: 'Phase Shifting', weight: 1 },
  { label: 'Intangibility', weight: 1 },
  { label: 'Density Control', weight: 1 },
  { label: 'Mass Alteration', weight: 1 },
  { label: 'Weight Manipulation', weight: 1 },
  { label: 'Buoyancy Control', weight: 1 },
  { label: 'Surface Tension Mastery', weight: 1 },
  { label: 'Viscosity Control', weight: 1 },
  { label: 'Cohesion Field', weight: 1 },
  { label: 'Adhesion Control', weight: 1 },
  { label: 'Solubility Manipulation', weight: 1 },
  { label: 'Chemical Transmutation', weight: 1 },
  { label: 'Elemental Creation', weight: 1 },
  { label: 'Alchemical Mastery', weight: 1 },
  { label: 'Philosopher\'s Stone Synthesis', weight: 1 },
  { label: 'Homunculus Alchemy', weight: 1 },
  { label: 'Ouroboros Binding', weight: 1 },
  { label: 'Gate of Truth Access', weight: 1 },
  { label: 'Equivalent Exchange Bypass', weight: 1 },
  { label: 'Taboo Alchemy', weight: 1 },
  { label: 'Body Modification (Self)', weight: 1 },
  { label: 'Automail Mastery', weight: 1 },
  { label: 'Flesh Alchemy', weight: 1 },
  { label: 'Bone Alchemy', weight: 1 },
  { label: 'Stone Alchemy', weight: 1 },
  { label: 'Metal Alchemy', weight: 1 },
  { label: 'Crystal Synthesis', weight: 1 },
  { label: 'Diamond Hardening', weight: 1 },
  { label: 'Mithril Forging', weight: 1 },
  { label: 'Adamantine Shaping', weight: 1 },
  { label: 'Orichalcum Mastery', weight: 1 },
  { label: 'Legendary Metal Creation', weight: 1 },
  { label: 'Runic Inscription', weight: 1 },
  { label: 'Sigil Mastery', weight: 1 },
  { label: 'Glyph Activation', weight: 1 },
  { label: 'Ward Creation', weight: 1 },
  { label: 'Seal Binding', weight: 1 },
  { label: 'Contract Enforcement', weight: 1 },
  { label: 'Oath Binding', weight: 1 },
  { label: 'Curse Casting', weight: 1 },
  { label: 'Curse Breaking', weight: 1 },
  { label: 'Hex Weaving', weight: 1 },
  { label: 'Boon Granting', weight: 1 },
  { label: 'Blessing Channeling', weight: 1 },
  { label: 'Miracle Working', weight: 1 },
  { label: 'Prayer Manifestation', weight: 1 },
  { label: 'Ritual Mastery', weight: 1 },
  { label: 'Sacrifice Empowerment', weight: 1 },
  { label: 'Blood Magic', weight: 1 },
  { label: 'Lunar Magic', weight: 1 },
  { label: 'Solar Magic', weight: 1 },
  { label: 'Stellar Magic', weight: 1 },
  { label: 'Tidal Magic', weight: 1 },
  { label: 'Seasonal Attunement', weight: 1 },
  { label: 'Elemental Attunement', weight: 1 },
  { label: 'Nature Attunement', weight: 1 },
  { label: 'Urban Magic', weight: 1 },
  { label: 'Industrial Magic', weight: 1 },
  { label: 'Technological Magic Fusion', weight: 1 },
  { label: 'Nanotech Control', weight: 1 },
  { label: 'Cybernetics Mastery', weight: 1 },
  { label: 'AI Communion', weight: 1 },
  { label: 'Digital Consciousness', weight: 1 },
  { label: 'Code Manipulation', weight: 1 },
  { label: 'System Hacking (Reality)', weight: 1 },
  { label: 'Protocol Override', weight: 1 },
  { label: 'Admin Access (Universe)', weight: 1 },
  { label: 'Root Access (Existence)', weight: 1 },
  { label: 'Debug Mode Activation', weight: 1 },
  { label: 'Sandbox Escape', weight: 1 },
  { label: 'Firewall Bypass (Cosmic)', weight: 1 },
  { label: 'Encryption Breaking', weight: 1 },
  { label: 'Decryption Mastery', weight: 1 },
  { label: 'Signal Jamming (Universal)', weight: 1 },
  { label: 'Broadcast Control', weight: 1 },
  { label: 'Information Supremacy', weight: 1 },
  { label: 'Data Overwrite', weight: 1 },
  { label: 'Memory Corruption (Targets)', weight: 1 },
  { label: 'Memory Restoration', weight: 1 },
  { label: 'Psychic Surgery', weight: 1 },
  { label: 'Mind Palace Creation', weight: 1 },
  { label: 'Cognitive Architecture', weight: 1 },
  { label: 'Thought Acceleration', weight: 1 },
  { label: 'Hyper-Cognition', weight: 1 },
  { label: 'Rapid Analysis', weight: 1 },
  { label: 'Instant Calculation', weight: 1 },
  { label: 'Tactical Supremacy', weight: 1 },
  { label: 'Strategic Omniscience', weight: 1 },
  { label: 'Combat Precognition', weight: 1 },
  { label: 'Battle Flow Mastery', weight: 1 },
  { label: 'Perfect Muscle Memory', weight: 1 },
  { label: 'Stance Mastery', weight: 1 },
  { label: 'Technique Copying', weight: 1 },
  { label: 'Art Absorption', weight: 1 },
  { label: 'Martial Enlightenment', weight: 1 },
  { label: 'Chi Mastery', weight: 1 },
  { label: 'Ki Projection', weight: 1 },
  { label: 'Chakra Alignment', weight: 1 },
  { label: 'Prana Channeling', weight: 1 },
  { label: 'Mana Well', weight: 1 },
  { label: 'Infinite Mana', weight: 1 },
  { label: 'Mana Conversion', weight: 1 },
  { label: 'Spell Stealing', weight: 1 },
  { label: 'Power Nullification', weight: 1 },
  { label: 'Ability Sealing', weight: 1 },
  { label: 'Skill Lock', weight: 1 },
  { label: 'Power Restriction (Others)', weight: 1 },
  { label: 'Power Amplification (Self)', weight: 1 },
  { label: 'Power Amplification (Others)', weight: 1 },
  { label: 'Synergy Mastery', weight: 1 },
  { label: 'Combination Attack Creation', weight: 1 },
  { label: 'Fusion Technique', weight: 1 },
  { label: 'Form Synthesis', weight: 1 },
  { label: 'Awakening Trigger', weight: 1 },
  { label: 'True Power Release', weight: 1 },
  { label: 'Limiter Removal', weight: 1 },
  { label: 'Governor Bypass', weight: 1 },
  { label: 'Threshold Crossing', weight: 1 },
  { label: 'Ascension Trigger', weight: 1 },
  { label: 'Transcendence', weight: 1 },
  { label: 'Apotheosis', weight: 1 },
  { label: 'Deification', weight: 1 },
  { label: 'Godhood (Temporary)', weight: 1 },
  { label: 'Avatar State', weight: 1 },
  { label: 'Super Mode Activation', weight: 1 },
  { label: 'Ultra Form', weight: 1 },
  { label: 'Hyper Mode', weight: 1 },
  { label: 'Rage Mode', weight: 1 },
  { label: 'Berserk State', weight: 1 },
  { label: 'Calm State (Combat)', weight: 1 },
  { label: 'Flow State (Eternal)', weight: 1 },
  { label: 'Zone Entry (Perfect)', weight: 1 },
  { label: 'Peak Performance Maintenance', weight: 1 },
  { label: 'Absolute Focus', weight: 1 },
  { label: 'Zero Distraction Field', weight: 1 },
  { label: 'Perfect Composure', weight: 1 },
  { label: 'Unbreakable Will', weight: 1 },
  { label: 'Iron Resolve', weight: 1 },
  { label: 'Determination Embodiment', weight: 1 },
  { label: 'Never-Give-Up Aura', weight: 1 },
  { label: 'Protagonist Energy', weight: 1 },
  { label: 'Main Character Syndrome', weight: 1 },
  { label: 'Chosen One Activation', weight: 1 },
  { label: 'Destiny Fulfillment', weight: 1 },
  { label: 'Prophecy Binding', weight: 1 },
  { label: 'Fate Convergence', weight: 1 },
  { label: 'Luck Maximization', weight: 1 },
  { label: 'Fortune Mastery', weight: 1 },
  { label: 'Karma Manipulation', weight: 1 },
  { label: 'Coincidence Engineering', weight: 1 },
  { label: 'Serendipity Control', weight: 1 },
  { label: 'Murphy\'s Law Reversal', weight: 1 },
  { label: 'Aura of Inevitability', weight: 1 },
  { label: 'Temporal Rewind', weight: 1 },
  { label: 'Dimension Slam', weight: 1 },
  { label: 'Soul Rend', weight: 1 },
  { label: 'Abyssal Grasp', weight: 1 },
  { label: 'Stygian Flame', weight: 1 },
  { label: 'Eldritch Blast (Advanced)', weight: 1 },
  { label: 'Primordial Roar', weight: 1 },
  { label: 'Ancient Dominion', weight: 1 },
  { label: 'Apex Predator Instinct', weight: 1 },
  { label: 'Pressure Point Mastery', weight: 1 },
  { label: 'Nerve Strike', weight: 1 },
  { label: 'Vital Point Accuracy', weight: 1 },
  { label: 'Death Touch', weight: 1 },
  { label: 'Life Drain (Contact)', weight: 1 },
  { label: 'Corrosive Aura', weight: 1 },
  { label: 'Disintegration Field', weight: 1 },
  { label: 'Nullity Zone', weight: 1 },
  { label: 'Suppression Field', weight: 1 },
  { label: 'Anti-Magic Aura', weight: 1 },
  { label: 'Power Siphon', weight: 1 },
  { label: 'Essence Theft', weight: 1 },
  { label: 'Mana Burn', weight: 1 },
  { label: 'Force Shield', weight: 1 },
  { label: 'Barrier Creation', weight: 1 },
  { label: 'Dome of Silence', weight: 1 },
  { label: 'Invisible Wall Generation', weight: 1 },
  { label: 'Mirror Shield', weight: 1 },
  { label: 'Deflection Mastery', weight: 1 },
  { label: 'Counter-Strike Reflex', weight: 1 },
  { label: 'Perfect Parry', weight: 1 },
  { label: 'Reversal Strike', weight: 1 },
  { label: 'Riposte Mastery', weight: 1 },
  { label: 'Combat Flow State', weight: 1 },
  { label: 'Warrior Trance', weight: 1 },
  { label: 'Battle Precognition', weight: 1 },
  { label: 'Enemy Intent Reading', weight: 1 },
  { label: 'Body Language Mastery', weight: 1 },
  { label: 'Deception Detection', weight: 1 },
  { label: 'Perfect Bluff', weight: 1 },

  // ── Elemental / Class-Granted Powers ──
  { label: 'Fire Breath', weight: 1 },
  { label: 'Lightning Breath', weight: 1 },
  { label: 'Poison Breath', weight: 1 },
  { label: 'Acid Spray', weight: 1 },
  { label: 'Frost Breath', weight: 1 },
  { label: 'Sunfire Aura', weight: 1 },
  { label: 'Blizzard Call', weight: 1 },
  { label: 'Thunder Clap', weight: 1 },
  { label: 'Hydrokinesis', weight: 1 },
  { label: 'Geokinesis', weight: 1 },
  { label: 'Pyrokinesis', weight: 1 },
  { label: 'Aerokinesis', weight: 1 },
  { label: 'Metallokinesis', weight: 1 },
  { label: 'Lava Control', weight: 1 },
  { label: 'Bloodbending', weight: 1 },
  { label: 'Lightning Generation', weight: 1 },
  { label: 'All Elements Mastery', weight: 1 },
  { label: 'Venom Injection', weight: 1 },
  { label: 'Web Slinging', weight: 1 },
  { label: 'Symbiote Tendrils', weight: 1 },
  { label: 'Cero Blast', weight: 1 },
  { label: 'Sonido Flash Step', weight: 1 },
  { label: 'Bone Manipulation', weight: 1 },
  { label: 'Shadow Corruption', weight: 1 },
  { label: 'Ki Blast', weight: 1 },
  { label: 'Zenkai Surge', weight: 1 },
  { label: 'Hakai (Destruction)', weight: 1 },
  { label: 'Flight (Saiyan)', weight: 1 },
  { label: 'Vampiric Drain', weight: 1 },
  { label: 'Bat Form', weight: 1 },
  { label: 'Blood Control', weight: 1 },
  { label: 'Mind Fog', weight: 1 },
  { label: 'Nether Flame', weight: 1 },
  { label: 'Soul Corruption', weight: 1 },
  { label: 'Infernal Contract', weight: 1 },
  { label: 'Titan Shift', weight: 1 },
  { label: 'Hardening', weight: 1 },
  { label: 'Steam Explosion', weight: 1 },
  { label: 'Jaw Titan Bite', weight: 1 },
]
