// powers-epic.ts — Rebalanced power pool for Wheel of Fate.
// 420 entries: F(80) E(70) D(70) C(70) B(60) A(50) S(40) SS(30) SSS(20)
// God tier (10) lives in powers-absurd.ts alongside comedy powers.
// No default export.

import type { SimpleItem } from './types'

export const epicPowers: SimpleItem[] = [
  // ── GOD TIER (10) — reality-breaking, universe-level ──
  { label: 'Omnipotence',                weight: 1, element: 'Cosmic',    grade: 'God', attackType: 'passive'  },
  { label: 'True Omniscience',           weight: 1, element: 'Cosmic',    grade: 'God', attackType: 'passive'  },
  { label: 'Reality Rewrite',            weight: 1, element: 'Chaos',     grade: 'God', attackType: 'attack'   },
  { label: 'Existence Erasure',          weight: 1, element: 'Void',      grade: 'God', attackType: 'attack'   },
  { label: 'Infinite Regeneration',      weight: 1, element: 'Soul',      grade: 'God', attackType: 'heal'     },
  { label: 'Conceptual Destruction',     weight: 1, element: 'Void',      grade: 'God', attackType: 'attack'   },
  { label: 'True Immortality',           weight: 1, element: 'Time',      grade: 'God', attackType: 'passive'  },
  { label: 'Universal Force Control',    weight: 1, element: 'Gravity',   grade: 'God', attackType: 'buff'     },
  { label: 'Absolute Causality Override',weight: 1, element: 'Time',      grade: 'God', attackType: 'buff'     },
  { label: 'Primordial Creation',        weight: 1, element: 'Cosmic',    grade: 'God', attackType: 'summon'   },

  // ── SSS TIER (20) — legendary, universe-scale ──
  { label: 'Pocket Universe Creation',   weight: 1, element: 'Chaos',     grade: 'SSS', attackType: 'summon'   },
  { label: 'Causality Violation',        weight: 1, element: 'Chaos',     grade: 'SSS', attackType: 'debuff'   },
  { label: 'Time Stop',                  weight: 1, element: 'Time',      grade: 'SSS', attackType: 'debuff'   },
  { label: 'Chronolock',                 weight: 1, element: 'Time',      grade: 'SSS', attackType: 'debuff'   },
  { label: 'Event Horizon Creation',     weight: 1, element: 'Void',      grade: 'SSS', attackType: 'aoe'      },
  { label: 'Stellar Detonation',         weight: 1, element: 'Cosmic',    grade: 'SSS', attackType: 'aoe'      },
  { label: 'Dimensional Fortress',       weight: 1, element: 'Void',      grade: 'SSS', attackType: 'buff'     },
  { label: 'Soul Domain',                weight: 1, element: 'Soul',      grade: 'SSS', attackType: 'buff'     },
  { label: 'Entropy Reversal',           weight: 1, element: 'Void',      grade: 'SSS', attackType: 'debuff'   },
  { label: 'Fate Unraveling',            weight: 1, element: 'Cosmic',    grade: 'SSS', attackType: 'debuff'   },
  { label: 'Astral Singularity',         weight: 1, element: 'Cosmic',    grade: 'SSS', attackType: 'aoe'      },
  { label: 'Void Annihilation',          weight: 1, element: 'Void',      grade: 'SSS', attackType: 'aoe'      },
  { label: 'World-Ending Flame',         weight: 1, element: 'Fire',      grade: 'SSS', attackType: 'aoe'      },
  { label: 'Absolute Freeze',            weight: 1, element: 'Ice',       grade: 'SSS', attackType: 'aoe'      },
  { label: 'Dimensional Collapse',       weight: 1, element: 'Chaos',     grade: 'SSS', attackType: 'aoe'      },
  { label: 'Cosmic Storm Manifestation', weight: 1, element: 'Cosmic',    grade: 'SSS', attackType: 'aoe'      },
  { label: 'The Death Touch',            weight: 1, element: 'Soul',      grade: 'SSS', attackType: 'attack'   },
  { label: 'Origin Sealing',             weight: 1, element: 'Arcane',    grade: 'SSS', attackType: 'debuff'   },
  { label: 'Universal Gravity Crush',    weight: 1, element: 'Gravity',   grade: 'SSS', attackType: 'aoe'      },
  { label: 'Primordial Darkness',        weight: 1, element: 'Shadow',    grade: 'SSS', attackType: 'aoe'      },

  // ── SS TIER (30) — divine-level power ──
  { label: 'Paradox Weaponization',      weight: 1, element: 'Chaos',     grade: 'SS',  attackType: 'attack'   },
  { label: 'Fate Threading',             weight: 1, element: 'Cosmic',    grade: 'SS',  attackType: 'buff'     },
  { label: 'Destiny Alteration',         weight: 1, element: 'Cosmic',    grade: 'SS',  attackType: 'buff'     },
  { label: 'Probability Inversion',      weight: 1, element: 'Chaos',     grade: 'SS',  attackType: 'debuff'   },
  { label: 'Reality Anchor',             weight: 1, element: 'Chaos',     grade: 'SS',  attackType: 'buff'     },
  { label: 'Reality Warping',            weight: 1, element: 'Chaos',     grade: 'SS',  attackType: 'buff'     },
  { label: 'Dark Energy Manipulation',   weight: 1, element: 'Void',      grade: 'SS',  attackType: 'attack'   },
  { label: 'Antimatter Generation',      weight: 1, element: 'Void',      grade: 'SS',  attackType: 'aoe'      },
  { label: 'Space Folding',              weight: 1, element: 'Chaos',     grade: 'SS',  attackType: 'buff'     },
  { label: 'Wormhole Creation',          weight: 1, element: 'Cosmic',    grade: 'SS',  attackType: 'buff'     },
  { label: 'Dimensional Lock',           weight: 1, element: 'Void',      grade: 'SS',  attackType: 'debuff'   },
  { label: 'Soul Forge',                 weight: 1, element: 'Soul',      grade: 'SS',  attackType: 'summon'   },
  { label: 'Dimensional Rifting',        weight: 1, element: 'Chaos',     grade: 'SS',  attackType: 'attack'   },
  { label: 'Chrono Displacement',        weight: 1, element: 'Time',      grade: 'SS',  attackType: 'debuff'   },
  { label: 'Graviton Control',           weight: 1, element: 'Gravity',   grade: 'SS',  attackType: 'buff'     },
  { label: 'Star Forge',                 weight: 1, element: 'Cosmic',    grade: 'SS',  attackType: 'summon'   },
  { label: 'Void Walking',               weight: 1, element: 'Void',      grade: 'SS',  attackType: 'buff'     },
  { label: 'Entropy Control',            weight: 1, element: 'Void',      grade: 'SS',  attackType: 'debuff'   },
  { label: 'Molecular Reconstruction',   weight: 1, element: 'Arcane',    grade: 'SS',  attackType: 'buff'     },
  { label: 'Neural Domination',          weight: 1, element: 'Psychic',   grade: 'SS',  attackType: 'debuff'   },
  { label: 'Absolute Zero Aura',         weight: 1, element: 'Ice',       grade: 'SS',  attackType: 'aoe'      },
  { label: 'Psychic Dominion',           weight: 1, element: 'Psychic',   grade: 'SS',  attackType: 'debuff'   },
  { label: 'Biological Control',         weight: 1, element: 'Nature',    grade: 'SS',  attackType: 'debuff'   },
  { label: 'Cosmic Awareness',           weight: 1, element: 'Cosmic',    grade: 'SS',  attackType: 'passive'  },
  { label: 'Dream Invasion',             weight: 1, element: 'Psychic',   grade: 'SS',  attackType: 'debuff'   },
  { label: 'Shadow Realm Creation',      weight: 1, element: 'Shadow',    grade: 'SS',  attackType: 'summon'   },
  { label: 'Gravity Singularity',        weight: 1, element: 'Gravity',   grade: 'SS',  attackType: 'aoe'      },
  { label: 'Life Force Severing',        weight: 1, element: 'Soul',      grade: 'SS',  attackType: 'attack'   },
  { label: 'Mass Petrification',         weight: 1, element: 'Earth',     grade: 'SS',  attackType: 'aoe'      },
  { label: 'Temporal Echo',              weight: 1, element: 'Time',      grade: 'SS',  attackType: 'buff'     },

  // ── S TIER (40) — mythic-level power ──
  { label: 'Time Reversal',              weight: 1, element: 'Time',      grade: 'S',   attackType: 'buff'     },
  { label: 'Shadow Realm Portal',        weight: 1, element: 'Shadow',    grade: 'S',   attackType: 'summon'   },
  { label: 'Probability Manipulation',   weight: 1, element: 'Chaos',     grade: 'S',   attackType: 'buff'     },
  { label: 'Dimensional Pocket',         weight: 1, element: 'Arcane',    grade: 'S',   attackType: 'buff'     },
  { label: 'Plasma Detonation',          weight: 1, element: 'Fire',      grade: 'S',   attackType: 'aoe'      },
  { label: 'Gravitational Mastery',      weight: 1, element: 'Gravity',   grade: 'S',   attackType: 'buff'     },
  { label: 'Necromancy',                 weight: 1, element: 'Soul',      grade: 'S',   attackType: 'summon'   },
  { label: 'Elemental Convergence',      weight: 1, element: 'Arcane',    grade: 'S',   attackType: 'aoe'      },
  { label: 'Soul Absorption',            weight: 1, element: 'Soul',      grade: 'S',   attackType: 'attack'   },
  { label: 'Quantum Tunneling',          weight: 1, element: 'Chaos',     grade: 'S',   attackType: 'buff'     },
  { label: 'Weather Dominion',           weight: 1, element: 'Wind',      grade: 'S',   attackType: 'aoe'      },
  { label: 'Spectral Army Summoning',    weight: 1, element: 'Soul',      grade: 'S',   attackType: 'summon'   },
  { label: 'Lava Mastery',               weight: 1, element: 'Fire',      grade: 'S',   attackType: 'aoe'      },
  { label: 'Lightning God Strike',       weight: 1, element: 'Lightning', grade: 'S',   attackType: 'attack'   },
  { label: 'Cosmic Ray Blast',           weight: 1, element: 'Cosmic',    grade: 'S',   attackType: 'attack'   },
  { label: 'Voidstep',                   weight: 1, element: 'Void',      grade: 'S',   attackType: 'buff'     },
  { label: 'Mental Fortress',            weight: 1, element: 'Psychic',   grade: 'S',   attackType: 'buff'     },
  { label: 'Blood Alchemy',              weight: 1, element: 'Blood',     grade: 'S',   attackType: 'buff'     },
  { label: 'Phoenix Rebirth',            weight: 1, element: 'Fire',      grade: 'S',   attackType: 'heal'     },
  { label: 'Nature Dominion',            weight: 1, element: 'Nature',    grade: 'S',   attackType: 'buff'     },
  { label: 'Ice Age Aura',               weight: 1, element: 'Ice',       grade: 'S',   attackType: 'aoe'      },
  { label: 'Thunder God Clap',           weight: 1, element: 'Lightning', grade: 'S',   attackType: 'aoe'      },
  { label: 'Neural Override',            weight: 1, element: 'Psychic',   grade: 'S',   attackType: 'debuff'   },
  { label: 'Death Defiance',             weight: 1, element: 'Soul',      grade: 'S',   attackType: 'passive'  },
  { label: 'Volcanic Eruption',          weight: 1, element: 'Earth',     grade: 'S',   attackType: 'aoe'      },
  { label: 'Tsunami Wave',               weight: 1, element: 'Water',     grade: 'S',   attackType: 'aoe'      },
  { label: 'Wind Cutter Storm',          weight: 1, element: 'Wind',      grade: 'S',   attackType: 'aoe'      },
  { label: 'Lightning Fortress',         weight: 1, element: 'Lightning', grade: 'S',   attackType: 'buff'     },
  { label: 'Time Manipulation',          weight: 1, element: 'Time',      grade: 'S',   attackType: 'buff'     },
  { label: 'Spectral Form',              weight: 1, element: 'Soul',      grade: 'S',   attackType: 'buff'     },
  { label: 'Life Force Drain',           weight: 1, element: 'Blood',     grade: 'S',   attackType: 'attack'   },
  { label: 'Crystalline Armor Manifestation', weight: 1, element: 'Earth', grade: 'S',  attackType: 'buff'     },
  { label: 'Sound Annihilation',         weight: 1, element: 'Sound',     grade: 'S',   attackType: 'aoe'      },
  { label: 'Acid Rain Summon',           weight: 1, element: 'Poison',    grade: 'S',   attackType: 'aoe'      },
  { label: 'Mana Vortex',                weight: 1, element: 'Arcane',    grade: 'S',   attackType: 'aoe'      },
  { label: 'Void Bomb',                  weight: 1, element: 'Void',      grade: 'S',   attackType: 'attack'   },
  { label: 'Cosmic Shield',              weight: 1, element: 'Cosmic',    grade: 'S',   attackType: 'buff'     },
  { label: 'Plague Aura',                weight: 1, element: 'Poison',    grade: 'S',   attackType: 'debuff'   },
  { label: 'Seraphic Wings',             weight: 1, element: 'Light',     grade: 'S',   attackType: 'buff'     },
  { label: 'Abyssal Tide',               weight: 1, element: 'Water',     grade: 'S',   attackType: 'aoe'      },

  // ── A TIER (50) — legendary power ──
  { label: 'Shadow Manipulation',        weight: 1, element: 'Shadow',    grade: 'A',   attackType: 'buff'     },
  { label: 'Molecular Vibration',        weight: 1, element: 'Arcane',    grade: 'A',   attackType: 'attack'   },
  { label: 'Atomic Restructuring',       weight: 1, element: 'Void',      grade: 'A',   attackType: 'buff'     },
  { label: 'Matter Disintegration',      weight: 1, element: 'Void',      grade: 'A',   attackType: 'attack'   },
  { label: 'Telekinetic Surge',          weight: 1, element: 'Psychic',   grade: 'A',   attackType: 'attack'   },
  { label: 'Precognition',               weight: 1, element: 'Psychic',   grade: 'A',   attackType: 'passive'  },
  { label: 'Nuclear Pulse',              weight: 1, element: 'Void',      grade: 'A',   attackType: 'aoe'      },
  { label: 'Illusion Mastery',           weight: 1, element: 'Arcane',    grade: 'A',   attackType: 'debuff'   },
  { label: 'Seismic Command',            weight: 1, element: 'Earth',     grade: 'A',   attackType: 'aoe'      },
  { label: 'Bone Architecture',          weight: 1, element: 'Earth',     grade: 'A',   attackType: 'summon'   },
  { label: 'Transmutation',              weight: 1, element: 'Arcane',    grade: 'A',   attackType: 'buff'     },
  { label: 'Conjuration',                weight: 1, element: 'Arcane',    grade: 'A',   attackType: 'summon'   },
  { label: 'Enchantment Mastery',        weight: 1, element: 'Arcane',    grade: 'A',   attackType: 'buff'     },
  { label: 'Evocation',                  weight: 1, element: 'Arcane',    grade: 'A',   attackType: 'attack'   },
  { label: 'Abjuration',                 weight: 1, element: 'Arcane',    grade: 'A',   attackType: 'buff'     },
  { label: 'Divination',                 weight: 1, element: 'Arcane',    grade: 'A',   attackType: 'passive'  },
  { label: 'Memory Erasure',             weight: 1, element: 'Psychic',   grade: 'A',   attackType: 'debuff'   },
  { label: 'Corrosive Touch',            weight: 1, element: 'Poison',    grade: 'A',   attackType: 'debuff'   },
  { label: 'Earthquake Stomp',           weight: 1, element: 'Earth',     grade: 'A',   attackType: 'aoe'      },
  { label: 'Arcane Barrage',             weight: 1, element: 'Arcane',    grade: 'A',   attackType: 'aoe'      },
  { label: 'Counterspell',               weight: 1, element: 'Arcane',    grade: 'A',   attackType: 'buff'     },
  { label: 'Spell Steal',                weight: 1, element: 'Arcane',    grade: 'A',   attackType: 'debuff'   },
  { label: 'Celestial Binding',          weight: 1, element: 'Light',     grade: 'A',   attackType: 'debuff'   },
  { label: 'Venom Mastery',              weight: 1, element: 'Poison',    grade: 'A',   attackType: 'debuff'   },
  { label: 'Holy Light Beam',            weight: 1, element: 'Light',     grade: 'A',   attackType: 'attack'   },
  { label: 'Blood Curse',                weight: 1, element: 'Blood',     grade: 'A',   attackType: 'debuff'   },
  { label: 'Time Slow',                  weight: 1, element: 'Time',      grade: 'A',   attackType: 'debuff'   },
  { label: 'Psychic Domination',         weight: 1, element: 'Psychic',   grade: 'A',   attackType: 'debuff'   },
  { label: 'Vitality Transfer',          weight: 1, element: 'Nature',    grade: 'A',   attackType: 'heal'     },
  { label: 'Ice Storm',                  weight: 1, element: 'Ice',       grade: 'A',   attackType: 'aoe'      },
  { label: 'Arcane Mastery',             weight: 1, element: 'Arcane',    grade: 'A',   attackType: 'buff'     },
  { label: 'Lightning Chain',            weight: 1, element: 'Lightning', grade: 'A',   attackType: 'aoe'      },
  { label: 'Shadow Army',                weight: 1, element: 'Shadow',    grade: 'A',   attackType: 'summon'   },
  { label: 'Force Field',                weight: 1, element: 'Arcane',    grade: 'A',   attackType: 'buff'     },
  { label: 'Spectral Blade Storm',       weight: 1, element: 'Soul',      grade: 'A',   attackType: 'aoe'      },
  { label: 'Curse Weaving',              weight: 1, element: 'Shadow',    grade: 'A',   attackType: 'debuff'   },
  { label: 'Magma Body',                 weight: 1, element: 'Fire',      grade: 'A',   attackType: 'buff'     },
  { label: 'Crystal Cage',               weight: 1, element: 'Earth',     grade: 'A',   attackType: 'debuff'   },
  { label: 'Toxin Immunity',             weight: 1, element: 'Poison',    grade: 'A',   attackType: 'passive'  },
  { label: 'Wind Slash',                 weight: 1, element: 'Wind',      grade: 'A',   attackType: 'attack'   },
  { label: 'Mind Reading',               weight: 1, element: 'Psychic',   grade: 'A',   attackType: 'passive'  },
  { label: 'Firestorm Aura',             weight: 1, element: 'Fire',      grade: 'A',   attackType: 'aoe'      },
  { label: 'Water Breathing',            weight: 1, element: 'Water',     grade: 'A',   attackType: 'passive'  },
  { label: 'Telepathy',                  weight: 1, element: 'Psychic',   grade: 'A',   attackType: 'passive'  },
  { label: 'Thunder Clap',               weight: 1, element: 'Lightning', grade: 'A',   attackType: 'aoe'      },
  { label: 'Curse of Decay',             weight: 1, element: 'Shadow',    grade: 'A',   attackType: 'debuff'   },
  { label: 'Nature Surge',               weight: 1, element: 'Nature',    grade: 'A',   attackType: 'heal'     },
  { label: 'Sound Shaping',              weight: 1, element: 'Sound',     grade: 'A',   attackType: 'buff'     },
  { label: 'Mirror Dimension',           weight: 1, element: 'Arcane',    grade: 'A',   attackType: 'buff'     },
  { label: 'Spirit Guidance',            weight: 1, element: 'Soul',      grade: 'A',   attackType: 'buff'     },

  // ── B TIER (60) — epic power ──
  { label: 'Lightning Mastery',          weight: 1, element: 'Lightning', grade: 'B',   attackType: 'buff'     },
  { label: 'Invulnerability',            weight: 1, element: 'Neutral',   grade: 'B',   attackType: 'passive'  },
  { label: 'Super Strength',             weight: 1, element: 'Neutral',   grade: 'B',   attackType: 'passive'  },
  { label: 'Super Speed',                weight: 1, element: 'Neutral',   grade: 'B',   attackType: 'passive'  },
  { label: 'Flight',                     weight: 1, element: 'Wind',      grade: 'B',   attackType: 'passive'  },
  { label: 'Teleportation',              weight: 1, element: 'Arcane',    grade: 'B',   attackType: 'buff'     },
  { label: 'Telekinesis',                weight: 1, element: 'Psychic',   grade: 'B',   attackType: 'attack'   },
  { label: 'Pyrokinesis',                weight: 1, element: 'Fire',      grade: 'B',   attackType: 'attack'   },
  { label: 'Hydrokinesis',               weight: 1, element: 'Water',     grade: 'B',   attackType: 'attack'   },
  { label: 'Electrokinesis',             weight: 1, element: 'Lightning', grade: 'B',   attackType: 'attack'   },
  { label: 'Cryokinesis',                weight: 1, element: 'Ice',       grade: 'B',   attackType: 'attack'   },
  { label: 'Terrakinesis',               weight: 1, element: 'Earth',     grade: 'B',   attackType: 'attack'   },
  { label: 'Aerokinesis',                weight: 1, element: 'Wind',      grade: 'B',   attackType: 'attack'   },
  { label: 'Photokinesis',               weight: 1, element: 'Light',     grade: 'B',   attackType: 'attack'   },
  { label: 'Umbrakinesis',               weight: 1, element: 'Shadow',    grade: 'B',   attackType: 'attack'   },
  { label: 'Quantum Tunneling',          weight: 1, element: 'Chaos',     grade: 'B',   attackType: 'buff'     },
  { label: 'Healing Factor',             weight: 1, element: 'Nature',    grade: 'B',   attackType: 'heal'     },
  { label: 'Cellular Regeneration',      weight: 1, element: 'Nature',    grade: 'B',   attackType: 'heal'     },
  { label: 'Plasma Generation',          weight: 1, element: 'Fire',      grade: 'B',   attackType: 'attack'   },
  { label: 'Light Refraction',           weight: 1, element: 'Light',     grade: 'B',   attackType: 'buff'     },
  { label: 'Dimensional Pocket',         weight: 1, element: 'Arcane',    grade: 'B',   attackType: 'buff'     },
  { label: 'Mana Drain',                 weight: 1, element: 'Arcane',    grade: 'B',   attackType: 'debuff'   },
  { label: 'Pathogen Generation',        weight: 1, element: 'Poison',    grade: 'B',   attackType: 'debuff'   },
  { label: 'Astral Projection',          weight: 1, element: 'Soul',      grade: 'B',   attackType: 'buff'     },
  { label: 'Soul Vision',                weight: 1, element: 'Soul',      grade: 'B',   attackType: 'passive'  },
  { label: 'Arcane Sight',               weight: 1, element: 'Arcane',    grade: 'B',   attackType: 'passive'  },
  { label: 'Petrification Touch',        weight: 1, element: 'Earth',     grade: 'B',   attackType: 'debuff'   },
  { label: 'Acid Touch',                 weight: 1, element: 'Poison',    grade: 'B',   attackType: 'debuff'   },
  { label: 'Magnetism Control',          weight: 1, element: 'Metal',     grade: 'B',   attackType: 'buff'     },
  { label: 'Metal Shaping',              weight: 1, element: 'Metal',     grade: 'B',   attackType: 'buff'     },
  { label: 'Radiation Emission',         weight: 1, element: 'Void',      grade: 'B',   attackType: 'aoe'      },
  { label: 'Sonic Boom',                 weight: 1, element: 'Sound',     grade: 'B',   attackType: 'aoe'      },
  { label: 'Fear Aura',                  weight: 1, element: 'Psychic',   grade: 'B',   attackType: 'debuff'   },
  { label: 'Berserker Frenzy',           weight: 1, element: 'Fire',      grade: 'B',   attackType: 'buff'     },
  { label: 'Indomitable Rage',           weight: 1, element: 'Fire',      grade: 'B',   attackType: 'buff'     },
  { label: 'Gravity Press',              weight: 1, element: 'Gravity',   grade: 'B',   attackType: 'attack'   },
  { label: 'Shadow Step',                weight: 1, element: 'Shadow',    grade: 'B',   attackType: 'buff'     },
  { label: 'Darkness Veil',              weight: 1, element: 'Shadow',    grade: 'B',   attackType: 'buff'     },
  { label: 'Mind Blast',                 weight: 1, element: 'Psychic',   grade: 'B',   attackType: 'attack'   },
  { label: 'Blood Manipulation',         weight: 1, element: 'Blood',     grade: 'B',   attackType: 'attack'   },
  { label: 'Arcane Torrent',             weight: 1, element: 'Arcane',    grade: 'B',   attackType: 'aoe'      },
  { label: 'Blizzard Breath',            weight: 1, element: 'Ice',       grade: 'B',   attackType: 'aoe'      },
  { label: 'Earth Spike Barrage',        weight: 1, element: 'Earth',     grade: 'B',   attackType: 'aoe'      },
  { label: 'Mimic',                      weight: 1, element: 'Arcane',    grade: 'B',   attackType: 'buff'     },
  { label: 'Mirror Copy',                weight: 1, element: 'Arcane',    grade: 'B',   attackType: 'summon'   },
  { label: 'Power Siphon',               weight: 1, element: 'Arcane',    grade: 'B',   attackType: 'debuff'   },
  { label: 'Flame Burst',                weight: 1, element: 'Fire',      grade: 'B',   attackType: 'attack'   },
  { label: 'Time Sense',                 weight: 1, element: 'Time',      grade: 'B',   attackType: 'passive'  },
  { label: 'Soul Sight',                 weight: 1, element: 'Soul',      grade: 'B',   attackType: 'passive'  },
  { label: 'Combat Flow State',          weight: 1, element: 'Neutral',   grade: 'B',   attackType: 'buff'     },
  { label: 'Battle Precognition',        weight: 1, element: 'Psychic',   grade: 'B',   attackType: 'passive'  },
  { label: 'Perfect Parry',              weight: 1, element: 'Neutral',   grade: 'B',   attackType: 'passive'  },
  { label: 'Counter-Strike Reflex',      weight: 1, element: 'Neutral',   grade: 'B',   attackType: 'passive'  },
  { label: 'Warrior Trance',             weight: 1, element: 'Neutral',   grade: 'B',   attackType: 'buff'     },
  { label: 'Arcane Infusion',            weight: 1, element: 'Arcane',    grade: 'B',   attackType: 'buff'     },
  { label: 'Runic Ward',                 weight: 1, element: 'Arcane',    grade: 'B',   attackType: 'buff'     },
  { label: 'Forge Blessing',             weight: 1, element: 'Metal',     grade: 'B',   attackType: 'buff'     },
  { label: 'Crystal Armor',              weight: 1, element: 'Earth',     grade: 'B',   attackType: 'buff'     },
  { label: 'Stone Endurance',            weight: 1, element: 'Earth',     grade: 'B',   attackType: 'passive'  },
  { label: 'Ancestor Spirit',            weight: 1, element: 'Soul',      grade: 'B',   attackType: 'summon'   },

  // ── C TIER (70) — rare power ──
  { label: 'Invisibility',               weight: 1, element: 'Shadow',    grade: 'C',   attackType: 'buff'     },
  { label: 'Aura Reading',               weight: 1, element: 'Psychic',   grade: 'C',   attackType: 'passive'  },
  { label: 'Smoke Bomb',                 weight: 1, element: 'Shadow',    grade: 'C',   attackType: 'debuff'   },
  { label: 'Backstab',                   weight: 1, element: 'Shadow',    grade: 'C',   attackType: 'attack'   },
  { label: 'Sneak Attack',               weight: 1, element: 'Shadow',    grade: 'C',   attackType: 'attack'   },
  { label: 'Vanishing Act',              weight: 1, element: 'Shadow',    grade: 'C',   attackType: 'buff'     },
  { label: 'Poison Blade',               weight: 1, element: 'Poison',    grade: 'C',   attackType: 'debuff'   },
  { label: 'Sacred Heal',                weight: 1, element: 'Light',     grade: 'C',   attackType: 'heal'     },
  { label: 'Turn Undead',                weight: 1, element: 'Soul',      grade: 'C',   attackType: 'attack'   },
  { label: 'Radiant Strike',             weight: 1, element: 'Light',     grade: 'C',   attackType: 'attack'   },
  { label: 'Channel Divinity',           weight: 1, element: 'Light',     grade: 'C',   attackType: 'buff'     },
  { label: 'Holy Strike',                weight: 1, element: 'Light',     grade: 'C',   attackType: 'attack'   },
  { label: 'Shield Slam',                weight: 1, element: 'Light',     grade: 'C',   attackType: 'attack'   },
  { label: 'Aura of Retribution',        weight: 1, element: 'Light',     grade: 'C',   attackType: 'buff'     },
  { label: 'Lay on Hands',               weight: 1, element: 'Light',     grade: 'C',   attackType: 'heal'     },
  { label: 'Consecrated Ground',         weight: 1, element: 'Light',     grade: 'C',   attackType: 'buff'     },
  { label: 'Druidic Wild Shape',         weight: 1, element: 'Nature',    grade: 'C',   attackType: 'buff'     },
  { label: "Hunter's Mark",              weight: 1, element: 'Nature',    grade: 'C',   attackType: 'debuff'   },
  { label: 'Volley Shot',                weight: 1, element: 'Wind',      grade: 'C',   attackType: 'aoe'      },
  { label: 'Beast Bond',                 weight: 1, element: 'Nature',    grade: 'C',   attackType: 'buff'     },
  { label: 'Terrain Mastery',            weight: 1, element: 'Nature',    grade: 'C',   attackType: 'buff'     },
  { label: 'Predator Stance',            weight: 1, element: 'Nature',    grade: 'C',   attackType: 'buff'     },
  { label: 'Precision Strike',           weight: 1, element: 'Neutral',   grade: 'C',   attackType: 'attack'   },
  { label: 'Dual Strike',                weight: 1, element: 'Neutral',   grade: 'C',   attackType: 'attack'   },
  { label: 'Parry',                      weight: 1, element: 'Neutral',   grade: 'C',   attackType: 'passive'  },
  { label: 'Shield Block',               weight: 1, element: 'Neutral',   grade: 'C',   attackType: 'passive'  },
  { label: 'Reckless Attack',            weight: 1, element: 'Fire',      grade: 'C',   attackType: 'attack'   },
  { label: 'Courage Aura',               weight: 1, element: 'Light',     grade: 'C',   attackType: 'buff'     },
  { label: 'Spirit Walk',                weight: 1, element: 'Soul',      grade: 'C',   attackType: 'buff'     },
  { label: 'Spirit Guide',               weight: 1, element: 'Soul',      grade: 'C',   attackType: 'buff'     },
  { label: 'Ancestor Favor',             weight: 1, element: 'Soul',      grade: 'C',   attackType: 'buff'     },
  { label: "Nature's Grasp",             weight: 1, element: 'Nature',    grade: 'C',   attackType: 'debuff'   },
  { label: 'Storm Circle',               weight: 1, element: 'Lightning', grade: 'C',   attackType: 'aoe'      },
  { label: 'Bomb Toss',                  weight: 1, element: 'Fire',      grade: 'C',   attackType: 'attack'   },
  { label: 'Smoke Screen',               weight: 1, element: 'Shadow',    grade: 'C',   attackType: 'debuff'   },
  { label: 'Warchief Rally',             weight: 1, element: 'Neutral',   grade: 'C',   attackType: 'buff'     },
  { label: 'Battle Cry',                 weight: 1, element: 'Neutral',   grade: 'C',   attackType: 'buff'     },
  { label: 'Divine Smite',               weight: 1, element: 'Light',     grade: 'C',   attackType: 'attack'   },
  { label: 'Arcane Memory',              weight: 1, element: 'Arcane',    grade: 'C',   attackType: 'passive'  },
  { label: 'Inspire Greatness',          weight: 1, element: 'Sound',     grade: 'C',   attackType: 'buff'     },
  { label: 'Heroic Tale',                weight: 1, element: 'Sound',     grade: 'C',   attackType: 'buff'     },
  { label: 'Cutting Words',              weight: 1, element: 'Sound',     grade: 'C',   attackType: 'debuff'   },
  { label: 'Song of Victory',            weight: 1, element: 'Sound',     grade: 'C',   attackType: 'buff'     },
  { label: 'Runic Memory',               weight: 1, element: 'Arcane',    grade: 'C',   attackType: 'passive'  },
  { label: 'Stone Call',                 weight: 1, element: 'Earth',     grade: 'C',   attackType: 'attack'   },
  { label: 'Tremor Sense',               weight: 1, element: 'Earth',     grade: 'C',   attackType: 'passive'  },
  { label: 'Shadow Blade',               weight: 1, element: 'Shadow',    grade: 'C',   attackType: 'attack'   },
  { label: 'Trickster Gambit',           weight: 1, element: 'Chaos',     grade: 'C',   attackType: 'buff'     },
  { label: 'Perfect Bluff',              weight: 1, element: 'Chaos',     grade: 'C',   attackType: 'buff'     },
  { label: 'Arcane Barrier',             weight: 1, element: 'Arcane',    grade: 'C',   attackType: 'buff'     },
  { label: 'Fire Breath',                weight: 1, element: 'Fire',      grade: 'C',   attackType: 'attack'   },
  { label: 'Venom Spit',                 weight: 1, element: 'Poison',    grade: 'C',   attackType: 'debuff'   },
  { label: 'Stone Skin',                 weight: 1, element: 'Earth',     grade: 'C',   attackType: 'buff'     },
  { label: 'Troll Blood',                weight: 1, element: 'Blood',     grade: 'C',   attackType: 'heal'     },
  { label: 'War Drums',                  weight: 1, element: 'Neutral',   grade: 'C',   attackType: 'buff'     },
  { label: 'Primal Fury',                weight: 1, element: 'Fire',      grade: 'C',   attackType: 'buff'     },
  { label: 'Crushing Blow',              weight: 1, element: 'Earth',     grade: 'C',   attackType: 'attack'   },
  { label: 'Inspire Courage',            weight: 1, element: 'Sound',     grade: 'C',   attackType: 'buff'     },
  { label: 'Bardic Lore',                weight: 1, element: 'Sound',     grade: 'C',   attackType: 'passive'  },
  { label: "Nature's Memory",            weight: 1, element: 'Nature',    grade: 'C',   attackType: 'passive'  },
  { label: 'Iron Resolve',               weight: 1, element: 'Neutral',   grade: 'C',   attackType: 'passive'  },
  { label: 'Ritual Circle',              weight: 1, element: 'Arcane',    grade: 'C',   attackType: 'summon'   },
  { label: 'Prismatic Spray',            weight: 1, element: 'Arcane',    grade: 'C',   attackType: 'aoe'      },
  { label: 'Toxin Resistance',           weight: 1, element: 'Poison',    grade: 'C',   attackType: 'passive'  },
  { label: 'Scavenge Protocol',          weight: 1, element: 'Neutral',   grade: 'C',   attackType: 'passive'  },
  { label: "Hunter's Instinct",          weight: 1, element: 'Nature',    grade: 'C',   attackType: 'passive'  },
  { label: 'Blade Dancing',              weight: 1, element: 'Wind',      grade: 'C',   attackType: 'buff'     },
  { label: 'Flash Step',                 weight: 1, element: 'Wind',      grade: 'C',   attackType: 'buff'     },
  { label: 'Iron Body',                  weight: 1, element: 'Metal',     grade: 'C',   attackType: 'passive'  },
  { label: 'Feral Senses',               weight: 1, element: 'Nature',    grade: 'C',   attackType: 'passive'  },

  // ── D TIER (70) — uncommon power ──
  { label: 'Evasion',                    weight: 1, element: 'Shadow',    grade: 'D',   attackType: 'passive'  },
  { label: 'Cunning Action',             weight: 1, element: 'Shadow',    grade: 'D',   attackType: 'passive'  },
  { label: 'Uncanny Dodge',              weight: 1, element: 'Shadow',    grade: 'D',   attackType: 'passive'  },
  { label: 'Quick Draw',                 weight: 1, element: 'Neutral',   grade: 'D',   attackType: 'passive'  },
  { label: 'Adaptability',               weight: 1, element: 'Neutral',   grade: 'D',   attackType: 'passive'  },
  { label: 'Iron Will',                  weight: 1, element: 'Neutral',   grade: 'D',   attackType: 'passive'  },
  { label: 'Stubborn Survival',          weight: 1, element: 'Neutral',   grade: 'D',   attackType: 'passive'  },
  { label: 'Danger Sense',               weight: 1, element: 'Psychic',   grade: 'D',   attackType: 'passive'  },
  { label: 'Pain Push',                  weight: 1, element: 'Neutral',   grade: 'D',   attackType: 'passive'  },
  { label: 'Primal Instinct',            weight: 1, element: 'Nature',    grade: 'D',   attackType: 'passive'  },
  { label: 'Relentless Stand',           weight: 1, element: 'Neutral',   grade: 'D',   attackType: 'passive'  },
  { label: 'Hardy Constitution',         weight: 1, element: 'Nature',    grade: 'D',   attackType: 'passive'  },
  { label: 'Bloodlust',                  weight: 1, element: 'Blood',     grade: 'D',   attackType: 'buff'     },
  { label: 'Pain Immunity',              weight: 1, element: 'Neutral',   grade: 'D',   attackType: 'passive'  },
  { label: 'Savage Fortitude',           weight: 1, element: 'Neutral',   grade: 'D',   attackType: 'passive'  },
  { label: 'Reckless Abandon',           weight: 1, element: 'Chaos',     grade: 'D',   attackType: 'buff'     },
  { label: 'Carnage Sense',              weight: 1, element: 'Blood',     grade: 'D',   attackType: 'passive'  },
  { label: 'Darkness Feel',              weight: 1, element: 'Shadow',    grade: 'D',   attackType: 'passive'  },
  { label: 'Pack Tactics',               weight: 1, element: 'Neutral',   grade: 'D',   attackType: 'buff'     },
  { label: 'Snarl',                      weight: 1, element: 'Nature',    grade: 'D',   attackType: 'debuff'   },
  { label: 'Tackle',                     weight: 1, element: 'Neutral',   grade: 'D',   attackType: 'attack'   },
  { label: 'Pounce',                     weight: 1, element: 'Nature',    grade: 'D',   attackType: 'attack'   },
  { label: 'Camouflage',                 weight: 1, element: 'Nature',    grade: 'D',   attackType: 'buff'     },
  { label: 'Burrow',                     weight: 1, element: 'Earth',     grade: 'D',   attackType: 'buff'     },
  { label: 'Aquatic Breathing',          weight: 1, element: 'Water',     grade: 'D',   attackType: 'passive'  },
  { label: 'Tree Climbing',              weight: 1, element: 'Nature',    grade: 'D',   attackType: 'passive'  },
  { label: 'Swarm Form',                 weight: 1, element: 'Nature',    grade: 'D',   attackType: 'buff'     },
  { label: 'Echolocation',               weight: 1, element: 'Sound',     grade: 'D',   attackType: 'passive'  },
  { label: 'Heat Sense',                 weight: 1, element: 'Fire',      grade: 'D',   attackType: 'passive'  },
  { label: 'Cold Resistance',            weight: 1, element: 'Ice',       grade: 'D',   attackType: 'passive'  },
  { label: 'Fire Resistance',            weight: 1, element: 'Fire',      grade: 'D',   attackType: 'passive'  },
  { label: 'Acid Resistance',            weight: 1, element: 'Poison',    grade: 'D',   attackType: 'passive'  },
  { label: 'Holy Resilience',            weight: 1, element: 'Light',     grade: 'D',   attackType: 'passive'  },
  { label: 'Dark Resistance',            weight: 1, element: 'Shadow',    grade: 'D',   attackType: 'passive'  },
  { label: 'Toughened Skin',             weight: 1, element: 'Neutral',   grade: 'D',   attackType: 'passive'  },
  { label: 'Natural Armor',              weight: 1, element: 'Nature',    grade: 'D',   attackType: 'passive'  },
  { label: 'Trap Sense',                 weight: 1, element: 'Neutral',   grade: 'D',   attackType: 'passive'  },
  { label: 'Foraging',                   weight: 1, element: 'Nature',    grade: 'D',   attackType: 'passive'  },
  { label: 'Night Vision',               weight: 1, element: 'Shadow',    grade: 'D',   attackType: 'passive'  },
  { label: 'Keen Nose',                  weight: 1, element: 'Nature',    grade: 'D',   attackType: 'passive'  },
  { label: 'Low Light Vision',           weight: 1, element: 'Shadow',    grade: 'D',   attackType: 'passive'  },
  { label: 'Tremorsense',                weight: 1, element: 'Earth',     grade: 'D',   attackType: 'passive'  },
  { label: 'Combat Hardening',           weight: 1, element: 'Neutral',   grade: 'D',   attackType: 'passive'  },
  { label: 'Battlefield Awareness',      weight: 1, element: 'Neutral',   grade: 'D',   attackType: 'passive'  },
  { label: 'Iron Gut',                   weight: 1, element: 'Neutral',   grade: 'D',   attackType: 'passive'  },
  { label: 'Weapon Affinity',            weight: 1, element: 'Neutral',   grade: 'D',   attackType: 'passive'  },
  { label: 'Shield Expertise',           weight: 1, element: 'Light',     grade: 'D',   attackType: 'passive'  },
  { label: 'Mounted Prowess',            weight: 1, element: 'Neutral',   grade: 'D',   attackType: 'passive'  },
  { label: 'Light Footing',              weight: 1, element: 'Wind',      grade: 'D',   attackType: 'passive'  },
  { label: 'Quick Recovery',             weight: 1, element: 'Nature',    grade: 'D',   attackType: 'passive'  },
  { label: 'Veteran Edge',               weight: 1, element: 'Neutral',   grade: 'D',   attackType: 'passive'  },
  { label: 'Tactical Awareness',         weight: 1, element: 'Neutral',   grade: 'D',   attackType: 'passive'  },
  { label: 'Ambush Training',            weight: 1, element: 'Shadow',    grade: 'D',   attackType: 'passive'  },
  { label: 'Enduring March',             weight: 1, element: 'Neutral',   grade: 'D',   attackType: 'passive'  },
  { label: 'Strong Grip',                weight: 1, element: 'Neutral',   grade: 'D',   attackType: 'passive'  },
  { label: 'Intimidate',                 weight: 1, element: 'Psychic',   grade: 'D',   attackType: 'debuff'   },
  { label: 'Provoke',                    weight: 1, element: 'Fire',      grade: 'D',   attackType: 'debuff'   },
  { label: 'Rally Cry (Minor)',           weight: 1, element: 'Sound',     grade: 'D',   attackType: 'buff'     },
  { label: 'Focus Stance',               weight: 1, element: 'Neutral',   grade: 'D',   attackType: 'buff'     },
  { label: 'Defensive Stance',           weight: 1, element: 'Neutral',   grade: 'D',   attackType: 'buff'     },
  { label: 'Weapon Throw',               weight: 1, element: 'Neutral',   grade: 'D',   attackType: 'attack'   },
  { label: 'Trip Attack',                weight: 1, element: 'Neutral',   grade: 'D',   attackType: 'attack'   },
  { label: 'Disarm',                     weight: 1, element: 'Neutral',   grade: 'D',   attackType: 'debuff'   },
  { label: 'Grapple Mastery',            weight: 1, element: 'Neutral',   grade: 'D',   attackType: 'attack'   },
  { label: 'Headbutt',                   weight: 1, element: 'Neutral',   grade: 'D',   attackType: 'attack'   },
  { label: 'Shoulder Bash',              weight: 1, element: 'Neutral',   grade: 'D',   attackType: 'attack'   },
  { label: 'Footwork',                   weight: 1, element: 'Wind',      grade: 'D',   attackType: 'passive'  },
  { label: 'Parting Blow',               weight: 1, element: 'Neutral',   grade: 'D',   attackType: 'attack'   },
  { label: 'Overpower',                  weight: 1, element: 'Neutral',   grade: 'D',   attackType: 'attack'   },
  { label: 'Pin',                        weight: 1, element: 'Neutral',   grade: 'D',   attackType: 'debuff'   },

  // ── E TIER (70) — weak power ──
  { label: 'Minor Healing',              weight: 1, element: 'Nature',    grade: 'E',   attackType: 'heal'     },
  { label: 'Dim Light Conjure',          weight: 1, element: 'Light',     grade: 'E',   attackType: 'buff'     },
  { label: 'Small Spark',                weight: 1, element: 'Lightning', grade: 'E',   attackType: 'attack'   },
  { label: 'Pebble Toss',                weight: 1, element: 'Earth',     grade: 'E',   attackType: 'attack'   },
  { label: 'Weak Acid Spit',             weight: 1, element: 'Poison',    grade: 'E',   attackType: 'debuff'   },
  { label: 'Minor Telepathy',            weight: 1, element: 'Psychic',   grade: 'E',   attackType: 'passive'  },
  { label: 'Shadow Whisper',             weight: 1, element: 'Shadow',    grade: 'E',   attackType: 'debuff'   },
  { label: 'Ember Touch',                weight: 1, element: 'Fire',      grade: 'E',   attackType: 'attack'   },
  { label: 'Cool Breeze',                weight: 1, element: 'Wind',      grade: 'E',   attackType: 'buff'     },
  { label: 'Slippery Field',             weight: 1, element: 'Water',     grade: 'E',   attackType: 'debuff'   },
  { label: 'Minor Shapeshift',           weight: 1, element: 'Nature',    grade: 'E',   attackType: 'buff'     },
  { label: 'Weak Compulsion',            weight: 1, element: 'Psychic',   grade: 'E',   attackType: 'debuff'   },
  { label: 'Faint Glow',                 weight: 1, element: 'Light',     grade: 'E',   attackType: 'buff'     },
  { label: 'Muffled Step',               weight: 1, element: 'Shadow',    grade: 'E',   attackType: 'buff'     },
  { label: 'Tiny Tremor',                weight: 1, element: 'Earth',     grade: 'E',   attackType: 'attack'   },
  { label: 'Leaf Shield',                weight: 1, element: 'Nature',    grade: 'E',   attackType: 'buff'     },
  { label: 'Sour Stench',                weight: 1, element: 'Poison',    grade: 'E',   attackType: 'debuff'   },
  { label: 'Cold Snap',                  weight: 1, element: 'Ice',       grade: 'E',   attackType: 'attack'   },
  { label: 'Sparkling Aura',             weight: 1, element: 'Light',     grade: 'E',   attackType: 'buff'     },
  { label: 'Phantom Whistle',            weight: 1, element: 'Sound',     grade: 'E',   attackType: 'debuff'   },
  { label: 'Minor Illusion',             weight: 1, element: 'Arcane',    grade: 'E',   attackType: 'debuff'   },
  { label: 'Dowsing',                    weight: 1, element: 'Arcane',    grade: 'E',   attackType: 'passive'  },
  { label: 'Weak Barrier',               weight: 1, element: 'Arcane',    grade: 'E',   attackType: 'buff'     },
  { label: 'Basic Levitation',           weight: 1, element: 'Gravity',   grade: 'E',   attackType: 'buff'     },
  { label: 'Whisper Sending',            weight: 1, element: 'Sound',     grade: 'E',   attackType: 'buff'     },
  { label: 'Mud Ball',                   weight: 1, element: 'Earth',     grade: 'E',   attackType: 'attack'   },
  { label: 'Fog Breath',                 weight: 1, element: 'Water',     grade: 'E',   attackType: 'debuff'   },
  { label: 'Trembling Touch',            weight: 1, element: 'Earth',     grade: 'E',   attackType: 'debuff'   },
  { label: 'Dull Ache',                  weight: 1, element: 'Psychic',   grade: 'E',   attackType: 'debuff'   },
  { label: 'Faint Curse',                weight: 1, element: 'Shadow',    grade: 'E',   attackType: 'debuff'   },
  { label: 'Static Touch',               weight: 1, element: 'Lightning', grade: 'E',   attackType: 'debuff'   },
  { label: 'Weak Bind',                  weight: 1, element: 'Arcane',    grade: 'E',   attackType: 'debuff'   },
  { label: 'Itch Inducement',            weight: 1, element: 'Nature',    grade: 'E',   attackType: 'debuff'   },
  { label: 'Minor Slow',                 weight: 1, element: 'Time',      grade: 'E',   attackType: 'debuff'   },
  { label: 'Puff of Smoke',              weight: 1, element: 'Shadow',    grade: 'E',   attackType: 'buff'     },
  { label: 'Stumble Field',              weight: 1, element: 'Arcane',    grade: 'E',   attackType: 'debuff'   },
  { label: 'Blurry Vision',              weight: 1, element: 'Psychic',   grade: 'E',   attackType: 'debuff'   },
  { label: 'Mild Nausea',                weight: 1, element: 'Poison',    grade: 'E',   attackType: 'debuff'   },
  { label: 'Weak Push',                  weight: 1, element: 'Wind',      grade: 'E',   attackType: 'attack'   },
  { label: 'Slippery Hands',             weight: 1, element: 'Water',     grade: 'E',   attackType: 'debuff'   },
  { label: 'Dim Flame',                  weight: 1, element: 'Fire',      grade: 'E',   attackType: 'attack'   },
  { label: 'Brittle Ground',             weight: 1, element: 'Earth',     grade: 'E',   attackType: 'debuff'   },
  { label: 'Minor Chill',                weight: 1, element: 'Ice',       grade: 'E',   attackType: 'debuff'   },
  { label: 'Damp Aura',                  weight: 1, element: 'Water',     grade: 'E',   attackType: 'debuff'   },
  { label: 'Hair Stand',                 weight: 1, element: 'Lightning', grade: 'E',   attackType: 'debuff'   },
  { label: 'Pale Flash',                 weight: 1, element: 'Light',     grade: 'E',   attackType: 'attack'   },
  { label: 'Faint Echo',                 weight: 1, element: 'Sound',     grade: 'E',   attackType: 'debuff'   },
  { label: 'Vague Feeling',              weight: 1, element: 'Psychic',   grade: 'E',   attackType: 'passive'  },
  { label: 'Weak Bolt',                  weight: 1, element: 'Lightning', grade: 'E',   attackType: 'attack'   },
  { label: 'Wilt Touch',                 weight: 1, element: 'Nature',    grade: 'E',   attackType: 'debuff'   },
  { label: 'Minor Drain',                weight: 1, element: 'Soul',      grade: 'E',   attackType: 'debuff'   },
  { label: 'Limp Shadow',                weight: 1, element: 'Shadow',    grade: 'E',   attackType: 'debuff'   },
  { label: 'Fumble Hex',                 weight: 1, element: 'Chaos',     grade: 'E',   attackType: 'debuff'   },
  { label: 'Minor Fear',                 weight: 1, element: 'Psychic',   grade: 'E',   attackType: 'debuff'   },
  { label: 'Faint Howl',                 weight: 1, element: 'Sound',     grade: 'E',   attackType: 'debuff'   },
  { label: 'Weak Gravity Shift',         weight: 1, element: 'Gravity',   grade: 'E',   attackType: 'debuff'   },
  { label: 'Lackluster Bolt',            weight: 1, element: 'Arcane',    grade: 'E',   attackType: 'attack'   },
  { label: 'Puddle Conjure',             weight: 1, element: 'Water',     grade: 'E',   attackType: 'buff'     },
  { label: 'Minor Rust',                 weight: 1, element: 'Metal',     grade: 'E',   attackType: 'debuff'   },
  { label: 'Feeble Shock',               weight: 1, element: 'Lightning', grade: 'E',   attackType: 'attack'   },
  { label: 'Soft Wind',                  weight: 1, element: 'Wind',      grade: 'E',   attackType: 'buff'     },
  { label: 'Dim Soul Sight',             weight: 1, element: 'Soul',      grade: 'E',   attackType: 'passive'  },
  { label: 'Weak Blood Sense',           weight: 1, element: 'Blood',     grade: 'E',   attackType: 'passive'  },
  { label: 'Crack Stone',                weight: 1, element: 'Earth',     grade: 'E',   attackType: 'attack'   },
  { label: 'Paper Cut Mastery',          weight: 1, element: 'Metal',     grade: 'E',   attackType: 'attack'   },
  { label: 'Faint Psychometry',          weight: 1, element: 'Psychic',   grade: 'E',   attackType: 'passive'  },
  { label: 'Mild Magnetism',             weight: 1, element: 'Metal',     grade: 'E',   attackType: 'buff'     },
  { label: 'Weak Time Sense',            weight: 1, element: 'Time',      grade: 'E',   attackType: 'passive'  },
  { label: 'Dim Aura',                   weight: 1, element: 'Arcane',    grade: 'E',   attackType: 'passive'  },
  { label: 'Faint Cosmic Awareness',     weight: 1, element: 'Cosmic',    grade: 'E',   attackType: 'passive'  },

  // ── F TIER (80) — common / joke powers ──
  { label: 'Slightly Louder Voice',                              weight: 1, element: 'Sound',   grade: 'F', attackType: 'passive' },
  { label: 'Ability to Open Jars',                              weight: 1, element: 'Neutral',  grade: 'F', attackType: 'passive' },
  { label: 'Perfect Parking',                                   weight: 1, element: 'Neutral',  grade: 'F', attackType: 'passive' },
  { label: 'Uncanny Balance',                                   weight: 1, element: 'Wind',     grade: 'F', attackType: 'passive' },
  { label: 'Knowing When Food is Done',                         weight: 1, element: 'Fire',     grade: 'F', attackType: 'passive' },
  { label: 'Minor Warmth Generation',                           weight: 1, element: 'Fire',     grade: 'F', attackType: 'passive' },
  { label: 'Always Finding Parking',                            weight: 1, element: 'Neutral',  grade: 'F', attackType: 'passive' },
  { label: 'Mild Stench Immunity',                              weight: 1, element: 'Neutral',  grade: 'F', attackType: 'passive' },
  { label: "Dog's Sense of Direction",                          weight: 1, element: 'Nature',   grade: 'F', attackType: 'passive' },
  { label: 'Slightly Better at Math',                           weight: 1, element: 'Arcane',   grade: 'F', attackType: 'passive' },
  { label: 'Reading Very Fast',                                 weight: 1, element: 'Arcane',   grade: 'F', attackType: 'passive' },
  { label: 'Never Gets Lost (Indoors)',                         weight: 1, element: 'Neutral',  grade: 'F', attackType: 'passive' },
  { label: 'Can Communicate With Fish (Badly)',                 weight: 1, element: 'Water',    grade: 'F', attackType: 'passive' },
  { label: 'Mild Clairvoyance (Only Trivia)',                   weight: 1, element: 'Psychic',  grade: 'F', attackType: 'passive' },
  { label: 'Knows What the Weather Is (Wrong)',                 weight: 1, element: 'Wind',     grade: 'F', attackType: 'passive' },
  { label: 'Can Whistle Really Well',                           weight: 1, element: 'Sound',    grade: 'F', attackType: 'passive' },
  { label: 'Infinite Patience (For One Thing)',                 weight: 1, element: 'Neutral',  grade: 'F', attackType: 'passive' },
  { label: 'Never Burns Toast',                                 weight: 1, element: 'Fire',     grade: 'F', attackType: 'passive' },
  { label: 'Always Finds a Sock',                               weight: 1, element: 'Neutral',  grade: 'F', attackType: 'passive' },
  { label: 'Can Smell Rain Coming',                             weight: 1, element: 'Water',    grade: 'F', attackType: 'passive' },
  { label: 'Slightly Better Aim',                               weight: 1, element: 'Neutral',  grade: 'F', attackType: 'passive' },
  { label: 'Speaks to Insects (They Ignore You)',               weight: 1, element: 'Nature',   grade: 'F', attackType: 'passive' },
  { label: 'Knows the Lyrics to Every Song (But Slightly Wrong)', weight: 1, element: 'Sound', grade: 'F', attackType: 'passive' },
  { label: 'Can Predict Coin Flips (30% of the Time)',          weight: 1, element: 'Chaos',    grade: 'F', attackType: 'passive' },
  { label: 'Mild Hypnosis (Only Works on Pigeons)',             weight: 1, element: 'Psychic',  grade: 'F', attackType: 'passive' },
  { label: 'Alarm Clock Body',                                  weight: 1, element: 'Time',     grade: 'F', attackType: 'passive' },
  { label: 'Always Right About the Time',                       weight: 1, element: 'Time',     grade: 'F', attackType: 'passive' },
  { label: 'Mild Telepathy (Only from Cats)',                   weight: 1, element: 'Psychic',  grade: 'F', attackType: 'passive' },
  { label: 'Can Juggle Three Things (Barely)',                  weight: 1, element: 'Neutral',  grade: 'F', attackType: 'passive' },
  { label: 'Perfectly Mediocre Everything',                     weight: 1, element: 'Neutral',  grade: 'F', attackType: 'passive' },
  { label: 'Stubbed Toe Immunity',                              weight: 1, element: 'Neutral',  grade: 'F', attackType: 'passive' },
  { label: 'Slightly Taller in the Morning',                    weight: 1, element: 'Neutral',  grade: 'F', attackType: 'passive' },
  { label: 'Always Has Exact Change',                           weight: 1, element: 'Neutral',  grade: 'F', attackType: 'passive' },
  { label: 'Can Find Any Remote Control',                       weight: 1, element: 'Neutral',  grade: 'F', attackType: 'passive' },
  { label: 'Never Forgets a Name (Only First Names)',           weight: 1, element: 'Psychic',  grade: 'F', attackType: 'passive' },
  { label: 'Can Open Ketchup Bottles Instantly',                weight: 1, element: 'Neutral',  grade: 'F', attackType: 'passive' },
  { label: 'Magnetic for Good Parking Spots',                   weight: 1, element: 'Metal',    grade: 'F', attackType: 'passive' },
  { label: 'Minor Shadow Puppetry',                             weight: 1, element: 'Shadow',   grade: 'F', attackType: 'passive' },
  { label: 'Can Hum Surprisingly Well',                         weight: 1, element: 'Sound',    grade: 'F', attackType: 'passive' },
  { label: 'Never Trips on Flat Surfaces',                      weight: 1, element: 'Neutral',  grade: 'F', attackType: 'passive' },
  { label: 'Can Sense When Wifi is Slow',                       weight: 1, element: 'Lightning',grade: 'F', attackType: 'passive' },
  { label: 'Remembers Every Dream (Boring Ones)',               weight: 1, element: 'Psychic',  grade: 'F', attackType: 'passive' },
  { label: 'Power of Mild Suggestion',                          weight: 1, element: 'Psychic',  grade: 'F', attackType: 'passive' },
  { label: 'Can Fold Laundry Very Fast',                        weight: 1, element: 'Neutral',  grade: 'F', attackType: 'passive' },
  { label: 'Slightly Better Handwriting',                       weight: 1, element: 'Neutral',  grade: 'F', attackType: 'passive' },
  { label: 'Parallel Parking Mastery',                          weight: 1, element: 'Neutral',  grade: 'F', attackType: 'passive' },
  { label: "Can See 10 Minutes into the Future (Only Traffic)", weight: 1, element: 'Time',     grade: 'F', attackType: 'passive' },
  { label: 'Knows When Pasta is Al Dente',                      weight: 1, element: 'Neutral',  grade: 'F', attackType: 'passive' },
  { label: 'Super Mediocrity Aura',                             weight: 1, element: 'Neutral',  grade: 'F', attackType: 'passive' },
  { label: 'Mild Aura of Competence',                           weight: 1, element: 'Light',    grade: 'F', attackType: 'passive' },
  { label: 'Always Lands Butter Side Up',                       weight: 1, element: 'Chaos',    grade: 'F', attackType: 'passive' },
  { label: 'Speaks Fluent Pigeon',                              weight: 1, element: 'Nature',   grade: 'F', attackType: 'passive' },
  { label: 'Paper Airplane Mastery',                            weight: 1, element: 'Wind',     grade: 'F', attackType: 'passive' },
  { label: 'Power of Not Spilling Drinks',                      weight: 1, element: 'Water',    grade: 'F', attackType: 'passive' },
  { label: 'Strong Opinions about Cheese',                      weight: 1, element: 'Neutral',  grade: 'F', attackType: 'passive' },
  { label: 'Mild Magnetism (For Keys)',                         weight: 1, element: 'Metal',    grade: 'F', attackType: 'passive' },
  { label: 'Can Sneeze Exactly Once',                           weight: 1, element: 'Wind',     grade: 'F', attackType: 'passive' },
  { label: 'Socks Always Match',                                weight: 1, element: 'Neutral',  grade: 'F', attackType: 'passive' },
  { label: 'Minor Thermostat Manipulation',                     weight: 1, element: 'Fire',     grade: 'F', attackType: 'passive' },
  { label: 'Knows When It Will Rain (Mostly)',                  weight: 1, element: 'Water',    grade: 'F', attackType: 'passive' },
  { label: 'Mild Ability to Identify Cheese by Smell',         weight: 1, element: 'Neutral',  grade: 'F', attackType: 'passive' },
  { label: 'Power to Always Get the Last Slice',               weight: 1, element: 'Chaos',    grade: 'F', attackType: 'passive' },
  { label: 'Very Dry Hands',                                   weight: 1, element: 'Neutral',  grade: 'F', attackType: 'passive' },
  { label: 'Slightly Better Handshake',                        weight: 1, element: 'Neutral',  grade: 'F', attackType: 'passive' },
  { label: 'Power of Being Kind of Alright',                   weight: 1, element: 'Neutral',  grade: 'F', attackType: 'passive' },
  { label: "Can Open Pickle Jars But That's It",               weight: 1, element: 'Neutral',  grade: 'F', attackType: 'passive' },
  { label: 'Mild Snoring Immunity',                            weight: 1, element: 'Sound',    grade: 'F', attackType: 'passive' },
  { label: 'Always Finds the TV Remote',                       weight: 1, element: 'Neutral',  grade: 'F', attackType: 'passive' },
  { label: 'Superior at Untying Knots',                        weight: 1, element: 'Neutral',  grade: 'F', attackType: 'passive' },
  { label: 'Can Successfully Guess Pizza Toppings',            weight: 1, element: 'Neutral',  grade: 'F', attackType: 'passive' },
  { label: 'Nose for Wi-Fi Passwords',                         weight: 1, element: 'Arcane',   grade: 'F', attackType: 'passive' },
  { label: 'Mild Aura of Being Slightly Less Annoying',        weight: 1, element: 'Neutral',  grade: 'F', attackType: 'passive' },
  { label: 'Immunity to Door Stubbing',                        weight: 1, element: 'Neutral',  grade: 'F', attackType: 'passive' },
  { label: 'Power of Adequate Mediocrity',                     weight: 1, element: 'Neutral',  grade: 'F', attackType: 'passive' },
  { label: 'Can Sense When a Movie Is About to Get Good',      weight: 1, element: 'Psychic',  grade: 'F', attackType: 'passive' },
  { label: 'Power of Knowing Exactly Which Line Will Move Fastest', weight: 1, element: 'Time', grade: 'F', attackType: 'passive' },
  { label: 'Minor Sandwich Optimization',                      weight: 1, element: 'Neutral',  grade: 'F', attackType: 'passive' },
  { label: 'Can Name Any Movie by 5 Seconds',                  weight: 1, element: 'Sound',    grade: 'F', attackType: 'passive' },
  { label: 'Power to Be Remarkably Average',                   weight: 1, element: 'Neutral',  grade: 'F', attackType: 'passive' },
  { label: 'The Ability to Find Parking (Sometimes)',          weight: 1, element: 'Neutral',  grade: 'F', attackType: 'passive' },
]
