import type { FlavorLabel } from './types'

export const powerMasteryLabels: FlavorLabel[] = [
  // F- (score: 2)
  { label: 'Accidentally Powers Off Own Ability', weight: 1, tier: 'F-', score: 2, color: 'var(--tier-f-minus)' },
  { label: 'Power Activates During Sneezes Only', weight: 1, tier: 'F-', score: 2, color: 'var(--tier-f-minus)' },
  { label: 'Unsure If They Even Have Powers', weight: 1, tier: 'F-', score: 2, color: 'var(--tier-f-minus)' },
  { label: 'Ability Triggers at Worst Possible Moments', weight: 1, tier: 'F-', score: 2, color: 'var(--tier-f-minus)' },
  { label: 'Has Used Power Once — It Was an Accident', weight: 1, tier: 'F-', score: 2, color: 'var(--tier-f-minus)' },
  { label: 'Can\'t Tell When Power Is Active', weight: 1, tier: 'F-', score: 2, color: 'var(--tier-f-minus)' },
  { label: 'Power Argues Back When Invoked', weight: 1, tier: 'F-', score: 2, color: 'var(--tier-f-minus)' },
  { label: 'Mastery: Does Not Apply', weight: 1, tier: 'F-', score: 2, color: 'var(--tier-f-minus)' },
  { label: 'Power Goes Rogue in Stressful Meetings', weight: 1, tier: 'F-', score: 2, color: 'var(--tier-f-minus)' },
  { label: 'Once Activated Power in a Library — Regrets It', weight: 1, tier: 'F-', score: 2, color: 'var(--tier-f-minus)' },
  { label: 'Forgets Power Exists Until It Causes Problems', weight: 1, tier: 'F-', score: 2, color: 'var(--tier-f-minus)' },
  { label: 'Power Control: Theoretical', weight: 1, tier: 'F-', score: 2, color: 'var(--tier-f-minus)' },
  { label: 'Own Power Doesn\'t Trust Them', weight: 1, tier: 'F-', score: 2, color: 'var(--tier-f-minus)' },
  { label: 'Has Only Achieved Desired Effect Once — By Accident', weight: 1, tier: 'F-', score: 2, color: 'var(--tier-f-minus)' },
  { label: 'More Danger to Self Than Others', weight: 1, tier: 'F-', score: 2, color: 'var(--tier-f-minus)' },
  { label: 'Power Frequently Confused About Its Own Direction', weight: 1, tier: 'F-', score: 2, color: 'var(--tier-f-minus)' },
  { label: 'Ability Requires Two Hours of Focus to Do Nothing', weight: 1, tier: 'F-', score: 2, color: 'var(--tier-f-minus)' },
  { label: 'Power Fires Backward More Often Than Not', weight: 1, tier: 'F-', score: 2, color: 'var(--tier-f-minus)' },
  { label: 'Hasn\'t Found the "On" Switch Yet', weight: 1, tier: 'F-', score: 2, color: 'var(--tier-f-minus)' },
  { label: 'Power and User Are Not on Speaking Terms', weight: 1, tier: 'F-', score: 2, color: 'var(--tier-f-minus)' },

  // F (score: 5)
  { label: 'Barely Controlled Ability', weight: 1, tier: 'F', score: 5, color: 'var(--tier-f)' },
  { label: 'Can Activate on Purpose — Sometimes', weight: 1, tier: 'F', score: 5, color: 'var(--tier-f)' },
  { label: 'Power Leaks Occasionally', weight: 1, tier: 'F', score: 5, color: 'var(--tier-f)' },
  { label: 'Activation Requires Full Concentration', weight: 1, tier: 'F', score: 5, color: 'var(--tier-f)' },
  { label: 'Shuts Off When Distracted', weight: 1, tier: 'F', score: 5, color: 'var(--tier-f)' },
  { label: 'Control Window: 3 Seconds', weight: 1, tier: 'F', score: 5, color: 'var(--tier-f)' },
  { label: 'Has Learned What Not to Do With It', weight: 1, tier: 'F', score: 5, color: 'var(--tier-f)' },
  { label: 'Power Active — Aim: Debatable', weight: 1, tier: 'F', score: 5, color: 'var(--tier-f)' },
  { label: 'Can Hold It Together for Short Bursts', weight: 1, tier: 'F', score: 5, color: 'var(--tier-f)' },
  { label: 'Training Producing Marginal Results', weight: 1, tier: 'F', score: 5, color: 'var(--tier-f)' },
  { label: 'Power Active — Direction: 50/50', weight: 1, tier: 'F', score: 5, color: 'var(--tier-f)' },
  { label: 'Has Read the Manual — Still Confused', weight: 1, tier: 'F', score: 5, color: 'var(--tier-f)' },
  { label: 'Can Summon; Cannot Direct', weight: 1, tier: 'F', score: 5, color: 'var(--tier-f)' },
  { label: 'Power Responds to Strong Emotions Only', weight: 1, tier: 'F', score: 5, color: 'var(--tier-f)' },
  { label: 'Reliable in Safe Conditions', weight: 1, tier: 'F', score: 5, color: 'var(--tier-f)' },
  { label: 'In Emergencies: Uncontrollable', weight: 1, tier: 'F', score: 5, color: 'var(--tier-f)' },
  { label: 'Power Control: Apprentice Level, Day 1', weight: 1, tier: 'F', score: 5, color: 'var(--tier-f)' },
  { label: 'Occasional Unintentional Mastery', weight: 1, tier: 'F', score: 5, color: 'var(--tier-f)' },
  { label: 'Results Vary Significantly by Mood', weight: 1, tier: 'F', score: 5, color: 'var(--tier-f)' },
  { label: 'Power Works — When It Wants To', weight: 1, tier: 'F', score: 5, color: 'var(--tier-f)' },

  // F+ (score: 8)
  { label: 'Basic Power Control', weight: 1, tier: 'F+', score: 8, color: 'var(--tier-f-plus)' },
  { label: 'Can Activate and Deactivate Reliably', weight: 1, tier: 'F+', score: 8, color: 'var(--tier-f-plus)' },
  { label: 'Limited Scope — Good Within It', weight: 1, tier: 'F+', score: 8, color: 'var(--tier-f-plus)' },
  { label: 'Maintains Control Under Calm Conditions', weight: 1, tier: 'F+', score: 8, color: 'var(--tier-f-plus)' },
  { label: 'Learning to Modulate Output', weight: 1, tier: 'F+', score: 8, color: 'var(--tier-f-plus)' },
  { label: 'Control Improving With Each Session', weight: 1, tier: 'F+', score: 8, color: 'var(--tier-f-plus)' },
  { label: 'Can Use Power Without Breaking Things (Usually)', weight: 1, tier: 'F+', score: 8, color: 'var(--tier-f-plus)' },
  { label: 'Power Follows Intent More Often Than Not', weight: 1, tier: 'F+', score: 8, color: 'var(--tier-f-plus)' },
  { label: 'Mastery: Early Stages, Promising', weight: 1, tier: 'F+', score: 8, color: 'var(--tier-f-plus)' },
  { label: 'Power Cooperates on Calm Days', weight: 1, tier: 'F+', score: 8, color: 'var(--tier-f-plus)' },
  { label: 'Consistent in Practice; Shaky in Combat', weight: 1, tier: 'F+', score: 8, color: 'var(--tier-f-plus)' },
  { label: 'Can Focus Output on Specific Targets', weight: 1, tier: 'F+', score: 8, color: 'var(--tier-f-plus)' },
  { label: 'No Longer Injures Themselves Weekly', weight: 1, tier: 'F+', score: 8, color: 'var(--tier-f-plus)' },
  { label: 'Power Responds to Intention Predictably', weight: 1, tier: 'F+', score: 8, color: 'var(--tier-f-plus)' },
  { label: 'Passable in Controlled Settings', weight: 1, tier: 'F+', score: 8, color: 'var(--tier-f-plus)' },
  { label: 'Knows the Basic Range and Limits', weight: 1, tier: 'F+', score: 8, color: 'var(--tier-f-plus)' },
  { label: 'Can Sustain Use for Extended Periods', weight: 1, tier: 'F+', score: 8, color: 'var(--tier-f-plus)' },
  { label: 'Power Running With Minimal Accidents', weight: 1, tier: 'F+', score: 8, color: 'var(--tier-f-plus)' },
  { label: 'Overcomes the Learning Curve Eventually', weight: 1, tier: 'F+', score: 8, color: 'var(--tier-f-plus)' },
  { label: 'Understands the Power Enough to Not Fear It', weight: 1, tier: 'F+', score: 8, color: 'var(--tier-f-plus)' },

  // E- (score: 11)
  { label: 'Steady Power Control', weight: 1, tier: 'E-', score: 11, color: 'var(--tier-e-minus)' },
  { label: 'Power Active and Reliable in Most Scenarios', weight: 1, tier: 'E-', score: 11, color: 'var(--tier-e-minus)' },
  { label: 'Adjusts Output Actively', weight: 1, tier: 'E-', score: 11, color: 'var(--tier-e-minus)' },
  { label: 'Power Feels Like a Second Limb', weight: 1, tier: 'E-', score: 11, color: 'var(--tier-e-minus)' },
  { label: 'Control Doesn\'t Break Under Mild Pressure', weight: 1, tier: 'E-', score: 11, color: 'var(--tier-e-minus)' },
  { label: 'Can Redirect Mid-Use Effectively', weight: 1, tier: 'E-', score: 11, color: 'var(--tier-e-minus)' },
  { label: 'Knows How to Suppress When Needed', weight: 1, tier: 'E-', score: 11, color: 'var(--tier-e-minus)' },
  { label: 'Mastery: Intermediate, Noticeably Skilled', weight: 1, tier: 'E-', score: 11, color: 'var(--tier-e-minus)' },
  { label: 'Power Works Well in Combat Settings', weight: 1, tier: 'E-', score: 11, color: 'var(--tier-e-minus)' },
  { label: 'Can Layer Multiple Uses Simultaneously', weight: 1, tier: 'E-', score: 11, color: 'var(--tier-e-minus)' },
  { label: 'Control Maintained Under Emotional Duress', weight: 1, tier: 'E-', score: 11, color: 'var(--tier-e-minus)' },
  { label: 'Power Precision: Improving Rapidly', weight: 1, tier: 'E-', score: 11, color: 'var(--tier-e-minus)' },
  { label: 'Rarely Overshoots Now', weight: 1, tier: 'E-', score: 11, color: 'var(--tier-e-minus)' },
  { label: 'Power Responds to Nuanced Commands', weight: 1, tier: 'E-', score: 11, color: 'var(--tier-e-minus)' },
  { label: 'Application Consistent in Variable Conditions', weight: 1, tier: 'E-', score: 11, color: 'var(--tier-e-minus)' },
  { label: 'Known for Controlled Application', weight: 1, tier: 'E-', score: 11, color: 'var(--tier-e-minus)' },
  { label: 'Can Sustain Use Across Extended Sessions', weight: 1, tier: 'E-', score: 11, color: 'var(--tier-e-minus)' },
  { label: 'Efficient Power Use — Minimal Drain', weight: 1, tier: 'E-', score: 11, color: 'var(--tier-e-minus)' },
  { label: 'Has Developed Personal Techniques', weight: 1, tier: 'E-', score: 11, color: 'var(--tier-e-minus)' },
  { label: 'Power and User Have Reached an Understanding', weight: 1, tier: 'E-', score: 11, color: 'var(--tier-e-minus)' },

  // E (score: 14)
  { label: 'Skilled Power User', weight: 1, tier: 'E', score: 14, color: 'var(--tier-e)' },
  { label: 'Precision Application in Combat', weight: 1, tier: 'E', score: 14, color: 'var(--tier-e)' },
  { label: 'Power Responds Like a Well-Trained Partner', weight: 1, tier: 'E', score: 14, color: 'var(--tier-e)' },
  { label: 'Can Hold Subtle Modulations', weight: 1, tier: 'E', score: 14, color: 'var(--tier-e)' },
  { label: 'Mastery Evident to Observers', weight: 1, tier: 'E', score: 14, color: 'var(--tier-e)' },
  { label: 'Power Output Consistent and Scalable', weight: 1, tier: 'E', score: 14, color: 'var(--tier-e)' },
  { label: 'Suppresses Entirely on Command', weight: 1, tier: 'E', score: 14, color: 'var(--tier-e)' },
  { label: 'No Unintended Activations in Months', weight: 1, tier: 'E', score: 14, color: 'var(--tier-e)' },
  { label: 'Power Precision: Surgical', weight: 1, tier: 'E', score: 14, color: 'var(--tier-e)' },
  { label: 'Can Use While Distracted — Power Doesn\'t Waver', weight: 1, tier: 'E', score: 14, color: 'var(--tier-e)' },
  { label: 'Simultaneously Applies Multiple Aspects', weight: 1, tier: 'E', score: 14, color: 'var(--tier-e)' },
  { label: 'Developed New Applications Without Training', weight: 1, tier: 'E', score: 14, color: 'var(--tier-e)' },
  { label: 'Can Feint With Power Mid-Battle', weight: 1, tier: 'E', score: 14, color: 'var(--tier-e)' },
  { label: 'Power Not Disrupted by Pain or Fear', weight: 1, tier: 'E', score: 14, color: 'var(--tier-e)' },
  { label: 'Mastery That Impresses Specialists', weight: 1, tier: 'E', score: 14, color: 'var(--tier-e)' },
  { label: 'Power Efficiency Rate: Near-Perfect', weight: 1, tier: 'E', score: 14, color: 'var(--tier-e)' },
  { label: 'Can Scale Power to the Micro Level', weight: 1, tier: 'E', score: 14, color: 'var(--tier-e)' },
  { label: 'Power Used in Creative Non-Standard Ways', weight: 1, tier: 'E', score: 14, color: 'var(--tier-e)' },
  { label: 'Maintains Full Control Under Maximum Output', weight: 1, tier: 'E', score: 14, color: 'var(--tier-e)' },
  { label: 'Power and Intent Are Perfectly Synchronized', weight: 1, tier: 'E', score: 14, color: 'var(--tier-e)' },

  // E+ (score: 17)
  { label: 'Expert Power Mastery', weight: 1, tier: 'E+', score: 17, color: 'var(--tier-e-plus)' },
  { label: 'Power Application: Flawless Under Pressure', weight: 1, tier: 'E+', score: 17, color: 'var(--tier-e-plus)' },
  { label: 'Simultaneous Multi-Target Use', weight: 1, tier: 'E+', score: 17, color: 'var(--tier-e-plus)' },
  { label: 'Uses Power at Molecular Scale Accurately', weight: 1, tier: 'E+', score: 17, color: 'var(--tier-e-plus)' },
  { label: 'Mastery Enables Abilities Within Abilities', weight: 1, tier: 'E+', score: 17, color: 'var(--tier-e-plus)' },
  { label: 'Power Doesn\'t Leak — Even Under Extreme Stress', weight: 1, tier: 'E+', score: 17, color: 'var(--tier-e-plus)' },
  { label: 'Can Weaponize Power in 3+ Ways Simultaneously', weight: 1, tier: 'E+', score: 17, color: 'var(--tier-e-plus)' },
  { label: 'Power Control: Admired by Other Power Users', weight: 1, tier: 'E+', score: 17, color: 'var(--tier-e-plus)' },
  { label: 'Can Suppress, Mirror, and Redirect in Sequence', weight: 1, tier: 'E+', score: 17, color: 'var(--tier-e-plus)' },
  { label: 'Mastery Has Unlocked Hidden Applications', weight: 1, tier: 'E+', score: 17, color: 'var(--tier-e-plus)' },
  { label: 'Power Optimization Rate: Near 100%', weight: 1, tier: 'E+', score: 17, color: 'var(--tier-e-plus)' },
  { label: 'Can Split Output Across Targets With Full Precision', weight: 1, tier: 'E+', score: 17, color: 'var(--tier-e-plus)' },
  { label: 'No Waste — Every Activation Intentional', weight: 1, tier: 'E+', score: 17, color: 'var(--tier-e-plus)' },
  { label: 'Power Responds to Thought, Not Just Intent', weight: 1, tier: 'E+', score: 17, color: 'var(--tier-e-plus)' },
  { label: 'Invented Power Techniques Others Now Study', weight: 1, tier: 'E+', score: 17, color: 'var(--tier-e-plus)' },
  { label: 'Control So Fine It Counts as Art', weight: 1, tier: 'E+', score: 17, color: 'var(--tier-e-plus)' },
  { label: 'Mastery Surpasses Their Original Teacher', weight: 1, tier: 'E+', score: 17, color: 'var(--tier-e-plus)' },
  { label: 'Power Applications: Textbook-Defying', weight: 1, tier: 'E+', score: 17, color: 'var(--tier-e-plus)' },
  { label: 'Uses Power to Counter Power Elegantly', weight: 1, tier: 'E+', score: 17, color: 'var(--tier-e-plus)' },
  { label: 'Commands Power Like a Language', weight: 1, tier: 'E+', score: 17, color: 'var(--tier-e-plus)' },

  // D- (score: 20)
  { label: 'Power as an Extension of Self', weight: 1, tier: 'D-', score: 20, color: 'var(--tier-d-minus)' },
  { label: 'Can Maintain Use Indefinitely', weight: 1, tier: 'D-', score: 20, color: 'var(--tier-d-minus)' },
  { label: 'Power and User: No Separation', weight: 1, tier: 'D-', score: 20, color: 'var(--tier-d-minus)' },
  { label: 'Mastery That Discovered a Second Power Layer', weight: 1, tier: 'D-', score: 20, color: 'var(--tier-d-minus)' },
  { label: 'Uses Power in Ways Unintended by Its Nature', weight: 1, tier: 'D-', score: 20, color: 'var(--tier-d-minus)' },
  { label: 'Power Precision: Perfect in All Recorded Instances', weight: 1, tier: 'D-', score: 20, color: 'var(--tier-d-minus)' },
  { label: 'Control Exists Even During Sleep', weight: 1, tier: 'D-', score: 20, color: 'var(--tier-d-minus)' },
  { label: 'Power Compressed to Minimal Expression for Precision', weight: 1, tier: 'D-', score: 20, color: 'var(--tier-d-minus)' },
  { label: 'Has Used Power to Affect What It "Shouldn\'t Affect"', weight: 1, tier: 'D-', score: 20, color: 'var(--tier-d-minus)' },
  { label: 'Mastery Visible at a Glance', weight: 1, tier: 'D-', score: 20, color: 'var(--tier-d-minus)' },
  { label: 'Power Responds to Emotion as a Feature, Not a Bug', weight: 1, tier: 'D-', score: 20, color: 'var(--tier-d-minus)' },
  { label: 'Can Reverse Own Power at Precise Timing', weight: 1, tier: 'D-', score: 20, color: 'var(--tier-d-minus)' },
  { label: 'Invented a Power Application Nobody Thought Possible', weight: 1, tier: 'D-', score: 20, color: 'var(--tier-d-minus)' },
  { label: 'Power Used at Atomic Level Without Error', weight: 1, tier: 'D-', score: 20, color: 'var(--tier-d-minus)' },
  { label: 'Full-Spectrum Control: Expression Through Suppression', weight: 1, tier: 'D-', score: 20, color: 'var(--tier-d-minus)' },
  { label: 'Power Control That Experts Study in Awe', weight: 1, tier: 'D-', score: 20, color: 'var(--tier-d-minus)' },
  { label: 'Can Use Power to Affect Immaterial Targets', weight: 1, tier: 'D-', score: 20, color: 'var(--tier-d-minus)' },
  { label: 'Subconscious Mastery Detected by Sensors', weight: 1, tier: 'D-', score: 20, color: 'var(--tier-d-minus)' },
  { label: 'Power Is the Cleanest Expression of Them', weight: 1, tier: 'D-', score: 20, color: 'var(--tier-d-minus)' },
  { label: 'Can Use Power to Influence Other Powers', weight: 1, tier: 'D-', score: 20, color: 'var(--tier-d-minus)' },

  // D (score: 23)
  { label: 'Complete Power Mastery', weight: 1, tier: 'D', score: 23, color: 'var(--tier-d)' },
  { label: 'Mastery That Reshaped Their Combat Style', weight: 1, tier: 'D', score: 23, color: 'var(--tier-d)' },
  { label: 'Uses Power as Casually as Breathing', weight: 1, tier: 'D', score: 23, color: 'var(--tier-d)' },
  { label: 'No Wasted Activation Since Year One', weight: 1, tier: 'D', score: 23, color: 'var(--tier-d)' },
  { label: 'Power Obeys Thought Before Intent Fully Forms', weight: 1, tier: 'D', score: 23, color: 'var(--tier-d)' },
  { label: 'Can Sustain Maximum Output Without Strain', weight: 1, tier: 'D', score: 23, color: 'var(--tier-d)' },
  { label: 'Simultaneously Manages Power in 10+ Applications', weight: 1, tier: 'D', score: 23, color: 'var(--tier-d)' },
  { label: 'Mastery Produces Creative Problem-Solving', weight: 1, tier: 'D', score: 23, color: 'var(--tier-d)' },
  { label: 'Power Can Be Weaponized, Shielded, or Suppressed — Instantly', weight: 1, tier: 'D', score: 23, color: 'var(--tier-d)' },
  { label: 'Power Controlled in Parallel With Combat Actions', weight: 1, tier: 'D', score: 23, color: 'var(--tier-d)' },
  { label: 'Has Discovered Applications Outside Original Scope', weight: 1, tier: 'D', score: 23, color: 'var(--tier-d)' },
  { label: 'Uses Power at Fractions of a Percent With Precision', weight: 1, tier: 'D', score: 23, color: 'var(--tier-d)' },
  { label: 'Mastery Recognized Across Power Classes', weight: 1, tier: 'D', score: 23, color: 'var(--tier-d)' },
  { label: 'Power Control Immune to Disruption Attempts', weight: 1, tier: 'D', score: 23, color: 'var(--tier-d)' },
  { label: 'Applies Power With Impossible Delicacy', weight: 1, tier: 'D', score: 23, color: 'var(--tier-d)' },
  { label: 'Power Expanded Beyond Its Original Parameters', weight: 1, tier: 'D', score: 23, color: 'var(--tier-d)' },
  { label: 'Power Use Completely Indistinguishable From Natural Action', weight: 1, tier: 'D', score: 23, color: 'var(--tier-d)' },
  { label: 'Mastery Redefines What the Power Can Do', weight: 1, tier: 'D', score: 23, color: 'var(--tier-d)' },
  { label: 'Power Naturally Optimizes Around Their Intent', weight: 1, tier: 'D', score: 23, color: 'var(--tier-d)' },
  { label: 'Has Never Lost Control — Not Even Close', weight: 1, tier: 'D', score: 23, color: 'var(--tier-d)' },

  // D+ (score: 26)
  { label: 'Power Transcends Its Defined Limits', weight: 1, tier: 'D+', score: 26, color: 'var(--tier-d-plus)' },
  { label: 'Mastery Grants Access to Locked Power Tiers', weight: 1, tier: 'D+', score: 26, color: 'var(--tier-d-plus)' },
  { label: 'Uses Power to Replicate Other Abilities', weight: 1, tier: 'D+', score: 26, color: 'var(--tier-d-plus)' },
  { label: 'Power Responds to Subconscious Commands', weight: 1, tier: 'D+', score: 26, color: 'var(--tier-d-plus)' },
  { label: 'Can Shape Power Into Tailored Applications Mid-Fight', weight: 1, tier: 'D+', score: 26, color: 'var(--tier-d-plus)' },
  { label: 'Mastery Enables Passive Power Loops', weight: 1, tier: 'D+', score: 26, color: 'var(--tier-d+)', },
  { label: 'Power Under Full Control at All Output Levels', weight: 1, tier: 'D+', score: 26, color: 'var(--tier-d-plus)' },
  { label: 'Can Simultaneously Affect Multiple Reality Layers', weight: 1, tier: 'D+', score: 26, color: 'var(--tier-d-plus)' },
  { label: 'Mastery Compresses Power to Near-Invisible Effect', weight: 1, tier: 'D+', score: 26, color: 'var(--tier-d-plus)' },
  { label: 'Power Used at Conceptual Level', weight: 1, tier: 'D+', score: 26, color: 'var(--tier-d-plus)' },
  { label: 'Control Flawless Even During Unconscious States', weight: 1, tier: 'D+', score: 26, color: 'var(--tier-d-plus)' },
  { label: 'Invented Power Techniques That Changed the Field', weight: 1, tier: 'D+', score: 26, color: 'var(--tier-d-plus)' },
  { label: 'Can Stack Simultaneous Effects Without Interference', weight: 1, tier: 'D+', score: 26, color: 'var(--tier-d-plus)' },
  { label: 'Power Acts as Both Tool and Shield Simultaneously', weight: 1, tier: 'D+', score: 26, color: 'var(--tier-d-plus)' },
  { label: 'Mastery That Intimidates Other Masters', weight: 1, tier: 'D+', score: 26, color: 'var(--tier-d-plus)' },
  { label: 'Power Extended Into Adjacent Phenomena', weight: 1, tier: 'D+', score: 26, color: 'var(--tier-d-plus)' },
  { label: 'Can Modulate Power at Sub-Quantum Precision', weight: 1, tier: 'D+', score: 26, color: 'var(--tier-d-plus)' },
  { label: 'Power Control Made Into an Art Form', weight: 1, tier: 'D+', score: 26, color: 'var(--tier-d-plus)' },
  { label: 'Uses Mastery to Amplify Others\' Powers', weight: 1, tier: 'D+', score: 26, color: 'var(--tier-d-plus)' },
  { label: 'Power Operates at Zero Friction With Intent', weight: 1, tier: 'D+', score: 26, color: 'var(--tier-d-plus)' },

  // C- through God: continuing the pattern with shorter entries for remaining 22 tiers
  // C- (score: 30)
  { label: 'Beyond Conventional Mastery', weight: 1, tier: 'C-', score: 30, color: 'var(--tier-c-minus)' },
  { label: 'Power Exceeds Its Described Boundaries', weight: 1, tier: 'C-', score: 30, color: 'var(--tier-c-minus)' },
  { label: 'Mastery Allows Power to Affect Concepts', weight: 1, tier: 'C-', score: 30, color: 'var(--tier-c-minus)' },
  { label: 'Power Responds Before Conscious Activation', weight: 1, tier: 'C-', score: 30, color: 'var(--tier-c-minus)' },
  { label: 'Can Express Power as Pure Mathematical Precision', weight: 1, tier: 'C-', score: 30, color: 'var(--tier-c-minus)' },
  { label: 'Full Control Over All Derived Effects', weight: 1, tier: 'C-', score: 30, color: 'var(--tier-c-minus)' },
  { label: 'Mastery Enables Power at the Causal Level', weight: 1, tier: 'C-', score: 30, color: 'var(--tier-c-minus)' },
  { label: 'Power Mastery Has Expanded the Power\'s Scope', weight: 1, tier: 'C-', score: 30, color: 'var(--tier-c-minus)' },
  { label: 'Uses Power to Influence Physical Constants Locally', weight: 1, tier: 'C-', score: 30, color: 'var(--tier-c-minus)' },
  { label: 'Mastery So Complete It Borders on Unnatural', weight: 1, tier: 'C-', score: 30, color: 'var(--tier-c-minus)' },
  { label: 'Can Detach Power Use From Time Constraints', weight: 1, tier: 'C-', score: 30, color: 'var(--tier-c-minus)' },
  { label: 'Power Outputs Beyond Its Designed Maximum', weight: 1, tier: 'C-', score: 30, color: 'var(--tier-c-minus)' },
  { label: 'Mastery That Altered How the Power Works Fundamentally', weight: 1, tier: 'C-', score: 30, color: 'var(--tier-c-minus)' },
  { label: 'Control That Implies Understanding Nobody Else Has', weight: 1, tier: 'C-', score: 30, color: 'var(--tier-c-minus)' },
  { label: 'Power Operates Across Dimensional Boundaries', weight: 1, tier: 'C-', score: 30, color: 'var(--tier-c-minus)' },
  { label: 'Uses Mastery to Invent Applications Mid-Battle', weight: 1, tier: 'C-', score: 30, color: 'var(--tier-c-minus)' },
  { label: 'Power Efficiency: Absolute Minimum Waste', weight: 1, tier: 'C-', score: 30, color: 'var(--tier-c-minus)' },
  { label: 'Mastery Allows Power to Be Temporarily Shared', weight: 1, tier: 'C-', score: 30, color: 'var(--tier-c-minus)' },
  { label: 'Can Apply Power to Things That Shouldn\'t Be Affected', weight: 1, tier: 'C-', score: 30, color: 'var(--tier-c-minus)' },
  { label: 'Power Is an Expression of Will Made Physical', weight: 1, tier: 'C-', score: 30, color: 'var(--tier-c-minus)' },

  // C (score: 34)
  { label: 'Supernatural Power Control', weight: 1, tier: 'C', score: 34, color: 'var(--tier-c)' },
  { label: 'Mastery Allows Power to Act Without Direct Supervision', weight: 1, tier: 'C', score: 34, color: 'var(--tier-c)' },
  { label: 'Can Compress Entire Power Into a Single Point', weight: 1, tier: 'C', score: 34, color: 'var(--tier-c)' },
  { label: 'Power Acts as Autonomous Extension of Self', weight: 1, tier: 'C', score: 34, color: 'var(--tier-c)' },
  { label: 'Mastery Enables Use During Unconscious States', weight: 1, tier: 'C', score: 34, color: 'var(--tier-c)' },
  { label: 'Power Operates Across Time Locally', weight: 1, tier: 'C', score: 34, color: 'var(--tier-c)' },
  { label: 'Simultaneously Active in Multiple Locations', weight: 1, tier: 'C', score: 34, color: 'var(--tier-c)' },
  { label: 'Has Unlocked Abilities Nested Within the Power', weight: 1, tier: 'C', score: 34, color: 'var(--tier-c)' },
  { label: 'Can Weaponize Opponent\'s Interaction With Their Power', weight: 1, tier: 'C', score: 34, color: 'var(--tier-c)' },
  { label: 'Mastery That Broke the Power\'s Supposed Limit', weight: 1, tier: 'C', score: 34, color: 'var(--tier-c)' },
  { label: 'Power Responds to Emotions as Intentional Commands', weight: 1, tier: 'C', score: 34, color: 'var(--tier-c)' },
  { label: 'Applies Power Across Multiple Planes Simultaneously', weight: 1, tier: 'C', score: 34, color: 'var(--tier-c)' },
  { label: 'Can Affect Non-Material Targets With Power', weight: 1, tier: 'C', score: 34, color: 'var(--tier-c)' },
  { label: 'Mastery That No Known Training System Produced', weight: 1, tier: 'C', score: 34, color: 'var(--tier-c)' },
  { label: 'Power Compressed to Zero-Point Expression', weight: 1, tier: 'C', score: 34, color: 'var(--tier-c)' },
  { label: 'Can Fold Power Back Onto Itself for Amplification', weight: 1, tier: 'C', score: 34, color: 'var(--tier-c)' },
  { label: 'Mastery Enables Real-Time Power Rewriting', weight: 1, tier: 'C', score: 34, color: 'var(--tier-c)' },
  { label: 'Full Mastery of Every Known and Unknown Application', weight: 1, tier: 'C', score: 34, color: 'var(--tier-c)' },
  { label: 'Power No Longer Constrained by Its Own Nature', weight: 1, tier: 'C', score: 34, color: 'var(--tier-c)' },
  { label: 'Uses Mastery to Counter Powers That Counter Theirs', weight: 1, tier: 'C', score: 34, color: 'var(--tier-c)' },

  // C+ (score: 38)
  { label: 'Reality-Grade Power Control', weight: 1, tier: 'C+', score: 38, color: 'var(--tier-c-plus)' },
  { label: 'Power and Reality Are Indistinguishable at This Level', weight: 1, tier: 'C+', score: 38, color: 'var(--tier-c-plus)' },
  { label: 'Mastery Breaks the Power\'s Original Ruleset', weight: 1, tier: 'C+', score: 38, color: 'var(--tier-c-plus)' },
  { label: 'Can Affect Abstract and Philosophical Targets', weight: 1, tier: 'C+', score: 38, color: 'var(--tier-c-plus)' },
  { label: 'Power Applied Across All Dimensions Simultaneously', weight: 1, tier: 'C+', score: 38, color: 'var(--tier-c-plus)' },
  { label: 'Mastery Rewrote What the Power Fundamentally Is', weight: 1, tier: 'C+', score: 38, color: 'var(--tier-c-plus)' },
  { label: 'Power Used to Affect Probability Directly', weight: 1, tier: 'C+', score: 38, color: 'var(--tier-c-plus)' },
  { label: 'Has Mastered Aspects of Power Nobody Knew Existed', weight: 1, tier: 'C+', score: 38, color: 'var(--tier-c-plus)' },
  { label: 'Power Effective Against Non-Physical Phenomena', weight: 1, tier: 'C+', score: 38, color: 'var(--tier-c-plus)' },
  { label: 'Mastery: Controls Power at the Cosmic Structural Level', weight: 1, tier: 'C+', score: 38, color: 'var(--tier-c-plus)' },
  { label: 'Can Invert Power at Will', weight: 1, tier: 'C+', score: 38, color: 'var(--tier-c-plus)' },
  { label: 'Power Can Be Shared, Lent, or Projected Into Others', weight: 1, tier: 'C+', score: 38, color: 'var(--tier-c-plus)' },
  { label: 'Uses Power to Nullify Other Powers Precisely', weight: 1, tier: 'C+', score: 38, color: 'var(--tier-c-plus)' },
  { label: 'Mastery Generates Effects Never Described in the Power\'s Literature', weight: 1, tier: 'C+', score: 38, color: 'var(--tier-c-plus)' },
  { label: 'Power Operates Ahead of Its Own Activation Time', weight: 1, tier: 'C+', score: 38, color: 'var(--tier-c-plus)' },
  { label: 'Uses Power to Bridge Physical and Non-Physical Space', weight: 1, tier: 'C+', score: 38, color: 'var(--tier-c-plus)' },
  { label: 'Mastery That Affects What the Power "Is" to Others', weight: 1, tier: 'C+', score: 38, color: 'var(--tier-c-plus)' },
  { label: 'Power Control Operates Across Temporal Boundaries', weight: 1, tier: 'C+', score: 38, color: 'var(--tier-c-plus)' },
  { label: 'Can Compress Power Into Pure Intent and Release', weight: 1, tier: 'C+', score: 38, color: 'var(--tier-c-plus)' },
  { label: 'Power Mastery That Expanded the Definition of the Ability', weight: 1, tier: 'C+', score: 38, color: 'var(--tier-c-plus)' },

  // B- (score: 42)
  { label: 'Transcendent Mastery', weight: 1, tier: 'B-', score: 42, color: 'var(--tier-b-minus)' },
  { label: 'Power Operates on the Level of Physical Law', weight: 1, tier: 'B-', score: 42, color: 'var(--tier-b-minus)' },
  { label: 'Mastery Enables Power to Alter Spacetime', weight: 1, tier: 'B-', score: 42, color: 'var(--tier-b-minus)' },
  { label: 'Can Use Power to Alter Events That Have Happened', weight: 1, tier: 'B-', score: 42, color: 'var(--tier-b-minus)' },
  { label: 'Power Extended Across Multiversal Space', weight: 1, tier: 'B-', score: 42, color: 'var(--tier-b-minus)' },
  { label: 'Mastery That Changed the Power\'s Fundamental Nature', weight: 1, tier: 'B-', score: 42, color: 'var(--tier-b-minus)' },
  { label: 'Power Controlled at Quantum Causality Level', weight: 1, tier: 'B-', score: 42, color: 'var(--tier-b-minus)' },
  { label: 'Can Operate Power Passively Across All Dimensions', weight: 1, tier: 'B-', score: 42, color: 'var(--tier-b-minus)' },
  { label: 'Mastery Allows Power to Affect Future States', weight: 1, tier: 'B-', score: 42, color: 'var(--tier-b-minus)' },
  { label: 'Power Output Affects Physics Locally', weight: 1, tier: 'B-', score: 42, color: 'var(--tier-b-minus)' },
  { label: 'Has Mastered Aspects That Predate the Power\'s Definition', weight: 1, tier: 'B-', score: 42, color: 'var(--tier-b-minus)' },
  { label: 'Power Controlled Beyond Its Original Source', weight: 1, tier: 'B-', score: 42, color: 'var(--tier-b-minus)' },
  { label: 'Mastery Allows Power to Interact With Abstract Structures', weight: 1, tier: 'B-', score: 42, color: 'var(--tier-b-minus)' },
  { label: 'Uses Power at Every Scale Simultaneously', weight: 1, tier: 'B-', score: 42, color: 'var(--tier-b-minus)' },
  { label: 'Power Responds to Intention Across All Planes', weight: 1, tier: 'B-', score: 42, color: 'var(--tier-b-minus)' },
  { label: 'Can Use Power to Rewrite Its Own Limits', weight: 1, tier: 'B-', score: 42, color: 'var(--tier-b-minus)' },
  { label: 'Mastery That Gave the Power New Properties', weight: 1, tier: 'B-', score: 42, color: 'var(--tier-b-minus)' },
  { label: 'Power Operates in Parallel Across All Known Uses', weight: 1, tier: 'B-', score: 42, color: 'var(--tier-b-minus)' },
  { label: 'Has Used Power to Counter Powers That Shouldn\'t Be Counterable', weight: 1, tier: 'B-', score: 42, color: 'var(--tier-b-minus)' },
  { label: 'Mastery That Made Other Masters Reclassify Themselves', weight: 1, tier: 'B-', score: 42, color: 'var(--tier-b-minus)' },

  // B (score: 47)
  { label: 'Omniversal Mastery Level', weight: 1, tier: 'B', score: 47, color: 'var(--tier-b)' },
  { label: 'Power Obeys Before Being Called', weight: 1, tier: 'B', score: 47, color: 'var(--tier-b)' },
  { label: 'Mastery Operates at the Level of Physical Constants', weight: 1, tier: 'B', score: 47, color: 'var(--tier-b)' },
  { label: 'Power Simultaneous Across All Active Timelines', weight: 1, tier: 'B', score: 47, color: 'var(--tier-b)' },
  { label: 'Can Extend Power to Affect Cosmological Events', weight: 1, tier: 'B', score: 47, color: 'var(--tier-b)' },
  { label: 'Power Actively Adjusts to Environment Without Input', weight: 1, tier: 'B', score: 47, color: 'var(--tier-b)' },
  { label: 'Mastery Changed What the Power Can Target', weight: 1, tier: 'B', score: 47, color: 'var(--tier-b)' },
  { label: 'Uses Power on Concepts That Pre-Date Language', weight: 1, tier: 'B', score: 47, color: 'var(--tier-b)' },
  { label: 'Can Affect Things That Only Exist Theoretically', weight: 1, tier: 'B', score: 47, color: 'var(--tier-b)' },
  { label: 'Mastery Expanded Power Into Adjacent Disciplines', weight: 1, tier: 'B', score: 47, color: 'var(--tier-b)' },
  { label: 'Power Operates as a Law, Not a Skill', weight: 1, tier: 'B', score: 47, color: 'var(--tier-b)' },
  { label: 'Control That Exists Beyond Cognitive Intervention', weight: 1, tier: 'B', score: 47, color: 'var(--tier-b)' },
  { label: 'Mastery Allows Power to Anchor Realities', weight: 1, tier: 'B', score: 47, color: 'var(--tier-b)' },
  { label: 'Power Is Now Indistinguishable From Their Essence', weight: 1, tier: 'B', score: 47, color: 'var(--tier-b)' },
  { label: 'Has Mastered the Concept the Power Is Based On', weight: 1, tier: 'B', score: 47, color: 'var(--tier-b)' },
  { label: 'Power Simultaneously Suppressed and Active in Balance', weight: 1, tier: 'B', score: 47, color: 'var(--tier-b)' },
  { label: 'Uses Power to Interfere With Pre-Existing Metaphysics', weight: 1, tier: 'B', score: 47, color: 'var(--tier-b)' },
  { label: 'Mastery That Made the Power Aware of Them', weight: 1, tier: 'B', score: 47, color: 'var(--tier-b)' },
  { label: 'Control That Precedes Any Defined Mastery System', weight: 1, tier: 'B', score: 47, color: 'var(--tier-b)' },
  { label: 'Rewrote What Mastery Means by Doing This', weight: 1, tier: 'B', score: 47, color: 'var(--tier-b)' },

  // B+ (score: 52)
  { label: 'Absolute Power Control', weight: 1, tier: 'B+', score: 52, color: 'var(--tier-b-plus)' },
  { label: 'Power Operates Across All Realities at Once', weight: 1, tier: 'B+', score: 52, color: 'var(--tier-b-plus)' },
  { label: 'Mastery That Altered the Power\'s Cosmological Classification', weight: 1, tier: 'B+', score: 52, color: 'var(--tier-b-plus)' },
  { label: 'Can Use Power to Affect Things Before They Happen', weight: 1, tier: 'B+', score: 52, color: 'var(--tier-b-plus)' },
  { label: 'Power Mastery Rewrites Its Own Origin', weight: 1, tier: 'B+', score: 52, color: 'var(--tier-b-plus)' },
  { label: 'Has Mastered All Possible Expressions of the Power', weight: 1, tier: 'B+', score: 52, color: 'var(--tier-b-plus)' },
  { label: 'Power Control Operates at the Level of Reality\'s Source Code', weight: 1, tier: 'B+', score: 52, color: 'var(--tier-b-plus)' },
  { label: 'Uses Mastery to Affect Powers That Oppose Theirs', weight: 1, tier: 'B+', score: 52, color: 'var(--tier-b-plus)' },
  { label: 'Can Apply Power to Delete or Create Conceptual Objects', weight: 1, tier: 'B+', score: 52, color: 'var(--tier-b-plus)' },
  { label: 'Power Has Never Operated Against Their Intent', weight: 1, tier: 'B+', score: 52, color: 'var(--tier-b-plus)' },
  { label: 'Mastery Enabled Power to Evolve Independently', weight: 1, tier: 'B+', score: 52, color: 'var(--tier-b-plus)' },
  { label: 'Can Extend Power to Affect Non-Existent Targets', weight: 1, tier: 'B+', score: 52, color: 'var(--tier-b-plus)' },
  { label: 'Power Mastery Has Made It Into a Natural Force', weight: 1, tier: 'B+', score: 52, color: 'var(--tier-b-plus)' },
  { label: 'Mastery Allows Real-Time Power Architecture', weight: 1, tier: 'B+', score: 52, color: 'var(--tier-b-plus)' },
  { label: 'Control Operates Across Infinite Applications', weight: 1, tier: 'B+', score: 52, color: 'var(--tier-b-plus)' },
  { label: 'Power Is Its Own Plane of Existence at This Point', weight: 1, tier: 'B+', score: 52, color: 'var(--tier-b-plus)' },
  { label: 'Mastery Allows Power to Know What\'s Needed Before Asked', weight: 1, tier: 'B+', score: 52, color: 'var(--tier-b-plus)' },
  { label: 'Has Discovered the True Nature of the Power Through Control', weight: 1, tier: 'B+', score: 52, color: 'var(--tier-b-plus)' },
  { label: 'Power Mastery Indistinguishable From Creating the Power', weight: 1, tier: 'B+', score: 52, color: 'var(--tier-b-plus)' },
  { label: 'Uses Power to Affect the Meta-Structure of Reality', weight: 1, tier: 'B+', score: 52, color: 'var(--tier-b-plus)' },

  // A- (score: 57)
  { label: 'Power and Self Are One', weight: 1, tier: 'A-', score: 57, color: 'var(--tier-a-minus)' },
  { label: 'No Distinction Between User and Ability', weight: 1, tier: 'A-', score: 57, color: 'var(--tier-a-minus)' },
  { label: 'Mastery Surpassed the Power Itself', weight: 1, tier: 'A-', score: 57, color: 'var(--tier-a-minus)' },
  { label: 'Power Operates Across All Omniversal Contexts', weight: 1, tier: 'A-', score: 57, color: 'var(--tier-a-minus)' },
  { label: 'Can Affect Powers That Don\'t Exist Yet', weight: 1, tier: 'A-', score: 57, color: 'var(--tier-a-minus)' },
  { label: 'Mastery Made the Power Aware of Itself', weight: 1, tier: 'A-', score: 57, color: 'var(--tier-a-minus)' },
  { label: 'Power Mastery Is a Law in Their Vicinity', weight: 1, tier: 'A-', score: 57, color: 'var(--tier-a-minus)' },
  { label: 'Uses Power to Operate Across All Possible Timelines at Once', weight: 1, tier: 'A-', score: 57, color: 'var(--tier-a-minus)' },
  { label: 'Control That Predates the Power\'s Origin', weight: 1, tier: 'A-', score: 57, color: 'var(--tier-a-minus)' },
  { label: 'Power Has Recognized Them as Its True Wielder', weight: 1, tier: 'A-', score: 57, color: 'var(--tier-a-minus)' },
  { label: 'Mastery Allows Power to Generate Other Powers', weight: 1, tier: 'A-', score: 57, color: 'var(--tier-a-minus)' },
  { label: 'Power Control Immune to Reality Distortion', weight: 1, tier: 'A-', score: 57, color: 'var(--tier-a-minus)' },
  { label: 'Simultaneously Active at Full Precision Everywhere', weight: 1, tier: 'A-', score: 57, color: 'var(--tier-a-minus)' },
  { label: 'Power Obeys Not Just Intent — But the Idea Behind Intent', weight: 1, tier: 'A-', score: 57, color: 'var(--tier-a-minus)' },
  { label: 'Mastery Defines the Boundaries of Power for All Others', weight: 1, tier: 'A-', score: 57, color: 'var(--tier-a-minus)' },
  { label: 'Has Used Power to Affect Physical Laws Permanently', weight: 1, tier: 'A-', score: 57, color: 'var(--tier-a-minus)' },
  { label: 'Power Applies Itself Without Activation', weight: 1, tier: 'A-', score: 57, color: 'var(--tier-a-minus)' },
  { label: 'Uses Power to Shape the Context That Power Exists In', weight: 1, tier: 'A-', score: 57, color: 'var(--tier-a-minus)' },
  { label: 'Mastery That Defined the Upper Limit of What\'s Possible', weight: 1, tier: 'A-', score: 57, color: 'var(--tier-a-minus)' },
  { label: 'Power Is at Peak in All Possible Expressions — Simultaneously', weight: 1, tier: 'A-', score: 57, color: 'var(--tier-a-minus)' },

  // A (score: 62)
  { label: 'Cosmic Mastery Class', weight: 1, tier: 'A', score: 62, color: 'var(--tier-a)' },
  { label: 'Power and Reality Are Co-Authoring', weight: 1, tier: 'A', score: 62, color: 'var(--tier-a)' },
  { label: 'Mastery Transcended the Concept of Control', weight: 1, tier: 'A', score: 62, color: 'var(--tier-a)' },
  { label: 'Power Has Mastered Back', weight: 1, tier: 'A', score: 62, color: 'var(--tier-a)' },
  { label: 'Uses Power to Operate in All Dimensions Without Activation', weight: 1, tier: 'A', score: 62, color: 'var(--tier-a)' },
  { label: 'Mastery Allows Power to Be Applied Retroactively', weight: 1, tier: 'A', score: 62, color: 'var(--tier-a)' },
  { label: 'Can Express Power Through Non-Physical Channels', weight: 1, tier: 'A', score: 62, color: 'var(--tier-a)' },
  { label: 'Power Operates at the Omniversal Structural Level', weight: 1, tier: 'A', score: 62, color: 'var(--tier-a)' },
  { label: 'Has Mastered Every Possible Application Simultaneously', weight: 1, tier: 'A', score: 62, color: 'var(--tier-a)' },
  { label: 'Mastery That Made the Omniverse Categorize Them Separately', weight: 1, tier: 'A', score: 62, color: 'var(--tier-a)' },
  { label: 'Power Obeys Before It Exists', weight: 1, tier: 'A', score: 62, color: 'var(--tier-a)' },
  { label: 'Control Operates Even in Anti-Power Environments', weight: 1, tier: 'A', score: 62, color: 'var(--tier-a)' },
  { label: 'Mastery Allows Use Without Source', weight: 1, tier: 'A', score: 62, color: 'var(--tier-a)' },
  { label: 'Power Functions as a Cosmological Foundation Here', weight: 1, tier: 'A', score: 62, color: 'var(--tier-a)' },
  { label: 'Has Defined What Mastery Means for Everyone After', weight: 1, tier: 'A', score: 62, color: 'var(--tier-a)' },
  { label: 'Power Mastery Rewrites What Powers Can Do', weight: 1, tier: 'A', score: 62, color: 'var(--tier-a)' },
  { label: 'Uses Mastery to Counter Powers That Counter All Powers', weight: 1, tier: 'A', score: 62, color: 'var(--tier-a)' },
  { label: 'Mastery That Extended Power Into Pre-Existence', weight: 1, tier: 'A', score: 62, color: 'var(--tier-a)' },
  { label: 'Power Has No Ceiling at This Level of Control', weight: 1, tier: 'A', score: 62, color: 'var(--tier-a)' },
  { label: 'Mastery Is a Physical Property of Their Universe', weight: 1, tier: 'A', score: 62, color: 'var(--tier-a)' },

  // A+ (score: 67)
  { label: 'The Power Obeys Before Being Called', weight: 1, tier: 'A+', score: 67, color: 'var(--tier-a-plus)' },
  { label: 'Mastery: Total — All Layers, All Scales, All Time', weight: 1, tier: 'A+', score: 67, color: 'var(--tier-a-plus)' },
  { label: 'Power Functions as a Pre-Cosmic Force', weight: 1, tier: 'A+', score: 67, color: 'var(--tier-a-plus)' },
  { label: 'Has Used Power to Affect the Source of All Power', weight: 1, tier: 'A+', score: 67, color: 'var(--tier-a-plus)' },
  { label: 'Control That Operates in Every Universe at Once', weight: 1, tier: 'A+', score: 67, color: 'var(--tier-a-plus)' },
  { label: 'Mastery So Absolute the Power Has No Independent State', weight: 1, tier: 'A+', score: 67, color: 'var(--tier-a-plus)' },
  { label: 'Power Mastery That Reclassified the Nature of Mastery', weight: 1, tier: 'A+', score: 67, color: 'var(--tier-a-plus)' },
  { label: 'Uses Power Without Any Separation Between Self and Ability', weight: 1, tier: 'A+', score: 67, color: 'var(--tier-a-plus)' },
  { label: 'Mastery Enables Power to Write Its Own New Rules', weight: 1, tier: 'A+', score: 67, color: 'var(--tier-a-plus)' },
  { label: 'Power Active Across All Possible States Simultaneously', weight: 1, tier: 'A+', score: 67, color: 'var(--tier-a-plus)' },
  { label: 'Has Mastered the Power\'s Power', weight: 1, tier: 'A+', score: 67, color: 'var(--tier-a-plus)' },
  { label: 'Mastery That Absorbed the Power Into Their Nature', weight: 1, tier: 'A+', score: 67, color: 'var(--tier-a-plus)' },
  { label: 'Power Is No Longer Distinct From Their Will', weight: 1, tier: 'A+', score: 67, color: 'var(--tier-a-plus)' },
  { label: 'Can Use Power to Affect Powers Across All Realities', weight: 1, tier: 'A+', score: 67, color: 'var(--tier-a-plus)' },
  { label: 'Mastery Has Become Its Own Power Type', weight: 1, tier: 'A+', score: 67, color: 'var(--tier-a-plus)' },
  { label: 'Power Functions Retroactively in All Timelines', weight: 1, tier: 'A+', score: 67, color: 'var(--tier-a-plus)' },
  { label: 'Has Used Power to Affect Things Before Power Existed', weight: 1, tier: 'A+', score: 67, color: 'var(--tier-a-plus)' },
  { label: 'Mastery Defines What Other Masters Aspire To', weight: 1, tier: 'A+', score: 67, color: 'var(--tier-a-plus)' },
  { label: 'Power Responds to Existence Itself', weight: 1, tier: 'A+', score: 67, color: 'var(--tier-a-plus)' },
  { label: 'Control Absolute — Nothing Comparable Exists', weight: 1, tier: 'A+', score: 67, color: 'var(--tier-a-plus)' },

  // S- (score: 72)
  { label: 'Omniversal Power Mastery', weight: 1, tier: 'S-', score: 72, color: 'var(--tier-s-minus)' },
  { label: 'Power Operates on Concepts Themselves', weight: 1, tier: 'S-', score: 72, color: 'var(--tier-s-minus)' },
  { label: 'Mastery That Altered the Omniverse\'s Definition of Power', weight: 1, tier: 'S-', score: 72, color: 'var(--tier-s-minus)' },
  { label: 'Uses Power to Affect Pre-Existing Metaphysical Structures', weight: 1, tier: 'S-', score: 72, color: 'var(--tier-s-minus)' },
  { label: 'Power and Self and Reality Share One Axis', weight: 1, tier: 'S-', score: 72, color: 'var(--tier-s-minus)' },
  { label: 'Mastery Allows Power to Function Across Non-Existence', weight: 1, tier: 'S-', score: 72, color: 'var(--tier-s-minus)' },
  { label: 'Has Used Power to Create New Power Categories', weight: 1, tier: 'S-', score: 72, color: 'var(--tier-s-minus)' },
  { label: 'Control Exists Even in Environments Where Power Can\'t', weight: 1, tier: 'S-', score: 72, color: 'var(--tier-s-minus)' },
  { label: 'Power Mastery Has Become an Omniversal Reference Point', weight: 1, tier: 'S-', score: 72, color: 'var(--tier-s-minus)' },
  { label: 'Can Operate Power Before It Exists in That Context', weight: 1, tier: 'S-', score: 72, color: 'var(--tier-s-minus)' },
  { label: 'Mastery Absorbed the Source of All Powers', weight: 1, tier: 'S-', score: 72, color: 'var(--tier-s-minus)' },
  { label: 'Power Functions as an Omniversal Constant', weight: 1, tier: 'S-', score: 72, color: 'var(--tier-s-minus)' },
  { label: 'Has Mastered Power in Every Form It Could Ever Take', weight: 1, tier: 'S-', score: 72, color: 'var(--tier-s-minus)' },
  { label: 'Mastery Rewrote the Laws Governing Their Power\'s Class', weight: 1, tier: 'S-', score: 72, color: 'var(--tier-s-minus)' },
  { label: 'Power Obeys Across All Versions of Reality', weight: 1, tier: 'S-', score: 72, color: 'var(--tier-s-minus)' },
  { label: 'Uses Power to Define What Power Is for the Omniverse', weight: 1, tier: 'S-', score: 72, color: 'var(--tier-s-minus)' },
  { label: 'Control That Predates the Concept of Powers Existing', weight: 1, tier: 'S-', score: 72, color: 'var(--tier-s-minus)' },
  { label: 'Mastery That Replaced Training as a Concept for Them', weight: 1, tier: 'S-', score: 72, color: 'var(--tier-s-minus)' },
  { label: 'Power Applies Itself to Scenarios It Has Never Encountered', weight: 1, tier: 'S-', score: 72, color: 'var(--tier-s-minus)' },
  { label: 'Mastery Is the Only Term Left for What They Do', weight: 1, tier: 'S-', score: 72, color: 'var(--tier-s-minus)' },

  // S (score: 77)
  { label: 'Perfect Power Mastery', weight: 1, tier: 'S', score: 77, color: 'var(--tier-s)' },
  { label: 'Power and Mastery Are Indistinguishable', weight: 1, tier: 'S', score: 77, color: 'var(--tier-s)' },
  { label: 'Can Use Power to Affect All Powers That Have Ever Existed', weight: 1, tier: 'S', score: 77, color: 'var(--tier-s)' },
  { label: 'Mastery That Wrote the Laws of Power in the Omniverse', weight: 1, tier: 'S', score: 77, color: 'var(--tier-s)' },
  { label: 'Power and Intent Are a Single Phenomenon', weight: 1, tier: 'S', score: 77, color: 'var(--tier-s)' },
  { label: 'Omniversal Power Authority', weight: 1, tier: 'S', score: 77, color: 'var(--tier-s)' },
  { label: 'Mastery So Complete Other Powers Defer to It', weight: 1, tier: 'S', score: 77, color: 'var(--tier-s)' },
  { label: 'Mastery That Seeded the Concept of Mastery Itself', weight: 1, tier: 'S', score: 77, color: 'var(--tier-s)' },
  { label: 'Can Use Power to Affect the Omniverse\'s Power Systems', weight: 1, tier: 'S', score: 77, color: 'var(--tier-s)' },
  { label: 'Power Active Across Every Possible Context — Perfectly', weight: 1, tier: 'S', score: 77, color: 'var(--tier-s)' },
  { label: 'Has Mastered Power at Every Scale, Every Time, Every Dimension', weight: 1, tier: 'S', score: 77, color: 'var(--tier-s)' },
  { label: 'Mastery That Altered the Pre-Universal Power Structure', weight: 1, tier: 'S', score: 77, color: 'var(--tier-s)' },
  { label: 'Power Operates in Ways That Cannot Be Named', weight: 1, tier: 'S', score: 77, color: 'var(--tier-s)' },
  { label: 'Can Apply Power to the Mechanism of Power Itself', weight: 1, tier: 'S', score: 77, color: 'var(--tier-s)' },
  { label: 'Mastery Functions as a Universal Organizing Principle', weight: 1, tier: 'S', score: 77, color: 'var(--tier-s)' },
  { label: 'Power Is Completely Integrated Into All Existence', weight: 1, tier: 'S', score: 77, color: 'var(--tier-s)' },
  { label: 'Uses Power to Alter How the Omniverse Categorizes Power', weight: 1, tier: 'S', score: 77, color: 'var(--tier-s)' },
  { label: 'Mastery Absolute — Applied to Everything — Always', weight: 1, tier: 'S', score: 77, color: 'var(--tier-s)' },
  { label: 'Power Control Is the Foundation of Their Reality', weight: 1, tier: 'S', score: 77, color: 'var(--tier-s)' },
  { label: 'Mastery That Became the Standard All Others Fail to Reach', weight: 1, tier: 'S', score: 77, color: 'var(--tier-s)' },

  // S+ (score: 81)
  { label: 'Omniversal Power Absolute', weight: 1, tier: 'S+', score: 81, color: 'var(--tier-s-plus)' },
  { label: 'Mastery That Cannot Be Observed Without Awe', weight: 1, tier: 'S+', score: 81, color: 'var(--tier-s-plus)' },
  { label: 'Power Responds to Existence — Not Commands', weight: 1, tier: 'S+', score: 81, color: 'var(--tier-s-plus)' },
  { label: 'Can Affect All Powers Across the Omniverse Simultaneously', weight: 1, tier: 'S+', score: 81, color: 'var(--tier-s-plus)' },
  { label: 'Mastery That Pre-Dates Powers Having Any Rules', weight: 1, tier: 'S+', score: 81, color: 'var(--tier-s-plus)' },
  { label: 'Power Has No Independent State — It Is Them', weight: 1, tier: 'S+', score: 81, color: 'var(--tier-s-plus)' },
  { label: 'Has Mastered All Possible Powers Through Mastering One', weight: 1, tier: 'S+', score: 81, color: 'var(--tier-s-plus)' },
  { label: 'Mastery Created New Laws That Now Govern All Power', weight: 1, tier: 'S+', score: 81, color: 'var(--tier-s-plus)' },
  { label: 'Uses Power to Shape What Power Is in All Realities', weight: 1, tier: 'S+', score: 81, color: 'var(--tier-s-plus)' },
  { label: 'Control Operates Beyond the Concept of Activation', weight: 1, tier: 'S+', score: 81, color: 'var(--tier-s-plus)' },
  { label: 'Mastery That Changed the Omniverse\'s Relationship With Power', weight: 1, tier: 'S+', score: 81, color: 'var(--tier-s-plus)' },
  { label: 'Power Applies Itself to All Things That Need Applying To', weight: 1, tier: 'S+', score: 81, color: 'var(--tier-s-plus)' },
  { label: 'Mastery Is Permanent — Cannot Be Removed by Any Means', weight: 1, tier: 'S+', score: 81, color: 'var(--tier-s-plus)' },
  { label: 'Power Mastery Is a Cosmological Constant', weight: 1, tier: 'S+', score: 81, color: 'var(--tier-s-plus)' },
  { label: 'Can Use Power to Retroactively Adjust All Power Use', weight: 1, tier: 'S+', score: 81, color: 'var(--tier-s-plus)' },
  { label: 'Mastery That Invented the Concept of Perfect Control', weight: 1, tier: 'S+', score: 81, color: 'var(--tier-s-plus)' },
  { label: 'Power Responds to Their Non-Existence Just as Readily', weight: 1, tier: 'S+', score: 81, color: 'var(--tier-s-plus)' },
  { label: 'Has Used Mastery to Rewrite Power in Every Possible Universe', weight: 1, tier: 'S+', score: 81, color: 'var(--tier-s-plus)' },
  { label: 'All Powers Are Expressions of Their One Mastery', weight: 1, tier: 'S+', score: 81, color: 'var(--tier-s-plus)' },
  { label: 'Mastery: Maximum. Permanent. Total.', weight: 1, tier: 'S+', score: 81, color: 'var(--tier-s-plus)' },

  // SS- (score: 85)
  { label: 'Primordial Power Mastery', weight: 1, tier: 'SS-', score: 85, color: 'var(--tier-ss-minus)' },
  { label: 'Has Mastered Power Before It Had a Name', weight: 1, tier: 'SS-', score: 85, color: 'var(--tier-ss-minus)' },
  { label: 'Mastery That Exists as an Omniversal Structural Force', weight: 1, tier: 'SS-', score: 85, color: 'var(--tier-ss-minus)' },
  { label: 'Power Responds Across Pre-Time', weight: 1, tier: 'SS-', score: 85, color: 'var(--tier-ss-minus)' },
  { label: 'Can Apply Power to All of Existence Simultaneously', weight: 1, tier: 'SS-', score: 85, color: 'var(--tier-ss-minus)' },
  { label: 'Mastery Is a Pre-Universal Phenomenon', weight: 1, tier: 'SS-', score: 85, color: 'var(--tier-ss-minus)' },
  { label: 'Power and All Power Are the Same at This Level', weight: 1, tier: 'SS-', score: 85, color: 'var(--tier-ss-minus)' },
  { label: 'Mastery Altered the Cosmological Definition of Ability', weight: 1, tier: 'SS-', score: 85, color: 'var(--tier-ss-minus)' },
  { label: 'Has Used Power to Affect What Power Is in Every Universe', weight: 1, tier: 'SS-', score: 85, color: 'var(--tier-ss-minus)' },
  { label: 'Control Is So Total That Power Requires No Activation', weight: 1, tier: 'SS-', score: 85, color: 'var(--tier-ss-minus)' },
  { label: 'Mastery That Pre-Seeded All Power Systems', weight: 1, tier: 'SS-', score: 85, color: 'var(--tier-ss-minus)' },
  { label: 'Power Operates Across Impossible Contexts Automatically', weight: 1, tier: 'SS-', score: 85, color: 'var(--tier-ss-minus)' },
  { label: 'Has Mastered Powers That Don\'t Exist in Any Reality', weight: 1, tier: 'SS-', score: 85, color: 'var(--tier-ss-minus)' },
  { label: 'Mastery That Made the Pre-Universe Reorganize', weight: 1, tier: 'SS-', score: 85, color: 'var(--tier-ss-minus)' },
  { label: 'Power Control Is the Primary Feature of All Existence Here', weight: 1, tier: 'SS-', score: 85, color: 'var(--tier-ss-minus)' },
  { label: 'Mastery Older Than What It Controls', weight: 1, tier: 'SS-', score: 85, color: 'var(--tier-ss-minus)' },
  { label: 'Power Applies to Everything Including the Concept of "Not-Power"', weight: 1, tier: 'SS-', score: 85, color: 'var(--tier-ss-minus)' },
  { label: 'Has Used Power Mastery to Define What Mastery Is', weight: 1, tier: 'SS-', score: 85, color: 'var(--tier-ss-minus)' },
  { label: 'Mastery Is Not a Skill — It Is Their Foundation', weight: 1, tier: 'SS-', score: 85, color: 'var(--tier-ss-minus)' },
  { label: 'Power Has Been Mastered to the Level of Pre-Existence', weight: 1, tier: 'SS-', score: 85, color: 'var(--tier-ss-minus)' },

  // SS (score: 88)
  { label: 'Power Mastery Beyond All Concept', weight: 1, tier: 'SS', score: 88, color: 'var(--tier-ss)' },
  { label: 'Mastery That Defined the Omniverse\'s First Power Rule', weight: 1, tier: 'SS', score: 88, color: 'var(--tier-ss)' },
  { label: 'Power Responds Across All of Pre-Existence', weight: 1, tier: 'SS', score: 88, color: 'var(--tier-ss)' },
  { label: 'Has Mastered Power in Ways the Power Cannot Describe', weight: 1, tier: 'SS', score: 88, color: 'var(--tier-ss)' },
  { label: 'Mastery Exists as an Intrinsic Property of Reality', weight: 1, tier: 'SS', score: 88, color: 'var(--tier-ss)' },
  { label: 'Control That Operates in Realms Where Control Has No Meaning', weight: 1, tier: 'SS', score: 88, color: 'var(--tier-ss)' },
  { label: 'Power Mastery Is What Made the Power Possible Originally', weight: 1, tier: 'SS', score: 88, color: 'var(--tier-ss)' },
  { label: 'Can Apply Power to the Concept of Power Itself', weight: 1, tier: 'SS', score: 88, color: 'var(--tier-ss)' },
  { label: 'Mastery Has Become the Universal Standard for Power Control', weight: 1, tier: 'SS', score: 88, color: 'var(--tier-ss)' },
  { label: 'Power Active — Perfectly — In All States — Always', weight: 1, tier: 'SS', score: 88, color: 'var(--tier-ss)' },
  { label: 'Has Used Power to Define What Powers Are for the Omniverse', weight: 1, tier: 'SS', score: 88, color: 'var(--tier-ss)' },
  { label: 'Mastery Is Older Than Time — Was Here First', weight: 1, tier: 'SS', score: 88, color: 'var(--tier-ss)' },
  { label: 'Power Control Has No Equivalent in Any Known System', weight: 1, tier: 'SS', score: 88, color: 'var(--tier-ss)' },
  { label: 'All Power Is a Subset of What They\'ve Mastered', weight: 1, tier: 'SS', score: 88, color: 'var(--tier-ss)' },
  { label: 'Mastery That Preceded the Mechanism That Powers Powers', weight: 1, tier: 'SS', score: 88, color: 'var(--tier-ss)' },
  { label: 'Control That Writes Its Own Rules Into Reality', weight: 1, tier: 'SS', score: 88, color: 'var(--tier-ss)' },
  { label: 'Power and Mastery Are One — Have Always Been One', weight: 1, tier: 'SS', score: 88, color: 'var(--tier-ss)' },
  { label: 'Has Mastered the Ultimate Concept Behind All Powers', weight: 1, tier: 'SS', score: 88, color: 'var(--tier-ss)' },
  { label: 'Mastery Absolute — Cosmic — Eternal', weight: 1, tier: 'SS', score: 88, color: 'var(--tier-ss)' },
  { label: 'Power Obeys Across All Infinities Without Exception', weight: 1, tier: 'SS', score: 88, color: 'var(--tier-ss)' },

  // SS+ (score: 91)
  { label: 'Power Mastery: Final Form', weight: 1, tier: 'SS+', score: 91, color: 'var(--tier-ss-plus)' },
  { label: 'All Powers Were Mastered Before Being Used', weight: 1, tier: 'SS+', score: 91, color: 'var(--tier-ss-plus)' },
  { label: 'Mastery Is What Makes the Omniverse Run Correctly', weight: 1, tier: 'SS+', score: 91, color: 'var(--tier-ss-plus)' },
  { label: 'Power Responds to Pure Intention Across All Dimensions', weight: 1, tier: 'SS+', score: 91, color: 'var(--tier-ss-plus)' },
  { label: 'Has Used Power to Affect What the Concept of Power Means', weight: 1, tier: 'SS+', score: 91, color: 'var(--tier-ss-plus)' },
  { label: 'Mastery That Defined "Control" as a Universal Concept', weight: 1, tier: 'SS+', score: 91, color: 'var(--tier-ss-plus)' },
  { label: 'Power Mastery Is a Pre-Cosmic Constant', weight: 1, tier: 'SS+', score: 91, color: 'var(--tier-ss-plus)' },
  { label: 'Can Apply Power to the Void Without Activation', weight: 1, tier: 'SS+', score: 91, color: 'var(--tier-ss-plus)' },
  { label: 'Mastery That Allowed Power to Exist Before It Did', weight: 1, tier: 'SS+', score: 91, color: 'var(--tier-ss-plus)' },
  { label: 'Control Has No Limit — Never Had One — Never Will', weight: 1, tier: 'SS+', score: 91, color: 'var(--tier-ss-plus)' },
  { label: 'All Power Mastery Is a Derivative of Theirs', weight: 1, tier: 'SS+', score: 91, color: 'var(--tier-ss-plus)' },
  { label: 'Mastery Rewrote Every Power System in Every Omniverse', weight: 1, tier: 'SS+', score: 91, color: 'var(--tier-ss-plus)' },
  { label: 'Power Operates Across All States — Including Non-Existence', weight: 1, tier: 'SS+', score: 91, color: 'var(--tier-ss-plus)' },
  { label: 'Has Used Power to Affect All Powers That Will Ever Be', weight: 1, tier: 'SS+', score: 91, color: 'var(--tier-ss-plus)' },
  { label: 'Mastery That Is Intrinsic to the Fabric of Existence', weight: 1, tier: 'SS+', score: 91, color: 'var(--tier-ss-plus)' },
  { label: 'Power Mastery Precedes and Will Outlast All Realities', weight: 1, tier: 'SS+', score: 91, color: 'var(--tier-ss-plus)' },
  { label: 'Control Absolute — Across All Planes — All Time — Always', weight: 1, tier: 'SS+', score: 91, color: 'var(--tier-ss-plus)' },
  { label: 'Mastery That Birthed the Concept of Using Power Well', weight: 1, tier: 'SS+', score: 91, color: 'var(--tier-ss-plus)' },
  { label: 'Has Mastered What Powers Will Become After Eternity', weight: 1, tier: 'SS+', score: 91, color: 'var(--tier-ss-plus)' },
  { label: 'Power Mastery: Total. Absolute. The End of the Concept.', weight: 1, tier: 'SS+', score: 91, color: 'var(--tier-ss-plus)' },

  // SSS- (score: 94)
  { label: 'Pre-Universal Mastery Absolute', weight: 1, tier: 'SSS-', score: 94, color: 'var(--tier-sss-minus)' },
  { label: 'Power Mastery Is What Made the Universe Possible', weight: 1, tier: 'SSS-', score: 94, color: 'var(--tier-sss-minus)' },
  { label: 'All Control Derives From Theirs', weight: 1, tier: 'SSS-', score: 94, color: 'var(--tier-sss-minus)' },
  { label: 'Has Mastered Power Across Every State Including None', weight: 1, tier: 'SSS-', score: 94, color: 'var(--tier-sss-minus)' },
  { label: 'Mastery So Absolute Powers Fear Being Called', weight: 1, tier: 'SSS-', score: 94, color: 'var(--tier-sss-minus)' },
  { label: 'Power Obeys Before Existence Allows It To', weight: 1, tier: 'SSS-', score: 94, color: 'var(--tier-sss-minus)' },
  { label: 'Mastery That Created the Concept of Control', weight: 1, tier: 'SSS-', score: 94, color: 'var(--tier-sss-minus)' },
  { label: 'Can Use Power to Affect the Ability to Have Power', weight: 1, tier: 'SSS-', score: 94, color: 'var(--tier-sss-minus)' },
  { label: 'All Power Systems Are Imperfect Copies of Their Mastery', weight: 1, tier: 'SSS-', score: 94, color: 'var(--tier-sss-minus)' },
  { label: 'Mastery That Is Older Than All Powers and All Rules', weight: 1, tier: 'SSS-', score: 94, color: 'var(--tier-sss-minus)' },
  { label: 'Has Mastered Powers That Only Exist in Theory', weight: 1, tier: 'SSS-', score: 94, color: 'var(--tier-sss-minus)' },
  { label: 'Control That Operates on the Fundamental Principle of Power', weight: 1, tier: 'SSS-', score: 94, color: 'var(--tier-sss-minus)' },
  { label: 'Mastery Is the First and Last Word in All Power Systems', weight: 1, tier: 'SSS-', score: 94, color: 'var(--tier-sss-minus)' },
  { label: 'Has Used Power to Redefine What Powers Are in the Omniverse', weight: 1, tier: 'SSS-', score: 94, color: 'var(--tier-sss-minus)' },
  { label: 'Power Mastery Is a Feature of Pre-Cosmic Structure', weight: 1, tier: 'SSS-', score: 94, color: 'var(--tier-sss-minus)' },
  { label: 'All Mastery Systems Were Built From Their Example', weight: 1, tier: 'SSS-', score: 94, color: 'var(--tier-sss-minus)' },
  { label: 'Mastery That Gave Power Its Own Laws', weight: 1, tier: 'SSS-', score: 94, color: 'var(--tier-sss-minus)' },
  { label: 'Has Mastered Power in Ways Even the Power Didn\'t Know', weight: 1, tier: 'SSS-', score: 94, color: 'var(--tier-sss-minus)' },
  { label: 'Control Absolute — Over All Powers — Across All Time', weight: 1, tier: 'SSS-', score: 94, color: 'var(--tier-sss-minus)' },
  { label: 'Mastery That Preceded the Existence It Now Governs', weight: 1, tier: 'SSS-', score: 94, color: 'var(--tier-sss-minus)' },

  // SSS (score: 97)
  { label: 'Omniversal Power Master', weight: 1, tier: 'SSS', score: 97, color: 'var(--tier-sss)' },
  { label: 'All Powers Are Their Power', weight: 1, tier: 'SSS', score: 97, color: 'var(--tier-sss)' },
  { label: 'Mastery That Cannot Be Named Without Creating It', weight: 1, tier: 'SSS', score: 97, color: 'var(--tier-sss)' },
  { label: 'Power Control Was Created When They Needed Control', weight: 1, tier: 'SSS', score: 97, color: 'var(--tier-sss)' },
  { label: 'Mastery Absolute — The Measure All Other Mastery Fails At', weight: 1, tier: 'SSS', score: 97, color: 'var(--tier-sss)' },
  { label: 'Has Mastered Every Power Across Every Possible Omniverse', weight: 1, tier: 'SSS', score: 97, color: 'var(--tier-sss)' },
  { label: 'Power Mastery Is a Foundational Law of the Omniverse', weight: 1, tier: 'SSS', score: 97, color: 'var(--tier-sss)' },
  { label: 'Uses Mastery to Govern What Power Is Allowed to Do', weight: 1, tier: 'SSS', score: 97, color: 'var(--tier-sss)' },
  { label: 'Mastery That Seeded Every Power Law That Exists', weight: 1, tier: 'SSS', score: 97, color: 'var(--tier-sss)' },
  { label: 'Power Has No Existence Without Their Mastery', weight: 1, tier: 'SSS', score: 97, color: 'var(--tier-sss)' },
  { label: 'Control That Defines What Control Is', weight: 1, tier: 'SSS', score: 97, color: 'var(--tier-sss)' },
  { label: 'Mastery That Created the First Power and the Last', weight: 1, tier: 'SSS', score: 97, color: 'var(--tier-sss)' },
  { label: 'Has Used Power to Affect What Power Means in All Contexts', weight: 1, tier: 'SSS', score: 97, color: 'var(--tier-sss)' },
  { label: 'Power Mastery: Perfect. Absolute. Unlimited. Eternal.', weight: 1, tier: 'SSS', score: 97, color: 'var(--tier-sss)' },
  { label: 'Mastery That Governs All Powers Across All Infinities', weight: 1, tier: 'SSS', score: 97, color: 'var(--tier-sss)' },
  { label: 'All Powers Report Back to Their Mastery', weight: 1, tier: 'SSS', score: 97, color: 'var(--tier-sss)' },
  { label: 'Mastery That Is the Reason Powers Have Laws', weight: 1, tier: 'SSS', score: 97, color: 'var(--tier-sss)' },
  { label: 'Has Achieved Mastery of the Source of All Mastery', weight: 1, tier: 'SSS', score: 97, color: 'var(--tier-sss)' },
  { label: 'Power Obeys in Every Context — Even Contexts Without Power', weight: 1, tier: 'SSS', score: 97, color: 'var(--tier-sss)' },
  { label: 'Absolute Power Mastery — Singular. Final. Absolute.', weight: 1, tier: 'SSS', score: 97, color: 'var(--tier-sss)' },

  // SSS+ (score: 99)
  { label: 'Perfect Control — Every Sense Covered', weight: 1, tier: 'SSS+', score: 99, color: 'var(--tier-sss-plus)' },
  { label: 'Power Mastery That Pre-Dates Powers Themselves', weight: 1, tier: 'SSS+', score: 99, color: 'var(--tier-sss-plus)' },
  { label: 'Mastery That Is the Power Source for All Other Mastery', weight: 1, tier: 'SSS+', score: 99, color: 'var(--tier-sss-plus)' },
  { label: 'Can Use Power to Affect What All Power Is Across Existence', weight: 1, tier: 'SSS+', score: 99, color: 'var(--tier-sss-plus)' },
  { label: 'Mastery Older Than the Concept of Having Abilities', weight: 1, tier: 'SSS+', score: 99, color: 'var(--tier-sss-plus)' },
  { label: 'Power Mastery Is the Reason Powers Are Controllable at All', weight: 1, tier: 'SSS+', score: 99, color: 'var(--tier-sss-plus)' },
  { label: 'All Power in All Omniverses Is Downstream of Their Mastery', weight: 1, tier: 'SSS+', score: 99, color: 'var(--tier-sss-plus)' },
  { label: 'Mastery So Total It Is the Foundational Law of All Reality', weight: 1, tier: 'SSS+', score: 99, color: 'var(--tier-sss-plus)' },
  { label: 'Power and Mastery Have No Distinction — They Are One Axiom', weight: 1, tier: 'SSS+', score: 99, color: 'var(--tier-sss-plus)' },
  { label: 'Has Mastered Powers That Have Not Been Created Yet', weight: 1, tier: 'SSS+', score: 99, color: 'var(--tier-sss-plus)' },
  { label: 'Control That Is a Law — Not a Trait', weight: 1, tier: 'SSS+', score: 99, color: 'var(--tier-sss-plus)' },
  { label: 'Mastery That Is the Origin Point of All Control', weight: 1, tier: 'SSS+', score: 99, color: 'var(--tier-sss-plus)' },
  { label: 'All Things That Use Power Use It Through Them', weight: 1, tier: 'SSS+', score: 99, color: 'var(--tier-sss-plus)' },
  { label: 'Power Mastery Cannot Be Described Without Undervaluing It', weight: 1, tier: 'SSS+', score: 99, color: 'var(--tier-sss-plus)' },
  { label: 'Mastery That Defined the First and Last Thing About Power', weight: 1, tier: 'SSS+', score: 99, color: 'var(--tier-sss-plus)' },
  { label: 'Power Obeys Before It Exists — This Is the Rule, Not the Exception', weight: 1, tier: 'SSS+', score: 99, color: 'var(--tier-sss-plus)' },
  { label: 'All Possible Expressions of Mastery Are Inferior', weight: 1, tier: 'SSS+', score: 99, color: 'var(--tier-sss-plus)' },
  { label: 'Has Mastered the Mechanism of Mastery Itself', weight: 1, tier: 'SSS+', score: 99, color: 'var(--tier-sss-plus)' },
  { label: 'Power Mastery Absolute — The Template All Others Follow', weight: 1, tier: 'SSS+', score: 99, color: 'var(--tier-sss-plus)' },
  { label: 'The First Mastery — The Deepest Control — The Final Word', weight: 1, tier: 'SSS+', score: 99, color: 'var(--tier-sss-plus)' },

  // God (score: 100)
  { label: 'The Power Obeys Before Being Called', weight: 1, tier: 'God', score: 100, color: 'var(--tier-god)' },
  { label: 'Mastery That Is the Source of All Power', weight: 1, tier: 'God', score: 100, color: 'var(--tier-god)' },
  { label: 'Power and Existence Are Co-Extensive at This Level', weight: 1, tier: 'God', score: 100, color: 'var(--tier-god)' },
  { label: 'All Powers Have Acknowledged Their Mastery', weight: 1, tier: 'God', score: 100, color: 'var(--tier-god)' },
  { label: 'Mastery That Invented Power Before Creating It', weight: 1, tier: 'God', score: 100, color: 'var(--tier-god)' },
  { label: 'Can Affect What Power Is Before It Has a Definition', weight: 1, tier: 'God', score: 100, color: 'var(--tier-god)' },
  { label: 'Mastery That Is the Bedrock of the Omniversal Power System', weight: 1, tier: 'God', score: 100, color: 'var(--tier-god)' },
  { label: 'Power Mastery: Infinite. Total. Permanent. Unrivaled.', weight: 1, tier: 'God', score: 100, color: 'var(--tier-god)' },
  { label: 'Every Power That Has Existed Was Mastered by Them First', weight: 1, tier: 'God', score: 100, color: 'var(--tier-god)' },
  { label: 'Mastery That Governs Itself and All That Follow', weight: 1, tier: 'God', score: 100, color: 'var(--tier-god)' },
  { label: 'All Control in All Realities Is a Descendant of Theirs', weight: 1, tier: 'God', score: 100, color: 'var(--tier-god)' },
  { label: 'Power Mastery Is What Made the First Moment Possible', weight: 1, tier: 'God', score: 100, color: 'var(--tier-god)' },
  { label: 'Control That Is Older Than the Power It Controls', weight: 1, tier: 'God', score: 100, color: 'var(--tier-god)' },
  { label: 'Mastery That Preceded Everything — Including Itself', weight: 1, tier: 'God', score: 100, color: 'var(--tier-god)' },
  { label: 'All Powers Were Given Rules by Their Mastery', weight: 1, tier: 'God', score: 100, color: 'var(--tier-god)' },
  { label: 'The Ultimate Power Is Perfect Power Mastery', weight: 1, tier: 'God', score: 100, color: 'var(--tier-god)' },
  { label: 'Mastery That Is the Reason Power Obeys Anyone at All', weight: 1, tier: 'God', score: 100, color: 'var(--tier-god)' },
  { label: 'Power and Mastery and Self Are a Single Absolute', weight: 1, tier: 'God', score: 100, color: 'var(--tier-god)' },
  { label: 'Mastery Beyond Description — Perfect — Final — Forever', weight: 1, tier: 'God', score: 100, color: 'var(--tier-god)' },
  { label: 'The Power Obeys. Full Stop. No Further Explanation.', weight: 1, tier: 'God', score: 100, color: 'var(--tier-god)' },
]
