import type { FlavorLabel } from './types'

export const powerMasteryLabels: FlavorLabel[] = [
  { label: "Has a Power, Doesn't Know It",          weight: 1, tier: 'F-',   score: 2,   color: '#555'    },
  { label: 'Power Accidentally Activates',          weight: 1, tier: 'F',    score: 5,   color: '#666'    },
  { label: 'Basic Control, Mostly',                 weight: 1, tier: 'F+',   score: 8,   color: '#777'    },
  { label: 'Can Aim Sometimes',                     weight: 1, tier: 'E-',   score: 11,  color: '#6b7280' },
  { label: 'Reliable Under Pressure',               weight: 1, tier: 'E',    score: 14,  color: '#9ca3af' },
  { label: 'Consistent Use in Combat',              weight: 1, tier: 'E+',   score: 17,  color: '#d1d5db' },
  { label: 'Advanced Technique User',               weight: 1, tier: 'D-',   score: 20,  color: '#92400e' },
  { label: 'Extends Beyond Basics',                 weight: 1, tier: 'D',    score: 23,  color: '#b45309' },
  { label: 'Mastered Secondary Abilities',          weight: 1, tier: 'D+',   score: 26,  color: '#d97706' },
  { label: 'Power-Optimized Combatant',             weight: 1, tier: 'C-',   score: 30,  color: '#1d4ed8' },
  { label: 'Pushes Power to Its Limits',            weight: 1, tier: 'C',    score: 34,  color: '#2563eb' },
  { label: 'Surpasses Typical Power Ceiling',       weight: 1, tier: 'C+',   score: 38,  color: '#3b82f6' },
  { label: 'Rewrites What the Power Can Do',        weight: 1, tier: 'B-',   score: 42,  color: '#065f46' },
  { label: 'Power Responds to Thought Alone',       weight: 1, tier: 'B',    score: 47,  color: '#059669' },
  { label: 'Transcends Power Class Limits',         weight: 1, tier: 'B+',   score: 52,  color: '#34d399' },
  { label: 'Creates New Applications',              weight: 1, tier: 'A-',   score: 57,  color: '#7c3aed' },
  { label: 'Mastery That Redefines the Power',      weight: 1, tier: 'A',    score: 62,  color: '#8b5cf6' },
  { label: 'Power Is an Extension of Self',         weight: 1, tier: 'A+',   score: 67,  color: '#a78bfa' },
  { label: 'Power Bends Reality Slightly',          weight: 1, tier: 'S-',   score: 72,  color: '#b91c1c' },
  { label: 'Unlimited Potential Unlocked',          weight: 1, tier: 'S',    score: 77,  color: '#dc2626' },
  { label: 'Power Mastery Beyond Category',         weight: 1, tier: 'S+',   score: 81,  color: '#ef4444' },
  { label: 'Breaks Power System Constraints',       weight: 1, tier: 'SS-',  score: 85,  color: '#ea580c' },
  { label: 'Power Indistinguishable from Magic',    weight: 1, tier: 'SS',   score: 88,  color: '#f97316' },
  { label: 'Power Writes Its Own Rules',            weight: 1, tier: 'SS+',  score: 91,  color: '#fb923c' },
  { label: 'Power and User Are One',                weight: 1, tier: 'SSS-', score: 94,  color: '#ca8a04' },
  { label: 'The Power Chose to Be Mastered',        weight: 1, tier: 'SSS',  score: 97,  color: '#eab308' },
  { label: 'Power Evolved Into Something New',      weight: 1, tier: 'SSS+', score: 99,  color: '#fde047' },
  { label: 'The Source of All Powers',              weight: 1, tier: 'God',  score: 100, color: '#e879f9' },
]
