// powers-epic.ts — Rebalanced power pool for Wheel of Fate.
// 420 entries: F(80) E(70) D(70) C(70) B(60) A(50) S(40) SS(30) SSS(20)
// God tier (10) lives in powers-absurd.ts alongside comedy powers.
// No default export.

import type { SimpleItem } from './types'

export const epicPowers: SimpleItem[] = [
  // ── GOD TIER (10) — reality-breaking, universe-level ──
  { label: 'Omnipotence', weight: 1, element: 'Cosmic', grade: 'God' },
  { label: 'True Omniscience', weight: 1, element: 'Cosmic', grade: 'God' },
  { label: 'Reality Rewrite', weight: 1, element: 'Chaos', grade: 'God' },
  { label: 'Existence Erasure', weight: 1, element: 'Void', grade: 'God' },
  { label: 'Infinite Regeneration', weight: 1, element: 'Soul', grade: 'God' },
  { label: 'Conceptual Destruction', weight: 1, element: 'Void', grade: 'God' },
  { label: 'True Immortality', weight: 1, element: 'Time', grade: 'God' },
  { label: 'Universal Force Control', weight: 1, element: 'Gravity', grade: 'God' },
  { label: 'Absolute Causality Override', weight: 1, element: 'Time', grade: 'God' },
  { label: 'Primordial Creation', weight: 1, element: 'Cosmic', grade: 'God' },

  // ── SSS TIER (20) — legendary, universe-scale ──
  { label: 'Pocket Universe Creation', weight: 1, element: 'Chaos', grade: 'SSS' },
  { label: 'Causality Violation', weight: 1, element: 'Chaos', grade: 'SSS' },
  { label: 'Time Stop', weight: 1, element: 'Time', grade: 'SSS' },
  { label: 'Chronolock', weight: 1, element: 'Time', grade: 'SSS' },
  { label: 'Event Horizon Creation', weight: 1, element: 'Void', grade: 'SSS' },
  { label: 'Stellar Detonation', weight: 1, element: 'Cosmic', grade: 'SSS' },
  { label: 'Dimensional Fortress', weight: 1, element: 'Void', grade: 'SSS' },
  { label: 'Soul Domain', weight: 1, element: 'Soul', grade: 'SSS' },
  { label: 'Entropy Reversal', weight: 1, element: 'Void', grade: 'SSS' },
  { label: 'Fate Unraveling', weight: 1, element: 'Cosmic', grade: 'SSS' },
  { label: 'Astral Singularity', weight: 1, element: 'Cosmic', grade: 'SSS' },
  { label: 'Void Annihilation', weight: 1, element: 'Void', grade: 'SSS' },
  { label: 'World-Ending Flame', weight: 1, element: 'Fire', grade: 'SSS' },
  { label: 'Absolute Freeze', weight: 1, element: 'Ice', grade: 'SSS' },
  { label: 'Dimensional Collapse', weight: 1, element: 'Chaos', grade: 'SSS' },
  { label: 'Cosmic Storm Manifestation', weight: 1, element: 'Cosmic', grade: 'SSS' },
  { label: 'The Death Touch', weight: 1, element: 'Soul', grade: 'SSS' },
  { label: 'Origin Sealing', weight: 1, element: 'Arcane', grade: 'SSS' },
  { label: 'Universal Gravity Crush', weight: 1, element: 'Gravity', grade: 'SSS' },
  { label: 'Primordial Darkness', weight: 1, element: 'Shadow', grade: 'SSS' },

  // ── SS TIER (30) — divine-level power ──
  { label: 'Paradox Weaponization', weight: 1, element: 'Chaos', grade: 'SS' },
  { label: 'Fate Threading', weight: 1, element: 'Cosmic', grade: 'SS' },
  { label: 'Destiny Alteration', weight: 1, element: 'Cosmic', grade: 'SS' },
  { label: 'Probability Inversion', weight: 1, element: 'Chaos', grade: 'SS' },
  { label: 'Reality Anchor', weight: 1, element: 'Chaos', grade: 'SS' },
  { label: 'Reality Warping', weight: 1, element: 'Chaos', grade: 'SS' },
  { label: 'Dark Energy Manipulation', weight: 1, element: 'Void', grade: 'SS' },
  { label: 'Antimatter Generation', weight: 1, element: 'Void', grade: 'SS' },
  { label: 'Space Folding', weight: 1, element: 'Chaos', grade: 'SS' },
  { label: 'Wormhole Creation', weight: 1, element: 'Cosmic', grade: 'SS' },
  { label: 'Dimensional Lock', weight: 1, element: 'Void', grade: 'SS' },
  { label: 'Soul Forge', weight: 1, element: 'Soul', grade: 'SS' },
  { label: 'Dimensional Rifting', weight: 1, element: 'Chaos', grade: 'SS' },
  { label: 'Chrono Displacement', weight: 1, element: 'Time', grade: 'SS' },
  { label: 'Graviton Control', weight: 1, element: 'Gravity', grade: 'SS' },
  { label: 'Star Forge', weight: 1, element: 'Cosmic', grade: 'SS' },
  { label: 'Void Walking', weight: 1, element: 'Void', grade: 'SS' },
  { label: 'Entropy Control', weight: 1, element: 'Void', grade: 'SS' },
  { label: 'Molecular Reconstruction', weight: 1, element: 'Arcane', grade: 'SS' },
  { label: 'Neural Domination', weight: 1, element: 'Psychic', grade: 'SS' },
  { label: 'Absolute Zero Aura', weight: 1, element: 'Ice', grade: 'SS' },
  { label: 'Psychic Dominion', weight: 1, element: 'Psychic', grade: 'SS' },
  { label: 'Biological Control', weight: 1, element: 'Nature', grade: 'SS' },
  { label: 'Cosmic Awareness', weight: 1, element: 'Cosmic', grade: 'SS' },
  { label: 'Dream Invasion', weight: 1, element: 'Psychic', grade: 'SS' },
  { label: 'Shadow Realm Creation', weight: 1, element: 'Shadow', grade: 'SS' },
  { label: 'Gravity Singularity', weight: 1, element: 'Gravity', grade: 'SS' },
  { label: 'Life Force Severing', weight: 1, element: 'Soul', grade: 'SS' },
  { label: 'Mass Petrification', weight: 1, element: 'Earth', grade: 'SS' },
  { label: 'Temporal Echo', weight: 1, element: 'Time', grade: 'SS' },

  // ── S TIER (40) — mythic-level power ──
  { label: 'Time Reversal', weight: 1, element: 'Time', grade: 'S' },
  { label: 'Shadow Realm Portal', weight: 1, element: 'Shadow', grade: 'S' },
  { label: 'Probability Manipulation', weight: 1, element: 'Chaos', grade: 'S' },
  { label: 'Dimensional Pocket', weight: 1, element: 'Arcane', grade: 'S' },
  { label: 'Plasma Detonation', weight: 1, element: 'Fire', grade: 'S' },
  { label: 'Gravitational Mastery', weight: 1, element: 'Gravity', grade: 'S' },
  { label: 'Necromancy', weight: 1, element: 'Soul', grade: 'S' },
  { label: 'Elemental Convergence', weight: 1, element: 'Arcane', grade: 'S' },
  { label: 'Soul Absorption', weight: 1, element: 'Soul', grade: 'S' },
  { label: 'Quantum Tunneling', weight: 1, element: 'Chaos', grade: 'S' },
  { label: 'Weather Dominion', weight: 1, element: 'Wind', grade: 'S' },
  { label: 'Spectral Army Summoning', weight: 1, element: 'Soul', grade: 'S' },
  { label: 'Lava Mastery', weight: 1, element: 'Fire', grade: 'S' },
  { label: 'Lightning God Strike', weight: 1, element: 'Lightning', grade: 'S' },
  { label: 'Cosmic Ray Blast', weight: 1, element: 'Cosmic', grade: 'S' },
  { label: 'Voidstep', weight: 1, element: 'Void', grade: 'S' },
  { label: 'Mental Fortress', weight: 1, element: 'Psychic', grade: 'S' },
  { label: 'Blood Alchemy', weight: 1, element: 'Blood', grade: 'S' },
  { label: 'Phoenix Rebirth', weight: 1, element: 'Fire', grade: 'S' },
  { label: 'Nature Dominion', weight: 1, element: 'Nature', grade: 'S' },
  { label: 'Ice Age Aura', weight: 1, element: 'Ice', grade: 'S' },
  { label: 'Thunder God Clap', weight: 1, element: 'Lightning', grade: 'S' },
  { label: 'Neural Override', weight: 1, element: 'Psychic', grade: 'S' },
  { label: 'Death Defiance', weight: 1, element: 'Soul', grade: 'S' },
  { label: 'Volcanic Eruption', weight: 1, element: 'Earth', grade: 'S' },
  { label: 'Tsunami Wave', weight: 1, element: 'Water', grade: 'S' },
  { label: 'Wind Cutter Storm', weight: 1, element: 'Wind', grade: 'S' },
  { label: 'Lightning Fortress', weight: 1, element: 'Lightning', grade: 'S' },
  { label: 'Time Manipulation', weight: 1, element: 'Time', grade: 'S' },
  { label: 'Spectral Form', weight: 1, element: 'Soul', grade: 'S' },
  { label: 'Life Force Drain', weight: 1, element: 'Blood', grade: 'S' },
  { label: 'Crystalline Armor Manifestation', weight: 1, element: 'Earth', grade: 'S' },
  { label: 'Sound Annihilation', weight: 1, element: 'Sound', grade: 'S' },
  { label: 'Acid Rain Summon', weight: 1, element: 'Poison', grade: 'S' },
  { label: 'Mana Vortex', weight: 1, element: 'Arcane', grade: 'S' },
  { label: 'Void Bomb', weight: 1, element: 'Void', grade: 'S' },
  { label: 'Cosmic Shield', weight: 1, element: 'Cosmic', grade: 'S' },
  { label: 'Plague Aura', weight: 1, element: 'Poison', grade: 'S' },
  { label: 'Seraphic Wings', weight: 1, element: 'Light', grade: 'S' },
  { label: 'Abyssal Tide', weight: 1, element: 'Water', grade: 'S' },

  // ── A TIER (50) — legendary power ──
  { label: 'Shadow Manipulation', weight: 1, element: 'Shadow', grade: 'A' },
  { label: 'Molecular Vibration', weight: 1, element: 'Arcane', grade: 'A' },
  { label: 'Atomic Restructuring', weight: 1, element: 'Void', grade: 'A' },
  { label: 'Matter Disintegration', weight: 1, element: 'Void', grade: 'A' },
  { label: 'Telekinetic Surge', weight: 1, element: 'Psychic', grade: 'A' },
  { label: 'Precognition', weight: 1, element: 'Psychic', grade: 'A' },
  { label: 'Nuclear Pulse', weight: 1, element: 'Void', grade: 'A' },
  { label: 'Illusion Mastery', weight: 1, element: 'Arcane', grade: 'A' },
  { label: 'Seismic Command', weight: 1, element: 'Earth', grade: 'A' },
  { label: 'Bone Architecture', weight: 1, element: 'Earth', grade: 'A' },
  { label: 'Transmutation', weight: 1, element: 'Arcane', grade: 'A' },
  { label: 'Conjuration', weight: 1, element: 'Arcane', grade: 'A' },
  { label: 'Enchantment Mastery', weight: 1, element: 'Arcane', grade: 'A' },
  { label: 'Evocation', weight: 1, element: 'Arcane', grade: 'A' },
  { label: 'Abjuration', weight: 1, element: 'Arcane', grade: 'A' },
  { label: 'Divination', weight: 1, element: 'Arcane', grade: 'A' },
  { label: 'Memory Erasure', weight: 1, element: 'Psychic', grade: 'A' },
  { label: 'Corrosive Touch', weight: 1, element: 'Poison', grade: 'A' },
  { label: 'Earthquake Stomp', weight: 1, element: 'Earth', grade: 'A' },
  { label: 'Arcane Barrage', weight: 1, element: 'Arcane', grade: 'A' },
  { label: 'Counterspell', weight: 1, element: 'Arcane', grade: 'A' },
  { label: 'Spell Steal', weight: 1, element: 'Arcane', grade: 'A' },
  { label: 'Celestial Binding', weight: 1, element: 'Light', grade: 'A' },
  { label: 'Venom Mastery', weight: 1, element: 'Poison', grade: 'A' },
  { label: 'Holy Light Beam', weight: 1, element: 'Light', grade: 'A' },
  { label: 'Blood Curse', weight: 1, element: 'Blood', grade: 'A' },
  { label: 'Time Slow', weight: 1, element: 'Time', grade: 'A' },
  { label: 'Psychic Domination', weight: 1, element: 'Psychic', grade: 'A' },
  { label: 'Vitality Transfer', weight: 1, element: 'Nature', grade: 'A' },
  { label: 'Ice Storm', weight: 1, element: 'Ice', grade: 'A' },
  { label: 'Arcane Mastery', weight: 1, element: 'Arcane', grade: 'A' },
  { label: 'Lightning Chain', weight: 1, element: 'Lightning', grade: 'A' },
  { label: 'Shadow Army', weight: 1, element: 'Shadow', grade: 'A' },
  { label: 'Force Field', weight: 1, element: 'Arcane', grade: 'A' },
  { label: 'Spectral Blade Storm', weight: 1, element: 'Soul', grade: 'A' },
  { label: 'Curse Weaving', weight: 1, element: 'Shadow', grade: 'A' },
  { label: 'Magma Body', weight: 1, element: 'Fire', grade: 'A' },
  { label: 'Crystal Cage', weight: 1, element: 'Earth', grade: 'A' },
  { label: 'Toxin Immunity', weight: 1, element: 'Poison', grade: 'A' },
  { label: 'Wind Slash', weight: 1, element: 'Wind', grade: 'A' },
  { label: 'Mind Reading', weight: 1, element: 'Psychic', grade: 'A' },
  { label: 'Firestorm Aura', weight: 1, element: 'Fire', grade: 'A' },
  { label: 'Water Breathing', weight: 1, element: 'Water', grade: 'A' },
  { label: 'Telepathy', weight: 1, element: 'Psychic', grade: 'A' },
  { label: 'Thunder Clap', weight: 1, element: 'Lightning', grade: 'A' },
  { label: 'Curse of Decay', weight: 1, element: 'Shadow', grade: 'A' },
  { label: 'Nature Surge', weight: 1, element: 'Nature', grade: 'A' },
  { label: 'Sound Shaping', weight: 1, element: 'Sound', grade: 'A' },
  { label: 'Mirror Dimension', weight: 1, element: 'Arcane', grade: 'A' },
  { label: 'Spirit Guidance', weight: 1, element: 'Soul', grade: 'A' },

  // ── B TIER (60) — epic power ──
  { label: 'Lightning Mastery', weight: 1, element: 'Lightning', grade: 'B' },
  { label: 'Invulnerability', weight: 1, element: 'Neutral', grade: 'B' },
  { label: 'Super Strength', weight: 1, element: 'Neutral', grade: 'B' },
  { label: 'Super Speed', weight: 1, element: 'Neutral', grade: 'B' },
  { label: 'Flight', weight: 1, element: 'Wind', grade: 'B' },
  { label: 'Teleportation', weight: 1, element: 'Arcane', grade: 'B' },
  { label: 'Telekinesis', weight: 1, element: 'Psychic', grade: 'B' },
  { label: 'Pyrokinesis', weight: 1, element: 'Fire', grade: 'B' },
  { label: 'Hydrokinesis', weight: 1, element: 'Water', grade: 'B' },
  { label: 'Electrokinesis', weight: 1, element: 'Lightning', grade: 'B' },
  { label: 'Cryokinesis', weight: 1, element: 'Ice', grade: 'B' },
  { label: 'Terrakinesis', weight: 1, element: 'Earth', grade: 'B' },
  { label: 'Aerokinesis', weight: 1, element: 'Wind', grade: 'B' },
  { label: 'Photokinesis', weight: 1, element: 'Light', grade: 'B' },
  { label: 'Umbrakinesis', weight: 1, element: 'Shadow', grade: 'B' },
  { label: 'Quantum Tunneling', weight: 1, element: 'Chaos', grade: 'B' },
  { label: 'Healing Factor', weight: 1, element: 'Nature', grade: 'B' },
  { label: 'Cellular Regeneration', weight: 1, element: 'Nature', grade: 'B' },
  { label: 'Plasma Generation', weight: 1, element: 'Fire', grade: 'B' },
  { label: 'Light Refraction', weight: 1, element: 'Light', grade: 'B' },
  { label: 'Dimensional Pocket', weight: 1, element: 'Arcane', grade: 'B' },
  { label: 'Mana Drain', weight: 1, element: 'Arcane', grade: 'B' },
  { label: 'Pathogen Generation', weight: 1, element: 'Poison', grade: 'B' },
  { label: 'Astral Projection', weight: 1, element: 'Soul', grade: 'B' },
  { label: 'Soul Vision', weight: 1, element: 'Soul', grade: 'B' },
  { label: 'Arcane Sight', weight: 1, element: 'Arcane', grade: 'B' },
  { label: 'Petrification Touch', weight: 1, element: 'Earth', grade: 'B' },
  { label: 'Acid Touch', weight: 1, element: 'Poison', grade: 'B' },
  { label: 'Magnetism Control', weight: 1, element: 'Metal', grade: 'B' },
  { label: 'Metal Shaping', weight: 1, element: 'Metal', grade: 'B' },
  { label: 'Radiation Emission', weight: 1, element: 'Void', grade: 'B' },
  { label: 'Sonic Boom', weight: 1, element: 'Sound', grade: 'B' },
  { label: 'Fear Aura', weight: 1, element: 'Psychic', grade: 'B' },
  { label: 'Berserker Frenzy', weight: 1, element: 'Fire', grade: 'B' },
  { label: 'Indomitable Rage', weight: 1, element: 'Fire', grade: 'B' },
  { label: 'Gravity Press', weight: 1, element: 'Gravity', grade: 'B' },
  { label: 'Shadow Step', weight: 1, element: 'Shadow', grade: 'B' },
  { label: 'Darkness Veil', weight: 1, element: 'Shadow', grade: 'B' },
  { label: 'Mind Blast', weight: 1, element: 'Psychic', grade: 'B' },
  { label: 'Blood Manipulation', weight: 1, element: 'Blood', grade: 'B' },
  { label: 'Arcane Torrent', weight: 1, element: 'Arcane', grade: 'B' },
  { label: 'Blizzard Breath', weight: 1, element: 'Ice', grade: 'B' },
  { label: 'Earth Spike Barrage', weight: 1, element: 'Earth', grade: 'B' },
  { label: 'Mimic', weight: 1, element: 'Arcane', grade: 'B' },
  { label: 'Mirror Copy', weight: 1, element: 'Arcane', grade: 'B' },
  { label: 'Power Siphon', weight: 1, element: 'Arcane', grade: 'B' },
  { label: 'Flame Burst', weight: 1, element: 'Fire', grade: 'B' },
  { label: 'Time Sense', weight: 1, element: 'Time', grade: 'B' },
  { label: 'Soul Sight', weight: 1, element: 'Soul', grade: 'B' },
  { label: 'Combat Flow State', weight: 1, element: 'Neutral', grade: 'B' },
  { label: 'Battle Precognition', weight: 1, element: 'Psychic', grade: 'B' },
  { label: 'Perfect Parry', weight: 1, element: 'Neutral', grade: 'B' },
  { label: 'Counter-Strike Reflex', weight: 1, element: 'Neutral', grade: 'B' },
  { label: 'Warrior Trance', weight: 1, element: 'Neutral', grade: 'B' },
  { label: 'Arcane Infusion', weight: 1, element: 'Arcane', grade: 'B' },
  { label: 'Runic Ward', weight: 1, element: 'Arcane', grade: 'B' },
  { label: 'Forge Blessing', weight: 1, element: 'Metal', grade: 'B' },
  { label: 'Crystal Armor', weight: 1, element: 'Earth', grade: 'B' },
  { label: 'Stone Endurance', weight: 1, element: 'Earth', grade: 'B' },
  { label: 'Ancestor Spirit', weight: 1, element: 'Soul', grade: 'B' },

  // ── C TIER (70) — rare power ──
  { label: 'Invisibility', weight: 1, element: 'Shadow', grade: 'C' },
  { label: 'Aura Reading', weight: 1, element: 'Psychic', grade: 'C' },
  { label: 'Smoke Bomb', weight: 1, element: 'Shadow', grade: 'C' },
  { label: 'Backstab', weight: 1, element: 'Shadow', grade: 'C' },
  { label: 'Sneak Attack', weight: 1, element: 'Shadow', grade: 'C' },
  { label: 'Vanishing Act', weight: 1, element: 'Shadow', grade: 'C' },
  { label: 'Poison Blade', weight: 1, element: 'Poison', grade: 'C' },
  { label: 'Sacred Heal', weight: 1, element: 'Light', grade: 'C' },
  { label: 'Turn Undead', weight: 1, element: 'Soul', grade: 'C' },
  { label: 'Radiant Strike', weight: 1, element: 'Light', grade: 'C' },
  { label: 'Channel Divinity', weight: 1, element: 'Light', grade: 'C' },
  { label: 'Holy Strike', weight: 1, element: 'Light', grade: 'C' },
  { label: 'Shield Slam', weight: 1, element: 'Light', grade: 'C' },
  { label: 'Aura of Retribution', weight: 1, element: 'Light', grade: 'C' },
  { label: 'Lay on Hands', weight: 1, element: 'Light', grade: 'C' },
  { label: 'Consecrated Ground', weight: 1, element: 'Light', grade: 'C' },
  { label: 'Druidic Wild Shape', weight: 1, element: 'Nature', grade: 'C' },
  { label: "Hunter's Mark", weight: 1, element: 'Nature', grade: 'C' },
  { label: 'Volley Shot', weight: 1, element: 'Wind', grade: 'C' },
  { label: 'Beast Bond', weight: 1, element: 'Nature', grade: 'C' },
  { label: 'Terrain Mastery', weight: 1, element: 'Nature', grade: 'C' },
  { label: 'Predator Stance', weight: 1, element: 'Nature', grade: 'C' },
  { label: 'Precision Strike', weight: 1, element: 'Neutral', grade: 'C' },
  { label: 'Dual Strike', weight: 1, element: 'Neutral', grade: 'C' },
  { label: 'Parry', weight: 1, element: 'Neutral', grade: 'C' },
  { label: 'Shield Block', weight: 1, element: 'Neutral', grade: 'C' },
  { label: 'Reckless Attack', weight: 1, element: 'Fire', grade: 'C' },
  { label: 'Courage Aura', weight: 1, element: 'Light', grade: 'C' },
  { label: 'Spirit Walk', weight: 1, element: 'Soul', grade: 'C' },
  { label: 'Spirit Guide', weight: 1, element: 'Soul', grade: 'C' },
  { label: 'Ancestor Favor', weight: 1, element: 'Soul', grade: 'C' },
  { label: "Nature's Grasp", weight: 1, element: 'Nature', grade: 'C' },
  { label: 'Storm Circle', weight: 1, element: 'Lightning', grade: 'C' },
  { label: 'Bomb Toss', weight: 1, element: 'Fire', grade: 'C' },
  { label: 'Smoke Screen', weight: 1, element: 'Shadow', grade: 'C' },
  { label: 'Warchief Rally', weight: 1, element: 'Neutral', grade: 'C' },
  { label: 'Battle Cry', weight: 1, element: 'Neutral', grade: 'C' },
  { label: 'Divine Smite', weight: 1, element: 'Light', grade: 'C' },
  { label: 'Arcane Memory', weight: 1, element: 'Arcane', grade: 'C' },
  { label: 'Inspire Greatness', weight: 1, element: 'Sound', grade: 'C' },
  { label: 'Heroic Tale', weight: 1, element: 'Sound', grade: 'C' },
  { label: 'Cutting Words', weight: 1, element: 'Sound', grade: 'C' },
  { label: 'Song of Victory', weight: 1, element: 'Sound', grade: 'C' },
  { label: 'Runic Memory', weight: 1, element: 'Arcane', grade: 'C' },
  { label: 'Stone Call', weight: 1, element: 'Earth', grade: 'C' },
  { label: 'Tremor Sense', weight: 1, element: 'Earth', grade: 'C' },
  { label: 'Shadow Blade', weight: 1, element: 'Shadow', grade: 'C' },
  { label: 'Trickster Gambit', weight: 1, element: 'Chaos', grade: 'C' },
  { label: 'Perfect Bluff', weight: 1, element: 'Chaos', grade: 'C' },
  { label: 'Arcane Barrier', weight: 1, element: 'Arcane', grade: 'C' },
  { label: 'Fire Breath', weight: 1, element: 'Fire', grade: 'C' },
  { label: 'Venom Spit', weight: 1, element: 'Poison', grade: 'C' },
  { label: 'Stone Skin', weight: 1, element: 'Earth', grade: 'C' },
  { label: 'Troll Blood', weight: 1, element: 'Blood', grade: 'C' },
  { label: 'War Drums', weight: 1, element: 'Neutral', grade: 'C' },
  { label: 'Primal Fury', weight: 1, element: 'Fire', grade: 'C' },
  { label: 'Crushing Blow', weight: 1, element: 'Earth', grade: 'C' },
  { label: 'Inspire Courage', weight: 1, element: 'Sound', grade: 'C' },
  { label: 'Bardic Lore', weight: 1, element: 'Sound', grade: 'C' },
  { label: "Nature's Memory", weight: 1, element: 'Nature', grade: 'C' },
  { label: 'Iron Resolve', weight: 1, element: 'Neutral', grade: 'C' },
  { label: 'Ritual Circle', weight: 1, element: 'Arcane', grade: 'C' },
  { label: 'Prismatic Spray', weight: 1, element: 'Arcane', grade: 'C' },
  { label: 'Toxin Resistance', weight: 1, element: 'Poison', grade: 'C' },
  { label: 'Scavenge Protocol', weight: 1, element: 'Neutral', grade: 'C' },
  { label: "Hunter's Instinct", weight: 1, element: 'Nature', grade: 'C' },
  { label: 'Blade Dancing', weight: 1, element: 'Wind', grade: 'C' },
  { label: 'Flash Step', weight: 1, element: 'Wind', grade: 'C' },
  { label: 'Iron Body', weight: 1, element: 'Metal', grade: 'C' },
  { label: 'Feral Senses', weight: 1, element: 'Nature', grade: 'C' },

  // ── D TIER (70) — uncommon power ──
  { label: 'Evasion', weight: 1, element: 'Shadow', grade: 'D' },
  { label: 'Cunning Action', weight: 1, element: 'Shadow', grade: 'D' },
  { label: 'Uncanny Dodge', weight: 1, element: 'Shadow', grade: 'D' },
  { label: 'Quick Draw', weight: 1, element: 'Neutral', grade: 'D' },
  { label: 'Adaptability', weight: 1, element: 'Neutral', grade: 'D' },
  { label: 'Iron Will', weight: 1, element: 'Neutral', grade: 'D' },
  { label: 'Stubborn Survival', weight: 1, element: 'Neutral', grade: 'D' },
  { label: 'Danger Sense', weight: 1, element: 'Psychic', grade: 'D' },
  { label: 'Pain Push', weight: 1, element: 'Neutral', grade: 'D' },
  { label: 'Primal Instinct', weight: 1, element: 'Nature', grade: 'D' },
  { label: 'Relentless Stand', weight: 1, element: 'Neutral', grade: 'D' },
  { label: 'Hardy Constitution', weight: 1, element: 'Nature', grade: 'D' },
  { label: 'Bloodlust', weight: 1, element: 'Blood', grade: 'D' },
  { label: 'Pain Immunity', weight: 1, element: 'Neutral', grade: 'D' },
  { label: 'Savage Fortitude', weight: 1, element: 'Neutral', grade: 'D' },
  { label: 'Reckless Abandon', weight: 1, element: 'Chaos', grade: 'D' },
  { label: 'Carnage Sense', weight: 1, element: 'Blood', grade: 'D' },
  { label: 'Darkness Feel', weight: 1, element: 'Shadow', grade: 'D' },
  { label: 'Pack Tactics', weight: 1, element: 'Neutral', grade: 'D' },
  { label: 'Snarl', weight: 1, element: 'Nature', grade: 'D' },
  { label: 'Tackle', weight: 1, element: 'Neutral', grade: 'D' },
  { label: 'Pounce', weight: 1, element: 'Nature', grade: 'D' },
  { label: 'Camouflage', weight: 1, element: 'Nature', grade: 'D' },
  { label: 'Burrow', weight: 1, element: 'Earth', grade: 'D' },
  { label: 'Aquatic Breathing', weight: 1, element: 'Water', grade: 'D' },
  { label: 'Tree Climbing', weight: 1, element: 'Nature', grade: 'D' },
  { label: 'Swarm Form', weight: 1, element: 'Nature', grade: 'D' },
  { label: 'Echolocation', weight: 1, element: 'Sound', grade: 'D' },
  { label: 'Heat Sense', weight: 1, element: 'Fire', grade: 'D' },
  { label: 'Cold Resistance', weight: 1, element: 'Ice', grade: 'D' },
  { label: 'Fire Resistance', weight: 1, element: 'Fire', grade: 'D' },
  { label: 'Acid Resistance', weight: 1, element: 'Poison', grade: 'D' },
  { label: 'Holy Resilience', weight: 1, element: 'Light', grade: 'D' },
  { label: 'Dark Resistance', weight: 1, element: 'Shadow', grade: 'D' },
  { label: 'Toughened Skin', weight: 1, element: 'Neutral', grade: 'D' },
  { label: 'Natural Armor', weight: 1, element: 'Nature', grade: 'D' },
  { label: 'Trap Sense', weight: 1, element: 'Neutral', grade: 'D' },
  { label: 'Foraging', weight: 1, element: 'Nature', grade: 'D' },
  { label: 'Night Vision', weight: 1, element: 'Shadow', grade: 'D' },
  { label: 'Keen Nose', weight: 1, element: 'Nature', grade: 'D' },
  { label: 'Low Light Vision', weight: 1, element: 'Shadow', grade: 'D' },
  { label: 'Tremorsense', weight: 1, element: 'Earth', grade: 'D' },
  { label: 'Combat Hardening', weight: 1, element: 'Neutral', grade: 'D' },
  { label: 'Battlefield Awareness', weight: 1, element: 'Neutral', grade: 'D' },
  { label: 'Iron Gut', weight: 1, element: 'Neutral', grade: 'D' },
  { label: 'Weapon Affinity', weight: 1, element: 'Neutral', grade: 'D' },
  { label: 'Shield Expertise', weight: 1, element: 'Light', grade: 'D' },
  { label: 'Mounted Prowess', weight: 1, element: 'Neutral', grade: 'D' },
  { label: 'Light Footing', weight: 1, element: 'Wind', grade: 'D' },
  { label: 'Quick Recovery', weight: 1, element: 'Nature', grade: 'D' },
  { label: 'Veteran Edge', weight: 1, element: 'Neutral', grade: 'D' },
  { label: 'Tactical Awareness', weight: 1, element: 'Neutral', grade: 'D' },
  { label: 'Ambush Training', weight: 1, element: 'Shadow', grade: 'D' },
  { label: 'Enduring March', weight: 1, element: 'Neutral', grade: 'D' },
  { label: 'Strong Grip', weight: 1, element: 'Neutral', grade: 'D' },
  { label: 'Intimidate', weight: 1, element: 'Psychic', grade: 'D' },
  { label: 'Provoke', weight: 1, element: 'Fire', grade: 'D' },
  { label: 'Rally Cry (Minor)', weight: 1, element: 'Sound', grade: 'D' },
  { label: 'Focus Stance', weight: 1, element: 'Neutral', grade: 'D' },
  { label: 'Defensive Stance', weight: 1, element: 'Neutral', grade: 'D' },
  { label: 'Weapon Throw', weight: 1, element: 'Neutral', grade: 'D' },
  { label: 'Trip Attack', weight: 1, element: 'Neutral', grade: 'D' },
  { label: 'Disarm', weight: 1, element: 'Neutral', grade: 'D' },
  { label: 'Grapple Mastery', weight: 1, element: 'Neutral', grade: 'D' },
  { label: 'Headbutt', weight: 1, element: 'Neutral', grade: 'D' },
  { label: 'Shoulder Bash', weight: 1, element: 'Neutral', grade: 'D' },
  { label: 'Footwork', weight: 1, element: 'Wind', grade: 'D' },
  { label: 'Parting Blow', weight: 1, element: 'Neutral', grade: 'D' },
  { label: 'Overpower', weight: 1, element: 'Neutral', grade: 'D' },
  { label: 'Pin', weight: 1, element: 'Neutral', grade: 'D' },

  // ── E TIER (70) — weak power ──
  { label: 'Minor Healing', weight: 1, element: 'Nature', grade: 'E' },
  { label: 'Dim Light Conjure', weight: 1, element: 'Light', grade: 'E' },
  { label: 'Small Spark', weight: 1, element: 'Lightning', grade: 'E' },
  { label: 'Pebble Toss', weight: 1, element: 'Earth', grade: 'E' },
  { label: 'Weak Acid Spit', weight: 1, element: 'Poison', grade: 'E' },
  { label: 'Minor Telepathy', weight: 1, element: 'Psychic', grade: 'E' },
  { label: 'Shadow Whisper', weight: 1, element: 'Shadow', grade: 'E' },
  { label: 'Ember Touch', weight: 1, element: 'Fire', grade: 'E' },
  { label: 'Cool Breeze', weight: 1, element: 'Wind', grade: 'E' },
  { label: 'Slippery Field', weight: 1, element: 'Water', grade: 'E' },
  { label: 'Minor Shapeshift', weight: 1, element: 'Nature', grade: 'E' },
  { label: 'Weak Compulsion', weight: 1, element: 'Psychic', grade: 'E' },
  { label: 'Faint Glow', weight: 1, element: 'Light', grade: 'E' },
  { label: 'Muffled Step', weight: 1, element: 'Shadow', grade: 'E' },
  { label: 'Tiny Tremor', weight: 1, element: 'Earth', grade: 'E' },
  { label: 'Leaf Shield', weight: 1, element: 'Nature', grade: 'E' },
  { label: 'Sour Stench', weight: 1, element: 'Poison', grade: 'E' },
  { label: 'Cold Snap', weight: 1, element: 'Ice', grade: 'E' },
  { label: 'Sparkling Aura', weight: 1, element: 'Light', grade: 'E' },
  { label: 'Phantom Whistle', weight: 1, element: 'Sound', grade: 'E' },
  { label: 'Minor Illusion', weight: 1, element: 'Arcane', grade: 'E' },
  { label: 'Dowsing', weight: 1, element: 'Arcane', grade: 'E' },
  { label: 'Weak Barrier', weight: 1, element: 'Arcane', grade: 'E' },
  { label: 'Basic Levitation', weight: 1, element: 'Gravity', grade: 'E' },
  { label: 'Whisper Sending', weight: 1, element: 'Sound', grade: 'E' },
  { label: 'Mud Ball', weight: 1, element: 'Earth', grade: 'E' },
  { label: 'Fog Breath', weight: 1, element: 'Water', grade: 'E' },
  { label: 'Trembling Touch', weight: 1, element: 'Earth', grade: 'E' },
  { label: 'Dull Ache', weight: 1, element: 'Psychic', grade: 'E' },
  { label: 'Faint Curse', weight: 1, element: 'Shadow', grade: 'E' },
  { label: 'Static Touch', weight: 1, element: 'Lightning', grade: 'E' },
  { label: 'Weak Bind', weight: 1, element: 'Arcane', grade: 'E' },
  { label: 'Itch Inducement', weight: 1, element: 'Nature', grade: 'E' },
  { label: 'Minor Slow', weight: 1, element: 'Time', grade: 'E' },
  { label: 'Puff of Smoke', weight: 1, element: 'Shadow', grade: 'E' },
  { label: 'Stumble Field', weight: 1, element: 'Arcane', grade: 'E' },
  { label: 'Blurry Vision', weight: 1, element: 'Psychic', grade: 'E' },
  { label: 'Mild Nausea', weight: 1, element: 'Poison', grade: 'E' },
  { label: 'Weak Push', weight: 1, element: 'Wind', grade: 'E' },
  { label: 'Slippery Hands', weight: 1, element: 'Water', grade: 'E' },
  { label: 'Dim Flame', weight: 1, element: 'Fire', grade: 'E' },
  { label: 'Brittle Ground', weight: 1, element: 'Earth', grade: 'E' },
  { label: 'Minor Chill', weight: 1, element: 'Ice', grade: 'E' },
  { label: 'Damp Aura', weight: 1, element: 'Water', grade: 'E' },
  { label: 'Hair Stand', weight: 1, element: 'Lightning', grade: 'E' },
  { label: 'Pale Flash', weight: 1, element: 'Light', grade: 'E' },
  { label: 'Faint Echo', weight: 1, element: 'Sound', grade: 'E' },
  { label: 'Vague Feeling', weight: 1, element: 'Psychic', grade: 'E' },
  { label: 'Weak Bolt', weight: 1, element: 'Lightning', grade: 'E' },
  { label: 'Wilt Touch', weight: 1, element: 'Nature', grade: 'E' },
  { label: 'Minor Drain', weight: 1, element: 'Soul', grade: 'E' },
  { label: 'Limp Shadow', weight: 1, element: 'Shadow', grade: 'E' },
  { label: 'Fumble Hex', weight: 1, element: 'Chaos', grade: 'E' },
  { label: 'Minor Fear', weight: 1, element: 'Psychic', grade: 'E' },
  { label: 'Faint Howl', weight: 1, element: 'Sound', grade: 'E' },
  { label: 'Weak Gravity Shift', weight: 1, element: 'Gravity', grade: 'E' },
  { label: 'Lackluster Bolt', weight: 1, element: 'Arcane', grade: 'E' },
  { label: 'Puddle Conjure', weight: 1, element: 'Water', grade: 'E' },
  { label: 'Minor Rust', weight: 1, element: 'Metal', grade: 'E' },
  { label: 'Feeble Shock', weight: 1, element: 'Lightning', grade: 'E' },
  { label: 'Soft Wind', weight: 1, element: 'Wind', grade: 'E' },
  { label: 'Dim Soul Sight', weight: 1, element: 'Soul', grade: 'E' },
  { label: 'Weak Blood Sense', weight: 1, element: 'Blood', grade: 'E' },
  { label: 'Crack Stone', weight: 1, element: 'Earth', grade: 'E' },
  { label: 'Paper Cut Mastery', weight: 1, element: 'Metal', grade: 'E' },
  { label: 'Faint Psychometry', weight: 1, element: 'Psychic', grade: 'E' },
  { label: 'Mild Magnetism', weight: 1, element: 'Metal', grade: 'E' },
  { label: 'Weak Time Sense', weight: 1, element: 'Time', grade: 'E' },
  { label: 'Dim Aura', weight: 1, element: 'Arcane', grade: 'E' },
  { label: 'Faint Cosmic Awareness', weight: 1, element: 'Cosmic', grade: 'E' },

  // ── F TIER (80) — common / joke powers ──
  { label: 'Slightly Louder Voice', weight: 1, element: 'Sound', grade: 'F' },
  { label: 'Ability to Open Jars', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Perfect Parking', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Uncanny Balance', weight: 1, element: 'Wind', grade: 'F' },
  { label: 'Knowing When Food is Done', weight: 1, element: 'Fire', grade: 'F' },
  { label: 'Minor Warmth Generation', weight: 1, element: 'Fire', grade: 'F' },
  { label: 'Always Finding Parking', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Mild Stench Immunity', weight: 1, element: 'Neutral', grade: 'F' },
  { label: "Dog's Sense of Direction", weight: 1, element: 'Nature', grade: 'F' },
  { label: 'Slightly Better at Math', weight: 1, element: 'Arcane', grade: 'F' },
  { label: 'Reading Very Fast', weight: 1, element: 'Arcane', grade: 'F' },
  { label: 'Never Gets Lost (Indoors)', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Can Communicate With Fish (Badly)', weight: 1, element: 'Water', grade: 'F' },
  { label: 'Mild Clairvoyance (Only Trivia)', weight: 1, element: 'Psychic', grade: 'F' },
  { label: 'Knows What the Weather Is (Wrong)', weight: 1, element: 'Wind', grade: 'F' },
  { label: 'Can Whistle Really Well', weight: 1, element: 'Sound', grade: 'F' },
  { label: 'Infinite Patience (For One Thing)', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Never Burns Toast', weight: 1, element: 'Fire', grade: 'F' },
  { label: 'Always Finds a Sock', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Can Smell Rain Coming', weight: 1, element: 'Water', grade: 'F' },
  { label: 'Slightly Better Aim', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Speaks to Insects (They Ignore You)', weight: 1, element: 'Nature', grade: 'F' },
  { label: 'Knows the Lyrics to Every Song (But Slightly Wrong)', weight: 1, element: 'Sound', grade: 'F' },
  { label: 'Can Predict Coin Flips (30% of the Time)', weight: 1, element: 'Chaos', grade: 'F' },
  { label: 'Mild Hypnosis (Only Works on Pigeons)', weight: 1, element: 'Psychic', grade: 'F' },
  { label: 'Alarm Clock Body', weight: 1, element: 'Time', grade: 'F' },
  { label: 'Always Right About the Time', weight: 1, element: 'Time', grade: 'F' },
  { label: 'Mild Telepathy (Only from Cats)', weight: 1, element: 'Psychic', grade: 'F' },
  { label: 'Can Juggle Three Things (Barely)', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Perfectly Mediocre Everything', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Stubbed Toe Immunity', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Slightly Taller in the Morning', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Always Has Exact Change', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Can Find Any Remote Control', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Never Forgets a Name (Only First Names)', weight: 1, element: 'Psychic', grade: 'F' },
  { label: 'Can Open Ketchup Bottles Instantly', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Magnetic for Good Parking Spots', weight: 1, element: 'Metal', grade: 'F' },
  { label: 'Minor Shadow Puppetry', weight: 1, element: 'Shadow', grade: 'F' },
  { label: 'Can Hum Surprisingly Well', weight: 1, element: 'Sound', grade: 'F' },
  { label: 'Never Trips on Flat Surfaces', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Can Sense When Wifi is Slow', weight: 1, element: 'Lightning', grade: 'F' },
  { label: 'Remembers Every Dream (Boring Ones)', weight: 1, element: 'Psychic', grade: 'F' },
  { label: 'Power of Mild Suggestion', weight: 1, element: 'Psychic', grade: 'F' },
  { label: 'Can Fold Laundry Very Fast', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Slightly Better Handwriting', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Parallel Parking Mastery', weight: 1, element: 'Neutral', grade: 'F' },
  { label: "Can See 10 Minutes into the Future (Only Traffic)", weight: 1, element: 'Time', grade: 'F' },
  { label: 'Knows When Pasta is Al Dente', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Super Mediocrity Aura', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Mild Aura of Competence', weight: 1, element: 'Light', grade: 'F' },
  { label: 'Always Lands Butter Side Up', weight: 1, element: 'Chaos', grade: 'F' },
  { label: 'Speaks Fluent Pigeon', weight: 1, element: 'Nature', grade: 'F' },
  { label: 'Paper Airplane Mastery', weight: 1, element: 'Wind', grade: 'F' },
  { label: 'Power of Not Spilling Drinks', weight: 1, element: 'Water', grade: 'F' },
  { label: 'Strong Opinions about Cheese', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Mild Magnetism (For Keys)', weight: 1, element: 'Metal', grade: 'F' },
  { label: 'Can Sneeze Exactly Once', weight: 1, element: 'Wind', grade: 'F' },
  { label: 'Socks Always Match', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Minor Thermostat Manipulation', weight: 1, element: 'Fire', grade: 'F' },
  { label: 'Knows When It Will Rain (Mostly)', weight: 1, element: 'Water', grade: 'F' },
  { label: 'Mild Ability to Identify Cheese by Smell', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Power to Always Get the Last Slice', weight: 1, element: 'Chaos', grade: 'F' },
  { label: 'Very Dry Hands', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Slightly Better Handshake', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Power of Being Kind of Alright', weight: 1, element: 'Neutral', grade: 'F' },
  { label: "Can Open Pickle Jars But That's It", weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Mild Snoring Immunity', weight: 1, element: 'Sound', grade: 'F' },
  { label: 'Always Finds the TV Remote', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Superior at Untying Knots', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Can Successfully Guess Pizza Toppings', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Nose for Wi-Fi Passwords', weight: 1, element: 'Arcane', grade: 'F' },
  { label: 'Mild Aura of Being Slightly Less Annoying', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Immunity to Door Stubbing', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Power of Adequate Mediocrity', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Can Sense When a Movie Is About to Get Good', weight: 1, element: 'Psychic', grade: 'F' },
  { label: 'Power of Knowing Exactly Which Line Will Move Fastest', weight: 1, element: 'Time', grade: 'F' },
  { label: 'Minor Sandwich Optimization', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Can Name Any Movie by 5 Seconds', weight: 1, element: 'Sound', grade: 'F' },
  { label: 'Power to Be Remarkably Average', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'The Ability to Find Parking (Sometimes)', weight: 1, element: 'Neutral', grade: 'F' },
]
