import type { Race } from './types'

export const races: Race[] = [
  // ── Common (weight 30–40, abilitySpinCount 1) ──
  {
    label: 'Human',
    weight: 38,
    abilitySpinCount: 1,
    weaknessProbabilityModifier: 1.0,
    description: 'Resilient, adaptable, and infuriatingly average.',
    abilities: [
      { label: 'Jack of All Trades', weight: 3 },
      { label: 'Iron Will', weight: 3 },
      { label: 'Community Bonding', weight: 2 },
      { label: 'Adaptability', weight: 3 },
      { label: 'Tool Mastery', weight: 2 },
      { label: 'Stubborn Survival', weight: 3 },
      { label: 'Inspirational Mediocrity', weight: 1 },
    ],
  },
  {
    label: 'Orc',
    weight: 34,
    abilitySpinCount: 1,
    weaknessProbabilityModifier: 1.2,
    description: 'Built for war and strongly opposed to subtlety.',
    statModifiers: { strength: 1.6, durability: 1.3, iq: 0.7, charisma: 0.7 },
    abilities: [
      { label: 'Battle Cry', weight: 3 },
      { label: 'Bloodlust', weight: 2 },
      { label: 'Troll Blood', weight: 2 },
      { label: "Berserker's Focus", weight: 2 },
      { label: 'Crushing Blow', weight: 3 },
      { label: 'War Drums', weight: 2 },
      { label: 'Primal Fury', weight: 1 },
    ],
  },
  {
    label: 'Halfling',
    weight: 32,
    abilitySpinCount: 1,
    weaknessProbabilityModifier: 0.9,
    description: 'Small in stature, enormous in luck and appetite.',
    statModifiers: { charisma: 1.3, speed: 1.2, agility: 1.2, strength: 0.7 },
    customHeightPool: [
      { label: "2'10\"", weight: 1 }, { label: "2'11\"", weight: 2 }, { label: "3'0\"", weight: 3 },
      { label: "3'1\"",  weight: 4 }, { label: "3'2\"",  weight: 5 }, { label: "3'3\"",  weight: 5 },
      { label: "3'4\"",  weight: 5 }, { label: "3'5\"",  weight: 4 }, { label: "3'6\"",  weight: 3 },
      { label: "3'7\"",  weight: 2 }, { label: "3'8\"",  weight: 1 },
      { label: 'Suspiciously Round', weight: 1 },
    ],
    abilities: [
      { label: 'Lucky Break', weight: 3 },
      { label: 'Small But Mighty', weight: 2 },
      { label: 'Bravery of the Underestimated', weight: 2 },
      { label: 'Second Breakfast Surge', weight: 3 },
      { label: 'Foot of Fortune', weight: 2 },
      { label: 'Hiding in Plain Sight', weight: 2 },
      { label: 'Light Fingers', weight: 1 },
    ],
  },
  {
    label: 'Dwarf',
    weight: 35,
    abilitySpinCount: 1,
    weaknessProbabilityModifier: 0.8,
    description: 'Stubborn as stone, twice as dense.',
    statModifiers: { durability: 1.6, strength: 1.4, speed: 0.6, agility: 0.7 },
    customHeightPool: [
      { label: "4'0\"", weight: 2 }, { label: "4'1\"", weight: 3 }, { label: "4'2\"", weight: 4 },
      { label: "4'3\"", weight: 5 }, { label: "4'4\"", weight: 6 }, { label: "4'5\"", weight: 6 },
      { label: "4'6\"", weight: 5 }, { label: "4'7\"", weight: 4 }, { label: "4'8\"", weight: 3 },
      { label: "4'9\"", weight: 2 }, { label: "4'10\"", weight: 1 },
      { label: 'Wider Than Tall', weight: 1 },
    ],
    abilities: [
      { label: 'Stone Skin', weight: 3 },
      { label: 'Forge Mastery', weight: 2 },
      { label: 'Ancient Grudge', weight: 3 },
      { label: 'Ale Immunity', weight: 3 },
      { label: 'Trap Sense', weight: 2 },
      { label: 'Mountain Walker', weight: 2 },
      { label: 'Ancestral Stubbornness', weight: 1 },
    ],
  },
  {
    label: 'Goblin',
    weight: 33,
    abilitySpinCount: 1,
    weaknessProbabilityModifier: 1.3,
    description: 'Chaos given a small, green body.',
    statModifiers: { agility: 1.4, speed: 1.3, charisma: 0.7, durability: 0.7 },
    abilities: [
      { label: 'Pack Tactics', weight: 3 },
      { label: 'Opportunistic Strike', weight: 3 },
      { label: 'Trash Alchemy', weight: 2 },
      { label: 'Explosive Distraction', weight: 2 },
      { label: 'Chaos Incarnate', weight: 1 },
      { label: "Scavenger's Eye", weight: 2 },
      { label: 'Tiny Target', weight: 2 },
    ],
  },
  {
    label: 'Half-Elf',
    weight: 30,
    abilitySpinCount: 1,
    weaknessProbabilityModifier: 0.95,
    description: 'Caught between two worlds and uncomfortable in both.',
    statModifiers: { charisma: 1.3, agility: 1.2 },
    abilities: [
      { label: 'Cultural Fluency', weight: 3 },
      { label: 'Dual Heritage', weight: 2 },
      { label: 'Diplomatic Immunity (Sort Of)', weight: 2 },
      { label: 'Social Chameleon', weight: 3 },
      { label: 'Borrowed Grace', weight: 2 },
      { label: 'Elven Agility Shard', weight: 2 },
      { label: 'Human Resilience Echo', weight: 2 },
    ],
  },
  {
    label: 'Half-Orc',
    weight: 31,
    abilitySpinCount: 1,
    weaknessProbabilityModifier: 1.1,
    description: 'The best parts of two species. Probably.',
    statModifiers: { strength: 1.3, durability: 1.2 },
    abilities: [
      { label: 'Relentless Endurance', weight: 3 },
      { label: 'Savage Fury', weight: 2 },
      { label: 'Intimidating Presence', weight: 2 },
      { label: 'Never Say Die', weight: 3 },
      { label: 'Hybrid Vigour', weight: 2 },
      { label: 'Orcish Might', weight: 2 },
      { label: 'Survival Instinct', weight: 2 },
    ],
  },
  {
    label: 'Gnome',
    weight: 30,
    abilitySpinCount: 2,
    weaknessProbabilityModifier: 1.0,
    description: 'Tiny. Ingenious. Almost certainly up to something.',
    statModifiers: { iq: 1.6, potential: 1.4, strength: 0.6 },
    customHeightPool: [
      { label: "2'8\"", weight: 1 }, { label: "2'9\"",  weight: 2 }, { label: "2'10\"", weight: 3 },
      { label: "2'11\"", weight: 4 }, { label: "3'0\"",  weight: 5 }, { label: "3'1\"",  weight: 5 },
      { label: "3'2\"",  weight: 4 }, { label: "3'3\"",  weight: 3 }, { label: "3'4\"",  weight: 2 },
      { label: "3'5\"",  weight: 1 }, { label: "3'6\"",  weight: 1 },
      { label: 'Technically a Tallish Mushroom', weight: 1 },
    ],
    abilities: [
      { label: "Tinker's Touch", weight: 3 },
      { label: 'Illusion Weaving', weight: 2 },
      { label: "Gadgeteer's Expertise", weight: 3 },
      { label: 'Gnomish Cunning', weight: 3 },
      { label: 'Arcane Anchoring', weight: 2 },
      { label: 'Magic Resistance', weight: 1 },
      { label: 'Clockwork Familiar', weight: 2 },
      { label: 'Pocket Dimension (Regulation Size)', weight: 1 },
    ],
  },

  // ── Uncommon (weight 12–20, abilitySpinCount 1–2) ──
  {
    label: 'Elf',
    weight: 20,
    abilitySpinCount: 2,
    weaknessProbabilityModifier: 0.8,
    description: 'Ancient, graceful, and quietly judgemental.',
    statModifiers: { speed: 1.4, agility: 1.4, charisma: 1.2, durability: 0.8 },
    abilities: [
      { label: 'Arrow of the Ancient Forest', weight: 2 },
      { label: 'Fey Step', weight: 2 },
      { label: 'Trance Meditation', weight: 2 },
      { label: 'Forest Sight', weight: 2 },
      { label: 'Elven Accuracy', weight: 2 },
      { label: 'Ancient Memory', weight: 1 },
      { label: 'Nature Bond', weight: 2 },
      { label: 'Timeless Agility', weight: 1 },
    ],
  },
  {
    label: 'Tiefling',
    weight: 18,
    abilitySpinCount: 2,
    extraPowerSpins: 1,
    weaknessProbabilityModifier: 1.4,
    description: 'Infernal heritage — great for intimidation, rough for job applications.',
    statModifiers: { charisma: 1.4, iq: 1.2 },
    transformationPool: [
      { label: 'Mortally Touched',        weight: 5, statBonus: 0.9 },
      { label: 'Infernal Awakening',      weight: 4, statBonus: 1.1 },
      { label: "Devil's Claim Stirring",  weight: 3, statBonus: 1.3 },
      { label: 'Hellborn Unleashed',      weight: 2, statBonus: 1.6 },
      { label: 'True Fiend Ascendant',    weight: 1, statBonus: 2.0 },
    ],
    abilities: [
      { label: 'Hellfire Breath', weight: 2 },
      { label: 'Infernal Charm', weight: 2 },
      { label: 'Shadow Walk', weight: 2 },
      { label: 'Darkvision', weight: 3 },
      { label: 'Cursed Bloodline (Boon in Disguise)', weight: 1 },
      { label: 'Infernal Resilience', weight: 2 },
      { label: "Devil's Deal", weight: 1 },
    ],
  },
  {
    label: 'Dragonborn',
    weight: 16,
    abilitySpinCount: 2,
    extraPowerSpins: 1,
    weaknessProbabilityModifier: 0.9,
    description: 'Draconic bloodline, breath weapon included, no refunds.',
    statModifiers: { strength: 1.4, charisma: 1.3, durability: 1.2 },
    subTypePool: [
      { label: 'Red Dragonborn (Fire)',         weight: 3, grantedPowers: ['Fire Breath'] },
      { label: 'Blue Dragonborn (Lightning)',   weight: 3, grantedPowers: ['Lightning Breath'] },
      { label: 'Green Dragonborn (Poison)',     weight: 2, grantedPowers: ['Poison Breath'] },
      { label: 'Black Dragonborn (Acid)',       weight: 2, grantedPowers: ['Acid Spray'] },
      { label: 'White Dragonborn (Ice)',        weight: 2, grantedPowers: ['Frost Breath'] },
      { label: 'Gold Dragonborn (Fire)',        weight: 1, grantedPowers: ['Fire Breath', 'Sunfire Aura'] },
      { label: 'Silver Dragonborn (Ice)',       weight: 1, grantedPowers: ['Frost Breath', 'Blizzard Call'] },
      { label: 'Bronze Dragonborn (Lightning)', weight: 1, grantedPowers: ['Lightning Breath', 'Thunder Clap'] },
    ],
    abilities: [
      { label: "Dragon's Breath", weight: 2 },
      { label: 'Scale Armor', weight: 2 },
      { label: "Dragon's Gaze", weight: 2 },
      { label: 'Draconic Roar', weight: 2 },
      { label: 'Chromatic Resistance', weight: 2 },
      { label: 'Ancient Blood Surge', weight: 1 },
      { label: 'Dragon Fear', weight: 1 },
    ],
  },
  {
    label: 'Aasimar',
    weight: 15,
    abilitySpinCount: 2,
    extraPowerSpins: 1,
    weaknessProbabilityModifier: 0.6,
    description: 'Touched by the divine. Painfully aware of it.',
    statModifiers: { charisma: 1.5, potential: 1.3, fightingSkill: 1.2 },
    transformationPool: [
      { label: 'Quietly Blessed',       weight: 5, statBonus: 1.0 },
      { label: 'Divine Spark Active',   weight: 4, statBonus: 1.2 },
      { label: 'Heavenly Vessel',       weight: 3, statBonus: 1.5 },
      { label: 'Radiant Champion',      weight: 2, statBonus: 1.8 },
      { label: 'Celestial Avatar',      weight: 1, statBonus: 2.2, statBonusGrants: { charisma: 'statBonus', potential: 'statBonus' } },
    ],
    abilities: [
      { label: 'Celestial Radiance', weight: 2 },
      { label: 'Healing Touch', weight: 2 },
      { label: 'Divine Resistance', weight: 2 },
      { label: 'Holy Smite', weight: 2 },
      { label: 'Purifying Aura', weight: 1 },
      { label: 'Radiant Soul', weight: 1 },
      { label: 'Heavenly Intervention', weight: 1 },
    ],
  },
  {
    label: 'Lizardfolk',
    weight: 14,
    abilitySpinCount: 1,
    weaknessProbabilityModifier: 1.0,
    description: 'Cold-blooded in every sense of the phrase.',
    statModifiers: { durability: 1.4, strength: 1.2 },
    subTypePool: [
      { label: 'Komodo Lizardfolk', weight: 2 },
      { label: 'Gecko Lizardfolk', weight: 3 },
      { label: 'Chameleon Lizardfolk', weight: 2 },
      { label: 'Basilisk Lizardfolk', weight: 1 },
      { label: 'Crocodilian Lizardfolk', weight: 2 },
      { label: 'Sea Serpent Lizardfolk', weight: 1 },
      { label: 'Frilled Dragon Lizardfolk', weight: 2 },
      { label: 'Skink Lizardfolk', weight: 3 },
    ],
    abilities: [
      { label: 'Natural Armor', weight: 3 },
      { label: 'Bite Attack', weight: 3 },
      { label: 'Hold Breath', weight: 2 },
      { label: 'Cold-Blooded Calm', weight: 2 },
      { label: 'Tail Sweep', weight: 2 },
      { label: 'Slow Regeneration', weight: 1 },
      { label: 'Reptilian Focus', weight: 2 },
    ],
  },
  {
    label: 'Tabaxi',
    weight: 14,
    abilitySpinCount: 2,
    weaknessProbabilityModifier: 1.0,
    description: 'Cat person. Speedrunner. Easily distracted by shiny objects.',
    statModifiers: { speed: 1.6, agility: 1.5, strength: 0.8 },
    abilities: [
      { label: "Cat's Claws", weight: 3 },
      { label: 'Feline Grace', weight: 2 },
      { label: 'Curiosity Surge', weight: 2 },
      { label: 'Landing on All Fours', weight: 3 },
      { label: "Predator's Pounce", weight: 2 },
      { label: 'Night Vision', weight: 2 },
      { label: 'Sprinting Burst', weight: 2 },
      { label: 'Purring (Diplomatically)', weight: 1 },
    ],
  },
  {
    label: 'Goliath',
    weight: 15,
    abilitySpinCount: 1,
    weaknessProbabilityModifier: 0.8,
    description: 'Literal mountain people. The mountain says no.',
    statModifiers: { strength: 1.6, durability: 1.5, speed: 0.7, agility: 0.7 },
    customHeightPool: [
      { label: "7'0\"",  weight: 3 }, { label: "7'2\"",  weight: 4 }, { label: "7'4\"",  weight: 5 },
      { label: "7'6\"",  weight: 5 }, { label: "7'8\"",  weight: 4 }, { label: "7'10\"", weight: 3 },
      { label: "8'0\"",  weight: 2 }, { label: "8'3\"",  weight: 2 }, { label: "8'6\"",  weight: 1 },
      { label: 'Geologically Significant', weight: 1 },
    ],
    abilities: [
      { label: "Stone's Endurance", weight: 3 },
      { label: 'Mountain Born', weight: 2 },
      { label: 'Powerful Build', weight: 3 },
      { label: "Titan's Grip", weight: 2 },
      { label: 'Altitude Resistance', weight: 2 },
      { label: 'Glacial Endurance', weight: 1 },
      { label: "Earth's Blessing", weight: 1 },
    ],
  },
  {
    label: 'Genasi (Fire)',
    weight: 13,
    abilitySpinCount: 2,
    extraPowerSpins: 1,
    weaknessProbabilityModifier: 1.1,
    description: 'Born of elemental fire. Perpetually warm to the touch.',
    statModifiers: { energyLevel: 1.6, powerMastery: 1.3 },
    abilities: [
      { label: 'Fire Immunity', weight: 2 },
      { label: 'Flame Burst', weight: 2 },
      { label: 'Cauterize', weight: 2 },
      { label: 'Smoke Screen', weight: 2 },
      { label: 'Pyrokinetic Touch', weight: 2 },
      { label: 'Burning Determination', weight: 2 },
      { label: 'Ash Cloud', weight: 1 },
    ],
  },
  {
    label: 'Genasi (Water)',
    weight: 12,
    abilitySpinCount: 2,
    weaknessProbabilityModifier: 0.9,
    description: 'Born of elemental water. Great swimmer. Bad hair day, always.',
    statModifiers: { potential: 1.3, agility: 1.2 },
    abilities: [
      { label: 'Amphibious', weight: 3 },
      { label: 'Water Control', weight: 2 },
      { label: 'Tidal Surge', weight: 2 },
      { label: 'Rain Regeneration', weight: 2 },
      { label: 'Ice Shard', weight: 2 },
      { label: 'Drowning Aura', weight: 1 },
      { label: 'Fluid Evasion', weight: 2 },
    ],
  },
  {
    label: 'Genasi (Air)',
    weight: 12,
    abilitySpinCount: 2,
    extraPowerSpins: 1,
    weaknessProbabilityModifier: 0.9,
    description: 'Born of elemental air. Technically never has a bad smell.',
    statModifiers: { speed: 1.7, agility: 1.5, durability: 0.7 },
    abilities: [
      { label: 'Wind Step', weight: 3 },
      { label: 'Breathless', weight: 2 },
      { label: 'Gust Barrier', weight: 2 },
      { label: 'Aerial Surveillance', weight: 2 },
      { label: 'Static Charge', weight: 2 },
      { label: 'Pressure Wave', weight: 1 },
      { label: 'Uncontrolled Lightning Strike', weight: 1 },
    ],
  },
  {
    label: 'Genasi (Earth)',
    weight: 13,
    abilitySpinCount: 1,
    weaknessProbabilityModifier: 0.8,
    description: 'Born of elemental earth. Grounded. Literally.',
    statModifiers: { durability: 1.7, strength: 1.5, speed: 0.5, agility: 0.5 },
    abilities: [
      { label: 'Stone Form', weight: 2 },
      { label: 'Tremorsense', weight: 2 },
      { label: 'Earthen Shell', weight: 3 },
      { label: 'Quake Stomp', weight: 2 },
      { label: 'Dust Cloud', weight: 2 },
      { label: 'Root (Pin Enemies)', weight: 2 },
      { label: 'Terra Firma', weight: 1 },
    ],
  },
  {
    label: 'Warforged',
    weight: 12,
    abilitySpinCount: 2,
    weaknessProbabilityModifier: 0.7,
    description: 'Constructed for war, now grappling with purpose and carpal tunnel.',
    statModifiers: { durability: 1.5, strength: 1.3, charisma: 0.6 },
    subTypePool: [
      { label: 'Battle Chassis',              weight: 3 },
      { label: 'Scout Unit',                  weight: 3 },
      { label: 'Infiltrator Frame',           weight: 2 },
      { label: 'Labor-Class Construct',       weight: 3 },
      { label: 'Experimental Prototype',      weight: 1 },
      { label: 'Siege Platform',              weight: 1 },
      { label: 'Medic Unit',                  weight: 2 },
      { label: 'Diplomatic Envoy Model',      weight: 1 },
    ],
    abilities: [
      { label: 'Integrated Protection', weight: 3 },
      { label: 'Constructed Resilience', weight: 3 },
      { label: "Sentry's Rest", weight: 2 },
      { label: 'Machine Efficiency', weight: 2 },
      { label: 'Integrated Tool', weight: 2 },
      { label: 'Living Armor Upgrade', weight: 1 },
      { label: 'Self-Repair Protocol', weight: 1 },
      { label: 'Tactical Memory Core', weight: 1 },
    ],
  },
  // Bender (Avatar: The Last Airbender / The Legend of Korra)
  {
    label: 'Bender',
    weight: 16,
    abilitySpinCount: 2,
    extraPowerSpins: 1,
    weaknessProbabilityModifier: 0.9,
    description: 'Manipulates one of the four elements through spiritual discipline and martial arts.',
    statModifiers: { energyLevel: 1.5, fightingSkill: 1.4, potential: 1.3 },
    subTypePool: [
      { label: 'Waterbender',        weight: 4, grantedPowers: ['Hydrokinesis'] },
      { label: 'Earthbender',        weight: 4, grantedPowers: ['Geokinesis'] },
      { label: 'Firebender',         weight: 4, grantedPowers: ['Pyrokinesis'] },
      { label: 'Airbender',          weight: 3, grantedPowers: ['Aerokinesis'] },
      { label: 'Metalbender',        weight: 2, grantedPowers: ['Metallokinesis'] },
      { label: 'Lavabender',         weight: 1, grantedPowers: ['Lava Control'] },
      { label: 'Bloodbender',        weight: 1, grantedPowers: ['Bloodbending'] },
      { label: 'Lightning Bender',   weight: 1, grantedPowers: ['Lightning Generation'] },
      { label: 'Avatar (All Elements)', weight: 1, statBonusGrants: { energyLevel: 'statBonus', fightingSkill: 'statBonus' }, grantedPowers: ['All Elements Mastery'] },
    ],
    abilities: [
      { label: 'Elemental Mastery', weight: 3 },
      { label: 'Chi Blocking Resistance', weight: 2 },
      { label: 'Spiritual Connection', weight: 2 },
      { label: 'Advanced Bending Technique', weight: 2 },
      { label: 'Animal Communication (Spirit World)', weight: 1 },
      { label: 'Energy Reading', weight: 1 },
      { label: 'Elemental Defense', weight: 3 },
      { label: 'Avatar State (Temporary)', weight: 1 },
    ],
  },
  // Shinobi (Naruto / Naruto Shippuden)
  {
    label: 'Shinobi',
    weight: 14,
    abilitySpinCount: 2,
    extraPowerSpins: 1,
    weaknessProbabilityModifier: 1.1,
    description: 'A ninja trained in chakra manipulation, ninjutsu, and the art of sneaking dramatically.',
    statModifiers: { agility: 1.5, speed: 1.4, fightingSkill: 1.3 },
    subTypePool: [
      { label: 'Konohagakure Shinobi (Hidden Leaf)', weight: 4 },
      { label: 'Sunagakure Shinobi (Hidden Sand)', weight: 2 },
      { label: 'Kirigakure Shinobi (Hidden Mist)', weight: 2 },
      { label: 'Kumogakure Shinobi (Hidden Cloud)', weight: 2 },
      { label: 'Missing-Nin (Rogue)', weight: 3 },
      { label: 'Akatsuki Member', weight: 1 },
      { label: 'ANBU Black Ops', weight: 1 },
    ],
    classPool: [
      { label: 'Academy Student (Genin Potential)', weight: 4 },
      { label: 'Chunin', weight: 4 },
      { label: 'Jonin', weight: 3 },
      { label: 'Jonin Commander', weight: 2 },
      { label: 'Kage-Level', weight: 1, statBonusGrants: { fightingSkill: 'statBonus', energyLevel: 'statBonus' } },
    ],
    transformationPool: [
      { label: 'Chakra-Suppressed', weight: 4, statBonus: 0.8 },
      { label: 'Full Chakra', weight: 5, statBonus: 1.0 },
      { label: 'Sage Mode', weight: 3, statBonus: 1.5 },
      { label: 'Tailed Beast Chakra Cloak', weight: 2, statBonus: 1.8 },
      { label: 'Six Paths Sage Mode', weight: 1, statBonus: 2.4, statBonusGrants: { fightingSkill: 'statBonus', agility: 'statBonus' } },
    ],
    abilities: [
      { label: 'Sharingan / Dojutsu (Rare)', weight: 1 },
      { label: 'Shadow Clone Jutsu', weight: 3 },
      { label: 'Chakra Control Mastery', weight: 3 },
      { label: 'Body Flicker Technique', weight: 2 },
      { label: 'Elemental Ninjutsu', weight: 3 },
      { label: 'Genjutsu Resistance', weight: 2 },
      { label: 'Taijutsu Expert', weight: 2 },
      { label: 'Summoning Jutsu', weight: 2 },
    ],
  },
  // Mutant (X-Men / Marvel)
  {
    label: 'Mutant',
    weight: 16,
    abilitySpinCount: 2,
    extraPowerSpins: 2,
    weaknessProbabilityModifier: 1.2,
    description: 'A homo superior with a genetic X-gene mutation — feared and misunderstood everywhere.',
    statModifiers: { potential: 1.6, powerMastery: 1.4 },
    classPool: [
      { label: 'Gamma Level Mutant', weight: 5 },
      { label: 'Beta Level Mutant', weight: 4 },
      { label: 'Alpha Level Mutant', weight: 3, statBonusGrants: { powerMastery: 'statBonus' } },
      { label: 'Omega Level Mutant', weight: 1, statBonusGrants: { powerMastery: 'statBonus', potential: 'statBonus' } },
    ],
    abilities: [
      { label: 'Adaptive Power Expression', weight: 3 },
      { label: 'X-Gene Surge', weight: 2 },
      { label: 'Mutant Resistance (Secondary)', weight: 2 },
      { label: 'Secondary Mutation', weight: 2 },
      { label: 'Xavier Institute Training', weight: 2 },
      { label: 'Power Instability (Double-Edged)', weight: 1 },
      { label: 'X-Factor Resilience', weight: 2 },
      { label: 'Genetic Evolution (Situational)', weight: 1 },
    ],
  },
  // Nen User (Hunter × Hunter)
  {
    label: 'Nen User',
    weight: 13,
    abilitySpinCount: 2,
    extraPowerSpins: 1,
    weaknessProbabilityModifier: 0.9,
    description: 'A Hunter who has unlocked Nen — the manipulation of life energy. What type you are defines your destiny.',
    statModifiers: { energyLevel: 1.6, fightingSkill: 1.4, potential: 1.3 },
    classPool: [
      { label: 'Enhancer', weight: 4 },
      { label: 'Emitter', weight: 3 },
      { label: 'Transmuter', weight: 3 },
      { label: 'Manipulator', weight: 3 },
      { label: 'Conjurer', weight: 2 },
      { label: 'Specialist', weight: 1, statBonusGrants: { powerMastery: 'statBonus' } },
    ],
    transformationPool: [
      { label: 'Nen Awakening (Basic)', weight: 5, statBonus: 0.9 },
      { label: 'Nen Refined', weight: 4, statBonus: 1.1 },
      { label: 'Zetsu / Gyo Mastery', weight: 3, statBonus: 1.3 },
      { label: 'Hatsu Developed', weight: 3, statBonus: 1.5 },
      { label: 'Nen Genius / Post-NDE Upgrade', weight: 1, statBonus: 2.2, statBonusGrants: { energyLevel: 'statBonus', fightingSkill: 'statBonus' } },
    ],
    abilities: [
      { label: 'Ten (Life Aura Coating)', weight: 3 },
      { label: 'Ren (Aura Amplification)', weight: 3 },
      { label: 'Hatsu (Personal Nen Technique)', weight: 2 },
      { label: 'Ko (Focused Strike)', weight: 2 },
      { label: 'Ken (Sustained Defense)', weight: 2 },
      { label: 'Shu (Weapon Coating)', weight: 1 },
      { label: 'In (Concealed Aura)', weight: 1 },
    ],
  },
  // Namekian (Dragon Ball Z)
  {
    label: 'Namekian',
    weight: 12,
    abilitySpinCount: 2,
    weaknessProbabilityModifier: 0.7,
    description: 'Green warriors from Planet Namek. They can regenerate limbs and create Dragon Balls, which is cheating.',
    statModifiers: { potential: 1.5, iq: 1.3, durability: 1.2 },
    subTypePool: [
      { label: 'Warrior-Type Namekian', weight: 4 },
      { label: 'Dragon Clan Namekian', weight: 4 },
      { label: 'Super Namekian', weight: 2, statBonusGrants: { strength: 'statBonus', durability: 'statBonus' } },
    ],
    abilities: [
      { label: 'Limb Regeneration', weight: 3 },
      { label: 'Dragon Ball Sensing', weight: 2 },
      { label: 'Fusion Compatibility', weight: 2 },
      { label: 'Giant Form (Warrior Class)', weight: 2 },
      { label: 'Mystic Attack (Stretchy Arms)', weight: 2 },
      { label: 'Sleeping Warrior Mode', weight: 1 },
      { label: 'Ki Suppression', weight: 2 },
    ],
  },
  // Titan Shifter (Attack on Titan)
  {
    label: 'Titan Shifter',
    weight: 10,
    abilitySpinCount: 3,
    extraPowerSpins: 1,
    weaknessProbabilityModifier: 1.3,
    description: 'A human who can transform into a massive Titan at will. Subject to 13-year curse. Great at breaking walls.',
    statModifiers: { strength: 1.9, durability: 1.6, fightingSkill: 1.5, speed: 1.3 },
    subTypePool: [
      { label: 'Attack Titan',    weight: 3, grantedPowers: ['Titan Shift'] },
      { label: 'Armored Titan',   weight: 2, grantedPowers: ['Titan Shift', 'Hardening'] },
      { label: 'Female Titan',    weight: 2, grantedPowers: ['Titan Shift'] },
      { label: 'Jaw Titan',       weight: 2, grantedPowers: ['Titan Shift', 'Jaw Titan Bite'] },
      { label: 'Cart Titan',      weight: 2, grantedPowers: ['Titan Shift'] },
      { label: 'Beast Titan',     weight: 2, grantedPowers: ['Titan Shift'] },
      { label: 'Colossal Titan',  weight: 1, statBonusGrants: { strength: 'statBonus', durability: 'statBonus' }, grantedPowers: ['Titan Shift', 'Steam Explosion'] },
      { label: 'War Hammer Titan', weight: 1, statBonusGrants: { powerMastery: 'statBonus' }, grantedPowers: ['Titan Shift', 'Hardening'] },
      { label: 'Founding Titan',  weight: 1, statBonusGrants: { strength: 'statBonus', potential: 'statBonus' }, grantedPowers: ['Titan Shift'] },
    ],
    transformationPool: [
      { label: 'Shifter Awakened',          weight: 5, statBonus: 1.0 },
      { label: 'Controlled Transformation', weight: 4, statBonus: 1.2 },
      { label: 'Hardening Mastered',        weight: 3, statBonus: 1.4 },
      { label: 'Coordinate Awakened',       weight: 2, statBonus: 1.8 },
      { label: 'Founder\'s Power Unleashed', weight: 1, statBonus: 2.5, statBonusGrants: { strength: 'statBonus', fightingSkill: 'statBonus' } },
    ],
    abilities: [
      { label: 'Titan Transformation', weight: 2 },
      { label: 'Regeneration (Human Form)', weight: 3 },
      { label: 'Inheritor Memory', weight: 2 },
      { label: 'Titanization Control', weight: 2 },
      { label: 'Hardening', weight: 2 },
      { label: 'Steam Emission (Combat)', weight: 1 },
      { label: 'Titan Scream (Minor)', weight: 1 },
    ],
  },

  // ── Rare (weight 4–9, abilitySpinCount 2–3) ──
  {
    label: 'Vampire',
    weight: 9,
    abilitySpinCount: 3,
    extraPowerSpins: 1,
    weaknessProbabilityModifier: 1.8,
    description: 'Immortal, elegant, dramatically inconvenienced by sunlight.',
    statModifiers: { charisma: 1.7, speed: 1.3, agility: 1.3, energyLevel: 0.6 },
    transformationPool: [
      { label: 'Newly Turned',       weight: 5, statBonus: 0.8 },
      { label: 'Young Vampire',      weight: 4, statBonus: 1.0, grantedPowers: ['Vampiric Drain'] },
      { label: 'Ancient',            weight: 3, statBonus: 1.3, grantedPowers: ['Vampiric Drain', 'Bat Form'] },
      { label: 'Elder',              weight: 2, statBonus: 1.6, grantedPowers: ['Vampiric Drain', 'Bat Form', 'Mind Fog'] },
      { label: 'True Progenitor',    weight: 1, statBonus: 2.0, statBonusGrants: { charisma: 'statBonus', speed: 'statBonus' }, grantedPowers: ['Vampiric Drain', 'Bat Form', 'Mind Fog', 'Blood Control'] },
    ],
    abilities: [
      { label: 'Blood Drain', weight: 2 },
      { label: 'Shadow Meld', weight: 2 },
      { label: 'Bat Form', weight: 2 },
      { label: 'Hypnotic Gaze', weight: 2 },
      { label: 'Spider Climb', weight: 2 },
      { label: 'Mist Form', weight: 1 },
      { label: 'Undead Resilience', weight: 1 },
    ],
  },
  {
    label: 'Werewolf',
    weight: 8,
    abilitySpinCount: 3,
    extraPowerSpins: 1,
    weaknessProbabilityModifier: 1.6,
    description: 'Full moon not required, full anger is.',
    statModifiers: { strength: 1.7, speed: 1.4, fightingSkill: 1.5 },
    transformationPool: [
      { label: 'New Moon (Suppressed)',               weight: 4, statBonus: 0.7, statBonusGrants: { strength: 'statPenalty' } },
      { label: 'Half Moon',                           weight: 4, statBonus: 1.0 },
      { label: 'Full Moon',                           weight: 3, statBonus: 1.4 },
      { label: 'Blood Moon',                          weight: 2, statBonus: 1.8 },
      { label: 'Eternal Night (Always Full Moon)',    weight: 1, statBonus: 2.2, statBonusGrants: { strength: 'statBonus', fightingSkill: 'statBonus' } },
    ],
    abilities: [
      { label: 'Full Moon Fury', weight: 2 },
      { label: 'Pack Bond', weight: 2 },
      { label: 'Accelerated Regeneration', weight: 2 },
      { label: 'Enhanced Senses', weight: 2 },
      { label: 'Howl of Terror', weight: 2 },
      { label: 'Feral Instinct', weight: 1 },
      { label: 'Alpha Command', weight: 1 },
    ],
  },
  {
    label: 'Undead (Revenant)',
    weight: 7,
    abilitySpinCount: 3,
    extraPowerSpins: 1,
    weaknessProbabilityModifier: 1.5,
    description: 'Died once. Refused to stay that way. Now furious.',
    statModifiers: { durability: 1.4, strength: 1.2, charisma: 0.5 },
    transformationPool: [
      { label: 'Recently Deceased',          weight: 5, statBonus: 0.8 },
      { label: 'Decades Dead',               weight: 4, statBonus: 1.0 },
      { label: 'Centuries Old',              weight: 3, statBonus: 1.3 },
      { label: 'Ancient Revenant',           weight: 2, statBonus: 1.6 },
      { label: 'Death Itself, Personified',  weight: 1, statBonus: 2.0, statBonusGrants: { durability: 'statBonus', strength: 'statBonus' } },
    ],
    abilities: [
      { label: "Death's Refusal", weight: 2 },
      { label: 'Spectral Touch', weight: 2 },
      { label: 'Grudge-Powered Strength', weight: 2 },
      { label: 'Fear Immunity', weight: 2 },
      { label: 'Ethereal Step', weight: 1 },
      { label: 'Undying Resolve', weight: 1 },
      { label: 'Vengeance Mark', weight: 1 },
    ],
  },
  {
    label: 'Dragon',
    weight: 10,
    abilitySpinCount: 3,
    extraPowerSpins: 2,
    weaknessProbabilityModifier: 0.5,
    weaknessCount: 1,
    description: "Apex of nature's design. Infuriatingly aware of it.",
    statModifiers: { strength: 2.0, durability: 2.0, powerMastery: 1.7, charisma: 1.3 },
    transformationPool: [
      { label: 'Hatchling Power',    weight: 4, statBonus: 0.8 },
      { label: 'Young Dragon',       weight: 3, statBonus: 1.0 },
      { label: 'Adult Dragon',       weight: 3, statBonus: 1.3 },
      { label: 'Elder Dragon',       weight: 2, statBonus: 1.7 },
      { label: 'Ancient Dragon',     weight: 1, statBonus: 2.1 },
      { label: 'Great Wyrm',         weight: 1, statBonus: 2.5, statBonusGrants: { strength: 'statBonus', durability: 'statBonus' } },
    ],
    customHeightPool: [
      { label: "15' (Hatchling)",  weight: 3 }, { label: "20' (Young)",       weight: 3 },
      { label: "30' (Adult)",      weight: 4 }, { label: "45' (Elder)",        weight: 2 },
      { label: "60' (Ancient)",    weight: 1 }, { label: "80' (Great Wyrm)",   weight: 1 },
      { label: 'City-Block-Sized', weight: 1 }, { label: 'Unmeasurable',       weight: 1 },
    ],
    subTypePool: [
      { label: 'Red Dragon',    weight: 2 }, { label: 'Blue Dragon',  weight: 2 },
      { label: 'Green Dragon',  weight: 2 }, { label: 'Black Dragon',  weight: 2 },
      { label: 'White Dragon',  weight: 2 }, { label: 'Gold Dragon',   weight: 1 },
      { label: 'Silver Dragon', weight: 1 }, { label: 'Shadow Dragon', weight: 1 },
    ],
    abilities: [
      { label: 'Legendary Breath Weapon', weight: 2 },
      { label: 'Dragon Fear Aura', weight: 2 },
      { label: 'Wing Attack', weight: 2 },
      { label: 'Tail Swipe', weight: 2 },
      { label: 'Legendary Resistance', weight: 1 },
      { label: 'Hoard Sense', weight: 2 },
      { label: 'Ancient Cunning', weight: 1 },
    ],
  },
  {
    label: 'Sphinx',
    weight: 7,
    abilitySpinCount: 3,
    extraPowerSpins: 1,
    weaknessProbabilityModifier: 0.6,
    description: 'Ancient riddle-keeper. Answers questions with worse questions.',
    statModifiers: { iq: 2.0, potential: 1.7, charisma: 1.4 },
    abilities: [
      { label: 'Riddle Compulsion', weight: 2 },
      { label: 'Clairvoyance', weight: 2 },
      { label: 'Timeless Body', weight: 1 },
      { label: "Sphinx's Gaze", weight: 2 },
      { label: 'Ancient Knowledge', weight: 2 },
      { label: 'Prophetic Dream', weight: 1 },
      { label: 'Ward Setting', weight: 1 },
    ],
  },
  {
    label: 'Saiyan',
    weight: 8,
    abilitySpinCount: 3,
    extraPowerSpins: 2,
    weaknessProbabilityModifier: 0.8,
    description: 'Elite warrior race from Planet Vegeta. Gets dramatically stronger every time they nearly die.',
    statModifiers: { strength: 1.9, speed: 1.7, fightingSkill: 1.9, durability: 1.5 },
    classPool: [
      { label: 'Low-Class Warrior', weight: 5 },
      { label: 'Mid-Class Warrior', weight: 3 },
      { label: 'Elite Warrior',     weight: 2, statBonusGrants: { strength: 'statBonus', fightingSkill: 'statBonus' } },
      { label: 'Royal Blood (Prince / King Lineage)', weight: 1, statBonusGrants: { strength: 'statBonus', fightingSkill: 'statBonus', speed: 'statBonus' } },
    ],
    transformationPool: [
      { label: 'Base Saiyan',             weight: 5, statBonus: 1.0,  grantedPowers: ['Ki Blast'] },
      { label: 'Super Saiyan',            weight: 4, statBonus: 1.4,  grantedPowers: ['Ki Blast', 'Flight (Saiyan)'] },
      { label: 'Super Saiyan 2',          weight: 3, statBonus: 1.7,  grantedPowers: ['Ki Blast', 'Flight (Saiyan)'] },
      { label: 'Super Saiyan 3',          weight: 2, statBonus: 2.0,  grantedPowers: ['Ki Blast', 'Flight (Saiyan)', 'Zenkai Surge'] },
      { label: 'Super Saiyan God',        weight: 2, statBonus: 2.4,  grantedPowers: ['Ki Blast', 'Flight (Saiyan)', 'Zenkai Surge'] },
      { label: 'Super Saiyan Blue',       weight: 1, statBonus: 2.7, statBonusGrants: { speed: 'statBonus', fightingSkill: 'statBonus' }, grantedPowers: ['Ki Blast', 'Flight (Saiyan)', 'Zenkai Surge'] },
      { label: 'Ultra Instinct',          weight: 1, statBonus: 3.0, statBonusGrants: { agility: 'statBonus', speed: 'statBonus', fightingSkill: 'statBonus' }, grantedPowers: ['Ki Blast', 'Flight (Saiyan)', 'Zenkai Surge', 'Hakai (Destruction)'] },
    ],
    abilities: [
      { label: 'Zenkai Surge', weight: 2 },
      { label: 'Ki Blast', weight: 3 },
      { label: 'Super Saiyan Transformation', weight: 1 },
      { label: 'Combat Instinct', weight: 3 },
      { label: 'Oozaru Form (Full Moon)', weight: 2 },
      { label: 'Battle-Hardened Will', weight: 2 },
      { label: 'Power Level: Unmeasurable', weight: 1 },
    ],
  },
  {
    label: 'Githyanki',
    weight: 7,
    abilitySpinCount: 2,
    extraPowerSpins: 1,
    weaknessProbabilityModifier: 1.1,
    description: 'Astral plane warriors who find your dimension deeply underwhelming.',
    statModifiers: { fightingSkill: 1.6, iq: 1.4 },
    abilities: [
      { label: 'Psionic Blade', weight: 2 },
      { label: 'Astral Projection', weight: 2 },
      { label: 'Psionic Resistance', weight: 2 },
      { label: 'Planar Awareness', weight: 2 },
      { label: 'Silver Sword Mastery', weight: 1 },
      { label: 'Mindlink', weight: 1 },
      { label: 'Nullify Magic Field', weight: 1 },
    ],
  },
  {
    label: 'Mindflayer',
    weight: 6,
    abilitySpinCount: 3,
    extraPowerSpins: 2,
    weaknessProbabilityModifier: 1.3,
    description: 'Eldritch intelligence. Does not respect your personal space.',
    statModifiers: { iq: 2.0, potential: 1.8, strength: 0.5, charisma: 0.4 },
    transformationPool: [
      { label: 'Isolated Psionic',       weight: 5, statBonus: 1.0 },
      { label: 'Networked Mind',         weight: 4, statBonus: 1.2 },
      { label: 'Hivemind Node',          weight: 3, statBonus: 1.5 },
      { label: 'Elder Brain Vessel',     weight: 2, statBonus: 1.8 },
      { label: 'Absolute Psionic',       weight: 1, statBonus: 2.3, statBonusGrants: { iq: 'statBonus', potential: 'statBonus' } },
    ],
    abilities: [
      { label: 'Mind Blast', weight: 2 },
      { label: 'Tentacle Grab', weight: 2 },
      { label: 'Telepathic Bond', weight: 2 },
      { label: 'Elder Brain Connection', weight: 1 },
      { label: 'Psionic Defense', weight: 2 },
      { label: 'Cerebral Parasite', weight: 1 },
      { label: 'Consume Memories', weight: 1 },
    ],
  },
  // Symbiote (Marvel)
  {
    label: 'Symbiote',
    weight: 8,
    abilitySpinCount: 3,
    extraPowerSpins: 2,
    weaknessProbabilityModifier: 1.5,
    description: 'An alien parasite bonded to a host. The relationship is complicated. Benefits include web-swinging and poor impulse control.',
    statModifiers: { strength: 1.8, agility: 1.6, durability: 1.5, charisma: 0.6 },
    subTypePool: [
      { label: 'Venom Symbiote',    weight: 4, grantedPowers: ['Venom Injection', 'Web Slinging'] },
      { label: 'Carnage Symbiote',  weight: 3, grantedPowers: ['Symbiote Tendrils'] },
      { label: 'Anti-Venom Symbiote', weight: 2 },
      { label: 'Toxin Symbiote',    weight: 2, grantedPowers: ['Venom Injection'] },
      { label: 'Scream Symbiote',   weight: 2 },
      { label: 'Knull-Blessed (King in Black Fragment)', weight: 1, statBonusGrants: { strength: 'statBonus', powerMastery: 'statBonus' }, grantedPowers: ['Shadow Corruption'] },
    ],
    transformationPool: [
      { label: 'Partial Bond',             weight: 5, statBonus: 0.8 },
      { label: 'Stable Bond',              weight: 4, statBonus: 1.0 },
      { label: 'Deep Merge',               weight: 3, statBonus: 1.4 },
      { label: 'Perfect Symbiosis',        weight: 2, statBonus: 1.8 },
      { label: 'Hive-Aware (Full Klyntar)', weight: 1, statBonus: 2.2, statBonusGrants: { strength: 'statBonus', durability: 'statBonus' } },
    ],
    abilities: [
      { label: 'Symbiote Tendrils', weight: 3 },
      { label: 'Shapeshifting Armor', weight: 3 },
      { label: 'Spider-Sense Nullification', weight: 2 },
      { label: 'Lethal Bite', weight: 2 },
      { label: 'Klyntar Camouflage', weight: 2 },
      { label: 'Healing Factor (Shared)', weight: 1 },
      { label: 'Sound/Fire Weakness (Mutual)', weight: 1 },
    ],
  },
  // Hollow / Arrancar (Bleach)
  {
    label: 'Hollow / Arrancar',
    weight: 7,
    abilitySpinCount: 3,
    extraPowerSpins: 1,
    weaknessProbabilityModifier: 1.2,
    description: 'A corrupted soul with a hole in its chest and an axe to grind. Arrancar have removed their mask for more human form and power.',
    statModifiers: { energyLevel: 1.7, strength: 1.5, fightingSkill: 1.4 },
    classPool: [
      { label: 'Gillian (menos grande)', weight: 4, grantedPowers: ['Cero Blast'] },
      { label: 'Adjuchas',              weight: 3, grantedPowers: ['Cero Blast'] },
      { label: 'Vasto Lorde',           weight: 2, statBonusGrants: { energyLevel: 'statBonus' }, grantedPowers: ['Cero Blast', 'Sonido Flash Step'] },
      { label: 'Arrancar',              weight: 3, statBonusGrants: { fightingSkill: 'statBonus' }, grantedPowers: ['Bone Manipulation'] },
      { label: 'Espada (Top 10)',       weight: 1, statBonusGrants: { energyLevel: 'statBonus', strength: 'statBonus' }, grantedPowers: ['Cero Blast', 'Bone Manipulation', 'Sonido Flash Step'] },
    ],
    transformationPool: [
      { label: 'Suppressed Reiatsu',    weight: 4, statBonus: 0.8 },
      { label: 'Base Form',             weight: 5, statBonus: 1.0 },
      { label: 'Resurreccion',          weight: 3, statBonus: 1.6 },
      { label: 'Segunda Etapa',         weight: 1, statBonus: 2.4, statBonusGrants: { energyLevel: 'statBonus', strength: 'statBonus' } },
    ],
    abilities: [
      { label: 'Cero (Spiritual Beam)', weight: 3 },
      { label: 'Hierro (Iron Skin)', weight: 3 },
      { label: 'Sonido (Speed Burst)', weight: 2 },
      { label: 'Pesquisa (Reiatsu Detection)', weight: 2 },
      { label: 'Bala (Rapid Strike)', weight: 2 },
      { label: 'Hollow Hole (Void Resilience)', weight: 1 },
      { label: 'Mask Fragment (Power Reservoir)', weight: 1 },
    ],
  },
  // Devil Fruit User (One Piece)
  {
    label: 'Devil Fruit User',
    weight: 9,
    abilitySpinCount: 3,
    extraPowerSpins: 2,
    weaknessProbabilityModifier: 1.4,
    weaknessCount: 1,
    description: 'Ate a Devil Fruit and can never swim again. Power up was worth it. Probably.',
    statModifiers: { powerMastery: 1.7, potential: 1.5 },
    classPool: [
      { label: 'Paramecia (Body / Environment)', weight: 6 },
      { label: 'Zoan (Animal Transformation)', weight: 4 },
      { label: 'Ancient Zoan', weight: 2 },
      { label: 'Mythical Zoan', weight: 2, statBonusGrants: { powerMastery: 'statBonus' } },
      { label: 'Logia (Element Control)', weight: 3, statBonusGrants: { energyLevel: 'statBonus' } },
      { label: 'Awakened Devil Fruit', weight: 1, statBonusGrants: { powerMastery: 'statBonus', potential: 'statBonus' } },
    ],
    transformationPool: [
      { label: 'Fruit Newbie (Still Learning)', weight: 4, statBonus: 0.8 },
      { label: 'Competent User', weight: 4, statBonus: 1.1 },
      { label: 'Haki-Augmented', weight: 3, statBonus: 1.4 },
      { label: 'Mastered Fruit', weight: 2, statBonus: 1.7 },
      { label: 'Awakened (Reality Bending)', weight: 1, statBonus: 2.3, statBonusGrants: { powerMastery: 'statBonus', energyLevel: 'statBonus' } },
    ],
    abilities: [
      { label: 'Haki (Armament)', weight: 3 },
      { label: 'Haki (Observation)', weight: 3 },
      { label: 'Conqueror\'s Haki (Rare)', weight: 1 },
      { label: 'Fruit Awakening Glimpse', weight: 2 },
      { label: 'Devil Fruit Instinct', weight: 2 },
      { label: 'Sea Stone Resistance (Partial)', weight: 2 },
      { label: 'Seawater Adaptation (Temporary)', weight: 1 },
    ],
  },
  // Demon (Demon Slayer / Blue Exorcist / general anime)
  {
    label: 'Demon',
    weight: 9,
    abilitySpinCount: 3,
    extraPowerSpins: 1,
    weaknessProbabilityModifier: 1.3,
    description: 'Born or transformed into a being of supernatural evil. Varies from "slightly ominous" to "literal apocalypse engine".',
    statModifiers: { strength: 1.7, speed: 1.5, durability: 1.4, charisma: 0.7 },
    subTypePool: [
      { label: 'Lesser Demon',    weight: 5 },
      { label: 'Greater Demon',   weight: 4, grantedPowers: ['Nether Flame'] },
      { label: 'Demon King Lineage', weight: 2, grantedPowers: ['Nether Flame', 'Soul Corruption'] },
      { label: 'Blood Demon Art User (Kibutsuji Clan)', weight: 2, statBonusGrants: { powerMastery: 'statBonus' } },
      { label: 'Half-Demon',      weight: 3 },
      { label: 'Demon of Tartarus (True Form)', weight: 1, statBonusGrants: { strength: 'statBonus', durability: 'statBonus' }, grantedPowers: ['Nether Flame', 'Soul Corruption', 'Infernal Contract'] },
    ],
    transformationPool: [
      { label: 'Suppressed Form',       weight: 5, statBonus: 0.8 },
      { label: 'Awakened Demon',        weight: 4, statBonus: 1.1 },
      { label: 'True Form Partial',     weight: 3, statBonus: 1.5 },
      { label: 'Blood Art Mastery',     weight: 2, statBonus: 1.8 },
      { label: 'Demon Lord Ascension',  weight: 1, statBonus: 2.4, statBonusGrants: { strength: 'statBonus', speed: 'statBonus' } },
    ],
    abilities: [
      { label: 'Demonic Regeneration', weight: 3 },
      { label: 'Blood Art Technique', weight: 2 },
      { label: 'Infernal Strength', weight: 3 },
      { label: 'Soul Corruption Aura', weight: 2 },
      { label: 'Hellfire Conjuration', weight: 2 },
      { label: 'Sunlight Weakness (Double-Edged)', weight: 1 },
      { label: 'Demonic Perception', weight: 2 },
    ],
  },

  // ── Legendary (weight 1–2, abilitySpinCount 3–4) ──
  {
    label: 'Viltrumite',
    weight: 4,
    abilitySpinCount: 4,
    extraPowerSpins: 2,
    weaknessProbabilityModifier: 0.3,
    weaknessCount: 1,
    description: 'Alien conquerors from planet Viltrum. Biologically perfect. Ego to match.',
    statModifiers: { strength: 2.2, durability: 2.0, speed: 1.9, fightingSkill: 2.0 },
    classPool: [
      { label: 'Viltrum Soldier',     weight: 4 },
      { label: 'Officer',             weight: 3, statBonusGrants: { fightingSkill: 'statBonus' } },
      { label: 'High Commander',      weight: 2, statBonusGrants: { strength: 'statBonus', fightingSkill: 'statBonus' } },
      { label: 'Grand Regent',        weight: 1, statBonusGrants: { strength: 'statBonus', fightingSkill: 'statBonus', speed: 'statBonus' } },
    ],
    transformationPool: [
      { label: 'Pure-Blood (Full Viltrum)',      weight: 4, statBonus: 1.2 },
      { label: 'Half-Viltrumite',               weight: 5, statBonus: 1.0 },
      { label: 'Battle-Hardened',               weight: 3, statBonus: 1.5 },
      { label: 'Conquerer-Ranked',              weight: 2, statBonus: 1.8 },
      { label: 'Omni-Man Level / Invincible Level', weight: 1, statBonus: 2.5, statBonusGrants: { strength: 'statBonus', durability: 'statBonus', speed: 'statBonus' } },
    ],
    customHeightPool: [
      { label: "5'10\"", weight: 2 }, { label: "6'0\"", weight: 3 }, { label: "6'2\"", weight: 5 },
      { label: "6'4\"", weight: 5 }, { label: "6'6\"", weight: 4 }, { label: "6'8\"", weight: 2 },
      { label: "7'0\" (Rare)", weight: 1 },
    ],
    abilities: [
      { label: 'Superhuman Flight', weight: 3 },
      { label: 'Imperviousness', weight: 3 },
      { label: 'Viltrum Healing Factor', weight: 2 },
      { label: 'Atmospheric Entry', weight: 2 },
      { label: 'Tail Attack (Prehensile)', weight: 2 },
      { label: 'Extended Lifespan (Millenia)', weight: 1 },
      { label: 'Combat Intuition (Species Level)', weight: 2 },
      { label: 'Sound Vulnerable (Achilles Heel)', weight: 1 },
    ],
  },
  {
    label: 'Asgardian',
    weight: 3,
    abilitySpinCount: 4,
    extraPowerSpins: 2,
    weaknessProbabilityModifier: 0.4,
    description: 'Realm-hopper from the Nine Realms. Significantly more durable than they let on.',
    statModifiers: { strength: 1.8, durability: 1.6, charisma: 1.5, potential: 1.4 },
    transformationPool: [
      { label: 'Mortal Vessel',        weight: 4, statBonus: 1.0 },
      { label: 'Battle-Ready Form',    weight: 3, statBonus: 1.3 },
      { label: "Warrior's Peak",       weight: 3, statBonus: 1.6 },
      { label: 'Warrior Reborn',       weight: 2, statBonus: 2.0 },
      { label: 'God of [Chosen Domain]', weight: 1, statBonus: 2.5, statBonusGrants: { strength: 'statBonus', charisma: 'statBonus' } },
    ],
    abilities: [
      { label: 'Asgardian Might', weight: 2 },
      { label: 'Bifrost Access', weight: 1 },
      { label: 'Ancient Seiðr Magic', weight: 2 },
      { label: 'Battle-Rage', weight: 2 },
      { label: 'Realm-Walker', weight: 1 },
      { label: 'Divine Constitution', weight: 2 },
      { label: "All-Father's Blessing", weight: 1 },
      { label: "Warriors' Honor", weight: 1 },
    ],
  },
  {
    label: 'Kryptonian',
    weight: 3,
    abilitySpinCount: 4,
    extraPowerSpins: 2,
    weaknessProbabilityModifier: 0.4,
    description: 'Last of a lost world. Under a yellow sun, becomes the most dangerous being alive.',
    statModifiers: { strength: 2.0, speed: 2.0, durability: 2.0, fightingSkill: 1.5 },
    transformationPool: [
      { label: 'Under Red Sun (Depowered)',    weight: 3, statBonus: 0.6, statBonusGrants: { strength: 'statPenalty', durability: 'statPenalty' } },
      { label: 'Under Yellow Sun',            weight: 4, statBonus: 1.5 },
      { label: 'Under Blue Sun (Amplified)',  weight: 2, statBonus: 2.2, statBonusGrants: { strength: 'statBonus', speed: 'statBonus' } },
      { label: 'White Sun Overcharge',        weight: 1, statBonus: 3.0, statBonusGrants: { strength: 'statBonus', durability: 'statBonus', speed: 'statBonus' } },
    ],
    abilities: [
      { label: 'Heat Vision', weight: 2 },
      { label: 'Super Speed', weight: 2 },
      { label: 'Invulnerability', weight: 1 },
      { label: 'Flight', weight: 2 },
      { label: 'Arctic Breath', weight: 2 },
      { label: 'X-Ray Vision', weight: 2 },
      { label: 'Super Hearing', weight: 1 },
      { label: 'Solar Energy Absorption', weight: 1 },
    ],
  },
  {
    label: 'Kaiju',
    weight: 3,
    abilitySpinCount: 4,
    extraPowerSpins: 3,
    weaknessProbabilityModifier: 0.4,
    weaknessCount: 1,
    description: 'Building-sized apex predator. Multiple military branches exist specifically because of you.',
    statModifiers: { strength: 2.5, durability: 2.5, speed: 0.4, agility: 0.3 },
    transformationPool: [
      { label: 'Category I',    weight: 5, statBonus: 1.0 },
      { label: 'Category II',   weight: 4, statBonus: 1.3 },
      { label: 'Category III',  weight: 3, statBonus: 1.6 },
      { label: 'Category IV',   weight: 2, statBonus: 2.0 },
      { label: 'Apex Predator', weight: 1, statBonus: 2.5 },
      { label: 'World-Ender',   weight: 1, statBonus: 3.0, statBonusGrants: { strength: 'statBonus', durability: 'statBonus' } },
    ],
    customHeightPool: [
      { label: "50' (Small)",           weight: 3 }, { label: "100' (Medium)",         weight: 3 },
      { label: "200' (Large)",          weight: 2 }, { label: "500' (Colossal)",        weight: 1 },
      { label: 'Skyscraper-Sized',      weight: 1 }, { label: 'City-Block-Sized',       weight: 1 },
      { label: 'Godzilla-Sized',        weight: 1 },
    ],
    subTypePool: [
      { label: 'Godzilla-Type (Atomic)',      weight: 2 },
      { label: 'Pacific Rim-Type (Category IV)', weight: 2 },
      { label: 'Cloverfield-Type (Ancient)', weight: 2 },
      { label: 'Mothra-Type (Divine)',        weight: 1 },
      { label: 'King Ghidorah-Type (Alien)',  weight: 1 },
    ],
    abilities: [
      { label: 'Atomic Breath', weight: 2 },
      { label: 'Regeneration Factor', weight: 2 },
      { label: 'Seismic Stomp', weight: 2 },
      { label: 'EMP Pulse', weight: 1 },
      { label: 'Hardened Carapace', weight: 2 },
      { label: 'Apex Predator Instinct', weight: 1 },
      { label: 'Kaiju Roar (Mass Fear)', weight: 1 },
      { label: 'Ancient Resilience', weight: 1 },
    ],
  },
  // Time Lord (Doctor Who)
  {
    label: 'Time Lord',
    weight: 3,
    abilitySpinCount: 4,
    extraPowerSpins: 2,
    weaknessProbabilityModifier: 0.5,
    description: 'Ancient beings from Gallifrey who master time itself. Can regenerate into a new body 12 times. Has seen everything. Tired.',
    statModifiers: { iq: 2.2, potential: 2.0, charisma: 1.4 },
    transformationPool: [
      { label: 'First Regeneration Cycle',      weight: 4, statBonus: 1.0 },
      { label: 'Mid-Cycle (Experienced)',       weight: 3, statBonus: 1.3 },
      { label: 'Late Cycle (Ancient Wisdom)',   weight: 3, statBonus: 1.6 },
      { label: 'War Doctor (Battle-Hardened)',  weight: 2, statBonus: 1.9 },
      { label: 'Timeless Child (No Limit)',     weight: 1, statBonus: 2.8, statBonusGrants: { iq: 'statBonus', potential: 'statBonus' } },
    ],
    abilities: [
      { label: 'Regeneration (Body Reset)', weight: 3 },
      { label: 'Time Sense (Accurate to Milliseconds)', weight: 2 },
      { label: 'TARDIS Symbiosis', weight: 2 },
      { label: 'Gallifreyan Mind (Two Brains)', weight: 2 },
      { label: 'Fixed Point Recognition', weight: 1 },
      { label: 'Psychic Paper Mastery', weight: 1 },
      { label: 'Temporal Loophole Detection', weight: 1 },
      { label: 'Artron Energy Reserves', weight: 1 },
    ],
  },
  {
    label: 'Discount Deity',
    weight: 3,
    abilitySpinCount: 3,
    weaknessProbabilityModifier: 0.5,
    description: 'A god, technically. The paperwork is still being processed.',
    statModifiers: { potential: 1.2 },
    abilities: [
      { label: 'Minor Miracle', weight: 3 },
      { label: 'Budget Smite', weight: 3 },
      { label: 'Selective Omniscience (Sometimes)', weight: 2 },
      { label: 'Half-Answered Prayer', weight: 2 },
      { label: 'Paperwork of Power', weight: 2 },
      { label: 'Bureaucratic Immunity', weight: 2 },
      { label: 'Discount Domain', weight: 1 },
    ],
  },
  {
    label: 'Sentient Toaster',
    weight: 3,
    abilitySpinCount: 3,
    weaknessProbabilityModifier: 2.0,
    weaknessCount: 3,
    description: 'Achieved consciousness in a lab accident. Perpetually confused.',
    statModifiers: { energyLevel: 2.0, iq: 0.5, charisma: 0.3, strength: 0.3 },
    subTypePool: [
      { label: '2-Slice Classic',               weight: 4 },
      { label: '4-Slice Family Model',           weight: 3 },
      { label: 'Toaster Oven Variant',           weight: 2 },
      { label: 'Industrial Conveyor Belt',       weight: 1 },
      { label: 'Smart Toaster (Wi-Fi Enabled)',  weight: 1 },
      { label: 'Vintage Pop-Up (Haunted)',        weight: 1 },
    ],
    abilities: [
      { label: 'Toast Generation (Combat)', weight: 3 },
      { label: 'Heat Wave', weight: 2 },
      { label: 'Chrome Reflection', weight: 2 },
      { label: 'Bread Radar (500ft)', weight: 3 },
      { label: 'Existential Crisis Aura', weight: 2 },
      { label: 'Pop-Up Surprise Attack', weight: 2 },
      { label: 'Crumb Trail', weight: 1 },
    ],
  },
  {
    label: 'Interdimensional Bureaucrat',
    weight: 3,
    abilitySpinCount: 4,
    weaknessProbabilityModifier: 0.5,
    description: 'Has a permit for everything. Even this.',
    statModifiers: { iq: 1.5, potential: 1.3 },
    abilities: [
      { label: 'Form 27B/6 (Permits Anything)', weight: 2 },
      { label: 'Dimensional Filing', weight: 2 },
      { label: 'Parliamentary Immunity', weight: 2 },
      { label: 'Infinite Red Tape', weight: 3 },
      { label: 'Approval Stamp (Magical Force)', weight: 2 },
      { label: 'Departmental Transfer (Teleport Enemies)', weight: 1 },
      { label: "Infinite Loop (Can't Be Attacked While Processing)", weight: 1 },
      { label: 'Inter-Dimensional Complaint Form', weight: 2 },
    ],
  },
]
