// races.ts — Race content data for Wheel of Fate.
// 35+ Race entries with weight-based rarity, abilitySpinCount, and weaknessProbabilityModifier.
// No default export. No functions. Static const array only.

import type { Race } from './types'

export const races: Race[] = [
  // ── Common (weight 30–40, abilitySpinCount 1, weaknessProbabilityModifier ~1.0) ──
  {
    label: 'Human',
    weight: 38,
    abilitySpinCount: 1,
    weaknessProbabilityModifier: 1.0,
    description: 'Resilient, adaptable, and infuriatingly average.',
  },
  {
    label: 'Orc',
    weight: 34,
    abilitySpinCount: 1,
    weaknessProbabilityModifier: 1.2,
    description: 'Built for war and strongly opposed to subtlety.',
  },
  {
    label: 'Halfling',
    weight: 32,
    abilitySpinCount: 1,
    weaknessProbabilityModifier: 0.9,
    description: 'Small in stature, enormous in luck and appetite.',
  },
  {
    label: 'Dwarf',
    weight: 35,
    abilitySpinCount: 1,
    weaknessProbabilityModifier: 0.8,
    description: 'Stubborn as stone, twice as dense.',
  },
  {
    label: 'Goblin',
    weight: 33,
    abilitySpinCount: 1,
    weaknessProbabilityModifier: 1.3,
    description: 'Chaos given a small, green body.',
  },
  {
    label: 'Half-Elf',
    weight: 30,
    abilitySpinCount: 1,
    weaknessProbabilityModifier: 0.95,
    description: 'Caught between two worlds and uncomfortable in both.',
  },
  {
    label: 'Half-Orc',
    weight: 31,
    abilitySpinCount: 1,
    weaknessProbabilityModifier: 1.1,
    description: 'The best parts of two species. Probably.',
  },
  {
    label: 'Gnome',
    weight: 30,
    abilitySpinCount: 2,
    weaknessProbabilityModifier: 1.0,
    description: 'Tiny. Ingenious. Almost certainly up to something.',
  },

  // ── Uncommon (weight 12–20, abilitySpinCount 1–2) ──
  {
    label: 'Elf',
    weight: 20,
    abilitySpinCount: 2,
    weaknessProbabilityModifier: 0.8,
    description: 'Ancient, graceful, and quietly judgemental.',
  },
  {
    label: 'Tiefling',
    weight: 18,
    abilitySpinCount: 2,
    weaknessProbabilityModifier: 1.4,
    description: 'Infernal heritage — great for intimidation, rough for job applications.',
  },
  {
    label: 'Dragonborn',
    weight: 16,
    abilitySpinCount: 2,
    weaknessProbabilityModifier: 0.9,
    description: 'Draconic bloodline, breath weapon included, no refunds.',
  },
  {
    label: 'Aasimar',
    weight: 15,
    abilitySpinCount: 2,
    weaknessProbabilityModifier: 0.6,
    description: 'Touched by the divine. Painfully aware of it.',
  },
  {
    label: 'Kobold',
    weight: 18,
    abilitySpinCount: 1,
    weaknessProbabilityModifier: 1.4,
    description: 'Small but highly motivated. Pack tactics enthusiast.',
  },
  {
    label: 'Lizardfolk',
    weight: 14,
    abilitySpinCount: 1,
    weaknessProbabilityModifier: 1.0,
    description: 'Cold-blooded in every sense of the phrase.',
  },
  {
    label: 'Kenku',
    weight: 13,
    abilitySpinCount: 2,
    weaknessProbabilityModifier: 1.1,
    description: 'Can only speak in voices they\'ve heard before. Useful, haunting.',
  },
  {
    label: 'Tabaxi',
    weight: 14,
    abilitySpinCount: 2,
    weaknessProbabilityModifier: 1.0,
    description: 'Cat person. Speedrunner. Easily distracted by shiny objects.',
  },
  {
    label: 'Firbolg',
    weight: 12,
    abilitySpinCount: 2,
    weaknessProbabilityModifier: 0.7,
    description: 'Gentle giant with a firm handshake and a surprising aptitude for magic.',
  },
  {
    label: 'Goliath',
    weight: 15,
    abilitySpinCount: 1,
    weaknessProbabilityModifier: 0.8,
    description: 'Literal mountain people. The mountain says no.',
  },
  {
    label: 'Hobgoblin',
    weight: 14,
    abilitySpinCount: 1,
    weaknessProbabilityModifier: 1.2,
    description: 'Goblins but they made a strategic plan first.',
  },
  {
    label: 'Genasi (Fire)',
    weight: 13,
    abilitySpinCount: 2,
    weaknessProbabilityModifier: 1.1,
    description: 'Born of elemental fire. Perpetually warm to the touch.',
  },
  {
    label: 'Genasi (Water)',
    weight: 12,
    abilitySpinCount: 2,
    weaknessProbabilityModifier: 0.9,
    description: 'Born of elemental water. Great swimmer. Bad hair day, always.',
  },
  {
    label: 'Genasi (Air)',
    weight: 12,
    abilitySpinCount: 2,
    weaknessProbabilityModifier: 0.9,
    description: 'Born of elemental air. Technically never has a bad smell.',
  },
  {
    label: 'Genasi (Earth)',
    weight: 13,
    abilitySpinCount: 1,
    weaknessProbabilityModifier: 0.8,
    description: 'Born of elemental earth. Grounded. Literally.',
  },
  {
    label: 'Changeling',
    weight: 12,
    abilitySpinCount: 2,
    weaknessProbabilityModifier: 1.0,
    description: 'Shapeshifter. Excellent spy. Terrible at keeping secrets about their own nature.',
  },
  {
    label: 'Warforged',
    weight: 12,
    abilitySpinCount: 2,
    weaknessProbabilityModifier: 0.7,
    description: 'Constructed for war, now grappling with purpose and carpal tunnel.',
  },

  // ── Rare (weight 4–9, abilitySpinCount 2–3) ──
  {
    label: 'Vampire',
    weight: 7,
    abilitySpinCount: 3,
    weaknessProbabilityModifier: 1.8,
    description: 'Immortal, elegant, dramatically inconvenienced by sunlight.',
  },
  {
    label: 'Werewolf',
    weight: 6,
    abilitySpinCount: 3,
    weaknessProbabilityModifier: 1.6,
    description: 'Full moon not required, full anger is.',
  },
  {
    label: 'Undead (Revenant)',
    weight: 5,
    abilitySpinCount: 3,
    weaknessProbabilityModifier: 1.5,
    description: 'Died once. Refused to stay that way. Now furious.',
  },
  {
    label: 'Dragon',
    weight: 8,
    abilitySpinCount: 3,
    weaknessProbabilityModifier: 0.5,
    description: 'Apex of nature\'s design. Infuriatingly aware of it.',
  },
  {
    label: 'Sphinx',
    weight: 5,
    abilitySpinCount: 3,
    weaknessProbabilityModifier: 0.6,
    description: 'Ancient riddle-keeper. Answers questions with worse questions.',
  },
  {
    label: 'Djinn',
    weight: 6,
    abilitySpinCount: 3,
    weaknessProbabilityModifier: 0.6,
    description: 'Wish-granter. Finds loopholes you didn\'t know existed.',
  },
  {
    label: 'Githyanki',
    weight: 5,
    abilitySpinCount: 2,
    weaknessProbabilityModifier: 1.1,
    description: 'Astral plane warriors who find your dimension deeply underwhelming.',
  },
  {
    label: 'Mindflayer',
    weight: 4,
    abilitySpinCount: 3,
    weaknessProbabilityModifier: 1.3,
    description: 'Eldritch intelligence. Does not respect your personal space.',
  },

  // ── Legendary (weight 1, abilitySpinCount 3–4) ──
  {
    label: 'Celestial',
    weight: 1,
    abilitySpinCount: 4,
    weaknessProbabilityModifier: 0.4,
    description: 'Literal divine being. Has seen things your philosophy dare not dream of.',
  },
  {
    label: 'Void-Born',
    weight: 1,
    abilitySpinCount: 4,
    weaknessProbabilityModifier: 0.4,
    description: 'Born in the space between spaces. Unsettling to stare at.',
  },
  {
    label: 'Primordial Titan',
    weight: 1,
    abilitySpinCount: 4,
    weaknessProbabilityModifier: 0.4,
    description: 'The oldest thing in any room. By an enormous margin.',
  },
  {
    label: 'Discount Deity',
    weight: 1,
    abilitySpinCount: 3,
    weaknessProbabilityModifier: 0.5,
    description: 'A god, technically. The paperwork is still being processed.',
  },
  {
    label: 'Sentient Toaster',
    weight: 1,
    abilitySpinCount: 3,
    weaknessProbabilityModifier: 2.0,
    description: 'Achieved consciousness in a lab accident. Perpetually confused.',
  },
  {
    label: 'Interdimensional Bureaucrat',
    weight: 1,
    abilitySpinCount: 4,
    weaknessProbabilityModifier: 0.5,
    description: 'Has a permit for everything. Even this.',
  },
]
