import type { FlavorLabel } from './types'

// Speed scale: F- = slower than a power walk, mortal mid = athletic sprinter,
// A range = world-record sprinter, S = supersonic, SS-SSS = lightspeed → causality-breaking,
// Cosmic+ = post-mortal pace, Infinite+ = speed beyond infinity.
export const speedLabels: FlavorLabel[] = [
  { label: 'Slower Than a Power Walk',                       weight: 4, tier: 'F-',            score: 2,   color: '#2c2c2c' },
  { label: 'Outrun by Honest Effort',                        weight: 4, tier: 'F',             score: 5,   color: '#404040' },
  { label: 'Mall Pace',                                      weight: 4, tier: 'F+',            score: 8,   color: '#525252' },
  { label: 'Below-Average Jogger',                           weight: 6, tier: 'E-',            score: 11,  color: '#4b5563' },
  { label: 'Average Foot Speed',                             weight: 6, tier: 'E',             score: 14,  color: '#64748b' },
  { label: 'Quick on Their Feet',                            weight: 6, tier: 'E+',            score: 17,  color: '#94a3b8' },
  { label: 'High-School Track Star',                         weight: 8, tier: 'D-',            score: 20,  color: '#14532d' },
  { label: 'College-Athlete Sprinter',                       weight: 8, tier: 'D',             score: 23,  color: '#166534' },
  { label: 'Conference-Champion Pace',                       weight: 8, tier: 'D+',            score: 26,  color: '#22c55e' },
  { label: 'Pro-League Fast',                                weight: 8, tier: 'C-',            score: 30,  color: '#047857' },
  { label: 'Nation-Level Sprinter',                          weight: 9, tier: 'C',             score: 34,  color: '#059669' },
  { label: 'Elite Pro Sprinter',                             weight: 8, tier: 'C+',            score: 38,  color: '#10b981' },
  { label: 'Olympic-Caliber',                                weight: 7, tier: 'B-',            score: 42,  color: '#115e59' },
  { label: 'Olympic Medalist Pace',                          weight: 7, tier: 'B',             score: 47,  color: '#0d9488' },
  { label: 'Peak Human Speed',                               weight: 7, tier: 'B+',            score: 52,  color: '#14b8a6' },
  { label: 'World-Record Holder',                            weight: 5, tier: 'A-',            score: 57,  color: '#155e75' },
  { label: 'Faster Than Cameras Can Catch',                  weight: 5, tier: 'A',             score: 62,  color: '#0e7490' },
  { label: 'Bullet-Time Reflexes',                           weight: 5, tier: 'A+',            score: 67,  color: '#06b6d4' },
  { label: 'Breaks the Sound Barrier on Foot',               weight: 4, tier: 'S-',            score: 72,  color: '#0c4a6e' },
  { label: 'Outruns Aircraft',                               weight: 4, tier: 'S',             score: 77,  color: '#0369a1' },
  { label: 'Cannot Be Seen When Moving',                     weight: 4, tier: 'S+',            score: 81,  color: '#0ea5e9' },
  { label: 'Approaches Lightspeed',                          weight: 3, tier: 'SS-',           score: 85,  color: '#1e3a8a' },
  { label: 'Steps Outpace Photons',                          weight: 3, tier: 'SS',            score: 88,  color: '#2563eb' },
  { label: 'Crosses Continents Between Heartbeats',          weight: 3, tier: 'SS+',           score: 91,  color: '#3b82f6' },
  { label: 'Beyond Lightspeed',                              weight: 1, tier: 'SSS-',          score: 94,  color: '#4338ca' },
  { label: 'Speed Is a Concept, Not a Limit',                weight: 1, tier: 'SSS',           score: 97,  color: '#4f46e5' },
  { label: 'Already There Before They Left',                 weight: 1, tier: 'SSS+',          score: 99,  color: '#6366f1' },
  { label: 'Laps the Observable Universe',                   weight: 1, tier: 'Z-',            score: 101, color: '#5b21b6' },
  { label: 'Outruns Causality',                              weight: 1, tier: 'Z',             score: 103, color: '#7c3aed' },
  { label: 'Moves Between Realities Without Pausing',        weight: 1, tier: 'Z+',            score: 105, color: '#8b5cf6' },
  { label: 'Beats Time to Its Own Arrival',                  weight: 0.7, tier: 'ZZ-',           score: 107, color: '#86198f' },
  { label: 'Several Steps Ahead of "Now"',                   weight: 0.7, tier: 'ZZ',            score: 109, color: '#a21caf' },
  { label: 'Already Past the End of Time',                   weight: 0.7, tier: 'ZZ+',           score: 111, color: '#c026d3' },
  { label: 'Speed That Reality Cannot Render',               weight: 0.5, tier: 'ZZZ-',          score: 113, color: '#be185d' },
  { label: 'Motion Without Movement',                        weight: 0.5, tier: 'ZZZ',           score: 115, color: '#db2777' },
  { label: 'Already Done Before They Started',               weight: 0.5, tier: 'ZZZ+',          score: 117, color: '#ec4899' },
  { label: 'Cosmic-Scale Pace',                              weight: 0.35, tier: 'Cosmic-',       score: 119, color: '#0e6b8a' },
  { label: 'Outpaces Galactic Rotation',                     weight: 0.35, tier: 'Cosmic',        score: 121, color: '#0891b2' },
  { label: 'Crosses Cosmoses in a Step',                     weight: 0.35, tier: 'Cosmic+',       score: 123, color: '#06b6d4' },
  { label: 'Speed That Outlives Time',                       weight: 0.25, tier: 'Immortal-',     score: 125, color: '#d946ef' },
  { label: 'Immortal-Class Velocity',                        weight: 0.25, tier: 'Immortal',      score: 127, color: '#ec4899' },
  { label: 'Endless Movement Without Fatigue',               weight: 0.25, tier: 'Immortal+',     score: 129, color: '#f472b6' },
  { label: 'Moves at the Speed of Divine Intent',            weight: 0.2, tier: 'Celestial-',    score: 131, color: '#831843' },
  { label: 'Crosses Divine Planes With a Thought',           weight: 0.2, tier: 'Celestial',     score: 133, color: '#9d174d' },
  { label: 'Even Gods Cannot Track Their Motion',            weight: 0.2, tier: 'Celestial+',    score: 135, color: '#be185d' },
  { label: 'Speed That Predates Time Itself',                weight: 0.15, tier: 'Godly-',        score: 137, color: '#f9a8d4' },
  { label: 'Has Already Arrived in Every Realm',             weight: 0.15, tier: 'Godly',         score: 139, color: '#f472b6' },
  { label: 'Outraces Divine Causation',                      weight: 0.15, tier: 'Godly+',        score: 141, color: '#ec4899' },
  { label: 'Outpaces the Concept of Motion',                 weight: 0.1, tier: 'Primordial-',   score: 143, color: '#d4d4d8' },
  { label: 'Was First Where No First Existed',               weight: 0.1, tier: 'Primordial',    score: 145, color: '#e4e4e7' },
  { label: 'Universe Schedules Around Their Arrival',        weight: 0.1, tier: 'Primordial+',   score: 147, color: '#fafafa' },
  { label: 'Absolute Speed',                                 weight: 0.07, tier: 'Absolute-',     score: 149, color: '#7dd3fc' },
  { label: 'Faster Than Speed Itself',                       weight: 0.07, tier: 'Absolute',      score: 151, color: '#38bdf8' },
  { label: 'Already Past the Finish Line',                   weight: 0.07, tier: 'Absolute+',     score: 153, color: '#0ea5e9' },
  { label: 'Beyond the Idea of Motion',                      weight: 0.05, tier: 'Transcendent-', score: 155, color: '#84cc16' },
  { label: 'Motion Transcends Itself in Their Wake',         weight: 0.05, tier: 'Transcendent',  score: 157, color: '#65a30d' },
  { label: 'They Move and Time Politely Catches Up',         weight: 0.05, tier: 'Transcendent+', score: 159, color: '#4d7c0f' },
  { label: 'Infinite Speed',                                 weight: 0.03, tier: 'Infinite-',     score: 161, color: '#525252' },
  { label: 'Truly Infinite Velocity',                        weight: 0.03, tier: 'Infinite',      score: 163, color: '#262626' },
  { label: 'Beyond Infinite Pace',                           weight: 0.03, tier: 'Infinite+',     score: 165, color: '#000000' },
]
