import type { FlavorLabel } from './types'

export const speedLabels: FlavorLabel[] = [
  // F- (score: 2)
  { label: 'Slower Than a Watched Kettle', weight: 1, tier: 'F-', score: 2, color: 'var(--tier-f-minus)' },
  { label: 'Overtaken by Parked Cars', weight: 1, tier: 'F-', score: 2, color: 'var(--tier-f-minus)' },
  { label: 'Clouds Lap Them', weight: 1, tier: 'F-', score: 2, color: 'var(--tier-f-minus)' },
  { label: 'Trees Are Faster', weight: 1, tier: 'F-', score: 2, color: 'var(--tier-f-minus)' },
  { label: 'Geological Pace', weight: 1, tier: 'F-', score: 2, color: 'var(--tier-f-minus)' },
  { label: 'Slower Than Drying Paint', weight: 1, tier: 'F-', score: 2, color: 'var(--tier-f-minus)' },
  { label: 'Snails Issue Complaint', weight: 1, tier: 'F-', score: 2, color: 'var(--tier-f-minus)' },
  { label: 'Speed: Conceptual Only', weight: 1, tier: 'F-', score: 2, color: 'var(--tier-f-minus)' },
  { label: 'Hair Growth Speed', weight: 1, tier: 'F-', score: 2, color: 'var(--tier-f-minus)' },
  { label: 'Moves in Geological Time', weight: 1, tier: 'F-', score: 2, color: 'var(--tier-f-minus)' },
  { label: 'The Ground Catches Up', weight: 1, tier: 'F-', score: 2, color: 'var(--tier-f-minus)' },
  { label: 'Sedimentary Layer Formation Speed', weight: 1, tier: 'F-', score: 2, color: 'var(--tier-f-minus)' },
  { label: 'Tortoise Filed a Complaint', weight: 1, tier: 'F-', score: 2, color: 'var(--tier-f-minus)' },
  { label: 'Footprints Dry Before They Move', weight: 1, tier: 'F-', score: 2, color: 'var(--tier-f-minus)' },
  { label: 'Dust Settles Before Arrival', weight: 1, tier: 'F-', score: 2, color: 'var(--tier-f-minus)' },
  { label: 'Continental Drift Is Faster', weight: 1, tier: 'F-', score: 2, color: 'var(--tier-f-minus)' },
  { label: 'Speed: Deferred', weight: 1, tier: 'F-', score: 2, color: 'var(--tier-f-minus)' },
  { label: 'Slower Than Bureaucratic Paperwork', weight: 1, tier: 'F-', score: 2, color: 'var(--tier-f-minus)' },
  { label: 'Glacial. Literally.', weight: 1, tier: 'F-', score: 2, color: 'var(--tier-f-minus)' },
  { label: 'Clocks Feel Bad for Them', weight: 1, tier: 'F-', score: 2, color: 'var(--tier-f-minus)' },

  // F (score: 5)
  { label: 'Slow Walk Speed', weight: 1, tier: 'F', score: 5, color: 'var(--tier-f)' },
  { label: 'Stroller Pace', weight: 1, tier: 'F', score: 5, color: 'var(--tier-f)' },
  { label: 'Slow Enough to Be a Fire Hazard', weight: 1, tier: 'F', score: 5, color: 'var(--tier-f)' },
  { label: 'Elderly Tortoise Adjacent', weight: 1, tier: 'F', score: 5, color: 'var(--tier-f)' },
  { label: 'Speed: Technically Present', weight: 1, tier: 'F', score: 5, color: 'var(--tier-f)' },
  { label: 'Moves at a Comfortable Shuffle', weight: 1, tier: 'F', score: 5, color: 'var(--tier-f)' },
  { label: 'Not in a Rush (Ever)', weight: 1, tier: 'F', score: 5, color: 'var(--tier-f)' },
  { label: 'Overtaken in a Crosswalk', weight: 1, tier: 'F', score: 5, color: 'var(--tier-f)' },
  { label: 'Waits for the Ground to Come to Them', weight: 1, tier: 'F', score: 5, color: 'var(--tier-f)' },
  { label: 'Missed a Bus Parked at the Stop', weight: 1, tier: 'F', score: 5, color: 'var(--tier-f)' },
  { label: 'Walking Speed Is Their Sprint', weight: 1, tier: 'F', score: 5, color: 'var(--tier-f)' },
  { label: 'Arrives Eventually', weight: 1, tier: 'F', score: 5, color: 'var(--tier-f)' },
  { label: 'Lazy River Speed', weight: 1, tier: 'F', score: 5, color: 'var(--tier-f)' },
  { label: 'Furniture Moves Faster (When Pushed)', weight: 1, tier: 'F', score: 5, color: 'var(--tier-f)' },
  { label: 'Speed: Aspirational', weight: 1, tier: 'F', score: 5, color: 'var(--tier-f)' },
  { label: 'Shadow Keeps Up Effortlessly', weight: 1, tier: 'F', score: 5, color: 'var(--tier-f)' },
  { label: 'Sunrise Beats Them to the Window', weight: 1, tier: 'F', score: 5, color: 'var(--tier-f)' },
  { label: 'Leaves Blow Past Them', weight: 1, tier: 'F', score: 5, color: 'var(--tier-f)' },
  { label: 'Elevator Is Overkill', weight: 1, tier: 'F', score: 5, color: 'var(--tier-f)' },
  { label: 'People Ask if They Need Help', weight: 1, tier: 'F', score: 5, color: 'var(--tier-f)' },

  // F+ (score: 8)
  { label: 'Brisk Walk at Best', weight: 1, tier: 'F+', score: 8, color: 'var(--tier-f-plus)' },
  { label: 'Can Catch a Slow Bus', weight: 1, tier: 'F+', score: 8, color: 'var(--tier-f-plus)' },
  { label: 'Jogs Without Injury', weight: 1, tier: 'F+', score: 8, color: 'var(--tier-f-plus)' },
  { label: 'Moderate Shuffle', weight: 1, tier: 'F+', score: 8, color: 'var(--tier-f-plus)' },
  { label: 'Barely Outruns a Dog', weight: 1, tier: 'F+', score: 8, color: 'var(--tier-f-plus)' },
  { label: 'Late to Everything (But Closer Now)', weight: 1, tier: 'F+', score: 8, color: 'var(--tier-f-plus)' },
  { label: 'Faster Than Standing Still', weight: 1, tier: 'F+', score: 8, color: 'var(--tier-f-plus)' },
  { label: 'Moderate Pace for the Motivated', weight: 1, tier: 'F+', score: 8, color: 'var(--tier-f-plus)' },
  { label: 'Slow Jog with Attitude', weight: 1, tier: 'F+', score: 8, color: 'var(--tier-f-plus)' },
  { label: 'Wind Doesn\'t Bother Blowing', weight: 1, tier: 'F+', score: 8, color: 'var(--tier-f-plus)' },
  { label: 'Moves Quick If Motivated by Food', weight: 1, tier: 'F+', score: 8, color: 'var(--tier-f-plus)' },
  { label: 'Could Maybe Outrun a Toddler', weight: 1, tier: 'F+', score: 8, color: 'var(--tier-f-plus)' },
  { label: 'Almost Fast Enough to Matter', weight: 1, tier: 'F+', score: 8, color: 'var(--tier-f-plus)' },
  { label: 'Arrives Before Midnight', weight: 1, tier: 'F+', score: 8, color: 'var(--tier-f-plus)' },
  { label: 'Overtakes Only Parked Objects', weight: 1, tier: 'F+', score: 8, color: 'var(--tier-f-plus)' },
  { label: 'Reasonable Ground Coverage Rate', weight: 1, tier: 'F+', score: 8, color: 'var(--tier-f-plus)' },
  { label: 'Speed: Technically Increasing', weight: 1, tier: 'F+', score: 8, color: 'var(--tier-f-plus)' },
  { label: 'Moves Before Asked Twice', weight: 1, tier: 'F+', score: 8, color: 'var(--tier-f-plus)' },
  { label: 'Almost Keeps Up with Kids', weight: 1, tier: 'F+', score: 8, color: 'var(--tier-f-plus)' },
  { label: 'Outruns Their Shadow Downhill', weight: 1, tier: 'F+', score: 8, color: 'var(--tier-f-plus)' },

  // E- (score: 11)
  { label: 'Casual Jog Speed', weight: 1, tier: 'E-', score: 11, color: 'var(--tier-e-minus)' },
  { label: 'Five-Minute Mile Possible', weight: 1, tier: 'E-', score: 11, color: 'var(--tier-e-minus)' },
  { label: 'Outruns the Average Person', weight: 1, tier: 'E-', score: 11, color: 'var(--tier-e-minus)' },
  { label: 'Can Catch a Bicycle Downhill', weight: 1, tier: 'E-', score: 11, color: 'var(--tier-e-minus)' },
  { label: 'Decent Ground Speed', weight: 1, tier: 'E-', score: 11, color: 'var(--tier-e-minus)' },
  { label: 'Moderate Sprint Ability', weight: 1, tier: 'E-', score: 11, color: 'var(--tier-e-minus)' },
  { label: 'Moves Well When Motivated', weight: 1, tier: 'E-', score: 11, color: 'var(--tier-e-minus)' },
  { label: 'Keeps Pace at a Light Run', weight: 1, tier: 'E-', score: 11, color: 'var(--tier-e-minus)' },
  { label: 'Athletic Walk', weight: 1, tier: 'E-', score: 11, color: 'var(--tier-e-minus)' },
  { label: 'Might Catch a Bus', weight: 1, tier: 'E-', score: 11, color: 'var(--tier-e-minus)' },
  { label: 'Faster Than Most at the Track', weight: 1, tier: 'E-', score: 11, color: 'var(--tier-e-minus)' },
  { label: 'Decent Reaction Speed', weight: 1, tier: 'E-', score: 11, color: 'var(--tier-e-minus)' },
  { label: 'Light-footed Approach', weight: 1, tier: 'E-', score: 11, color: 'var(--tier-e-minus)' },
  { label: 'Comfortably Outpaces Traffic', weight: 1, tier: 'E-', score: 11, color: 'var(--tier-e-minus)' },
  { label: 'Picks Up the Pace', weight: 1, tier: 'E-', score: 11, color: 'var(--tier-e-minus)' },
  { label: 'Outruns Dogs (Small Breeds)', weight: 1, tier: 'E-', score: 11, color: 'var(--tier-e-minus)' },
  { label: 'Covers Ground Efficiently', weight: 1, tier: 'E-', score: 11, color: 'var(--tier-e-minus)' },
  { label: 'Consistent Speed', weight: 1, tier: 'E-', score: 11, color: 'var(--tier-e-minus)' },
  { label: 'Faster Than Expected', weight: 1, tier: 'E-', score: 11, color: 'var(--tier-e-minus)' },
  { label: 'Better Than Average Sprinter', weight: 1, tier: 'E-', score: 11, color: 'var(--tier-e-minus)' },

  // E (score: 14)
  { label: 'Average Human Runner', weight: 1, tier: 'E', score: 14, color: 'var(--tier-e)' },
  { label: 'Good Running Form', weight: 1, tier: 'E', score: 14, color: 'var(--tier-e)' },
  { label: 'Keeps Up in a Race', weight: 1, tier: 'E', score: 14, color: 'var(--tier-e)' },
  { label: 'Competent Sprint', weight: 1, tier: 'E', score: 14, color: 'var(--tier-e)' },
  { label: 'Can Chase Down a Bicycle', weight: 1, tier: 'E', score: 14, color: 'var(--tier-e)' },
  { label: 'Normal Human Pace', weight: 1, tier: 'E', score: 14, color: 'var(--tier-e)' },
  { label: 'Moderate Athletic Speed', weight: 1, tier: 'E', score: 14, color: 'var(--tier-e)' },
  { label: 'Track Team Potential', weight: 1, tier: 'E', score: 14, color: 'var(--tier-e)' },
  { label: 'Fast Enough to Catch an Escape', weight: 1, tier: 'E', score: 14, color: 'var(--tier-e)' },
  { label: 'Speed: Reliably Present', weight: 1, tier: 'E', score: 14, color: 'var(--tier-e)' },
  { label: 'Runs a Solid Five Miles Comfortably', weight: 1, tier: 'E', score: 14, color: 'var(--tier-e)' },
  { label: 'Good Footwork', weight: 1, tier: 'E', score: 14, color: 'var(--tier-e)' },
  { label: 'Fast-Walking Intimidation', weight: 1, tier: 'E', score: 14, color: 'var(--tier-e)' },
  { label: 'Outruns Trouble Occasionally', weight: 1, tier: 'E', score: 14, color: 'var(--tier-e)' },
  { label: 'Standard-Issue Runner', weight: 1, tier: 'E', score: 14, color: 'var(--tier-e)' },
  { label: 'Reasonable Reaction Time', weight: 1, tier: 'E', score: 14, color: 'var(--tier-e)' },
  { label: 'Athletic Build, Normal Speed', weight: 1, tier: 'E', score: 14, color: 'var(--tier-e)' },
  { label: 'Consistent Pace Over Distance', weight: 1, tier: 'E', score: 14, color: 'var(--tier-e)' },
  { label: 'Can Dodge Slow Things', weight: 1, tier: 'E', score: 14, color: 'var(--tier-e)' },
  { label: 'Moves When It Matters', weight: 1, tier: 'E', score: 14, color: 'var(--tier-e)' },

  // E+ (score: 17)
  { label: 'Above Average Runner', weight: 1, tier: 'E+', score: 17, color: 'var(--tier-e-plus)' },
  { label: 'Varsity Track Speed', weight: 1, tier: 'E+', score: 17, color: 'var(--tier-e-plus)' },
  { label: 'Outruns Most People', weight: 1, tier: 'E+', score: 17, color: 'var(--tier-e-plus)' },
  { label: 'Fast Enough to Be Dangerous', weight: 1, tier: 'E+', score: 17, color: 'var(--tier-e-plus)' },
  { label: 'Quick Off the Mark', weight: 1, tier: 'E+', score: 17, color: 'var(--tier-e-plus)' },
  { label: 'Sprinter\'s Build', weight: 1, tier: 'E+', score: 17, color: 'var(--tier-e-plus)' },
  { label: 'Outruns Large Dogs', weight: 1, tier: 'E+', score: 17, color: 'var(--tier-e-plus)' },
  { label: 'Makes Running Look Natural', weight: 1, tier: 'E+', score: 17, color: 'var(--tier-e-plus)' },
  { label: 'Surprise Speed', weight: 1, tier: 'E+', score: 17, color: 'var(--tier-e-plus)' },
  { label: 'Hard to Catch', weight: 1, tier: 'E+', score: 17, color: 'var(--tier-e-plus)' },
  { label: 'Keeps Pace with Cyclists Casually', weight: 1, tier: 'E+', score: 17, color: 'var(--tier-e-plus)' },
  { label: 'Acceleration That Startles', weight: 1, tier: 'E+', score: 17, color: 'var(--tier-e-plus)' },
  { label: 'Noticeably Quick', weight: 1, tier: 'E+', score: 17, color: 'var(--tier-e-plus)' },
  { label: 'Speed: Consistent and Reliable', weight: 1, tier: 'E+', score: 17, color: 'var(--tier-e-plus)' },
  { label: 'Eyes Can Track Them (Barely)', weight: 1, tier: 'E+', score: 17, color: 'var(--tier-e-plus)' },
  { label: 'Moves with Purpose and Velocity', weight: 1, tier: 'E+', score: 17, color: 'var(--tier-e-plus)' },
  { label: 'Athletic Sprint, Excellent Form', weight: 1, tier: 'E+', score: 17, color: 'var(--tier-e-plus)' },
  { label: 'Fast Enough to Dodge Most Strikes', weight: 1, tier: 'E+', score: 17, color: 'var(--tier-e-plus)' },
  { label: 'Pro Athletic Speed', weight: 1, tier: 'E+', score: 17, color: 'var(--tier-e-plus)' },
  { label: 'Zero to Fast in Seconds', weight: 1, tier: 'E+', score: 17, color: 'var(--tier-e-plus)' },

  // D- (score: 20)
  { label: 'Elite Human Speed', weight: 1, tier: 'D-', score: 20, color: 'var(--tier-d-minus)' },
  { label: 'Olympic Sprinter Territory', weight: 1, tier: 'D-', score: 20, color: 'var(--tier-d-minus)' },
  { label: 'Sub-10 Second Hundred Meters', weight: 1, tier: 'D-', score: 20, color: 'var(--tier-d-minus)' },
  { label: 'Hard to Track Visually', weight: 1, tier: 'D-', score: 20, color: 'var(--tier-d-minus)' },
  { label: 'Speed Blur Approaching', weight: 1, tier: 'D-', score: 20, color: 'var(--tier-d-minus)' },
  { label: 'Eyes Struggle to Follow', weight: 1, tier: 'D-', score: 20, color: 'var(--tier-d-minus)' },
  { label: 'Leaves Afterimage at Sprint', weight: 1, tier: 'D-', score: 20, color: 'var(--tier-d-minus)' },
  { label: 'Human Speed Limit Reached', weight: 1, tier: 'D-', score: 20, color: 'var(--tier-d-minus)' },
  { label: 'Wind Has to Hustle to Keep Up', weight: 1, tier: 'D-', score: 20, color: 'var(--tier-d-minus)' },
  { label: 'Outruns Cars in Short Bursts', weight: 1, tier: 'D-', score: 20, color: 'var(--tier-d-minus)' },
  { label: 'Flash Mobility', weight: 1, tier: 'D-', score: 20, color: 'var(--tier-d-minus)' },
  { label: 'Zero Reaction Time', weight: 1, tier: 'D-', score: 20, color: 'var(--tier-d-minus)' },
  { label: 'First Gear is Third Gear', weight: 1, tier: 'D-', score: 20, color: 'var(--tier-d-minus)' },
  { label: 'Moves Before Thinking Ends', weight: 1, tier: 'D-', score: 20, color: 'var(--tier-d-minus)' },
  { label: 'Outpaces Radar Guns', weight: 1, tier: 'D-', score: 20, color: 'var(--tier-d-minus)' },
  { label: 'Fast as Physics Allows (Briefly)', weight: 1, tier: 'D-', score: 20, color: 'var(--tier-d-minus)' },
  { label: 'Clothes Struggle to Keep Up', weight: 1, tier: 'D-', score: 20, color: 'var(--tier-d-minus)' },
  { label: 'Their Start is Most People\'s Finish', weight: 1, tier: 'D-', score: 20, color: 'var(--tier-d-minus)' },
  { label: 'Seen as a Streak of Motion', weight: 1, tier: 'D-', score: 20, color: 'var(--tier-d-minus)' },
  { label: 'Acceleration Beyond Human Norm', weight: 1, tier: 'D-', score: 20, color: 'var(--tier-d-minus)' },

  // D (score: 23)
  { label: 'Superhuman Speed', weight: 1, tier: 'D', score: 23, color: 'var(--tier-d)' },
  { label: 'Outruns Highway Traffic', weight: 1, tier: 'D', score: 23, color: 'var(--tier-d)' },
  { label: 'Blurs When Running', weight: 1, tier: 'D', score: 23, color: 'var(--tier-d)' },
  { label: 'Can Dodge Bullets (Slow Ones)', weight: 1, tier: 'D', score: 23, color: 'var(--tier-d)' },
  { label: 'Air Displacement on Movement', weight: 1, tier: 'D', score: 23, color: 'var(--tier-d)' },
  { label: 'Moves Faster Than Sight', weight: 1, tier: 'D', score: 23, color: 'var(--tier-d)' },
  { label: 'Past Before You Register Present', weight: 1, tier: 'D', score: 23, color: 'var(--tier-d)' },
  { label: 'Leaves Sonic Whispers', weight: 1, tier: 'D', score: 23, color: 'var(--tier-d)' },
  { label: 'Speed: Clearly Supernatural', weight: 1, tier: 'D', score: 23, color: 'var(--tier-d)' },
  { label: 'Creates Air Currents When Walking', weight: 1, tier: 'D', score: 23, color: 'var(--tier-d)' },
  { label: 'Faster Than Thought (Close)', weight: 1, tier: 'D', score: 23, color: 'var(--tier-d)' },
  { label: 'Tracking Them Requires Instruments', weight: 1, tier: 'D', score: 23, color: 'var(--tier-d)' },
  { label: 'Ground Burns Slightly', weight: 1, tier: 'D', score: 23, color: 'var(--tier-d)' },
  { label: 'Reaction Speed: Instant', weight: 1, tier: 'D', score: 23, color: 'var(--tier-d)' },
  { label: 'Exits Before Entering', weight: 1, tier: 'D', score: 23, color: 'var(--tier-d)' },
  { label: 'Breeze From Passing Drops Books', weight: 1, tier: 'D', score: 23, color: 'var(--tier-d)' },
  { label: 'Speed Camera Broken After One Photo', weight: 1, tier: 'D', score: 23, color: 'var(--tier-d)' },
  { label: 'Leaves a Very Long Afterimage', weight: 1, tier: 'D', score: 23, color: 'var(--tier-d)' },
  { label: 'Covers Miles Between Breaths', weight: 1, tier: 'D', score: 23, color: 'var(--tier-d)' },
  { label: 'Trains Become Obstacles', weight: 1, tier: 'D', score: 23, color: 'var(--tier-d)' },

  // D+ (score: 26)
  { label: 'Hypersonic Movement', weight: 1, tier: 'D+', score: 26, color: 'var(--tier-d-plus)' },
  { label: 'Breaks the Sound Barrier Casually', weight: 1, tier: 'D+', score: 26, color: 'var(--tier-d-plus)' },
  { label: 'Sonic Boom on Acceleration', weight: 1, tier: 'D+', score: 26, color: 'var(--tier-d-plus)' },
  { label: 'Invisible When Sprinting', weight: 1, tier: 'D+', score: 26, color: 'var(--tier-d-plus)' },
  { label: 'Outruns Jets', weight: 1, tier: 'D+', score: 26, color: 'var(--tier-d-plus)' },
  { label: 'Mach 5 on a Tuesday', weight: 1, tier: 'D+', score: 26, color: 'var(--tier-d-plus)' },
  { label: 'Aircraft Lose Them Quickly', weight: 1, tier: 'D+', score: 26, color: 'var(--tier-d-plus)' },
  { label: 'Radar Cannot Lock On', weight: 1, tier: 'D+', score: 26, color: 'var(--tier-d-plus)' },
  { label: 'Wind Does Not Have Time to React', weight: 1, tier: 'D+', score: 26, color: 'var(--tier-d-plus)' },
  { label: 'Reality Blurs in Wake', weight: 1, tier: 'D+', score: 26, color: 'var(--tier-d-plus)' },
  { label: 'Moves Between Heartbeats', weight: 1, tier: 'D+', score: 26, color: 'var(--tier-d-plus)' },
  { label: 'Creates Vacuum in Passing', weight: 1, tier: 'D+', score: 26, color: 'var(--tier-d-plus)' },
  { label: 'Shockwave Announces Arrival After Departure', weight: 1, tier: 'D+', score: 26, color: 'var(--tier-d-plus)' },
  { label: 'Laps Themselves', weight: 1, tier: 'D+', score: 26, color: 'var(--tier-d-plus)' },
  { label: 'Speed Causes Small Fires', weight: 1, tier: 'D+', score: 26, color: 'var(--tier-d-plus)' },
  { label: 'Continental Cross in Seconds', weight: 1, tier: 'D+', score: 26, color: 'var(--tier-d-plus)' },
  { label: 'Fast Enough to See Own Departure', weight: 1, tier: 'D+', score: 26, color: 'var(--tier-d-plus)' },
  { label: 'Air Ignites in Wake', weight: 1, tier: 'D+', score: 26, color: 'var(--tier-d-plus)' },
  { label: 'Bullets Are Trivially Slow', weight: 1, tier: 'D+', score: 26, color: 'var(--tier-d-plus)' },
  { label: 'Outruns Their Own Name', weight: 1, tier: 'D+', score: 26, color: 'var(--tier-d-plus)' },

  // C- (score: 30)
  { label: 'Speed of Sound Plus', weight: 1, tier: 'C-', score: 30, color: 'var(--tier-c-minus)' },
  { label: 'Crosses Oceans in Minutes', weight: 1, tier: 'C-', score: 30, color: 'var(--tier-c-minus)' },
  { label: 'Can Lap the Globe', weight: 1, tier: 'C-', score: 30, color: 'var(--tier-c-minus)' },
  { label: 'Moves Between Lightning Strikes', weight: 1, tier: 'C-', score: 30, color: 'var(--tier-c-minus)' },
  { label: 'Almost at Light Speed', weight: 1, tier: 'C-', score: 30, color: 'var(--tier-c-minus)' },
  { label: 'Outpaces Explosions', weight: 1, tier: 'C-', score: 30, color: 'var(--tier-c-minus)' },
  { label: 'Arrives Before Sound Does', weight: 1, tier: 'C-', score: 30, color: 'var(--tier-c-minus)' },
  { label: 'Time Flinches on Their Sprint', weight: 1, tier: 'C-', score: 30, color: 'var(--tier-c-minus)' },
  { label: 'Faster Than a Shockwave', weight: 1, tier: 'C-', score: 30, color: 'var(--tier-c-minus)' },
  { label: 'Creates Weather Phenomena While Running', weight: 1, tier: 'C-', score: 30, color: 'var(--tier-c-minus)' },
  { label: 'Earth Curves Before Them', weight: 1, tier: 'C-', score: 30, color: 'var(--tier-c-minus)' },
  { label: 'Outpaces Their Own Sonic Boom', weight: 1, tier: 'C-', score: 30, color: 'var(--tier-c-minus)' },
  { label: 'Creates New Latitude Lines', weight: 1, tier: 'C-', score: 30, color: 'var(--tier-c-minus)' },
  { label: 'Trail Evaporates Behind Them', weight: 1, tier: 'C-', score: 30, color: 'var(--tier-c-minus)' },
  { label: 'Faster Than Any Man-Made Object', weight: 1, tier: 'C-', score: 30, color: 'var(--tier-c-minus)' },
  { label: 'Satellites File Complaints', weight: 1, tier: 'C-', score: 30, color: 'var(--tier-c-minus)' },
  { label: 'Can Literally Run Around the Problem', weight: 1, tier: 'C-', score: 30, color: 'var(--tier-c-minus)' },
  { label: 'Photons Check Their Rearview', weight: 1, tier: 'C-', score: 30, color: 'var(--tier-c-minus)' },
  { label: 'Laps a Country in One Breath', weight: 1, tier: 'C-', score: 30, color: 'var(--tier-c-minus)' },
  { label: 'Wind Cannot Follow', weight: 1, tier: 'C-', score: 30, color: 'var(--tier-c-minus)' },

  // C (score: 34)
  { label: 'Lightspeed Adjacent', weight: 1, tier: 'C', score: 34, color: 'var(--tier-c)' },
  { label: 'Outruns Light (Almost)', weight: 1, tier: 'C', score: 34, color: 'var(--tier-c)' },
  { label: 'Reaches Orbit in Seconds', weight: 1, tier: 'C', score: 34, color: 'var(--tier-c)' },
  { label: 'Moon Trip: 1.3 Seconds', weight: 1, tier: 'C', score: 34, color: 'var(--tier-c)' },
  { label: 'Time Dilates Around Them', weight: 1, tier: 'C', score: 34, color: 'var(--tier-c)' },
  { label: 'Physics Starts Worrying', weight: 1, tier: 'C', score: 34, color: 'var(--tier-c)' },
  { label: 'Arrives Before Deciding to Go', weight: 1, tier: 'C', score: 34, color: 'var(--tier-c)' },
  { label: 'Light Bends Around Them Out of Courtesy', weight: 1, tier: 'C', score: 34, color: 'var(--tier-c)' },
  { label: 'Can See Their Own Past Self Running', weight: 1, tier: 'C', score: 34, color: 'var(--tier-c)' },
  { label: 'Speed Creates Visible Time Shear', weight: 1, tier: 'C', score: 34, color: 'var(--tier-c)' },
  { label: 'Solar System in Under a Day', weight: 1, tier: 'C', score: 34, color: 'var(--tier-c)' },
  { label: 'Outruns Causality Briefly', weight: 1, tier: 'C', score: 34, color: 'var(--tier-c)' },
  { label: 'Faster Than Electromagnetic Radiation', weight: 1, tier: 'C', score: 34, color: 'var(--tier-c)' },
  { label: 'Can Outrun Their Own Death', weight: 1, tier: 'C', score: 34, color: 'var(--tier-c)' },
  { label: 'Galaxy Edge Trip for Lunch', weight: 1, tier: 'C', score: 34, color: 'var(--tier-c)' },
  { label: 'Creates Temporal Afterimages', weight: 1, tier: 'C', score: 34, color: 'var(--tier-c)' },
  { label: 'Passes Photons with Ease', weight: 1, tier: 'C', score: 34, color: 'var(--tier-c)' },
  { label: 'Speed Collapses Local Space', weight: 1, tier: 'C', score: 34, color: 'var(--tier-c)' },
  { label: 'Red-Shifts on Sprint', weight: 1, tier: 'C', score: 34, color: 'var(--tier-c)' },
  { label: 'Photons Ask for a Piggyback', weight: 1, tier: 'C', score: 34, color: 'var(--tier-c)' },

  // C+ (score: 38)
  { label: 'FTL Movement', weight: 1, tier: 'C+', score: 38, color: 'var(--tier-c-plus)' },
  { label: 'Crosses the Galaxy Casually', weight: 1, tier: 'C+', score: 38, color: 'var(--tier-c-plus)' },
  { label: 'Bends Space on Sprint', weight: 1, tier: 'C+', score: 38, color: 'var(--tier-c-plus)' },
  { label: 'Travel Via Space Folding', weight: 1, tier: 'C+', score: 38, color: 'var(--tier-c-plus)' },
  { label: 'Was Here Before Here Existed', weight: 1, tier: 'C+', score: 38, color: 'var(--tier-c-plus)' },
  { label: 'Spacetime Reconfigures Itself', weight: 1, tier: 'C+', score: 38, color: 'var(--tier-c-plus)' },
  { label: 'Outruns the Expansion of Space', weight: 1, tier: 'C+', score: 38, color: 'var(--tier-c-plus)' },
  { label: 'Infinite Velocity Theoretically', weight: 1, tier: 'C+', score: 38, color: 'var(--tier-c-plus)' },
  { label: 'Speed Causes Universal Redshift', weight: 1, tier: 'C+', score: 38, color: 'var(--tier-c-plus)' },
  { label: 'Can Lap The Universe', weight: 1, tier: 'C+', score: 38, color: 'var(--tier-c-plus)' },
  { label: 'Arrives at Destination of Future Decision', weight: 1, tier: 'C+', score: 38, color: 'var(--tier-c-plus)' },
  { label: 'Traverses Parallel Universes Between Steps', weight: 1, tier: 'C+', score: 38, color: 'var(--tier-c-plus)' },
  { label: 'Creates Spacetime Tunnels by Running', weight: 1, tier: 'C+', score: 38, color: 'var(--tier-c-plus)' },
  { label: 'Can Outrun an Expanding Universe', weight: 1, tier: 'C+', score: 38, color: 'var(--tier-c-plus)' },
  { label: 'Multiversal Speed', weight: 1, tier: 'C+', score: 38, color: 'var(--tier-c-plus)' },
  { label: 'Dimensional Barrier: Meaningless', weight: 1, tier: 'C+', score: 38, color: 'var(--tier-c-plus)' },
  { label: 'Past, Present, Future: All Available', weight: 1, tier: 'C+', score: 38, color: 'var(--tier-c-plus)' },
  { label: 'Creates Time Paradoxes Just by Jogging', weight: 1, tier: 'C+', score: 38, color: 'var(--tier-c-plus)' },
  { label: 'Space Itself Is Just a Slow Lane', weight: 1, tier: 'C+', score: 38, color: 'var(--tier-c-plus)' },
  { label: 'Arrives Before Deciding to Move', weight: 1, tier: 'C+', score: 38, color: 'var(--tier-c-plus)' },

  // B- (score: 42)
  { label: 'Infinite Speed Approaches', weight: 1, tier: 'B-', score: 42, color: 'var(--tier-b-minus)' },
  { label: 'Moves Between Moments', weight: 1, tier: 'B-', score: 42, color: 'var(--tier-b-minus)' },
  { label: 'Time Is a Suggestion', weight: 1, tier: 'B-', score: 42, color: 'var(--tier-b-minus)' },
  { label: 'Already There', weight: 1, tier: 'B-', score: 42, color: 'var(--tier-b-minus)' },
  { label: 'Everywhere at Once (Almost)', weight: 1, tier: 'B-', score: 42, color: 'var(--tier-b-minus)' },
  { label: 'Speed Transcends Physics', weight: 1, tier: 'B-', score: 42, color: 'var(--tier-b-minus)' },
  { label: 'Outpaces the Future', weight: 1, tier: 'B-', score: 42, color: 'var(--tier-b-minus)' },
  { label: 'Not Even Thought Keeps Up', weight: 1, tier: 'B-', score: 42, color: 'var(--tier-b-minus)' },
  { label: 'Leaves Temporal Impressions', weight: 1, tier: 'B-', score: 42, color: 'var(--tier-b-minus)' },
  { label: 'Photons File Insurance Claims', weight: 1, tier: 'B-', score: 42, color: 'var(--tier-b-minus)' },
  { label: 'Moves Through Unwritten History', weight: 1, tier: 'B-', score: 42, color: 'var(--tier-b-minus)' },
  { label: 'Laps the Speed of Thought', weight: 1, tier: 'B-', score: 42, color: 'var(--tier-b-minus)' },
  { label: 'Can Hold Conversations in Microseconds', weight: 1, tier: 'B-', score: 42, color: 'var(--tier-b-minus)' },
  { label: 'Physics Has No Comment', weight: 1, tier: 'B-', score: 42, color: 'var(--tier-b-minus)' },
  { label: 'Movement Precedes Intention', weight: 1, tier: 'B-', score: 42, color: 'var(--tier-b-minus)' },
  { label: 'Outruns Consequence', weight: 1, tier: 'B-', score: 42, color: 'var(--tier-b-minus)' },
  { label: 'Seen in Seven Timelines at Once', weight: 1, tier: 'B-', score: 42, color: 'var(--tier-b-minus)' },
  { label: 'Can Outrun the Past', weight: 1, tier: 'B-', score: 42, color: 'var(--tier-b-minus)' },
  { label: 'Speed: Beyond Any Known Metric', weight: 1, tier: 'B-', score: 42, color: 'var(--tier-b-minus)' },
  { label: 'The Wind Couldn\'t See Them Leave', weight: 1, tier: 'B-', score: 42, color: 'var(--tier-b-minus)' },

  // B (score: 47)
  { label: 'Speed of Thought', weight: 1, tier: 'B', score: 47, color: 'var(--tier-b)' },
  { label: 'Moves Faster Than Neural Signal', weight: 1, tier: 'B', score: 47, color: 'var(--tier-b)' },
  { label: 'Exists Across Time Simultaneously', weight: 1, tier: 'B', score: 47, color: 'var(--tier-b)' },
  { label: 'Outruns Causality Comfortably', weight: 1, tier: 'B', score: 47, color: 'var(--tier-b)' },
  { label: 'Everywhere Yesterday', weight: 1, tier: 'B', score: 47, color: 'var(--tier-b)' },
  { label: 'Traverses All Universes in Seconds', weight: 1, tier: 'B', score: 47, color: 'var(--tier-b)' },
  { label: 'Speed Folds Spacetime', weight: 1, tier: 'B', score: 47, color: 'var(--tier-b)' },
  { label: 'Present Before Decision', weight: 1, tier: 'B', score: 47, color: 'var(--tier-b)' },
  { label: 'Makes Light Look Like Traffic', weight: 1, tier: 'B', score: 47, color: 'var(--tier-b)' },
  { label: 'Time Isn\'t An Issue', weight: 1, tier: 'B', score: 47, color: 'var(--tier-b)' },
  { label: 'Has Already Arrived', weight: 1, tier: 'B', score: 47, color: 'var(--tier-b)' },
  { label: 'Moves Between Atomic Moments', weight: 1, tier: 'B', score: 47, color: 'var(--tier-b)' },
  { label: 'Faster Than The Concept of Now', weight: 1, tier: 'B', score: 47, color: 'var(--tier-b)' },
  { label: 'Creates New Temporal Branches by Running', weight: 1, tier: 'B', score: 47, color: 'var(--tier-b)' },
  { label: 'Outruns Awareness Itself', weight: 1, tier: 'B', score: 47, color: 'var(--tier-b)' },
  { label: 'Moves Like a Living Exception', weight: 1, tier: 'B', score: 47, color: 'var(--tier-b)' },
  { label: 'All Timelines Crossed in One Blink', weight: 1, tier: 'B', score: 47, color: 'var(--tier-b)' },
  { label: 'Outruns the Collapse of Possibility', weight: 1, tier: 'B', score: 47, color: 'var(--tier-b)' },
  { label: 'Wins Every Race That Hasn\'t Been Run', weight: 1, tier: 'B', score: 47, color: 'var(--tier-b)' },
  { label: 'Past and Future Are Both Already Behind', weight: 1, tier: 'B', score: 47, color: 'var(--tier-b)' },

  // B+ (score: 52)
  { label: 'Omnipresent Adjacent', weight: 1, tier: 'B+', score: 52, color: 'var(--tier-b-plus)' },
  { label: 'Exists in All Locations Simultaneously', weight: 1, tier: 'B+', score: 52, color: 'var(--tier-b-plus)' },
  { label: 'Speed Exceeds Dimensionality', weight: 1, tier: 'B+', score: 52, color: 'var(--tier-b-plus)' },
  { label: 'In Every Timeline at Once', weight: 1, tier: 'B+', score: 52, color: 'var(--tier-b-plus)' },
  { label: 'Movement Has Become Omnipresence', weight: 1, tier: 'B+', score: 52, color: 'var(--tier-b-plus)' },
  { label: 'Laps the Heat Death of the Universe', weight: 1, tier: 'B+', score: 52, color: 'var(--tier-b-plus)' },
  { label: 'Moved Before the Big Bang', weight: 1, tier: 'B+', score: 52, color: 'var(--tier-b-plus)' },
  { label: 'Traverses Infinite Space in Zero Time', weight: 1, tier: 'B+', score: 52, color: 'var(--tier-b-plus)' },
  { label: 'Speed Without a Reference Frame', weight: 1, tier: 'B+', score: 52, color: 'var(--tier-b-plus)' },
  { label: 'Causality Is Just a Loose Guideline', weight: 1, tier: 'B+', score: 52, color: 'var(--tier-b-plus)' },
  { label: 'Arrives at All Points Simultaneously', weight: 1, tier: 'B+', score: 52, color: 'var(--tier-b-plus)' },
  { label: 'Can Be in Two Epochs at Once', weight: 1, tier: 'B+', score: 52, color: 'var(--tier-b-plus)' },
  { label: 'Omniversal Distance is One Step', weight: 1, tier: 'B+', score: 52, color: 'var(--tier-b-plus)' },
  { label: 'Left Before the Concept of Leaving Existed', weight: 1, tier: 'B+', score: 52, color: 'var(--tier-b-plus)' },
  { label: 'The Universe Hasn\'t Caught Up Yet', weight: 1, tier: 'B+', score: 52, color: 'var(--tier-b-plus)' },
  { label: 'Exists in Plural Locations', weight: 1, tier: 'B+', score: 52, color: 'var(--tier-b-plus)' },
  { label: 'Speed Breaks Logical Implication', weight: 1, tier: 'B+', score: 52, color: 'var(--tier-b-plus)' },
  { label: 'Everywhere Before Now', weight: 1, tier: 'B+', score: 52, color: 'var(--tier-b-plus)' },
  { label: 'All Addresses Are the Same Address', weight: 1, tier: 'B+', score: 52, color: 'var(--tier-b-plus)' },
  { label: 'Movement is Indistinguishable from Being', weight: 1, tier: 'B+', score: 52, color: 'var(--tier-b-plus)' },

  // A- (score: 57)
  { label: 'Temporal Omnipresence', weight: 1, tier: 'A-', score: 57, color: 'var(--tier-a-minus)' },
  { label: 'Already at the End', weight: 1, tier: 'A-', score: 57, color: 'var(--tier-a-minus)' },
  { label: 'Speed Beyond Linear Existence', weight: 1, tier: 'A-', score: 57, color: 'var(--tier-a-minus)' },
  { label: 'Exists Outside Sequence', weight: 1, tier: 'A-', score: 57, color: 'var(--tier-a-minus)' },
  { label: 'No Transition Between Points', weight: 1, tier: 'A-', score: 57, color: 'var(--tier-a-minus)' },
  { label: 'Can Visit Every Moment Simultaneously', weight: 1, tier: 'A-', score: 57, color: 'var(--tier-a-minus)' },
  { label: 'Sees the Beginning and End as the Same Step', weight: 1, tier: 'A-', score: 57, color: 'var(--tier-a-minus)' },
  { label: 'Speed Equivalent to Non-Movement', weight: 1, tier: 'A-', score: 57, color: 'var(--tier-a-minus)' },
  { label: 'Omni-Temporal', weight: 1, tier: 'A-', score: 57, color: 'var(--tier-a-minus)' },
  { label: 'Time Has Forgotten Them', weight: 1, tier: 'A-', score: 57, color: 'var(--tier-a-minus)' },
  { label: 'All Paths Already Taken', weight: 1, tier: 'A-', score: 57, color: 'var(--tier-a-minus)' },
  { label: 'Moves in Pre-Existence', weight: 1, tier: 'A-', score: 57, color: 'var(--tier-a-minus)' },
  { label: 'Position: All of Them', weight: 1, tier: 'A-', score: 57, color: 'var(--tier-a-minus)' },
  { label: 'Traverses the Absence of Distance', weight: 1, tier: 'A-', score: 57, color: 'var(--tier-a-minus)' },
  { label: 'Non-Linear Movement as Default State', weight: 1, tier: 'A-', score: 57, color: 'var(--tier-a-minus)' },
  { label: 'Direction: Irrelevant', weight: 1, tier: 'A-', score: 57, color: 'var(--tier-a-minus)' },
  { label: 'Outruns What Has Not Happened Yet', weight: 1, tier: 'A-', score: 57, color: 'var(--tier-a-minus)' },
  { label: 'Speed and Stillness Are the Same', weight: 1, tier: 'A-', score: 57, color: 'var(--tier-a-minus)' },
  { label: 'Location: Yes', weight: 1, tier: 'A-', score: 57, color: 'var(--tier-a-minus)' },
  { label: 'The Journey Took Zero Time', weight: 1, tier: 'A-', score: 57, color: 'var(--tier-a-minus)' },

  // A (score: 62)
  { label: 'Omnipresent', weight: 1, tier: 'A', score: 62, color: 'var(--tier-a)' },
  { label: 'Before the Question Forms', weight: 1, tier: 'A', score: 62, color: 'var(--tier-a)' },
  { label: 'Speed That Rewrites Order', weight: 1, tier: 'A', score: 62, color: 'var(--tier-a)' },
  { label: 'Exists at Every Moment at Once', weight: 1, tier: 'A', score: 62, color: 'var(--tier-a)' },
  { label: 'Causality\'s Nightmare', weight: 1, tier: 'A', score: 62, color: 'var(--tier-a)' },
  { label: 'Outruns Infinity', weight: 1, tier: 'A', score: 62, color: 'var(--tier-a)' },
  { label: 'The Concept of Arrival Is Redundant', weight: 1, tier: 'A', score: 62, color: 'var(--tier-a)' },
  { label: 'Simultaneously Everywhere Across All Existence', weight: 1, tier: 'A', score: 62, color: 'var(--tier-a)' },
  { label: 'Speed Made Non-Existence Navigable', weight: 1, tier: 'A', score: 62, color: 'var(--tier-a)' },
  { label: 'Distance Ceased to Apply', weight: 1, tier: 'A', score: 62, color: 'var(--tier-a)' },
  { label: 'Moves Through What Cannot Be Moved Through', weight: 1, tier: 'A', score: 62, color: 'var(--tier-a)' },
  { label: 'Motion Has Become Metaphysics', weight: 1, tier: 'A', score: 62, color: 'var(--tier-a)' },
  { label: 'Already Reached the Uncreated', weight: 1, tier: 'A', score: 62, color: 'var(--tier-a)' },
  { label: 'Time Addresses Them Formally', weight: 1, tier: 'A', score: 62, color: 'var(--tier-a)' },
  { label: 'Everywhere Always', weight: 1, tier: 'A', score: 62, color: 'var(--tier-a)' },
  { label: 'Can Outrun the End of Everything', weight: 1, tier: 'A', score: 62, color: 'var(--tier-a)' },
  { label: 'All Timelines: Already Visited', weight: 1, tier: 'A', score: 62, color: 'var(--tier-a)' },
  { label: 'Moving and Arriving Are the Same Act', weight: 1, tier: 'A', score: 62, color: 'var(--tier-a)' },
  { label: 'Speed Is No Longer the Right Word', weight: 1, tier: 'A', score: 62, color: 'var(--tier-a)' },
  { label: 'Omniversal Position: All of Them', weight: 1, tier: 'A', score: 62, color: 'var(--tier-a)' },

  // A+ (score: 67)
  { label: 'Transcendent Velocity', weight: 1, tier: 'A+', score: 67, color: 'var(--tier-a-plus)' },
  { label: 'Faster Than the Concept of Speed', weight: 1, tier: 'A+', score: 67, color: 'var(--tier-a-plus)' },
  { label: 'Moves Through Non-Existence', weight: 1, tier: 'A+', score: 67, color: 'var(--tier-a-plus)' },
  { label: 'Has No Position Because All Are Taken', weight: 1, tier: 'A+', score: 67, color: 'var(--tier-a-plus)' },
  { label: 'Speed Pre-Dates Causality', weight: 1, tier: 'A+', score: 67, color: 'var(--tier-a-plus)' },
  { label: 'Was There Before There Was a There', weight: 1, tier: 'A+', score: 67, color: 'var(--tier-a-plus)' },
  { label: 'Runs at the Speed of Intention', weight: 1, tier: 'A+', score: 67, color: 'var(--tier-a-plus)' },
  { label: 'Movement Equivalent to Omniscience', weight: 1, tier: 'A+', score: 67, color: 'var(--tier-a-plus)' },
  { label: 'Velocity That Predates the Universe', weight: 1, tier: 'A+', score: 67, color: 'var(--tier-a-plus)' },
  { label: 'Can Outrun Their Own Non-Existence', weight: 1, tier: 'A+', score: 67, color: 'var(--tier-a-plus)' },
  { label: 'Speed Becomes Indistinguishable from Creation', weight: 1, tier: 'A+', score: 67, color: 'var(--tier-a-plus)' },
  { label: 'Traveled Before the Track Existed', weight: 1, tier: 'A+', score: 67, color: 'var(--tier-a-plus)' },
  { label: 'The Beginning and End Are Adjacent', weight: 1, tier: 'A+', score: 67, color: 'var(--tier-a-plus)' },
  { label: 'Outruns Finality', weight: 1, tier: 'A+', score: 67, color: 'var(--tier-a-plus)' },
  { label: 'Space: No Longer a Constraint', weight: 1, tier: 'A+', score: 67, color: 'var(--tier-a-plus)' },
  { label: 'Speed Collapses All Ontological Gaps', weight: 1, tier: 'A+', score: 67, color: 'var(--tier-a-plus)' },
  { label: 'Temporal Sovereignty via Velocity', weight: 1, tier: 'A+', score: 67, color: 'var(--tier-a-plus)' },
  { label: 'Position Doesn\'t Constrain Them', weight: 1, tier: 'A+', score: 67, color: 'var(--tier-a-plus)' },
  { label: 'Movement Indistinguishable from Being Everywhere', weight: 1, tier: 'A+', score: 67, color: 'var(--tier-a-plus)' },
  { label: 'Outruns Eternity on a Good Day', weight: 1, tier: 'A+', score: 67, color: 'var(--tier-a-plus)' },

  // S- (score: 72)
  { label: 'Absolute Motion', weight: 1, tier: 'S-', score: 72, color: 'var(--tier-s-minus)' },
  { label: 'Speed Without Reference', weight: 1, tier: 'S-', score: 72, color: 'var(--tier-s-minus)' },
  { label: 'Traveled Before Travel Existed', weight: 1, tier: 'S-', score: 72, color: 'var(--tier-s-minus)' },
  { label: 'Position: Irrelevant', weight: 1, tier: 'S-', score: 72, color: 'var(--tier-s-minus)' },
  { label: 'Reaches Non-Existence Quickly', weight: 1, tier: 'S-', score: 72, color: 'var(--tier-s-minus)' },
  { label: 'Motion That Pre-Dates the Framework', weight: 1, tier: 'S-', score: 72, color: 'var(--tier-s-minus)' },
  { label: 'Velocity Unbound', weight: 1, tier: 'S-', score: 72, color: 'var(--tier-s-minus)' },
  { label: 'Space Gave Up', weight: 1, tier: 'S-', score: 72, color: 'var(--tier-s-minus)' },
  { label: 'Speed: The Only Law', weight: 1, tier: 'S-', score: 72, color: 'var(--tier-s-minus)' },
  { label: 'Speed Writes New Cosmological Constants', weight: 1, tier: 'S-', score: 72, color: 'var(--tier-s-minus)' },
  { label: 'Can Move Through Unwritten Spacetime', weight: 1, tier: 'S-', score: 72, color: 'var(--tier-s-minus)' },
  { label: 'Speed Collapses the Distinction of Now', weight: 1, tier: 'S-', score: 72, color: 'var(--tier-s-minus)' },
  { label: 'Nothing Remains Stationary Relative to Them', weight: 1, tier: 'S-', score: 72, color: 'var(--tier-s-minus)' },
  { label: 'Velocity Renders Existence Optional', weight: 1, tier: 'S-', score: 72, color: 'var(--tier-s-minus)' },
  { label: 'The Universe Hasn\'t Processed Their Departure Yet', weight: 1, tier: 'S-', score: 72, color: 'var(--tier-s-minus)' },
  { label: 'Motion That Bypasses Being', weight: 1, tier: 'S-', score: 72, color: 'var(--tier-s-minus)' },
  { label: 'Runs Outside of Sequence', weight: 1, tier: 'S-', score: 72, color: 'var(--tier-s-minus)' },
  { label: 'Outruns What Was Going to Happen', weight: 1, tier: 'S-', score: 72, color: 'var(--tier-s-minus)' },
  { label: 'Speed: Even the Universe Can\'t Keep Up', weight: 1, tier: 'S-', score: 72, color: 'var(--tier-s-minus)' },
  { label: 'Time Bowed Out', weight: 1, tier: 'S-', score: 72, color: 'var(--tier-s-minus)' },

  // S (score: 77)
  { label: 'Speed Beyond Omnipresence', weight: 1, tier: 'S', score: 77, color: 'var(--tier-s)' },
  { label: 'Faster Than Existing', weight: 1, tier: 'S', score: 77, color: 'var(--tier-s)' },
  { label: 'Traverses Non-Existence Quickly', weight: 1, tier: 'S', score: 77, color: 'var(--tier-s)' },
  { label: 'Movement That Transcends Metaphysics', weight: 1, tier: 'S', score: 77, color: 'var(--tier-s)' },
  { label: 'Faster Than Conception', weight: 1, tier: 'S', score: 77, color: 'var(--tier-s)' },
  { label: 'Location Is Just a Detail', weight: 1, tier: 'S', score: 77, color: 'var(--tier-s)' },
  { label: 'Movement Predates the Framework', weight: 1, tier: 'S', score: 77, color: 'var(--tier-s)' },
  { label: 'Already There Before Intending to Go', weight: 1, tier: 'S', score: 77, color: 'var(--tier-s)' },
  { label: 'Speed That Cannot Be Described', weight: 1, tier: 'S', score: 77, color: 'var(--tier-s)' },
  { label: 'Outruns Abstract Infinity', weight: 1, tier: 'S', score: 77, color: 'var(--tier-s)' },
  { label: 'The Very Concept of Distance Apologizes', weight: 1, tier: 'S', score: 77, color: 'var(--tier-s)' },
  { label: 'Can Visit Moments That Haven\'t Been Created', weight: 1, tier: 'S', score: 77, color: 'var(--tier-s)' },
  { label: 'Speed Is Now a Philosophical Stance', weight: 1, tier: 'S', score: 77, color: 'var(--tier-s)' },
  { label: 'Position: Also Philosophy Now', weight: 1, tier: 'S', score: 77, color: 'var(--tier-s)' },
  { label: 'Runs Through the Absence of the Universe', weight: 1, tier: 'S', score: 77, color: 'var(--tier-s)' },
  { label: 'Laps the End of Existence', weight: 1, tier: 'S', score: 77, color: 'var(--tier-s)' },
  { label: 'Faster Than the Fact That Things Exist', weight: 1, tier: 'S', score: 77, color: 'var(--tier-s)' },
  { label: 'The Future Arrived Late to Meeting Them', weight: 1, tier: 'S', score: 77, color: 'var(--tier-s)' },
  { label: 'Omnipresence Is Just Warmup Speed', weight: 1, tier: 'S', score: 77, color: 'var(--tier-s)' },
  { label: 'The Universe Writes Apology Cards', weight: 1, tier: 'S', score: 77, color: 'var(--tier-s)' },

  // S+ (score: 81)
  { label: 'Abstract Velocity', weight: 1, tier: 'S+', score: 81, color: 'var(--tier-s-plus)' },
  { label: 'Faster Than Non-Existence', weight: 1, tier: 'S+', score: 81, color: 'var(--tier-s-plus)' },
  { label: 'Runs Through Unformed Reality', weight: 1, tier: 'S+', score: 81, color: 'var(--tier-s-plus)' },
  { label: 'Movement That Pre-Dates Possibility', weight: 1, tier: 'S+', score: 81, color: 'var(--tier-s-plus)' },
  { label: 'Speed That Writes Universal History', weight: 1, tier: 'S+', score: 81, color: 'var(--tier-s-plus)' },
  { label: 'Arrives Everywhere Simultaneously Before Leaving', weight: 1, tier: 'S+', score: 81, color: 'var(--tier-s-plus)' },
  { label: 'Faster Than the Idea of Speed', weight: 1, tier: 'S+', score: 81, color: 'var(--tier-s-plus)' },
  { label: 'Moved Through All of Eternity Already', weight: 1, tier: 'S+', score: 81, color: 'var(--tier-s-plus)' },
  { label: 'Speed Has Become Indistinguishable From Thought', weight: 1, tier: 'S+', score: 81, color: 'var(--tier-s-plus)' },
  { label: 'Outruns the End of All Possible Timelines', weight: 1, tier: 'S+', score: 81, color: 'var(--tier-s-plus)' },
  { label: 'Can Be Everywhere Before Nothing Was', weight: 1, tier: 'S+', score: 81, color: 'var(--tier-s-plus)' },
  { label: 'The Last Thing the Void Saw Was a Blip', weight: 1, tier: 'S+', score: 81, color: 'var(--tier-s-plus)' },
  { label: 'Speed Bypasses Logical Limits', weight: 1, tier: 'S+', score: 81, color: 'var(--tier-s-plus)' },
  { label: 'Journey and Destination Are Simultaneous', weight: 1, tier: 'S+', score: 81, color: 'var(--tier-s-plus)' },
  { label: 'Can Outrun the Conditions of Their Birth', weight: 1, tier: 'S+', score: 81, color: 'var(--tier-s-plus)' },
  { label: 'Moved Through Pre-Physics', weight: 1, tier: 'S+', score: 81, color: 'var(--tier-s-plus)' },
  { label: 'Velocity: Yes', weight: 1, tier: 'S+', score: 81, color: 'var(--tier-s-plus)' },
  { label: 'Every Location in the Universe: Home', weight: 1, tier: 'S+', score: 81, color: 'var(--tier-s-plus)' },
  { label: 'Faster Than the Framework That Defines Fast', weight: 1, tier: 'S+', score: 81, color: 'var(--tier-s-plus)' },
  { label: 'Speed: Has No Meaning, Still Impressive', weight: 1, tier: 'S+', score: 81, color: 'var(--tier-s-plus)' },

  // SS- (score: 85)
  { label: 'Pre-Causal Motion', weight: 1, tier: 'SS-', score: 85, color: 'var(--tier-ss-minus)' },
  { label: 'Moves Outside of Being', weight: 1, tier: 'SS-', score: 85, color: 'var(--tier-ss-minus)' },
  { label: 'Traverses Absolute Nothing', weight: 1, tier: 'SS-', score: 85, color: 'var(--tier-ss-minus)' },
  { label: 'Motion That Preceded Everything', weight: 1, tier: 'SS-', score: 85, color: 'var(--tier-ss-minus)' },
  { label: 'Speed That Defies All Philosophical Frameworks', weight: 1, tier: 'SS-', score: 85, color: 'var(--tier-ss-minus)' },
  { label: 'Moves Through the Pre-Universe', weight: 1, tier: 'SS-', score: 85, color: 'var(--tier-ss-minus)' },
  { label: 'Can Arrive at Points Before They Exist', weight: 1, tier: 'SS-', score: 85, color: 'var(--tier-ss-minus)' },
  { label: 'Even Omnipresence Is Left Behind', weight: 1, tier: 'SS-', score: 85, color: 'var(--tier-ss-minus)' },
  { label: 'Speed: A Concept They Invented', weight: 1, tier: 'SS-', score: 85, color: 'var(--tier-ss-minus)' },
  { label: 'Velocity Beyond Abstract Infinity', weight: 1, tier: 'SS-', score: 85, color: 'var(--tier-ss-minus)' },
  { label: 'Crossed the Uncrossable', weight: 1, tier: 'SS-', score: 85, color: 'var(--tier-ss-minus)' },
  { label: 'Direction and Speed Are Redundant', weight: 1, tier: 'SS-', score: 85, color: 'var(--tier-ss-minus)' },
  { label: 'The Abyss Is Just Another Location', weight: 1, tier: 'SS-', score: 85, color: 'var(--tier-ss-minus)' },
  { label: 'Speed Collapses All Possible Routes', weight: 1, tier: 'SS-', score: 85, color: 'var(--tier-ss-minus)' },
  { label: 'Faster Than the Beginning of Time', weight: 1, tier: 'SS-', score: 85, color: 'var(--tier-ss-minus)' },
  { label: 'No Distance Is Not Instantly Trivial', weight: 1, tier: 'SS-', score: 85, color: 'var(--tier-ss-minus)' },
  { label: 'Even Timelessness Is a Route', weight: 1, tier: 'SS-', score: 85, color: 'var(--tier-ss-minus)' },
  { label: 'Speed Beyond Imaginary Measurement', weight: 1, tier: 'SS-', score: 85, color: 'var(--tier-ss-minus)' },
  { label: 'Skips Existence as a Shortcut', weight: 1, tier: 'SS-', score: 85, color: 'var(--tier-ss-minus)' },
  { label: 'Moved Before Motion Was Defined', weight: 1, tier: 'SS-', score: 85, color: 'var(--tier-ss-minus)' },

  // SS (score: 88)
  { label: 'Meta-Velocity', weight: 1, tier: 'SS', score: 88, color: 'var(--tier-ss)' },
  { label: 'Outruns the Thought of Speed', weight: 1, tier: 'SS', score: 88, color: 'var(--tier-ss)' },
  { label: 'Faster Than Even Nothing', weight: 1, tier: 'SS', score: 88, color: 'var(--tier-ss)' },
  { label: 'Pre-Existed All Travel', weight: 1, tier: 'SS', score: 88, color: 'var(--tier-ss)' },
  { label: 'Speed That Erases Its Own Concept', weight: 1, tier: 'SS', score: 88, color: 'var(--tier-ss)' },
  { label: 'Reached Everywhere Before Everywhere Was', weight: 1, tier: 'SS', score: 88, color: 'var(--tier-ss)' },
  { label: 'Moves at the Speed of Absolute Reality', weight: 1, tier: 'SS', score: 88, color: 'var(--tier-ss)' },
  { label: 'Speed Has Achieved Its Own Theology', weight: 1, tier: 'SS', score: 88, color: 'var(--tier-ss)' },
  { label: 'Omnipotence Is Just Adjacent', weight: 1, tier: 'SS', score: 88, color: 'var(--tier-ss)' },
  { label: 'Movement That Requires No Space', weight: 1, tier: 'SS', score: 88, color: 'var(--tier-ss)' },
  { label: 'Already Beyond the Boundary of All Things', weight: 1, tier: 'SS', score: 88, color: 'var(--tier-ss)' },
  { label: 'Speed Predates What Speed Would Travel Through', weight: 1, tier: 'SS', score: 88, color: 'var(--tier-ss)' },
  { label: 'Lapped All Possible Destinations', weight: 1, tier: 'SS', score: 88, color: 'var(--tier-ss)' },
  { label: 'Nowhere Is Off-Limits', weight: 1, tier: 'SS', score: 88, color: 'var(--tier-ss)' },
  { label: 'Movement Is Now Just Ontology', weight: 1, tier: 'SS', score: 88, color: 'var(--tier-ss)' },
  { label: 'Traverses Non-Being as Casually as a Stroll', weight: 1, tier: 'SS', score: 88, color: 'var(--tier-ss)' },
  { label: 'Speed Without Bounds or Definitions', weight: 1, tier: 'SS', score: 88, color: 'var(--tier-ss)' },
  { label: 'The Concept of Going Fast Submitted a Resignation', weight: 1, tier: 'SS', score: 88, color: 'var(--tier-ss)' },
  { label: 'Reaches Destinations That Don\'t Exist', weight: 1, tier: 'SS', score: 88, color: 'var(--tier-ss)' },
  { label: 'Speed: It\'s Personal Now', weight: 1, tier: 'SS', score: 88, color: 'var(--tier-ss)' },

  // SS+ (score: 91)
  { label: 'Godspeed (Pre-God)', weight: 1, tier: 'SS+', score: 91, color: 'var(--tier-ss-plus)' },
  { label: 'Moves at the Speed of Will', weight: 1, tier: 'SS+', score: 91, color: 'var(--tier-ss-plus)' },
  { label: 'Can Arrive Before Departure Was Conceivable', weight: 1, tier: 'SS+', score: 91, color: 'var(--tier-ss-plus)' },
  { label: 'Speed That Writes Theology', weight: 1, tier: 'SS+', score: 91, color: 'var(--tier-ss-plus)' },
  { label: 'Faster Than the Laws Governing Faster', weight: 1, tier: 'SS+', score: 91, color: 'var(--tier-ss-plus)' },
  { label: 'Moved at the Speed of Creation', weight: 1, tier: 'SS+', score: 91, color: 'var(--tier-ss-plus)' },
  { label: 'Was Everywhere Before Everywhere Was Possible', weight: 1, tier: 'SS+', score: 91, color: 'var(--tier-ss-plus)' },
  { label: 'Speed Renders Choice Redundant', weight: 1, tier: 'SS+', score: 91, color: 'var(--tier-ss-plus)' },
  { label: 'Location and Speed Are the Same Thing', weight: 1, tier: 'SS+', score: 91, color: 'var(--tier-ss-plus)' },
  { label: 'Moves Through Fundamental Absence', weight: 1, tier: 'SS+', score: 91, color: 'var(--tier-ss-plus)' },
  { label: 'Outruns the Idea That Anything Was Ever Still', weight: 1, tier: 'SS+', score: 91, color: 'var(--tier-ss-plus)' },
  { label: 'Has Reached the Destination That Hasn\'t Been Thought of Yet', weight: 1, tier: 'SS+', score: 91, color: 'var(--tier-ss-plus)' },
  { label: 'Speed: Even the God Tier Acknowledges', weight: 1, tier: 'SS+', score: 91, color: 'var(--tier-ss-plus)' },
  { label: 'Motion That Requires Nothing', weight: 1, tier: 'SS+', score: 91, color: 'var(--tier-ss-plus)' },
  { label: 'Can Lap Absolute Nothingness', weight: 1, tier: 'SS+', score: 91, color: 'var(--tier-ss-plus)' },
  { label: 'Velocity Beyond All Possible Definition', weight: 1, tier: 'SS+', score: 91, color: 'var(--tier-ss-plus)' },
  { label: 'Moves Faster Than the Creation of Faster', weight: 1, tier: 'SS+', score: 91, color: 'var(--tier-ss-plus)' },
  { label: 'Space Itself Doesn\'t Know Where They Are', weight: 1, tier: 'SS+', score: 91, color: 'var(--tier-ss-plus)' },
  { label: 'Speed Transcends the Requirement for Space', weight: 1, tier: 'SS+', score: 91, color: 'var(--tier-ss-plus)' },
  { label: 'The Universe Watches in Slow Motion', weight: 1, tier: 'SS+', score: 91, color: 'var(--tier-ss-plus)' },

  // SSS- (score: 94)
  { label: 'Absolute Speed', weight: 1, tier: 'SSS-', score: 94, color: 'var(--tier-sss-minus)' },
  { label: 'Was There Before There', weight: 1, tier: 'SSS-', score: 94, color: 'var(--tier-sss-minus)' },
  { label: 'Faster Than the Origin', weight: 1, tier: 'SSS-', score: 94, color: 'var(--tier-sss-minus)' },
  { label: 'Movement That Preceded Creation', weight: 1, tier: 'SSS-', score: 94, color: 'var(--tier-sss-minus)' },
  { label: 'Speed Has Become Its Own Natural Law', weight: 1, tier: 'SSS-', score: 94, color: 'var(--tier-sss-minus)' },
  { label: 'Everywhere Before Everywhere Was Named', weight: 1, tier: 'SSS-', score: 94, color: 'var(--tier-sss-minus)' },
  { label: 'Outruns Even Philosophical Constructs of Speed', weight: 1, tier: 'SSS-', score: 94, color: 'var(--tier-sss-minus)' },
  { label: 'Position: Wherever Needed Before Needed', weight: 1, tier: 'SSS-', score: 94, color: 'var(--tier-sss-minus)' },
  { label: 'Motion Without Departure or Arrival', weight: 1, tier: 'SSS-', score: 94, color: 'var(--tier-sss-minus)' },
  { label: 'Speed That Was the Premise of Existence', weight: 1, tier: 'SSS-', score: 94, color: 'var(--tier-sss-minus)' },
  { label: 'Crossed All Distances Before There Were Distances', weight: 1, tier: 'SSS-', score: 94, color: 'var(--tier-sss-minus)' },
  { label: 'Speed: The First Law', weight: 1, tier: 'SSS-', score: 94, color: 'var(--tier-sss-minus)' },
  { label: 'Omnipresent and Then Some', weight: 1, tier: 'SSS-', score: 94, color: 'var(--tier-sss-minus)' },
  { label: 'Past, Present, Future: Already Lapped', weight: 1, tier: 'SSS-', score: 94, color: 'var(--tier-sss-minus)' },
  { label: 'Traveled Through the Pre-Creation Void', weight: 1, tier: 'SSS-', score: 94, color: 'var(--tier-sss-minus)' },
  { label: 'Speed Wrote the Big Bang into Existence', weight: 1, tier: 'SSS-', score: 94, color: 'var(--tier-sss-minus)' },
  { label: 'Movement That Is Its Own Cosmology', weight: 1, tier: 'SSS-', score: 94, color: 'var(--tier-sss-minus)' },
  { label: 'Was Faster Than Possible', weight: 1, tier: 'SSS-', score: 94, color: 'var(--tier-sss-minus)' },
  { label: 'Speed That Doesn\'t Need Physics', weight: 1, tier: 'SSS-', score: 94, color: 'var(--tier-sss-minus)' },
  { label: 'No Frame of Reference Contains Them', weight: 1, tier: 'SSS-', score: 94, color: 'var(--tier-sss-minus)' },

  // SSS (score: 97)
  { label: 'Origin-Level Velocity', weight: 1, tier: 'SSS', score: 97, color: 'var(--tier-sss)' },
  { label: 'Moves at the Speed of Divinity', weight: 1, tier: 'SSS', score: 97, color: 'var(--tier-sss)' },
  { label: 'Speed Equivalent to Omniscience', weight: 1, tier: 'SSS', score: 97, color: 'var(--tier-sss)' },
  { label: 'First Motion Preceding All Others', weight: 1, tier: 'SSS', score: 97, color: 'var(--tier-sss)' },
  { label: 'Already Beyond the Last Possible Boundary', weight: 1, tier: 'SSS', score: 97, color: 'var(--tier-sss)' },
  { label: 'Speed That Erases Distance as a Concept', weight: 1, tier: 'SSS', score: 97, color: 'var(--tier-sss)' },
  { label: 'Moved Through the Void Before Void Was Named', weight: 1, tier: 'SSS', score: 97, color: 'var(--tier-sss)' },
  { label: 'Even Absence Cannot Contain Them', weight: 1, tier: 'SSS', score: 97, color: 'var(--tier-sss)' },
  { label: 'Location Gave Up as a Category', weight: 1, tier: 'SSS', score: 97, color: 'var(--tier-sss)' },
  { label: 'Speed That Is Indistinguishable from Creation', weight: 1, tier: 'SSS', score: 97, color: 'var(--tier-sss)' },
  { label: 'Reaches Every Possibility Before It Exists', weight: 1, tier: 'SSS', score: 97, color: 'var(--tier-sss)' },
  { label: 'The Concept of Fast Apologizes', weight: 1, tier: 'SSS', score: 97, color: 'var(--tier-sss)' },
  { label: 'Was Everywhere Before Omnipresence', weight: 1, tier: 'SSS', score: 97, color: 'var(--tier-sss)' },
  { label: 'Movement Is Its Own Universal Law Now', weight: 1, tier: 'SSS', score: 97, color: 'var(--tier-sss)' },
  { label: 'Traveled at the Speed of the Uncaused', weight: 1, tier: 'SSS', score: 97, color: 'var(--tier-sss)' },
  { label: 'Speed So Pure It Approaches Stillness', weight: 1, tier: 'SSS', score: 97, color: 'var(--tier-sss)' },
  { label: 'Reached the Pre-Existent Before It Pre-Existed', weight: 1, tier: 'SSS', score: 97, color: 'var(--tier-sss)' },
  { label: 'Physics Rewrote Itself to Accommodate', weight: 1, tier: 'SSS', score: 97, color: 'var(--tier-sss)' },
  { label: 'Destination and Origin: The Same Point', weight: 1, tier: 'SSS', score: 97, color: 'var(--tier-sss)' },
  { label: 'Motion That Preceded Cause', weight: 1, tier: 'SSS', score: 97, color: 'var(--tier-sss)' },

  // SSS+ (score: 99)
  { label: 'Beyond Omnipresence', weight: 1, tier: 'SSS+', score: 99, color: 'var(--tier-sss-plus)' },
  { label: 'Faster Than the Fact That Things Exist', weight: 1, tier: 'SSS+', score: 99, color: 'var(--tier-sss-plus)' },
  { label: 'Moves Through Pre-Being', weight: 1, tier: 'SSS+', score: 99, color: 'var(--tier-sss-plus)' },
  { label: 'Speed Defines Its Own Metaphysics', weight: 1, tier: 'SSS+', score: 99, color: 'var(--tier-sss-plus)' },
  { label: 'Arrived Before Existence Was an Option', weight: 1, tier: 'SSS+', score: 99, color: 'var(--tier-sss-plus)' },
  { label: 'Motion That Is a Fundamental Force', weight: 1, tier: 'SSS+', score: 99, color: 'var(--tier-sss-plus)' },
  { label: 'Speed That Pre-Dates the Concept of Going', weight: 1, tier: 'SSS+', score: 99, color: 'var(--tier-sss-plus)' },
  { label: 'All Locations Simultaneously at All Times', weight: 1, tier: 'SSS+', score: 99, color: 'var(--tier-sss-plus)' },
  { label: 'Velocity So High It Loops Back Through Nothing', weight: 1, tier: 'SSS+', score: 99, color: 'var(--tier-sss-plus)' },
  { label: 'Speed Wrote All of Physics', weight: 1, tier: 'SSS+', score: 99, color: 'var(--tier-sss-plus)' },
  { label: 'Moved Through Every Possible Non-Place', weight: 1, tier: 'SSS+', score: 99, color: 'var(--tier-sss-plus)' },
  { label: 'Even the Void Is a Lap Away', weight: 1, tier: 'SSS+', score: 99, color: 'var(--tier-sss-plus)' },
  { label: 'Before the Question Forms, Already Left', weight: 1, tier: 'SSS+', score: 99, color: 'var(--tier-sss-plus)' },
  { label: 'Speed: The Progenitor', weight: 1, tier: 'SSS+', score: 99, color: 'var(--tier-sss-plus)' },
  { label: 'Traverses the Infinite in a Single Step', weight: 1, tier: 'SSS+', score: 99, color: 'var(--tier-sss-plus)' },
  { label: 'Was Moving Before It Was Possible to Move', weight: 1, tier: 'SSS+', score: 99, color: 'var(--tier-sss-plus)' },
  { label: 'Motion Without Dimension', weight: 1, tier: 'SSS+', score: 99, color: 'var(--tier-sss-plus)' },
  { label: 'Destination: Everything', weight: 1, tier: 'SSS+', score: 99, color: 'var(--tier-sss-plus)' },
  { label: 'Speed Became a Fundamental Force', weight: 1, tier: 'SSS+', score: 99, color: 'var(--tier-sss-plus)' },
  { label: 'Space Is Just a Temporary Suggestion', weight: 1, tier: 'SSS+', score: 99, color: 'var(--tier-sss-plus)' },

  // God (score: 100)
  { label: 'Omnipresent', weight: 1, tier: 'God', score: 100, color: 'var(--tier-god)' },
  { label: 'Before the Question Forms', weight: 1, tier: 'God', score: 100, color: 'var(--tier-god)' },
  { label: 'Causality\'s Nightmare', weight: 1, tier: 'God', score: 100, color: 'var(--tier-god)' },
  { label: 'Exists at Every Moment Simultaneously', weight: 1, tier: 'God', score: 100, color: 'var(--tier-god)' },
  { label: 'The Concept of Distance Filed a Complaint', weight: 1, tier: 'God', score: 100, color: 'var(--tier-god)' },
  { label: 'Moved Before Movement Was Invented', weight: 1, tier: 'God', score: 100, color: 'var(--tier-god)' },
  { label: 'Speed That Defines Existence Itself', weight: 1, tier: 'God', score: 100, color: 'var(--tier-god)' },
  { label: 'Was There Before There Was a There', weight: 1, tier: 'God', score: 100, color: 'var(--tier-god)' },
  { label: 'Time Defers to Their Schedule', weight: 1, tier: 'God', score: 100, color: 'var(--tier-god)' },
  { label: 'Reached the End Before the Beginning', weight: 1, tier: 'God', score: 100, color: 'var(--tier-god)' },
  { label: 'No Distance Has Ever Applied', weight: 1, tier: 'God', score: 100, color: 'var(--tier-god)' },
  { label: 'Location: Everywhere and Nowhere', weight: 1, tier: 'God', score: 100, color: 'var(--tier-god)' },
  { label: 'Speed Was Their Idea', weight: 1, tier: 'God', score: 100, color: 'var(--tier-god)' },
  { label: 'Arrives at Destinations That Haven\'t Been Created', weight: 1, tier: 'God', score: 100, color: 'var(--tier-god)' },
  { label: 'Traverses the Uncreated Void on a Whim', weight: 1, tier: 'God', score: 100, color: 'var(--tier-god)' },
  { label: 'Motion That Is Synonymous With Being', weight: 1, tier: 'God', score: 100, color: 'var(--tier-god)' },
  { label: 'Past and Future Are Just Different Names for Now', weight: 1, tier: 'God', score: 100, color: 'var(--tier-god)' },
  { label: 'Speed Wrote the First Law', weight: 1, tier: 'God', score: 100, color: 'var(--tier-god)' },
  { label: 'Already Done Anything You\'ll Think Of', weight: 1, tier: 'God', score: 100, color: 'var(--tier-god)' },
  { label: 'Everywhere Always Was The Starting Point', weight: 1, tier: 'God', score: 100, color: 'var(--tier-god)' },
]
