import type { FlavorLabel } from './types'

export const speedLabels: FlavorLabel[] = [
  { label: 'Slower Than a Power Walk',        weight: 4, tier: 'F-',   score: 2,   color: '#555'    },
  { label: 'Casual Jogger',                   weight: 4, tier: 'F',    score: 5,   color: '#666'    },
  { label: 'Slightly Below Average Runner',   weight: 4, tier: 'F+',   score: 8,   color: '#777'    },
  { label: 'Light Jog',                       weight: 6, tier: 'E-',   score: 11,  color: '#6b7280' },
  { label: 'Keeps Up in a Foot Race',         weight: 6, tier: 'E',    score: 14,  color: '#9ca3af' },
  { label: 'Fast for a Civilian',             weight: 6, tier: 'E+',   score: 17,  color: '#d1d5db' },
  { label: 'Trained Sprinter Level',          weight: 8, tier: 'D-',   score: 20,  color: '#92400e' },
  { label: 'Track Team Material',             weight: 8, tier: 'D',    score: 23,  color: '#b45309' },
  { label: 'Near Athlete Grade',              weight: 8, tier: 'D+',   score: 26,  color: '#d97706' },
  { label: 'Olympic Sprinter Speed',          weight: 8, tier: 'C-',   score: 30,  color: '#1d4ed8' },
  { label: 'Faster Than Any Human',           weight: 8, tier: 'C',    score: 34,  color: '#2563eb' },
  { label: 'Blur of Motion',                  weight: 8, tier: 'C+',   score: 38,  color: '#3b82f6' },
  { label: 'Outpaces Vehicles',               weight: 7, tier: 'B-',   score: 42,  color: '#065f46' },
  { label: 'Sonic Adjacent',                  weight: 7, tier: 'B',    score: 47,  color: '#059669' },
  { label: 'Hypersonic',                      weight: 7, tier: 'B+',   score: 52,  color: '#34d399' },
  { label: "Can't Be Seen When Moving",       weight: 5, tier: 'A-',   score: 57,  color: '#7c3aed' },
  { label: 'Mach-Speed Combat',               weight: 5, tier: 'A',    score: 62,  color: '#8b5cf6' },
  { label: 'Crosses Continents Instantly',    weight: 5, tier: 'A+',   score: 67,  color: '#a78bfa' },
  { label: 'Orbits the Planet in Seconds',    weight: 4, tier: 'S-',   score: 72,  color: '#b91c1c' },
  { label: 'Breaks Light Speed',              weight: 4, tier: 'S',    score: 77,  color: '#dc2626' },
  { label: 'Relativistic Velocity',           weight: 4, tier: 'S+',   score: 81,  color: '#ef4444' },
  { label: 'Outpaces Time Itself',            weight: 3, tier: 'SS-',  score: 85,  color: '#ea580c' },
  { label: 'Exists Everywhere at Once',       weight: 3, tier: 'SS',   score: 88,  color: '#f97316' },
  { label: 'Moves Between Dimensions',        weight: 3, tier: 'SS+',  score: 91,  color: '#fb923c' },
  { label: 'Beyond Causality',                          weight: 2, tier: 'SSS-',      score: 94,  color: '#ca8a04' },
  { label: 'Instantaneous Omnipresence',                weight: 2, tier: 'SSS',       score: 97,  color: '#eab308' },
  { label: 'Speed Is a Concept, Not a Limit',           weight: 2, tier: 'SSS+',      score: 99,  color: '#fde047' },
  { label: 'Laps the Observable Universe',              weight: 2, tier: 'Z-',        score: 101, color: '#0e7490' },
  { label: 'Moves Between the Seams of Reality',        weight: 2, tier: 'Z',         score: 103, color: '#0891b2' },
  { label: 'Crosses Universes Before Deciding To',      weight: 2, tier: 'Z+',        score: 105, color: '#06b6d4' },
  { label: 'Travels Without Needing to Move',           weight: 1, tier: 'ZZ-',       score: 107, color: '#3730a3' },
  { label: 'Speed Has Become a Personal Courtesy',      weight: 1, tier: 'ZZ',        score: 109, color: '#4f46e5' },
  { label: 'Arrives Before the Decision to Leave',      weight: 1, tier: 'ZZ+',       score: 111, color: '#818cf8' },
  { label: 'Movement Is Now Retrospective',             weight: 1, tier: 'ZZZ-',      score: 113, color: '#9d174d' },
  { label: 'Reached the Destination Before It Existed', weight: 1, tier: 'ZZZ',       score: 115, color: '#be185d' },
  { label: 'Fast Enough to Outrun Consequences',        weight: 1, tier: 'ZZZ+',      score: 117, color: '#ec4899' },
  { label: 'Moves at the Speed of Divine Intent',       weight: 1, tier: 'Celestial-',score: 119, color: '#075985' },
  { label: 'Traverses the Divine Planes Instantly',     weight: 1, tier: 'Celestial', score: 121, color: '#0284c7' },
  { label: 'Even Gods Cannot Track the Movement',       weight: 1, tier: 'Celestial+',score: 123, color: '#38bdf8' },
  { label: 'Speed That Preceded Time Itself',           weight: 1, tier: 'Godly-',    score: 125, color: '#c026d3' },
  { label: 'The Flash Would Tap Out',                   weight: 1, tier: 'Godly',     score: 127, color: '#e879f9' },
  { label: 'Was There Before Movement Existed',         weight: 1, tier: 'Primordial',score: 130, color: '#ffffff' },
]
