import type { FlavorLabel } from './types'

// Strength scale: F- = can barely lift their own arms, mortal mid = elite athlete,
// A+ = peak human/world-record lifter (B-tier no longer "tank-shrugging"),
// S–SSS = superhuman → reality-bending, Cosmic+ = post-mortal force,
// Infinite+ = strength beyond infinity.
export const strengthLabels: FlavorLabel[] = [
  { label: 'Wet Noodle Arms',                                weight: 4, tier: 'F-',            score: 2,   color: '#4a4a4a' },
  { label: 'Loses Arm Wrestles to Children',                 weight: 4, tier: 'F',             score: 5,   color: '#5c5c5c' },
  { label: 'Struggles With a Full Backpack',                 weight: 4, tier: 'F+',            score: 8,   color: '#6e6e6e' },
  { label: 'Below-Average Grip',                             weight: 6, tier: 'E-',            score: 11,  color: '#6b7280' },
  { label: 'Average Adult Strength',                         weight: 6, tier: 'E',             score: 14,  color: '#9ca3af' },
  { label: 'Solid Handshake',                                weight: 6, tier: 'E+',            score: 17,  color: '#d1d5db' },
  { label: 'Holds Their Own in a Scuffle',                   weight: 8, tier: 'D-',            score: 20,  color: '#92400e' },
  { label: 'Casually Fit',                                   weight: 8, tier: 'D',             score: 23,  color: '#b45309' },
  { label: 'Visibly Strong',                                 weight: 8, tier: 'D+',            score: 26,  color: '#d97706' },
  { label: 'Gym Regular',                                    weight: 8, tier: 'C-',            score: 30,  color: '#1d4ed8' },
  { label: 'Strong for Their Weight Class',                  weight: 9, tier: 'C',             score: 34,  color: '#2563eb' },
  { label: 'Amateur Power Lifter',                           weight: 8, tier: 'C+',            score: 38,  color: '#3b82f6' },
  { label: 'Bouncer Build',                                  weight: 7, tier: 'B-',            score: 42,  color: '#065f46' },
  { label: 'Professional Strongman',                         weight: 7, tier: 'B',             score: 47,  color: '#059669' },
  { label: 'National-Level Lifter',                          weight: 7, tier: 'B+',            score: 52,  color: '#34d399' },
  { label: 'Olympic-Grade Power',                            weight: 5, tier: 'A-',            score: 57,  color: '#7c3aed' },
  { label: 'World-Record Holder',                            weight: 5, tier: 'A',             score: 62,  color: '#8b5cf6' },
  { label: 'Peak Human Specimen',                            weight: 5, tier: 'A+',            score: 67,  color: '#a78bfa' },
  { label: 'Superhuman Muscle',                              weight: 4, tier: 'S-',            score: 72,  color: '#b91c1c' },
  { label: 'Bends Steel Bars Casually',                      weight: 4, tier: 'S',             score: 77,  color: '#dc2626' },
  { label: 'Lifts Cars Off Trapped People',                  weight: 4, tier: 'S+',            score: 81,  color: '#ef4444' },
  { label: 'Tosses Tanks Like Furniture',                    weight: 3, tier: 'SS-',           score: 85,  color: '#ea580c' },
  { label: 'Pulverizes Concrete Buildings',                  weight: 3, tier: 'SS',            score: 88,  color: '#f97316' },
  { label: 'Throws Aircraft Carriers',                       weight: 3, tier: 'SS+',           score: 91,  color: '#fb923c' },
  { label: 'Continental Shockwave on Impact',                weight: 2, tier: 'SSS-',          score: 94,  color: '#ca8a04' },
  { label: 'Planetary-Scale Might',                          weight: 2, tier: 'SSS',           score: 97,  color: '#eab308' },
  { label: 'Universe-Bending Force',                         weight: 2, tier: 'SSS+',          score: 99,  color: '#fde047' },
  { label: 'Shatters Stars With a Strike',                   weight: 2, tier: 'Z-',            score: 101, color: '#be185d' },
  { label: 'Collapses Solar Systems Casually',               weight: 2, tier: 'Z',             score: 103, color: '#db2777' },
  { label: 'Unravels Galaxies on Impact',                    weight: 2, tier: 'Z+',            score: 105, color: '#ec4899' },
  { label: 'Dents the Fabric of Multiple Universes',         weight: 1, tier: 'ZZ-',           score: 107, color: '#6d28d9' },
  { label: 'Breaks Parallel Realities on Contact',           weight: 1, tier: 'ZZ',            score: 109, color: '#7c3aed' },
  { label: 'Force Transcends Any Universe',                  weight: 1, tier: 'ZZ+',           score: 111, color: '#8b5cf6' },
  { label: 'Stronger Than the Rules Defining Strength',      weight: 1, tier: 'ZZZ-',          score: 113, color: '#0e7490' },
  { label: 'Reality Briefly Reboots on Their Hits',          weight: 1, tier: 'ZZZ',           score: 115, color: '#06b6d4' },
  { label: 'Hits So Hard the Concept of Force Complains',    weight: 1, tier: 'ZZZ+',          score: 117, color: '#22d3ee' },
  { label: 'Cosmic-Scale Strength',                          weight: 1, tier: 'Cosmic-',       score: 119, color: '#0e6b8a' },
  { label: 'Wrestles Cosmic Forces by Hand',                 weight: 1, tier: 'Cosmic',        score: 121, color: '#0891b2' },
  { label: 'Knocks Constellations Out of Alignment',         weight: 1, tier: 'Cosmic+',       score: 123, color: '#06b6d4' },
  { label: 'Strength That Refuses to Die',                   weight: 1, tier: 'Immortal-',     score: 125, color: '#d946ef' },
  { label: 'Immortal-Class Muscle',                          weight: 1, tier: 'Immortal',      score: 127, color: '#ec4899' },
  { label: 'Has Lifted Things That No Longer Exist',         weight: 1, tier: 'Immortal+',     score: 129, color: '#f472b6' },
  { label: 'Punches Echo Across the Divine Planes',          weight: 1, tier: 'Celestial-',    score: 131, color: '#831843' },
  { label: 'Strength Granted by the Stars Themselves',       weight: 1, tier: 'Celestial',     score: 133, color: '#9d174d' },
  { label: 'Even Gods Train to Resist This Force',           weight: 1, tier: 'Celestial+',    score: 135, color: '#be185d' },
  { label: 'Strength That Rewrites Creation',                weight: 1, tier: 'Godly-',        score: 137, color: '#f9a8d4' },
  { label: 'Lifts Reality Itself',                           weight: 1, tier: 'Godly',         score: 139, color: '#f472b6' },
  { label: 'Snaps the Spine of Causality',                   weight: 1, tier: 'Godly+',        score: 141, color: '#ec4899' },
  { label: 'Existed Before the Concept of Force',            weight: 1, tier: 'Primordial-',   score: 143, color: '#d4d4d8' },
  { label: 'Authored Resistance Itself',                     weight: 1, tier: 'Primordial',    score: 145, color: '#e4e4e7' },
  { label: 'Conceptual Annihilation per Strike',             weight: 1, tier: 'Primordial+',   score: 147, color: '#fafafa' },
  { label: 'Strength Is Just a Word For What They Are',      weight: 1, tier: 'Absolute-',     score: 149, color: '#7dd3fc' },
  { label: 'Force That Wrote the First Law of Physics',      weight: 1, tier: 'Absolute',      score: 151, color: '#38bdf8' },
  { label: 'Absolute Power, Uncontested',                    weight: 1, tier: 'Absolute+',     score: 153, color: '#0ea5e9' },
  { label: 'Beyond the Idea of Strength',                    weight: 1, tier: 'Transcendent-', score: 155, color: '#84cc16' },
  { label: 'Force Itself Defers to Them',                    weight: 1, tier: 'Transcendent',  score: 157, color: '#65a30d' },
  { label: 'Power Transcends Power',                         weight: 1, tier: 'Transcendent+', score: 159, color: '#4d7c0f' },
  { label: 'Infinite Strength',                              weight: 1, tier: 'Infinite-',     score: 161, color: '#525252' },
  { label: 'Truly Infinite Power',                           weight: 1, tier: 'Infinite',      score: 163, color: '#262626' },
  { label: 'Beyond Infinite Force',                          weight: 1, tier: 'Infinite+',     score: 165, color: '#000000' },
]
