import type { FlavorLabel } from './types'

// One label per tier grade (28 total). Weights are base-1; dynamic scoring in +page.svelte overrides distribution.
export const strengthLabels: FlavorLabel[] = [
  { label: 'Wet Noodle Arm',                weight: 4, tier: 'F-',   score: 2,   color: '#555'     },
  { label: 'Below Average Handshake',        weight: 4, tier: 'F',    score: 5,   color: '#666'     },
  { label: 'Marginally Stronger Than a Child', weight: 4, tier: 'F+', score: 8,  color: '#777'     },
  { label: 'Can Lift a Toddler',             weight: 6, tier: 'E-',   score: 11,  color: '#6b7280'  },
  { label: 'Neighborhood Average',           weight: 6, tier: 'E',    score: 14,  color: '#9ca3af'  },
  { label: 'Decent Grip Strength',           weight: 6, tier: 'E+',   score: 17,  color: '#d1d5db'  },
  { label: 'Can Hold Their Own',             weight: 8, tier: 'D-',   score: 20,  color: '#92400e'  },
  { label: 'Solidly Fit',                    weight: 8, tier: 'D',    score: 23,  color: '#b45309'  },
  { label: 'Above-Average Gym Build',        weight: 8, tier: 'D+',   score: 26,  color: '#d97706'  },
  { label: 'Noticeably Strong',              weight: 8, tier: 'C-',   score: 30,  color: '#1d4ed8'  },
  { label: 'Street Fighter Physique',        weight: 8, tier: 'C',    score: 34,  color: '#2563eb'  },
  { label: 'Power Lifter Energy',            weight: 8, tier: 'C+',   score: 38,  color: '#3b82f6'  },
  { label: 'Breaks Things by Accident',      weight: 7, tier: 'B-',   score: 42,  color: '#065f46'  },
  { label: 'Olympic-Grade Strength',         weight: 7, tier: 'B',    score: 47,  color: '#059669'  },
  { label: 'Peak Human Specimen',            weight: 7, tier: 'B+',   score: 52,  color: '#34d399'  },
  { label: 'Superhuman Muscles',             weight: 5, tier: 'A-',   score: 57,  color: '#7c3aed'  },
  { label: 'Bends Steel Bars',              weight: 5, tier: 'A',    score: 62,  color: '#8b5cf6'  },
  { label: 'Punches Through Buildings',      weight: 5, tier: 'A+',   score: 67,  color: '#a78bfa'  },
  { label: 'Throws Tanks Like Frisbees',     weight: 4, tier: 'S-',   score: 72,  color: '#b91c1c'  },
  { label: 'Moves Mountains',               weight: 4, tier: 'S',    score: 77,  color: '#dc2626'  },
  { label: 'Tectonic Force',                weight: 4, tier: 'S+',   score: 81,  color: '#ef4444'  },
  { label: 'Continental Shockwave',          weight: 3, tier: 'SS-',  score: 85,  color: '#ea580c'  },
  { label: 'Planetary-Scale Might',          weight: 3, tier: 'SS',   score: 88,  color: '#f97316'  },
  { label: 'Stellar Catastrophe',            weight: 3, tier: 'SS+',  score: 91,  color: '#fb923c'  },
  { label: 'Universal Physical Threat',                   weight: 2, tier: 'SSS-',      score: 94,  color: '#ca8a04' },
  { label: 'Reality-Breaking Strength',                   weight: 2, tier: 'SSS',       score: 97,  color: '#eab308' },
  { label: 'Omnipotent Physical Force',                   weight: 2, tier: 'SSS+',      score: 99,  color: '#fde047' },
  { label: 'Shatters Galactic Clusters',                  weight: 2, tier: 'Z-',        score: 101, color: '#0e7490' },
  { label: 'Casually Collapses Solar Systems',            weight: 2, tier: 'Z',         score: 103, color: '#0891b2' },
  { label: 'Unravels Space-Time With a Swing',            weight: 2, tier: 'Z+',        score: 105, color: '#06b6d4' },
  { label: 'Dents the Fabric of Multiple Universes',      weight: 1, tier: 'ZZ-',       score: 107, color: '#3730a3' },
  { label: 'Breaks Parallel Realities on Impact',         weight: 1, tier: 'ZZ',        score: 109, color: '#4f46e5' },
  { label: 'Physical Force Transcends Any Universe',      weight: 1, tier: 'ZZ+',       score: 111, color: '#818cf8' },
  { label: 'Stronger Than the Laws That Define Strength', weight: 1, tier: 'ZZZ-',      score: 113, color: '#9d174d' },
  { label: 'The Concept of Force Files a Complaint',      weight: 1, tier: 'ZZZ',       score: 115, color: '#be185d' },
  { label: 'Hits So Hard Reality Briefly Reboots',        weight: 1, tier: 'ZZZ+',      score: 117, color: '#ec4899' },
  { label: 'Punches Are Felt Across the Divine Planes',   weight: 1, tier: 'Celestial-',score: 119, color: '#075985' },
  { label: 'Strength Granted by the Stars Themselves',    weight: 1, tier: 'Celestial', score: 121, color: '#0284c7' },
  { label: 'Even Gods Train to Eventually Resist This',   weight: 1, tier: 'Celestial+',score: 123, color: '#38bdf8' },
  { label: 'Strength That Rewrites the Rules of Creation',weight: 1, tier: 'Godly-',    score: 125, color: '#c026d3' },
  { label: 'Lifts Reality Itself',                        weight: 1, tier: 'Godly',     score: 127, color: '#e879f9' },
  { label: 'Existed Before the Concept of Force',         weight: 1, tier: 'Primordial',score: 130, color: '#ffffff' },
]
