import type { FlavorLabel } from './types'

// One label per tier grade (28 total). Weights are base-1; dynamic scoring in +page.svelte overrides distribution.
export const strengthLabels: FlavorLabel[] = [
  { label: 'Wet Noodle Arm',                weight: 1, tier: 'F-',   score: 2,   color: '#555'     },
  { label: 'Below Average Handshake',        weight: 1, tier: 'F',    score: 5,   color: '#666'     },
  { label: 'Marginally Stronger Than a Child', weight: 1, tier: 'F+', score: 8,  color: '#777'     },
  { label: 'Can Lift a Toddler',             weight: 1, tier: 'E-',   score: 11,  color: '#6b7280'  },
  { label: 'Neighborhood Average',           weight: 1, tier: 'E',    score: 14,  color: '#9ca3af'  },
  { label: 'Decent Grip Strength',           weight: 1, tier: 'E+',   score: 17,  color: '#d1d5db'  },
  { label: 'Can Hold Their Own',             weight: 1, tier: 'D-',   score: 20,  color: '#92400e'  },
  { label: 'Solidly Fit',                    weight: 1, tier: 'D',    score: 23,  color: '#b45309'  },
  { label: 'Above-Average Gym Build',        weight: 1, tier: 'D+',   score: 26,  color: '#d97706'  },
  { label: 'Noticeably Strong',              weight: 1, tier: 'C-',   score: 30,  color: '#1d4ed8'  },
  { label: 'Street Fighter Physique',        weight: 1, tier: 'C',    score: 34,  color: '#2563eb'  },
  { label: 'Power Lifter Energy',            weight: 1, tier: 'C+',   score: 38,  color: '#3b82f6'  },
  { label: 'Breaks Things by Accident',      weight: 1, tier: 'B-',   score: 42,  color: '#065f46'  },
  { label: 'Olympic-Grade Strength',         weight: 1, tier: 'B',    score: 47,  color: '#059669'  },
  { label: 'Peak Human Specimen',            weight: 1, tier: 'B+',   score: 52,  color: '#34d399'  },
  { label: 'Superhuman Muscles',             weight: 1, tier: 'A-',   score: 57,  color: '#7c3aed'  },
  { label: 'Bends Steel Bars',              weight: 1, tier: 'A',    score: 62,  color: '#8b5cf6'  },
  { label: 'Punches Through Buildings',      weight: 1, tier: 'A+',   score: 67,  color: '#a78bfa'  },
  { label: 'Throws Tanks Like Frisbees',     weight: 1, tier: 'S-',   score: 72,  color: '#b91c1c'  },
  { label: 'Moves Mountains',               weight: 1, tier: 'S',    score: 77,  color: '#dc2626'  },
  { label: 'Tectonic Force',                weight: 1, tier: 'S+',   score: 81,  color: '#ef4444'  },
  { label: 'Continental Shockwave',          weight: 1, tier: 'SS-',  score: 85,  color: '#ea580c'  },
  { label: 'Planetary-Scale Might',          weight: 1, tier: 'SS',   score: 88,  color: '#f97316'  },
  { label: 'Stellar Catastrophe',            weight: 1, tier: 'SS+',  score: 91,  color: '#fb923c'  },
  { label: 'Universal Physical Threat',      weight: 1, tier: 'SSS-', score: 94,  color: '#ca8a04'  },
  { label: 'Reality-Breaking Strength',      weight: 1, tier: 'SSS',  score: 97,  color: '#eab308'  },
  { label: 'Omnipotent Physical Force',      weight: 1, tier: 'SSS+', score: 99,  color: '#fde047'  },
  { label: 'Lifts Reality Itself',           weight: 1, tier: 'God',  score: 100, color: '#e879f9'  },
]
