// titles.ts — Title content pool for Wheel of Fate.
// Every title grants at least one statBonusGrants entry (positive or negative).
// No default export. No functions. Static const array only.

import type { SimpleItem } from './types'

export const titles: SimpleItem[] = [
  // ── Epic Titles — strong bonuses ──
  { label: 'The Undying',           weight: 1, statBonusGrants: { durability: 'statBonus', energyLevel: 'statBonus' } },
  { label: 'Harbinger of Storms',   weight: 1, statBonusGrants: { energyLevel: 'statBonus', powerMastery: 'statBonus' } },
  { label: 'God-Slayer',            weight: 1, statBonusGrants: { fightingSkill: 'statBonus', strength: 'statBonus' } },
  { label: 'The Eternal',           weight: 1, statBonusGrants: { potential: 'statBonus', durability: 'statBonus' } },
  { label: 'Void-Touched',          weight: 1, statBonusGrants: { powerMastery: 'statBonus', iq: 'statBonus' } },
  { label: 'Scourge of Nations',    weight: 1, statBonusGrants: { fightingSkill: 'statBonus', charisma: 'statPenalty' } },
  { label: 'The Unyielding',        weight: 1, statBonusGrants: { durability: 'statBonus', strength: 'statBonus' } },
  { label: 'Lord of Ash',           weight: 1, statBonusGrants: { energyLevel: 'statBonus', charisma: 'statPenalty' } },
  { label: 'The Forsaken',          weight: 1, statBonusGrants: { potential: 'statBonus', charisma: 'statPenalty' } },
  { label: 'World-Ender',           weight: 1, statBonusGrants: { strength: 'statBonus', powerMastery: 'statBonus', charisma: 'statPenalty' } },
  { label: 'The Immovable',         weight: 1, statBonusGrants: { strength: 'statBonus', durability: 'statBonus' } },
  { label: 'Bane of Heaven',        weight: 1, statBonusGrants: { strength: 'statBonus', fightingSkill: 'statBonus' } },
  { label: 'The Inevitable',        weight: 1, statBonusGrants: { speed: 'statBonus', potential: 'statBonus' } },
  { label: 'Last of Their Kind',    weight: 1, statBonusGrants: { strength: 'statBonus', charisma: 'statPenalty' } },
  { label: 'The Relentless',        weight: 1, statBonusGrants: { speed: 'statBonus', energyLevel: 'statBonus' } },
  { label: 'Breaker of Seals',      weight: 1, statBonusGrants: { powerMastery: 'statBonus', iq: 'statBonus' } },
  { label: 'The Unkillable',        weight: 1, statBonusGrants: { durability: 'statBonus', energyLevel: 'statBonus' } },
  { label: 'Destroyer of Truths',   weight: 1, statBonusGrants: { iq: 'statBonus', charisma: 'statBonus' } },
  { label: 'The Boundless',         weight: 1, statBonusGrants: { speed: 'statBonus', agility: 'statBonus' } },
  { label: 'Sovereign of Ruin',     weight: 1, statBonusGrants: { durability: 'statBonus', strength: 'statBonus', charisma: 'statPenalty' } },
  { label: 'The Desolate',          weight: 1, statBonusGrants: { durability: 'statBonus', charisma: 'statPenalty' } },
  { label: 'Wrath Incarnate',       weight: 1, statBonusGrants: { strength: 'statBonus', fightingSkill: 'statBonus' } },
  { label: 'The Unbound',           weight: 1, statBonusGrants: { agility: 'statBonus', speed: 'statBonus' } },
  { label: 'Eclipse of Ages',       weight: 1, statBonusGrants: { energyLevel: 'statBonus', potential: 'statBonus' } },
  { label: 'The Inexorable',        weight: 1, statBonusGrants: { durability: 'statBonus', fightingSkill: 'statBonus' } },
  { label: 'Devourer of Worlds',    weight: 1, statBonusGrants: { powerMastery: 'statBonus', strength: 'statBonus' } },
  { label: 'The Inescapable',       weight: 1, statBonusGrants: { speed: 'statBonus', agility: 'statBonus' } },
  { label: 'Reaper of Fates',       weight: 1, statBonusGrants: { fightingSkill: 'statBonus', agility: 'statBonus' } },
  { label: 'The Transcendent',      weight: 1, statBonusGrants: { potential: 'statBonus', powerMastery: 'statBonus' } },
  { label: 'Apex Predator',         weight: 1, statBonusGrants: { agility: 'statBonus', fightingSkill: 'statBonus' } },
  { label: 'Herald of Endings',     weight: 1, statBonusGrants: { potential: 'statBonus', energyLevel: 'statBonus' } },
  { label: 'The Primordial',        weight: 1, statBonusGrants: { strength: 'statBonus', durability: 'statBonus' } },
  { label: 'Terror of the Void',    weight: 1, statBonusGrants: { powerMastery: 'statBonus', iq: 'statBonus' } },
  { label: 'The Unconquered',       weight: 1, statBonusGrants: { fightingSkill: 'statBonus', durability: 'statBonus' } },
  { label: 'Sovereign of Shadows',  weight: 1, statBonusGrants: { agility: 'statBonus', charisma: 'statBonus' } },
  { label: 'The Undeniable',        weight: 1, statBonusGrants: { charisma: 'statBonus', strength: 'statBonus' } },
  { label: 'Flame of Apocalypse',   weight: 1, statBonusGrants: { energyLevel: 'statBonus', powerMastery: 'statBonus' } },
  { label: 'The Implacable',        weight: 1, statBonusGrants: { durability: 'statBonus', fightingSkill: 'statBonus' } },
  { label: 'Scion of Oblivion',     weight: 1, statBonusGrants: { powerMastery: 'statBonus', potential: 'statBonus' } },
  { label: 'The Remorseless',       weight: 1, statBonusGrants: { fightingSkill: 'statBonus', charisma: 'statPenalty' } },
  { label: 'Champion of Nothingness', weight: 1, statBonusGrants: { strength: 'statBonus', iq: 'statBonus' } },
  { label: 'The Unstoppable',       weight: 1, statBonusGrants: { speed: 'statBonus', durability: 'statBonus' } },
  { label: 'Harbinger of Silence',  weight: 1, statBonusGrants: { agility: 'statBonus', charisma: 'statPenalty' } },
  { label: 'The Absolute',          weight: 1, statBonusGrants: { potential: 'statBonus', powerMastery: 'statBonus', fightingSkill: 'statBonus' } },
  { label: 'Vessel of the End',     weight: 1, statBonusGrants: { energyLevel: 'statBonus', durability: 'statBonus' } },
  { label: 'The Unbroken',          weight: 1, statBonusGrants: { durability: 'statBonus', strength: 'statBonus' } },
  { label: 'Shadow of Eternity',    weight: 1, statBonusGrants: { agility: 'statBonus', speed: 'statBonus' } },
  { label: 'The Undefeated',        weight: 1, statBonusGrants: { fightingSkill: 'statBonus', potential: 'statBonus' } },
  { label: 'Apex of Fear',          weight: 1, statBonusGrants: { charisma: 'statBonus', fightingSkill: 'statBonus' } },
  { label: 'The Interminable',      weight: 1, statBonusGrants: { durability: 'statBonus', energyLevel: 'statBonus' } },
  { label: 'Calamity Made Flesh',   weight: 1, statBonusGrants: { strength: 'statBonus', powerMastery: 'statBonus' } },
  { label: 'The Undoubted',         weight: 1, statBonusGrants: { charisma: 'statBonus', iq: 'statBonus' } },

  // ── More Epic Titles ──
  { label: 'Oathbreaker',           weight: 1, statBonusGrants: { strength: 'statBonus', charisma: 'statPenalty' } },
  { label: 'The Unchained',         weight: 1, statBonusGrants: { strength: 'statBonus', agility: 'statBonus' } },
  { label: 'Demon King',            weight: 1, statBonusGrants: { strength: 'statBonus', fightingSkill: 'statBonus', charisma: 'statPenalty' } },
  { label: 'The Undaunted',         weight: 1, statBonusGrants: { durability: 'statBonus', fightingSkill: 'statBonus' } },
  { label: 'Pinnacle of Violence',  weight: 1, statBonusGrants: { fightingSkill: 'statBonus', strength: 'statBonus' } },
  { label: 'The Corrupted',         weight: 1, statBonusGrants: { powerMastery: 'statBonus', charisma: 'statPenalty', iq: 'statPenalty' } },
  { label: 'Harbinger of Blood',    weight: 1, statBonusGrants: { fightingSkill: 'statBonus', speed: 'statBonus' } },
  { label: 'The Cataclysm',         weight: 1, statBonusGrants: { energyLevel: 'statBonus', strength: 'statBonus' } },
  { label: 'Sovereign of War',      weight: 1, statBonusGrants: { fightingSkill: 'statBonus', strength: 'statBonus', charisma: 'statBonus' } },
  { label: 'The Unmatched',         weight: 1, statBonusGrants: { fightingSkill: 'statBonus', agility: 'statBonus' } },
  { label: 'Blade of the Cosmos',   weight: 1, statBonusGrants: { weaponMastery: 'statBonus', fightingSkill: 'statBonus' } },
  { label: 'The Unbowed',           weight: 1, statBonusGrants: { durability: 'statBonus', charisma: 'statBonus' } },
  { label: 'Void Sovereign',        weight: 1, statBonusGrants: { powerMastery: 'statBonus', iq: 'statBonus', charisma: 'statPenalty' } },
  { label: 'The Terrible',          weight: 1, statBonusGrants: { strength: 'statBonus', charisma: 'statBonus' } },
  { label: 'Extinction Event',      weight: 1, statBonusGrants: { strength: 'statBonus', energyLevel: 'statBonus', iq: 'statPenalty' } },

  // ── Absurd Titles — small penalties or minor misfortune ──
  { label: 'The Perpetually Confused',       weight: 1, statBonusGrants: { iq: 'statPenalty' } },
  { label: 'He Who Trips on Flat Surfaces',  weight: 1, statBonusGrants: { agility: 'statPenalty' } },
  { label: 'Smell of Old Books',             weight: 1, statBonusGrants: { charisma: 'statPenalty', iq: 'statBonus' } },
  { label: 'The Unreasonably Tall',          weight: 1, statBonusGrants: { strength: 'statBonus', agility: 'statPenalty' } },
  { label: 'Professional Disappointment',   weight: 1, statBonusGrants: { charisma: 'statPenalty' } },
  { label: 'The Mildly Ominous',             weight: 1, statBonusGrants: { charisma: 'statBonus' } },
  { label: 'Mostly Harmless',               weight: 1, statBonusGrants: { fightingSkill: 'statPenalty', charisma: 'statBonus' } },
  { label: 'The Suspiciously Cheerful',     weight: 1, statBonusGrants: { charisma: 'statBonus', iq: 'statPenalty' } },
  { label: 'He Who Cannot Park Correctly',  weight: 1, statBonusGrants: { agility: 'statPenalty' } },
  { label: 'The Aggressively Normal',       weight: 1, statBonusGrants: { charisma: 'statPenalty' } },
  { label: 'Bane of Staplers',              weight: 1, statBonusGrants: { iq: 'statPenalty', strength: 'statBonus' } },
  { label: 'The Chronically Late',          weight: 1, statBonusGrants: { speed: 'statPenalty' } },
  { label: 'Expert of Unsolicited Opinions', weight: 1, statBonusGrants: { charisma: 'statPenalty', iq: 'statBonus' } },
  { label: 'The Involuntary Hiccupper',     weight: 1, statBonusGrants: { charisma: 'statPenalty' } },
  { label: 'The Unnecessarily Verbose',     weight: 1, statBonusGrants: { charisma: 'statPenalty', iq: 'statBonus' } },
  { label: 'He Who Misses Obvious Hints',   weight: 1, statBonusGrants: { iq: 'statPenalty' } },
  { label: 'The Perpetually Overdressed',   weight: 1, statBonusGrants: { charisma: 'statBonus', agility: 'statPenalty' } },
  { label: 'Accidentally Famous',           weight: 1, statBonusGrants: { charisma: 'statBonus' } },
  { label: 'The Suspiciously Helpful',      weight: 1, statBonusGrants: { charisma: 'statBonus', iq: 'statPenalty' } },
  { label: 'Fear Him Not, for He Is Fine',  weight: 1, statBonusGrants: { durability: 'statBonus', fightingSkill: 'statPenalty' } },
  { label: 'The Mildly Inconvenienced',     weight: 1, statBonusGrants: { durability: 'statPenalty' } },
  { label: 'Somewhat Legendary',            weight: 1, statBonusGrants: { charisma: 'statBonus' } },
  { label: 'The Regrettably Memorable',     weight: 1, statBonusGrants: { charisma: 'statBonus', iq: 'statPenalty' } },
  { label: 'Feared by Few, Tolerated by Most', weight: 1, statBonusGrants: { charisma: 'statPenalty', fightingSkill: 'statBonus' } },
  { label: 'He Who Takes the Last Slice',   weight: 1, statBonusGrants: { charisma: 'statPenalty', strength: 'statBonus' } },
  { label: 'The Boldly Mediocre',           weight: 1, statBonusGrants: { charisma: 'statPenalty' } },
  { label: 'The Indecisive',                weight: 1, statBonusGrants: { iq: 'statPenalty', speed: 'statPenalty' } },
  { label: 'The One Who Replies-All',       weight: 1, statBonusGrants: { charisma: 'statPenalty' } },
  { label: 'Bane of Good Parking Spots',    weight: 1, statBonusGrants: { iq: 'statPenalty' } },
  { label: 'The Marginally Threatening',    weight: 1, statBonusGrants: { fightingSkill: 'statBonus' } },
  { label: 'The Reluctantly Heroic',        weight: 1, statBonusGrants: { durability: 'statBonus', charisma: 'statPenalty' } },
  { label: 'The Oddly Specific',            weight: 1, statBonusGrants: { iq: 'statBonus' } },
  { label: 'The Unknowingly Impressive',    weight: 1, statBonusGrants: { strength: 'statBonus', iq: 'statPenalty' } },
  { label: 'Accidentally Victorious',       weight: 1, statBonusGrants: { strength: 'statBonus', agility: 'statPenalty' } },
  { label: 'The Technically Correct',       weight: 1, statBonusGrants: { iq: 'statBonus', charisma: 'statPenalty' } },
  { label: 'He Who Explained It at Length', weight: 1, statBonusGrants: { iq: 'statBonus', charisma: 'statPenalty' } },
  { label: 'The Unexpectedly Present',      weight: 1, statBonusGrants: { speed: 'statBonus' } },
  { label: 'Scourge of Reasonable Plans',   weight: 1, statBonusGrants: { iq: 'statPenalty', strength: 'statBonus' } },
  { label: 'The Persistently Underwhelming', weight: 1, statBonusGrants: { potential: 'statPenalty' } },
  { label: 'He Tried',                      weight: 1, statBonusGrants: { potential: 'statBonus', fightingSkill: 'statPenalty' } },
  { label: 'The Sincerely Mistaken',        weight: 1, statBonusGrants: { iq: 'statPenalty' } },
  { label: 'Notorious for Being Fine',      weight: 1, statBonusGrants: { durability: 'statBonus' } },
  { label: 'The Occasionally Menacing',     weight: 1, statBonusGrants: { charisma: 'statBonus', fightingSkill: 'statPenalty' } },
  { label: 'Of Mild Concern',               weight: 1, statBonusGrants: { iq: 'statBonus', charisma: 'statPenalty' } },
  { label: 'The Somewhat Ominous',          weight: 1, statBonusGrants: { charisma: 'statBonus' } },
  { label: 'The Generally Tolerated',       weight: 1, statBonusGrants: { charisma: 'statPenalty' } },
  { label: 'Not Entirely Without Merit',    weight: 1, statBonusGrants: { potential: 'statBonus' } },
  { label: 'The Adequately Named',          weight: 1, statBonusGrants: { charisma: 'statPenalty', iq: 'statPenalty' } },
  { label: 'Survivor of Their Own Decisions', weight: 1, statBonusGrants: { durability: 'statBonus', iq: 'statPenalty' } },
  { label: 'The Uncannily Specific',        weight: 1, statBonusGrants: { iq: 'statBonus' } },
  { label: 'The Almost',                    weight: 1, statBonusGrants: { potential: 'statPenalty' } },
  { label: 'The Nevertheless',              weight: 1, statBonusGrants: { durability: 'statBonus' } },
  { label: 'The However',                   weight: 1, statBonusGrants: { charisma: 'statPenalty' } },
  { label: 'The Reportedly',                weight: 1, statBonusGrants: { charisma: 'statBonus' } },
  { label: 'The Allegedly Powerful',        weight: 1, statBonusGrants: { potential: 'statBonus' } },
  { label: 'Sources Say Dangerous',         weight: 1, statBonusGrants: { charisma: 'statBonus', fightingSkill: 'statBonus' } },
  { label: 'Unverified Legend',             weight: 1, statBonusGrants: { charisma: 'statBonus', potential: 'statBonus' } },
  { label: 'The Person In Question',        weight: 1, statBonusGrants: { iq: 'statPenalty' } },
  { label: 'That One',                      weight: 1, statBonusGrants: { charisma: 'statPenalty' } },
  { label: 'Him, Apparently',               weight: 1, statBonusGrants: { charisma: 'statPenalty', potential: 'statBonus' } },
  { label: 'Them (You Know the One)',        weight: 1, statBonusGrants: { charisma: 'statPenalty', strength: 'statBonus' } },
]
