// titles.ts — Title content pool for Wheel of Fate.
// 52+ SimpleItem entries spanning epic to absurd. No default export. No functions.

import type { SimpleItem } from './types'

export const titles: SimpleItem[] = [
  // ── Epic Titles ──
  { label: 'The Undying', weight: 1 },
  { label: 'Harbinger of Storms', weight: 1 },
  { label: 'God-Slayer', weight: 1 },
  { label: 'The Eternal', weight: 1 },
  { label: 'Void-Touched', weight: 1 },
  { label: 'Scourge of Nations', weight: 1 },
  { label: 'The Unyielding', weight: 1 },
  { label: 'Lord of Ash', weight: 1 },
  { label: 'The Forsaken', weight: 1 },
  { label: 'World-Ender', weight: 1 },
  { label: 'The Immovable', weight: 1 },
  { label: 'Bane of Heaven', weight: 1 },
  { label: 'The Inevitable', weight: 1 },
  { label: 'Last of Their Kind', weight: 1 },
  { label: 'The Relentless', weight: 1 },
  { label: 'Breaker of Seals', weight: 1 },
  { label: 'The Unkillable', weight: 1 },
  { label: 'Destroyer of Truths', weight: 1 },
  { label: 'The Boundless', weight: 1 },
  { label: 'Sovereign of Ruin', weight: 1 },
  { label: 'The Desolate', weight: 1 },
  { label: 'Wrath Incarnate', weight: 1 },
  { label: 'The Unbound', weight: 1 },
  { label: 'Eclipse of Ages', weight: 1 },
  { label: 'The Inexorable', weight: 1 },
  { label: 'Devourer of Worlds', weight: 1 },
  { label: 'The Inescapable', weight: 1 },
  { label: 'Reaper of Fates', weight: 1 },
  { label: 'The Transcendent', weight: 1 },
  { label: 'Apex Predator', weight: 1 },
  { label: 'Herald of Endings', weight: 1 },
  { label: 'The Primordial', weight: 1 },
  { label: 'Terror of the Void', weight: 1 },
  { label: 'The Unconquered', weight: 1 },
  { label: 'Sovereign of Shadows', weight: 1 },
  { label: 'The Undeniable', weight: 1 },
  { label: 'Flame of Apocalypse', weight: 1 },
  { label: 'The Implacable', weight: 1 },
  { label: 'Scion of Oblivion', weight: 1 },
  { label: 'The Remorseless', weight: 1 },
  { label: 'Champion of Nothingness', weight: 1 },
  { label: 'The Unstoppable', weight: 1 },
  { label: 'Harbinger of Silence', weight: 1 },
  { label: 'The Absolute', weight: 1 },
  { label: 'Vessel of the End', weight: 1 },
  { label: 'The Unbroken', weight: 1 },
  { label: 'Shadow of Eternity', weight: 1 },
  { label: 'The Undefeated', weight: 1 },
  { label: 'Apex of Fear', weight: 1 },
  { label: 'The Interminable', weight: 1 },
  { label: 'Calamity Made Flesh', weight: 1 },
  { label: 'The Undoubted', weight: 1 },

  // ── Absurd Titles ──
  { label: 'The Perpetually Confused', weight: 1 },
  { label: 'He Who Trips on Flat Surfaces', weight: 1 },
  { label: 'Smell of Old Books', weight: 1 },
  { label: 'The Unreasonably Tall', weight: 1 },
  { label: 'Professional Disappointment', weight: 1 },
  { label: 'The Mildly Ominous', weight: 1 },
  { label: 'Mostly Harmless', weight: 1 },
  { label: 'The Suspiciously Cheerful', weight: 1 },
  { label: 'He Who Cannot Park Correctly', weight: 1 },
  { label: 'The Aggressively Normal', weight: 1 },
  { label: 'Bane of Staplers', weight: 1 },
  { label: 'The Chronically Late', weight: 1 },
  { label: 'Expert of Unsolicited Opinions', weight: 1 },
  { label: 'The Involuntary Hiccupper', weight: 1 },
  { label: 'The Unnecessarily Verbose', weight: 1 },
  { label: 'He Who Misses Obvious Hints', weight: 1 },
  { label: 'The Perpetually Overdressed', weight: 1 },
  { label: 'Accidentally Famous', weight: 1 },
  { label: 'The Suspiciously Helpful', weight: 1 },
  { label: 'Fear Him Not, for He Is Fine', weight: 1 },
  { label: 'The Mildly Inconvenienced', weight: 1 },
  { label: 'Somewhat Legendary', weight: 1 },
  { label: 'The Regrettably Memorable', weight: 1 },
  { label: 'Feared by Few, Tolerated by Most', weight: 1 },
  { label: 'He Who Takes the Last Slice', weight: 1 },
  { label: 'The Boldly Mediocre', weight: 1 },
  { label: 'The Indecisive', weight: 1 },
  { label: 'The One Who Replies-All', weight: 1 },
  { label: 'Bane of Good Parking Spots', weight: 1 },
  { label: 'The Marginally Threatening', weight: 1 },
  { label: 'The Reluctantly Heroic', weight: 1 },
  { label: 'The Oddly Specific', weight: 1 },
  { label: 'The Unknowingly Impressive', weight: 1 },
  { label: 'Accidentally Victorious', weight: 1 },
  { label: 'The Technically Correct', weight: 1 },
  { label: 'He Who Explained It at Length', weight: 1 },
  { label: 'The Unexpectedly Present', weight: 1 },
  { label: 'Scourge of Reasonable Plans', weight: 1 },
  { label: 'The Persistently Underwhelming', weight: 1 },
  { label: 'He Tried', weight: 1 },
  { label: 'The Sincerely Mistaken', weight: 1 },
  { label: 'Notorious for Being Fine', weight: 1 },
  { label: 'The Occasionally Menacing', weight: 1 },
  { label: 'Of Mild Concern', weight: 1 },
  { label: 'The Somewhat Ominous', weight: 1 },
  { label: 'The Generally Tolerated', weight: 1 },
  { label: 'Not Entirely Without Merit', weight: 1 },
  { label: 'The Adequately Named', weight: 1 },
  { label: 'Survivor of Their Own Decisions', weight: 1 },
  { label: 'The Uncannily Specific', weight: 1 },
  { label: 'The Almost', weight: 1 },
  { label: 'The Nevertheless', weight: 1 },
  { label: 'The However', weight: 1 },
  { label: 'The Reportedly', weight: 1 },
  { label: 'The Allegedly Powerful', weight: 1 },
  { label: 'Sources Say Dangerous', weight: 1 },
  { label: 'Unverified Legend', weight: 1 },
  { label: 'The Person In Question', weight: 1 },
  { label: 'That One', weight: 1 },
  { label: 'Him, Apparently', weight: 1 },
  { label: 'Them (You Know the One)', weight: 1 },
]
