// weaknesses.ts — Weaknesses content pool for Wheel of Fate.
// ~450 Weakness entries with severe boolean flag.
// severe: true = classic/debilitating weaknesses drawn for high-modifier races.
// severe: false = absurd/comedic weaknesses.
// No default export. No functions. Static const array only.

import type { Weakness } from './types'

export const weaknesses: Weakness[] = [
  // ── Severe: true — Classic / Debilitating Weaknesses ──
  { label: 'Sunlight', weight: 1, severe: true },
  { label: 'Silver', weight: 1, severe: true },
  { label: 'Running Water', weight: 1, severe: true },
  { label: 'Holy Ground', weight: 1, severe: true },
  { label: 'Garlic', weight: 1, severe: true },
  { label: 'Iron (Cold)', weight: 1, severe: true },
  { label: 'Salt Circle', weight: 1, severe: true },
  { label: 'Decapitation', weight: 1, severe: true },
  { label: 'Fire', weight: 1, severe: true },
  { label: 'Bright Light', weight: 1, severe: true },
  { label: 'Sound Above 120dB', weight: 1, severe: true },
  { label: 'Holy Water', weight: 1, severe: true },
  { label: 'Blessed Weapons', weight: 1, severe: true },
  { label: 'True Name Knowledge', weight: 1, severe: true },
  { label: 'Iron Restraints', weight: 1, severe: true },
  { label: 'Salt (Consecrated)', weight: 1, severe: true },
  { label: 'Rowan Wood', weight: 1, severe: true },
  { label: 'Hawthorn', weight: 1, severe: true },
  { label: 'Wolfsbane', weight: 1, severe: true },
  { label: 'Mistletoe', weight: 1, severe: true },
  { label: 'Ash Wood', weight: 1, severe: true },
  { label: 'Oak Binding', weight: 1, severe: true },
  { label: "Running Water (Can't Cross)", weight: 1, severe: true },
  { label: 'Threshold Invitation Required', weight: 1, severe: true },
  { label: 'Mirror Sight (Reveals True Form)', weight: 1, severe: true },
  { label: 'Bell Toll', weight: 1, severe: true },
  { label: 'Churchyard Soil', weight: 1, severe: true },
  { label: 'Exorcism Rite', weight: 1, severe: true },
  { label: 'Binding Sigil', weight: 1, severe: true },
  { label: 'Pentacle Trap', weight: 1, severe: true },
  { label: "Dragon's Bane", weight: 1, severe: true },
  { label: 'Void Nullifier', weight: 1, severe: true },
  { label: 'Anti-Magic Field', weight: 1, severe: true },
  { label: 'Power Suppressant', weight: 1, severe: true },
  { label: 'Null Zone', weight: 1, severe: true },
  { label: 'Dispel Magic', weight: 1, severe: true },
  { label: 'Counter-Spell', weight: 1, severe: true },
  { label: 'Negation Field', weight: 1, severe: true },
  { label: 'Elemental Opposition', weight: 1, severe: true },
  { label: 'Absolute Zero', weight: 1, severe: true },
  { label: 'Extreme Heat', weight: 1, severe: true },
  { label: 'Crushing Pressure', weight: 1, severe: true },
  { label: 'Radiation', weight: 1, severe: true },
  { label: 'Sonic Disruption', weight: 1, severe: true },
  { label: 'Magnetic Reversal', weight: 1, severe: true },
  { label: 'Gravity Well', weight: 1, severe: true },
  { label: 'Temporal Stasis', weight: 1, severe: true },
  { label: 'Soul Seal', weight: 1, severe: true },
  { label: 'Life Force Drain', weight: 1, severe: true },
  { label: 'True Death Ritual', weight: 1, severe: true },

  // ── Severe: false — Absurd / Comedic Weaknesses ──

  // — Sensory / Annoyance —
  { label: 'Testicular Torsion', weight: 1, severe: false },
  { label: 'Vague Social Anxiety', weight: 1, severe: false },
  { label: 'The Smell of Burnt Toast', weight: 1, severe: false },
  { label: 'Exposure to the Word "Moist"', weight: 1, severe: false },
  { label: 'Being Called by Their Full Name', weight: 1, severe: false },
  { label: 'Mild Inconvenience', weight: 1, severe: false },
  { label: 'The Sound of Styrofoam Rubbing Together', weight: 1, severe: false },
  { label: 'Comic Sans', weight: 1, severe: false },
  { label: 'Someone Eating Loudly Nearby', weight: 1, severe: false },
  { label: 'Elevator Music', weight: 1, severe: false },
  { label: 'Mondays', weight: 1, severe: false },
  { label: 'The Smell of Fresh Bread (Cannot Resist)', weight: 1, severe: false },
  { label: 'FOMO', weight: 1, severe: false },
  { label: 'Mild Compliments', weight: 1, severe: false },
  { label: 'Someone Humming Incorrectly', weight: 1, severe: false },
  { label: 'A Slightly Too-Long Hug', weight: 1, severe: false },
  { label: 'The Word "Ointment"', weight: 1, severe: false },
  { label: 'The Macarena (Any Context)', weight: 1, severe: false },
  { label: 'Losing at Trivia', weight: 1, severe: false },
  { label: 'Someone Chewing Ice', weight: 1, severe: false },
  { label: 'Unexpected Touching of the Shoulder', weight: 1, severe: false },
  { label: 'The Sound of a Fork Scraping a Plate', weight: 1, severe: false },
  { label: 'A Slightly Damp Handshake', weight: 1, severe: false },
  { label: 'Overenthusiastic Eye Contact', weight: 1, severe: false },
  { label: 'Pen Clicking', weight: 1, severe: false },
  { label: 'Knuckle Cracking', weight: 1, severe: false },
  { label: 'Loud Chewing', weight: 1, severe: false },
  { label: 'Slurping', weight: 1, severe: false },
  { label: 'Whistling Off-Key', weight: 1, severe: false },
  { label: 'Humming Under Their Breath', weight: 1, severe: false },
  { label: 'Foot Tapping', weight: 1, severe: false },
  { label: 'Finger Drumming', weight: 1, severe: false },
  { label: 'Sniffing Repeatedly', weight: 1, severe: false },
  { label: 'Loud Keyboard Typing', weight: 1, severe: false },
  { label: 'Speaker Phone in Public', weight: 1, severe: false },
  { label: 'The Sound of Their Own Name Said Disappointedly', weight: 1, severe: false },
  { label: 'A Passive-Aggressive Sigh', weight: 1, severe: false },
  { label: 'The Word "Interesting" Said Without Conviction', weight: 1, severe: false },
  { label: 'Nails on a Chalkboard', weight: 1, severe: false },
  { label: 'The Phrase "It Is What It Is"', weight: 1, severe: false },
  { label: '"Per My Last Email"', weight: 1, severe: false },

  // — Combat / Power Absurdities —
  { label: 'Cannot Fight While Being Watched', weight: 1, severe: false },
  { label: 'Loses Focus When Tripped', weight: 1, severe: false },
  { label: 'Allergic to Winning', weight: 1, severe: false },
  { label: 'Falls When Complimented Mid-Battle', weight: 1, severe: false },
  { label: 'Defeated by Their Own Dramatic Pause', weight: 1, severe: false },
  { label: 'Powers Only Work When No One Is Watching', weight: 1, severe: false },
  { label: 'Abilities Require Exactly 8 Hours of Prior Sleep', weight: 1, severe: false },
  { label: 'Cannot Use Abilities on an Empty Stomach', weight: 1, severe: false },
  { label: 'Powers Malfunction When Running Late', weight: 1, severe: false },
  { label: 'Loses Stats When Embarrassed', weight: 1, severe: false },
  { label: 'Cannot Concentrate During Sustained Eye Contact', weight: 1, severe: false },
  { label: 'Intimidated by Capes (When Worn by Others)', weight: 1, severe: false },
  { label: 'Cannot Hit Someone Shorter Than Them', weight: 1, severe: false },
  { label: 'Abilities Glitch Near Strong Wi-Fi', weight: 1, severe: false },
  { label: 'Powers Only Function on Weekdays', weight: 1, severe: false },
  { label: 'Cannot Win Fairly', weight: 1, severe: false },
  { label: 'Cannot Resist a Good Comeback Even at the Wrong Moment', weight: 1, severe: false },
  { label: 'Guaranteed to Monologue at the Worst Moment', weight: 1, severe: false },
  { label: 'Their Evil Twin Is Slightly Stronger', weight: 1, severe: false },
  { label: 'Defeated by Being Reasoned With', weight: 1, severe: false },
  { label: 'Cannot Stay Mad at a Redemption Arc', weight: 1, severe: false },
  { label: 'Backstory Gets in the Way at Critical Moments', weight: 1, severe: false },
  { label: 'Cannot Ignore a Side Quest', weight: 1, severe: false },
  { label: 'Arrives Last to Every Battle', weight: 1, severe: false },
  { label: 'Always Hits Something Behind Their Target', weight: 1, severe: false },
  { label: 'The Villain Has a Point', weight: 1, severe: false },
  { label: 'Their Own Theme Music Inspires the Enemy', weight: 1, severe: false },
  { label: "Can't Help Helping, Even Enemies", weight: 1, severe: false },
  { label: "Too Sympathetic to the Enemy's Motive", weight: 1, severe: false },
  { label: 'Defeated by Their Own Flashback', weight: 1, severe: false },
  { label: 'Extremely Pettable Head', weight: 1, severe: false },

  // — Animal Vulnerabilities —
  { label: 'Geese (All Geese)', weight: 1, severe: false },
  { label: 'Defeated by a Confident Duck', weight: 1, severe: false },
  { label: 'Cannot Harm Anything Cute', weight: 1, severe: false },
  { label: 'Distracted by Any Dog, Immediately', weight: 1, severe: false },
  { label: 'Birds That Are Looking Directly at Them', weight: 1, severe: false },
  { label: 'Cannot Focus if a Cat Enters the Room', weight: 1, severe: false },
  { label: 'A Pigeon with an Attitude', weight: 1, severe: false },
  { label: 'Swans (Specifically)', weight: 1, severe: false },
  { label: 'Haunted by a Specific Crow', weight: 1, severe: false },
  { label: 'Loses the Will to Fight if a Bunny Appears', weight: 1, severe: false },
  { label: 'Any Baby Animal, Anywhere', weight: 1, severe: false },
  { label: 'Horses That Know Too Much', weight: 1, severe: false },

  // — Time / Energy —
  { label: 'Completely Useless Before Coffee', weight: 1, severe: false },
  { label: 'Loses Half Their Power After 10pm', weight: 1, severe: false },
  { label: 'Powers Lag by Exactly 15 Minutes', weight: 1, severe: false },
  { label: 'Only Vulnerable on Wednesdays', weight: 1, severe: false },
  { label: 'Cannot Function Before Noon', weight: 1, severe: false },
  { label: 'The Afternoon Slump (Debilitating)', weight: 1, severe: false },
  { label: 'Morning People', weight: 1, severe: false },
  { label: 'The Sunday Evening Feeling', weight: 1, severe: false },
  { label: 'Full Moon (But the Wrong Effect)', weight: 1, severe: false },
  { label: 'Overly Enthusiastic Mornings', weight: 1, severe: false },

  // — Physical Comedy —
  { label: 'Trips on Flat Surfaces Exclusively', weight: 1, severe: false },
  { label: 'Doors (All Kinds, All Directions)', weight: 1, severe: false },
  { label: 'Stairs (Specifically Going Down)', weight: 1, severe: false },
  { label: 'Cannot Run in a Straight Line When Nervous', weight: 1, severe: false },
  { label: 'Stubbed Toe Ends the Fight', weight: 1, severe: false },
  { label: 'Cannot Function With Wet Socks', weight: 1, severe: false },
  { label: 'Loses 40% of Power Without a Good Coat', weight: 1, severe: false },
  { label: 'Absolutely Destroyed by a Sudden Loud Noise', weight: 1, severe: false },
  { label: 'Sneezes at the Worst Possible Moment', weight: 1, severe: false },
  { label: 'Hiccups During Dramatic Monologues', weight: 1, severe: false },
  { label: 'Cannot Fight in Formal Attire', weight: 1, severe: false },
  { label: 'Loses Balance When Looked at Directly', weight: 1, severe: false },
  { label: 'IKEA (Any Part of the Experience)', weight: 1, severe: false },

  // — Food / Hunger —
  { label: 'Cannot Fight Hungry', weight: 1, severe: false },
  { label: 'Completely Derailed by the Smell of Food', weight: 1, severe: false },
  { label: 'Free Samples Are a Kill Switch', weight: 1, severe: false },
  { label: 'Cannot Resist a Buffet, Any Buffet', weight: 1, severe: false },
  { label: 'Loses All Composure Near a Cheese Board', weight: 1, severe: false },
  { label: 'Defeated by a Well-Timed Snack Offer', weight: 1, severe: false },
  { label: 'Bribeable with Baked Goods', weight: 1, severe: false },
  { label: 'Loses the Will to Win if Offered Pizza', weight: 1, severe: false },
  { label: 'Bread Basket (Cannot Resist)', weight: 1, severe: false },
  { label: 'Ordering the Most Complicated Coffee', weight: 1, severe: false },
  { label: 'Coffee Snob Reaction to Instant Coffee', weight: 1, severe: false },
  { label: 'Tea Snobbery (Milk First Debate)', weight: 1, severe: false },
  { label: 'Toast Butter-Side Down', weight: 1, severe: false },
  { label: 'Regional Food Loyalty (Extreme)', weight: 1, severe: false },

  // — Social / Interpersonal —
  { label: 'Cannot Stay Angry at Someone Who Apologises First', weight: 1, severe: false },
  { label: 'Collapses Under Sincere Appreciation', weight: 1, severe: false },
  { label: 'Physically Cannot Leave a Conversation First', weight: 1, severe: false },
  { label: 'Loses Composure if Someone Cries Unexpectedly', weight: 1, severe: false },
  { label: 'Defeated by a Good Story', weight: 1, severe: false },
  { label: 'Cannot Ignore Someone Waving Too Enthusiastically', weight: 1, severe: false },
  { label: 'Power of Friendship (Enemy Version)', weight: 1, severe: false },
  { label: 'Cannot Refuse a Dare', weight: 1, severe: false },
  { label: 'Being Voluntold', weight: 1, severe: false },
  { label: 'Team Building Exercises', weight: 1, severe: false },
  { label: 'Ice Breaker Questions', weight: 1, severe: false },
  { label: 'Forced Fun', weight: 1, severe: false },
  { label: 'Mandatory Participation', weight: 1, severe: false },
  { label: 'Being Described as "Quirky"', weight: 1, severe: false },
  { label: 'Passive-Aggressive Sticky Notes', weight: 1, severe: false },
  { label: 'Unsolicited Life Advice', weight: 1, severe: false },
  { label: 'Being Accused of Not Listening', weight: 1, severe: false },
  { label: 'The Small Talk Death Spiral', weight: 1, severe: false },
  { label: 'Pre-Party Anxiety', weight: 1, severe: false },
  { label: 'Mid-Party Exhaustion', weight: 1, severe: false },
  { label: 'Post-Party Analysis at 3am', weight: 1, severe: false },
  { label: 'The Hangover of Social Overstimulation', weight: 1, severe: false },
  { label: '"Any Plans for the Weekend?" (Monday)', weight: 1, severe: false },
  { label: 'Being Called "Buddy" Aggressively', weight: 1, severe: false },
  { label: 'Being Called "Champ" Passive-Aggressively', weight: 1, severe: false },
  { label: 'High Five Left Hanging', weight: 1, severe: false },
  { label: 'Fist Bump Missed', weight: 1, severe: false },
  { label: 'Forgetting a Name Immediately After Introduction', weight: 1, severe: false },
  { label: 'Calling Someone by the Wrong Name Repeatedly', weight: 1, severe: false },
  { label: 'Deeply Uncomfortable When Someone Is Too Nice', weight: 1, severe: false },
  { label: '"It\'s Fine" When It Clearly Is Not', weight: 1, severe: false },
  { label: 'Being Told to "Just Relax"', weight: 1, severe: false },
  { label: '"Have You Tried Yoga?" (Unsolicited)', weight: 1, severe: false },
  { label: 'Cold Shower Evangelism', weight: 1, severe: false },
  { label: 'CrossFit Mentioned Within Three Minutes', weight: 1, severe: false },
  { label: 'Hustle Culture Manifestos', weight: 1, severe: false },
  { label: '"I Only Need 4 Hours of Sleep"', weight: 1, severe: false },
  { label: 'MLM Recruitment Attempts', weight: 1, severe: false },
  { label: 'Crypto Explanation Unsolicited', weight: 1, severe: false },
  { label: 'NFT Investment Pitch', weight: 1, severe: false },

  // — Supernatural Specifics —
  { label: 'Weakness to a Specific Cheese (Unknown Which)', weight: 1, severe: false },
  { label: 'Real Name Is Embarrassing If Spoken Aloud', weight: 1, severe: false },
  { label: 'Haunted by a Completely Unrelated Ghost', weight: 1, severe: false },
  { label: 'Their Villain Arc Keeps Starting', weight: 1, severe: false },
  { label: 'Secret Weakness Is Something Stupid', weight: 1, severe: false },
  { label: 'Immune to Fire but Not Lukewarm', weight: 1, severe: false },
  { label: 'Invulnerable Except to Their Own Weapon', weight: 1, severe: false },
  { label: 'The Yellow Sun Is the Wrong Color', weight: 1, severe: false },
  { label: 'Cannot Be Harmed at 3:33am (Only Then)', weight: 1, severe: false },
  { label: 'Kryptonite (Something Embarrassing)', weight: 1, severe: false },
  { label: 'Glitter (It Gets Everywhere)', weight: 1, severe: false },
  { label: 'Strongly Affected by Vibes', weight: 1, severe: false },
  { label: 'Their Own Wikipedia Page', weight: 1, severe: false },
  { label: 'Nostalgia (Sudden, Debilitating)', weight: 1, severe: false },
  { label: 'Kindness from Unexpected Sources', weight: 1, severe: false },
  { label: 'A Really Good View', weight: 1, severe: false },
  { label: 'The Smell of Petrichor (Cannot Fight Immediately After)', weight: 1, severe: false },

  // — Tech / Modern Life —
  { label: 'Being Left on Read', weight: 1, severe: false },
  { label: 'Three Dots That Disappear', weight: 1, severe: false },
  { label: 'Unexplained "K" Response', weight: 1, severe: false },
  { label: 'Autocorrect at Critical Moments', weight: 1, severe: false },
  { label: 'Accidentally Liking an Old Post', weight: 1, severe: false },
  { label: 'Buffering at a Critical Moment', weight: 1, severe: false },
  { label: 'Low Battery Warning During the Best Part', weight: 1, severe: false },
  { label: 'Phone Dying Without a Charger Nearby', weight: 1, severe: false },
  { label: 'Running Out of Storage', weight: 1, severe: false },
  { label: 'WiFi Dropping at a Crucial Moment', weight: 1, severe: false },
  { label: 'Forgetting They\'re Unmuted', weight: 1, severe: false },
  { label: 'Unknowingly Screen Sharing Personal Content', weight: 1, severe: false },
  { label: 'Cannot Resist Checking Their Phone Mid-Battle', weight: 1, severe: false },
  { label: 'Fatally Distracted by a Notification', weight: 1, severe: false },
  { label: 'Unsaved Work', weight: 1, severe: false },
  { label: 'The YouTube Ad at the Most Tense Moment', weight: 1, severe: false },
  { label: 'Loses Concentration if Someone Nearby Is on a Louder Call', weight: 1, severe: false },
  { label: 'Defeated if Their Playlist Ends', weight: 1, severe: false },
  { label: 'Ringtone Going Off in Silence', weight: 1, severe: false },
  { label: '"I\'ve Done My Research"', weight: 1, severe: false },
  { label: '"Just Asking Questions"', weight: 1, severe: false },
  { label: '"Do Your Own Research"', weight: 1, severe: false },
  { label: 'Someone on TikTok Explained It to Them', weight: 1, severe: false },
  { label: 'AI-Generated Content (Unedited)', weight: 1, severe: false },

  // — Work / Meetings —
  { label: 'A Meeting That Could Have Been an Email', weight: 1, severe: false },
  { label: 'Reply-All Email Chains', weight: 1, severe: false },
  { label: 'PowerPoint with Thirty Slides of Text', weight: 1, severe: false },
  { label: '"Quick Question" (Takes 45 Minutes)', weight: 1, severe: false },
  { label: '"Short Meeting, I Promise"', weight: 1, severe: false },
  { label: 'Unsolicited LinkedIn Requests', weight: 1, severe: false },
  { label: 'The Passive-Aggressive "Thanks"', weight: 1, severe: false },
  { label: '"Just Circling Back"', weight: 1, severe: false },
  { label: '"Move the Needle"', weight: 1, severe: false },
  { label: '"Thought Leader" Self-Description', weight: 1, severe: false },
  { label: 'End-of-Year Performance Review', weight: 1, severe: false },
  { label: '"Some Feedback Came Through About You"', weight: 1, severe: false },
  { label: '"People Have Been Noticing"', weight: 1, severe: false },
  { label: 'Surprise Performance Improvement Plan', weight: 1, severe: false },
  { label: '"Right-Sizing" Announcement', weight: 1, severe: false },
  { label: 'The Work Christmas Party', weight: 1, severe: false },
  { label: '"You Look Tired"', weight: 1, severe: false },
  { label: '"You Look Well" (Ambiguously)', weight: 1, severe: false },
  { label: '"That\'s Very Brave"', weight: 1, severe: false },
  { label: 'Faint Praise as Damnation', weight: 1, severe: false },
  { label: 'Ambiguous Compliment Requiring Interpretation', weight: 1, severe: false },
  { label: '"It\'s Almost There"', weight: 1, severe: false },
  { label: '"Actually, I Have a Few More Notes"', weight: 1, severe: false },
  { label: '"Just One Final Change"', weight: 1, severe: false },
  { label: 'Being Caught Just as They\'re Leaving', weight: 1, severe: false },
  { label: '"Before You Go—"', weight: 1, severe: false },
  { label: '"Five More Minutes" (Third Time)', weight: 1, severe: false },

  // — Media / Culture —
  { label: 'Spoilers (Before They\'ve Watched It)', weight: 1, severe: false },
  { label: 'Cliffhanger Season Finale (Show Was Cancelled)', weight: 1, severe: false },
  { label: 'Retcons', weight: 1, severe: false },
  { label: 'Unnecessary Sequels', weight: 1, severe: false },
  { label: 'Being Told a Show Gets Better in Season 4', weight: 1, severe: false },
  { label: 'Misattributed Quotes', weight: 1, severe: false },
  { label: 'Meme Used as Counterargument', weight: 1, severe: false },
  { label: 'Wikipedia Summary as Authority', weight: 1, severe: false },
  { label: 'Inability to Admit Being Wrong', weight: 1, severe: false },
  { label: 'The Moving Goalposts', weight: 1, severe: false },
  { label: 'Being Technically Right in a Useless Way', weight: 1, severe: false },
  { label: 'Good Point, Wrong Meeting', weight: 1, severe: false },
  { label: 'Reinventing Something That Exists', weight: 1, severe: false },
  { label: 'Great Idea, Already Done', weight: 1, severe: false },

  // — Lateness / Navigation —
  { label: 'Chronic Lateness Presented as Personality', weight: 1, severe: false },
  { label: '"I Know a Shortcut" (Longer Route)', weight: 1, severe: false },
  { label: '"The GPS Is Wrong"', weight: 1, severe: false },
  { label: '"I Don\'t Need Directions"', weight: 1, severe: false },
  { label: 'Arriving Ninety Minutes Late Confidently', weight: 1, severe: false },
  { label: 'Never Left Yet When Due to Arrive', weight: 1, severe: false },
  { label: '"We\'re Making Good Time" (Not Making Good Time)', weight: 1, severe: false },

  // — Eating Out —
  { label: 'The Double-Dipper', weight: 1, severe: false },
  { label: 'Splitting the Bill 14 Ways', weight: 1, severe: false },
  { label: 'Tipping Amount Disagreement', weight: 1, severe: false },
  { label: 'The Last Chip Etiquette Breach', weight: 1, severe: false },
  { label: 'Stealing Chips Brazenly', weight: 1, severe: false },
  { label: 'Eating Off Someone\'s Plate', weight: 1, severe: false },
  { label: '"Can I Taste Yours?"', weight: 1, severe: false },
  { label: 'The Group Order Where One Person Wants Substitutions', weight: 1, severe: false },
  { label: 'Sending Food Back (Unjustifiably)', weight: 1, severe: false },
  { label: 'Allergy Mentioned After Ordering', weight: 1, severe: false },
  { label: 'Service Charge Debate', weight: 1, severe: false },

  // — Misc Absurdist —
  { label: 'A Very Good Scented Candle', weight: 1, severe: false },
  { label: 'Competitive Vibes', weight: 1, severe: false },
  { label: 'Their Own Reflection\'s Judgement', weight: 1, severe: false },
  { label: 'Someone Else\'s Infectious Optimism', weight: 1, severe: false },
  { label: 'A Surprisingly Warm Handshake', weight: 1, severe: false },
  { label: 'Eye Contact Held One Second Too Long', weight: 1, severe: false },
  { label: 'Being Called "An Old Soul"', weight: 1, severe: false },
  { label: 'Someone Who Loves Mondays', weight: 1, severe: false },
  { label: 'People Who Are Fine Without Caffeine', weight: 1, severe: false },
  { label: 'Recounting Dreams in Detail', weight: 1, severe: false },
  { label: 'The Phrase "Live, Laugh, Love"', weight: 1, severe: false },
  { label: 'Motivational Poster in the Workplace', weight: 1, severe: false },
  { label: 'Inspirational Quote Over a Sunset', weight: 1, severe: false },
  { label: 'Hustle Culture Before 7am', weight: 1, severe: false },
  { label: 'Making Plans and Immediately Regretting It', weight: 1, severe: false },
  { label: '"We Should Catch Up Soon" (Never)', weight: 1, severe: false },
  { label: 'Friends Who Always Cancel', weight: 1, severe: false },
  { label: 'The Perpetual Rain Check', weight: 1, severe: false },
  { label: 'Someone Who Never Initiates Plans', weight: 1, severe: false },
  { label: '"How Was Your Weekend?" (Monday, Without Genuine Interest)', weight: 1, severe: false },
  { label: 'The Corridor Nod Misread as a Bow', weight: 1, severe: false },
  { label: 'The Elbow Bump (Still Happening)', weight: 1, severe: false },
  { label: 'Overly Firm Handshake', weight: 1, severe: false },
  { label: 'Limp Handshake', weight: 1, severe: false },

  // ── Severe: true — Additional Debilitating Weaknesses ──
  { label: 'Iron', weight: 1, severe: true },
  { label: 'Cold Iron', weight: 1, severe: true },
  { label: 'Blessed Weapons', weight: 1, severe: true },
  { label: 'Sea Salt', weight: 1, severe: true },
  { label: 'Rowan Wood', weight: 1, severe: true },
  { label: 'Hawthorn', weight: 1, severe: true },
  { label: 'Mistletoe', weight: 1, severe: true },
  { label: 'Obsidian', weight: 1, severe: true },
  { label: 'Moon Water', weight: 1, severe: true },
  { label: 'Dragon Glass', weight: 1, severe: true },
  { label: 'Rune-Carved Stone', weight: 1, severe: true },
  { label: 'Divine Light', weight: 1, severe: true },
  { label: 'Banishment Ritual', weight: 1, severe: true },
  { label: 'True Name', weight: 1, severe: true },
  { label: 'Binding Circle', weight: 1, severe: true },
  { label: 'Saltwater', weight: 1, severe: true },
  { label: 'Purifying Flame', weight: 1, severe: true },
  { label: 'Essence Drain', weight: 1, severe: true },
  { label: 'Void Exposure', weight: 1, severe: true },
  { label: 'Anti-Magic Field', weight: 1, severe: true },
  { label: 'Null Zone', weight: 1, severe: true },
  { label: 'Mirror Reflection', weight: 1, severe: true },
  { label: 'Paradox Construct', weight: 1, severe: true },
  { label: 'Sound Above 20kHz', weight: 1, severe: true },
  { label: 'Concentrated Sunlight', weight: 1, severe: true },
  { label: 'Sacred Geometry', weight: 1, severe: true },
  { label: 'Soul Anchor Destruction', weight: 1, severe: true },

  // ── Severe: false — Additional Absurd / Comedic Weaknesses ──
  { label: 'Someone Saying Your Full Name', weight: 1, severe: false },
  { label: 'Being Ignored', weight: 1, severe: false },
  { label: 'Dad Jokes', weight: 1, severe: false },
  { label: 'Slow WiFi', weight: 1, severe: false },
  { label: 'Loud Chewing', weight: 1, severe: false },
  { label: 'Spoilers', weight: 1, severe: false },
  { label: 'Telemarketer Calls', weight: 1, severe: false },
  { label: 'Elevator Music', weight: 1, severe: false },
  { label: 'The Color Beige', weight: 1, severe: false },
  { label: 'Motivational Posters', weight: 1, severe: false },
  { label: 'Comic Sans', weight: 1, severe: false },
  { label: 'Excessive Emojis', weight: 1, severe: false },
  { label: 'Being Put on Hold', weight: 1, severe: false },
  { label: 'Printer Errors', weight: 1, severe: false },
  { label: 'Microsoft Teams Notifications', weight: 1, severe: false },
  { label: 'Unsolicited Opinions', weight: 1, severe: false },
  { label: 'The Number 13', weight: 1, severe: false },
  { label: 'Mirror Selfies', weight: 1, severe: false },
  { label: 'Inspirational LinkedIn Posts', weight: 1, severe: false },
  { label: 'People Who Walk Slowly in Groups', weight: 1, severe: false },
  { label: 'FOMO', weight: 1, severe: false },
  { label: 'Cliffhanger Endings', weight: 1, severe: false },
  { label: 'Autocorrect', weight: 1, severe: false },
  { label: 'The "Reply All" Email', weight: 1, severe: false },
  { label: 'Being Called "Buddy"', weight: 1, severe: false },
  { label: 'Unskippable Ads', weight: 1, severe: false },
  { label: 'Being Talked Down To', weight: 1, severe: false },
  { label: 'Slow Walkers on Escalators', weight: 1, severe: false },
  { label: 'Wrong Coffee Order', weight: 1, severe: false },
  { label: 'Ice Bucket Challenges', weight: 1, severe: false },
  { label: 'Chain Letters', weight: 1, severe: false },
  { label: 'Mandatory Fun at Work', weight: 1, severe: false },
  { label: 'The "Just Checking In" Email', weight: 1, severe: false },
  { label: 'Phone Calls Instead of Texts', weight: 1, severe: false },
  { label: 'Being Photographed Unexpectedly', weight: 1, severe: false },
  { label: 'Open-Plan Office Noise', weight: 1, severe: false },
  { label: 'The Group Project (Unfair Workload)', weight: 1, severe: false },
  { label: 'Unasked-For Advice', weight: 1, severe: false },
  { label: 'The Uptalker', weight: 1, severe: false },
  { label: 'Lukewarm Tea', weight: 1, severe: false },
  { label: 'The Final 2% Battery Warning', weight: 1, severe: false },
  { label: 'Someone Standing Too Close in Queue', weight: 1, severe: false },
  { label: 'The Wet Handshake', weight: 1, severe: false },
  { label: 'Being Sent Voice Messages Instead of Texts', weight: 1, severe: false },
  { label: 'Clickbait', weight: 1, severe: false },
  { label: 'Unnecessary Spoiler Tags (Wrong)', weight: 1, severe: false },
  { label: 'Being Called Intense', weight: 1, severe: false },
  { label: 'Unsolicited Dietary Advice', weight: 1, severe: false },
  { label: '"You Look Tired"', weight: 1, severe: false },
  { label: 'People Who Film Concerts', weight: 1, severe: false },
  { label: 'Teeth-on-Cutlery Scraping', weight: 1, severe: false },
  { label: 'Being Told to Smile More', weight: 1, severe: false },
  { label: 'Neck Cracking in Quiet Rooms', weight: 1, severe: false },
  { label: 'Someone Narrating What They\'re Typing', weight: 1, severe: false },
  { label: 'The Wrong Toilet Paper Direction', weight: 1, severe: false },
  { label: 'People Who Overuse "Literally"', weight: 1, severe: false },
  { label: 'Being Quoted Incorrectly', weight: 1, severe: false },
  { label: 'The Passive-Aggressive Ellipsis...', weight: 1, severe: false },
  { label: 'Grammar Policing', weight: 1, severe: false },
  { label: 'Blue Tick Without Reply', weight: 1, severe: false },
  { label: 'Being Put on Speakerphone Unannounced', weight: 1, severe: false },
  { label: 'Notifications During Movies', weight: 1, severe: false },
  { label: 'People Who Don\'t Return Carts', weight: 1, severe: false },
  { label: 'The 11pm "Quick Question"', weight: 1, severe: false },
  { label: 'Fake Deadlines', weight: 1, severe: false },
  { label: 'Unclear Instructions', weight: 1, severe: false },
  { label: 'Microwave Smells From Colleagues', weight: 1, severe: false },
  { label: 'Someone Finishing Your Sentences', weight: 1, severe: false },
  { label: 'The Constant Topic-Changer', weight: 1, severe: false },
  { label: 'Being Told You\'re Sensitive', weight: 1, severe: false },
  { label: 'The Doorbell Mid-Nap', weight: 1, severe: false },
  { label: 'People Who Don\'t Use Turn Signals', weight: 1, severe: false },
  { label: 'Air Guitar in Public', weight: 1, severe: false },
  { label: 'The Unnecessary Meeting Invitation', weight: 1, severe: false },
  { label: 'Unsolicited Neck Massages', weight: 1, severe: false },
  { label: 'Being Nicknamed Without Consent', weight: 1, severe: false },
  { label: 'The Condescending "Good Job!"', weight: 1, severe: false },
  { label: 'Surprise Party Spoilers', weight: 1, severe: false },
  { label: 'People Who Text While Walking Into You', weight: 1, severe: false },
  { label: 'Passive Whistling', weight: 1, severe: false },
  { label: 'The Endless Goodbye', weight: 1, severe: false },
  { label: 'Eye-Rolling in Meetings', weight: 1, severe: false },
  { label: 'The Overly Loud Yawn', weight: 1, severe: false },
  { label: 'Running Monologue During Films', weight: 1, severe: false },
  { label: 'The Alarm for a Meeting Already Started', weight: 1, severe: false },
  { label: 'Being Told "It Is What It Is"', weight: 1, severe: false },
  { label: 'The Person Who Replies to Every Message Separately', weight: 1, severe: false },
  { label: 'Glitter That Gets Everywhere', weight: 1, severe: false },
]
