// weaknesses.ts — Weaknesses content pool for Wheel of Fate.
// 500+ Weakness entries with severe boolean flag.
// severe: true = classic/debilitating weaknesses drawn for high-modifier races.
// severe: false = absurd/comedic weaknesses.
// No default export. No functions. Static const array only.

import type { Weakness } from './types'

export const weaknesses: Weakness[] = [
  // ── Severe: true — Classic / Debilitating Weaknesses ──
  { label: 'Sunlight', weight: 1, severe: true },
  { label: 'Silver', weight: 1, severe: true },
  { label: 'Running Water', weight: 1, severe: true },
  { label: 'Holy Ground', weight: 1, severe: true },
  { label: 'Garlic', weight: 1, severe: true },
  { label: 'Iron (Cold)', weight: 1, severe: true },
  { label: 'Salt Circle', weight: 1, severe: true },
  { label: 'Decapitation', weight: 1, severe: true },
  { label: 'Fire', weight: 1, severe: true },
  { label: 'Bright Light', weight: 1, severe: true },
  { label: 'Sound above 120dB', weight: 1, severe: true },
  { label: 'Holy Water', weight: 1, severe: true },
  { label: 'Blessed Weapons', weight: 1, severe: true },
  { label: 'True Name Knowledge', weight: 1, severe: true },
  { label: 'Iron Restraints', weight: 1, severe: true },
  { label: 'Salt (Consecrated)', weight: 1, severe: true },
  { label: 'Rowan Wood', weight: 1, severe: true },
  { label: 'Hawthorn', weight: 1, severe: true },
  { label: 'Wolfsbane', weight: 1, severe: true },
  { label: 'Mistletoe', weight: 1, severe: true },
  { label: 'Ash Wood', weight: 1, severe: true },
  { label: 'Oak Binding', weight: 1, severe: true },
  { label: 'Running Water (Can\'t Cross)', weight: 1, severe: true },
  { label: 'Threshold Invitation Required', weight: 1, severe: true },
  { label: 'Mirror Sight (Reveals True Form)', weight: 1, severe: true },
  { label: 'Bell Toll', weight: 1, severe: true },
  { label: 'Churchyard Soil', weight: 1, severe: true },
  { label: 'Exorcism Rite', weight: 1, severe: true },
  { label: 'Binding Sigil', weight: 1, severe: true },
  { label: 'Pentacle Trap', weight: 1, severe: true },
  { label: 'Dragon\'s Bane', weight: 1, severe: true },
  { label: 'Void Nullifier', weight: 1, severe: true },
  { label: 'Anti-Magic Field', weight: 1, severe: true },
  { label: 'Power Suppressant', weight: 1, severe: true },
  { label: 'Null Zone', weight: 1, severe: true },
  { label: 'Dispel Magic', weight: 1, severe: true },
  { label: 'Counter-Spell', weight: 1, severe: true },
  { label: 'Negation Field', weight: 1, severe: true },
  { label: 'Elemental Opposition', weight: 1, severe: true },
  { label: 'Absolute Zero', weight: 1, severe: true },
  { label: 'Extreme Heat', weight: 1, severe: true },
  { label: 'Crushing Pressure', weight: 1, severe: true },
  { label: 'Radiation', weight: 1, severe: true },
  { label: 'Sonic Disruption', weight: 1, severe: true },
  { label: 'Magnetic Reversal', weight: 1, severe: true },
  { label: 'Gravity Well', weight: 1, severe: true },
  { label: 'Temporal Stasis', weight: 1, severe: true },
  { label: 'Soul Seal', weight: 1, severe: true },
  { label: 'Life Force Drain', weight: 1, severe: true },
  { label: 'True Death Ritual', weight: 1, severe: true },

  // ── Severe: false — Absurd / Comedic Weaknesses ──
  { label: 'Testicular Torsion', weight: 1, severe: false },
  { label: 'Vague Social Anxiety', weight: 1, severe: false },
  { label: 'The Smell of Burnt Toast', weight: 1, severe: false },
  { label: 'Exposure to the Word "Moist"', weight: 1, severe: false },
  { label: 'Being Called by Their Full Name', weight: 1, severe: false },
  { label: 'Mild Inconvenience', weight: 1, severe: false },
  { label: 'The Sound of Styrofoam Rubbing Together', weight: 1, severe: false },
  { label: 'Comic Sans Font', weight: 1, severe: false },
  { label: 'Someone Eating Loudly Nearby', weight: 1, severe: false },
  { label: 'Elevator Music', weight: 1, severe: false },
  { label: 'Unsolicited LinkedIn Requests', weight: 1, severe: false },
  { label: 'The Phrase "Per My Last Email"', weight: 1, severe: false },
  { label: 'Being Voluntold for Things', weight: 1, severe: false },
  { label: 'Reply-All Email Chains', weight: 1, severe: false },
  { label: 'Passive-Aggressive Sticky Notes', weight: 1, severe: false },
  { label: 'Mondays', weight: 1, severe: false },
  { label: 'The Smell of Fresh Bread (Cannot Resist)', weight: 1, severe: false },
  { label: 'Freshly Brewed Coffee Aroma', weight: 1, severe: false },
  { label: 'The Sound of Bubble Wrap', weight: 1, severe: false },
  { label: 'Inability to Leave a Party First', weight: 1, severe: false },
  { label: 'FOMO', weight: 1, severe: false },
  { label: 'Mild Compliments', weight: 1, severe: false },
  { label: 'Someone Humming Incorrectly', weight: 1, severe: false },
  { label: 'A Slightly Too-Long Hug', weight: 1, severe: false },
  { label: 'Mismatched Socks (Perceived)', weight: 1, severe: false },
  { label: 'The Word "Ointment"', weight: 1, severe: false },
  { label: 'Macarena Playing in Any Context', weight: 1, severe: false },
  { label: 'Being Accused of Not Listening', weight: 1, severe: false },
  { label: 'Losing at Trivia', weight: 1, severe: false },
  { label: 'The Phrase "It Is What It Is"', weight: 1, severe: false },
  { label: 'Someone Chewing Ice', weight: 1, severe: false },
  { label: 'Unexpected Touching of the Shoulder', weight: 1, severe: false },
  { label: 'The Sound of a Fork Scraping a Plate', weight: 1, severe: false },
  { label: 'Nails on a Chalkboard (Metaphorical)', weight: 1, severe: false },
  { label: 'A Slightly Damp Handshake', weight: 1, severe: false },
  { label: 'Overenthusiastic Eye Contact', weight: 1, severe: false },
  { label: 'The Presence of Someone Who Stands Just Too Close', weight: 1, severe: false },
  { label: 'Breathing Through Mouth (Others)', weight: 1, severe: false },
  { label: 'Pen Clicking', weight: 1, severe: false },
  { label: 'Knuckle Cracking', weight: 1, severe: false },
  { label: 'Loud Chewing', weight: 1, severe: false },
  { label: 'Slurping', weight: 1, severe: false },
  { label: 'Whistling Off-Key', weight: 1, severe: false },
  { label: 'Humming Under Breath', weight: 1, severe: false },
  { label: 'Foot Tapping', weight: 1, severe: false },
  { label: 'Finger Drumming', weight: 1, severe: false },
  { label: 'Sniffing Repeatedly', weight: 1, severe: false },
  { label: 'Desk Shaking from Leg', weight: 1, severe: false },
  { label: 'Loud Keyboard Typing', weight: 1, severe: false },
  { label: 'Speaker Phone in Public', weight: 1, severe: false },
  { label: 'Video Without Headphones on Train', weight: 1, severe: false },
  { label: 'Loud Phone Calls on Public Transport', weight: 1, severe: false },
  { label: 'Recounting Dreams in Detail', weight: 1, severe: false },
  { label: 'Being Asked "Have You Tried Yoga?"', weight: 1, severe: false },
  { label: 'Unsolicited Life Advice', weight: 1, severe: false },
  { label: 'Nutritional Lectures from Non-Doctors', weight: 1, severe: false },
  { label: 'The Phrase "Live, Laugh, Love"', weight: 1, severe: false },
  { label: 'Motivational Poster in Workplace', weight: 1, severe: false },
  { label: 'Team Building Exercises', weight: 1, severe: false },
  { label: 'Ice Breaker Questions', weight: 1, severe: false },
  { label: 'Being Made to Clap in Unison', weight: 1, severe: false },
  { label: 'Forced Fun', weight: 1, severe: false },
  { label: 'Mandatory Participation', weight: 1, severe: false },
  { label: 'Spirit Week at Work', weight: 1, severe: false },
  { label: 'The Work Christmas Party', weight: 1, severe: false },
  { label: 'Secret Santa with a Budget of £5', weight: 1, severe: false },
  { label: 'Mandatory Fun Forms', weight: 1, severe: false },
  { label: 'Icebreaker Bingo', weight: 1, severe: false },
  { label: 'Someone Asking If You\'re Okay When You\'re Fine', weight: 1, severe: false },
  { label: 'Being Described as "Quirky"', weight: 1, severe: false },
  { label: 'Being Called "An Old Soul"', weight: 1, severe: false },
  { label: 'Someone Who Loves Mondays', weight: 1, severe: false },
  { label: 'Overly Enthusiastic Mornings', weight: 1, severe: false },
  { label: 'People Who Are Fine Without Caffeine', weight: 1, severe: false },
  { label: 'Morning People', weight: 1, severe: false },
  { label: 'The Alarm Before You Need To Get Up', weight: 1, severe: false },
  { label: 'The Last 10 Minutes Before a Deadline', weight: 1, severe: false },
  { label: 'The Sunday Evening Feeling', weight: 1, severe: false },
  { label: 'The Pre-Holiday Email Onslaught', weight: 1, severe: false },
  { label: 'Returning to 247 Unread Emails', weight: 1, severe: false },
  { label: 'Inbox Zero People Describing Their System', weight: 1, severe: false },
  { label: 'People Who Read Physical Books on Purpose', weight: 1, severe: false },
  { label: 'Bookmarks That Fall Out', weight: 1, severe: false },
  { label: 'Spoilers (For Things You Haven\'t Watched Yet)', weight: 1, severe: false },
  { label: 'People Who Tell You the Twist Before You See It', weight: 1, severe: false },
  { label: 'Sequels That Are Worse Than the Original', weight: 1, severe: false },
  { label: 'Reboots That Miss the Point', weight: 1, severe: false },
  { label: 'Unnecessary Sequels', weight: 1, severe: false },
  { label: 'The Words "Extended Universe"', weight: 1, severe: false },
  { label: 'Crossover Events', weight: 1, severe: false },
  { label: 'Retcons', weight: 1, severe: false },
  { label: 'Cliffhanger Season Finales (Cancelled)', weight: 1, severe: false },
  { label: 'Being Told a Show Gets Better in Season 4', weight: 1, severe: false },
  { label: 'Ten-Minute Unskippable Intros', weight: 1, severe: false },
  { label: 'The YouTube Ad at the Most Tense Moment', weight: 1, severe: false },
  { label: 'Buffering at a Critical Moment', weight: 1, severe: false },
  { label: 'Low Battery Warning During the Best Part', weight: 1, severe: false },
  { label: 'Phone Dying Without a Charger Nearby', weight: 1, severe: false },
  { label: 'The Charger That Only Works at Certain Angles', weight: 1, severe: false },
  { label: 'Running Out of Storage', weight: 1, severe: false },
  { label: 'Autocorrect at Critical Moments', weight: 1, severe: false },
  { label: 'Sending a Message to the Wrong Person', weight: 1, severe: false },
  { label: 'Replying Instead of Forwarding', weight: 1, severe: false },
  { label: 'Accidentally Liking an Old Post', weight: 1, severe: false },
  { label: 'The Aggressive Notification Badge', weight: 1, severe: false },
  { label: 'App Updates at the Worst Time', weight: 1, severe: false },
  { label: 'Terms and Conditions Updated', weight: 1, severe: false },
  { label: 'Forced Software Update Mid-Battle', weight: 1, severe: false },
  { label: 'Driver Update Required', weight: 1, severe: false },
  { label: 'The Computer Needs to Restart', weight: 1, severe: false },
  { label: 'Unsaved Work', weight: 1, severe: false },
  { label: 'CTRL+Z Not Working', weight: 1, severe: false },
  { label: 'The Document Was Not Saved', weight: 1, severe: false },
  { label: 'Cloud Sync Conflict', weight: 1, severe: false },
  { label: 'Duplicate File Named "Final_FINAL_v3_ACTUAL"', weight: 1, severe: false },
  { label: 'The Wrong Version Open', weight: 1, severe: false },
  { label: 'The Track Changes Nobody Accepted', weight: 1, severe: false },
  { label: 'Comment from Someone Who No Longer Works There', weight: 1, severe: false },
  { label: 'Meeting Invite Without Agenda', weight: 1, severe: false },
  { label: 'A Meeting That Could Have Been an Email', weight: 1, severe: false },
  { label: 'PowerPoint with Thirty Slides of Text', weight: 1, severe: false },
  { label: 'The Person Who Presents by Reading the Slides Aloud', weight: 1, severe: false },
  { label: 'Transition Effects in Presentations', weight: 1, severe: false },
  { label: 'The Font Papyrus', weight: 1, severe: false },
  { label: 'WordArt (Earnest Usage)', weight: 1, severe: false },
  { label: 'Clipart in Professional Documents', weight: 1, severe: false },
  { label: 'The Comic Sans Font in Formal Communications', weight: 1, severe: false },
  { label: 'All Caps Emails', weight: 1, severe: false },
  { label: 'Excessive Exclamation Marks in Professional Context!!!', weight: 1, severe: false },
  { label: 'The Passive-Aggressive "Thanks"', weight: 1, severe: false },
  { label: '"As Per My Previous Email"', weight: 1, severe: false },
  { label: '"Just Circling Back"', weight: 1, severe: false },
  { label: '"Quick Wins"', weight: 1, severe: false },
  { label: '"Move the Needle"', weight: 1, severe: false },
  { label: '"Boil the Ocean"', weight: 1, severe: false },
  { label: '"Eating Our Own Dog Food"', weight: 1, severe: false },
  { label: '"Drinking the Kool-Aid" (Said Approvingly)', weight: 1, severe: false },
  { label: '"Circle Back to This"', weight: 1, severe: false },
  { label: '"Take This Offline"', weight: 1, severe: false },
  { label: '"Double-Click on That"', weight: 1, severe: false },
  { label: '"Bleeding Edge"', weight: 1, severe: false },
  { label: '"Skin in the Game"', weight: 1, severe: false },
  { label: '"Ideate"', weight: 1, severe: false },
  { label: '"Learnings"', weight: 1, severe: false },
  { label: '"Impactful"', weight: 1, severe: false },
  { label: '"Leverage" Used as a Verb', weight: 1, severe: false },
  { label: '"Utilise" When "Use" Would Do', weight: 1, severe: false },
  { label: '"Facilitate" When No Facilitation Occurred', weight: 1, severe: false },
  { label: '"Holistic Approach"', weight: 1, severe: false },
  { label: '"Deep Dive" Without Preparation', weight: 1, severe: false },
  { label: '"Helicopter View" (From Someone in the Weeds)', weight: 1, severe: false },
  { label: '"Boiling the Frog"', weight: 1, severe: false },
  { label: '"Parallel Processing" in Human Context', weight: 1, severe: false },
  { label: '"Silos" (Disapprovingly)', weight: 1, severe: false },
  { label: '"Swim Lanes"', weight: 1, severe: false },
  { label: '"Waterfalling" This', weight: 1, severe: false },
  { label: '"Agile" Used Incorrectly', weight: 1, severe: false },
  { label: '"Sprint" Outside of Technology', weight: 1, severe: false },
  { label: '"Scrum" Outside of Rugby', weight: 1, severe: false },
  { label: '"Retrospective" on a Good Day', weight: 1, severe: false },
  { label: '"Standup" That Is Not Standing Up', weight: 1, severe: false },
  { label: '"Velocity" Applied to Humans', weight: 1, severe: false },
  { label: '"Story Points" in Actual Meetings', weight: 1, severe: false },
  { label: '"Definition of Done" for Life Goals', weight: 1, severe: false },
  { label: '"Minimum Viable Product" Applied to Relationships', weight: 1, severe: false },
  { label: '"User Story" for Breakfast', weight: 1, severe: false },
  { label: '"Pain Point" Used in Conversation', weight: 1, severe: false },
  { label: '"Customer Journey" Used Incorrectly', weight: 1, severe: false },
  { label: '"Touch Point" as Affection', weight: 1, severe: false },
  { label: '"Net Promoter Score" for Friendship', weight: 1, severe: false },
  { label: '"Engagement Metrics" in Personal Life', weight: 1, severe: false },
  { label: '"Monetise" Something That Should Be Free', weight: 1, severe: false },
  { label: '"Freemium" Relationships', weight: 1, severe: false },
  { label: '"Upsell" in Friendship', weight: 1, severe: false },
  { label: '"ROI" on Kindness', weight: 1, severe: false },
  { label: '"Value Add" When There Is None', weight: 1, severe: false },
  { label: '"Thought Leader" Self-Description', weight: 1, severe: false },
  { label: '"Influencer" Without Influence', weight: 1, severe: false },
  { label: '"Personal Brand" Mentioned in Conversation', weight: 1, severe: false },
  { label: 'Someone Describing Their Hustle at a Party', weight: 1, severe: false },
  { label: 'The Phrase "I\'m an Entrepreneur"', weight: 1, severe: false },
  { label: 'Pitching a Business at a Wedding', weight: 1, severe: false },
  { label: 'MLM Recruitment Attempts', weight: 1, severe: false },
  { label: 'Network Marketing Explained Over Dinner', weight: 1, severe: false },
  { label: 'Being Asked to Join a Downline', weight: 1, severe: false },
  { label: 'Crypto Explanation Unsolicited', weight: 1, severe: false },
  { label: 'NFT Investment Pitch', weight: 1, severe: false },
  { label: 'Blockchain Used Where Unnecessary', weight: 1, severe: false },
  { label: 'AI-Generated Content (Unedited)', weight: 1, severe: false },
  { label: 'ChatGPT-Written Emails (Obvious)', weight: 1, severe: false },
  { label: 'Prompt Engineering Flex', weight: 1, severe: false },
  { label: 'AI Art in a Gallery', weight: 1, severe: false },
  { label: '"The Algorithm" Personified', weight: 1, severe: false },
  { label: 'TikTok Trends Explained Earnestly', weight: 1, severe: false },
  { label: 'Parents on Facebook', weight: 1, severe: false },
  { label: 'Grandparents Discovering Emojis', weight: 1, severe: false },
  { label: 'Excessive Emoji in Professional Communication', weight: 1, severe: false },
  { label: 'The Thumbs-Up Emoji as Response', weight: 1, severe: false },
  { label: 'Being Left on Read', weight: 1, severe: false },
  { label: 'Three Dots That Disappear', weight: 1, severe: false },
  { label: 'Being Seen Online but Not Replied To', weight: 1, severe: false },
  { label: 'Unexplained "K" Response', weight: 1, severe: false },
  { label: '"K" When You Expected More', weight: 1, severe: false },
  { label: 'One Word Texts After Long Messages', weight: 1, severe: false },
  { label: 'Someone Who Never Initiates Plans', weight: 1, severe: false },
  { label: 'Friends Who Always Cancel', weight: 1, severe: false },
  { label: 'The Perpetual Rain Check', weight: 1, severe: false },
  { label: '"We Should Catch Up Soon" (Never)', weight: 1, severe: false },
  { label: 'Making Plans and Immediately Regretting It', weight: 1, severe: false },
  { label: 'Agreeing to Something and Dreading It', weight: 1, severe: false },
  { label: 'The Anticipatory Social Dread', weight: 1, severe: false },
  { label: 'Pre-Party Anxiety', weight: 1, severe: false },
  { label: 'Mid-Party Exhaustion', weight: 1, severe: false },
  { label: 'Post-Party Analysis at 3am', weight: 1, severe: false },
  { label: 'The Hangover of Social Overstimulation', weight: 1, severe: false },
  { label: 'The Small Talk Death Spiral', weight: 1, severe: false },
  { label: '"So What Do You Do?" at Social Events', weight: 1, severe: false },
  { label: '"Any Plans for the Weekend?" (Monday)', weight: 1, severe: false },
  { label: '"How Was Your Weekend?" (Monday)', weight: 1, severe: false },
  { label: 'The Office Kitchen Encounter', weight: 1, severe: false },
  { label: 'The Lift Ride with a Colleague', weight: 1, severe: false },
  { label: 'The Corridor Acknowledgement Problem', weight: 1, severe: false },
  { label: 'Deciding When to Say Hello in a Long Corridor', weight: 1, severe: false },
  { label: 'Wave Timing Miscalculation', weight: 1, severe: false },
  { label: 'Double Wave Disaster', weight: 1, severe: false },
  { label: 'Handshake When Hug Was Expected', weight: 1, severe: false },
  { label: 'Hug When Handshake Was Expected', weight: 1, severe: false },
  { label: 'The Cheek Kiss in Wrong Culture', weight: 1, severe: false },
  { label: 'Two Kisses or Three?', weight: 1, severe: false },
  { label: 'The Mid-Hug Pat Duration Problem', weight: 1, severe: false },
  { label: 'Overly Firm Handshake', weight: 1, severe: false },
  { label: 'Limp Handshake', weight: 1, severe: false },
  { label: 'The Half-Handshake Conversion', weight: 1, severe: false },
  { label: 'Fist Bump Missed', weight: 1, severe: false },
  { label: 'High Five Left Hanging', weight: 1, severe: false },
  { label: 'Elbow Bump (Still Happening)', weight: 1, severe: false },
  { label: 'Air Kiss (Went Wrong)', weight: 1, severe: false },
  { label: 'The Nod That Was Misread as Bow', weight: 1, severe: false },
  { label: 'The Accidental Curtsy', weight: 1, severe: false },
  { label: 'Forgetting Someone\'s Name Immediately After Introduction', weight: 1, severe: false },
  { label: 'Calling Someone by the Wrong Name Repeatedly', weight: 1, severe: false },
  { label: 'Being Called by a Pet Name in Professional Context', weight: 1, severe: false },
  { label: 'Being Called "Hun" by a Stranger', weight: 1, severe: false },
  { label: 'Being Called "Sweetie" Patronisingly', weight: 1, severe: false },
  { label: 'Being Called "Buddy" Aggressively', weight: 1, severe: false },
  { label: 'Being Called "Champ" Passive-Aggressively', weight: 1, severe: false },
  { label: 'Being Called "Sport" Dismissively', weight: 1, severe: false },
  { label: 'Being Called "Tiger" Ironically', weight: 1, severe: false },
  { label: 'Being Called "Big Guy" (Not Big)', weight: 1, severe: false },
  { label: 'Being Called "Little Guy" (Not Little)', weight: 1, severe: false },
  { label: 'Being Called "Chief" While Not in Charge', weight: 1, severe: false },
  { label: 'Being Called "Boss" by Someone with Power Over Them', weight: 1, severe: false },
  { label: 'Misattributed Quotes', weight: 1, severe: false },
  { label: 'Inspirational Quotes Over Sunsets (Instagram)', weight: 1, severe: false },
  { label: 'Fake Stoic Philosophy Posts', weight: 1, severe: false },
  { label: '"A Quote Often Misattributed to Einstein"', weight: 1, severe: false },
  { label: 'History Rewritten as Self-Help', weight: 1, severe: false },
  { label: 'Hustle Culture Manifestos', weight: 1, severe: false },
  { label: '"You Only Need 4 Hours of Sleep"', weight: 1, severe: false },
  { label: '"I Woke Up at 4am and Here\'s What Happened"', weight: 1, severe: false },
  { label: 'Cold Shower Evangelism', weight: 1, severe: false },
  { label: 'Ice Bath Instructions Unsolicited', weight: 1, severe: false },
  { label: 'Marathon Running Described as Personality', weight: 1, severe: false },
  { label: 'CrossFit Mentioned Within Three Minutes', weight: 1, severe: false },
  { label: 'Veganism Brought Up Immediately', weight: 1, severe: false },
  { label: 'Dry January with Commentary', weight: 1, severe: false },
  { label: 'Intermittent Fasting Explained Unprompted', weight: 1, severe: false },
  { label: 'Keto Diet Evangelism', weight: 1, severe: false },
  { label: 'Paleo Diet Explanation at Dinner', weight: 1, severe: false },
  { label: 'Gluten Intolerance without a Diagnosis', weight: 1, severe: false },
  { label: 'Dairy-Free Choice Overly Explained', weight: 1, severe: false },
  { label: 'Ordering the Most Complicated Coffee', weight: 1, severe: false },
  { label: 'Explaining Your Coffee Order in Detail', weight: 1, severe: false },
  { label: 'Asking for Oat Milk in a Way That Inconveniences Others', weight: 1, severe: false },
  { label: 'The Eight-Word Starbucks Order', weight: 1, severe: false },
  { label: 'Naming Your Starbucks Name Strategically', weight: 1, severe: false },
  { label: 'Barista Spelling Your Name Wrong (Takes It Personally)', weight: 1, severe: false },
  { label: 'Coffee Snob Reaction to Instant Coffee', weight: 1, severe: false },
  { label: 'Tea Snobbery (Milk First Debate)', weight: 1, severe: false },
  { label: 'Being Present When Someone Describes Their Tea-Making Process', weight: 1, severe: false },
  { label: 'Someone Saying "It\'s Not Real Tea" About Your Tea', weight: 1, severe: false },
  { label: 'The Biscuit-to-Tea Ratio Lecture', weight: 1, severe: false },
  { label: 'Dunking Judgement', weight: 1, severe: false },
  { label: 'Biscuit Breaking in Tea (Catastrophic)', weight: 1, severe: false },
  { label: 'Toast Butter-Side Down', weight: 1, severe: false },
  { label: 'Jam Before Cream Debate', weight: 1, severe: false },
  { label: 'Scone Pronunciation Conflict', weight: 1, severe: false },
  { label: 'Regional Food Loyalty (Extreme)', weight: 1, severe: false },
  { label: 'Accepting Criticism of Home Town Food', weight: 1, severe: false },
  { label: 'Hearing "That\'s Not How They Do It There"', weight: 1, severe: false },
  { label: 'Authenticity Argument About Cuisine', weight: 1, severe: false },
  { label: 'Menu in Foreign Language Without Translation', weight: 1, severe: false },
  { label: 'Mispronouncing French Menu Items (Corrected Audibly)', weight: 1, severe: false },
  { label: 'Ordering Something You Don\'t Understand', weight: 1, severe: false },
  { label: 'Food Arriving While Others Are Still Ordering', weight: 1, severe: false },
  { label: 'Splitting the Bill 14 Ways', weight: 1, severe: false },
  { label: '"Actually, I Only Had a Starter"', weight: 1, severe: false },
  { label: 'Service Charge Debate', weight: 1, severe: false },
  { label: 'Tipping Amount Disagreement', weight: 1, severe: false },
  { label: 'Someone Who Doesn\'t Tip But Talks Loudly', weight: 1, severe: false },
  { label: 'Arriving at Restaurant Still Deciding', weight: 1, severe: false },
  { label: 'The Last-Minute Menu Change', weight: 1, severe: false },
  { label: 'The Group Order Where One Person Wants Substitutions', weight: 1, severe: false },
  { label: 'Dietary Requirement Discovered at Restaurant', weight: 1, severe: false },
  { label: 'Allergy Mentioned After Ordering', weight: 1, severe: false },
  { label: 'Sending Food Back (Unjustifiably)', weight: 1, severe: false },
  { label: 'Eating Others\' Leftovers Without Asking', weight: 1, severe: false },
  { label: 'The Last Chip Etiquette Breach', weight: 1, severe: false },
  { label: 'Stealing Chips Brazenly', weight: 1, severe: false },
  { label: 'The Double-Dipper', weight: 1, severe: false },
  { label: 'Sharing Starters Without Agreement', weight: 1, severe: false },
  { label: '"Can I Taste Yours?"', weight: 1, severe: false },
  { label: 'Eating Off Someone\'s Plate', weight: 1, severe: false },
  { label: 'Asking "Are You Going to Finish That?"', weight: 1, severe: false },
  { label: 'The Person Who Takes the Last of Everything', weight: 1, severe: false },
  { label: 'Serving Themselves First Repeatedly', weight: 1, severe: false },
  { label: 'Not Offering to Help Clear Up', weight: 1, severe: false },
  { label: 'Sitting Down While Others Wash Up', weight: 1, severe: false },
  { label: 'Passive Television Watching During Washing Up', weight: 1, severe: false },
  { label: 'Claiming to Have Helped When You Didn\'t', weight: 1, severe: false },
  { label: 'Partial Contribution to a Group Effort', weight: 1, severe: false },
  { label: 'Taking Credit for Collaborative Work', weight: 1, severe: false },
  { label: 'Presenting Others\' Ideas as Your Own', weight: 1, severe: false },
  { label: 'Subtle Idea Theft in Meetings', weight: 1, severe: false },
  { label: 'The Credit-Taking Interruption', weight: 1, severe: false },
  { label: 'Talking Over Others in Meetings', weight: 1, severe: false },
  { label: 'Interrupting Mid-Sentence to Make Unrelated Point', weight: 1, severe: false },
  { label: 'The Premature Conclusion Before You Finish', weight: 1, severe: false },
  { label: 'Someone Finishing Your Sentences Wrongly', weight: 1, severe: false },
  { label: 'Being Talked At Rather Than To', weight: 1, severe: false },
  { label: 'The Conversation Hijack', weight: 1, severe: false },
  { label: 'The Monologue Dressed as a Dialogue', weight: 1, severe: false },
  { label: 'Rhetorical Questions Asked Aggressively', weight: 1, severe: false },
  { label: 'Being Asked a Question to Demonstrate Their Knowledge', weight: 1, severe: false },
  { label: 'Socratic Method Used Passive-Aggressively', weight: 1, severe: false },
  { label: 'Condescension Wrapped in a Question', weight: 1, severe: false },
  { label: 'The Educational Tone Toward an Expert', weight: 1, severe: false },
  { label: 'Being Explained Something You Invented', weight: 1, severe: false },
  { label: 'Introduction to a Concept You Published', weight: 1, severe: false },
  { label: 'The Oversimplification of Your Specialist Area', weight: 1, severe: false },
  { label: 'Wikipedia Summary as Authority', weight: 1, severe: false },
  { label: 'YouTube Video as Definitive Source', weight: 1, severe: false },
  { label: 'Documentary Viewed Once as Expertise', weight: 1, severe: false },
  { label: 'Podcast Opinion Presented as Fact', weight: 1, severe: false },
  { label: 'Newsletter Subscription as Academic Credential', weight: 1, severe: false },
  { label: 'LinkedIn Post Cited in Argument', weight: 1, severe: false },
  { label: 'Facebook Share as Research', weight: 1, severe: false },
  { label: 'Reposted Infographic as Evidence', weight: 1, severe: false },
  { label: 'Meme Used as Counterargument', weight: 1, severe: false },
  { label: 'Screenshot as Primary Source', weight: 1, severe: false },
  { label: '"I Read Somewhere" as Citation', weight: 1, severe: false },
  { label: '"I Heard That" as Evidence', weight: 1, severe: false },
  { label: '"A Friend Who Is a Doctor Said"', weight: 1, severe: false },
  { label: '"My Cousin Who Works in Finance Said"', weight: 1, severe: false },
  { label: '"Someone on TikTok Explained"', weight: 1, severe: false },
  { label: '"The Algorithm Showed Me"', weight: 1, severe: false },
  { label: '"I\'ve Done My Research"', weight: 1, severe: false },
  { label: '"You Should Look Into It"', weight: 1, severe: false },
  { label: '"Just Asking Questions"', weight: 1, severe: false },
  { label: '"Do Your Own Research"', weight: 1, severe: false },
  { label: 'Winking Emoji Used Menacingly', weight: 1, severe: false },
  { label: '"Do Your Own Research" Combined with Wrong Information', weight: 1, severe: false },
  { label: 'Being Absolutely Certain About Things Not Understood', weight: 1, severe: false },
  { label: 'Intellectual Humility Absence', weight: 1, severe: false },
  { label: 'No Room for Doubt', weight: 1, severe: false },
  { label: 'The Closed Mind Manifested as Debate Tactic', weight: 1, severe: false },
  { label: 'Inability to Admit Being Wrong', weight: 1, severe: false },
  { label: 'The Moving Goalposts', weight: 1, severe: false },
  { label: 'Winning the Argument While Being Wrong', weight: 1, severe: false },
  { label: 'Being Technically Right in a Useless Way', weight: 1, severe: false },
  { label: 'Winning a Point That Doesn\'t Matter', weight: 1, severe: false },
  { label: 'Being Correct in a Situation That Has Already Moved On', weight: 1, severe: false },
  { label: 'Correct But Unhelpful', weight: 1, severe: false },
  { label: 'Accurate But Irrelevant', weight: 1, severe: false },
  { label: 'Timely But Wrong Room', weight: 1, severe: false },
  { label: 'Well-Intentioned But Spectacularly Ill-Timed', weight: 1, severe: false },
  { label: 'Good Point, Wrong Meeting', weight: 1, severe: false },
  { label: 'Right Person, Wrong Question', weight: 1, severe: false },
  { label: 'Wrong Person, Right Answer (Attributed Elsewhere)', weight: 1, severe: false },
  { label: 'Great Idea, Already Done', weight: 1, severe: false },
  { label: 'Reinventing Something That Exists', weight: 1, severe: false },
  { label: 'Building What Already Exists', weight: 1, severe: false },
  { label: 'Solving a Problem That Was Solved in 1992', weight: 1, severe: false },
  { label: 'Discovering Something Known for 200 Years', weight: 1, severe: false },
  { label: 'Patent for Something in Public Domain', weight: 1, severe: false },
  { label: 'Trademarking Sunlight', weight: 1, severe: false },
  { label: 'Charging for Something That Was Free', weight: 1, severe: false },
  { label: '"We\'re Not Removing It, Just Moving It Behind a Paywall"', weight: 1, severe: false },
  { label: '"We Value Your Feedback (We Will Not Change)"', weight: 1, severe: false },
  { label: '"Our Privacy Is Important to Us"', weight: 1, severe: false },
  { label: '"We\'ve Updated Our Privacy Policy"', weight: 1, severe: false },
  { label: '"To Better Serve You (New Fee)"', weight: 1, severe: false },
  { label: '"Exciting Changes Coming Soon" (Budget Cuts)', weight: 1, severe: false },
  { label: '"Right-Sizing" Announcement', weight: 1, severe: false },
  { label: '"Efficiency Programme" Announcement', weight: 1, severe: false },
  { label: '"Restructuring for Growth"', weight: 1, severe: false },
  { label: '"Strategic Review Outcome"', weight: 1, severe: false },
  { label: '"Proactive Talent Rationalisation"', weight: 1, severe: false },
  { label: '"Resource Optimisation Initiative"', weight: 1, severe: false },
  { label: '"Involuntary Offboarding"', weight: 1, severe: false },
  { label: 'End-of-Year Performance Review', weight: 1, severe: false },
  { label: 'Surprise Performance Improvement Plan', weight: 1, severe: false },
  { label: 'Mid-Year Check-In with Subtext', weight: 1, severe: false },
  { label: '360 Review Feedback from Anonymous Colleague', weight: 1, severe: false },
  { label: '"This Is Just a Developmental Conversation"', weight: 1, severe: false },
  { label: '"Some Feedback Came Through About You"', weight: 1, severe: false },
  { label: '"People Have Been Noticing"', weight: 1, severe: false },
  { label: '"There Is a Perception Issue"', weight: 1, severe: false },
  { label: '"I Just Wanted to Flag This"', weight: 1, severe: false },
  { label: '"I Noticed You Didn\'t Join the Retreat"', weight: 1, severe: false },
  { label: '"You Seem Distant Lately"', weight: 1, severe: false },
  { label: '"Are You Okay? You Seem Off"', weight: 1, severe: false },
  { label: '"You Look Tired"', weight: 1, severe: false },
  { label: '"Have You Been Sleeping?"', weight: 1, severe: false },
  { label: '"You Look Different"', weight: 1, severe: false },
  { label: '"Did You Change Something?"', weight: 1, severe: false },
  { label: '"Have You Lost or Gained Weight?"', weight: 1, severe: false },
  { label: '"You Look Well" (Ambiguously)', weight: 1, severe: false },
  { label: '"You Look... Healthy"', weight: 1, severe: false },
  { label: '"Did Something Happen to Your Hair?"', weight: 1, severe: false },
  { label: '"Oh, That\'s an Interesting Look"', weight: 1, severe: false },
  { label: '"That\'s Very Brave"', weight: 1, severe: false },
  { label: '"Not Everyone Could Wear That"', weight: 1, severe: false },
  { label: '"It\'s Very You" (Tone Unclear)', weight: 1, severe: false },
  { label: '"Well, It\'s Original"', weight: 1, severe: false },
  { label: '"You\'ve Got Confidence, That\'s for Sure"', weight: 1, severe: false },
  { label: '"I Could Never Pull That Off" (Tone Unclear)', weight: 1, severe: false },
  { label: 'Ambiguous Compliment Requiring Interpretation', weight: 1, severe: false },
  { label: 'Micro-Encouragement with Macro-Doubt', weight: 1, severe: false },
  { label: 'Faint Praise as Damnation', weight: 1, severe: false },
  { label: 'Enthusiastic Agreement Followed by "But"', weight: 1, severe: false },
  { label: '"That\'s Great, And Also—"', weight: 1, severe: false },
  { label: '"I Love It, Except For—"', weight: 1, severe: false },
  { label: '"It\'s Almost There"', weight: 1, severe: false },
  { label: '"Just One More Small Thing"', weight: 1, severe: false },
  { label: '"We\'re So Close"', weight: 1, severe: false },
  { label: '"Just One Final Change"', weight: 1, severe: false },
  { label: '"Actually, I Have a Few More Notes"', weight: 1, severe: false },
  { label: '"Can We Just Revisit This Section?"', weight: 1, severe: false },
  { label: '"While We\'re At It"', weight: 1, severe: false },
  { label: '"Now That I Think About It"', weight: 1, severe: false },
  { label: '"One More Thing" (Columbo Style, Not Charming)', weight: 1, severe: false },
  { label: 'Being Caught Just as You\'re Leaving', weight: 1, severe: false },
  { label: 'New Task When Packing Up', weight: 1, severe: false },
  { label: '"Before You Go—"', weight: 1, severe: false },
  { label: '"This Won\'t Take Long"', weight: 1, severe: false },
  { label: '"Quick Question" (Takes 45 Minutes)', weight: 1, severe: false },
  { label: '"Five Minutes of Your Time" (It Is Not)', weight: 1, severe: false },
  { label: '"I\'ll Be Brief" (They Will Not)', weight: 1, severe: false },
  { label: '"Short Meeting, I Promise"', weight: 1, severe: false },
  { label: 'The Zoom Call That Could Have Been an Email', weight: 1, severe: false },
  { label: 'The Video Call Where Someone\'s Mic Is Always Muted', weight: 1, severe: false },
  { label: '"Can You Hear Me Now?"', weight: 1, severe: false },
  { label: '"You\'re On Mute"', weight: 1, severe: false },
  { label: '"Hello? Hello? Am I—"', weight: 1, severe: false },
  { label: 'Background Noise Etiquette Failure', weight: 1, severe: false },
  { label: 'Dog During Critical Presentation', weight: 1, severe: false },
  { label: 'Child Walk-In at Worst Moment', weight: 1, severe: false },
  { label: 'Postman Doorbell During Professional Call', weight: 1, severe: false },
  { label: 'WiFi Dropping at Crucial Moment', weight: 1, severe: false },
  { label: 'Freezing Frame Mid-Sentence', weight: 1, severe: false },
  { label: 'Camera Off but Audio Accidentally On', weight: 1, severe: false },
  { label: 'Forgetting You\'re Unmuted', weight: 1, severe: false },
  { label: 'Talking to Yourself (On Call)', weight: 1, severe: false },
  { label: 'Unknowingly Screen Sharing Personal Content', weight: 1, severe: false },
  { label: 'Notification Sound During Quiet Moment', weight: 1, severe: false },
  { label: 'Ringtone Going Off in Cinema', weight: 1, severe: false },
  { label: 'Wrong Ringtone for the Situation', weight: 1, severe: false },
  { label: 'Ringtone Still Set to Default', weight: 1, severe: false },
  { label: 'Novelty Ringtone in Formal Setting', weight: 1, severe: false },
  { label: 'Ring-ring Ringtone in Ironic Usage', weight: 1, severe: false },
  { label: 'Aggressive Default Notification Sound', weight: 1, severe: false },
  { label: 'Email Alert Every 30 Seconds', weight: 1, severe: false },
  { label: 'Slack Ping at 11pm', weight: 1, severe: false },
  { label: '"Sent From My iPhone" (Nothing of Substance Follows)', weight: 1, severe: false },
  { label: '"On the Go, May Be Brief"', weight: 1, severe: false },
  { label: '"I\'ll Get Back to You" (Does Not)', weight: 1, severe: false },
  { label: '"Will Do!" (Does Not Do)', weight: 1, severe: false },
  { label: '"On It!" (Not On It)', weight: 1, severe: false },
  { label: '"Consider It Done" (Not Done)', weight: 1, severe: false },
  { label: '"Already Ahead of You" (Not Ahead)', weight: 1, severe: false },
  { label: '"Just Sent That Over" (Did Not)', weight: 1, severe: false },
  { label: '"Check Your Inbox" (Empty)', weight: 1, severe: false },
  { label: '"Should Be With You Now" (Is Not)', weight: 1, severe: false },
  { label: '"It\'s Coming, One Second" (Multiple Minutes)', weight: 1, severe: false },
  { label: '"Almost Ready" (Not Close)', weight: 1, severe: false },
  { label: '"Just Finishing Up" (Hours Later)', weight: 1, severe: false },
  { label: '"Five More Minutes" (Third Time)', weight: 1, severe: false },
  { label: '"Nearly There!" (Beginning, Actually)', weight: 1, severe: false },
  { label: '"Just Around the Corner" (Twenty Minutes)', weight: 1, severe: false },
  { label: '"We\'re Making Good Time" (We Are Not)', weight: 1, severe: false },
  { label: '"I Know a Shortcut" (Longer Route)', weight: 1, severe: false },
  { label: '"Trust Me, It\'s Quicker This Way"', weight: 1, severe: false },
  { label: '"The GPS Is Wrong"', weight: 1, severe: false },
  { label: '"I Don\'t Need Directions"', weight: 1, severe: false },
  { label: 'Refusing to Ask for Help While Lost', weight: 1, severe: false },
  { label: 'Arriving Ninety Minutes Late Confidently', weight: 1, severe: false },
  { label: 'Chronic Lateness Presented as Personality', weight: 1, severe: false },
  { label: 'Lateness Attributed to Traffic Always', weight: 1, severe: false },
  { label: 'Never Having Left Yet When Due to Arrive', weight: 1, severe: false },
]
