// weapons.ts — Weapons content pool for Wheel of Fate.
// 500+ SimpleItem entries spanning legendary to absurd.
// No default export. No functions. Static const array only.

import type { SimpleItem } from './types'

export const weapons: SimpleItem[] = [
  { label: 'No Weapon (Unarmed)', weight: 4, element: 'Neutral', grade: 'D' },
  { label: 'Excalibur', weight: 1, element: 'Light', grade: 'SS' },
  { label: 'Mjolnir', weight: 1, element: 'Lightning', grade: 'SS' },
  { label: 'Gungnir', weight: 1, element: 'Wind', grade: 'SS' },
  { label: 'Durandal', weight: 1, element: 'Light', grade: 'SS' },
  { label: 'Joyeuse', weight: 1, element: 'Light', grade: 'SS' },
  { label: 'Kusarigama', weight: 1, element: 'Neutral', grade: 'C' },
  { label: 'Void Blade', weight: 1, element: 'Void', grade: 'S' },
  { label: 'Seraphic Lance', weight: 1, element: 'Light', grade: 'S' },
  { label: 'Dragon\'s Fang', weight: 1, element: 'Fire', grade: 'S' },
  { label: 'Shadowmeld Dagger', weight: 1, element: 'Shadow', grade: 'A' },
  { label: 'Thunderclap Hammer', weight: 1, element: 'Lightning', grade: 'A' },
  { label: 'Sunfire Bow', weight: 1, element: 'Light', grade: 'A' },
  { label: 'Runic Greatsword', weight: 1, element: 'Arcane', grade: 'A' },
  { label: 'Ethereal Whip', weight: 1, element: 'Arcane', grade: 'A' },
  { label: 'Bloodletter', weight: 1, element: 'Blood', grade: 'A' },
  { label: 'Soulreaver', weight: 1, element: 'Soul', grade: 'S' },
  { label: 'Starfall Javelin', weight: 1, element: 'Cosmic', grade: 'A' },
  { label: 'Moonblade', weight: 1, element: 'Cosmic', grade: 'A' },
  { label: 'Stormcaller Staff', weight: 1, element: 'Lightning', grade: 'A' },
  { label: 'Frostbite Axe', weight: 1, element: 'Ice', grade: 'A' },
  { label: 'Hellfire Crossbow', weight: 1, element: 'Fire', grade: 'A' },
  { label: 'Celestial Spear', weight: 1, element: 'Light', grade: 'A' },
  { label: 'Abyssal Scythe', weight: 1, element: 'Void', grade: 'S' },
  { label: 'Titan\'s Maul', weight: 1, element: 'Earth', grade: 'A' },
  { label: 'Phantom Blade', weight: 1, element: 'Soul', grade: 'A' },
  { label: 'Wraithbone Saber', weight: 1, element: 'Soul', grade: 'B' },
  { label: 'Arcanite Wand', weight: 1, element: 'Arcane', grade: 'C' },
  { label: 'Voidsteel Katana', weight: 1, element: 'Void', grade: 'C' },
  { label: 'Dragonbone Club', weight: 1, element: 'Earth', grade: 'C' },
  { label: 'Mithril Rapier', weight: 1, element: 'Metal', grade: 'C' },
  { label: 'Orichalcum Trident', weight: 1, element: 'Metal', grade: 'C' },
  { label: 'Stardust Bow', weight: 1, element: 'Cosmic', grade: 'C' },
  { label: 'Necromancer\'s Staff', weight: 1, element: 'Arcane', grade: 'C' },
  { label: 'Warlock\'s Grimoire (Weaponised)', weight: 1, element: 'Arcane', grade: 'C' },
  { label: 'Oracle\'s Rod', weight: 1, element: 'Arcane', grade: 'C' },
  { label: 'Tempest Blade', weight: 1, element: 'Lightning', grade: 'C' },
  { label: 'Eternal Edge', weight: 1, element: 'Neutral', grade: 'C' },
  { label: 'Deathwhisper', weight: 1, element: 'Void', grade: 'S' },
  { label: 'Godsplitter', weight: 1, element: 'Light', grade: 'SS' },
  { label: 'Worldrend', weight: 1, element: 'Chaos', grade: 'SS' },
  { label: 'Sunder Fist', weight: 1, element: 'Metal', grade: 'B' },
  { label: 'War Hymn Blade', weight: 1, element: 'Neutral', grade: 'C' },
  { label: 'Fate\'s Edge', weight: 1, element: 'Arcane', grade: 'S' },
  { label: 'Prophecy Sword', weight: 1, element: 'Arcane', grade: 'S' },
  { label: 'The Last Word (Firearm)', weight: 1, element: 'Neutral', grade: 'SS' },
  { label: 'Final Judgment (Cannon)', weight: 1, element: 'Light', grade: 'SS' },
  { label: 'Heaven\'s Fury', weight: 1, element: 'Light', grade: 'SS' },
  { label: 'Hell\'s Wrath', weight: 1, element: 'Fire', grade: 'S' },
  { label: 'Voidcaller Bow', weight: 1, element: 'Void', grade: 'A' },
  { label: 'Stormbreaker', weight: 1, element: 'Lightning', grade: 'A' },
  { label: 'Bloodmoon Scimitar', weight: 1, element: 'Blood', grade: 'A' },
  { label: 'Eclipse Blade', weight: 1, element: 'Shadow', grade: 'S' },
  { label: 'Sundering Spear', weight: 1, element: 'Wind', grade: 'B' },
  { label: 'Earthshaker Hammer', weight: 1, element: 'Earth', grade: 'B' },
  { label: 'Skyrender Axe', weight: 1, element: 'Wind', grade: 'B' },
  { label: 'Tidecaller Trident', weight: 1, element: 'Water', grade: 'B' },
  { label: 'Flamebrand', weight: 1, element: 'Fire', grade: 'C' },
  { label: 'Frostweave Blade', weight: 1, element: 'Ice', grade: 'C' },
  { label: 'Thunderstrike Halberd', weight: 1, element: 'Lightning', grade: 'C' },
  { label: 'Shadowfang', weight: 1, element: 'Shadow', grade: 'A' },
  { label: 'Radiant Sword', weight: 1, element: 'Light', grade: 'A' },
  { label: 'Darkmatter Blade', weight: 1, element: 'Void', grade: 'S' },
  { label: 'Quantum Saber', weight: 1, element: 'Cosmic', grade: 'A' },
  { label: 'Chrono Blade', weight: 1, element: 'Time', grade: 'A' },
  { label: 'Soul Splitter', weight: 1, element: 'Soul', grade: 'S' },
  { label: 'Reality Cutter', weight: 1, element: 'Chaos', grade: 'SSS' },
  { label: 'Dimensional Edge', weight: 1, element: 'Void', grade: 'S' },
  { label: 'Cosmic Lance', weight: 1, element: 'Cosmic', grade: 'S' },
  { label: 'Entropy Sword', weight: 1, element: 'Void', grade: 'SSS' },
  { label: 'Chaos Blade', weight: 1, element: 'Chaos', grade: 'SSS' },
  { label: 'Order Breaker', weight: 1, element: 'Chaos', grade: 'S' },
  { label: 'Nexus Sword', weight: 1, element: 'Chaos', grade: 'A' },
  { label: 'Prism Blade', weight: 1, element: 'Chaos', grade: 'B' },
  { label: 'Umbral Dagger', weight: 1, element: 'Shadow', grade: 'B' },
  { label: 'Luminous Rapier', weight: 1, element: 'Light', grade: 'B' },
  { label: 'Arcane Shortsword', weight: 1, element: 'Arcane', grade: 'C' },
  { label: 'Spellblade', weight: 1, element: 'Arcane', grade: 'C' },
  { label: 'Rune-etched Battleaxe', weight: 1, element: 'Arcane', grade: 'C' },
  { label: 'Sigil Spear', weight: 1, element: 'Arcane', grade: 'C' },
  { label: 'Enchanted Longbow', weight: 1, element: 'Arcane', grade: 'C' },
  { label: 'Blessed Mace', weight: 1, element: 'Light', grade: 'C' },
  { label: 'Cursed Claymore', weight: 1, element: 'Shadow', grade: 'C' },
  { label: 'Hexblade', weight: 1, element: 'Arcane', grade: 'C' },
  { label: 'Charm-Forged Flail', weight: 1, element: 'Arcane', grade: 'B' },
  { label: 'Imbued Morning Star', weight: 1, element: 'Arcane', grade: 'B' },
  { label: 'War Scythe of Endings', weight: 1, element: 'Soul', grade: 'S' },
  { label: 'Reaping Hook', weight: 1, element: 'Blood', grade: 'B' },
  { label: 'Harvest Blade', weight: 1, element: 'Blood', grade: 'B' },
  { label: 'Ancient Halberd', weight: 1, element: 'Neutral', grade: 'C' },
  { label: 'Primordial Glaive', weight: 1, element: 'Neutral', grade: 'SS' },
  { label: 'Archaic Warhammer', weight: 1, element: 'Neutral', grade: 'C' },
  { label: 'Ancestral Blade', weight: 1, element: 'Neutral', grade: 'C' },
  { label: 'Heirloom Sword', weight: 1, element: 'Neutral', grade: 'C' },
  { label: 'Relic Blade', weight: 1, element: 'Neutral', grade: 'C' },
  { label: 'Artifact Sword', weight: 1, element: 'Neutral', grade: 'C' },
  { label: 'Mythic Spear', weight: 1, element: 'Neutral', grade: 'C' },
  { label: 'Legendary Bow', weight: 1, element: 'Neutral', grade: 'C' },
  { label: 'Fabled Dagger', weight: 1, element: 'Neutral', grade: 'C' },
  { label: 'Storied Axe', weight: 1, element: 'Neutral', grade: 'C' },
  { label: 'Epic Wand', weight: 1, element: 'Arcane', grade: 'C' },
  { label: 'Heroic Shield', weight: 1, element: 'Neutral', grade: 'C' },
  { label: 'Champion\'s Blade', weight: 1, element: 'Neutral', grade: 'C' },
  { label: 'Conqueror\'s Axe', weight: 1, element: 'Metal', grade: 'C' },
  { label: 'Destroyer\'s Hammer', weight: 1, element: 'Metal', grade: 'C' },
  { label: 'Protector\'s Shield', weight: 1, element: 'Neutral', grade: 'C' },
  { label: 'Guardian\'s Spear', weight: 1, element: 'Neutral', grade: 'C' },
  { label: 'Avenger\'s Sword', weight: 1, element: 'Neutral', grade: 'C' },
  { label: 'Paladin\'s Holy Avenger', weight: 1, element: 'Light', grade: 'A' },
  { label: 'Ranger\'s Heartseeker Bow', weight: 1, element: 'Neutral', grade: 'A' },
  { label: 'Assassin\'s Shadowdagger', weight: 1, element: 'Shadow', grade: 'A' },
  { label: 'Mage\'s Arcane Focus', weight: 1, element: 'Arcane', grade: 'B' },
  { label: 'Druid\'s Nature Staff', weight: 1, element: 'Nature', grade: 'B' },
  { label: 'Warlock\'s Pact Blade', weight: 1, element: 'Arcane', grade: 'A' },
  { label: 'Sorcerer\'s Power Conduit', weight: 1, element: 'Arcane', grade: 'B' },
  { label: 'Bard\'s Instrument of War', weight: 1, element: 'Sound', grade: 'B' },
  { label: 'Monk\'s Iron Fists', weight: 1, element: 'Metal', grade: 'C' },
  { label: 'Berserker\'s Greataxe', weight: 1, element: 'Neutral', grade: 'B' },
  { label: 'Necromancer\'s Deathscythe', weight: 1, element: 'Soul', grade: 'S' },
  { label: 'Artificer\'s Mechanical Arm', weight: 1, element: 'Metal', grade: 'C' },
  { label: 'Cleric\'s Divine Rod', weight: 1, element: 'Light', grade: 'B' },
  { label: 'Inquisitor\'s Flame Whip', weight: 1, element: 'Fire', grade: 'B' },
  { label: 'Templar\'s Crusader Blade', weight: 1, element: 'Light', grade: 'B' },
  { label: 'Dark Knight\'s Hell Edge', weight: 1, element: 'Fire', grade: 'B' },
  { label: 'Death Knight\'s Runeblade', weight: 1, element: 'Soul', grade: 'A' },
  { label: 'Blood Knight\'s Crimson Blade', weight: 1, element: 'Blood', grade: 'B' },
  { label: 'Chaos Knight\'s Fractal Sword', weight: 1, element: 'Chaos', grade: 'B' },
  { label: 'Sky Knight\'s Aerial Spear', weight: 1, element: 'Wind', grade: 'B' },
  { label: 'Sea Knight\'s Depth Blade', weight: 1, element: 'Water', grade: 'B' },
  { label: 'Earth Knight\'s Stone Maul', weight: 1, element: 'Earth', grade: 'B' },
  { label: 'Star Knight\'s Celestial Edge', weight: 1, element: 'Light', grade: 'A' },
  { label: 'Void Knight\'s Nothing Blade', weight: 1, element: 'Void', grade: 'S' },
  { label: 'Time Knight\'s Paradox Sword', weight: 1, element: 'Time', grade: 'S' },
  { label: 'Soul Knight\'s Ecto-Blade', weight: 1, element: 'Soul', grade: 'B' },
  { label: 'Mind Knight\'s Psi-Blade', weight: 1, element: 'Psychic', grade: 'B' },
  { label: 'Spirit Blade', weight: 1, element: 'Soul', grade: 'B' },
  { label: 'Ghost Sword', weight: 1, element: 'Soul', grade: 'B' },
  { label: 'Wraith Scythe', weight: 1, element: 'Soul', grade: 'B' },
  { label: 'Banshee\'s Wail Spear', weight: 1, element: 'Soul', grade: 'A' },
  { label: 'Lich\'s Phylactery Staff', weight: 1, element: 'Soul', grade: 'A' },
  { label: 'Vampire\'s Bloodblade', weight: 1, element: 'Blood', grade: 'B' },
  { label: 'Werewolf\'s Silver-Proof Claw', weight: 1, element: 'Nature', grade: 'B' },
  { label: 'Dragon\'s Claw Gauntlets', weight: 1, element: 'Fire', grade: 'A' },
  { label: 'Phoenix Feather Blade', weight: 1, element: 'Light', grade: 'A' },
  { label: 'Griffin Talon', weight: 1, element: 'Nature', grade: 'A' },
  { label: 'Unicorn Horn Lance', weight: 1, element: 'Light', grade: 'A' },
  { label: 'Basilisk Eye Staff', weight: 1, element: 'Nature', grade: 'B' },
  { label: 'Medusa\'s Gaze Wand', weight: 1, element: 'Nature', grade: 'B' },
  { label: 'Chimera Fang', weight: 1, element: 'Nature', grade: 'B' },
  { label: 'Hydra Spine Blade', weight: 1, element: 'Nature', grade: 'B' },
  { label: 'Cerberus Chain', weight: 1, element: 'Nature', grade: 'A' },
  { label: 'Kraken Tentacle', weight: 1, element: 'Nature', grade: 'B' },
  { label: 'Leviathan Scale Bow', weight: 1, element: 'Nature', grade: 'B' },
  { label: 'Behemoth Bone Club', weight: 1, element: 'Nature', grade: 'B' },
  { label: 'Ziz Feather Arrows', weight: 1, element: 'Wind', grade: 'B' },
  { label: 'Golem Arm', weight: 1, element: 'Metal', grade: 'C' },
  { label: 'Automaton Fist', weight: 1, element: 'Metal', grade: 'C' },
  { label: 'Construct Cannon', weight: 1, element: 'Metal', grade: 'C' },
  { label: 'Mechanical Spider Blade', weight: 1, element: 'Metal', grade: 'C' },
  { label: 'Steam-Powered Mace', weight: 1, element: 'Metal', grade: 'C' },
  { label: 'Aether Cannon', weight: 1, element: 'Arcane', grade: 'C' },
  { label: 'Plasma Cutter', weight: 1, element: 'Fire', grade: 'B' },
  { label: 'Energy Rifle', weight: 1, element: 'Arcane', grade: 'B' },
  { label: 'Photon Blade', weight: 1, element: 'Light', grade: 'B' },
  { label: 'Ion Spear', weight: 1, element: 'Cosmic', grade: 'B' },
  { label: 'Graviton Hammer', weight: 1, element: 'Gravity', grade: 'A' },
  { label: 'Singularity Gun', weight: 1, element: 'Gravity', grade: 'S' },
  { label: 'Antimatter Pistol', weight: 1, element: 'Cosmic', grade: 'A' },
  { label: 'Neutrino Railgun', weight: 1, element: 'Cosmic', grade: 'A' },
  { label: 'Tachyon Blade', weight: 1, element: 'Time', grade: 'A' },
  { label: 'Quark Destabiliser', weight: 1, element: 'Cosmic', grade: 'S' },
  { label: 'Hadron Collider Sword', weight: 1, element: 'Cosmic', grade: 'S' },
  { label: 'Fusion Lance', weight: 1, element: 'Cosmic', grade: 'A' },
  { label: 'Fission Bomb (Personal)', weight: 1, element: 'Arcane', grade: 'B' },
  { label: 'Nano-blade', weight: 1, element: 'Metal', grade: 'B' },
  { label: 'Micro-filament Whip', weight: 1, element: 'Metal', grade: 'C' },
  { label: 'Molecular Wire', weight: 1, element: 'Metal', grade: 'C' },
  { label: 'Monomolecular Blade', weight: 1, element: 'Metal', grade: 'B' },
  { label: 'Vibro-sword', weight: 1, element: 'Metal', grade: 'B' },
  { label: 'Sonic Disruptor', weight: 1, element: 'Sound', grade: 'B' },
  { label: 'Ultrasonic Blade', weight: 1, element: 'Sound', grade: 'B' },
  { label: 'Resonance Hammer', weight: 1, element: 'Sound', grade: 'B' },
  { label: 'Frequency Rifle', weight: 1, element: 'Sound', grade: 'C' },
  { label: 'Waveform Disruptor', weight: 1, element: 'Sound', grade: 'C' },
  { label: 'Psionic Blade', weight: 1, element: 'Psychic', grade: 'B' },
  { label: 'Mind Saber', weight: 1, element: 'Psychic', grade: 'B' },
  { label: 'Fear Manifestation Blade', weight: 1, element: 'Psychic', grade: 'B' },
  { label: 'Dream Cutter', weight: 1, element: 'Psychic', grade: 'B' },
  { label: 'Nightmare Scythe', weight: 1, element: 'Psychic', grade: 'B' },
  { label: 'Memory Sword', weight: 1, element: 'Psychic', grade: 'B' },
  { label: 'Will Blade', weight: 1, element: 'Psychic', grade: 'B' },
  { label: 'Intent Spear', weight: 1, element: 'Psychic', grade: 'B' },
  { label: 'Conviction Sword', weight: 1, element: 'Light', grade: 'B' },
  { label: 'Faith Lance', weight: 1, element: 'Light', grade: 'B' },
  { label: 'Doubt Dagger', weight: 1, element: 'Psychic', grade: 'B' },
  { label: 'Despair Scythe', weight: 1, element: 'Psychic', grade: 'B' },
  { label: 'Hope Blade', weight: 1, element: 'Light', grade: 'B' },
  { label: 'Love Sword (Terrifyingly Effective)', weight: 1, element: 'Neutral', grade: 'B' },
  { label: 'Grandma\'s Slipper', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Frozen Fish', weight: 1, element: 'Water', grade: 'F' },
  { label: 'Damp Newspaper', weight: 1, element: 'Water', grade: 'F' },
  { label: 'A Stern Talking-To', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Passive Aggression (Manifested)', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Slightly Disappointing Handshake', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Pool Noodle', weight: 1, element: 'Water', grade: 'F' },
  { label: 'Traffic Cone', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Overcooked Noodle', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Aggressive Eye Contact', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Decorative Gourd', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Novelty Giant Inflatable Hammer', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Rolled-Up Magazine', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Wet Towel', weight: 1, element: 'Water', grade: 'F' },
  { label: 'Unripe Avocado', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Heavily Annotated Tax Return', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Passive-Aggressive Note on Windscreen', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Complaint Letter (Sent Third Class)', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Passive-Aggressive Sighing', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'The Silent Treatment', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Withering Glare', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'A Strongly Worded Email (Printed Out)', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Bureaucratic Form (Multiple Copies)', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Outdated User Manual', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Single Chopstick', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Novelty Key Ring (Loaded)', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Stale Baguette', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Frozen Burrito', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Crocs (Both)', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Flip Flops (Armed)', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'An Embarrassing Photo', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Receipt from 2009', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Strongly Worded Tweet (Printed)', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'One-Star Review (Framed)', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Passive-Aggressive Post-It Note', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Half a Pair of Scissors', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Staple Gun (Jammed)', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Tape Dispenser with No Tape', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Broken Ruler', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Chewed Pen', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'An IOU', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Coupon for 10% Off (Expired)', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Gift Card with Unknown Balance', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Souvenir Snow Globe', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Novelty Bobblehead', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Plastic Flamingo', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Garden Gnome', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Decorative Wind Chime', weight: 1, element: 'Sound', grade: 'F' },
  { label: 'Lava Lamp', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Vintage Telephone (Rotary)', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Extremely Heavy Cookbook', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Encyclopedia Volume M', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Phone Book (Regional)', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'IKEA Instructions', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Owner\'s Manual (Wrong Language)', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Warranty Card (Filled Out Incorrectly)', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Terms and Conditions (Full Printout)', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Cookie Tin (Empty, Sewing Inside)', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Fruitcake (Several Years Old)', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Candy Cane (Structural)', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Novelty Giant Candy Bar', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Swiss Roll (Unsliced)', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Block of Aged Parmesan', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Baguette (Very Stale)', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Raw Turnip', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Unopened Jar of Pickles', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Full Bottle of Ketchup', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Family-Size Can of Beans', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Cast Iron Skillet', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Le Creuset Dutch Oven', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Wok (With Residual Heat)', weight: 1, element: 'Fire', grade: 'F' },
  { label: 'Electric Whisk (Plugged In)', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Immersion Blender (Running)', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Potato Masher', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Ladle (Aggressive)', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Tongs (Snap)', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Salad Spinner (Launched)', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Mandoline Slicer (Carefully)', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Box Grater', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Can Opener (Manual)', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Nutcracker (Vintage)', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Lemon Squeezer', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Garlic Press', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Avocado Tool', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Egg Slicer', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Strawberry Huller', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Mango Splitter', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Corn Stripper', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Asparagus Peeler', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Olive Pitter (Loaded)', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Cherry Picker', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Bench Scraper', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Pastry Cutter', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Rolling Pin (Oak, Heavy)', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Marble Rolling Pin', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Dough Hook', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Piping Bag (Full, Pressurised)', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Fondant Smoother', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Cake Leveler', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Bread Knife (Just the Bread Knife)', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Steak Knife (One)', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Butter Knife (That\'s It)', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Toothpick (Artisanal)', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Cocktail Stirrer', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Travel Mug (Lid Slightly Off)', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Thermos from 1987', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Reusable Shopping Bag (Full)', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Tote Bag (Extremely Heavy)', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Fanny Pack (Armed)', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Backpack (Overfull)', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Laptop Bag (With Laptop)', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Briefcase (Locked, Unknown Contents)', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Umbrella (Pointy End First)', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Walking Stick (Not Needed)', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Collapsible Chair', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Camping Stool (Wobbly)', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Step Ladder (Two-Step)', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Toilet Plunger', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Mop (Dripping)', weight: 1, element: 'Water', grade: 'F' },
  { label: 'Broom', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Dustpan and Brush', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Window Squeegee', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Feather Duster (Decorative)', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Swiffer (Extended)', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Vacuum Attachment (Hose Only)', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Pool Skimmer', weight: 1, element: 'Water', grade: 'F' },
  { label: 'Leaf Blower (Petrol)', weight: 1, element: 'Wind', grade: 'F' },
  { label: 'Garden Hoe', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Rake', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Trowel', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Watering Can (Full)', weight: 1, element: 'Water', grade: 'F' },
  { label: 'Plastic Plant Pot', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Overgrown Houseplant', weight: 1, element: 'Nature', grade: 'F' },
  { label: 'Cactus (Potted, Unprotected)', weight: 1, element: 'Nature', grade: 'F' },
  { label: 'Hanging Basket (With Bracket)', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Gnome on a Stick', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Wind Chime (Sonic)', weight: 1, element: 'Sound', grade: 'F' },
  { label: 'Flamingo Lamp (Weighted Base)', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Lava Lamp (Hot)', weight: 1, element: 'Fire', grade: 'F' },
  { label: 'Novelty Desk Fan', weight: 1, element: 'Wind', grade: 'F' },
  { label: 'Desk Lamp (Angle-Poise)', weight: 1, element: 'Light', grade: 'F' },
  { label: 'Paperweight (Suspicious)', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Crystal Ball (Solid)', weight: 1, element: 'Arcane', grade: 'F' },
  { label: 'Snow Globe (Large)', weight: 1, element: 'Ice', grade: 'F' },
  { label: 'Ceramic Figurine', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Porcelain Vase', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Trophy (Wrong Name Engraved)', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Participation Medal', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Certificate of Mediocrity', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Framed Inspirational Quote', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Novelty Calendar (Wrong Year)', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Office Chair (On Wheels)', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Filing Cabinet (Closed)', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Rubber Stamp', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Stapler (Industrial)', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Three-Hole Punch', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Letter Opener', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Highlighter (Neon Yellow)', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Whiteboard Eraser', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Laser Pointer (Red Dot)', weight: 1, element: 'Light', grade: 'F' },
  { label: 'Presentation Clicker', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Mouse (Wireless, Low Battery)', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Keyboard (Mechanical, Noisy)', weight: 1, element: 'Sound', grade: 'F' },
  { label: 'USB Hub (Full)', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Extension Lead (Fully Extended)', weight: 1, element: 'Lightning', grade: 'F' },
  { label: 'Cable Ties (Bundle)', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Rubber Band Ball', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Box of Paperclips', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Correction Fluid (Wet)', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Post-It Note Dispenser (Loaded)', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Binder Clip (Oversized)', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Finger of Blame', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Pointing Stick', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'The Clue Bat', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Literally a Wet Noodle', weight: 1, element: 'Water', grade: 'F' },
  { label: 'Just a Stick, Really', weight: 1, element: 'Neutral', grade: 'D' },
  { label: 'A Rock (Unspecified)', weight: 1, element: 'Neutral', grade: 'D' },
  { label: 'Slightly Bigger Rock', weight: 1, element: 'Neutral', grade: 'D' },
  { label: 'A Sharp Stone (Found)', weight: 1, element: 'Neutral', grade: 'D' },
  { label: 'The First Tool (Prehistoric)', weight: 1, element: 'Neutral', grade: 'D' },
  { label: 'Improvised Club', weight: 1, element: 'Neutral', grade: 'D' },
  { label: 'Improvised Spear (Broom Handle)', weight: 1, element: 'Neutral', grade: 'D' },
  { label: 'Improvised Bow (Garden Twine)', weight: 1, element: 'Neutral', grade: 'D' },
  { label: 'Improvised Armour (Pots and Pans)', weight: 1, element: 'Neutral', grade: 'D' },
  { label: 'Improvised Shield (Bin Lid)', weight: 1, element: 'Neutral', grade: 'D' },
  { label: 'Improvised Sword (Long Stick)', weight: 1, element: 'Neutral', grade: 'D' },
  { label: 'Improvised Flail (Sock with Something in It)', weight: 1, element: 'Neutral', grade: 'D' },
  { label: 'Improvised Hammer (Shoe)', weight: 1, element: 'Neutral', grade: 'D' },
  { label: 'Improvised Axe (Half a Chair)', weight: 1, element: 'Neutral', grade: 'D' },
  { label: 'Improvised Lance (Mop)', weight: 1, element: 'Neutral', grade: 'D' },
  { label: 'Improvised Weapon (Whatever Is to Hand)', weight: 1, element: 'Neutral', grade: 'D' },
  { label: 'The Entire Environment as a Weapon', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Environmental Hazard (Specific)', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Situational Advantage', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Context-Appropriate Item', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Nearby Object (Unspecified)', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Whatever This Is', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Something That Looked Like a Weapon', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Totally Not a Weapon (It Is)', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Plausibly a Weapon', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Technically a Weapon in Eleven Jurisdictions', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Not Technically Illegal', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Legally Ambiguous Object', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Barely a Weapon', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Questionable Choice', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'The Judge Will Decide', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Exhibit A', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Exhibit B (Worse)', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'A Very Loud Voice', weight: 1, element: 'Sound', grade: 'F' },
  { label: 'The Element of Surprise', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Disappointment (Weaponised)', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Unbearable Cheerfulness', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Mild Inconvenience (Physical)', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Sheer Audacity', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'The Power of Asking to Speak with the Manager', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'An Extremely Long Receipt', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Loyalty Points (Printed Summary)', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'A Very Concerned Letter to Council', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Noise Complaint Form', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Parking Ticket (Stamped)', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Speeding Fine (Framed)', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Overdue Library Book', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Accumulated Late Fees', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Outstanding Debt (Manifested)', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Mounting Interest', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'The Bill (Final Reminder)', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Invoice (With Penalties)', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Small Claims Court Summons', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Strongly Worded Will (Updated)', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Inheritance (Withheld)', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'The Last Piece of Cake (Taken)', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Remote Control (Batteries Stolen)', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Phone Charger (Wrong Cable)', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Slightly Tangled Earphones', weight: 1, element: 'Sound', grade: 'F' },
  { label: 'Pop-Up Ad (Printed)', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Unskippable Pre-Roll Ad', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Cookie Consent Form', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Terms and Conditions (Accepted)', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'CAPTCHA of Doom', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Please Disable Your Ad Blocker', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Subscribe to Continue Reading', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'The Paywall', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Password Reset Email (That Never Arrives)', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Two-Factor Authentication (Phone Lost)', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Security Question (Forgotten Answer)', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Account Locked (Try Again Later)', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Error 404', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Loading Spinner (Forever)', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Blue Screen of Death', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Kunai (Novelty Keychain)', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Shuriken (Foam)', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Nunchucks (DVD Tutorial)', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Tonfa (Pool Noodle)', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Bo Staff (Parking Meter)', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Sai (Letter Openers, Paired)', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Kama (Pizza Cutter)', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Wakizashi (Bread Knife)', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Tanto (Butter Knife)', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Naginata (Mop with Attitude)', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Yari (Selfie Stick)', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Ono (Axe from Monopoly)', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Kanabo (Baseball Bat with Issues)', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Tessen (Novelty Fan)', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Manriki (Jump Rope)', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Blowgun (Cocktail Straw)', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Boomerang (Does Not Return)', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Lasso (Extension Cord)', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Sling (Elastic Band, Large)', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Bola (Three Socks with Coins)', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Net (Shopping Bag)', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Crossbow (Rubber Band)', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Arbalest (Upscaled Crossbow)', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Ballista (DIY)', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Trebuchet (Small)', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Catapult (Rubber Band)', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Ballista Bolt (Single)', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Cannon Ball (Small)', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Flintlock (Damp)', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Musket (One Shot)', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Blunderbuss', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Pepperbox (Overloaded)', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Derringer (Tiny)', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Cap Gun (Sounds Real)', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Water Pistol (Bleach)', weight: 1, element: 'Water', grade: 'F' },
  { label: 'Nerf Gun (Modified)', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Airsoft Pistol (Legal)', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Paintball Marker', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Potato Gun', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Spud Cannon', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Tennis Ball Launcher', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'T-Shirt Cannon', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Confetti Cannon', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Silly String Can', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Fire Extinguisher', weight: 1, element: 'Water', grade: 'F' },
  { label: 'Flamethrower (Small)', weight: 1, element: 'Fire', grade: 'F' },
  { label: 'Smoke Grenade (Decorative)', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Flashbang (Camera Flash)', weight: 1, element: 'Light', grade: 'F' },
  { label: 'Stun Gun (Novelty)', weight: 1, element: 'Lightning', grade: 'F' },
  { label: 'Cattle Prod (Repurposed)', weight: 1, element: 'Lightning', grade: 'F' },
  { label: 'Spork of Destiny', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Couch Cushion Buckler', weight: 1, element: 'Neutral', grade: 'F' },
  { label: 'Frozen Baguette', weight: 1, element: 'Ice', grade: 'F' },
  { label: 'Pool Noodle (Enchanted)', weight: 1, element: 'Water', grade: 'F' },
  { label: 'The Infinite Clipboard', weight: 1, element: 'Neutral', grade: 'F' },
]

// ── Categorized pools — used when weaponType is resolved ──────────────────────
// Each pool is shown on the weapon wheel when that category is selected.

const _noWeapon: SimpleItem[] = [
  { label: 'No Weapon (Unarmed)',           weight: 8, element: 'Neutral', grade: 'D' },
  { label: 'Bare Fists (Technically)',       weight: 4, element: 'Neutral', grade: 'D' },
  { label: 'Just Your Hands (Dramatic)',     weight: 3, element: 'Neutral', grade: 'D' },
  { label: 'The Power of Friendship',        weight: 1, element: 'Neutral', grade: 'D' },
]

const _melee: SimpleItem[] = [
  { label: 'Excalibur',                       weight: 1, element: 'Light', grade: 'SS' },
  { label: 'Durandal',                        weight: 1, element: 'Light', grade: 'SS' },
  { label: 'Kusarigama',                      weight: 1, element: 'Neutral', grade: 'C' },
  { label: 'Void Blade',                      weight: 1, element: 'Void', grade: 'S' },
  { label: 'Dragon\'s Fang',                  weight: 2, element: 'Fire', grade: 'S' },
  { label: 'Thunderclap Hammer',              weight: 2, element: 'Lightning', grade: 'A' },
  { label: 'Runic Greatsword',                weight: 2, element: 'Arcane', grade: 'A' },
  { label: 'Bloodletter',                     weight: 2, element: 'Blood', grade: 'A' },
  { label: 'Abyssal Scythe',                  weight: 2, element: 'Void', grade: 'S' },
  { label: 'Titan\'s Maul',                   weight: 2, element: 'Earth', grade: 'A' },
  { label: 'Phantom Blade',                   weight: 2, element: 'Soul', grade: 'A' },
  { label: 'Voidsteel Katana',                weight: 2, element: 'Void', grade: 'C' },
  { label: 'Mithril Rapier',                  weight: 2, element: 'Metal', grade: 'C' },
  { label: 'Shadowfang',                      weight: 2, element: 'Shadow', grade: 'A' },
  { label: 'Tempest Blade',                   weight: 2, element: 'Lightning', grade: 'C' },
  { label: 'Frostbite Axe',                   weight: 2, element: 'Ice', grade: 'A' },
  { label: 'Godsplitter',                     weight: 1, element: 'Light', grade: 'SS' },
  { label: 'Bloodmoon Scimitar',              weight: 2, element: 'Blood', grade: 'A' },
  { label: 'Titan\'s Greatsword',             weight: 2, element: 'Earth', grade: 'B' },
  { label: 'Iron Sword',                      weight: 4, element: 'Metal', grade: 'D' },
  { label: 'Steel Longsword',                 weight: 4, element: 'Metal', grade: 'D' },
  { label: 'Wooden Club',                     weight: 4, element: 'Neutral', grade: 'D' },
  { label: 'Hand Axe',                        weight: 4, element: 'Neutral', grade: 'D' },
  { label: 'Bronze Spear',                    weight: 3, element: 'Metal', grade: 'D' },
  { label: 'Warhammer',                       weight: 3, element: 'Neutral', grade: 'D' },
  { label: 'Shortdagger',                     weight: 3, element: 'Neutral', grade: 'D' },
  { label: 'Shortsword',                      weight: 3, element: 'Neutral', grade: 'D' },
  { label: 'Gladius',                         weight: 3, element: 'Neutral', grade: 'D' },
  { label: 'Kopis',                           weight: 3, element: 'Neutral', grade: 'D' },
  { label: 'Falchion',                        weight: 3, element: 'Neutral', grade: 'D' },
  { label: 'Broadsword',                      weight: 3, element: 'Neutral', grade: 'D' },
  { label: 'Claymore',                        weight: 3, element: 'Neutral', grade: 'D' },
  { label: 'Bastard Sword',                   weight: 3, element: 'Neutral', grade: 'D' },
  { label: 'Estoc (Thrusting Sword)',         weight: 3, element: 'Neutral', grade: 'D' },
  { label: 'Saber',                           weight: 3, element: 'Neutral', grade: 'D' },
  { label: 'Katana',                          weight: 3, element: 'Neutral', grade: 'D' },
  { label: 'Nodachi',                         weight: 2, element: 'Neutral', grade: 'D' },
  { label: 'Naginata',                        weight: 2, element: 'Neutral', grade: 'D' },
  { label: 'Halberd',                         weight: 2, element: 'Neutral', grade: 'D' },
  { label: 'Glaive',                          weight: 2, element: 'Neutral', grade: 'D' },
  { label: 'Partisan',                        weight: 2, element: 'Neutral', grade: 'D' },
  { label: 'War Scythe',                      weight: 2, element: 'Neutral', grade: 'D' },
  { label: 'Flail',                           weight: 2, element: 'Neutral', grade: 'D' },
  { label: 'Morning Star',                    weight: 2, element: 'Neutral', grade: 'D' },
  { label: 'Mace',                            weight: 3, element: 'Neutral', grade: 'D' },
  { label: 'Maul',                            weight: 2, element: 'Neutral', grade: 'D' },
  { label: 'Battle Axe',                      weight: 3, element: 'Neutral', grade: 'D' },
  { label: 'Great Axe',                       weight: 2, element: 'Neutral', grade: 'D' },
  { label: 'Trident',                         weight: 2, element: 'Neutral', grade: 'D' },
  { label: 'War Lance',                       weight: 2, element: 'Neutral', grade: 'D' },
  { label: 'Natural Claws (Retractable)',      weight: 2, element: 'Neutral', grade: 'D' },
  { label: 'Bone Club (Self-Made)',            weight: 2, element: 'Neutral', grade: 'D' },
  { label: 'Rolling Pin (Oak, Heavy)',         weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Cast Iron Skillet',               weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Baseball Bat',                    weight: 3, element: 'Neutral', grade: 'D' },
  { label: 'Cricket Bat',                     weight: 3, element: 'Neutral', grade: 'D' },
  { label: 'Shovel',                          weight: 3, element: 'Neutral', grade: 'D' },
  { label: 'Frying Pan (Heavy)',              weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Wrench (Large)',                  weight: 3, element: 'Metal', grade: 'D' },
  { label: 'Crowbar',                         weight: 3, element: 'Metal', grade: 'D' },
  { label: 'Pipe (Lead)',                     weight: 3, element: 'Metal', grade: 'D' },
  { label: 'Improvised Club',                 weight: 3, element: 'Neutral', grade: 'D' },
  { label: 'A Rock (Unspecified)',            weight: 3, element: 'Neutral', grade: 'D' },
  { label: 'Slightly Bigger Rock',            weight: 3, element: 'Neutral', grade: 'D' },
]

const _ranged: SimpleItem[] = [
  { label: 'Mjolnir',                         weight: 1, element: 'Lightning', grade: 'SS' },
  { label: 'Gungnir',                         weight: 1, element: 'Wind', grade: 'SS' },
  { label: 'Seraphic Lance',                  weight: 1, element: 'Light', grade: 'S' },
  { label: 'Starfall Javelin',                weight: 1, element: 'Cosmic', grade: 'A' },
  { label: 'Sunfire Bow',                     weight: 2, element: 'Light', grade: 'A' },
  { label: 'Stardust Bow',                    weight: 2, element: 'Cosmic', grade: 'C' },
  { label: 'Voidcaller Bow',                  weight: 2, element: 'Void', grade: 'A' },
  { label: 'Hellfire Crossbow',               weight: 2, element: 'Fire', grade: 'A' },
  { label: 'Leviathan Scale Bow',             weight: 2, element: 'Nature', grade: 'B' },
  { label: 'Legendary Bow',                   weight: 2, element: 'Neutral', grade: 'C' },
  { label: 'Ranger\'s Heartseeker Bow',       weight: 2, element: 'Neutral', grade: 'A' },
  { label: 'Ziz Feather Arrows',              weight: 2, element: 'Wind', grade: 'B' },
  { label: 'Shortbow',                        weight: 4, element: 'Neutral', grade: 'D' },
  { label: 'Longbow',                         weight: 4, element: 'Neutral', grade: 'D' },
  { label: 'Recurve Bow',                     weight: 3, element: 'Neutral', grade: 'D' },
  { label: 'War Bow',                         weight: 3, element: 'Neutral', grade: 'D' },
  { label: 'Composite Bow',                   weight: 3, element: 'Neutral', grade: 'D' },
  { label: 'Crossbow',                        weight: 3, element: 'Neutral', grade: 'D' },
  { label: 'Heavy Crossbow',                  weight: 3, element: 'Neutral', grade: 'D' },
  { label: 'Light Crossbow',                  weight: 3, element: 'Neutral', grade: 'D' },
  { label: 'Repeating Crossbow',              weight: 2, element: 'Neutral', grade: 'D' },
  { label: 'Hand Crossbow',                   weight: 2, element: 'Neutral', grade: 'D' },
  { label: 'Sling',                           weight: 3, element: 'Neutral', grade: 'D' },
  { label: 'Javelin',                         weight: 3, element: 'Neutral', grade: 'D' },
  { label: 'Throwing Axe',                    weight: 3, element: 'Neutral', grade: 'D' },
  { label: 'Throwing Knife',                  weight: 3, element: 'Neutral', grade: 'D' },
  { label: 'Shuriken',                        weight: 3, element: 'Neutral', grade: 'D' },
  { label: 'Kunai',                           weight: 3, element: 'Neutral', grade: 'D' },
  { label: 'Flintlock Pistol',               weight: 3, element: 'Neutral', grade: 'D' },
  { label: 'Musket',                          weight: 2, element: 'Neutral', grade: 'D' },
  { label: 'Revolver',                        weight: 3, element: 'Neutral', grade: 'D' },
  { label: 'Semi-Auto Pistol',               weight: 3, element: 'Neutral', grade: 'D' },
  { label: 'Shotgun',                         weight: 3, element: 'Neutral', grade: 'D' },
  { label: 'Rifle',                           weight: 3, element: 'Neutral', grade: 'D' },
  { label: 'Sniper Rifle',                    weight: 2, element: 'Neutral', grade: 'D' },
  { label: 'Submachine Gun',                  weight: 2, element: 'Neutral', grade: 'D' },
  { label: 'Assault Rifle',                   weight: 2, element: 'Neutral', grade: 'D' },
  { label: 'Rocket Launcher',                 weight: 1, element: 'Fire', grade: 'C' },
  { label: 'Railgun',                         weight: 1, element: 'Metal', grade: 'C' },
  { label: 'Neutrino Railgun',                weight: 1, element: 'Cosmic', grade: 'A' },
  { label: 'The Last Word (Firearm)',          weight: 1, element: 'Neutral', grade: 'SS' },
  { label: 'Boomerang (Actually Returns)',    weight: 2, element: 'Neutral', grade: 'D' },
  { label: 'Sling (Elastic Band, Large)',      weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Potato Gun',                      weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'T-Shirt Cannon',                  weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Nerf Gun (Modified)',             weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Water Pistol (Bleach)',           weight: 2, element: 'Water', grade: 'F' },
  { label: 'Confetti Cannon',                 weight: 3, element: 'Neutral', grade: 'F' },
]

const _magical: SimpleItem[] = [
  { label: 'Stormcaller Staff',               weight: 2, element: 'Lightning', grade: 'A' },
  { label: 'Necromancer\'s Staff',            weight: 2, element: 'Arcane', grade: 'C' },
  { label: 'Druid\'s Nature Staff',           weight: 2, element: 'Nature', grade: 'B' },
  { label: 'Oracle\'s Rod',                   weight: 2, element: 'Arcane', grade: 'C' },
  { label: 'Arcanite Wand',                   weight: 2, element: 'Arcane', grade: 'C' },
  { label: 'Medusa\'s Gaze Wand',             weight: 2, element: 'Nature', grade: 'B' },
  { label: 'Basilisk Eye Staff',              weight: 2, element: 'Nature', grade: 'B' },
  { label: 'Epic Wand',                       weight: 2, element: 'Arcane', grade: 'C' },
  { label: 'Mage\'s Arcane Focus',            weight: 2, element: 'Arcane', grade: 'B' },
  { label: 'Sorcerer\'s Power Conduit',       weight: 2, element: 'Arcane', grade: 'B' },
  { label: 'Warlock\'s Grimoire (Weaponised)', weight: 2, element: 'Arcane', grade: 'C' },
  { label: 'Warlock\'s Pact Blade',           weight: 2, element: 'Arcane', grade: 'A' },
  { label: 'Cleric\'s Divine Rod',            weight: 2, element: 'Light', grade: 'B' },
  { label: 'Spellblade',                      weight: 2, element: 'Arcane', grade: 'C' },
  { label: 'Bard\'s Instrument of War',       weight: 2, element: 'Sound', grade: 'B' },
  { label: 'Heaven\'s Fury',                  weight: 1, element: 'Light', grade: 'SS' },
  { label: 'Hell\'s Wrath',                   weight: 1, element: 'Fire', grade: 'S' },
  { label: 'War Hymn Blade',                  weight: 2, element: 'Neutral', grade: 'C' },
  { label: 'Prophecy Sword',                  weight: 2, element: 'Arcane', grade: 'S' },
  { label: 'Sigil Spear',                     weight: 2, element: 'Arcane', grade: 'C' },
  { label: 'Enchanted Longbow',               weight: 2, element: 'Arcane', grade: 'C' },
  { label: 'Blessed Mace',                    weight: 2, element: 'Light', grade: 'C' },
  { label: 'Rune-etched Battleaxe',           weight: 2, element: 'Arcane', grade: 'C' },
  { label: 'Arcane Shortsword',               weight: 2, element: 'Arcane', grade: 'C' },
  { label: 'Luminous Rapier',                 weight: 2, element: 'Light', grade: 'B' },
  { label: 'Radiant Sword',                   weight: 2, element: 'Light', grade: 'A' },
  { label: 'Spirit Blade',                    weight: 2, element: 'Soul', grade: 'B' },
  { label: 'Phoenix Feather Blade',           weight: 2, element: 'Light', grade: 'A' },
  { label: 'Paladin\'s Holy Avenger',         weight: 2, element: 'Light', grade: 'A' },
  { label: 'Charm-Forged Flail',              weight: 2, element: 'Arcane', grade: 'B' },
  { label: 'Imbued Morning Star',             weight: 2, element: 'Arcane', grade: 'B' },
  { label: 'Crystal Ball (Solid)',            weight: 2, element: 'Arcane', grade: 'B' },
  { label: 'Psionic Blade',                   weight: 2, element: 'Psychic', grade: 'B' },
  { label: 'Mind Saber',                      weight: 2, element: 'Psychic', grade: 'B' },
  { label: 'Conviction Sword',                weight: 2, element: 'Light', grade: 'B' },
  { label: 'Faith Lance',                     weight: 2, element: 'Light', grade: 'B' },
  { label: 'Hope Blade',                      weight: 2, element: 'Light', grade: 'B' },
  { label: 'Love Sword (Terrifyingly Effective)', weight: 2, element: 'Neutral', grade: 'B' },
  { label: 'A Very Loud Voice (Weaponised)',  weight: 2, element: 'Sound', grade: 'F' },
  { label: 'Disappointment (Manifested)',     weight: 2, element: 'Neutral', grade: 'F' },
  { label: 'Fear Manifestation Blade',        weight: 2, element: 'Psychic', grade: 'B' },
  { label: 'Dream Cutter',                    weight: 2, element: 'Psychic', grade: 'B' },
  { label: 'Memory Sword',                    weight: 2, element: 'Psychic', grade: 'B' },
  { label: 'Will Blade',                      weight: 2, element: 'Psychic', grade: 'B' },
  { label: 'Sheer Audacity (Focused)',        weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Chrono Blade',                    weight: 2, element: 'Time', grade: 'A' },
  { label: 'Reality Cutter',                  weight: 1, element: 'Chaos', grade: 'SSS' },
  { label: 'Entropy Sword',                   weight: 1, element: 'Void', grade: 'SSS' },
  { label: 'Dimensional Edge',                weight: 1, element: 'Void', grade: 'S' },
  { label: 'Cosmic Lance',                    weight: 1, element: 'Cosmic', grade: 'S' },
]

const _exotic: SimpleItem[] = [
  { label: 'Ethereal Whip',                   weight: 2, element: 'Arcane', grade: 'A' },
  { label: 'Inquisitor\'s Flame Whip',        weight: 2, element: 'Fire', grade: 'B' },
  { label: 'Micro-filament Whip',             weight: 2, element: 'Metal', grade: 'C' },
  { label: 'Cerberus Chain',                  weight: 2, element: 'Nature', grade: 'A' },
  { label: 'Kraken Tentacle',                 weight: 2, element: 'Nature', grade: 'B' },
  { label: 'Golem Arm',                       weight: 2, element: 'Metal', grade: 'C' },
  { label: 'Automaton Fist',                  weight: 2, element: 'Metal', grade: 'C' },
  { label: 'Construct Cannon',                weight: 2, element: 'Metal', grade: 'C' },
  { label: 'Mechanical Spider Blade',         weight: 2, element: 'Metal', grade: 'C' },
  { label: 'Steam-Powered Mace',              weight: 2, element: 'Metal', grade: 'C' },
  { label: 'Aether Cannon',                   weight: 2, element: 'Arcane', grade: 'C' },
  { label: 'Plasma Cutter',                   weight: 2, element: 'Fire', grade: 'B' },
  { label: 'Photon Blade',                    weight: 2, element: 'Light', grade: 'B' },
  { label: 'Graviton Hammer',                 weight: 2, element: 'Gravity', grade: 'A' },
  { label: 'Singularity Gun',                 weight: 1, element: 'Gravity', grade: 'S' },
  { label: 'Vibro-sword',                     weight: 2, element: 'Metal', grade: 'B' },
  { label: 'Sonic Disruptor',                 weight: 2, element: 'Sound', grade: 'B' },
  { label: 'Nano-blade',                      weight: 2, element: 'Metal', grade: 'B' },
  { label: 'Quantum Saber',                   weight: 2, element: 'Cosmic', grade: 'A' },
  { label: 'Monomolecular Blade',             weight: 2, element: 'Metal', grade: 'B' },
  { label: 'Artificer\'s Mechanical Arm',    weight: 2, element: 'Metal', grade: 'C' },
  { label: 'Dragon\'s Claw Gauntlets',        weight: 2, element: 'Fire', grade: 'A' },
  { label: 'Griffin Talon',                   weight: 2, element: 'Nature', grade: 'A' },
  { label: 'Chimera Fang',                    weight: 2, element: 'Nature', grade: 'B' },
  { label: 'Energy Rifle',                    weight: 2, element: 'Arcane', grade: 'B' },
  { label: 'Fusion Lance',                    weight: 1, element: 'Cosmic', grade: 'A' },
  { label: 'Umbrella (Pointy End First)',     weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Fire Extinguisher',              weight: 3, element: 'Water', grade: 'F' },
  { label: 'Flamethrower (Small)',            weight: 3, element: 'Fire', grade: 'F' },
  { label: 'Grandma\'s Slipper',             weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Frozen Fish',                     weight: 3, element: 'Water', grade: 'F' },
  { label: 'Pool Noodle',                     weight: 3, element: 'Water', grade: 'F' },
  { label: 'Traffic Cone',                    weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Cactus (Potted, Unprotected)',    weight: 3, element: 'Nature', grade: 'F' },
  { label: 'Le Creuset Dutch Oven',           weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Wok (With Residual Heat)',        weight: 3, element: 'Fire', grade: 'F' },
  { label: 'Immersion Blender (Running)',     weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Leaf Blower (Petrol)',            weight: 3, element: 'Wind', grade: 'F' },
  { label: 'Novelty Giant Inflatable Hammer', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Toilet Plunger',                  weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Broom',                           weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Just a Stick, Really',            weight: 3, element: 'Neutral', grade: 'D' },
  { label: 'Literally a Wet Noodle',          weight: 3, element: 'Water', grade: 'F' },
  { label: 'The Entire Environment as a Weapon', weight: 2, element: 'Neutral', grade: 'F' },
  { label: 'Blue Screen of Death',            weight: 2, element: 'Neutral', grade: 'F' },
  { label: 'CAPTCHA of Doom',                 weight: 2, element: 'Neutral', grade: 'F' },
  { label: 'Unskippable Pre-Roll Ad',         weight: 2, element: 'Neutral', grade: 'F' },
  { label: 'Error 404',                       weight: 2, element: 'Neutral', grade: 'F' },
  { label: 'Loading Spinner (Forever)',        weight: 2, element: 'Neutral', grade: 'F' },
  { label: 'Paperweight (Suspicious)',         weight: 2, element: 'Neutral', grade: 'F' },
  { label: 'Rubber Band Ball',                weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Overdue Library Book',            weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Strongly Worded Tweet (Printed)', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'An Embarrassing Photo',           weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Outstanding Debt (Manifested)',   weight: 2, element: 'Neutral', grade: 'F' },
  { label: 'The Bill (Final Reminder)',        weight: 2, element: 'Neutral', grade: 'F' },
]

const _cursed: SimpleItem[] = [
  { label: 'Hexblade',                        weight: 3, element: 'Arcane', grade: 'C' },
  { label: 'Cursed Claymore',                 weight: 3, element: 'Shadow', grade: 'C' },
  { label: 'Deathwhisper',                    weight: 2, element: 'Void', grade: 'S' },
  { label: 'Soulreaver',                      weight: 2, element: 'Soul', grade: 'S' },
  { label: 'Hell\'s Wrath',                   weight: 2, element: 'Fire', grade: 'S' },
  { label: 'War Scythe of Endings',           weight: 2, element: 'Soul', grade: 'S' },
  { label: 'Reaping Hook',                    weight: 2, element: 'Blood', grade: 'B' },
  { label: 'Harvest Blade',                   weight: 2, element: 'Blood', grade: 'B' },
  { label: 'Ghost Sword',                     weight: 2, element: 'Soul', grade: 'B' },
  { label: 'Wraith Scythe',                   weight: 2, element: 'Soul', grade: 'B' },
  { label: 'Banshee\'s Wail Spear',           weight: 2, element: 'Soul', grade: 'A' },
  { label: 'Lich\'s Phylactery Staff',        weight: 2, element: 'Soul', grade: 'A' },
  { label: 'Vampire\'s Bloodblade',           weight: 2, element: 'Blood', grade: 'B' },
  { label: 'Necromancer\'s Deathscythe',      weight: 2, element: 'Soul', grade: 'S' },
  { label: 'Dark Knight\'s Hell Edge',        weight: 2, element: 'Fire', grade: 'B' },
  { label: 'Death Knight\'s Runeblade',       weight: 2, element: 'Soul', grade: 'A' },
  { label: 'Blood Knight\'s Crimson Blade',   weight: 2, element: 'Blood', grade: 'B' },
  { label: 'Chaos Knight\'s Fractal Sword',   weight: 2, element: 'Chaos', grade: 'B' },
  { label: 'Void Knight\'s Nothing Blade',    weight: 2, element: 'Void', grade: 'S' },
  { label: 'Soul Splitter',                   weight: 2, element: 'Soul', grade: 'S' },
  { label: 'Darkmatter Blade',                weight: 2, element: 'Void', grade: 'S' },
  { label: 'Chaos Blade',                     weight: 2, element: 'Chaos', grade: 'SSS' },
  { label: 'Eclipse Blade',                   weight: 2, element: 'Shadow', grade: 'S' },
  { label: 'Despair Scythe',                  weight: 2, element: 'Psychic', grade: 'B' },
  { label: 'Doubt Dagger',                    weight: 2, element: 'Psychic', grade: 'B' },
  { label: 'Nightmare Scythe',                weight: 2, element: 'Psychic', grade: 'B' },
  { label: 'Darkmatter Blade',                weight: 2, element: 'Void', grade: 'S' },
  { label: 'Umbral Dagger',                   weight: 2, element: 'Shadow', grade: 'B' },
  { label: 'Soul Knight\'s Ecto-Blade',       weight: 2, element: 'Soul', grade: 'B' },
  { label: 'Mind Knight\'s Psi-Blade',        weight: 2, element: 'Psychic', grade: 'B' },
  { label: 'Werewolf\'s Silver-Proof Claw',   weight: 2, element: 'Nature', grade: 'B' },
  { label: 'Hydra Spine Blade',               weight: 2, element: 'Nature', grade: 'B' },
  { label: 'Doom Blade (Foretold)',           weight: 1, element: 'Void', grade: 'S' },
  { label: 'The Last Word (Foretold)',        weight: 1, element: 'Neutral', grade: 'SS' },
  { label: 'Inherited Grudge Blade',          weight: 2, element: 'Shadow', grade: 'B' },
  { label: 'Receipt from 2009',               weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Parking Ticket (Stamped)',        weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Accumulated Late Fees',           weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Mounting Interest',               weight: 2, element: 'Neutral', grade: 'F' },
]

const _ancient: SimpleItem[] = [
  { label: 'Excalibur',                       weight: 1, element: 'Light', grade: 'SS' },
  { label: 'Mjolnir',                         weight: 1, element: 'Lightning', grade: 'SS' },
  { label: 'Gungnir',                         weight: 1, element: 'Wind', grade: 'SS' },
  { label: 'Durandal',                        weight: 1, element: 'Light', grade: 'SS' },
  { label: 'Joyeuse',                         weight: 1, element: 'Light', grade: 'SS' },
  { label: 'Worldrend',                       weight: 1, element: 'Chaos', grade: 'SS' },
  { label: 'Godsplitter',                     weight: 1, element: 'Light', grade: 'SS' },
  { label: 'Fate\'s Edge',                    weight: 1, element: 'Arcane', grade: 'S' },
  { label: 'Eternal Edge',                    weight: 1, element: 'Neutral', grade: 'C' },
  { label: 'Ancient Halberd',                 weight: 2, element: 'Neutral', grade: 'C' },
  { label: 'Primordial Glaive',               weight: 2, element: 'Neutral', grade: 'SS' },
  { label: 'Archaic Warhammer',               weight: 2, element: 'Neutral', grade: 'C' },
  { label: 'Ancestral Blade',                 weight: 2, element: 'Neutral', grade: 'C' },
  { label: 'Heirloom Sword',                  weight: 2, element: 'Neutral', grade: 'C' },
  { label: 'Relic Blade',                     weight: 2, element: 'Neutral', grade: 'C' },
  { label: 'Artifact Sword',                  weight: 2, element: 'Neutral', grade: 'C' },
  { label: 'Mythic Spear',                    weight: 2, element: 'Neutral', grade: 'C' },
  { label: 'Fabled Dagger',                   weight: 2, element: 'Neutral', grade: 'C' },
  { label: 'Storied Axe',                     weight: 2, element: 'Neutral', grade: 'C' },
  { label: 'Champion\'s Blade',               weight: 2, element: 'Neutral', grade: 'C' },
  { label: 'Conqueror\'s Axe',                weight: 2, element: 'Metal', grade: 'C' },
  { label: 'Destroyer\'s Hammer',             weight: 2, element: 'Metal', grade: 'C' },
  { label: 'Paladin\'s Holy Avenger',         weight: 2, element: 'Light', grade: 'A' },
  { label: 'Guardian\'s Spear',               weight: 2, element: 'Neutral', grade: 'C' },
  { label: 'Protector\'s Shield (as Weapon)', weight: 2, element: 'Neutral', grade: 'C' },
  { label: 'Phoenix Feather Blade',           weight: 1, element: 'Light', grade: 'A' },
  { label: 'Unicorn Horn Lance',              weight: 1, element: 'Light', grade: 'A' },
  { label: 'Dragon\'s Fang (First Generation)', weight: 1, element: 'Fire', grade: 'S' },
  { label: 'Void Blade (Pre-Creation)',       weight: 1, element: 'Void', grade: 'S' },
  { label: 'Time Knight\'s Paradox Sword',   weight: 1, element: 'Time', grade: 'S' },
  { label: 'Cosmic Lance',                    weight: 1, element: 'Cosmic', grade: 'S' },
  { label: 'The First Tool (Prehistoric)',    weight: 1, element: 'Neutral', grade: 'D' },
  { label: 'Sky Knight\'s Aerial Spear',      weight: 2, element: 'Wind', grade: 'B' },
  { label: 'Star Knight\'s Celestial Edge',   weight: 1, element: 'Light', grade: 'A' },
  { label: 'Templar\'s Crusader Blade',       weight: 2, element: 'Light', grade: 'B' },
  { label: 'Orichalcum Trident',              weight: 1, element: 'Metal', grade: 'C' },
  { label: 'Adamantine Greatsword',           weight: 1, element: 'Metal', grade: 'B' },
  { label: 'Sundering Spear',                 weight: 2, element: 'Wind', grade: 'B' },
  { label: 'Earthshaker Hammer',              weight: 2, element: 'Earth', grade: 'B' },
  { label: 'Skyrender Axe',                   weight: 2, element: 'Wind', grade: 'B' },
]

export const weaponsByCategory: Record<string, SimpleItem[]> = {
  'None':    _noWeapon,
  'Melee':   _melee,
  'Ranged':  _ranged,
  'Magical': _magical,
  'Exotic':  _exotic,
  'Cursed':  _cursed,
  'Ancient': _ancient,
}
