import type { FlavorLabel } from './types'

export const weaponMasteryLabels: FlavorLabel[] = [
  { label: 'Holds Weapon Backwards',              weight: 4, tier: 'F-',   score: 2,   color: '#555'    },
  { label: "Hasn't Hurt Themselves Yet",          weight: 4, tier: 'F',    score: 5,   color: '#666'    },
  { label: 'Swings in the Right Direction',       weight: 4, tier: 'F+',   score: 8,   color: '#777'    },
  { label: 'Basic Proficiency',                   weight: 6, tier: 'E-',   score: 11,  color: '#6b7280' },
  { label: 'Handles a Weapon Adequately',         weight: 6, tier: 'E',    score: 14,  color: '#9ca3af' },
  { label: 'Regular Combatant Caliber',           weight: 6, tier: 'E+',   score: 17,  color: '#d1d5db' },
  { label: 'Skilled Soldier Level',               weight: 8, tier: 'D-',   score: 20,  color: '#92400e' },
  { label: 'Weapon of Choice Mastered',           weight: 8, tier: 'D',    score: 23,  color: '#b45309' },
  { label: 'Multi-Weapon Versatility',            weight: 8, tier: 'D+',   score: 26,  color: '#d97706' },
  { label: 'Legendary Swordsman Class',           weight: 8, tier: 'C-',   score: 30,  color: '#1d4ed8' },
  { label: 'Tournament Champion',                 weight: 8, tier: 'C',    score: 34,  color: '#2563eb' },
  { label: 'Weapon Becomes an Extension of Self', weight: 8, tier: 'C+',   score: 38,  color: '#3b82f6' },
  { label: 'Weapon Creates Shockwaves',           weight: 7, tier: 'B-',   score: 42,  color: '#065f46' },
  { label: 'Defeats Armed Forces Alone',          weight: 7, tier: 'B',    score: 47,  color: '#059669' },
  { label: 'Technique That Defies Physics',       weight: 7, tier: 'B+',   score: 52,  color: '#34d399' },
  { label: 'Creates Art With Combat',             weight: 5, tier: 'A-',   score: 57,  color: '#7c3aed' },
  { label: 'No Defense Can Block It',             weight: 5, tier: 'A',    score: 62,  color: '#8b5cf6' },
  { label: 'Weapon and Wielder Are One',          weight: 5, tier: 'A+',   score: 67,  color: '#a78bfa' },
  { label: 'Technique Alters the Battlefield',    weight: 4, tier: 'S-',   score: 72,  color: '#b91c1c' },
  { label: 'The Weapon Fears Disappointing Them', weight: 4, tier: 'S',    score: 77,  color: '#dc2626' },
  { label: 'Could Kill a God With This',          weight: 4, tier: 'S+',   score: 81,  color: '#ef4444' },
  { label: 'Strikes That Bend Space',             weight: 3, tier: 'SS-',  score: 85,  color: '#ea580c' },
  { label: 'Weapon Transcends Physical Form',     weight: 3, tier: 'SS',   score: 88,  color: '#f97316' },
  { label: 'Strikes That Exist Outside Time',     weight: 3, tier: 'SS+',  score: 91,  color: '#fb923c' },
  { label: 'Weapon Is Now a Principle of Combat',          weight: 2, tier: 'SSS-',      score: 94,  color: '#ca8a04' },
  { label: 'Cannot Miss. Ever.',                           weight: 2, tier: 'SSS',       score: 97,  color: '#eab308' },
  { label: 'The Blow Lands Before It Is Thrown',           weight: 2, tier: 'SSS+',      score: 99,  color: '#fde047' },
  { label: 'Technique Recognized by Other Dimensions',     weight: 2, tier: 'Z-',        score: 101, color: '#0e7490' },
  { label: 'Strikes That Land Across Timelines',           weight: 2, tier: 'Z',         score: 103, color: '#0891b2' },
  { label: 'Every Swing Ends a Possibility',               weight: 2, tier: 'Z+',        score: 105, color: '#06b6d4' },
  { label: 'The Weapon Has Achieved Enlightenment',        weight: 1, tier: 'ZZ-',       score: 107, color: '#3730a3' },
  { label: 'Mastery That Defies All Known Combat Styles',  weight: 1, tier: 'ZZ',        score: 109, color: '#4f46e5' },
  { label: 'The Weapon Has Its Own Gravity',               weight: 1, tier: 'ZZ+',       score: 111, color: '#818cf8' },
  { label: 'Cannot Be Described by Any Fighting Style',    weight: 1, tier: 'ZZZ-',      score: 113, color: '#9d174d' },
  { label: 'The Blow Transcends the Moment of Delivery',   weight: 1, tier: 'ZZZ',       score: 115, color: '#be185d' },
  { label: 'Strikes That Unmake What They Touch',          weight: 1, tier: 'ZZZ+',      score: 117, color: '#ec4899' },
  { label: 'Weapon Technique Guided by Divine Intent',     weight: 1, tier: 'Celestial-',score: 119, color: '#075985' },
  { label: 'Strikes That Carry Celestial Weight',          weight: 1, tier: 'Celestial', score: 121, color: '#0284c7' },
  { label: 'Even Gods Step Back When the Weapon Is Drawn', weight: 1, tier: 'Celestial+',score: 123, color: '#38bdf8' },
  { label: 'A Technique That Changes Everything It Touches',weight: 1, tier: 'Godly-',   score: 125, color: '#c026d3' },
  { label: 'Casually Slices Causality',                    weight: 1, tier: 'Godly',     score: 127, color: '#e879f9' },
  { label: 'Was Wielding Before Weapons Were Invented',    weight: 1, tier: 'Primordial',score: 130, color: '#ffffff' },
]
