// weapons.ts — Weapons content pool for Wheel of Fate.
// 500 total: God×10, SSS×20, SS×30, S×40, A×50, B×60, C×70, D×70, E×70, F×80
// All entries have element and grade fields.

import type { SimpleItem } from './types'

export const weapons: SimpleItem[] = [

  // ── GOD TIER (10) — Weapons of absolute, world-ending power ──
  { label: 'The Sword of Creation', weight: 1, element: 'Cosmic', grade: 'God' },
  { label: 'Excalibur Ultima', weight: 1, element: 'Light', grade: 'God' },
  { label: 'Mjolnir (True Form)', weight: 1, element: 'Lightning', grade: 'God' },
  { label: 'The Spear of Destiny', weight: 1, element: 'Light', grade: 'God' },
  { label: 'Ragnarok (The End Blade)', weight: 1, element: 'Chaos', grade: 'God' },
  { label: 'Kusarigama of Fate', weight: 1, element: 'Time', grade: 'God' },
  { label: 'The First Flame (Weapon)', weight: 1, element: 'Fire', grade: 'God' },
  { label: 'Void Eater', weight: 1, element: 'Void', grade: 'God' },
  { label: 'Primordial Darkness Blade', weight: 1, element: 'Shadow', grade: 'God' },
  { label: 'The Endless Arrow', weight: 1, element: 'Cosmic', grade: 'God' },

  // ── SSS TIER (20) — Legendary mythical weapons ──
  { label: 'Excalibur', weight: 1, element: 'Light', grade: 'SSS' },
  { label: 'Mjolnir', weight: 1, element: 'Lightning', grade: 'SSS' },
  { label: 'Gungnir', weight: 1, element: 'Wind', grade: 'SSS' },
  { label: 'Durandal', weight: 1, element: 'Light', grade: 'SSS' },
  { label: 'Tyrfing (The Cursed Blade)', weight: 1, element: 'Shadow', grade: 'SSS' },
  { label: 'Joyeuse', weight: 1, element: 'Light', grade: 'SSS' },
  { label: 'Gáe Bulg', weight: 1, element: 'Blood', grade: 'SSS' },
  { label: 'Caladbolg', weight: 1, element: 'Arcane', grade: 'SSS' },
  { label: 'Godsplitter', weight: 1, element: 'Light', grade: 'SSS' },
  { label: 'Worldrend', weight: 1, element: 'Chaos', grade: 'SSS' },
  { label: 'Deathwhisper', weight: 1, element: 'Void', grade: 'SSS' },
  { label: 'Fragarach (The Answerer)', weight: 1, element: 'Wind', grade: 'SSS' },
  { label: 'Harpe (God-Slayer)', weight: 1, element: 'Metal', grade: 'SSS' },
  { label: 'Gandiva (Divine Bow)', weight: 1, element: 'Cosmic', grade: 'SSS' },
  { label: 'Ruyi Jingu Bang', weight: 1, element: 'Earth', grade: 'SSS' },
  { label: 'Kusarigama of Shadows', weight: 1, element: 'Shadow', grade: 'SSS' },
  { label: 'Heaven-Piercer Lance', weight: 1, element: 'Light', grade: 'SSS' },
  { label: 'Soul Reaper\'s Scythe', weight: 1, element: 'Soul', grade: 'SSS' },
  { label: 'Eternal Oblivion Blade', weight: 1, element: 'Void', grade: 'SSS' },
  { label: 'The Dragon Slayer', weight: 1, element: 'Fire', grade: 'SSS' },

  // ── SS TIER (30) — Exceptional mythical weapons ──
  { label: 'Void Blade', weight: 1, element: 'Void', grade: 'SS' },
  { label: 'Seraphic Lance', weight: 1, element: 'Light', grade: 'SS' },
  { label: 'Dragon\'s Fang', weight: 1, element: 'Fire', grade: 'SS' },
  { label: 'Soulreaver', weight: 1, element: 'Soul', grade: 'SS' },
  { label: 'Abyssal Scythe', weight: 1, element: 'Void', grade: 'SS' },
  { label: 'Celestial Greatsword', weight: 1, element: 'Cosmic', grade: 'SS' },
  { label: 'Reaper\'s Edge', weight: 1, element: 'Shadow', grade: 'SS' },
  { label: 'Star Forge Hammer', weight: 1, element: 'Cosmic', grade: 'SS' },
  { label: 'Blood Moon Scythe', weight: 1, element: 'Blood', grade: 'SS' },
  { label: 'Titan\'s Wrath', weight: 1, element: 'Earth', grade: 'SS' },
  { label: 'Glacier Splitter', weight: 1, element: 'Ice', grade: 'SS' },
  { label: 'Stormborn Greatsword', weight: 1, element: 'Lightning', grade: 'SS' },
  { label: 'Hellfire Blade', weight: 1, element: 'Fire', grade: 'SS' },
  { label: 'Wraithbane', weight: 1, element: 'Soul', grade: 'SS' },
  { label: 'Cosmic Rift Blade', weight: 1, element: 'Cosmic', grade: 'SS' },
  { label: 'The Nightbringer', weight: 1, element: 'Shadow', grade: 'SS' },
  { label: 'Thundergod\'s Hammer', weight: 1, element: 'Lightning', grade: 'SS' },
  { label: 'Frostpeak Spear', weight: 1, element: 'Ice', grade: 'SS' },
  { label: 'Phantom Sword', weight: 1, element: 'Soul', grade: 'SS' },
  { label: 'Arcane Obliterator', weight: 1, element: 'Arcane', grade: 'SS' },
  { label: 'Nature\'s Wrath Staff', weight: 1, element: 'Nature', grade: 'SS' },
  { label: 'Venomfang Dagger', weight: 1, element: 'Poison', grade: 'SS' },
  { label: 'Time Rend Blade', weight: 1, element: 'Time', grade: 'SS' },
  { label: 'Gravity Cannon', weight: 1, element: 'Gravity', grade: 'SS' },
  { label: 'Psychic Shatter Orb', weight: 1, element: 'Psychic', grade: 'SS' },
  { label: 'Sound Shredder', weight: 1, element: 'Sound', grade: 'SS' },
  { label: 'Blood Throne Sword', weight: 1, element: 'Blood', grade: 'SS' },
  { label: 'Soul Forge Axe', weight: 1, element: 'Soul', grade: 'SS' },
  { label: 'Chaos Incarnate Blade', weight: 1, element: 'Chaos', grade: 'SS' },
  { label: 'Eternal Darkness Bow', weight: 1, element: 'Shadow', grade: 'SS' },

  // ── S TIER (40) — Mythic-grade weapons ──
  { label: 'Shadowmeld Dagger', weight: 1, element: 'Shadow', grade: 'S' },
  { label: 'Thunderclap Hammer', weight: 1, element: 'Lightning', grade: 'S' },
  { label: 'Sunfire Bow', weight: 1, element: 'Light', grade: 'S' },
  { label: 'Runic Greatsword', weight: 1, element: 'Arcane', grade: 'S' },
  { label: 'Ethereal Whip', weight: 1, element: 'Arcane', grade: 'S' },
  { label: 'Bloodletter', weight: 1, element: 'Blood', grade: 'S' },
  { label: 'Starfall Javelin', weight: 1, element: 'Cosmic', grade: 'S' },
  { label: 'Moonblade', weight: 1, element: 'Cosmic', grade: 'S' },
  { label: 'Stormcaller Staff', weight: 1, element: 'Lightning', grade: 'S' },
  { label: 'Frostbite Axe', weight: 1, element: 'Ice', grade: 'S' },
  { label: 'Hellfire Crossbow', weight: 1, element: 'Fire', grade: 'S' },
  { label: 'Celestial Spear', weight: 1, element: 'Light', grade: 'S' },
  { label: 'Titan\'s Maul', weight: 1, element: 'Earth', grade: 'S' },
  { label: 'Phantom Blade', weight: 1, element: 'Soul', grade: 'S' },
  { label: 'Infernal Gauntlets', weight: 1, element: 'Fire', grade: 'S' },
  { label: 'Vortex Blade', weight: 1, element: 'Wind', grade: 'S' },
  { label: 'Frozen Soul Lance', weight: 1, element: 'Ice', grade: 'S' },
  { label: 'Necromancer\'s Scythe', weight: 1, element: 'Soul', grade: 'S' },
  { label: 'Runic Battle Axe', weight: 1, element: 'Arcane', grade: 'S' },
  { label: 'Poison Fang Blades', weight: 1, element: 'Poison', grade: 'S' },
  { label: 'Storm Arrow', weight: 1, element: 'Wind', grade: 'S' },
  { label: 'Void Chain Whip', weight: 1, element: 'Void', grade: 'S' },
  { label: 'Earth Shaker Hammer', weight: 1, element: 'Earth', grade: 'S' },
  { label: 'Mirror of the Soul', weight: 1, element: 'Psychic', grade: 'S' },
  { label: 'Crystal Resonance Staff', weight: 1, element: 'Sound', grade: 'S' },
  { label: 'Blood Cursed Sword', weight: 1, element: 'Blood', grade: 'S' },
  { label: 'Gravity Pulse Cannon', weight: 1, element: 'Gravity', grade: 'S' },
  { label: 'Nature\'s Blight Bow', weight: 1, element: 'Nature', grade: 'S' },
  { label: 'Metal God Gauntlets', weight: 1, element: 'Metal', grade: 'S' },
  { label: 'Temporal Cutter', weight: 1, element: 'Time', grade: 'S' },
  { label: 'Ancient Dragon Claw', weight: 1, element: 'Fire', grade: 'S' },
  { label: 'Dimensional Rift Sword', weight: 1, element: 'Arcane', grade: 'S' },
  { label: 'Psychic Amplifier Lance', weight: 1, element: 'Psychic', grade: 'S' },
  { label: 'Chaos Maul', weight: 1, element: 'Chaos', grade: 'S' },
  { label: 'Void Touched Crossbow', weight: 1, element: 'Void', grade: 'S' },
  { label: 'Soul Bind Chains', weight: 1, element: 'Soul', grade: 'S' },
  { label: 'Glacier Edge Blade', weight: 1, element: 'Ice', grade: 'S' },
  { label: 'Star Dust Spear', weight: 1, element: 'Cosmic', grade: 'S' },
  { label: 'Flame Tongue Sword', weight: 1, element: 'Fire', grade: 'S' },
  { label: 'Shadow Step Daggers', weight: 1, element: 'Shadow', grade: 'S' },

  // ── A TIER (50) — Legendary weapons ──
  { label: 'Wraithbone Saber', weight: 1, element: 'Soul', grade: 'A' },
  { label: 'Tempest Blade', weight: 1, element: 'Lightning', grade: 'A' },
  { label: 'Eternal Edge', weight: 1, element: 'Neutral', grade: 'A' },
  { label: 'Sunder Fist', weight: 1, element: 'Metal', grade: 'A' },
  { label: 'Cursed Chain Whip', weight: 1, element: 'Arcane', grade: 'A' },
  { label: 'Iron Tide Trident', weight: 1, element: 'Water', grade: 'A' },
  { label: 'Blazing Phoenix Sword', weight: 1, element: 'Fire', grade: 'A' },
  { label: 'Shadow Claw Gauntlets', weight: 1, element: 'Shadow', grade: 'A' },
  { label: 'Frost Wolf Fang Blade', weight: 1, element: 'Ice', grade: 'A' },
  { label: 'Thunder Strike Spear', weight: 1, element: 'Lightning', grade: 'A' },
  { label: 'Verdant Bow', weight: 1, element: 'Nature', grade: 'A' },
  { label: 'Arcane Pulse Wand', weight: 1, element: 'Arcane', grade: 'A' },
  { label: 'Crimson Chaos Sword', weight: 1, element: 'Blood', grade: 'A' },
  { label: 'Iron Will Gauntlets', weight: 1, element: 'Metal', grade: 'A' },
  { label: 'Serpent Fang Daggers', weight: 1, element: 'Poison', grade: 'A' },
  { label: 'Windcutter Scimitar', weight: 1, element: 'Wind', grade: 'A' },
  { label: 'Sea Dragon Trident', weight: 1, element: 'Water', grade: 'A' },
  { label: 'Soulbind Lasso', weight: 1, element: 'Soul', grade: 'A' },
  { label: 'Gravity Distortion Staff', weight: 1, element: 'Gravity', grade: 'A' },
  { label: 'Stone Titan Hammer', weight: 1, element: 'Earth', grade: 'A' },
  { label: 'Mirror Blade', weight: 1, element: 'Psychic', grade: 'A' },
  { label: 'Void Chain', weight: 1, element: 'Void', grade: 'A' },
  { label: 'Stardust Bow', weight: 1, element: 'Cosmic', grade: 'A' },
  { label: 'Runic War Hammer', weight: 1, element: 'Arcane', grade: 'A' },
  { label: 'Chaos Spike Mace', weight: 1, element: 'Chaos', grade: 'A' },
  { label: 'Obsidian Blade', weight: 1, element: 'Earth', grade: 'A' },
  { label: 'Frozen Moon Blade', weight: 1, element: 'Ice', grade: 'A' },
  { label: 'Blood Bound Axe', weight: 1, element: 'Blood', grade: 'A' },
  { label: 'Nature\'s Fury Club', weight: 1, element: 'Nature', grade: 'A' },
  { label: 'Soundwave Cannon', weight: 1, element: 'Sound', grade: 'A' },
  { label: 'Timefrost Dagger', weight: 1, element: 'Time', grade: 'A' },
  { label: 'Astral Sword', weight: 1, element: 'Cosmic', grade: 'A' },
  { label: 'Psychic Spike Lance', weight: 1, element: 'Psychic', grade: 'A' },
  { label: 'Flame Crown Axe', weight: 1, element: 'Fire', grade: 'A' },
  { label: 'Deep Ocean Spear', weight: 1, element: 'Water', grade: 'A' },
  { label: 'Lightning Fist Gauntlets', weight: 1, element: 'Lightning', grade: 'A' },
  { label: 'Shadow Piercer Arrows', weight: 1, element: 'Shadow', grade: 'A' },
  { label: 'Metal Wing Blades', weight: 1, element: 'Metal', grade: 'A' },
  { label: 'Void Pulse Wand', weight: 1, element: 'Void', grade: 'A' },
  { label: 'Ancient Rune Sword', weight: 1, element: 'Arcane', grade: 'A' },
  { label: 'Grimoire of the Abyss', weight: 1, element: 'Arcane', grade: 'A' },
  { label: 'Soul Extractor Staff', weight: 1, element: 'Soul', grade: 'A' },
  { label: 'Titan Skull Club', weight: 1, element: 'Earth', grade: 'A' },
  { label: 'Blood Price Daggers', weight: 1, element: 'Blood', grade: 'A' },
  { label: 'Emerald Spine Bow', weight: 1, element: 'Nature', grade: 'A' },
  { label: 'Thunderstrike Crossbow', weight: 1, element: 'Lightning', grade: 'A' },
  { label: 'Void Eye Staff', weight: 1, element: 'Void', grade: 'A' },
  { label: 'Phoenix Wing Blades', weight: 1, element: 'Fire', grade: 'A' },
  { label: 'Gravity Shift Hammer', weight: 1, element: 'Gravity', grade: 'A' },
  { label: 'Crystal Resonator', weight: 1, element: 'Sound', grade: 'A' },

  // ── B TIER (60) — Epic weapons ──
  { label: 'Voidsteel Katana', weight: 1, element: 'Void', grade: 'B' },
  { label: 'Arcanite Wand', weight: 1, element: 'Arcane', grade: 'B' },
  { label: 'Necromancer\'s Staff', weight: 1, element: 'Arcane', grade: 'B' },
  { label: 'Warlock\'s Grimoire (Weaponised)', weight: 1, element: 'Arcane', grade: 'B' },
  { label: 'War Hymn Blade', weight: 1, element: 'Neutral', grade: 'B' },
  { label: 'Scorched Blade', weight: 1, element: 'Fire', grade: 'B' },
  { label: 'Frost Kiss Dagger', weight: 1, element: 'Ice', grade: 'B' },
  { label: 'Storm Edge Sword', weight: 1, element: 'Wind', grade: 'B' },
  { label: 'Bone Splitter Axe', weight: 1, element: 'Earth', grade: 'B' },
  { label: 'Shadow Fang Blade', weight: 1, element: 'Shadow', grade: 'B' },
  { label: 'Electric Javelin', weight: 1, element: 'Lightning', grade: 'B' },
  { label: 'Thornwood Staff', weight: 1, element: 'Nature', grade: 'B' },
  { label: 'Iron Tide Axe', weight: 1, element: 'Water', grade: 'B' },
  { label: 'Venom Arrow Quiver', weight: 1, element: 'Poison', grade: 'B' },
  { label: 'Runed Mace', weight: 1, element: 'Arcane', grade: 'B' },
  { label: 'Gravity Crush Gauntlets', weight: 1, element: 'Gravity', grade: 'B' },
  { label: 'Void Pulse Arrows', weight: 1, element: 'Void', grade: 'B' },
  { label: 'Spectral Whip', weight: 1, element: 'Soul', grade: 'B' },
  { label: 'Chaos Serrated Blade', weight: 1, element: 'Chaos', grade: 'B' },
  { label: 'Cinder Axe', weight: 1, element: 'Fire', grade: 'B' },
  { label: 'Moonlight Bow', weight: 1, element: 'Cosmic', grade: 'B' },
  { label: 'Echo Blade', weight: 1, element: 'Sound', grade: 'B' },
  { label: 'Time Step Daggers', weight: 1, element: 'Time', grade: 'B' },
  { label: 'Psychic Shards', weight: 1, element: 'Psychic', grade: 'B' },
  { label: 'Metal Fist Gauntlets', weight: 1, element: 'Metal', grade: 'B' },
  { label: 'Coral Trident', weight: 1, element: 'Water', grade: 'B' },
  { label: 'Blood Oath Blade', weight: 1, element: 'Blood', grade: 'B' },
  { label: 'Cracked Runic Sword', weight: 1, element: 'Arcane', grade: 'B' },
  { label: 'Thorn Whip', weight: 1, element: 'Nature', grade: 'B' },
  { label: 'Magnetized War Hammer', weight: 1, element: 'Metal', grade: 'B' },
  { label: 'Darkwood Bow', weight: 1, element: 'Nature', grade: 'B' },
  { label: 'Soul Chain Whip', weight: 1, element: 'Soul', grade: 'B' },
  { label: 'Void Shard Blade', weight: 1, element: 'Void', grade: 'B' },
  { label: 'Storm Javelin', weight: 1, element: 'Wind', grade: 'B' },
  { label: 'Flame Coil Whip', weight: 1, element: 'Fire', grade: 'B' },
  { label: 'Frozen Fang Daggers', weight: 1, element: 'Ice', grade: 'B' },
  { label: 'Arcane Bolt Wand', weight: 1, element: 'Arcane', grade: 'B' },
  { label: 'Shadow Bound Crossbow', weight: 1, element: 'Shadow', grade: 'B' },
  { label: 'Gravity Spike Mace', weight: 1, element: 'Gravity', grade: 'B' },
  { label: 'Howling Wind Blade', weight: 1, element: 'Wind', grade: 'B' },
  { label: 'Earth Crusher Hammer', weight: 1, element: 'Earth', grade: 'B' },
  { label: 'Needle Fang Blades', weight: 1, element: 'Poison', grade: 'B' },
  { label: 'Resonant Staff', weight: 1, element: 'Sound', grade: 'B' },
  { label: 'Cosmic Shard Dagger', weight: 1, element: 'Cosmic', grade: 'B' },
  { label: 'Blood Stone Mace', weight: 1, element: 'Blood', grade: 'B' },
  { label: 'Chaos Burst Cannon', weight: 1, element: 'Chaos', grade: 'B' },
  { label: 'Temporal Knife', weight: 1, element: 'Time', grade: 'B' },
  { label: 'Mind Spike Lance', weight: 1, element: 'Psychic', grade: 'B' },
  { label: 'Volcanic Spear', weight: 1, element: 'Fire', grade: 'B' },
  { label: 'Tide Caller Trident', weight: 1, element: 'Water', grade: 'B' },
  { label: 'Wraith Blade', weight: 1, element: 'Soul', grade: 'B' },
  { label: 'Iron Spine Flail', weight: 1, element: 'Metal', grade: 'B' },
  { label: 'Eclipse Blade', weight: 1, element: 'Shadow', grade: 'B' },
  { label: 'Tundra Edge Sword', weight: 1, element: 'Ice', grade: 'B' },
  { label: 'Crystal Shard Bow', weight: 1, element: 'Sound', grade: 'B' },
  { label: 'Void Touched Axe', weight: 1, element: 'Void', grade: 'B' },
  { label: 'Thornvine Whip', weight: 1, element: 'Nature', grade: 'B' },
  { label: 'Abyssal Dagger', weight: 1, element: 'Void', grade: 'B' },
  { label: 'War Drum Hammer', weight: 1, element: 'Earth', grade: 'B' },
  { label: 'Crimson Staff', weight: 1, element: 'Blood', grade: 'B' },

  // ── C TIER (70) — Rare weapons ──
  { label: 'Kusarigama', weight: 1, element: 'Neutral', grade: 'C' },
  { label: 'Dragonbone Club', weight: 1, element: 'Earth', grade: 'C' },
  { label: 'Mithril Rapier', weight: 1, element: 'Metal', grade: 'C' },
  { label: 'Orichalcum Trident', weight: 1, element: 'Metal', grade: 'C' },
  { label: 'Oracle\'s Rod', weight: 1, element: 'Arcane', grade: 'C' },
  { label: 'Enchanted Longbow', weight: 1, element: 'Arcane', grade: 'C' },
  { label: 'Magma Sword', weight: 1, element: 'Fire', grade: 'C' },
  { label: 'Tide Blade', weight: 1, element: 'Water', grade: 'C' },
  { label: 'Vine Lash Whip', weight: 1, element: 'Nature', grade: 'C' },
  { label: 'Hunting Bow (Enchanted)', weight: 1, element: 'Nature', grade: 'C' },
  { label: 'Hex Dagger', weight: 1, element: 'Arcane', grade: 'C' },
  { label: 'Chain Flail', weight: 1, element: 'Metal', grade: 'C' },
  { label: 'Iron Spike Club', weight: 1, element: 'Earth', grade: 'C' },
  { label: 'Ember Crossbow', weight: 1, element: 'Fire', grade: 'C' },
  { label: 'Wind Blade', weight: 1, element: 'Wind', grade: 'C' },
  { label: 'Frost Javelin', weight: 1, element: 'Ice', grade: 'C' },
  { label: 'Shadow Arrow Quiver', weight: 1, element: 'Shadow', grade: 'C' },
  { label: 'Shock Gauntlets', weight: 1, element: 'Lightning', grade: 'C' },
  { label: 'Bone Scythe', weight: 1, element: 'Soul', grade: 'C' },
  { label: 'Tidal Hammer', weight: 1, element: 'Water', grade: 'C' },
  { label: 'Cracked War Axe', weight: 1, element: 'Metal', grade: 'C' },
  { label: 'Gale Bow', weight: 1, element: 'Wind', grade: 'C' },
  { label: 'Gloom Blade', weight: 1, element: 'Shadow', grade: 'C' },
  { label: 'Coral Staff', weight: 1, element: 'Water', grade: 'C' },
  { label: 'Gravel Fist Gauntlets', weight: 1, element: 'Earth', grade: 'C' },
  { label: 'Spark Wand', weight: 1, element: 'Lightning', grade: 'C' },
  { label: 'Venomcoat Blade', weight: 1, element: 'Poison', grade: 'C' },
  { label: 'Bramble Staff', weight: 1, element: 'Nature', grade: 'C' },
  { label: 'Iron Jaw Trap (On a Stick)', weight: 1, element: 'Metal', grade: 'C' },
  { label: 'Whisper Blade', weight: 1, element: 'Sound', grade: 'C' },
  { label: 'Void Shard Arrow', weight: 1, element: 'Void', grade: 'C' },
  { label: 'Bloodstone Dagger', weight: 1, element: 'Blood', grade: 'C' },
  { label: 'Time Freeze Arrow', weight: 1, element: 'Time', grade: 'C' },
  { label: 'Psychic Edge Blade', weight: 1, element: 'Psychic', grade: 'C' },
  { label: 'Chaos Fragment Mace', weight: 1, element: 'Chaos', grade: 'C' },
  { label: 'Stone Spike Spear', weight: 1, element: 'Earth', grade: 'C' },
  { label: 'Frost Thorn Bow', weight: 1, element: 'Ice', grade: 'C' },
  { label: 'Burn Scar Blade', weight: 1, element: 'Fire', grade: 'C' },
  { label: 'Iron Fist Gauntlets', weight: 1, element: 'Metal', grade: 'C' },
  { label: 'Soul Lantern (Weaponised)', weight: 1, element: 'Soul', grade: 'C' },
  { label: 'Toxic Spike Daggers', weight: 1, element: 'Poison', grade: 'C' },
  { label: 'Gravity Bead Staff', weight: 1, element: 'Gravity', grade: 'C' },
  { label: 'Splinter Bow', weight: 1, element: 'Nature', grade: 'C' },
  { label: 'Arcane Splinter', weight: 1, element: 'Arcane', grade: 'C' },
  { label: 'Echo Knife', weight: 1, element: 'Sound', grade: 'C' },
  { label: 'Lava Chip Sword', weight: 1, element: 'Fire', grade: 'C' },
  { label: 'Deep Water Staff', weight: 1, element: 'Water', grade: 'C' },
  { label: 'Thunderstrike Club', weight: 1, element: 'Lightning', grade: 'C' },
  { label: 'Blood Drip Blade', weight: 1, element: 'Blood', grade: 'C' },
  { label: 'Void Thread Whip', weight: 1, element: 'Void', grade: 'C' },
  { label: 'Cinder Club', weight: 1, element: 'Fire', grade: 'C' },
  { label: 'Gust Blade', weight: 1, element: 'Wind', grade: 'C' },
  { label: 'Dark Shard Dagger', weight: 1, element: 'Shadow', grade: 'C' },
  { label: 'Mudstone Hammer', weight: 1, element: 'Earth', grade: 'C' },
  { label: 'Iron Thorn Whip', weight: 1, element: 'Metal', grade: 'C' },
  { label: 'Cryo Spike', weight: 1, element: 'Ice', grade: 'C' },
  { label: 'Nature Bind Staff', weight: 1, element: 'Nature', grade: 'C' },
  { label: 'Hex Bolt Wand', weight: 1, element: 'Arcane', grade: 'C' },
  { label: 'Spliced Shadow Blade', weight: 1, element: 'Shadow', grade: 'C' },
  { label: 'Brine Blade', weight: 1, element: 'Water', grade: 'C' },
  { label: 'Pulse Blade', weight: 1, element: 'Lightning', grade: 'C' },
  { label: 'Chaos Fuse Mace', weight: 1, element: 'Chaos', grade: 'C' },
  { label: 'Thorn Staff', weight: 1, element: 'Nature', grade: 'C' },
  { label: 'Drift Spear', weight: 1, element: 'Wind', grade: 'C' },
  { label: 'Claw Gauntlets', weight: 1, element: 'Metal', grade: 'C' },
  { label: 'Mind Cut Blade', weight: 1, element: 'Psychic', grade: 'C' },
  { label: 'Doom Dagger', weight: 1, element: 'Shadow', grade: 'C' },
  { label: 'Silt Axe', weight: 1, element: 'Earth', grade: 'C' },
  { label: 'Time Sliver Dagger', weight: 1, element: 'Time', grade: 'C' },
  { label: 'Rusted Cleaver', weight: 1, element: 'Metal', grade: 'C' },

  // ── D TIER (70) — Uncommon weapons ──
  { label: 'No Weapon (Unarmed)', weight: 4, element: 'Neutral', grade: 'D' },
  { label: 'Hunting Knife', weight: 1, element: 'Neutral', grade: 'D' },
  { label: 'Short Sword', weight: 1, element: 'Metal', grade: 'D' },
  { label: 'Wooden Staff', weight: 1, element: 'Nature', grade: 'D' },
  { label: 'Crossbow', weight: 1, element: 'Neutral', grade: 'D' },
  { label: 'Handaxe', weight: 1, element: 'Metal', grade: 'D' },
  { label: 'Hunting Spear', weight: 1, element: 'Earth', grade: 'D' },
  { label: 'Flail', weight: 1, element: 'Metal', grade: 'D' },
  { label: 'Shortsword (Chipped)', weight: 1, element: 'Metal', grade: 'D' },
  { label: 'Training Sword', weight: 1, element: 'Metal', grade: 'D' },
  { label: 'Militia Shield (Weaponised)', weight: 1, element: 'Metal', grade: 'D' },
  { label: 'Worn Mace', weight: 1, element: 'Earth', grade: 'D' },
  { label: 'Crude Bow', weight: 1, element: 'Neutral', grade: 'D' },
  { label: 'Notched Dagger', weight: 1, element: 'Metal', grade: 'D' },
  { label: 'Sling', weight: 1, element: 'Earth', grade: 'D' },
  { label: 'Iron Poker', weight: 1, element: 'Fire', grade: 'D' },
  { label: 'Wooden Cudgel', weight: 1, element: 'Nature', grade: 'D' },
  { label: 'Bent Spear', weight: 1, element: 'Metal', grade: 'D' },
  { label: 'Apprentice Wand', weight: 1, element: 'Arcane', grade: 'D' },
  { label: 'Patchwork Crossbow', weight: 1, element: 'Neutral', grade: 'D' },
  { label: 'Dull Cleaver', weight: 1, element: 'Metal', grade: 'D' },
  { label: 'Improvised Club', weight: 1, element: 'Earth', grade: 'D' },
  { label: 'Fisherman\'s Harpoon', weight: 1, element: 'Water', grade: 'D' },
  { label: 'Farmhand\'s Scythe', weight: 1, element: 'Earth', grade: 'D' },
  { label: 'Guard\'s Halberd (Old)', weight: 1, element: 'Metal', grade: 'D' },
  { label: 'Soldier\'s Shortsword', weight: 1, element: 'Metal', grade: 'D' },
  { label: 'Hedge Trimmer (Sharpened)', weight: 1, element: 'Nature', grade: 'D' },
  { label: 'Rusted Knuckles', weight: 1, element: 'Metal', grade: 'D' },
  { label: 'Kitchen Knife (Large)', weight: 1, element: 'Neutral', grade: 'D' },
  { label: 'Barbarian Cudgel', weight: 1, element: 'Earth', grade: 'D' },
  { label: 'Crooked Staff', weight: 1, element: 'Arcane', grade: 'D' },
  { label: 'River Rock Sling', weight: 1, element: 'Earth', grade: 'D' },
  { label: 'Broken Hilt Sword', weight: 1, element: 'Metal', grade: 'D' },
  { label: 'Novice Bow', weight: 1, element: 'Nature', grade: 'D' },
  { label: 'Blunt Axe', weight: 1, element: 'Metal', grade: 'D' },
  { label: 'Militia Spear', weight: 1, element: 'Metal', grade: 'D' },
  { label: 'Bone Club', weight: 1, element: 'Earth', grade: 'D' },
  { label: 'Leather Sap', weight: 1, element: 'Neutral', grade: 'D' },
  { label: 'Branch Javelin', weight: 1, element: 'Nature', grade: 'D' },
  { label: 'Stone-Tipped Spear', weight: 1, element: 'Earth', grade: 'D' },
  { label: 'Scrap Metal Club', weight: 1, element: 'Metal', grade: 'D' },
  { label: 'Apprentice\'s Dagger', weight: 1, element: 'Neutral', grade: 'D' },
  { label: 'Simple Quarterstaff', weight: 1, element: 'Nature', grade: 'D' },
  { label: 'Cobbled Crossbow', weight: 1, element: 'Neutral', grade: 'D' },
  { label: 'Reed Pipe Blowgun', weight: 1, element: 'Poison', grade: 'D' },
  { label: 'Farmer\'s Pitchfork', weight: 1, element: 'Earth', grade: 'D' },
  { label: 'Inn Brawler\'s Bottle', weight: 1, element: 'Neutral', grade: 'D' },
  { label: 'Chain Whip (Rusted)', weight: 1, element: 'Metal', grade: 'D' },
  { label: 'Branch (Surprisingly Heavy)', weight: 1, element: 'Nature', grade: 'D' },
  { label: 'Guard Baton', weight: 1, element: 'Metal', grade: 'D' },
  { label: 'Carving Knife', weight: 1, element: 'Neutral', grade: 'D' },
  { label: 'Hunting Axe', weight: 1, element: 'Nature', grade: 'D' },
  { label: 'Cracked Buckler (Weaponised)', weight: 1, element: 'Metal', grade: 'D' },
  { label: 'Worn Gauntlets', weight: 1, element: 'Metal', grade: 'D' },
  { label: 'Rock (Very Large)', weight: 1, element: 'Earth', grade: 'D' },
  { label: 'Cane (Sharpened)', weight: 1, element: 'Neutral', grade: 'D' },
  { label: 'Crude Trident', weight: 1, element: 'Water', grade: 'D' },
  { label: 'Militia Hammer', weight: 1, element: 'Metal', grade: 'D' },
  { label: 'Reed Arrow Bow', weight: 1, element: 'Nature', grade: 'D' },
  { label: 'Stick (With a Nail)', weight: 1, element: 'Neutral', grade: 'D' },
  { label: 'Kitchen Cleaver', weight: 1, element: 'Neutral', grade: 'D' },
  { label: 'Apprentice\'s Wand (Bent)', weight: 1, element: 'Arcane', grade: 'D' },
  { label: 'Shiv (Prison Grade)', weight: 1, element: 'Neutral', grade: 'D' },
  { label: 'Rusty Shortsword', weight: 1, element: 'Metal', grade: 'D' },
  { label: 'Blunt Hammer', weight: 1, element: 'Earth', grade: 'D' },
  { label: 'Crooked Knife', weight: 1, element: 'Neutral', grade: 'D' },
  { label: 'Repurposed Tool (Weapon)', weight: 1, element: 'Neutral', grade: 'D' },
  { label: 'Guard\'s Baton (Old)', weight: 1, element: 'Metal', grade: 'D' },
  { label: 'Practice Spear', weight: 1, element: 'Metal', grade: 'D' },
  { label: 'Rope (Knotted)', weight: 1, element: 'Neutral', grade: 'D' },

  // ── E TIER (70) — Weak weapons ──
  { label: 'Straw Broom Handle', weight: 2, element: 'Neutral', grade: 'E' },
  { label: 'Foam Pool Noodle', weight: 2, element: 'Water', grade: 'E' },
  { label: 'Folded Newspaper', weight: 2, element: 'Neutral', grade: 'E' },
  { label: 'Wet Sock', weight: 2, element: 'Water', grade: 'E' },
  { label: 'Floppy Rubber Sword', weight: 2, element: 'Neutral', grade: 'E' },
  { label: 'Broken Umbrella', weight: 2, element: 'Wind', grade: 'E' },
  { label: 'Mop (Slightly Damp)', weight: 2, element: 'Water', grade: 'E' },
  { label: 'Cardboard Tube (Long)', weight: 2, element: 'Neutral', grade: 'E' },
  { label: 'Wooden Spoon (Weapon Grade)', weight: 2, element: 'Nature', grade: 'E' },
  { label: 'Unpeeled Banana (Thrown)', weight: 2, element: 'Neutral', grade: 'E' },
  { label: 'Wet Noodles (Bundle)', weight: 2, element: 'Neutral', grade: 'E' },
  { label: 'Limp Hose (Garden)', weight: 2, element: 'Water', grade: 'E' },
  { label: 'Stick Painted to Look Like a Sword', weight: 2, element: 'Neutral', grade: 'E' },
  { label: 'Pillow (Very Soft)', weight: 2, element: 'Neutral', grade: 'E' },
  { label: 'Confetti Cannon (Empty)', weight: 2, element: 'Wind', grade: 'E' },
  { label: 'Rubber Band Sling', weight: 2, element: 'Neutral', grade: 'E' },
  { label: 'Decorative Dagger (Blunt)', weight: 2, element: 'Metal', grade: 'E' },
  { label: 'Butter Knife', weight: 2, element: 'Metal', grade: 'E' },
  { label: 'Folding Fan (Cheap)', weight: 2, element: 'Wind', grade: 'E' },
  { label: 'Kazoo of Mild Annoyance', weight: 2, element: 'Sound', grade: 'E' },
  { label: 'Stress Ball (Squeaky)', weight: 2, element: 'Neutral', grade: 'E' },
  { label: 'Birthday Candle (Lit)', weight: 2, element: 'Fire', grade: 'E' },
  { label: 'Fly Swatter (Heavy Duty)', weight: 2, element: 'Neutral', grade: 'E' },
  { label: 'Whittled Toothpick Spear', weight: 2, element: 'Nature', grade: 'E' },
  { label: 'Cork Pop Pistol', weight: 2, element: 'Neutral', grade: 'E' },
  { label: 'Cat Toy (Feather on Stick)', weight: 2, element: 'Wind', grade: 'E' },
  { label: 'Melted Ice Cream (Flung)', weight: 2, element: 'Ice', grade: 'E' },
  { label: 'Oversized Pencil (Blunt)', weight: 2, element: 'Neutral', grade: 'E' },
  { label: 'Balloon Animal (Improvised Club)', weight: 2, element: 'Wind', grade: 'E' },
  { label: 'Wet Paper Fan', weight: 2, element: 'Water', grade: 'E' },
  { label: 'Pointing Stick (Presentation)', weight: 2, element: 'Neutral', grade: 'E' },
  { label: 'Spatula (Plastic)', weight: 2, element: 'Fire', grade: 'E' },
  { label: 'Kazoo Crossbow (Toy)', weight: 2, element: 'Sound', grade: 'E' },
  { label: 'Dried Noodles (Uncooked)', weight: 2, element: 'Neutral', grade: 'E' },
  { label: 'Tape Measure (Extended)', weight: 2, element: 'Metal', grade: 'E' },
  { label: 'Ladle (Bent)', weight: 2, element: 'Metal', grade: 'E' },
  { label: 'Novelty Oversized Crayon', weight: 2, element: 'Neutral', grade: 'E' },
  { label: 'Deflated Football', weight: 2, element: 'Neutral', grade: 'E' },
  { label: 'Ripped Poster (Rolled)', weight: 2, element: 'Neutral', grade: 'E' },
  { label: 'Cotton Candy Wand (Eaten)', weight: 2, element: 'Neutral', grade: 'E' },
  { label: 'Squeaky Hammer (Toy)', weight: 2, element: 'Neutral', grade: 'E' },
  { label: 'Loose Shoelace (Whipped)', weight: 2, element: 'Neutral', grade: 'E' },
  { label: 'Licorice Whip', weight: 2, element: 'Neutral', grade: 'E' },
  { label: 'Ping Pong Paddle', weight: 2, element: 'Neutral', grade: 'E' },
  { label: 'Bubble Wand (Blunt End)', weight: 2, element: 'Water', grade: 'E' },
  { label: 'Foam Finger (Pointing)', weight: 2, element: 'Neutral', grade: 'E' },
  { label: 'Party Horn (Forceful)', weight: 2, element: 'Sound', grade: 'E' },
  { label: 'Crumpled Tinfoil Sword', weight: 2, element: 'Metal', grade: 'E' },
  { label: 'Bag of Marshmallows', weight: 2, element: 'Neutral', grade: 'E' },
  { label: 'Rubber Duck (Thrown)', weight: 2, element: 'Water', grade: 'E' },
  { label: 'Wet Towel Snap', weight: 2, element: 'Water', grade: 'E' },
  { label: 'Plastic Fork (Stabby End)', weight: 2, element: 'Neutral', grade: 'E' },
  { label: 'Empty Spray Can', weight: 2, element: 'Wind', grade: 'E' },
  { label: 'Cardboard Tube Sword', weight: 2, element: 'Neutral', grade: 'E' },
  { label: 'Old Flip Flop (Slapped)', weight: 2, element: 'Neutral', grade: 'E' },
  { label: 'Novelty Giant Pencil', weight: 2, element: 'Neutral', grade: 'E' },
  { label: 'Straw (Bendy)', weight: 2, element: 'Neutral', grade: 'E' },
  { label: 'Sock With Coins in It', weight: 2, element: 'Metal', grade: 'E' },
  { label: 'Broken TV Remote', weight: 2, element: 'Neutral', grade: 'E' },
  { label: 'Balloon Sword (Pops Easily)', weight: 2, element: 'Wind', grade: 'E' },
  { label: 'Damp Sponge Mace', weight: 2, element: 'Water', grade: 'E' },
  { label: 'Worn Out Loofah', weight: 2, element: 'Water', grade: 'E' },
  { label: 'Spaghetti (Uncooked Bundle)', weight: 2, element: 'Neutral', grade: 'E' },
  { label: 'Frisbee (Aimed)', weight: 2, element: 'Wind', grade: 'E' },
  { label: 'Cheese Wedge (Sharpened)', weight: 2, element: 'Neutral', grade: 'E' },
  { label: 'Harmonica (Thrown)', weight: 2, element: 'Sound', grade: 'E' },
  { label: 'Leaf Blower (Reversed)', weight: 2, element: 'Wind', grade: 'E' },
  { label: 'Water Pistol (Angry Setting)', weight: 2, element: 'Water', grade: 'E' },
  { label: 'Broken Drumstick', weight: 2, element: 'Sound', grade: 'E' },
  { label: 'Wilted Flower Bouquet', weight: 2, element: 'Nature', grade: 'E' },

  // ── F TIER (80) — Comedy/joke weapons ──
  { label: 'A Slightly Sharp Stick', weight: 3, element: 'Nature', grade: 'F' },
  { label: 'Spoon (Plastic)', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Pineapple (On Pizza)', weight: 3, element: 'Fire', grade: 'F' },
  { label: 'A Strongly Worded Letter', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'My Disappointment (Maternal)', weight: 3, element: 'Psychic', grade: 'F' },
  { label: 'Participation Trophy (Thrown)', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Divorce Papers (Wielded)', weight: 3, element: 'Chaos', grade: 'F' },
  { label: 'A Passive Aggressive Post-It', weight: 3, element: 'Psychic', grade: 'F' },
  { label: 'Slipper (Very Old)', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'The Pointed Finger', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'An Argument Starter (Topic: Pineapple on Pizza)', weight: 3, element: 'Chaos', grade: 'F' },
  { label: 'Common Sense (Deployed)', weight: 3, element: 'Psychic', grade: 'F' },
  { label: 'A Single Raised Eyebrow', weight: 3, element: 'Psychic', grade: 'F' },
  { label: 'The Silent Treatment', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Wi-Fi Password (Withheld)', weight: 3, element: 'Chaos', grade: 'F' },
  { label: 'Passive Aggressive Humming', weight: 3, element: 'Sound', grade: 'F' },
  { label: 'Excel Spreadsheet (Weaponised)', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Terms and Conditions (Fully Read)', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'The Power of a Really Good Stare', weight: 3, element: 'Psychic', grade: 'F' },
  { label: 'Expired Coupon (Claimed)', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Nerf Sword (Fully Committed)', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Sandcastle Battlements', weight: 3, element: 'Earth', grade: 'F' },
  { label: 'Sock Puppet (Threatening)', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Banana Peel (Placed Deliberately)', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Fidget Spinner (Offensive Mode)', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Passive Aggressive Emoji Sword', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Rock Paper Scissors (Nuclear Option)', weight: 3, element: 'Chaos', grade: 'F' },
  { label: 'A Mild Annoyance (Sustained)', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Canned Applause (Derisive)', weight: 3, element: 'Sound', grade: 'F' },
  { label: 'An Airbud (Thrown)', weight: 3, element: 'Sound', grade: 'F' },
  { label: 'Post-Its (All Colors, Hostile)', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Lukewarm Coffee (Flung)', weight: 3, element: 'Fire', grade: 'F' },
  { label: 'Outdated Meme Reference', weight: 3, element: 'Chaos', grade: 'F' },
  { label: 'A Recitation of Your Resume', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Powerpoint Presentation (48 Slides)', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Unsolicited LinkedIn Connection', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Reading the Comments Section Aloud', weight: 3, element: 'Chaos', grade: 'F' },
  { label: 'A Bag of Last-Minute Concerns', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'The Honest Performance Review', weight: 3, element: 'Psychic', grade: 'F' },
  { label: 'Unsolicited Parenting Advice', weight: 3, element: 'Psychic', grade: 'F' },
  { label: 'A Children\'s Toy Bow', weight: 3, element: 'Nature', grade: 'F' },
  { label: 'Argument-Winning Machine (Broken)', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Fax Machine (Weaponised)', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Wet Handshake', weight: 3, element: 'Water', grade: 'F' },
  { label: 'Extremely Late Reply (Delivered In Person)', weight: 3, element: 'Time', grade: 'F' },
  { label: 'A Passive Aggressive Silence', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Compliment (Backhanded)', weight: 3, element: 'Psychic', grade: 'F' },
  { label: 'A Cancelled Plans (Repeated)', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'The "Just Asking Questions" Blade', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Uninvited Opinion Club', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Dead Plant (Wielded Sadly)', weight: 3, element: 'Nature', grade: 'F' },
  { label: 'Friendship Bracelet (Given Ironically)', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'A Crumpled Parking Ticket', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Watered-Down Threat', weight: 3, element: 'Water', grade: 'F' },
  { label: 'The Look (Maternal Edition)', weight: 3, element: 'Psychic', grade: 'F' },
  { label: 'Speed Bump (Carried)', weight: 3, element: 'Earth', grade: 'F' },
  { label: 'Empty Promises Wand', weight: 3, element: 'Arcane', grade: 'F' },
  { label: 'Motivational Poster (Rolled Up)', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Mild Inconvenience Mace', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'A Very Loud Sigh', weight: 3, element: 'Wind', grade: 'F' },
  { label: 'The Overly Detailed Voicemail', weight: 3, element: 'Sound', grade: 'F' },
  { label: 'A Printed Email (With Highlighter)', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Cheese Grater Fists', weight: 3, element: 'Metal', grade: 'F' },
  { label: 'Aggressive Thumbs-Up', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'A Firm Tap on the Shoulder', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Phone (No Signal, 2% Battery)', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Leftover Birthday Cake (Thrown Piece)', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'The Mandatory Update (Forced)', weight: 3, element: 'Chaos', grade: 'F' },
  { label: 'A Passive Aggressive GIF', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Slow-Clap Generator', weight: 3, element: 'Sound', grade: 'F' },
  { label: '"Reply All" Email Cascade', weight: 3, element: 'Chaos', grade: 'F' },
  { label: 'Slightly Aggressive Eye Contact', weight: 3, element: 'Psychic', grade: 'F' },
  { label: 'The "Can We Talk?" Message', weight: 3, element: 'Psychic', grade: 'F' },
  { label: 'Warranty Void Sticker (Peeled Angrily)', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'An Extremely Loud Yawn', weight: 3, element: 'Sound', grade: 'F' },
  { label: 'A Phone Screen (Cracked, Still Works)', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Oven Mitt (One)', weight: 3, element: 'Fire', grade: 'F' },
  { label: 'The Threatening Wink', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Expired Yogurt (Thrown)', weight: 3, element: 'Neutral', grade: 'F' },
  { label: 'Gentle Nudge (Very Gentle)', weight: 3, element: 'Neutral', grade: 'F' },
]
