// weapons.ts — Weapons content pool for Wheel of Fate.
// 500+ SimpleItem entries spanning legendary to absurd.
// No default export. No functions. Static const array only.

import type { SimpleItem } from './types'

export const weapons: SimpleItem[] = [
  // ── Legendary / Epic Weapons ──
  { label: 'Excalibur', weight: 1 },
  { label: 'Mjolnir', weight: 1 },
  { label: 'Gungnir', weight: 1 },
  { label: 'Durandal', weight: 1 },
  { label: 'Joyeuse', weight: 1 },
  { label: 'Kusarigama', weight: 1 },
  { label: 'Void Blade', weight: 1 },
  { label: 'Seraphic Lance', weight: 1 },
  { label: 'Dragon\'s Fang', weight: 1 },
  { label: 'Shadowmeld Dagger', weight: 1 },
  { label: 'Thunderclap Hammer', weight: 1 },
  { label: 'Sunfire Bow', weight: 1 },
  { label: 'Runic Greatsword', weight: 1 },
  { label: 'Ethereal Whip', weight: 1 },
  { label: 'Bloodletter', weight: 1 },
  { label: 'Soulreaver', weight: 1 },
  { label: 'Starfall Javelin', weight: 1 },
  { label: 'Moonblade', weight: 1 },
  { label: 'Stormcaller Staff', weight: 1 },
  { label: 'Frostbite Axe', weight: 1 },
  { label: 'Hellfire Crossbow', weight: 1 },
  { label: 'Celestial Spear', weight: 1 },
  { label: 'Abyssal Scythe', weight: 1 },
  { label: 'Titan\'s Maul', weight: 1 },
  { label: 'Phantom Blade', weight: 1 },
  { label: 'Wraithbone Saber', weight: 1 },
  { label: 'Arcanite Wand', weight: 1 },
  { label: 'Voidsteel Katana', weight: 1 },
  { label: 'Dragonbone Club', weight: 1 },
  { label: 'Mithril Rapier', weight: 1 },
  { label: 'Orichalcum Trident', weight: 1 },
  { label: 'Stardust Bow', weight: 1 },
  { label: 'Necromancer\'s Staff', weight: 1 },
  { label: 'Warlock\'s Grimoire (Weaponised)', weight: 1 },
  { label: 'Oracle\'s Rod', weight: 1 },
  { label: 'Tempest Blade', weight: 1 },
  { label: 'Eternal Edge', weight: 1 },
  { label: 'Deathwhisper', weight: 1 },
  { label: 'Godsplitter', weight: 1 },
  { label: 'Worldrend', weight: 1 },
  { label: 'Sunder Fist', weight: 1 },
  { label: 'War Hymn Blade', weight: 1 },
  { label: 'Fate\'s Edge', weight: 1 },
  { label: 'Prophecy Sword', weight: 1 },
  { label: 'The Last Word (Firearm)', weight: 1 },
  { label: 'Final Judgment (Cannon)', weight: 1 },
  { label: 'Heaven\'s Fury', weight: 1 },
  { label: 'Hell\'s Wrath', weight: 1 },
  { label: 'Voidcaller Bow', weight: 1 },
  { label: 'Stormbreaker', weight: 1 },
  { label: 'Bloodmoon Scimitar', weight: 1 },
  { label: 'Eclipse Blade', weight: 1 },
  { label: 'Sundering Spear', weight: 1 },
  { label: 'Earthshaker Hammer', weight: 1 },
  { label: 'Skyrender Axe', weight: 1 },
  { label: 'Tidecaller Trident', weight: 1 },
  { label: 'Flamebrand', weight: 1 },
  { label: 'Frostweave Blade', weight: 1 },
  { label: 'Thunderstrike Halberd', weight: 1 },
  { label: 'Shadowfang', weight: 1 },
  { label: 'Radiant Sword', weight: 1 },
  { label: 'Darkmatter Blade', weight: 1 },
  { label: 'Quantum Saber', weight: 1 },
  { label: 'Chrono Blade', weight: 1 },
  { label: 'Soul Splitter', weight: 1 },
  { label: 'Reality Cutter', weight: 1 },
  { label: 'Dimensional Edge', weight: 1 },
  { label: 'Cosmic Lance', weight: 1 },
  { label: 'Entropy Sword', weight: 1 },
  { label: 'Chaos Blade', weight: 1 },
  { label: 'Order Breaker', weight: 1 },
  { label: 'Nexus Sword', weight: 1 },
  { label: 'Prism Blade', weight: 1 },
  { label: 'Umbral Dagger', weight: 1 },
  { label: 'Luminous Rapier', weight: 1 },
  { label: 'Arcane Shortsword', weight: 1 },
  { label: 'Spellblade', weight: 1 },
  { label: 'Rune-etched Battleaxe', weight: 1 },
  { label: 'Sigil Spear', weight: 1 },
  { label: 'Enchanted Longbow', weight: 1 },
  { label: 'Blessed Mace', weight: 1 },
  { label: 'Cursed Claymore', weight: 1 },
  { label: 'Hexblade', weight: 1 },
  { label: 'Charm-Forged Flail', weight: 1 },
  { label: 'Imbued Morning Star', weight: 1 },
  { label: 'War Scythe of Endings', weight: 1 },
  { label: 'Reaping Hook', weight: 1 },
  { label: 'Harvest Blade', weight: 1 },
  { label: 'Ancient Halberd', weight: 1 },
  { label: 'Primordial Glaive', weight: 1 },
  { label: 'Archaic Warhammer', weight: 1 },
  { label: 'Ancestral Blade', weight: 1 },
  { label: 'Heirloom Sword', weight: 1 },
  { label: 'Relic Blade', weight: 1 },
  { label: 'Artifact Sword', weight: 1 },
  { label: 'Mythic Spear', weight: 1 },
  { label: 'Legendary Bow', weight: 1 },
  { label: 'Fabled Dagger', weight: 1 },
  { label: 'Storied Axe', weight: 1 },
  { label: 'Epic Wand', weight: 1 },
  { label: 'Heroic Shield', weight: 1 },
  { label: 'Champion\'s Blade', weight: 1 },
  { label: 'Conqueror\'s Axe', weight: 1 },
  { label: 'Destroyer\'s Hammer', weight: 1 },
  { label: 'Protector\'s Shield', weight: 1 },
  { label: 'Guardian\'s Spear', weight: 1 },
  { label: 'Avenger\'s Sword', weight: 1 },
  { label: 'Paladin\'s Holy Avenger', weight: 1 },
  { label: 'Ranger\'s Heartseeker Bow', weight: 1 },
  { label: 'Assassin\'s Shadowdagger', weight: 1 },
  { label: 'Mage\'s Arcane Focus', weight: 1 },
  { label: 'Druid\'s Nature Staff', weight: 1 },
  { label: 'Warlock\'s Pact Blade', weight: 1 },
  { label: 'Sorcerer\'s Power Conduit', weight: 1 },
  { label: 'Bard\'s Instrument of War', weight: 1 },
  { label: 'Monk\'s Iron Fists', weight: 1 },
  { label: 'Berserker\'s Greataxe', weight: 1 },
  { label: 'Necromancer\'s Deathscythe', weight: 1 },
  { label: 'Artificer\'s Mechanical Arm', weight: 1 },
  { label: 'Cleric\'s Divine Rod', weight: 1 },
  { label: 'Inquisitor\'s Flame Whip', weight: 1 },
  { label: 'Templar\'s Crusader Blade', weight: 1 },
  { label: 'Dark Knight\'s Hell Edge', weight: 1 },
  { label: 'Death Knight\'s Runeblade', weight: 1 },
  { label: 'Blood Knight\'s Crimson Blade', weight: 1 },
  { label: 'Chaos Knight\'s Fractal Sword', weight: 1 },
  { label: 'Sky Knight\'s Aerial Spear', weight: 1 },
  { label: 'Sea Knight\'s Depth Blade', weight: 1 },
  { label: 'Earth Knight\'s Stone Maul', weight: 1 },
  { label: 'Star Knight\'s Celestial Edge', weight: 1 },
  { label: 'Void Knight\'s Nothing Blade', weight: 1 },
  { label: 'Time Knight\'s Paradox Sword', weight: 1 },
  { label: 'Soul Knight\'s Ecto-Blade', weight: 1 },
  { label: 'Mind Knight\'s Psi-Blade', weight: 1 },
  { label: 'Spirit Blade', weight: 1 },
  { label: 'Ghost Sword', weight: 1 },
  { label: 'Wraith Scythe', weight: 1 },
  { label: 'Banshee\'s Wail Spear', weight: 1 },
  { label: 'Lich\'s Phylactery Staff', weight: 1 },
  { label: 'Vampire\'s Bloodblade', weight: 1 },
  { label: 'Werewolf\'s Silver-Proof Claw', weight: 1 },
  { label: 'Dragon\'s Claw Gauntlets', weight: 1 },
  { label: 'Phoenix Feather Blade', weight: 1 },
  { label: 'Griffin Talon', weight: 1 },
  { label: 'Unicorn Horn Lance', weight: 1 },
  { label: 'Basilisk Eye Staff', weight: 1 },
  { label: 'Medusa\'s Gaze Wand', weight: 1 },
  { label: 'Chimera Fang', weight: 1 },
  { label: 'Hydra Spine Blade', weight: 1 },
  { label: 'Cerberus Chain', weight: 1 },
  { label: 'Kraken Tentacle', weight: 1 },
  { label: 'Leviathan Scale Bow', weight: 1 },
  { label: 'Behemoth Bone Club', weight: 1 },
  { label: 'Ziz Feather Arrows', weight: 1 },
  { label: 'Golem Arm', weight: 1 },
  { label: 'Automaton Fist', weight: 1 },
  { label: 'Construct Cannon', weight: 1 },
  { label: 'Mechanical Spider Blade', weight: 1 },
  { label: 'Steam-Powered Mace', weight: 1 },
  { label: 'Aether Cannon', weight: 1 },
  { label: 'Plasma Cutter', weight: 1 },
  { label: 'Energy Rifle', weight: 1 },
  { label: 'Photon Blade', weight: 1 },
  { label: 'Ion Spear', weight: 1 },
  { label: 'Graviton Hammer', weight: 1 },
  { label: 'Singularity Gun', weight: 1 },
  { label: 'Antimatter Pistol', weight: 1 },
  { label: 'Neutrino Railgun', weight: 1 },
  { label: 'Tachyon Blade', weight: 1 },
  { label: 'Quark Destabiliser', weight: 1 },
  { label: 'Hadron Collider Sword', weight: 1 },
  { label: 'Fusion Lance', weight: 1 },
  { label: 'Fission Bomb (Personal)', weight: 1 },
  { label: 'Nano-blade', weight: 1 },
  { label: 'Micro-filament Whip', weight: 1 },
  { label: 'Molecular Wire', weight: 1 },
  { label: 'Monomolecular Blade', weight: 1 },
  { label: 'Vibro-sword', weight: 1 },
  { label: 'Sonic Disruptor', weight: 1 },
  { label: 'Ultrasonic Blade', weight: 1 },
  { label: 'Resonance Hammer', weight: 1 },
  { label: 'Frequency Rifle', weight: 1 },
  { label: 'Waveform Disruptor', weight: 1 },
  { label: 'Psionic Blade', weight: 1 },
  { label: 'Thought Spear', weight: 1 },
  { label: 'Mind Saber', weight: 1 },
  { label: 'Emotion Sword', weight: 1 },
  { label: 'Fear Manifestation Blade', weight: 1 },
  { label: 'Dream Cutter', weight: 1 },
  { label: 'Nightmare Scythe', weight: 1 },
  { label: 'Memory Sword', weight: 1 },
  { label: 'Will Blade', weight: 1 },
  { label: 'Intent Spear', weight: 1 },
  { label: 'Conviction Sword', weight: 1 },
  { label: 'Faith Lance', weight: 1 },
  { label: 'Doubt Dagger', weight: 1 },
  { label: 'Despair Scythe', weight: 1 },
  { label: 'Hope Blade', weight: 1 },
  { label: 'Love Sword (Terrifyingly Effective)', weight: 1 },

  // ── Absurd / Comedic Weapons ──
  { label: 'Pineapple', weight: 1 },
  { label: 'Grandma\'s Slipper', weight: 1 },
  { label: 'Slightly Sharp Pencil', weight: 1 },
  { label: 'Frozen Fish', weight: 1 },
  { label: 'Damp Newspaper', weight: 1 },
  { label: 'Novelty-Sized Fork', weight: 1 },
  { label: 'A Stern Talking-To', weight: 1 },
  { label: 'Passive Aggression (Manifested)', weight: 1 },
  { label: 'Slightly Disappointing Handshake', weight: 1 },
  { label: 'Pool Noodle', weight: 1 },
  { label: 'Traffic Cone', weight: 1 },
  { label: 'Overcooked Noodle', weight: 1 },
  { label: 'Left Shoe Only', weight: 1 },
  { label: 'Barely-Sharpened #2 Pencil', weight: 1 },
  { label: 'Aggressive Eye Contact', weight: 1 },
  { label: 'Decorative Gourd', weight: 1 },
  { label: 'Novelty Giant Inflatable Hammer', weight: 1 },
  { label: 'Rolled-Up Magazine', weight: 1 },
  { label: 'Wet Towel', weight: 1 },
  { label: 'Half-Eaten Banana', weight: 1 },
  { label: 'Unripe Avocado', weight: 1 },
  { label: 'Heavily Annotated Tax Return', weight: 1 },
  { label: 'Passive-Aggressive Note on Windscreen', weight: 1 },
  { label: 'Complaint Letter (Sent Third Class)', weight: 1 },
  { label: 'Passive-Aggressive Sighing', weight: 1 },
  { label: 'The Silent Treatment', weight: 1 },
  { label: 'Withering Glare', weight: 1 },
  { label: 'A Strongly Worded Email (Printed Out)', weight: 1 },
  { label: 'Bureaucratic Form (Multiple Copies)', weight: 1 },
  { label: 'Outdated User Manual', weight: 1 },
  { label: 'Broken Umbrella', weight: 1 },
  { label: 'Single Chopstick', weight: 1 },
  { label: 'Cheese Grater', weight: 1 },
  { label: 'Novelty Key Ring (Loaded)', weight: 1 },
  { label: 'Spatula of Doom', weight: 1 },
  { label: 'Aggressive Balloon Animal', weight: 1 },
  { label: 'Suspiciously Heavy Sandwich', weight: 1 },
  { label: 'Stale Baguette', weight: 1 },
  { label: 'Frozen Burrito', weight: 1 },
  { label: 'Wet Cardboard Box', weight: 1 },
  { label: 'Crocs (Both)', weight: 1 },
  { label: 'Flip Flops (Armed)', weight: 1 },
  { label: 'Socks with Sandals', weight: 1 },
  { label: 'An Embarrassing Photo', weight: 1 },
  { label: 'Receipt from 2009', weight: 1 },
  { label: 'Strongly Worded Tweet (Printed)', weight: 1 },
  { label: 'One-Star Review (Framed)', weight: 1 },
  { label: 'Passive-Aggressive Post-It Note', weight: 1 },
  { label: 'Half a Pair of Scissors', weight: 1 },
  { label: 'Staple Gun (Jammed)', weight: 1 },
  { label: 'Tape Dispenser with No Tape', weight: 1 },
  { label: 'Broken Ruler', weight: 1 },
  { label: 'Chewed Pen', weight: 1 },
  { label: 'Dried-Up Marker', weight: 1 },
  { label: 'An IOU', weight: 1 },
  { label: 'Coupon for 10% Off (Expired)', weight: 1 },
  { label: 'Gift Card with Unknown Balance', weight: 1 },
  { label: 'Tiny Souvenir Spoon', weight: 1 },
  { label: 'Souvenir Snow Globe', weight: 1 },
  { label: 'Novelty Bobblehead', weight: 1 },
  { label: 'Rubber Duck (Weaponised)', weight: 1 },
  { label: 'Plastic Flamingo', weight: 1 },
  { label: 'Garden Gnome', weight: 1 },
  { label: 'Decorative Wind Chime', weight: 1 },
  { label: 'Lava Lamp', weight: 1 },
  { label: 'Vintage Telephone (Rotary)', weight: 1 },
  { label: 'Extremely Heavy Cookbook', weight: 1 },
  { label: 'Encyclopedia Volume M', weight: 1 },
  { label: 'Phone Book (Regional)', weight: 1 },
  { label: 'IKEA Instructions', weight: 1 },
  { label: 'Owner\'s Manual (Wrong Language)', weight: 1 },
  { label: 'Warranty Card (Filled Out Incorrectly)', weight: 1 },
  { label: 'Terms and Conditions (Full Printout)', weight: 1 },
  { label: 'Cookie Tin (Empty, Sewing Inside)', weight: 1 },
  { label: 'Fruitcake (Several Years Old)', weight: 1 },
  { label: 'Candy Cane (Structural)', weight: 1 },
  { label: 'Novelty Giant Candy Bar', weight: 1 },
  { label: 'Swiss Roll (Unsliced)', weight: 1 },
  { label: 'Block of Aged Parmesan', weight: 1 },
  { label: 'Wheel of Cheese', weight: 1 },
  { label: 'Baguette (Very Stale)', weight: 1 },
  { label: 'Raw Turnip', weight: 1 },
  { label: 'Artisanal Bread Loaf', weight: 1 },
  { label: 'Unopened Jar of Pickles', weight: 1 },
  { label: 'Full Bottle of Ketchup', weight: 1 },
  { label: 'Family-Size Can of Beans', weight: 1 },
  { label: 'Cast Iron Skillet', weight: 1 },
  { label: 'Le Creuset Dutch Oven', weight: 1 },
  { label: 'Wok (With Residual Heat)', weight: 1 },
  { label: 'Electric Whisk (Plugged In)', weight: 1 },
  { label: 'Immersion Blender (Running)', weight: 1 },
  { label: 'Potato Masher', weight: 1 },
  { label: 'Slotted Spoon', weight: 1 },
  { label: 'Ladle (Aggressive)', weight: 1 },
  { label: 'Tongs (Snap)', weight: 1 },
  { label: 'Salad Spinner (Launched)', weight: 1 },
  { label: 'Mandoline Slicer (Carefully)', weight: 1 },
  { label: 'Box Grater', weight: 1 },
  { label: 'Can Opener (Manual)', weight: 1 },
  { label: 'Nutcracker (Vintage)', weight: 1 },
  { label: 'Lemon Squeezer', weight: 1 },
  { label: 'Garlic Press', weight: 1 },
  { label: 'Avocado Tool', weight: 1 },
  { label: 'Egg Slicer', weight: 1 },
  { label: 'Strawberry Huller', weight: 1 },
  { label: 'Mango Splitter', weight: 1 },
  { label: 'Pineapple Corer (Ironic)', weight: 1 },
  { label: 'Corn Stripper', weight: 1 },
  { label: 'Asparagus Peeler', weight: 1 },
  { label: 'Olive Pitter (Loaded)', weight: 1 },
  { label: 'Cherry Picker', weight: 1 },
  { label: 'Bread Lame', weight: 1 },
  { label: 'Bench Scraper', weight: 1 },
  { label: 'Pastry Cutter', weight: 1 },
  { label: 'Rolling Pin (Oak, Heavy)', weight: 1 },
  { label: 'Marble Rolling Pin', weight: 1 },
  { label: 'Dough Hook', weight: 1 },
  { label: 'Piping Bag (Full, Pressurised)', weight: 1 },
  { label: 'Fondant Smoother', weight: 1 },
  { label: 'Cake Leveler', weight: 1 },
  { label: 'Bread Knife (Just the Bread Knife)', weight: 1 },
  { label: 'Steak Knife (One)', weight: 1 },
  { label: 'Butter Knife (That\'s It)', weight: 1 },
  { label: 'Dessert Spoon', weight: 1 },
  { label: 'Cocktail Umbrella (Many)', weight: 1 },
  { label: 'Toothpick (Artisanal)', weight: 1 },
  { label: 'Cocktail Stirrer', weight: 1 },
  { label: 'Sippy Cup', weight: 1 },
  { label: 'Travel Mug (Lid Slightly Off)', weight: 1 },
  { label: 'Thermos from 1987', weight: 1 },
  { label: 'Reusable Shopping Bag (Full)', weight: 1 },
  { label: 'Tote Bag (Extremely Heavy)', weight: 1 },
  { label: 'Fanny Pack (Armed)', weight: 1 },
  { label: 'Backpack (Overfull)', weight: 1 },
  { label: 'Laptop Bag (With Laptop)', weight: 1 },
  { label: 'Briefcase (Locked, Unknown Contents)', weight: 1 },
  { label: 'Umbrella (Pointy End First)', weight: 1 },
  { label: 'Walking Stick (Not Needed)', weight: 1 },
  { label: 'Collapsible Chair', weight: 1 },
  { label: 'Camping Stool (Wobbly)', weight: 1 },
  { label: 'Step Ladder (Two-Step)', weight: 1 },
  { label: 'Toilet Plunger', weight: 1 },
  { label: 'Mop (Dripping)', weight: 1 },
  { label: 'Broom', weight: 1 },
  { label: 'Dustpan and Brush', weight: 1 },
  { label: 'Window Squeegee', weight: 1 },
  { label: 'Feather Duster (Decorative)', weight: 1 },
  { label: 'Swiffer (Extended)', weight: 1 },
  { label: 'Vacuum Attachment (Hose Only)', weight: 1 },
  { label: 'Pool Skimmer', weight: 1 },
  { label: 'Leaf Blower (Petrol)', weight: 1 },
  { label: 'Garden Hoe', weight: 1 },
  { label: 'Rake', weight: 1 },
  { label: 'Trowel', weight: 1 },
  { label: 'Watering Can (Full)', weight: 1 },
  { label: 'Plastic Plant Pot', weight: 1 },
  { label: 'Overgrown Houseplant', weight: 1 },
  { label: 'Cactus (Potted, Unprotected)', weight: 1 },
  { label: 'Hanging Basket (With Bracket)', weight: 1 },
  { label: 'Gnome on a Stick', weight: 1 },
  { label: 'Wind Chime (Sonic)', weight: 1 },
  { label: 'Flamingo Lamp (Weighted Base)', weight: 1 },
  { label: 'Lava Lamp (Hot)', weight: 1 },
  { label: 'Novelty Desk Fan', weight: 1 },
  { label: 'Desk Lamp (Angle-Poise)', weight: 1 },
  { label: 'Paperweight (Suspicious)', weight: 1 },
  { label: 'Crystal Ball (Solid)', weight: 1 },
  { label: 'Snow Globe (Large)', weight: 1 },
  { label: 'Ceramic Figurine', weight: 1 },
  { label: 'Porcelain Vase', weight: 1 },
  { label: 'Trophy (Wrong Name Engraved)', weight: 1 },
  { label: 'Participation Medal', weight: 1 },
  { label: 'Certificate of Mediocrity', weight: 1 },
  { label: 'Framed Inspirational Quote', weight: 1 },
  { label: 'Novelty Calendar (Wrong Year)', weight: 1 },
  { label: 'Office Chair (On Wheels)', weight: 1 },
  { label: 'Filing Cabinet (Closed)', weight: 1 },
  { label: 'Rubber Stamp', weight: 1 },
  { label: 'Stapler (Industrial)', weight: 1 },
  { label: 'Three-Hole Punch', weight: 1 },
  { label: 'Letter Opener', weight: 1 },
  { label: 'Highlighter (Neon Yellow)', weight: 1 },
  { label: 'Marker (Permanent)', weight: 1 },
  { label: 'Whiteboard Eraser', weight: 1 },
  { label: 'Dry-Erase Marker Set', weight: 1 },
  { label: 'Laser Pointer (Red Dot)', weight: 1 },
  { label: 'Presentation Clicker', weight: 1 },
  { label: 'Mouse (Wireless, Low Battery)', weight: 1 },
  { label: 'Keyboard (Mechanical, Noisy)', weight: 1 },
  { label: 'USB Hub (Full)', weight: 1 },
  { label: 'Power Strip (All Sockets Taken)', weight: 1 },
  { label: 'Extension Lead (Fully Extended)', weight: 1 },
  { label: 'Cable Ties (Bundle)', weight: 1 },
  { label: 'Rubber Band Ball', weight: 1 },
  { label: 'Box of Paperclips', weight: 1 },
  { label: 'Correction Fluid (Wet)', weight: 1 },
  { label: 'Post-It Note Dispenser (Loaded)', weight: 1 },
  { label: 'Binder Clip (Oversized)', weight: 1 },
  { label: 'Finger of Blame', weight: 1 },
  { label: 'Pointing Stick', weight: 1 },
  { label: 'The Clue Bat', weight: 1 },
  { label: 'Literally a Wet Noodle', weight: 1 },
  { label: 'Just a Stick, Really', weight: 1 },
  { label: 'A Rock (Unspecified)', weight: 1 },
  { label: 'Slightly Bigger Rock', weight: 1 },
  { label: 'A Sharp Stone (Found)', weight: 1 },
  { label: 'The First Tool (Prehistoric)', weight: 1 },
  { label: 'Improvised Club', weight: 1 },
  { label: 'Improvised Spear (Broom Handle)', weight: 1 },
  { label: 'Improvised Bow (Garden Twine)', weight: 1 },
  { label: 'Improvised Armour (Pots and Pans)', weight: 1 },
  { label: 'Improvised Shield (Bin Lid)', weight: 1 },
  { label: 'Improvised Sword (Long Stick)', weight: 1 },
  { label: 'Improvised Flail (Sock with Something in It)', weight: 1 },
  { label: 'Improvised Hammer (Shoe)', weight: 1 },
  { label: 'Improvised Axe (Half a Chair)', weight: 1 },
  { label: 'Improvised Lance (Mop)', weight: 1 },
  { label: 'Improvised Weapon (Whatever Is to Hand)', weight: 1 },
  { label: 'The Entire Environment as a Weapon', weight: 1 },
  { label: 'Environmental Hazard (Specific)', weight: 1 },
  { label: 'Situational Advantage', weight: 1 },
  { label: 'Context-Appropriate Item', weight: 1 },
  { label: 'Nearby Object (Unspecified)', weight: 1 },
  { label: 'Whatever This Is', weight: 1 },
  { label: 'Something That Looked Like a Weapon', weight: 1 },
  { label: 'Totally Not a Weapon (It Is)', weight: 1 },
  { label: 'Plausibly a Weapon', weight: 1 },
  { label: 'Technically a Weapon in Eleven Jurisdictions', weight: 1 },
  { label: 'Not Technically Illegal', weight: 1 },
  { label: 'Legally Ambiguous Object', weight: 1 },
  { label: 'Barely a Weapon', weight: 1 },
  { label: 'Questionable Choice', weight: 1 },
  { label: 'The Judge Will Decide', weight: 1 },
  { label: 'Exhibit A', weight: 1 },
  { label: 'Exhibit B (Worse)', weight: 1 },
  { label: 'A Very Loud Voice', weight: 1 },
  { label: 'The Element of Surprise', weight: 1 },
  { label: 'Disappointment (Weaponised)', weight: 1 },
  { label: 'Unbearable Cheerfulness', weight: 1 },
  { label: 'Mild Inconvenience (Physical)', weight: 1 },
  { label: 'Sheer Audacity', weight: 1 },
  { label: 'The Power of Asking to Speak with the Manager', weight: 1 },
  { label: 'An Extremely Long Receipt', weight: 1 },
  { label: 'Loyalty Points (Printed Summary)', weight: 1 },
  { label: 'A Very Concerned Letter to Council', weight: 1 },
  { label: 'Noise Complaint Form', weight: 1 },
  { label: 'Parking Ticket (Stamped)', weight: 1 },
  { label: 'Speeding Fine (Framed)', weight: 1 },
  { label: 'Overdue Library Book', weight: 1 },
  { label: 'Accumulated Late Fees', weight: 1 },
  { label: 'Outstanding Debt (Manifested)', weight: 1 },
  { label: 'Mounting Interest', weight: 1 },
  { label: 'The Bill (Final Reminder)', weight: 1 },
  { label: 'Invoice (With Penalties)', weight: 1 },
  { label: 'Small Claims Court Summons', weight: 1 },
  { label: 'Strongly Worded Will (Updated)', weight: 1 },
  { label: 'Inheritance (Withheld)', weight: 1 },
  { label: 'The Last Piece of Cake (Taken)', weight: 1 },
  { label: 'Remote Control (Batteries Stolen)', weight: 1 },
  { label: 'Phone Charger (Wrong Cable)', weight: 1 },
  { label: 'Slightly Tangled Earphones', weight: 1 },
  { label: 'Pop-Up Ad (Printed)', weight: 1 },
  { label: 'Unskippable Pre-Roll Ad', weight: 1 },
  { label: 'Cookie Consent Form', weight: 1 },
  { label: 'Terms and Conditions (Accepted)', weight: 1 },
  { label: 'CAPTCHA of Doom', weight: 1 },
  { label: 'Please Disable Your Ad Blocker', weight: 1 },
  { label: 'Subscribe to Continue Reading', weight: 1 },
  { label: 'The Paywall', weight: 1 },
  { label: 'Password Reset Email (That Never Arrives)', weight: 1 },
  { label: 'Two-Factor Authentication (Phone Lost)', weight: 1 },
  { label: 'Security Question (Forgotten Answer)', weight: 1 },
  { label: 'Account Locked (Try Again Later)', weight: 1 },
  { label: 'Error 404', weight: 1 },
  { label: 'Loading Spinner (Forever)', weight: 1 },
  { label: 'Blue Screen of Death', weight: 1 },
  { label: 'Kunai (Novelty Keychain)', weight: 1 },
  { label: 'Shuriken (Foam)', weight: 1 },
  { label: 'Nunchucks (DVD Tutorial)', weight: 1 },
  { label: 'Tonfa (Pool Noodle)', weight: 1 },
  { label: 'Bo Staff (Parking Meter)', weight: 1 },
  { label: 'Sai (Letter Openers, Paired)', weight: 1 },
  { label: 'Kama (Pizza Cutter)', weight: 1 },
  { label: 'Wakizashi (Bread Knife)', weight: 1 },
  { label: 'Tanto (Butter Knife)', weight: 1 },
  { label: 'Naginata (Mop with Attitude)', weight: 1 },
  { label: 'Yari (Selfie Stick)', weight: 1 },
  { label: 'Ono (Axe from Monopoly)', weight: 1 },
  { label: 'Kanabo (Baseball Bat with Issues)', weight: 1 },
  { label: 'Tessen (Novelty Fan)', weight: 1 },
  { label: 'Manriki (Jump Rope)', weight: 1 },
  { label: 'Blowgun (Cocktail Straw)', weight: 1 },
  { label: 'Boomerang (Does Not Return)', weight: 1 },
  { label: 'Lasso (Extension Cord)', weight: 1 },
  { label: 'Sling (Elastic Band, Large)', weight: 1 },
  { label: 'Bola (Three Socks with Coins)', weight: 1 },
  { label: 'Net (Shopping Bag)', weight: 1 },
  { label: 'Crossbow (Rubber Band)', weight: 1 },
  { label: 'Arbalest (Upscaled Crossbow)', weight: 1 },
  { label: 'Ballista (DIY)', weight: 1 },
  { label: 'Trebuchet (Small)', weight: 1 },
  { label: 'Catapult (Rubber Band)', weight: 1 },
  { label: 'Ballista Bolt (Single)', weight: 1 },
  { label: 'Cannon Ball (Small)', weight: 1 },
  { label: 'Flintlock (Damp)', weight: 1 },
  { label: 'Musket (One Shot)', weight: 1 },
  { label: 'Blunderbuss', weight: 1 },
  { label: 'Pepperbox (Overloaded)', weight: 1 },
  { label: 'Derringer (Tiny)', weight: 1 },
  { label: 'Cap Gun (Sounds Real)', weight: 1 },
  { label: 'Water Pistol (Bleach)', weight: 1 },
  { label: 'Nerf Gun (Modified)', weight: 1 },
  { label: 'Airsoft Pistol (Legal)', weight: 1 },
  { label: 'Paintball Marker', weight: 1 },
  { label: 'Potato Gun', weight: 1 },
  { label: 'Spud Cannon', weight: 1 },
  { label: 'Tennis Ball Launcher', weight: 1 },
  { label: 'T-Shirt Cannon', weight: 1 },
  { label: 'Confetti Cannon', weight: 1 },
  { label: 'Silly String Can', weight: 1 },
  { label: 'Fire Extinguisher', weight: 1 },
  { label: 'Flamethrower (Small)', weight: 1 },
  { label: 'Smoke Grenade (Decorative)', weight: 1 },
  { label: 'Flashbang (Camera Flash)', weight: 1 },
  { label: 'Stun Gun (Novelty)', weight: 1 },
  { label: 'Cattle Prod (Repurposed)', weight: 1 },
]
