import type { FlavorLabel } from './types'

// Weapon Mastery scale: F- = could hurt themselves, mortal mid = trained specialist,
// A range = world-class weaponmaster, S+ = legendary swordsaint,
// SS-SSS = inventor of styles, Cosmic+ = post-mortal armament,
// Infinite+ = weapons beyond weapons.
export const weaponMasteryLabels: FlavorLabel[] = [
  { label: 'Could Hurt Themselves With a Stick',             weight: 4, tier: 'F-',            score: 2,   color: '#4a4a4a' },
  { label: 'Holds Blades by the Sharp End',                  weight: 4, tier: 'F',             score: 5,   color: '#5c5c5c' },
  { label: 'Drops Whatever They Pick Up',                    weight: 4, tier: 'F+',            score: 8,   color: '#6e6e6e' },
  { label: 'Once Held a Sword in a Movie',                   weight: 6, tier: 'E-',            score: 11,  color: '#6b7280' },
  { label: 'A Few Lessons',                                  weight: 6, tier: 'E',             score: 14,  color: '#9ca3af' },
  { label: 'Decent Form',                                    weight: 6, tier: 'E+',            score: 17,  color: '#d1d5db' },
  { label: 'Club-Level Practitioner',                        weight: 8, tier: 'D-',            score: 20,  color: '#92400e' },
  { label: 'Renaissance-Fair Veteran',                       weight: 8, tier: 'D',             score: 23,  color: '#b45309' },
  { label: 'Reliable in a Skirmish',                         weight: 8, tier: 'D+',            score: 26,  color: '#d97706' },
  { label: 'Regional Tournament Fighter',                    weight: 8, tier: 'C-',            score: 30,  color: '#1d4ed8' },
  { label: 'National-Level Swordfighter',                    weight: 9, tier: 'C',             score: 34,  color: '#2563eb' },
  { label: 'Multi-Weapon Specialist',                        weight: 8, tier: 'C+',            score: 38,  color: '#3b82f6' },
  { label: 'Veteran Weaponmaster',                           weight: 7, tier: 'B-',            score: 42,  color: '#065f46' },
  { label: 'Olympic Fencer / World Combat Champion',         weight: 7, tier: 'B',             score: 47,  color: '#059669' },
  { label: 'Peak Human Weapon Skill',                        weight: 7, tier: 'B+',            score: 52,  color: '#34d399' },
  { label: 'World-Class Bladesmith Fighter',                 weight: 5, tier: 'A-',            score: 57,  color: '#7c3aed' },
  { label: 'Legendary Swordmaster',                          weight: 5, tier: 'A',             score: 62,  color: '#8b5cf6' },
  { label: 'Generation-Defining Weaponmaster',               weight: 5, tier: 'A+',            score: 67,  color: '#a78bfa' },
  { label: 'Superhuman Weapon Handler',                      weight: 4, tier: 'S-',            score: 72,  color: '#b91c1c' },
  { label: 'Any Object Is a Weapon in Their Hand',           weight: 4, tier: 'S',             score: 77,  color: '#dc2626' },
  { label: 'Invents Weapons Mid-Fight',                      weight: 4, tier: 'S+',            score: 81,  color: '#ef4444' },
  { label: 'Author of Multiple Weapon Schools',              weight: 3, tier: 'SS-',           score: 85,  color: '#ea580c' },
  { label: 'Has Beaten Every Style Ever Documented',         weight: 3, tier: 'SS',            score: 88,  color: '#f97316' },
  { label: 'Considered the Standard for Their Weapon',       weight: 3, tier: 'SS+',           score: 91,  color: '#fb923c' },
  { label: 'Weapons Sing in Their Grip',                     weight: 2, tier: 'SSS-',          score: 94,  color: '#ca8a04' },
  { label: 'The Weapon Trains Them, Not the Reverse',        weight: 2, tier: 'SSS',           score: 97,  color: '#eab308' },
  { label: 'Has Forgotten More Forms Than Exist',            weight: 2, tier: 'SSS+',          score: 99,  color: '#fde047' },
  { label: 'Has Held Weapons From Forgotten Ages',           weight: 2, tier: 'Z-',            score: 101, color: '#be185d' },
  { label: 'Multiversal Weaponmaster',                       weight: 2, tier: 'Z',             score: 103, color: '#db2777' },
  { label: 'Every Reality Has a Story About Their Blade',    weight: 2, tier: 'Z+',            score: 105, color: '#ec4899' },
  { label: 'Their Stance Is the Whole Library',              weight: 1, tier: 'ZZ-',           score: 107, color: '#6d28d9' },
  { label: 'No Weapon Falls Out of Their Hands',             weight: 1, tier: 'ZZ',            score: 109, color: '#7c3aed' },
  { label: 'Weapons Choose to Be Theirs',                    weight: 1, tier: 'ZZ+',           score: 111, color: '#8b5cf6' },
  { label: 'Forms That Reality Re-Reads to Understand',      weight: 1, tier: 'ZZZ-',          score: 113, color: '#0e7490' },
  { label: 'Style That Outlives Combat Itself',              weight: 1, tier: 'ZZZ',           score: 115, color: '#06b6d4' },
  { label: 'Has Already Sheathed What You Just Drew',        weight: 1, tier: 'ZZZ+',          score: 117, color: '#22d3ee' },
  { label: 'Cosmic-Class Weaponhandler',                     weight: 1, tier: 'Cosmic-',       score: 119, color: '#0e6b8a' },
  { label: 'Wields Constellations as Blades',                weight: 1, tier: 'Cosmic',        score: 121, color: '#0891b2' },
  { label: 'Has Drawn From Galactic Sheaths',                weight: 1, tier: 'Cosmic+',       score: 123, color: '#06b6d4' },
  { label: 'Forms That Outlive Empires',                     weight: 1, tier: 'Immortal-',     score: 125, color: '#d946ef' },
  { label: 'Immortal-Class Swordmaster',                     weight: 1, tier: 'Immortal',      score: 127, color: '#ec4899' },
  { label: 'Carries Weapons No Longer Allowed to Exist',     weight: 1, tier: 'Immortal+',     score: 129, color: '#f472b6' },
  { label: 'Wields the Weapons of Divine Beings',            weight: 1, tier: 'Celestial-',    score: 131, color: '#831843' },
  { label: 'Even Gods Loan Them Their Blades',               weight: 1, tier: 'Celestial',     score: 133, color: '#9d174d' },
  { label: 'Pantheons Send Their Best to Spar — They Decline',weight: 1, tier: 'Celestial+',   score: 135, color: '#be185d' },
  { label: 'Author of Divine Combat Forms',                  weight: 1, tier: 'Godly-',        score: 137, color: '#f9a8d4' },
  { label: 'Has Sharpened Things Gods Could Not',            weight: 1, tier: 'Godly',         score: 139, color: '#f472b6' },
  { label: 'Carries the Original Sword Every Pantheon Copies',weight: 1, tier: 'Godly+',       score: 141, color: '#ec4899' },
  { label: 'Predates the Concept of Weaponry',               weight: 1, tier: 'Primordial-',   score: 143, color: '#d4d4d8' },
  { label: 'Forged the First Edge',                          weight: 1, tier: 'Primordial',    score: 145, color: '#e4e4e7' },
  { label: 'Authored Every School of Weaponry',              weight: 1, tier: 'Primordial+',   score: 147, color: '#fafafa' },
  { label: 'Absolute Weaponmaster',                          weight: 1, tier: 'Absolute-',     score: 149, color: '#7dd3fc' },
  { label: 'Weapons Cooperate Reflexively',                  weight: 1, tier: 'Absolute',      score: 151, color: '#38bdf8' },
  { label: 'Anything Held By Them Becomes Decisive',         weight: 1, tier: 'Absolute+',     score: 153, color: '#0ea5e9' },
  { label: 'Beyond the Idea of Weaponry',                    weight: 1, tier: 'Transcendent-', score: 155, color: '#84cc16' },
  { label: 'Weapons Transcend Themselves in Their Grip',     weight: 1, tier: 'Transcendent',  score: 157, color: '#65a30d' },
  { label: 'Carries Implements No Word Describes',           weight: 1, tier: 'Transcendent+', score: 159, color: '#4d7c0f' },
  { label: 'Infinite Weapon Mastery',                        weight: 1, tier: 'Infinite-',     score: 161, color: '#525252' },
  { label: 'Truly Infinite Armament',                        weight: 1, tier: 'Infinite',      score: 163, color: '#262626' },
  { label: 'Beyond Infinite Weaponry',                       weight: 1, tier: 'Infinite+',     score: 165, color: '#000000' },
]
