import type { FlavorLabel } from './types'

export const weaponMasteryLabels: FlavorLabel[] = [
  { label: 'Holds Weapon Backwards',              weight: 1, tier: 'F-',   score: 2,   color: '#555'    },
  { label: "Hasn't Hurt Themselves Yet",          weight: 1, tier: 'F',    score: 5,   color: '#666'    },
  { label: 'Swings in the Right Direction',       weight: 1, tier: 'F+',   score: 8,   color: '#777'    },
  { label: 'Basic Proficiency',                   weight: 1, tier: 'E-',   score: 11,  color: '#6b7280' },
  { label: 'Handles a Weapon Adequately',         weight: 1, tier: 'E',    score: 14,  color: '#9ca3af' },
  { label: 'Regular Combatant Caliber',           weight: 1, tier: 'E+',   score: 17,  color: '#d1d5db' },
  { label: 'Skilled Soldier Level',               weight: 1, tier: 'D-',   score: 20,  color: '#92400e' },
  { label: 'Weapon of Choice Mastered',           weight: 1, tier: 'D',    score: 23,  color: '#b45309' },
  { label: 'Multi-Weapon Versatility',            weight: 1, tier: 'D+',   score: 26,  color: '#d97706' },
  { label: 'Legendary Swordsman Class',           weight: 1, tier: 'C-',   score: 30,  color: '#1d4ed8' },
  { label: 'Tournament Champion',                 weight: 1, tier: 'C',    score: 34,  color: '#2563eb' },
  { label: 'Weapon Becomes an Extension of Self', weight: 1, tier: 'C+',   score: 38,  color: '#3b82f6' },
  { label: 'Weapon Creates Shockwaves',           weight: 1, tier: 'B-',   score: 42,  color: '#065f46' },
  { label: 'Defeats Armed Forces Alone',          weight: 1, tier: 'B',    score: 47,  color: '#059669' },
  { label: 'Technique That Defies Physics',       weight: 1, tier: 'B+',   score: 52,  color: '#34d399' },
  { label: 'Creates Art With Combat',             weight: 1, tier: 'A-',   score: 57,  color: '#7c3aed' },
  { label: 'No Defense Can Block It',             weight: 1, tier: 'A',    score: 62,  color: '#8b5cf6' },
  { label: 'Weapon and Wielder Are One',          weight: 1, tier: 'A+',   score: 67,  color: '#a78bfa' },
  { label: 'Technique Alters the Battlefield',    weight: 1, tier: 'S-',   score: 72,  color: '#b91c1c' },
  { label: 'The Weapon Fears Disappointing Them', weight: 1, tier: 'S',    score: 77,  color: '#dc2626' },
  { label: 'Could Kill a God With This',          weight: 1, tier: 'S+',   score: 81,  color: '#ef4444' },
  { label: 'Strikes That Bend Space',             weight: 1, tier: 'SS-',  score: 85,  color: '#ea580c' },
  { label: 'Weapon Transcends Physical Form',     weight: 1, tier: 'SS',   score: 88,  color: '#f97316' },
  { label: 'Strikes That Exist Outside Time',     weight: 1, tier: 'SS+',  score: 91,  color: '#fb923c' },
  { label: 'Weapon Is Now a Principle of Combat', weight: 1, tier: 'SSS-', score: 94,  color: '#ca8a04' },
  { label: 'Cannot Miss. Ever.',                  weight: 1, tier: 'SSS',  score: 97,  color: '#eab308' },
  { label: 'The Blow Lands Before It Is Thrown',  weight: 1, tier: 'SSS+', score: 99,  color: '#fde047' },
  { label: 'Casually Slices Causality',           weight: 1, tier: 'God',  score: 100, color: '#e879f9' },
]
